spyder-ide/spyder

bootstrap.py
=> PR: Fix restarting Spyder whem it was started using bootstrap.py

spyder/plugins/explorer/widgets/explorer.py
=> PR: Show hidden files in explorer and project explorer

spyder/plugins/editor/widgets/tests/test_goto.py
=> PR: Fix hanging test when not in git repository

spyder/utils/tests/test_vcs.py
As a followup on #11546, #11547, skip more tests if not building from cloned git repository
=> PR: Only test for git when in git

spyder/plugins/variableexplorer/widgets/collectionseditor.py
Reset `source_model` to update available variables after setting data (prevents showing removed variables).
Fixes #11455 
FIxes #11001 
=> PR: Reset source model from parent after setting data (Variable explorer)

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
Add handling for `PicklingError` when getting values from the kernel
Fixes #11489
=> PR: Add handling for PicklingError when getting values from the kernel

CONTRIBUTING.md, bootstrap.py, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/comms/commbase.py, spyder/__init__.py, spyder/config/utils.py, spyder/plugins/ipythonconsole/comms/kernelcomm.py, spyder/plugins/ipythonconsole/comms/tests/test_comms.py
Fixes #11471
Depends on spyder-ide/spyder-kernels#204
=> PR: Remove usage of load_exception in KernelComm and fix importing spyder-kernels subrepo

spyder/plugins/variableexplorer/widgets/arrayeditor.py
Change the title for NumPy arrays in the variable explorer
Fixes #11331 
=> PR: Change variable explorer title for NumPy object arrays

spyder/app/mainwindow.py
Remove parameter when calling the `reset_to_defaults` method.
Fixes #11586 
=> PR: Fix TypeError in `spyder --defaults`

spyder/plugins/editor/widgets/editor.py, spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
Add the option for focusing the widgets depending on the `focus_to_editor` configuration.
Fixes #11503 
=> PR: Fix focus to the editor given the focus_to_editor option

spyder/config/main.py, spyder/plugins/completion/kite/plugin.py
=> PR: Add handling for faulty Kite installations

continuous_integration/azure/install.bat, continuous_integration/azure/install.sh, continuous_integration/travis/install.sh, spyder/plugins/editor/widgets/tests/test_introspection.py
=> PR: Fix test_conda_env_activation

spyder/plugins/editor/utils/autosave.py, spyder/plugins/editor/utils/tests/test_autosave.py
Spyder's autosave system records the hash of the contents of every file which is opened or renamed in the editor, and uses this to decide whether to perform an autosave. According to the bug reports, sometimes (but rarely) a file is opened but no hash recorded, leading to a `KeyError` when autosaving. I have looked but cannot find out how and why this happens.
This PR handles the `KeyError` (more) gracefully by performing an autosave if the original hash is not recorded. This is inefficient because the autosave may not be needed and the autosave file may be the same as the original file. After the file is autosaved once, the hash of the autosave file is used and the file is only autosaved again if it differs, so it is not too inefficient. If Spyder is not quit cleanly, then the next time …
=> PR: Fix KeyError on autosave

spyder/plugins/editor/plugin.py
Register the shortcuts for the editor actions, in this way they can be changed without restarting spyder.
Fixes #11630 
=> PR: Use register_shortcut for a successful remap of cell shortcuts

spyder/plugins/editor/widgets/codeeditor.py
=> PR: Remove highlight on key release event

spyder/plugins/completion/plugin.py
This PR prevents ``textDocument/foldingRange`` requests from being ignored when files are first opened at startup.
Fixes #11671
@andfoy
=> PR: Prevent code folding from not being called on startup

.github/workflows/duplicates.yml
This adds the action to handle duplicates and add a label.
Any thoughts @ccordoba12 ?
=> PR: Add Github action to close duplicate issues

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
=> PR: Fix translations

spyder/app/tests/test_mainwindow.py, spyder/plugins/pylint/tests/test_pylint.py, spyder/plugins/pylint/utils.py, spyder/plugins/pylint/widgets/pylintgui.py
Supersedes PR #10751 by @tovogt . This should be ready to merge as-is, presuming tests pass on the CIs (as they all did locally).
Previously, the Pylint plugin (Static Code Analysis pane) would not find the correct .pylintrc configuration file (or any config file at all) when run, either in the working dir, the project dir or the home directory. Furthermore, the working directory was not set to match that of Spyder. With these improvements, which were originally implemented on my suggestion by @tovogt , the cwd is now set correctly, and more importantly the most proximate `.pylintrc` file is retrieved and used, smoothly integrated with Pylint's built-in search path: 
1. `.pylintrc` (or `pylintrc`, `pyproject.toml`, or `setup.cfg`) or in the file's directory*
2. Any `.pylintrc` (etc.) in …
=> PR: Make pylint plugin find most local .pylintrc to given file and set cwd correctly

spyder/plugins/editor/widgets/codeeditor.py, spyder/utils/tests/test_encoding.py
=> Editor: Only ask for completions when text is generated after pressing a key

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_introspection.py
Add a comparison to check if the prefix of a completion request is the response so we don't show it.
Fixes #11600 
=> PR: Do not include complete words as part of completion suggestions

spyder/api/i18n.py, spyder/api/translations.py
=> PR: Add API entry for translation utilities

spyder/config/base.py
Unfortunately its translation is quite incomplete (just 15% now). Once it's at least at 90%, we will enable it again.
=> PR: Disable Polish translation

requirements/conda.txt, spyder/tests/test_dependencies_in_sync.py
This was incorrectly removed in PR #11517.
=> PR: Restore rtree to the conda deps

spyder/plugins/variableexplorer/widgets/importwizard.py
Disable array option if `numpy.ndarray` or `numpy.array` can't be imported
Fixes #11634 
=> PR: Fix validation for import as ndarray/array

spyder/plugins/ipythonconsole/utils/kernelspec.py
Change comparison between selected python executable and `sys.executable` since the executable could be of the form `python/python.exe` or `pythonw/pythonw.exe` but chairing the same path
Part of #11819 
=> PR: Improve Python executable validation in kernelspec

spyder/plugins/ipythonconsole/comms/kernelcomm.py, spyder/plugins/ipythonconsole/plugin.py
=> PR: Increase time to detect if kernel is alive and to receive the comm config

spyder/plugins/pylint/plugin.py, spyder/plugins/pylint/tests/test_pylint.py, spyder/plugins/pylint/tests/test_pylint_config_dialog.py, spyder/plugins/pylint/widgets/pylintgui.py
Update the code of the pylint plugin to python 3
Fixes #11725 
=> PR: Update Pylint plugin to Python 3

spyder/plugins/breakpoints/plugin.py, spyder/plugins/breakpoints/widgets/breakpointsgui.py
Migrate the code under the breakpoints plugin from python 2 to python 3
Fixes #11616 
=> PR: Update Breakpoints plugin to Python 3

spyder/plugins/findinfiles/plugin.py, spyder/plugins/findinfiles/tests/test_plugin.py, spyder/plugins/findinfiles/tests/test_widgets.py, spyder/plugins/findinfiles/widgets.py
Migrate the code of find in files to Python 3
Fixes #11839 
=> PR: Update Find plugin to Python 3

spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/utils/kernelspec.py, spyder/plugins/ipythonconsole/utils/manager.py
=> PR: Fix error when restarting the kernel and restore showing kernel errors on Windows

spyder/api/completion.py
Corrected a spelling error in the api/completion.py file
Fixes null
I certify the above statement is true and correct: michelwoo
=> PR: Spelling correction

spyder/app/mainwindow.py
=> PR: Catch TypeError when handling screen change

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py, spyder/plugins/variableexplorer/widgets/collectionseditor.py, spyder/plugins/variableexplorer/widgets/dataframeeditor.py, spyder/plugins/variableexplorer/widgets/namespacebrowser.py
=> PR: Add loading indicator for the Variable Explorer

spyder/plugins/variableexplorer/widgets/collectionseditor.py
=> PR: Set data only one time after multiple removes

spyder/plugins/editor/panels/scrollflag.py
Check if block is valid before painting it and reduce code repetition.
Fixes #
=> PR: Check if block is valid before painting it in the scrollflag panel

spyder/plugins/variableexplorer/widgets/objectexplorer/attribute_model.py
Change to Exception for capturing any error related with numpy import
Fixes #11988 
=> PR: Fix OSError when importing Numpy in Object Explorer

spyder/app/tests/script_unicode.py, spyder/app/tests/test_mainwindow.py, spyder/widgets/mixins.py, spyder/widgets/tests/test_mixins.py
=> PR: Fix getting help from the console for dot objects and remove redundant info from completion hints

spyder/utils/encoding.py
=> PR: Add validation for path existence before writing to filename

azure-pipelines.yml, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/pylint/widgets/pylintgui.py, spyder/utils/tests/test_encoding.py, spyder/utils/tests/test_programs.py
=> PR: Fix error when showing Pylint output

spyder/plugins/completion/fallback/utils.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/plugins/ipythonconsole/widgets/tests/test_kernelconnect.py, spyder/widgets/github/tests/test_github_backend.py
=> PR: Prevent error when checking if prefix is valid in fallback with utf-16 characters

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
=> PR: Update translation files

spyder/plugins/explorer/widgets/fileassociations.py
Format the example in the file association dialog
Fixes #11919 
=> PR: Fix file association dialog example in settings

spyder/plugins/plots/plugin.py, spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/tests/test_plots_widgets.py
Migrate the code of plots plugin to Python 3
Fixes #12130 
I certify the above statement is true and correct:steff456
=> PR: Update plots plugin to Python 3

spyder/utils/qthelpers.py
=> PR: Display correct shortcut string on tooltips

spyder/plugins/variableexplorer/widgets/arrayeditor.py, spyder/plugins/variableexplorer/widgets/dataframeeditor.py
=> PR: Catch NameError when trying to load more data in the dataframe and array viewers

spyder/plugins/ipythonconsole/plugin.py, spyder/py3compat.py
=> PR: Patch asyncio to start Spyder with Python 3.8 on Windows

spyder/preferences/shortcuts.py, spyder/preferences/tests/test_shorcuts.py
I broke this test on a previous PR 🙃 
=> PR: Fix file tests for shortcuts

spyder/plugins/editor/panels/tests/test_scrollflag.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/explorer/widgets/tests/test_explorer.py, spyder/plugins/findinfiles/tests/test_plugin.py
Local Mac tests were failing or producing segfaults (or both). These changes seem to alleviate the problem
=> PR: Fix running fast tests locally on macOS

README.md
Update README github action badges 
=> PR: Update README build badges

spyder/app/mainwindow.py
=> PR: Save main window settings after plugin windows are closed

.github/scripts/check_skip.sh, .github/scripts/check_skip_py.sh, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
Add script to skip a build if a commit message contains either the words `[ci skip]` or `[skip ci]` 
Also added skip if no py files where changed on a PR
Right now there is no way to avoid builds from starting but once a skip is set, it will take about 20-30 seconds to finish all.
=> PR: Add skip to builds plus check for skipping if PRs do not change Python files

.github/scripts/check_skip_py.sh, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
=> PR: Only cancel previous builds on pull_request events

spyder/plugins/editor/widgets/codeeditor.py
Added docstring explaining the parameters of setup_editor() function in codeeditor.py
Fixes #10124 
=> PR: Add docstring to explain CodeEditor parameters

spyder/plugins/help/plugin.py
Add a try/except block to handle a type error when an object doesn't have arguments spec and notes.
Fixes #12287 
=> PR: Fix TypeError in the Help plugin in plain text mode

spyder/plugins/completion/languageserver/client.py, spyder/plugins/completion/languageserver/plugin.py, spyder/plugins/completion/languageserver/transport/common/producer.py, spyder/plugins/completion/languageserver/transport/stdio/producer.py, spyder/plugins/completion/languageserver/transport/tcp/producer.py
This PR enables to monitor LSP processes which run under stdio pipes, which are created by the transport layer itself, as opposed of the client itself
Fixes #
=> PR: Enable status check for stdio LSP servers

spyder/plugins/completion/kite/client.py, spyder/plugins/completion/kite/utils/status.py
=> PR: Handle string status responses in Kite due to VPN errors

spyder/plugins/editor/widgets/codeeditor.py
Added a call to document_did_change when backspace is pressed.
Fixes #12373 
=> PR: Trigger documentDidChange on backspace

spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/widgets/namespacebrowser.py, spyder/plugins/variableexplorer/widgets/collectionseditor.py, spyder/plugins/variableexplorer/widgets/namespacebrowser.py
=> PR: Make refresh namespacebrowser an interrupt call (Variable Explorer)

README.md
=> PR: Link the Contributing guide on our Readme to tell people how to run Spyder from a clone

spyder/plugins/onlinehelp/plugin.py, spyder/plugins/onlinehelp/pydoc_patch.py, spyder/plugins/onlinehelp/static/css/dark_pydoc.css, spyder/plugins/onlinehelp/static/css/light_pydoc.css, spyder/plugins/onlinehelp/widgets.py, spyder/utils/qthelpers.py, spyder/widgets/browser.py
=> PR: Fix the same font in Preferences and update action icons (Online Help)

spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/client.py
=> PR: Use runfile for external spyder-kernels

spyder/plugins/editor/widgets/codeeditor.py
Add the line counter in the code editor even if the code is folded.
**Debugger**
**Code Analysis markers**
Fixes #12321 
=> PR: Code analysis and debug markers correctly positioned when code is folded

spyder/plugins/ipythonconsole/widgets/client.py
Add try except block for AttributeError in the ipython console
Fixes #12400
=> PR: Catch AttributeError when closing a console

spyder/utils/encoding.py
This PR prevents saving files (that do not have an explicit encoding defined) as ASCII
Fixes #12416
=> PR: Encode and store UTF-8 files by default

spyder/app/tests/test_mainwindow.py
Pylint released 2.5.0 some hours ago and that version broke the test mentioned above.
=> PR: Update test_run_static_code_analysis for the latest Pylint version

spyder/plugins/editor/widgets/codeeditor.py
Check if the source is pylint before removing redundant messages
Check if the source is pylint before removing part of the completion
Fixes #11152 
=> PR: Correctly display messages from the pyls-mypy plugin

spyder/plugins/plots/widgets/figurebrowser.py, spyder/utils/icon_manager.py
Add a broken icon in the plots if the figure loaded is corrupted
(Hardcoded a division by 0 for getting the screenshot)
Fixes #12253 
=> PR: Add broken icon in the plots if the figure is corrupted

spyder/plugins/console/plugin.py, spyder/plugins/console/widgets/shell.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/variableexplorer/widgets/namespacebrowser.py, spyder/preferences/shortcuts.py
=> PR: Fix missing shortcuts on Preferences

NOTICE.txt, spyder/plugins/onlinehelp/pydoc_patch.py, spyder/plugins/onlinehelp/static/css/dark_pydoc.css, spyder/plugins/onlinehelp/static/css/light_pydoc.css, spyder/plugins/onlinehelp/widgets.py, spyder/widgets/comboboxes.py
=> PR: More improvements to Online Help

spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/widgets/calltip.py
=> PR: Hide tooltip and calltip widgets when window is not active

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
=> PR: Update translation file strings

spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/tests/test_editor.py
=> PR: Invert duplicate line down and up behaviour

.github/workflows/duplicates.yml
=> PR: Update duplicates.yml

.github/workflows/cleanup.yml, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
=> PR: Add cron job for cancelling old builds

runtests.py
* ignore external-deps directory when collecting tests
* requiring specifying 'spyder'  directory is now obsolete
Fixes #12654
@mrclary
=> PR: Ignore external-deps directory in runtests.py

RELEASE.md
=> PR: Update release instructions to include localization updates

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
=> PR: Store copy of the list representation of index and columns (Variable Explorer)

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
=> PR: Handle NaT values (Variable Explorer)

spyder/widgets/onecolumntree.py
Changed text for collapse selection, expand selection to collapse section and expand section and removed restore in code analysis pane.
Fixes #12657
Juanis2112
=> PR: Change text for collapse and expand selection and remove restore action in Code Analysis pane

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/plugin.py
Remove additional empty line at the end of the template to solve #12596 
Fixes #12596 
Juanis2112
=> PR: Remove additional empty line at the end of the template

spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/codeeditor.py
=> PR: Clone cell list to splitted editors

spyder/plugins/pylint/plugin.py
Change menu item in source menu from run static code analysis to run code analysis
Change menu item in source menu from run static code analysis to run code analysis because the name of the pane was changed. 
Fixes #12733 
Juanis2112
=> PR: Change menu item in Source menu from "Run static code analysis" to "Run code analysis"

spyder/widgets/findreplace.py, spyder/widgets/tests/test_findreplace.py
Select the length of the replacement text completely.
Fixes #12659 
=> PR: Fix selected range after "Replace Selection"

spyder/widgets/findreplace.py
Changed the text of "Replace selection" to "Replace in selection" to make it clearer as in this action the whole selection is replaced by the text entered in the text field "Replace with".
Fixes #12661 
Juanis2112
=> PR: Change text of "Replace selection" to "Replace in selection"

spyder/plugins/pylint/widgets/pylintgui.py
=> PR: Remove some odd blanks introduced in review

.github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
=> PR: Enable conda package cache in Github actions

spyder/api/exceptions.py, spyder/api/menus.py, spyder/api/plugins.py, spyder/api/preferences.py, spyder/api/toolbars.py, spyder/api/widgets/__init__.py, spyder/api/widgets/auxiliary_widgets.py, spyder/api/widgets/menus.py, spyder/api/widgets/mixins.py, spyder/api/widgets/toolbars.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/preferences/appearance.py, spyder/preferences/tests/conftest.py
=> PR: Create new API for plugins and widgets

spyder/plugins/pylint/plugin.py, spyder/plugins/pylint/tests/test_pylint.py, spyder/plugins/pylint/tests/test_pylint_config_dialog.py, spyder/plugins/pylint/widgets/pylintgui.py
Connect the `'max_entries'` option with the pylint analysis plugin. It wasn't connected to anything so that configuration didn't had any effect.
Fixes #12740 
=> PR: Fix customizing Code Analysis history

spyder/plugins/editor/plugin.py
=> PR: Use QFileDialog on OSX to open files

spyder/app/mainwindow.py
A preview of the dialog:
Fixes #12716 
=> PR: Improve detection of screen scale change by storing current dpi

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
Improved messages for missing modules in Variable Explorer: Added special messages for numpy and pandas, and another message for other missing modules. 
Pandas:
Numpy:
Other modules:
Fixes #12563 
Juanis2112
=> PR: Improve messages for missing modules in Variable Explorer

.github/workflows/duplicates.yml
Update message to be displayed in GitHub when a duplicate of #11372 is submitted to reflect that 4.1.2 (and 4.1.3) is now released.
=> PR: Update message in duplicates.yml now that 4.1.2 is available

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, external-deps/spyder-kernels/spyder_kernels/utils/nsview.py, spyder/plugins/variableexplorer/widgets/collectionseditor.py, spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py, spyder/py3compat.py
Fixes #12620 
Supersedes #12876 and spyder-ide/spyder-kernels#224
=> PR: Use UserRole to sort columns by actual value and not display value (Variable Explorer)

NOTICE.txt, setup.py, spyder/api/plugins.py, spyder/app/mainwindow.py, spyder/app/solver.py, spyder/app/tests/test_solver.py, spyder/dependencies.py, spyder/plugins/pylint/tests/test_pylint_config_dialog.py, spyder/utils/external/toposort/LICENSE.txt, spyder/utils/external/toposort/__init__.py, spyder/utils/external/toposort/toposort.py
=> PR: Add entry point plugin discovery and add plugin deps solver

spyder/config/main.py, spyder/plugins/pylint/confpage.py, spyder/plugins/pylint/plugin.py, spyder/plugins/pylint/tests/test_pylint.py, spyder/plugins/pylint/widgets/pylintgui.py
Verify if the current file is already shown in the history combobox to avoid duplicates.
Fixes #12883 
=> PR: Verify if file is already shown in the combobox to avoid duplicates (Code Analysis)

spyder/api/plugins.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/console/plugin.py, spyder/plugins/console/widgets/main_widget.py, spyder/plugins/console/widgets/shell.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/help/api.py, spyder/plugins/help/plugin.py, spyder/plugins/help/widgets.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/control.py, spyder/preferences/appearance.py, spyder/widgets/mixins.py
Fixes #12186 
Depends on #11741
=> PR: Migrate Help plugin to new API

README.md
These are just minor README changes that I noticed while reading through the GitHub page
None
=> PR: Minor fixes in Readme

spyder/api/plugins.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/console/plugin.py, spyder/plugins/editor/plugin.py, spyder/plugins/explorer/plugin.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/findinfiles/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/workingdirectory/container.py, spyder/plugins/workingdirectory/plugin.py, spyder/plugins/workingdirectory/tests/test_workingdirectory.py
=> PR: Migrate Working Directory plugin to the new API

spyder/api/widgets/__init__.py, spyder/app/mainwindow.py, spyder/plugins/onlinehelp/api.py, spyder/plugins/onlinehelp/plugin.py, spyder/plugins/onlinehelp/pydoc_patch.py, spyder/plugins/onlinehelp/tests/test_pydocgui.py, spyder/plugins/onlinehelp/widgets.py, spyder/widgets/browser.py
=> PR: Move Online help to new API 

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, spyder/app/tests/test_mainwindow.py
Add warning to avoid problems I had with micro-manager/pycro-manager#42
Basically, if you run a script that was not saved, spyder fakes a file. As there is no fork() on window, multiprocessing can't just copy the content of the memory and has to restore the state somehow. Part of doing it is to import the main file. But if the main file doesn't exist, then that will fail.
see https://github.com/spyder-ide/spyder-kernels/pull/229
Fixes #
=> PR: Add warning on console if file is not saved before running it

spyder/plugins/variableexplorer/widgets/texteditor.py
=> PR: Update window flags on text editor for macOS (Variable Explorer)

spyder/plugins/editor/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipython_config_dialog.py
If the file is in debug mode and the user tries to close that file an informative message will appear in the ipython console.
Fixes #12810
=> PR: Add message when the debug mode is on and the file cannot be closed

spyder/app/mainwindow.py, spyder/plugins/profiler/api.py, spyder/plugins/profiler/confpage.py, spyder/plugins/profiler/plugin.py, spyder/plugins/profiler/tests/test_profiler.py, spyder/plugins/profiler/tests/test_profiler_config_dialog.py, spyder/plugins/profiler/widgets/main_widget.py, spyder/preferences/tests/conftest.py
=> PR: Migrate Profiler to new API

setup.py, spyder/app/mainwindow.py, spyder/app/tests/test_solver.py, spyder/plugins/completion/languageserver/plugin.py, spyder/plugins/console/plugin.py, spyder/plugins/console/tests/test_plugin.py, spyder/plugins/console/widgets/console.py, spyder/plugins/console/widgets/main_widget.py, spyder/plugins/ipythonconsole/comms/kernelcomm.py, spyder/plugins/ipythonconsole/widgets/shell.py, spyder/preferences/tests/conftest.py, spyder/widgets/reporterror.py
This was broken after PR #12438.
=> PR: Fix reporting internal PyLS errors and generalize reporting error mechanism

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
Improve error message for loading spydata with missing dependencies
Fixes #12799 
juanis2112
=> PR: Improve error message for loading spydata with missing dependencies

spyder/api/plugins.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/history/api.py, spyder/plugins/history/plugin.py, spyder/plugins/history/tests/test_history_config_dialog.py, spyder/plugins/history/tests/test_plugin.py, spyder/plugins/history/widgets.py, spyder/plugins/onlinehelp/tests/test_pydocgui.py, spyder/preferences/appearance.py, spyder/preferences/tests/conftest.py
=> PR: Migrate History Plugin to new API

spyder/config/main.py, spyder/plugins/pylint/plugin.py, spyder/plugins/pylint/widgets/pylintgui.py
Store the filenames of the history and load them in the pylint plugin. As well as dynamically change the length of the combobox list if the user changes the `max_entries` option
Screenshot taken after restarting spyder
=> PR: Store the analyzed filenames of the Code Analysis plugin

spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/shell.py
Hide loading if a execution input was sent to the kernel (locally or remotely)
Fixes #13048
=> PR: Show console when other execution happens

spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/shell.py
=> PR: Don't interrupt the kernel when resetting namespace

spyder/plugins/help/utils/tutorial.rst
Correct spelling from "Wold" to "World"
=> PR: Fix spelling error in tutorial (Help)

spyder/plugins/console/widgets/main_widget.py
`internal_plugins` can be `{}`
Fixes #
=> PR: Fix showing internal errors

external-deps/spyder-kernels/.github/workflows/windows-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py, spyder/plugins/ipythonconsole/widgets/client.py
=> PR: Ask config after configuration

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/comms/commbase.py, external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/start.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
For the details please see spyder-ide/spyder-kernels#234
=> PR: Update spyder-kernels subrepo to fix an error with ipykernel 5.3.1

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/ipythonconsole/comms/kernelcomm.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
=> PR: Send comm config on every message to avoid TimeoutError's

spyder/plugins/findinfiles/widgets.py
Improve the context menu and behavior of the excluded combobox in the find panel
- Fix the combobox insertion when the search is triggered
- Remove actions of context menu
Fixes #13178 
=> PR: Some improvements for the Find pane

spyder/app/mac_stylesheet.qss
=> PR: Add scroll arrows fix for Qt 5.9 and 5.12

CONTRIBUTING.md
A participant in our SciPy 2020 sprint commented that our contributing guide mentions cloning the Spyder repo directly, rather forking it which is necessary to create a pull request. @juanis2112 pointed this out, and as such I've updated the Contributing guide accordingly.
I certify the above statement is true and correct: CAM-Gerlach
=> PR: Update Contributing guide to specify forking the Spyder repo

spyder/api/widgets/toolbars.py, spyder/app/mainwindow.py
=> PR: Fix toolbar title and tabify of external plugins

spyder/app/mainwindow.py, spyder/app/solver.py
=> PR: Display external plugins in the dependencies dialog

spyder/api/widgets/__init__.py, spyder/api/widgets/auxiliary_widgets.py, spyder/app/mainwindow.py, spyder/plugins/history/tests/test_plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/plots/api.py, spyder/plugins/plots/plugin.py, spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/main_widget.py, spyder/plugins/plots/widgets/tests/test_plots_widgets.py
=> PR: Move Plots to use new Plugin API

spyder/plugins/findinfiles/widgets.py
=> PR: Add check for extras_toolbar existence

.github/scripts/modules_test.sh, spyder/app/mainwindow.py, spyder/widgets/about.py
Added a Copy to Clipboard button to the About Spyder dialog as requested in fix 7844
Removed the code for the dialog from app/mainwindow.py into widgets/about.py
Converted the dialog from QMessageBox to QDialog to support the extra button.
Updated copyright date from 2019 to 2020.
Fixes #7844 
I certify the above statement is true and correct: @davidxbuck
=> PR: Add "Copy to clipboard" button to the "About Spyder" dialog

.github/workflows/binder-badge.yaml, .github/workflows/chatops-binder.yaml
There are some small errors in the binder actions I added on PR #13392.
=> PR: Fix Binder actions

.github/workflows/chatops-binder.yaml, binder/apt.txt, binder/environment.yml, binder/postBuild, binder/xfce4-panel.xml, binder/xsettings.xml
=> PR: Improve Binder installation

spyder/config/main.py, spyder/plugins/editor/widgets/editor.py, spyder/preferences/shortcuts.py
I finally spent the time to (somewhat) figure out how to use git... (a certain john smith accurately [sums up](https://stackoverflow.com/questions/25101983/can-i-revert-commits-directly-on-github#comment73500278_25102008) my feelings on using git as a full time engineer, and occasional programmer)
I also realized I somehow have two accounts on github, so please ignore the other one -_-
Fixes  #13158
=> PR: Add a "Show in external file browser" shortcut (Editor)

spyder/plugins/onlinehelp/pydoc_patch.py
Catch BrokenPipeError when trying to open a port for the online help when there's permission errors
Fixes #13388 
=> PR: Catch BrokenPipeError when trying to open a port (Online Help)

spyder/app/mainwindow.py
Some previous PR introduced duplicate entries on the preferences page for the new API plugins. 
This fixes that.
=> PR: Remove duplicate preferences pages

spyder/api/preferences.py, spyder/app/mainwindow.py, spyder/app/tests/test_solver.py, spyder/plugins/appearance/__init__.py, spyder/plugins/appearance/confpage.py, spyder/plugins/appearance/plugin.py, spyder/plugins/appearance/widgets.py, spyder/plugins/help/plugin.py, spyder/plugins/pylint/tests/test_pylint.py, spyder/preferences/configdialog.py, spyder/preferences/tests/conftest.py
=> PR: Create a new Appearance plugin

spyder/plugins/help/utils/tutorial.rst
=> PR: Fix error in tutorial (Help)

spyder/config/main.py, spyder/plugins/explorer/confpage.py, spyder/plugins/explorer/plugin.py, spyder/plugins/explorer/widgets/explorer.py, spyder/utils/qthelpers.py
=> PR: Improve Files plugin UI

spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_goto.py, spyder/plugins/projects/plugin.py
=> PR: Add file hover-go-to relative to project root

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
Updated iPython 7.17 breaks tests
Fixes #13490
=> PR: Fix failing test for IPython 7.17

spyder/plugins/variableexplorer/widgets/collectionseditor.py, spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py
=> PR: Fix error when showing dicts with mixed type keys (Variable Explorer)

.gitignore, bootstrap.py, spyder/plugins/completion/languageserver/client.py
This PR installs pyls on a external directory different to site-packages, by doing so, Spyder won't remove any user-installed pyls
Fixes #
=> PR: Install PyLS locally without modifying site-packages

spyder/plugins/onlinehelp/widgets.py
=> PR: Update placeholder text in Online Help plugin

spyder/plugins/breakpoints/widgets/main_widget.py
=> PR: Remove actions from breakpoints options menu

spyder/api/widgets/mixins.py
=> PR: Add icon to menu creation mixin

spyder/preferences/runconfig.py
Add a scrollbar to run dialogs so it can be fully visible in small screens
Fixes #13531 
=> PR: Fix height of "Run > Configuration per file" dialog by adding a scrollbar to it

spyder/plugins/pylint/widgets/pylintgui.py
Catch the `IndexError` in the pylint history
Fixes #13342 
=> PR: Handle IndexError in Pylint history

spyder/plugins/help/plugin.py
Fix a couple of messages in the help pan in the `plain text` option
Fixes #13585 
=> PR: Fix messages shown in plain text (Help)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py
Update spyder-kernels to add fix for imported modules with joblib
Fixes #13632
=> PR: Update subrepo with spyder-kernels#244

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, spyder/app/tests/test_mainwindow.py
Should pass when spyder-kernels/pull/243 is merged
Fixes #12651.
Depends on spyder-ide/spyder-kernels#243
=> PR: Add test for spyder-kernels#243

spyder/__init__.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/utils/icon_manager.py
- Added tutorial videos to help menu pointing to the playlist of spyder tutorials in Youtube 
- Removed Spyder tutorial from help menu as it is already in the help pane (and it will be removed in the future to be integrated with the docs)
- Updated link of troubleshooting guide in help menu to point to the new troubleshooting guide in docs
- Added new icon for video tutorials in help menu
Fixes #13239 
Juanis2112
=> PR: Add tutorial videos to help menu, update link to troubleshooting in docs

MAINTENANCE.md, setup.cfg
This details several things that maintainers need to know for their job.
@dalthviz, please take a look at this one.
=> PR: Add some instructions for maintainers

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/tests.txt, external-deps/spyder-kernels/setup.py, external-deps/spyder-kernels/spyder_kernels/utils/nsview.py, external-deps/spyder-kernels/spyder_kernels/utils/tests/test_nsview.py, spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py
=> PR: Update subrepo with spyder-kernels#251

spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/debugging.py
=> PR: Fix debugger panel not being updated

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
=> PR: Update subrepo with spyder-kernels#252

spyder/config/main.py, spyder/plugins/explorer/confpage.py, spyder/plugins/explorer/plugin.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/explorer/widgets/tests/test_explorer.py, spyder/plugins/projects/plugin.py, spyder/plugins/projects/widgets/explorer.py
Create the changes discussed over the file explorer pane,
Pane layout:
Filter dialog:
Hamburger menu:
Context menu:
Preferences config page:
Fixes #13465 
=> PR: Fix some UX/UI issues in the Files pane

spyder/__init__.py, spyder/app/mainwindow.py, spyder/app/tour.py
(I changed all the tips to appear to the side and not on the bottom/top of the pane because most of them didn't fit ~~but there is one that even in the side doesn't fit, still trying to fix that one.~~ (Already fixed)
Fixes #13240
=> PR: Fix technical bugs on tour

spyder/app/tour.py
Per @ccordoba12 's request, I've revised the existing tour steps to update some out of date references, fix grammar issues, improve phrasing, and add some additional content. However, I was fairly conservative and didn't add too much new stuff from our docs; @juanis2112 feel free to suggest/add additional details or further revise the text as desired.
I certify the above statement is true and correct: CAM-Gerlach
=> PR: Update, revise and copyedit existing tour steps

spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/app/tour.py, spyder/config/main.py, spyder/plugins/completion/kite/plugin.py
Changed Kite dialog to tour dialog when starting Spyder for first time.
Fixes #13832 
Juanis2112
=> PR: Change Kite dialog to tour dialog when starting Spyder for first time

spyder/config/main.py, spyder/preferences/tests/test_shorcuts.py
Added shortcuts to profiler and code analysis
- cmd+shift+R for profiler 
- cmd+shift+C for code analysis.
Fixes #13439 
Juanis2112
=> PR: Add shortcuts to Profiler and Code Analysis panes

bootstrap.py, spyder/app/cli_options.py, spyder/app/mainwindow.py, spyder/app/start.py, spyder/app/tests/test_mainwindow.py, spyder/config/base.py, spyder/config/tests/test_base.py, spyder/plugins/ipythonconsole/utils/kernelspec.py
Added safe-mode option to Spyder in non dev mode to solve issue #12631 
Fixes #12631 
TODO:
Juanis2112
=> PR: Add safe-mode option to Spyder in non dev mode

spyder/plugins/breakpoints/plugin.py
This fixes our tests in master.
=> PR: Use our convention for os.path to fix import error (Breakpoints)

installers/Windows/installer.py
Handle `python-slugify` package in the build of the Windows installer
=> PR: Update script installer to handle python-slugify package

external-deps/python-language-server/.gitrepo, external-deps/python-language-server/pyls/plugins/preload_imports.py
=> PR: Update subrepo with python-language-server#873

spyder/widgets/findreplace.py
Changed:
* Replace/find next
* Replace in selection
* Replace all
Fixes #13957
=> PR: Change replace labels in find/replace widget

spyder/plugins/ipythonconsole/utils/manager.py
=> PR: Catch an error when trying to restart the kernel (IPython console)

spyder/plugins/projects/utils/watcher.py
=> PR: Catch an error when stopping watcher (Projects)

spyder/utils/snippets/nodes.py
=> PR: Add name and value to base node class (Snippets)

installers/macOS/req-const.txt, installers/macOS/setup.py
Fixed a few bugs and updated build requirements
* `setuptools` and `pyobjc` recent releases are now compatible with the macOS application build so the environment constraints file was updated accordingly.
* A bug was fixed in which `pyls_black`, `pyls_spyder`, and `setuptools` were not installed with the bundle. These packages were recently added requirements that seem to be undetected by `py2app`
mrclary
=> PR: Update macOS app with new dependencies

.github/workflows/installer-macos.yml, installers/macOS/setup.py
Include `blib2to3` in `py2app` package option.
Fully install `spyder-kernels` and `python-language-server` to generate necessary egg-info
Fixes #14140 
@mrclary
=> PR: Resolve LSP not starting in Mac app

spyder/app/mainwindow.py
Fixed project opening when starting spyder in Mac app. 
Fixes #
Juanis2112
=> PR: Fix project opening when starting Spyder in Mac app

spyder/config/main.py
Black is the one that people have been requesting the most during the last months, so I think it's better to make it the default.
=> PR: Change default auto-formatter to be Black (Editor)

spyder/utils/check-git.sh, spyder/utils/programs.py, spyder/utils/vcs.py
Added find_git function for macOS to verify correctly if git is installed
Fixes #12045
Juanis2112
=> PR: Add find_git function to verify correctly if git is installed on macOS

spyder/utils/programs.py
Fixes https://github.com/spyder-ide/spyder/issues/14163
Fixes #
=> PR: Fix get_package_version

spyder/utils/conda.py, spyder/utils/programs.py, spyder/widgets/status.py
@steff456, the detection of environments was failing on Windows due to some small issues. Please take a look at this PR to see if it looks ok for you.
@CAM-Gerlach, could you test if this works locally for you? Thanks!
=> PR: Fix detection of conda and pyenv environments on Windows

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/start.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, external-deps/spyder-kernels/spyder_kernels/utils/misc.py
This is to check that that PR doesn't break anything here.
=> PR: Update subrepo with spyder-kernels#255

spyder/app/utils.py
This has been broken for months and no one has noticed it.
=> PR: Fix logging to a file

external-deps/python-language-server/.gitrepo, external-deps/python-language-server/pyls/plugins/flake8_lint.py, external-deps/python-language-server/test/plugins/test_flake8_lint.py, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/CHANGELOG.md, external-deps/spyder-kernels/spyder_kernels/_version.py
This should have been done while doing our release (specifically in PR #14170) but I missed it. I'll add this step to our Release instructions in a separate PR.
=> PR: Update our subrepos after releasing 4.2.0

Announcements.md, CHANGELOG.md, RELEASE.md
- This streamlines and simplifies our release instructions.
- It also fixes some errors in our Changelog and Announcements files.
=> PR: Improve release instructions

spyder/plugins/ipythonconsole/comms/kernelcomm.py, spyder/plugins/ipythonconsole/widgets/help.py, spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
Stop waiting on disconnected comms. Instead:
If interrupting: don't interrupt and send via regular channel.
If blocking: raise an error and let the calling function handle the error
Fixes #13288
=> PR: Don't wait for disconnected comm (IPython console)

.github/scripts/check_skip.sh, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
This PR fixes failures in GitHub actions related to `ACTIONS_ALLOW_UNSECURE_COMMANDS` being disabled
Fixes #
=> PR: Disable set-env usage on GitHub Actions and update conda action

spyder/plugins/variableexplorer/widgets/dataframeeditor.py, spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py
=> PR: Recalculate index when sorting (Variable Explorer)

external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/macos-tests.yml, external-deps/spyder-kernels/.github/workflows/windows-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/kernel.py
Catch the error to prevent a PermissionError, IOError and OSError.
Fixes #14100
Depends on spyder-ide/spyder-kernels#261
=> PR: Catch IOError and OSError in spyder-kernels get_cwd

spyder/plugins/pylint/main_widget.py
This was making our tests fail.
=> PR: Fix wrong import (Code analysis)

external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/macos-tests.yml, external-deps/spyder-kernels/.github/workflows/windows-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/utils/misc.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/shell.py
Remote kernel would not use `runfile` to use a script, and would not shutdown properly. This PR fixes these issues and adds tests.
Depends on spyder-ide/spyder-kernels#262
=> PR: Fix issues with external kernels runfile and shutdown

spyder/plugins/editor/utils/decoration.py
=> PR: Check for initial selection before updating decorations

.github/scripts/install.sh
New conda packages for Pyzmq 20 were uploaded yesterday, but (unfortunately) they are making our slow tests fail on Windows. I really don't know the reason.
=> PR: Use Pyzmq 19 on Windows (Testing)

spyder/plugins/editor/widgets/base.py
Catch a RuntimeError exception in the editor when a widget is already been deleted.
Fixes #13248 
=> PR: Catch RuntimeError in the editor

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
This is necessary for @juanis2112 to improve our docs for the debugger.
ccordoba12
=> PR: Sync spyder-kernels subrepo

spyder/app/tests/test_mainwindow.py, spyder/config/main.py, spyder/plugins/findinfiles/plugin.py, spyder/plugins/findinfiles/widgets.py
=> PR: Fix some issues with the Find in files plugin

spyder/app/mainwindow.py, spyder/plugins/projects/plugin.py
This bug was introduced in PR #14137.
I need to check with @juanis2112 if this doesn't introduce a regression in the Mac app.
Fixes #14348.
=> PR: Fix opening projects from the command line

installers/Windows/installer.py, installers/Windows/req-extras-pull-request.txt, installers/Windows/req-extras-release.txt, installers/Windows/req-pull-request.txt, installers/Windows/req-release.txt
Buidling the Windows installers is failing due to that.
=> PR: Pin cryptography to 3.2.1 to avoid issues with lack of wheels for version 3.3 (Windows installer)

spyder/app/mainwindow.py, spyder/plugins/projects/plugin.py, spyder/plugins/workingdirectory/container.py
I found this functionality was broken in master after testing PR #14227
=> PR: Fix changing directory when opening and closing projects

.github/scripts/install.sh, pytest.ini, spyder/app/mainwindow.py, spyder/preferences/maininterpreter.py, spyder/preferences/tests/test_config_dialog.py, spyder/utils/conda.py, spyder/utils/programs.py, spyder/utils/pyenv.py, spyder/utils/tests/test_conda.py, spyder/utils/tests/test_pyenv.py, spyder/widgets/status.py, spyder/widgets/tests/test_status.py
* Compute the list of envs every 60 seconds in a thread in the interpreter status widget. That will keep them updated.
* Cache that list to retrieve it quickly when opening our Preferences
* Add tests for the utility functions that detect environments.
* Update interpreter in status bar when it's removed outside Spyder.
TODO
Fixes #14330
=> PR: Improve detection of conda and pyenv environments

spyder/app/tour.py
Changed colors  pf background and buttons in the tour dialog for Spyder's light mode
Fixes #14203 
Juanis2112
=> PR: Change colors for tour dialog in light mode

spyder/api/preferences.py, spyder/app/mainwindow.py, spyder/plugins/maininterpreter/__init__.py, spyder/plugins/maininterpreter/confpage.py, spyder/plugins/maininterpreter/plugin.py, spyder/plugins/maininterpreter/tests/__init__.py, spyder/plugins/maininterpreter/tests/test_confpage.py, spyder/preferences/tests/conftest.py, spyder/preferences/tests/test_config_dialog.py
=> PR: Migrate Main interpreter to new plugin API

external-deps/python-language-server/.github/workflows/test-linux.yml, external-deps/python-language-server/.github/workflows/test-mac.yml, external-deps/python-language-server/.github/workflows/test-win.yml, external-deps/python-language-server/.gitrepo, external-deps/python-language-server/pyls/hookspecs.py, external-deps/python-language-server/pyls/python_ls.py, spyder/plugins/editor/utils/editor.py, spyder/widgets/findreplace.py
This PR unfolds all the nested code folding blocks when a search result lands inside of them.
Fixes #12485 
=> PR: Improve unfold_if_colapsed logic to consider nested blocks

spyder/plugins/editor/panels/scrollflag.py
Align flags if not enough lines to create a scrollbar
Before:
small:
Here, the flags are not aligned!
large:
After:
Small
The flags are aligned.
Large
Same as before.
Fixes #14263
impact27
=> PR: Align flags if not enough lines to create a scrollbar

spyder/config/gui.py, spyder/utils/syntaxhighlighters.py
=> PR: Add default values for color schemes

spyder/plugins/ipythonconsole/plugin.py
This change will show it correctly on the light theme.
=> PR: Set color of pager label (IPython console)

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/debugging.py
=> PR: Update continuation prompt

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/debugging.py
=> PR: Save prompt number while recursive debugging

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
This improves the way we detect assignments in Pdb when using our new exclamation mark mode.
Fixes #14477.
=> PR: Update subrepo with spyder-kernels#272

spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py
Pandas 1.2.0 broke a test in collectionsEditor
=> PR: Fix test compatibility with Pandas 1.2.0

installers/macOS/setup.py
* include `pandas` outside zip location
* additional build cleanup
Fixes #14542 
@mrclary
=> PR: Fix Variable Explorer pandas KeyError in macOS App

RELEASE.md
This adds several instructions that were missing from the release process and were detected when releasing 4.2.1
=> PR: Update release instructions

spyder/widgets/colors.py
Apply the suggested patch in https://github.com/spyder-ide/spyder/issues/14535
Fixes #14535 
juliangilbey
=> Fix DeprecationWarning: explicitly cast to an integer

NOTICE.txt, spyder/app/mainwindow.py, spyder/app/restart.py, spyder/app/start.py, spyder/app/tests/test_mainwindow.py, spyder/app/tour.py, spyder/plugins/completion/languageserver/plugin.py, spyder/plugins/editor/tests/test_plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/plots/widgets/figurebrowser.py, spyder/utils/stringmatching.py, spyder/utils/tests/test_programs.py, spyder/widgets/arraybuilder.py, spyder/widgets/collectionseditor.py, spyder/widgets/helperwidgets.py, spyder/widgets/pathmanager.py, spyder/widgets/tabs.py, tools/png-convert-and-optimize.sh, tools/rm_whitespace.py
=> PR: Fix spelling mistakes in comments and docstrings

spyder/plugins/editor/widgets/codeeditor.py
- That prevents a segfault after folding is updated.
- This is a follow up to PR #14574, which introduced this nasty side effect.
=> PR: Compute extended ranges for folding out of its thread (Editor)

spyder/api/widgets/menus.py, spyder/plugins/mainmenu/plugin.py
=> PR: Support dynamic menus on Mac

installers/macOS/setup.py, spyder/config/snippets.py
* I erroneously removed `spyder_kernels` from `py2app` packages in a previous merge request. This is required to be outside the zip library to work properly for internal IPython consoles on the macOS app
* I also found and corrected some invalid escape sequences which gave warnings in the pytests
@mrclary
=> PR: Fix IPython console for internal environment on macOS app

spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/config/main.py, spyder/plugins/explorer/api.py, spyder/plugins/explorer/confpage.py, spyder/plugins/explorer/plugin.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/explorer/widgets/main_widget.py, spyder/plugins/explorer/widgets/tests/test_explorer.py, spyder/plugins/explorer/widgets/tests/test_fileassociations.py, spyder/plugins/explorer/widgets/utils.py, spyder/plugins/projects/plugin.py, spyder/plugins/projects/widgets/explorer.py, spyder/plugins/workingdirectory/plugin.py
Migration of the explorer plugin to the new API
Fixes #12195 
=> PR: Migrate Files to the new API

README.md
=> PR: Update the date of copyright notice

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
This is necessary to fix the problem reported on issue #14472
Fixes #14472.
=> PR: Sync subrepo with spyder-kernels#271

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py, spyder/app/tests/test_mainwindow.py
Add test for https://github.com/spyder-ide/spyder-kernels/pull/278
Fixes #14551
=> PR: Test for spyder-kernels#278

CODE_OF_CONDUCT.md
I updated code of conduct with version 2.0 of the CONTRIBUTOR COVENANT CODE OF CONDUCT.
Fixes #
=> PR: Update code of conduct with version 2.0 of Contributor Covenant's one

spyder/plugins/editor/widgets/codeeditor.py
- That was freezing when typing fast in large files.
- I verified folding updates as expected without that code.
=> PR: Don't terminate folding thread before running new update (Editor)

spyder/plugins/variableexplorer/widgets/collectionseditor.py
This fixes the error that happens when two objects cannot be compared and groups the results in the variable explorer by the ones that can be sorted vs the ones that are not numerical or string.
Increasing order
Decreasing order
Fixes #14527
=> PR: Catch type error when sorting by size in variable explorer

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Update the `*.po` and `*.pot` files for synchronizing with Crowdin for our next release.
=> PR: Update translations for 4.2.2

installers/macOS/setup.py
Patch `py2app` template `site.py` file so that IPython `help()` works with internal IPython consoles on macOS application.
Fixes #14713
@mrclary
=> PR: Patch py2app site.py template for IPython help()

spyder/plugins/completion/kite/widgets/install.py
Remove unexpected argument in Kite installation
Fixes #14801 
=> PR: Remove unexpected argument in Kite installation dialog

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/plugin.py, spyder/plugins/findinfiles/plugin.py, spyder/plugins/findinfiles/tests/test_widgets.py, spyder/plugins/findinfiles/widgets.py
Go to the correct position from the find in files plugin
Fixes #14755
=> PR: Fix match in Find plugin

spyder/plugins/editor/panels/utils.py
This PR prevents raising errors when trying to remove a folding node that does not exist anymore.
Fixes #14835
=> PR: Prevent IndexError when updating folding

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
=> PR: Add TypeError as a Picklingerror (Variable Explorer)

.github/workflows/test-files.yml
This is a temporary workaround until we understand how to fix them with the latest version.
=> PR: Use QtAwesome 1.0.1 for the file tests

spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/projects/widgets/explorer.py
Removed "options" variable from some unused places
Fixes #
=> PR: Remove "options" variable from some unused places

spyder/plugins/editor/widgets/codeeditor.py
=> PR: Avoid segfault when processing code analysis results

spyder/app/mainwindow.py, spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po, spyder/plugins/layout/container.py
=> PR: Update translation strings

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/widgets/codeeditor.py
This fixes some segfaults in our test suite.
=> PR: Use a single QThread instance to update linting results (Editor)

spyder/app/tests/test_mainwindow.py, spyder/plugins/layout/container.py
This skips a test in Mac because it started to give segfaults.
=> PR: Fix a segfault in the test suite

.github/workflows/installer-win.yml, installers/Windows/installer.py, installers/Windows/req-extras-pull-request.txt, installers/Windows/req-pull-request.txt
=> PR: Update Windows installer script to support new Spyder internal plugins entrypoints and qdarkstyle

spyder/plugins/completion/providers/kite/provider.py, spyder/plugins/completion/providers/kite/widgets/calltoaction.py
Fixes #14888 
~It's missing the item regarding the on boarding file (that seems like is being caused since the `sig_file_open` gets emitted before being actually connected to the Editor)~
=> PR: Fix Kite issues for Spyder 5

binder/environment.yml, requirements/tests.txt, setup.py, spyder/plugins/editor/tests/conftest.py, spyder/plugins/editor/tests/test_editor_config_dialog.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/conftest.py, spyder/plugins/editor/widgets/tests/test_bookmarks.py, spyder/plugins/editor/widgets/tests/test_breakpoints.py, spyder/plugins/editor/widgets/tests/test_codeeditor_1.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/editor/widgets/tests/test_editorsplitter.py, spyder/plugins/editor/widgets/tests/test_save.py, spyder/plugins/editor/widgets/tests/test_shortcuts.py, spyder/plugins/help/tests/test_plugin.py, spyder/plugins/history/tests/test_history_config_dialog.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/profiler/tests/test_profiler.py, spyder/plugins/projects/widgets/tests/test_projectdialog.py, spyder/plugins/variableexplorer/widgets/tests/test_arrayeditor.py, spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py, spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py, spyder/widgets/tests/test_collectioneditor.py
The Python 2 days are over. No need to (try to) import the extra mock package.
=> PR: Remove extra mock package

spyder/plugins/projects/api.py
The project api `get_recent_files` now checks for `recent_files` in main project configuration section and moves it to workspace section.
Fixes #15064
@mrclary
=> PR: Check for recent_files in project's main configuration section

spyder/widgets/browser.py
Only show the context menu popup if available
Fixes #15098 
=> PR: Fix popup error in WebView

spyder/plugins/ipythonconsole/widgets/shell.py
Fixes https://github.com/spyder-ide/spyder/issues/15112
=> PR: Fix missing arg in _handle_kernel_restarted

spyder/plugins/layout/plugin.py
This fixes other errors at startup I found while testing on Windows.
=> PR: Use the right args order in get_conf/set_conf (Layout)

spyder/api/preferences.py, spyder/app/mainwindow.py, spyder/config/main.py, spyder/plugins/appearance/confpage.py, spyder/plugins/help/plugin.py, spyder/plugins/run/confpage.py
This PR fixes some issues where the preferences dialog emitted an exception due to missing arguments.
Fixes #15090
=> PR: Fix some issues when applying Run/Help settings in the Preferences dialog

spyder/app/mainwindow.py
This fixes the error when trying to load an external plugin that not inherits from SpyderDockablePlugin
=> PR: Manage loading external SpyderPluginV2 plugins

spyder/app/mainwindow.py, spyder/app/solver.py, spyder/app/tests/test_solver.py, spyder/plugins/editor/plugin.py, spyder/plugins/projects/plugin.py
Non migrated plugins where calling plugins directly through the mainwindow also the pruning of the solver now takes into account that a pruned plugin could be required for previously non-pruned plugins
Fixes #15177 
=> PR: Handle disabling completions and improve pruning (Solver)

spyder/plugins/findinfiles/widgets.py
The icon of the `FindInFilesWidget.find_action` was not updated as intented in `FindInFilesWidget.update_actions`.
Fixes #
=> PR: Correctly update search action's icon in "Find" pane

spyder/plugins/findinfiles/widgets.py
- Fix setting max number of results
- Fix saving exclude patterns
Fixes #15350 
Fixes #15345 
=> PR: Fix a couple of bugs in Find

spyder/utils/stylesheet.py
Fixes #15398
I certify the above statement is true and correct: Jean-Sébastien
=> PR: Fix minor visual glitch when hovering tabs of the Editor

spyder/plugins/completion/plugin.py, spyder/plugins/editor/plugin.py
Config updates in the completion manager for the providers were being wrapped inside a tuple
Fixes #15324
=> PR: Fix args/kwargs handling in the call_all_editorstacks signature to update completion related options for the Editor

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
This avoids setting breakpoints on non-readable files.
Fixes #15546
=> PR: Sync subrepo with spyder-kernels#291

installers/macOS/setup.py
* Moved `docutils` out of zip directory
* Included `sphinx` extensions
Fixes #15195 
Fixes #15609
@mrclary
=> PR: Fix issues related to sphinx >= 4.0 and docutils >= 0.17 in Mac installer

.github/workflows/installer-win.yml
=> PR: Update Windows assets url

binder/environment.yml, requirements/conda.txt, setup.py, spyder/dependencies.py, spyder/plugins/projects/plugin.py
* Stopped the current watcher on project switching
Fixes #14803
@mrclary
=> PR: Revert the constraint on Watchdog 2.0

spyder/widgets/tabs.py
Fixes the selected tab when right clicking
Fixes #15313
=> PR: Fixes the selected tab when right clicking

spyder/plugins/ipythonconsole/comms/kernelcomm.py
This avoids showing an unnecessary error in that case.
Fixes #15645.
=> PR: Catch an error when shutting down the comm channel (IPython console)

installers/macOS/setup.py
Updated info.plist file for macOS app for darkmode compliance
Fixes #15689
@mrclary
=> PR: Fix dark mode compliance in macOS app

spyder/plugins/editor/widgets/editor.py
This can happen under very special circumstances but the fix is really simple.
Fixes #15714.
=> PR: Catch an error when restoring files on Windows (Editor)

spyder/app/mainwindow.py, spyder/plugins/editor/plugin.py, spyder/plugins/ipythonconsole/plugin.py
Move remaining code using the IPython Console from the Mainwindow
=> PR: Remove remaining code from the mainwindow (IPython Console)

spyder/api/config/mixins.py, spyder/api/plugins.py, spyder/api/widgets/auxiliary_widgets.py, spyder/api/widgets/main_widget.py, spyder/app/mainwindow.py, spyder/config/manager.py, spyder/plugins/appearance/confpage.py, spyder/plugins/preferences/plugin.py
This changes enable Spyder to load a third party plugin that has it's own configuration. As well, some minor bugs with appearance configuration broadcasting are fixed. 
=> PR: Fix loading complex third party plugins

spyder/api/plugins.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/config/manager.py
Related to https://github.com/spyder-ide/spyder/pull/14918
=> PR: Fix unregistering plugins in new API

.github/scripts/install.sh, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
This fixes the problems with our debugger after the release of IPython 7.24
Fixes #15738.
=> PR: Sync subrepo with spyder-kernels#297

spyder/app/start.py
- Prevent showing internal logging errors.
- Prevent that our dependencies display warnings when not in debug mode
Those errors and warnings were displayed either in the console or through our error dialog, but they are not Spyder errors that users need to report here.
Fixes #15768 
Fixes #15163 
=> PR: Fix some issues with the logging module

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/start.py
Fix importing the `sys` module through `Preferences > IPython console > Startup > Lines`.
Fixes #15788.
=> PR: Sync subrepo with spyder-kernels#299

spyder/plugins/completion/providers/kite/provider.py, spyder/plugins/completion/providers/kite/utils/install.py, spyder/plugins/completion/providers/kite/utils/status.py, spyder/plugins/completion/providers/kite/widgets/calltoaction.py, spyder/plugins/completion/providers/kite/widgets/status.py
Since the future of Kite is unclear, the Kite team asked us to disable all Kite call-to-action and dialog inside Spyder if the installers were to be unavailable at any point.
Fixes #
=> PR: Disable Kite call-to-action and dialog if installers are not available

spyder/plugins/console/widgets/main_widget.py, spyder/plugins/console/widgets/shell.py, spyder/plugins/help/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/control.py, spyder/plugins/ipythonconsole/widgets/debugging.py, spyder/plugins/ipythonconsole/widgets/shell.py, spyder/plugins/plots/plugin.py, spyder/plugins/variableexplorer/plugin.py, spyder/widgets/mixins.py, spyder/widgets/tabs.py
Standardize the signals names used by the IPython Console
=> PR: Initial signals names standardization (IPython Console)

installers/macOS/setup.py
Added `pylint` to `packages` option for `py2app`.
Fixes #15885
@mrclary
=> PR: Add pylint to packages option for py2app (macOS installer)

spyder/plugins/completion/providers/kite/utils/status.py
When requests fails to connect to Internet in order to verify Kite's installers availability, it crashes Spyder on startup. This PR prevents those kinds of errors.
Fixes #15876 
=> PR: Prevent connection errors when trying to verify Kite installers

spyder/plugins/editor/widgets/codeeditor.py
=> PR: Find next character correctly (Editor)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
Thus syncs our subrepo with https://github.com/spyder-ide/spyder-kernels/pull/300, which provides the fix.
Fixes #15780 
=> PR: Fix %debug magic

external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml, external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/windows-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/CHANGELOG.md, external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- This depends on https://github.com/spyder-ide/spyder-kernels/pull/292
- It also depends on a new release of IPykernel that includes https://github.com/ipython/ipykernel/pull/704
=> PR: Fix tests for IPykernel 6

spyder/app/utils.py
Changed the size of the splash screen because it looks too big.
This is the size it is with this PR but I will post some other options in the comments.
Fixes #16006
=> PR: Change size of splash screen

.github/workflows/installer-macos.yml
The build process for our installer started to fail since this morning and I'm trying to fix it here.
=> PR: Fix failures when building macOS installers

.github/workflows/installer-win.yml, installers/Windows/installer.py
Pylint modifies the sys.path and removes from it the path to the packages included with the installer on Windows
Fixes #15452
Depends on https://github.com/spyder-ide/windows-installer-assets/pull/3
=> PR: Add modified Pylint init file to prevent modifications to sys.path

setup.cfg
Those files are not going to be part of the package, so we can safely remove them from the `check-manifest` test
=> PR: Exclude files in branding from check-manifest

spyder/plugins/editor/widgets/editor.py, spyder/plugins/variableexplorer/widgets/arrayeditor.py, spyder/plugins/variableexplorer/widgets/basedialog.py, spyder/plugins/variableexplorer/widgets/dataframeeditor.py, spyder/plugins/variableexplorer/widgets/importwizard.py, spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py, spyder/plugins/variableexplorer/widgets/texteditor.py, spyder/utils/stylesheet.py, spyder/widgets/browser.py, spyder/widgets/collectionseditor.py
Among the problems I solved in this PR we have:
- Buttons had no padding and spacing around them.
- Margins around the layout that contains buttons were zero.
- Buttons were misaligned in two rows.
**Before/After**
----
----
----
----
----
----
Fixes #15698
Fixes #15320
=> PR: Improve style of editors (Variable Explorer)

spyder/utils/stylesheet.py
Those changes broke setting the color of links, as we found out with @juanis2112.
=> PR: Revert changes that avoided to compute stylesheets when importing the stylesheet module

spyder/plugins/application/container.py
Added link to download the available update of spyder from the dialog (Only for people using the installers)
Fixes #15667 
Juanis2112
=> PR: Add link to download new installer update in dialog

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
This updates our translation strings in preparation for the upcoming release.
=> PR: Update translation strings for 5.1.0

spyder/plugins/editor/extensions/snippets.py
This catches another simple error with snippets.
Fixes #16105 
=> PR: Catch another error with snippets (Editor)

.github/workflows/installer-win.yml
=> PR: Bump Windows installer assets version

spyder/plugins/editor/widgets/codeeditor.py
Solve odd bug when using tabs and pasting code in the editor.
Fixes #16137.
=> PR: Solve error when using tabs and pasting code (Editor)

spyder/plugins/editor/widgets/codeeditor.py
- Unfortunately, the fix I came up with in #16146 was incorrect because I was not able to reproduce it.
- Today I came up with a way to do it and found the real fix.
=> PR: Really fix pasting with tabs

spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
This improves the running time of our tests in case of failures.
=> PR: Skip a flaky test on Linux and mark others as flaky

spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/utils/registries.py
- This greatly simplifies how we perform that update, which was consuming a lot of resources before.
- It also catches an error that prevented Spyder to be run through the Python profiler. That's what I used to discover this problem.
I think this helps to resolve the main problem reported on issue #15631 (at least it does on my tests). But that's hard to say because other factors could be involved.
=> PR: Simplify updating enabled state of code analysis actions (Editor)

spyder/plugins/editor/widgets/codeeditor.py
This prevents a memory leak and sluggishness in the editor after some time.
Fixes #15631
=> PR: Clear code_analysis_underline extra selections before painting new ones (Editor)

spyder/plugins/projects/api.py
Avoid overwriting the project type if it already exists.
=> PR: Avoid overwrite of existing project type

spyder/plugins/completion/plugin.py
This was a small regression introduced by PR #15629.
=> PR: Fix performing app restart when LSP goes down

spyder/plugins/completion/providers/languageserver/providers/workspace.py
Added a *method* that handles the response of the ``workspace/executeCommand`` request to the *WorkspaceProvider*.
This is required due to the current architecture of the *Completions* plugin's *lsp provider* that requires handlers to properly receive the response of the requests.
Fixes #16343
=> PR: Handle execute command response (LSP)

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py
- This was causing a freeze due to a while loop that never ended.
- I also took the opportunity to add log messages for some editing operations.
Fixes #16401
=> PR: Don't try to trim new lines for files with a single line (Editor)

external-deps/python-lsp-server/.gitrepo, external-deps/python-lsp-server/CONFIGURATION.md, external-deps/python-lsp-server/README.md, external-deps/python-lsp-server/pylsp/config/schema.json, external-deps/python-lsp-server/pylsp/plugins/_resolvers.py, external-deps/python-lsp-server/pylsp/plugins/jedi_completion.py, external-deps/python-lsp-server/test/plugins/test_completion.py
- This checks that our tests pass with the new snippets cache I proposed in the PyLSP.
- Depends on https://github.com/python-lsp/python-lsp-server/pull/83
=> PR: Check tests with new snippets cache (Completions)

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Update `*.po` files for the next release `5.2.0` translations 
=> PR: Update translations for 5.2.0

README.md
That paragraph was mentioning the work we were preparing for Spyder 4, which is very outdated now.
Fixes #16778
=> PR: Remove paragraph about Spyder 4 (Readme)

spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/utils/manager.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/debugging.py, spyder/plugins/ipythonconsole/widgets/main_widget.py, spyder/plugins/ipythonconsole/widgets/shell.py, spyder/plugins/outlineexplorer/tests/test_widgets.py, spyder/plugins/preferences/tests/conftest.py, spyder/utils/programs.py
Fixes #
Depends on https://github.com/spyder-ide/spyder/pull/16764
=> PR: Fix kernel shutdown (IPython console)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/__main__.py, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, external-deps/spyder-kernels/spyder_kernels/utils/nsview.py
- Shape of Pytorch arrays was not detected correctly (see https://github.com/spyder-ide/spyder-kernels/pull/333).
- Don't use `get` when getting values from `f_locals` (see https://github.com/spyder-ide/spyder-kernels/pull/332).
Fixes #16780
Fixes #16348
=> PR: Fix a couple of issues when running Pytorch code (IPython console)

CONTRIBUTING.md, RELEASE.md
* Some outdated references to spyder `4.x` and spyder-kernels `1.x` branches.
* Update crowdin link to sync translations
* Update `conda.txt` requirements link
=> PR: Update RELEASE.md and CONTRIBUTING.md

spyder/app/tests/test_mainwindow.py
Oddly, that test started to hang in our test suite since yesterday.
=> PR: Skip a test in our pip slots because it's hanging

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po, spyder/plugins/projects/widgets/projectdialog.py
Update missing translation strings after https://github.com/spyder-ide/spyder/pull/16847
Running `gettext-helpers` the following message appears:
```
...spyder/spyder/plugins/projects/widgets/projectdialog.py:74: Seen unexpected token "f"Select a new or existing directory to create a new Spyder ""
```
~Not sure if there is something I should do~ Changed to use `format` instead of `f-strings`
=> PR: Update missing translation strings for next release

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/client.py
=> PR: Print std stream messages in the console while starting

spyder/plugins/completion/confpage.py, spyder/plugins/console/plugin.py, spyder/plugins/layout/plugin.py, spyder/plugins/maininterpreter/plugin.py, spyder/plugins/mainmenu/plugin.py, spyder/plugins/preferences/plugin.py, spyder/plugins/shortcuts/plugin.py, spyder/plugins/statusbar/confpage.py, spyder/plugins/statusbar/plugin.py, spyder/plugins/toolbar/plugin.py, spyder/plugins/workingdirectory/plugin.py
This PR prevents the following plugins from being disabled: 
- Layout
- Main interpreter
- Main menu
- Preferences
- Shortcuts
- Status bar
- Working directory
- Toolbar
The decision was mainly because these set of plugins shouldn't be disabled since they form part of the core of the application.
=> PR: Prevent some plugins from being disabled

spyder/plugins/editor/extensions/docstring.py, spyder/plugins/editor/extensions/tests/test_docstring.py
* Fix minor style and spelling issues in that extension after #14567.
* Add regressions tests for the issues solved by that PR.
=> PR: Some improvements to the docstring extension (Editor)

spyder/api/plugin_registration/_confpage.py
This fixes an issue when trying to unpack the state of the checkbox of external plugins
=> PR: Fix error when updating the plugin checkboxes state

spyder/plugins/ipythonconsole/widgets/client.py
Filter debugger bug message as done with the message for http://bugs.python.org/issue1666807
Fixes #16927 
=> PR: Add validation to filter "Python bug https://bugs.python.org/issue1180193" message

spyder/widgets/findreplace.py
Fixes https://github.com/spyder-ide/spyder/issues/16948
=> PR: Clear highlighted matches after clearing text in find widget (Editor)

spyder/plugins/completion/providers/languageserver/conftabs/formatting.py
We incorrectly say that we support it when that's not the case.
Fixes #16964.
=> PR: Remove mention to Yapf in style and formatting preferences tab (Completions)

README.md
Use new Quansight logo in Readme.
=> PR: Update Quansight logo in Readme

spyder/app/mainwindow.py, spyder/requirements.py
Outadated validation for `spyder-kernels` version at `spyder/requirements.py`
Fixes #17005 
=> PR: Remove `check_spyder_kernels`

spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/tests/test_codeeditor.py
Fixes the highlighting of a cell. With 5.x:
Fixes #
=> PR: Fix cell highlighting (Editor)

spyder/plugins/variableexplorer/widgets/objectexplorer/tests/test_objectexplorer.py
We needed to update that test to deal with newer Python versions.
Fixes #17068.
=> PR: Fix test_objectexplorer_collection_types for Python 3.9+

spyder/plugins/findinfiles/widgets/search_thread.py
=> PR: Fix FileNotFoundError in Find plugin

spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/editor.py
Small fixes to improve compatibility with PySide 
rear1019
=> PR: Small fixes to improve compatibility with PySide

spyder/plugins/console/tests/test_plugin.py, spyder/plugins/editor/panels/tests/test_scrollflag.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/utils/stdfile.py, spyder/plugins/ipythonconsole/widgets/main_widget.py, spyder/plugins/maininterpreter/tests/test_confpage.py, spyder/plugins/onlinehelp/tests/test_pydocgui.py, spyder/plugins/variableexplorer/widgets/arrayeditor.py, spyder/plugins/variableexplorer/widgets/tests/test_arrayeditor.py, spyder/plugins/workingdirectory/tests/test_workingdirectory.py
Fix segfaults, flaky and failing tests, and tests that were not working with newer Python versions.
Fixes #17090 
Fixes #17084 
Fixes #17080 
Fixes #17069 
Fixes #17067 
Fixes #17059 
Fixes #17058 
=> PR: Fix several small issues in our test suite

spyder/plugins/editor/widgets/tests/test_introspection.py
There is one more conda-dependent test after #17095 - this protects it in the same way as the previous (updated) PR.
=> PR: Skip another conda test if this tool is not present

spyder/widgets/calltip.py
This is necessary for Python 3.10 compatibility
Fixes #17120.
=> PR: Fix an implicit float to int conversion

spyder/plugins/editor/utils/languages.py
Adding .pyz file as markdown to add support to syntex highligher for .pyz (Zen Knit)
=> PR: Add pyz file extension to be syntax-highlighted as markdown

spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py, spyder/widgets/collectionseditor.py, spyder/widgets/tests/test_collectioneditor.py
Fixes #16423. See also #17022, for which this is an identical PR but on a different branch as requested.
I certify the above statement is true and correct: Mike Battaglia and Carlos Cordoba
=> PR: Make Variable Explorer column headers movable

.github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, spyder/app/tests/test_mainwindow.py
Also add a timeout to our test Github actions workflows to prevent them running for too long.
=> PR: Skip a test on Windows because it hangs sometimes

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py
- Depends on spyder-ide/spyder-kernels#363
Fixes #16696.
=> PR: Fix error with multiprocessing when code contains classes (IPython console)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/python-27.txt, external-deps/spyder-kernels/spyder_kernels/comms/commbase.py, external-deps/spyder-kernels/spyder_kernels/utils/dochelpers.py
- This is an error generated in the kernel but that impacts the console.
- Depends on spyder-ide/spyder-kernels#364
Fixes #17144.
=> PR: Prevent an error when inserting left brackets in the IPython console

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Update translations `*.pot `and `*.po` files.
=> PR: Update translations for 5.2.2

spyder/app/tests/test_mainwindow.py, spyder/plugins/history/plugin.py, spyder/plugins/history/widgets.py
That connection was broken since the release of Spyder 5, but it was noticed only recently in StackOverflow by one of our users.
Fixes #17184.
=> PR: Restore connection between the IPython console and History

spyder/plugins/editor/panels/linenumber.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/utils/syntaxhighlighters.py
this PR:
```
>>> import timeit
>>> timeit.timeit("spy.window.editor.get_focus_widget().linenumberarea.repaint(0, 0, -1, -1)", number=1000, globals={"spy": spy})
1.000121
```
5.x
```
>>> import timeit
>>> timeit.timeit("spy.window.editor.get_focus_widget().linenumberarea.repaint(0, 0, -1, -1)", number=1000, globals={"spy": spy})
2.3169081999999968
```
2.5x faster painting of the line numbers
Fixes #
=> PR: Use static text for line numbers (Editor)

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
This avoids our test suite to hang sometimes due to that test.
=> PR: Skip a test on Mac because it started to hang

spyder/plugins/plots/widgets/figurebrowser.py
Faster show of plots in the plot plugin.
Fixes #
=> PR: Avoid looping on all thumbnails (Plots)

RELEASE.md
* Add a note regarding the update of spyder-kernels version when updating the value in the IPython Console validation
* Move 'publish announcement' step to be the last one (after conda-forge packages are ready)
=> PR: Update RELEASE.md info regarding spyder-kernels version updates

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/client.py
Fixes https://github.com/spyder-ide/spyder/issues/17252
=> PR: Fix restart when something is present in kernel's stderr file (IPython console)

binder/environment.yml, requirements/tests.txt, setup.py
This is necessary to support a more recent version of `pluggy` for the PyLSP.
=> PR: Increase Pytest required version to 6+

installers/macOS/setup.py, pytest.ini, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/onlinehelp/tests/test_pydocgui.py
- This should prevent the hangs we've been seeing lately.
- This also fixes a failure with the Mac app.
=> PR: Skip more IPython console tests because they started to hang

.github/workflows/installer-win.yml
Update bundled Python version to support compatibility with packages (pandas) newer versions.
Maybe could be worthy to have Windows installer with different Python versions bundled?
Just in case to check the Python releases: https://www.python.org/downloads/windows/
Fixes #17253 
=> PR: Bump Windows installer Python version to 3.8.10

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
Fix error with PySide2 raised when a DataFrameView is initiated. 
Fixes #17139
=> PR: Fix DataFrameView error with PySide2

.gitattributes, external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml, external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/macos-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/python-27.txt, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, external-deps/spyder-kernels/spyder_kernels/py3compat.py
- Depends on spyder-ide/spyder-kernels#374
Fixes #17289.
=> PR: Prevent error when the kernel tries to get file code from the frontend

installers/Windows/req-extras-pull-request.txt, installers/Windows/req-extras-release.txt, installers/Windows/req-pull-request.txt, installers/Windows/req-release.txt, setup.py
Bundles `spyder-terminal` with the different Windows installers
Fixes #17202 
=> PR: Add spyder-terminal to the Windows installers

spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/utils/stdfile.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/main_widget.py
Cache a kernel to avoid waiting for a new kernel to launch.
=> PR: Cache previous kernel attributes to speed up kernel launch (IPython console)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/utils/nsview.py
- Depends on spyder-ide/spyder-kernels#377
Fixes #16844.
=> PR: Fix error when getting size of dask dataframe objects (IPython console)

spyder/plugins/editor/plugin.py
I think this error happens when a completion is in progress.
Fixes #17486.
=> PR: Catch error when undocking/docking the editor

spyder/plugins/completion/plugin.py
Fix logic in completions status widgets validations (when adding or removing them)
Fixes #17262 
=> PR: Fix validations to add/remove completion status widgets

spyder/config/manager.py
Handle error when creating the `CONF` instance by showing reset config files message:
Fixes #16747 
=> PR: Prompt user to reset Spyder config files in case `CONF` instance initialization fails

spyder/plugins/editor/extensions/docstring.py
Recreate #13503 for the 5.x branch.
None.
I certify the above statement is true and correct: trollodel
=> PR: Remove the cls parameter from generated docstring (Editor)

spyder/plugins/projects/plugin.py
This avoid an error when that file is corrupt or can't be read by any other reason.
Fixes #17621
=> PR: Catch any error when reading workspace config file (Projects)

MANIFEST.in, setup.cfg
- I forgot to do this in PR #17605, so our tests started to fail.
=> PR: Skip Changelog files from manifest

spyder/app/tests/test_mainwindow.py, spyder/plugins/findinfiles/plugin.py
Also add a test so that that behavior doesn't regress in the future.
Fixes #17475.
=> PR: Give focus to Find search text widget when switching to it

spyder/plugins/outlineexplorer/widgets.py
=> PR: Remove duplicates when sorting in the outline explorer

spyder/api/plugin_registration/registry.py
=> PR: Move deleteLater calls to be done after validating plugin can be closed

installers/Windows/README.md
Add some info for the command line options available for the Windows installer
Fixes #17725 
=> PR: Add some info regarding command line arguments for the Windows installer

installers/macOS/test_app.sh, spyder/app/restart.py
Changed the executable for restarting the macOS application from `Spyder.app/Contents/MacOS/python` to `Spyder.app/Contents/MacOS/Spyder`.
Updated the `test_app.sh` script with more informative messaging.
Fixes #17731
=> PR: Change restart script for macOS app

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/main_widget.py
Some Matplotlib options where being ignored since no method was subscribed to their changes
Fixes #16297 
=> PR: Subscribe to configs for Matplotlib inline backend (IPython Console)

spyder/api/plugin_registration/mixins.py, spyder/config/main.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/main_widget.py, spyder/plugins/workingdirectory/confpage.py, spyder/plugins/workingdirectory/container.py, spyder/plugins/workingdirectory/plugin.py, spyder/plugins/workingdirectory/tests/test_workingdirectory.py
* This is for @isabela-pf and @CAM-Gerlach, so they can see the UI changes proposed to the Preferences page of the Working directory plugin:
**Before**
**After**
* And this is for @dalthviz, so he can better understand the changes proposed here when reviewing this code:
- I made the consoles working directory to be set correctly at startup and for new consoles. The previous code was trying to set it before the kernel is up, which had no effect. Furthermore, if a project is active at startup, setting the working directory to the project's one was failing due to Projects not being listed as part of the optional requirements of the IPython console (and the problem mentioned above).
- Now we raise an error if a method is decorated with `on_plugin_available` or `on_plugin_teardown`, but the …
=> PR: Fix setting working directory at startup and for new IPython consoles

spyder/plugins/ipythonconsole/widgets/main_widget.py
See commit message for details. This error has been detected while porting the Watchlist Plugin (see #16438) to Spyder v5.3.0.
rear1019
=> PR: Don’t emit `sig_shellwidget_created` before shell widget is initialized

spyder/plugins/editor/plugin.py
=> PR: Fix “Source → Show warning/error list” action (Pyside2)

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Update translations `*.pot `and `*.po` files.
=> PR: Update translations for 5.3.1

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/posix.txt, external-deps/spyder-kernels/requirements/windows.txt, external-deps/spyder-kernels/setup.py
That fixes a couple of errors while closing Spyder.
Fixes #17776.
=> PR: Increase minimal required version of jupyter_client in spyder-kernels 

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po, spyder/plugins/workingdirectory/confpage.py
There was a fix that one of our translator found in a string (Working directory config page): A missing space. Fixing that here and recompiling the translations files to resync with Crowdin.
Thank you to [beweta](https://crowdin.com/profile/beweta) for letting us know about it
=> PR: Update translations for 5.3.1 with config page fix

spyder/plugins/mainmenu/plugin.py
This makes shortcuts for actions placed in menus to be registered as expected.
Fixes #16061
=> PR: Pre-render menus in all operating systems (Main menus)

installers/Windows/req-extras-pull-request.txt, installers/Windows/req-extras-release.txt
Adds a optional dependency (`openpyxl`) to handle Excel files with `pandas` to the Windows installer that comes with `pandas`. Also adds `defusedxml` following the `openpyxl` security warning: https://openpyxl.readthedocs.io/en/stable/#security
Part of #18071
=> PR: Add `openpyxl` and `defusedxml` to the full version Windows installers

installers/macOS/packages.py
PR #18107 installed `defusedxml` and `openpyxl` into the build environment, but I forgot to add them to the actual app build.
Last bit of #18071
=> PR: Really add `defusedxml` and `openpyxl` to the Mac app build

spyder/plugins/help/utils/tutorial.rst
Update Spyder tutorial text
Fixes #13812
Fixes #13043
=> PR: Update Spyder tutorial (Help)

installers/Windows/installer.py
This will help in the development process when checking locally changes to be done over the assets side (adding/removing or updating files from https://github.com/spyder-ide/windows-installer-assets)
=> PR: Add flag to prevent downloading assets for the Windows installer script

spyder/plugins/console/widgets/main_widget.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/maininterpreter/confpage.py, spyder/plugins/profiler/widgets/main_widget.py
Change of all strings displayed to the user from "Python script" to "Python file"
Fixes https://github.com/spyder-ide/ux-improvements/issues/29
I certify the above statement is true and correct: @jsbautista
=> PR: Change of all strings displayed to the user from `Python script` to `Python file`

spyder/plugins/completion/providers/kite/utils/status.py
On mac, every time a file is opened, Spyder checks if kite is installed. This is quite time consumming and not likely to change often. I therefore propose to cache the result of the search to avoid increasing the file loading time.
Fixes #
=> PR: Cache validation of local Kite installation on Mac

installers/Windows/README.md
A guide to create Spyder windows Installer was added
Added instructions to generate the installer
I certify the above statement is true and correct:@jsbautista
=> PR: Update instructions to build the Windows installer

installers/macOS/setup.py, spyder/__init__.py, spyder/widgets/about.py, spyder/widgets/reporterror.py
The Spyder version text in the About dialogue and the issue reporter now includes the Spyder installer type (standalone, conda, or pip).
Additionally, the IPython console environment is optionally included (in detail view) when submitting issues to GitHub from the issue reporter.
If included, the environment list will be the result of `python -m pip list` if it is a non-conda environment and the result of `conda list --prefix <env-path>` if it is a conda environment.
The versions text for "Copy version info" in the About dialogue and in the issue reporter are consolidated to one function.
Example "Copy version info"
* Spyder version: 5.4.0.dev0 744e2ab2b (conda)
* Python version: 3.10.4 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.4
* Operating System: Darwin 20.6.0 …
=> PR: Add installer and environment info to issue reporter

spyder/config/lsp.py
This avoids showing results coming from that plugin when users install it on their own.
Fixes #17701.
=> PR: Disable pyls-flake8 plugin (Completions)

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Update translations `*.pot` and `*.po` files for the upcoming Spyder 5.3.2 release
=> PR: Update translations for 5.3.2

spyder/plugins/ipythonconsole/widgets/debugging.py
- This is infrequent but when it happens it prevents users to create consoles, which is very serious.
- In that case, I think it's better to skip the functionality we have to save the history of Pdb commands.
Fixes #18531.
=> PR: Catch errors when creating or accessing Pdb history (IPython console)

.github/workflows/installer-macos.yml, .github/workflows/installer-win.yml, .github/workflows/test-files.yml
Installers ignore changes to other installers.
test-files.yml workflow ignores changes to installers.
=> PR: Restrict unnecessary workflows when only installer files are changed.

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/namespace_manager.py, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, spyder/app/tests/test_mainwindow.py
- Add tests for https://github.com/spyder-ide/spyder-kernels/pull/395
Fixes #
=> PR: Add tests for running namespace

.github/workflows/installer-macos.yml, .github/workflows/installer-win.yml, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, installers/Windows/README.md, installers/Windows/installer.py
* Change default URL for Windows installer assets to be the latest release available on the `window-installer-assets` repository
=> PR: Change default installers assets download URL (Windows)

installers/Windows/installer.py
Code to copy all NSIS plugins into discoverable path
I certify the above statement is true and correct: @jsbautista
=> PR: Copy all NSIS plugins into discoverable path

spyder/plugins/application/confpage.py
Fix issue where `macOS_group` was referenced before assignment.
Fixes #18597
=> PR: Fix issue where macOS_group was referenced before assignment (Preferences)

spyder/plugins/editor/widgets/codeeditor.py
Fix merge of https://github.com/spyder-ide/spyder/pull/16988
Fixes #
=> PR: Remove remaining call to `update_extra_selections` (Editor)

.github/workflows/installer-macos.yml, installers/macOS/codesign.sh, installers/macOS/qt_webengine.xml
Added `com.apple.security.cs.disable-executable-apge-protection` entitlement to QtWebEngineProcess.app
Fixes #18776
=> PR: Fix issue where QtWebEngineProcess was not working properly in signed macOS app

spyder/app/tests/test_mainwindow.py, spyder/plugins/framesexplorer/widgets/main_widget.py
=> PR: Close memory leak in master

spyder/app/tests/test_mainwindow.py
=> PR: Fix `test_leaks` on master

.github/workflows/installer-macos.yml, .github/workflows/test-mac.yml, spyder/plugins/maininterpreter/tests/test_confpage.py
- See: https://github.com/actions/virtual-environments/issues/5583
* Move Mac installer workflow to Mac 11
* Move Mac test suite to Mac 12
=> PR: Use Mac 12 to run tests on CIs and Mac 11 for the standalone app

external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/macos-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/start.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/404
Fixes #18856
=> PR: Add a test for plotting from the Variable Explorer while debugging

spyder/app/tests/test_mainwindow.py, spyder/plugins/debugger/widgets/main_widget.py, spyder/plugins/editor/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/main_widget.py
=> PR: Move debug buttons to the Debugger plugin

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py
=> PR: Prevent triggering Dask tasks when getting variables properties (IPython console)

spyder/plugins/ipythonconsole/widgets/client.py
=> PR: Add PYDEVD debug warning message to benign errors (IPython Console)

spyder/plugins/ipythonconsole/widgets/debugging.py, spyder/plugins/ipythonconsole/widgets/main_widget.py
Keep focus in shellwidget while debugging unless explicitly asked.
For example, if `Maintain focus in the editor` is enabled and the user is using the debugger button, keep the focus in the editor.
If the user is typing in the console, keep the focus in the console.
Fixes #19042
=> PR: Keep focus in shellwidget while debugging

spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/completion.py
Also remove some unnecessary imports and variables.
Fixes #19109.
=> PR: Catch an error when creating new editor windows

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Update translations `*.pot` and `*.po` files for the upcoming Spyder 5.3.3 release
=> PR: Update translations for 5.3.3

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/main_widget.py
Previously the `get_current_client` or `get_current_shellwidget` methods were used to get new created clients, however that could cause some operations to be done in a different client if multiple clients are being created. So for example, if files `a.py` and `b.py` are requested to be run from the Files pane, a client is created to execute file `a.py` but ends up being run in a new console created initially to run file `b.py`
Fixes #15405 
=> PR: Ensure correct client and shellwidget are used to execute code in new consoles when multiple scripts are run at the same time (IPython Console)

spyder/app/mainwindow.py
This avoids an error when that plugin is not available.
Fixes #19172
=> PR: Validate that Layout plugin exists in `moveEvent` method (Main Window)

installers/macOS/packages.py
Fix issue where py2app does not include all formatters for pygments=2.13.
Fixes #19236
=> PR: Add Pygments to the list of packages placed out of the zipped library (Mac app)

spyder/app/tests/test_mainwindow.py, spyder/config/main.py, spyder/images/dark/debug_selection.svg, spyder/images/light/debug_selection.svg, spyder/plugins/debugger/plugin.py, spyder/plugins/debugger/widgets/main_widget.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/shortcuts/tests/test_shortcuts.py
=> PR: Add a debug current line or selection button

.github/workflows/installer-macos.yml
This fixes an error while building it, probably because older Python versions don't support the latest Mac version used on Github actions.
=> PR: Use a more recent Python version for our Mac app

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/shell.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/client.py
- Goes with https://github.com/spyder-ide/spyder-kernels/pull/413
Fixes #19355
=> PR: Remove polling std streams

spyder/plugins/editor/widgets/codeeditor.py
I don't know under what circumstances this could happen, but it was reported that it does, so we need to address it.
Fixes #19514
=> PR: Prevent error when trying to update folding info (Editor)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/posix.txt, external-deps/spyder-kernels/requirements/tests.txt, external-deps/spyder-kernels/requirements/windows.txt, external-deps/spyder-kernels/setup.py, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/utils/nsview.py, spyder/plugins/ipythonconsole/widgets/namespacebrowser.py, spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
- Depends on spyder-ide/spyder-kernels#416.
- Also improve message when an unknown error occurs while retrieving a variable from the console; and stop Variable Explorer spinner if that's the case.
Fixes #19516
Fixes #19145 
Fixes #19026 
=> PR: Fix some errors when computing the namespace view and a memory leak with the Matplotlib Qt backend (IPython console)

spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/api.py, spyder/plugins/editor/panels/tests/test_scrollflag.py, spyder/plugins/editor/widgets/tests/conftest.py, spyder/plugins/editor/widgets/tests/test_completions_hide.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/kernelconnect.py, spyder/widgets/github/gh_login.py, spyder/widgets/tests/test_collectioneditor.py, spyder/widgets/tests/test_findreplace.py
Various Fixes to improve compatibility with PySide2. This time some fixes for tests are included: We have looked into running the testsuite with PySide2 and this PR contains “low-hanging fruit” fixes. There are still failures which we haven’t looked into yet (we possibly will some day).
rear1019
=> PR: Fixes to improve compatibility with PySide2

spyder/app/tests/test_mainwindow.py, spyder/plugins/base.py, spyder/plugins/layout/plugin.py
- This was a regression introduced in #18928.
Fixes #19374.
=> PR: Fix keyboard shortcut to switch to the Editor

installers/macOS/req-build.txt
=> PR: Pin black to 22.8.0 (Mac app)

bootstrap.py
When launching from bootstrap, detects whether the root branch has changed to/from master, in which case spyder is reinstalled in editable mode.
Fixes #19728
=> PR: Reinstall spyder in editable mode in bootstrap if branch changed to/from master

spyder/plugins/ipythonconsole/widgets/client.py
=> PR: Add benign error 'The following argument was not expected' (IPython Console)

spyder/plugins/console/widgets/shell.py
This was causing a crash at startup.
Fixes #19850.
=> PR: Catch any error while reading Internal Console history file

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po, spyder/plugins/application/container.py, spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
- Fix issues at the Application plugin container and the IPython Console plugin namespacebrowser widget
- Update translations  `*.pot` and `*.po` files for the upcoming Spyder 5.4.0 release
=> PR: Update translations for 5.4.0

spyder/plugins/ipythonconsole/confpage.py
Large values make Spyder quite sluggish according to what was reported in issue #19091.
Fixes #19091 
=> PR: Set a much lower max value for buffer size (IPython console)

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/plugin.py
`handle_current_filename` should not take any arguments
Fixes #
=> PR: Fix handle current filename

.github/workflows/installers-conda.yml
=> PR: Do not build experimental installer for win-64 on release

README.md, RELEASE.md
Update docs for binder related elements
Fixes #19902
=> PR: Update binder link and add instructions when releasing new versions to keep it updated

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/posix.txt, external-deps/spyder-kernels/requirements/windows.txt, external-deps/spyder-kernels/setup.py, external-deps/spyder-kernels/spyder_kernels/console/kernel.py
Update spyder-kernels subrepo
Fixes #19874
=> PR: Update `spyder-kernels` subrepo to include constraint and fixes for `ipykernel` 6.16.1

spyder/plugins/profiler/widgets/main_widget.py
disables save button if no profile loaded yet
disables load and clear button while profiling is running
add default extension if no extension given on save dialog
Fixes #19633 
Fixes #6444
I certify the above statement is true and correct: Florian Maurer
=> PR: Fixes profiler extension and buttons

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/conftest.py, spyder/plugins/editor/widgets/tests/test_decorations.py, spyder/plugins/editor/widgets/tests/test_editorsplitter.py, spyder/plugins/editor/widgets/tests/test_save.py
See commit messages for details
rear1019
=> PR: Fix some LSP issues

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 5.4.1 release
=> PR: Update translations for 5.4.1

.github/workflows/installer-macos.yml, .github/workflows/installer-win.yml, .github/workflows/installers-conda.yml, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
This is necessary now that our Heroku bot is not working anymore.
=> PR: Cancel runs in progress when pushing new commits (CI)

external-deps/python-lsp-server/.github/workflows/static.yml, external-deps/python-lsp-server/.github/workflows/test-linux.yml, external-deps/python-lsp-server/.github/workflows/test-mac.yml, external-deps/python-lsp-server/.github/workflows/test-win.yml, external-deps/python-lsp-server/.gitrepo, external-deps/python-lsp-server/pylsp/plugins/pycodestyle_lint.py, external-deps/python-lsp-server/pyproject.toml, external-deps/python-lsp-server/test/plugins/test_pycodestyle_lint.py, spyder/plugins/editor/widgets/codeeditor.py
- Depends on https://github.com/python-lsp/python-lsp-server/pull/319
- Also fix error when restarting LSP servers, which was introduced by #20047.
Fixes #19565 
=> PR: Fix Pycodestyle linting with line endings other than LF (Completions)

spyder/plugins/editor/utils/autosave.py
This can be annoying for users and doesn't give any relevant information to them.
Fixes #20286 
=> PR: Avoid showing a `logger.error` message when auto-saving (Editor)

spyder/plugins/editor/widgets/editor.py
Also improve style of revert message.
Fixes #20284
=> PR: Catch error when trying to revert unexisting files (Editor)

.github/workflows/installer-macos.yml, .github/workflows/installers-conda.yml, spyder/utils/environ.py
* Ensure that `pcregrep` bash command is available
* Fix workflow logic for `build-installers` job of conda-based installer workflow
* Temporary fix for #20097. A better fix for #20097 will be implemented by #20106
Fixes #20291
Fixes #20097 
=> PR: Fix installer issues and bug when getting environment variables

spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/widgets/mixins.py
- This is a regression introduced by #20226.
- Add tests for dot completions  and the case solved by #20226.
- Improve code style of several `if` blocks in the editor.
Fixes #20285.
=> PR: Fix automatic completions after a dot is written next to a module

spyder/utils/programs.py
- The previous code didn't validate that the working directory was not `None`, which led to errors.
- Improve code readability a bit.
Fixes #20398.
=> PR: Fix check for UNC working directory path when running code in external terminals

.github/scripts/install.sh
This is a small regression introduced after PR #20425 was merged to `master`.
=> PR: Replace mamba command with micromamba in CI install script (Testing)

spyder/utils/programs.py
* Fix priority for `pyenv`
* Add `mambaforge` and `miniforge`
* Reprioritize `anaconda` and `miniconda`
=> PR: Update conda search paths to include mambaforge and miniforge

spyder/plugins/pythonpath/plugin.py
Add missing `return` statement
rear1019
=> PR: Fix error in public API of Python Path Manager

spyder/plugins/maininterpreter/plugin.py
Add a method that could be accessed from other plugins to set the current Python interpreter used by Spyder
Part of https://github.com/spyder-ide/spyder-env-manager/issues/11 and https://github.com/spyder-ide/spyder-env-manager/pull/13
=> PR: Add public API method to set custom interpreter (Main interpreter)

spyder/plugins/run/container.py, spyder/plugins/run/plugin.py
- This is not needed after #20557.
=> PR: Remove API method that's no longer necessary (Run)

.github/workflows/installers-conda.yml
* Artifacts uploaded on pull request and "Build as release candidate" manual triggers, not on actual releases. Assets are uploaded on release.
* Added text files for sha256sum results for Linux and Windows artifacts. These are uploaded as artifacts on "Build as release candidate" manual triggers and release assets on release. This is not performed for pull requests.
Fixes #20536
=> PR: Add sha256sum to release assets

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/shell.py
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/446.
- See that PR for more context.
=> PR: Fix debugger tests with the latest version of IPykernel

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 5.4.3 release
=> PR: Update base translation strings for 5.4.3

spyder/app/tests/test_mainwindow.py
Some changes were necessary to make that test work for the new Run architecture.
=> PR: Fix `test_clickable_ipython_tracebacks`

installers/Windows/req-extras-pull-request.txt, installers/Windows/req-extras-release.txt, installers/macOS/req-extras.txt
Remove constraint for PyZMQ since the compatibility issues whit version > 25 were fixed upstream
Part of #20742 
=> PR: Remove constraint for PyZMQ < 25 (Installers)

.github/scripts/install.sh, external-deps/python-lsp-server/.gitrepo, external-deps/python-lsp-server/pylsp/_utils.py, external-deps/python-lsp-server/pylsp/plugins/autopep8_format.py, external-deps/python-lsp-server/pylsp/plugins/definition.py, external-deps/python-lsp-server/pylsp/plugins/jedi_rename.py, external-deps/python-lsp-server/pylsp/plugins/pydocstyle_lint.py, external-deps/python-lsp-server/pylsp/plugins/references.py, external-deps/python-lsp-server/pylsp/plugins/rope_rename.py, external-deps/python-lsp-server/pylsp/plugins/yapf_format.py, external-deps/python-lsp-server/pylsp/python_lsp.py, external-deps/python-lsp-server/pylsp/workspace.py, external-deps/python-lsp-server/pyproject.toml, external-deps/python-lsp-server/test/fixtures.py, external-deps/python-lsp-server/test/plugins/test_definitions.py, external-deps/python-lsp-server/test/plugins/test_references.py, external-deps/python-lsp-server/test/plugins/test_yapf_format.py, external-deps/python-lsp-server/test/test_workspace.py
This will help us to ensure that completions and linting are working as expected before releasing the next version of that package and Spyder 5.4.3.
=> PR: Sync latest changes in PyLSP

RELEASE.md
* Adds more details for the manual run of workflows and updates the way to mark a release candidate version
=> PR: Update `RELEASE.md` following 5.4.3 release experience

installers-conda/build_installers.py, installers-conda/resources/post-install.sh
* Remove installer option to initialize the conda environment. See https://github.com/spyder-ide/spyder/issues/20001#issuecomment-1510448472
* Revise `uninstall-spyder` to prompt user for confirmation before uninstalling.
=> PR: Remove installer option to initialize the conda environment and misc improvements

spyder/plugins/editor/plugin.py
Missing validation to prevent saving as Editor bookmarks `None`
Fixes #20885
=> PR: Prevent saving `None` value as Editor bookmarks

spyder/plugins/ipythonconsole/utils/kernelspec.py
See https://github.com/spyder-ide/spyder/issues/20800#issuecomment-1518442321
Fixes #20800 
=> PR: Add `-Xfrozen_modules` flag to prevent Python incorrectly compiled message (IPython Console)

Announcements.md
Fixed typo in hmtl to html
Fixes #
=> PR: Fix typo in Announcements.md

external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml, external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/macos-tests.yml, external-deps/spyder-kernels/.github/workflows/windows-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/tests.txt, external-deps/spyder-kernels/setup.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, external-deps/spyder-kernels/spyder_kernels/utils/tests/test_nsview.py
This prevents errors while debugging Plotly code and makes our debugger faster too.
Fixes #20639.
Part of #20571.
=> PR: Disable IPython's debugger skip functionality by default (IPython console)

binder/environment.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/setup.py, requirements/main.yml, setup.py, spyder/dependencies.py
This is necessary to fix the following problems in the IPython console.
- Error when sending an inspect request for Dataframes to kernel.
- Lack of code completions for second level modules.
Fixes #20871
Fixes #20816
=> PR: Skip more buggy IPython versions

spyder/plugins/editor/panels/linenumber.py
=> PR: Fix line number painting when wrap text option is active (Editor)

.github/workflows/installers-conda.yml
This is necessary for now because the Apple ID we were using for this is expired.
=> PR: Skip notarization of our Mac app (Installers)

MANIFEST.in, RELEASE.md, setup.cfg
This was an oversight of mine in alpha1.
=> PR: Remove Spyder 5 changelog from tarball

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/posix.txt, external-deps/spyder-kernels/requirements/windows.txt, external-deps/spyder-kernels/setup.py
- This was fixed in https://github.com/ipython/ipykernel/pull/1125, which is part of IPykernel 6.23.2.
- We increased our requirement to that version in Spyder-kernels to get the fix.
Fixes #21017.
=> PR: Fix showing a PyZMQ warning when filtering warnings

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 5.4.4 release
=> PR: Update translations for 5.4.4

.github/workflows/installers-conda.yml
Update installers to use Python 3.10
=> PR: Update installers to use Python 3.10

.github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_editor.py
Not doing that left incorrect highlighted results when moving from file to file.
=> PR: Rehighlight found results in the editor when switching between files

scripts/org.spyder_ide.spyder.appdata.xml
Update appdata to include content-rating, url, and releases.
Re-opened PR to submit to 5.x
This change add more information to appdata. This appdata are used by distributors to enhance their metadata.
This is part of an effort to ship Spyder to Flathub.
https://github.com/spyder-ide/spyder/issues/6898
https://github.com/flathub/flathub/pull/4344
Fixes #
I certify the above statement is true and correct: Kavin Teenakul
=> PR: Update `spyder.appdata.xml` to include more info

spyder/plugins/editor/widgets/editorstack/editorstack.py
Continue work started at https://github.com/spyder-ide/spyder/pull/13260 by cherry-picking the commits there on top of latest master
Supersedes https://github.com/spyder-ide/spyder/pull/13260
Fixes #10815
=> PR: Add copy absolute and relative paths to file context menu (Editor)

spyder/plugins/pylint/utils.py
We were not actually catching those errors, so they were leaked to our error report dialog.
Fixes #21218.
=> PR: Catch errors when trying to detect the pylintrc file (Code Analysis)

binder/environment.yml, requirements/linux.yml, requirements/main.yml
Part of https://github.com/spyder-ide/spyder/issues/21257
Fixes #4120 (for conda installations using the conda-forge channel)
=> PR: Add `fzf` and `fcitx-qt5` as conda requirements

spyder/plugins/application/container.py, spyder/utils/conda.py
Offer to download installer for macOS and Windows, regardless of current installation type.
We currently do not offer a stable release Linux installer, so the message for Linux users remains unchanged.
Here is the latest proposed messaging. Please reply if there are any errors or new suggestions.
<details><summary>Windows & macOS</summary>
- <details><summary>If Spyder is a standalone app</summary>
- Dialog 1
* Spyder <new_ver> is available! (you have <cur_ver>)
* Would you like to automatically download and install it?
* For more information...
* "Check for updates at startup" checkbox
* Buttons: Yes | No
- Dialog 2 (not applicable)
</details>
- <details><summary>If Spyder is a conda installation</summary>
- Dialog 1
* Spyder <new_ver> is available! (you have <cur_ver>)
* Would you like …
=> PR: Change updater messaging to promote our installers

RELEASE.md, spyder/plugins/ipythonconsole/__init__.py
Prevent IPython Console hanging showing the loading message due to `spyder-kernels` version validation
=> PR: Update `RELEASE.md` instructions and bump `spyder-kernels` version used in the IPython Console validations

setup.py
I forgot to do that in PR #21335.
=> PR: Bump `python-lsp-server` version when using Spyder in dev mode

spyder/plugins/editor/confpage.py
**Before**
**After**
Fixes #21359.
=> PR: Add link to Sphinx type of docstrings in Editor's config page

spyder/utils/syntaxhighlighters.py
- Instead of doing it unconditionally, now we try to detect if they are used in match/case conditions.
- Also, remove some unnecessary code and improve code style a bit here and there.
**Before**
**After**
Fixes #21239.
=> PR: Improve syntax highlighting of match/case keywords (Editor)

spyder/plugins/application/container.py, spyder/utils/conda.py, spyder/utils/tests/test_conda.py, spyder/workers/tests/test_update.py, spyder/workers/updates.py
- Check for updates in the conda channel from which Spyder was installed.
- Use `channeldata.json` to make that process faster.
- Improve error messages when it's not possible to check for updates.
- Use PyPI json info to check for updates when not in conda or Spyder was installed from PyPI in a conda env.
- Improve tests related to updates.
- Improve message informing that an update is available.
* Make dialog non-modal to not interrupt users except for our installers because they require user intervention.
* Make initial line to be a header (specifically `h3`), so that it has more prominence.
* Remove text about current version because it adds too much info to the message.
* Add more space between header and command paragraph.
* Add more space between command paragraph and footer text. …
=> PR: Improve mechanism to check for updates and message that informs about them

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 5.5.0 release
=> PR: Update translations for 5.5.0

spyder/config/base.py
See PR #21451 for the details.
=> PR: Backport PR #21451 (Fix interface language auto-configuration)

scripts/org.spyder_ide.spyder.appdata.xml
Use the name element in a developer block instead, as recommended by appstreamcli 1.0.0.
Use the `name` element in a `developer` block instead, as recommended by `appstreamcli` 1.0.0.
This fixes all warnings when validating the AppData XML file, although there are still informational messages:
```
I: org.spyder_ide.spyder:32: developer-id-missing
The `developer` element is missing an `id` property, containing a unique string ID for the
developer. Consider adding a unique ID.
I: org.spyder_ide.spyder:~: content-rating-missing
This component has no `content_rating` tag to provide age rating information. You can generate
the tag data online by answering a few questions at https://hughsie.github.io/oars/
✔ Validation was successful: infos: 2, pedantic: 2
```
**N/A**
By submitting this Pull …
=> PR: Fix deprecated top-level `developer_name` in AppData XML (Linux)

spyder/plugins/help/utils/conf.py
=> PR: Fix not displaying math equations in the Help pane

spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/externalterminal/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/pythonpath/container.py, spyder/plugins/pythonpath/plugin.py, spyder/plugins/pythonpath/widgets/pathmanager.py
- Improve its style by:
- Avoiding hover in headers by using QLabels for them.
- Rewording a bit text shown in it description.
- Align description label and list widget to the left.
- Remove folder icons because they don't additional info.
- Use config options instead of conf files to save paths.
- Fix passing our additions to `sys.path` to external terminals. This was a regression introduced by PR #17467.
- Expand tests to check that paths are added in the right order and removed when unchecked from the dialog.
**Before**
**After**
Fixes #20129.
Fixes #19182. …
=> PR: Some improvements to the Pythonpath plugin

spyder/plugins/pythonpath/utils.py
The regex that this PR fixes was not quoted correctly; this PR fixes the quoting.
=> PR: Fix regex quoting

spyder/plugins/editor/widgets/editorstack/editorstack.py, spyder/plugins/editor/widgets/editorstack/tests/test_save.py
For the Editor save message box, replaced button text: "Yes" -> "Save", "No" -> "Discard".
Additionally, replaced "Yes to All" and "No to All" buttons with "Apply to all" checkbox. This checkbox is present only if more than 1 file has unsaved changes. The last screen shot shows the button configuration for multiple unsaved files _before_ this PR.
The cancel button text on Linux is cut off and seems to be a result of including icons in the button. I don't know if this plagues other message box buttons in Spyder on Linux. But this may need to be resolved in another PR.
Fixes #21482
and …
=> PR: Update button text for editor changed files message box

.github/workflows/installer-macos.yml, .github/workflows/installer-win.yml, .github/workflows/installers-conda.yml, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
Updated checkout and cache to address notice `Node.js 16 actions are deprecated`
=> PR: Update actions to checkout@v4 and cache@v4 (CI)

.github/workflows/installer-macos.yml, .github/workflows/installer-win.yml, .github/workflows/installers-conda.yml
Update to download-artifact@v4 and upload-artifact@v4
=> PR: Update to download-artifact@v4 and upload-artifact@v4 (CI)

spyder/plugins/tours/tours.py
A string we show in the tour was not marked as in need of translation. 
Fixes #21849.
=> PR: Add missing string for translation (Tours)

RELEASE.md
Add some details regarding the need to build source distribution and wheel from a Linux machine to prevent files with permissions errors. See #21892 and #14494
Also, update names over the installers rc build/check section.
=> PR: Update `RELEASE` notes regarding sdist/wheel building and update installers section

spyder/plugins/debugger/panels/debuggerpanel.py
Prevent trying to use `None` value in the editor debugger panel when painting
Fixes #21468 
=> PR: Add validation for `editor.sideareas_color` over debugger panel

spyder/plugins/ipythonconsole/widgets/main_widget.py
Follow up of PR #21947 for master.
=> PR: Fix getting IPython version for external conda environments (IPython console)

spyder/plugins/ipythonconsole/scripts/conda-activate.bat
Fix issues to use the bundle micromamba executable on Windows when installing the installer for all the users due to path having spaces while also taking into account that the conda env could have spaces in its path too.
Fixes #21960
=> PR: Fix micromamba based kernel env activation (IPython console)

.github/workflows/installer-win.yml
Upload to releases the Window installer with the new naming scheme to try to mitigate update errors from remaining Windows installers installations from versions 5.5.1 to 5.5.3
Fixes #22001
=> PR: Add step to upload Windows installer following new naming format on release (CI)

.github/workflows/build-subrepos.yml, .github/workflows/installers-conda.yml
Update installers to use Python 3.11
Fixes #22068
=> PR: Use Python 3.11 for our installers

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.0 release
=> PR: Update translations for 6.0.0 

spyder/widgets/collectionseditor.py, spyder/widgets/tests/test_collectioneditor.py
A couple of tests were failing due to that release.
Fixes #
=> PR: Fix failing tests due to Numpy 2.0 (Testing)

spyder/plugins/profiler/widgets/main_widget.py
=> PR: Fix profiling results being hidden (Profiler)

spyder/plugins/application/widgets/about.py
|    Tab     |Before|After|
|-|-|-|
|Overview|![image](https://github.com/user-attachments/assets/90a06cb7-9141-49c7-8525-73effc6e9f82)|![image](https://github.com/user-attachments/assets/7e7efd64-a323-4610-926f-dcc6884edb0b)|
|Community|![image](https://github.com/user-attachments/assets/1d7e9e58-4af9-4e7b-b7a5-b763a4ab5c94)|![image](https://github.com/user-attachments/assets/cc836715-2624-4b25-bcfa-eadb24fd7f5f)|
|Legal|![image](https://github.com/user-attachments/assets/7296dcea-8a8f-43d8-8080-3099da45da54)|![image](https://github.com/user-attachments/assets/21d9e52e-c740-4d08-9a5f-f6063ccc5bac)|
Fixes #22180 …
=> PR: Increase about dialog width to prevent cutting text on Windows (Application)

.github/workflows/installers-conda.yml
This reverts commit 89166a4c6f9a122f01a9c0f108227327f478a13b, reversing changes made to ae1e2787879692ba79930b48f4a63a7011a08967.
Revert #22269
=> PR: Revert PR 22269 (Disable signing Mac app)

.github/workflows/installers-conda.yml
Ensure that local conda channel exists, even for releases and even if empty.
=> PR: Always create the local conda channel on CI, even for releases

spyder/plugins/explorer/widgets/explorer.py
- Remove odd capitalization in several strings.
- Don't translate "Git commit" because it makes little sense in languages other than English.
Fixes #21959.
=> PR: Improve text of several strings for translation (Files/Projects)

spyder/api/shellconnect/main_widget.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/utils/client.py, spyder/plugins/ipythonconsole/utils/kernel_handler.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/main_widget.py, spyder/plugins/remoteclient/api/client.py, spyder/plugins/remoteclient/api/jupyterhub/__init__.py, spyder/plugins/remoteclient/api/protocol.py, spyder/plugins/remoteclient/api/ssh.py, spyder/plugins/remoteclient/plugin.py, spyder/plugins/remoteclient/widgets/container.py
Update the connection status and reset all connection-dependent properties when the connection is lost. Also, try to reconnect to the server and reconnect to the kernel if a remote console is opened.
=> PR: Handle remote connection lost (Remote client)

spyder/utils/environ.py
Fixed missing `#` in shabang line in `user-env.sh`
=> PR: Fix typo in shebang line in `user-env.sh`

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.0 release following latest changes/strings additions/changes
=> PR: Update translations for 6.0.0 (extra strings)

installers-conda/build-environment.yml, installers-conda/build_installers.py
Update `menuinst` to version 2.1.2.
=> PR: Update menuinst version for file-type association (Installers)

CONTRIBUTING.md, external-deps/qtconsole/.github/workflows/linux-tests.yml, external-deps/qtconsole/.github/workflows/macos-tests.yml, external-deps/qtconsole/.github/workflows/windows-tests.yml, external-deps/qtconsole/.gitignore, external-deps/qtconsole/.gitrepo, external-deps/qtconsole/docs/source/changelog.rst, external-deps/qtconsole/docs/source/conf.py, external-deps/qtconsole/qtconsole/ansi_code_processor.py, external-deps/qtconsole/qtconsole/console_widget.py, external-deps/qtconsole/qtconsole/frontend_widget.py, external-deps/qtconsole/qtconsole/jupyter_widget.py, external-deps/qtconsole/qtconsole/mainwindow.py, external-deps/qtconsole/qtconsole/tests/test_00_console_widget.py, external-deps/qtconsole/qtconsole/tests/test_ansi_code_processor.py, external-deps/qtconsole/qtconsole/tests/test_comms.py, external-deps/qtconsole/qtconsole/tests/test_jupyter_widget.py, external-deps/qtconsole/requirements/environment.yml, external-deps/qtconsole/setup.py
This is necessary before releasing a new Qtconsole version to check everything is fine here.
Fixes #
=> PR: Update Qtconsole subrepo

RELEASE.md, changelogs/Spyder-6.md
- Add to Changelog the most important improvements from the last alpha and beta releases.
- Also, add instructions necessary to release a new major version.
Fixes #
=> PR: Update user-facing Changelog for Spyder 6.0

changelogs/Spyder-6.md
This addresses some minor issues I found after checking the changes I did in PR #22397.
=> PR: Minor fixes to Spyder 6 Changelog

.github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
- Tests are not running in that branch because they are not marked to run on it.
- Also, remove old `4.x` branch from our tests.
Fixes #
=> PR: Update workflows to run in the `6.x` branch (CI)

spyder/__init__.py
That correctly reflects what the next version is going to be.
Fixes #
=> PR: Fix development version

scripts/org.spyder_ide.spyder.appdata.xml
Update metadata for release date and version in org.spyder_ide.spyder.appdata.xml
This simply keep the version and release date update for any service that use the appdata file.
Fixes #
Kavin Teenakul
=> PR: Update org.spyder_ide.spyder.appdata.xml

spyder/utils/environ.py
- Spyder was freezing at startup if launched in the background on Linux (i.e. with `spyder &`). And that happened when trying to get the current env vars using a separate script.
- However, that's not really necessary because, when launched in a system terminal, Spyder will inherit the terminal env vars. 
- Fortunately, `psutil` allows us to easily detect when a process is launched from a terminal. And if that's the case, we simply use `os.environ` as the current env vars.
Fixes #22415. …
=> PR: Don't use script to get env vars if Spyder is launched from a terminal (Utils)

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.1 release following latest changes/strings additions/changes
=> PR: Update translations for 6.0.1

spyder/app/mainwindow.py
It's unclear when this error happens but the fix was easy.
Fixes #22514
=> PR: Prevent error when unmaximizing plugins (Main window)

RELEASE.md
Add step to RELEASE.md file to update `org.spyder_ide.spyder.appdata.xml` as discussed over https://github.com/spyder-ide/spyder/pull/22474#issuecomment-2357213156
Supersedes PR #22529
=> PR: Add step to `RELEASE.md` to update metadata files (`org.spyder_ide.spyder.appdata.xml`)

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
Update `Changelog`, `Announcements` and metadata files for 6.0.1
=> PR: Update `Changelog`, `Announcements` and metadata files for 6.0.1

Announcements.md, changelogs/Spyder-6.md
- Improve order of fixes from most critical/important to least.
- Add some missing fixes.
- Improve wording a bit here and there.
=> PR: Some improvements to Changelog and Announcements for 6.0.1

.github/workflows/automerge.yml, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
This will help to merge backport PRs automatically in the `6.x` branch.
=> PR: Add `automerge` workflow for automatic merges (CI)

.github/workflows/automerge.yml
- Add version, which is required by Github.
- Increase number of retries and sleep time between them to cover how long it takes to run our test suite.
=> PR: Try to fix `automerge` action (CI)

spyder/plugins/layout/api.py
Some odd errors show up if we don't do this.
Fixes #22584.
=> PR: Dock all undocked plugins before applying a layout

spyder/plugins/profiler/widgets/main_widget.py
Fix setting of working directory in Profiler plugin.
Note: The error has been found after making some custom changes to Spyder. I couldn’t reproduce the error in upstream Spyder.
rear1019
=> PR: Fix setting of working directory in Profiler plugin

.github/workflows/installers-conda.yml, installers-conda/resources/post-install.sh
* Fix issue where aliases could not be written to rc files if they were symbolic links
* Fix issue where NSIS logging flag was not respected on Windows
=> PR: Minor updates to the installer

external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml, external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/macos-tests.yml, external-deps/spyder-kernels/.github/workflows/windows-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/README.md, external-deps/spyder-kernels/spyder_kernels/_version.py, external-deps/spyder-kernels/spyder_kernels/utils/iofuncs.py, external-deps/spyder-kernels/spyder_kernels/utils/tests/test_iofuncs.py, setup.py, spyder/plugins/ipythonconsole/__init__.py
- We can do this because we now use a better development version in the spyder-kernels stable branch.
- Also, remove an unnecessary condition in `setup.py` related to that.
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/514
=> PR: Simplify min/max required versions of spyder-kernels in the stable branch (IPython console)

.github/workflows/purge-cache.yml, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-remoteclient.yml, .github/workflows/test-win.yml
Workflow cache is purged every Sunday at 4:10 UTC.
All unit tests are then run on the latest master commit.
This will result in testing environments being resolved and cached, and verified with possible updates to indirect dependencies.
=> PR: Purge workflow cache weekly

spyder/app/tests/test_mainwindow.py, spyder/config/tests/test_base.py, spyder/config/utils.py, spyder/plugins/completion/providers/languageserver/client.py, spyder/plugins/editor/widgets/codeeditor/tests/test_introspection.py, spyder/plugins/editor/widgets/editorstack/editorstack.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/maininterpreter/tests/test_plugin.py, spyder/plugins/pylint/main_widget.py, spyder/plugins/pylint/tests/test_pylint.py, spyder/plugins/updatemanager/widgets/update.py, spyder/plugins/updatemanager/workers.py, spyder/utils/tests/test_conda.py
Replaced `spyder.config.utils.is_anaconda` with `spyder_kernels.utils.pythonenv.is_conda_env`
=> PR: Replace `is_anaconda` with `is_conda_env`

install_dev_repos.py
When Spyder is installed in editable mode, `.dist-info` is created instead of `.egg-link`.
This breaks the test for whether Spyder is installed in editable mode. The test is updated to accommodate `.dist-info` by checking for `editable` in the `direct_url.json` file in `.dist-info`.
=> PR: Update installing developer repos to accommodate dist-info

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.2 release following latest changes/strings additions/changes
=> PR: Update translations for 6.0.2

.github/workflows/installers-conda.yml, RELEASE.md, installers-conda/build_installers.py
Also, update instructions to update Spyder-kernels before a new release. That's necessary now that we're using a backporting workflow. 
=> PR: Mention that we need to publish release candidates for stable versions in release instructions

RELEASE.md
Improve version update instructions- Follow up of #22771 (https://github.com/spyder-ide/spyder/pull/22771#issuecomment-2448561178)
=> PR: Improve version update instructions on `RELEASE.md`

.github/workflows/test-mac.yml, .github/workflows/test-win.yml
This should run our test suite faster given the many performance improvements from the last releases.
Fixes #
=> PR: Update Python versions used for testing on Windows and Mac (CI)

binder/apt.txt, binder/environment.yml
=> PR: Use `jupyter-remote-desktop-proxy` for binder setup (Binder)

spyder/plugins/appearance/confpage.py
See https://github.com/spyder-ide/spyder/issues/22492#issuecomment-2430449984
Fixes #22492 
=> PR: Handle error when trying to get invalid/unavailable custom syntax highlighting themes (Appearance)

spyder/utils/conda.py
This error was mentioned in https://github.com/spyder-ide/spyder/issues/23061#issue-2686198460
Fixes #
=> PR: Fix small error in `get_spyder_conda_channel` (Utils)

spyder/plugins/ipythonconsole/tests/conftest.py, spyder/plugins/ipythonconsole/utils/style.py, spyder/plugins/ipythonconsole/widgets/shell.py
See https://github.com/spyder-ide/spyder/pull/22965#issuecomment-2502686900
Follow-up for #22965
=> PR: Use style functions from `spyder-kernels` (IPython Console)

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.3 release following latest changes/strings additions/changes
=> PR: Update translations for 6.0.3

spyder/plugins/tours/plugin.py
This checks what plugins area available before registering the intro tour, which prevents errors while showing it.
Fixes #22635 
=> PR: Remove from intro tour steps for unavailable plugins (Tours)

RELEASE.md
Some minor things that could be changed that I noticed while following the instructions to do https://github.com/conda-forge/spyder-feedstock/pull/209
=> PR: Minor improvements to `RELEASE.md` release candidate section

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
=> PR: Update Changelog, Announcements and metadata files for 6.0.3

spyder/plugins/remoteclient/api/client.py, spyder/plugins/remoteclient/widgets/connectionstatus.py
- Report that the connection failed to be established in several places where we were not doing it before.
- Improve several logger messages that were confusing (e.g. reporting errors as warnings).
- Separate log messages with a small vertical space when displaying them to make them easier to read. 
Improved log messages and small vertical space between them
**Before**
**After**
Fixes #
=> PR: Improve reporting status and logger messages (Remote client)

spyder/plugins/ipythonconsole/widgets/control.py, spyder/widgets/mixins.py
=> Backport PR #23316 on branch 6.x (PR: Prevent Chinese input method to block edit input area

spyder/plugins/editor/widgets/editorstack/editorstack.py
Fix shortcut stop debugger
The "stop" shortcut is registered in the editor so it can be used directly from it
Fixes #22673 
@jsbautista
=> PR: Fix shortcut stop debugger

external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml, external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/shell.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
=> Backport PR #23477

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/widgets/main_widget.py, spyder/plugins/run/container.py
This functionality was working at some point but it's broken in the new Run architecture.
Fixes #23076.
=> PR: Fix Re-run cell when the last executed cell is not in the current file (Run)

spyder/plugins/appearance/widgets.py
Add validation for theme color changes. A message box was added to display invalid colors
Preview:
Fixes #22970 
@jsbautista
=> PR : Add validation for theme color changes (Preferences)

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.4 release following latest changes/strings additions/changes
=> PR: Update translations for 6.0.4

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.4 release following latest changes/strings additions/changes
=> PR: Update translations for 6.0.4 (part 2)

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
=> PR: Update Changelog, Announcements and metadata files for 6.0.4

spyder/plugins/ipythonconsole/widgets/main_widget.py, spyder/utils/conda.py, spyder/utils/pyenv.py, spyder/utils/tests/test_conda.py
=> PR: Show environments with the same name in different paths in the `New console in environment` menu

spyder/plugins/ipythonconsole/widgets/client.py
Fixes #spyder-ide/spyder#23726
=> PR: Add string that contains `UNC` to benign errors (IPython console)

.github/workflows/test-linux-qt6.yml
- This is a small follow-up PR to fix the workflow added in #23118.
Fixes #
=> PR: Fix workflow to run tests with PyQt6 (CI)

conftest.py, spyder/app/tests/test_mainwindow.py
=> Backport PR #23788 on branch 6.x (PR: Fix some issues in our test suite (CI))

.github/workflows/duplicates.yml, spyder/plugins/editor/tests/test_plugin.py, spyder/plugins/editor/widgets/codeeditor/codeeditor.py, spyder/plugins/editor/widgets/codeeditor/lsp_mixin.py
Fix code folding in cloned editors, like the ones shown in new editor windows and split panels.
Fixes #23622 
@jsbautista
=> PR: Fix code folding in cloned editors (Editor)

spyder/plugins/tours/widgets.py
Close tour when lose focus
Fixes #23516 
@jsbautista
=> PR: Close tour when it loses focus

.github/workflows/test-linux-qt6.yml, .github/workflows/test-linux.yml, .github/workflows/test-remoteclient.yml
- See https://github.com/actions/runner-images/issues/11101
- That's why our tests will be failing today.
Fixes #
=> PR: Update Ubuntu to 22.04 because the 20.04 image will be removed (CI)

.github/workflows/test-linux.yml, .github/workflows/test-remoteclient.yml
=> Backport PR #23876 on branch 6.x (PR: Update Ubuntu to 22.04 because the 20.04 image will be removed (CI))

spyder/plugins/ipythonconsole/utils/kernelspec.py, spyder/utils/conda.py
Validate conda version and raise an error as needed. See https://github.com/spyder-ide/spyder/issues/22554#issuecomment-2691844623
A preview of the messages:
Fixes #23595
Fixes #22554 
=> PR: Add validation for conda version, raise error if using version <4.9 and if conda executable can't be detected (IPython Console)

spyder/plugins/ipythonconsole/utils/kernelspec.py
A preview:
Part of #23558 
See https://github.com/spyder-ide/spyder/issues/23558#issuecomment-2707561132
=> PR: Add message for Pixi created envs when conda executable is not found (IPython Console)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/conftest.py, external-deps/spyder-kernels/requirements/tests.txt, external-deps/spyder-kernels/setup.py, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, external-deps/spyder-kernels/spyder_kernels/utils/tests/test_iofuncs.py
- This checks that the changes in https://github.com/spyder-ide/spyder-kernels/pull/534 don't break our tests here.
Fixes #
=> PR: Check async changes to debugger completions (IPython console)

changelogs/Spyder-6.md
=> PR: Update Changelog for 6.1.0a1

spyder/plugins/debugger/widgets/framesbrowser.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/run/plugin.py, spyder/utils/vcs.py
Various minor fixes, see commits for details
rear1019
=> PR: Various minor fixes

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.5 release following latest changes/strings additions/changes
=> PR: Update translations for 6.0.5

spyder/widgets/comboboxes.py
Fix search and replace case sensitivity and history in editor 
Fixes #23597
@jsbautista
=> PR: Fix case sensitivity and history when searching and replacing text in the Editor

spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/projects/widgets/main_widget.py
- This is a follow-up of #23965 to display a more specific text for that option.
- Also, skip some tests on Windows and Mac that started to fail too much.
Fixes #
=> PR: Improve text of option to search files in the switcher (Projects)

spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/projects/widgets/main_widget.py
=> Backport PR #24026 on branch 6.x (PR: Improve text of option to search files in the switcher (Projects))

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.5 release following latest changes/strings additions/changes
=> PR: Update translations for 6.0.5 (part 2)

.github/FUNDING.yml, README.md, scripts/org.spyder_ide.spyder.appdata.xml, spyder/plugins/application/widgets/appeal_page/dark/index.html, spyder/plugins/application/widgets/appeal_page/light/index.html
- The new page is now live in: https://www.spyder-ide.org/donate 
- The purpose of this PR is to include a link to it in our in-app appeal message, Readme, appdata metadata and funding.yml links.
Fixes #
=> PR: Change donations link from Open Collective to our own page

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
=> PR: Update Changelog, Announcements and metadata files for 6.0.5

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
Backport PR https://github.com/spyder-ide/spyder/pull/24051 on branch 6.x (PR: Update Changelog, Announcements and metadata files for 6.0.5)
=> Backport PR #24051 on branch 6.x (PR: Update Changelog, Announcements and metadata files for 6.0.5)

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py, spyder/widgets/tests/test_collectioneditor.py
Raise the maximum of digits for converting an int to a string to 32,767. Since Python 3.11, converting int with too many digits to a string throws an error to prevent denial-of-service attacks. This leads to an error when editing a large int in the Variable Explorer.
When the user tries to edit an int with more than 32,767 digits, a dialog box is displayed explaining that the value is too large.
The number 32,767 was chosen because that is the maximum length of the QLineEdit that is used to edit an int.
Fixes #21751 …
=> PR: Fix editing of large ints in the Variable Explorer

spyder/app/tests/test_mainwindow.py
=> Backport PR #24042 on branch 6.x (PR: Skip some tests to make the suite more reliable (CI))

spyder/config/utils.py, spyder/plugins/layout/container.py
=> Backport PR #24009 on branch 6.x (PR: Disable fullscreen mode when running on WSL (Layout))

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/code_runner.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
=> Backport PR #24105 on branch 6.x (PR: Respect case sensitivity of working directory when running code (IPython console))

spyder/plugins/application/widgets/status.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/layout/container.py
- I missed that in my review of #24095.
- I also included a couple of small style fixes that I missed in other PRs.
Fixes #
=> PR: Use link to our webpage for donations when no web widgets are available (Application)

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
Improve error message
Fixes #23378
@jsbautista
=> PR: Improve message when trying to view object with an attribute that references a generator

spyder/plugins/ipythonconsole/widgets/client.py
Add matplotlib error to benign messages
Fixes #24153
@jsbautista
=> PR: Add Matplotlib font cache message to benign errors (IPython console)

spyder/plugins/appearance/confpage.py
=> PR: Fix applying changes to custom color schemes to open files (Editor)

spyder/config/main.py, spyder/plugins/editor/confpage.py, spyder/plugins/editor/tests/conftest.py, spyder/plugins/editor/widgets/editorstack/editorstack.py, spyder/plugins/editor/widgets/main_widget.py
=> PR: Add option to show/hide file name toolbar (Editor)

spyder/plugins/editor/widgets/codeeditor/tests/test_warnings.py
=> PR: Fix failing tests on macOS (CI)

.github/workflows/test-files.yml, .github/workflows/test-linux-qt6.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-remoteclient.yml, .github/workflows/test-win.yml
Update workflow triggers
* Do not trigger on 5.x branch
* Do not trigger on other workflow yml file changes
* Do not trigger on unrelated github shell scripts
=> PR: Remove unnecessary workflow triggers (CI)

.github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-remoteclient.yml, .github/workflows/test-win.yml
=> Backport PR #24245 on branch 6.x (PR: Remove unnecessary workflow triggers (CI))

.github/workflows/build-subrepos.yml, .github/workflows/installers-conda.yml, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-remoteclient.yml, .github/workflows/test-win.yml
=> Backport PR #24244 on branch 6.x (PR: Update workflow actions to address some warnings (CI))

changelogs/Spyder-6.md
Also, reorganize its API subsections in order of importance.
Fixes #
=> PR: Add new features and improvements for 6.1.0 to our Changelog

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py, spyder/plugins/variableexplorer/widgets/dataframeeditor.py, spyder/plugins/variableexplorer/widgets/namespacebrowser.py, spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py, spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py, spyder/widgets/collectionseditor.py, spyder/widgets/tests/test_collectioneditor.py
Add a button to the dataframe editor. When pressed, Spyder will plot a histogram of the data in the column that the currently selected cell is in. If multiple cells are selected then histograms of all columns containing at least one selected cells are plotted. If no cell is selected then the button is disabled. See video below.
Panda's `DataFrame.hist()` function is called to plot the histogram. The plot is displayed in the Plots pane or in a separate window, just like when the user generates a plot from the collection editor. In fact, part of the implementation for plotting from the collection editor and the dataframe editor is shared (inside the namespace browser).
Just like the collection editor, the plotting is done in Spyder's runtime environment. We mentioned once that we might want …
=> PR: Plot histogram from dataframe editor (Variable Explorer)

spyder/plugins/findinfiles/widgets/main_widget.py, spyder/plugins/findinfiles/widgets/results_browser.py, spyder/widgets/comboboxes.py
=> Backport PR #24239 on branch 6.x (PR: Fix width of the Find pane when searching for long strings)

spyder/plugins/explorer/widgets/explorer.py
Fix open context menu when right-clicking the blank area of Files pane
Fixes #24205 
@jsbautista
=> PR: Fix opening context menu when clicking the blank area of Files pane

spyder/plugins/editor/utils/findtasks.py
Make Editor annotations work in lower case
Fixes #22341
@jsbautista
=> PR: Make Editor annotations work in lower case

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.0.6 release following latest changes/strings additions/changes
=> PR: Update translations for 6.0.6

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
=> PR: Update Changelog, Announcements and metadata files for 6.0.6

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
Backport PR #24411: PR: Update Changelog, Announcements and metadata files for 6.0.6
=> Backport PR #24411 on branch 6.x (PR: Update Changelog, Announcements and metadata files for 6.0.6)

spyder/config/main.py, spyder/plugins/editor/widgets/editorstack/tests/test_shortcuts.py
Change shortcut transform to uppercase
Fixes #4126
@jsbautista
=> PR : Change shortcut to transform text to uppercase (Editor)

spyder/config/main.py, spyder/widgets/findreplace.py
Add shortcut to replace all
Fixes #24423 
@jsbautista
=> PR: Add shortcut to find/replace widget to replace all found instances

spyder/config/main.py, spyder/plugins/editor/widgets/editorstack/tests/test_shortcuts.py
Change shortcut transform to lowercase
Fixes #
@jsbautista
=> PR: Change shortcut to transform text to lowercase (Editor)

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
=> PR: Update Changelog, Announcements and metadata files for 6.0.7

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
Backport PR #24464: PR: Update Changelog, Announcements and metadata files for 6.0.7
=> Backport PR #24464 on branch 6.x (PR: Update Changelog, Announcements and metadata files for 6.0.7)

spyder/plugins/explorer/widgets/main_widget.py
=> PR: Move filter and refresh actions to be part of the corner widgets (Files)

Announcements.md, changelogs/Spyder-6.md
=> PR: Update Announcements and Changelog for 6.1.0a3

external-deps/spyder-remote-services/.gitrepo, external-deps/spyder-remote-services/spyder_remote_services/services/files/base.py, external-deps/spyder-remote-services/spyder_remote_services/services/files/compression.py, external-deps/spyder-remote-services/spyder_remote_services/services/files/handlers.py, setup.cfg, spyder/plugins/remoteclient/api/modules/file_services.py, spyder/plugins/remoteclient/tests/test_files.py
Added zipping support to remote files api
Added option to remove non-empty directories
This client-side update corresponds with the server-side changes implemented in https://github.com/spyder-ide/spyder-remote-services/pull/18
=> PR: Add zipping and deleting of non-empty directories to the Remote client files api module

spyder/utils/programs.py
See https://github.com/spyder-ide/spyder/issues/20968#issuecomment-2989430195
Fixes #20968 
=> PR: Add environment variables when trying to detect modules on Windows (Utils/IPython Console)

.well-known/funding-manifest-urls
Adds the `.well-known/funding-manifest-urls` file required to validate that our `funding.json` on the Spyder website for the FLOSS fund represents this repo.
I certify the above statement is true and correct: CAM-Gerlach
=> PR: Add funding-manifest-urls for FLOSS fund

spyder/config/main.py, spyder/plugins/application/container.py, spyder/plugins/debugger/plugin.py, spyder/plugins/debugger/widgets/main_widget.py, spyder/plugins/editor/api/actions.py, spyder/plugins/editor/confpage.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor/codeeditor.py, spyder/plugins/editor/widgets/editorstack/editorstack.py, spyder/plugins/editor/widgets/main_widget.py, spyder/plugins/findinfiles/plugin.py, spyder/plugins/help/utils/tutorial.rst, spyder/plugins/ipythonconsole/widgets/kernelconnect.py, spyder/plugins/ipythonconsole/widgets/main_widget.py, spyder/plugins/projects/widgets/main_widget.py, spyder/plugins/remoteclient/widgets/container.py, spyder/plugins/run/container.py, spyder/plugins/shortcuts/plugin.py
* Removes the "Scroll past the end" menu item from the Source menu, as this is an infrequently changed low-priority option
* Replace it with the far more frequently toggled "Wrap lines" item
* Enable "Underline errors" by default, to more clearly show users where their code has issues like other IDEs
* Revise menu UI text and tooltips throughout the application to be more clear and concise
* Be consistent and follow standard UI guidelines in use of the ellipses after menu items
* Be clearer and more up to date in naming/describing the EOL character options, and tweak the order
I found a few additional instances where menu re-ordering would make things clearer and more logical, but I've left that for another PR to avoid letting this one get even more out of scope.
By submitting this Pull …
=> PR: Adjust Source menu, underline errors by default & fix menu text

spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/main_widget.py, spyder/plugins/remoteclient/api/protocol.py, spyder/plugins/remoteclient/plugin.py, spyder/plugins/remoteclient/tests/fixtures.py, spyder/plugins/remoteclient/widgets/__init__.py, spyder/plugins/remoteclient/widgets/connectiondialog.py, spyder/plugins/remoteclient/widgets/connectionstatus.py
=> PR: Add a JupyterHub connection page to the remote connections dialog (Remote client)

spyder/api/plugin_registration/_confpage.py, spyder/utils/icon_manager.py, spyder/widgets/config.py, spyder/widgets/elementstable.py, spyder/widgets/emptymessage.py, spyder/widgets/helperwidgets.py
- This includes many enhancements to that widget to implement a new UI for managing environments in the spyder-env-manager plugin.
- Add kwarg to create vertical comboboxes to `SpyderConfigPage` and fix `edit_remove` icon.
- Add kwarg to `EmptyMessageWidget` to not highlight it on focus in.
- Fix icon for `edit_remove` action.
Fixes #
=> PR: Additional improvements for `ElementsTable` (Widgets)

changelogs/Spyder-6.md, spyder/plugins/application/container.py, spyder/plugins/application/plugin.py, spyder/plugins/completion/providers/languageserver/conftabs/advanced.py, spyder/plugins/help/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/layout/plugin.py, spyder/plugins/mainmenu/api.py, spyder/plugins/preferences/plugin.py, spyder/plugins/preferences/widgets/container.py, spyder/plugins/pythonpath/plugin.py, spyder/plugins/remoteclient/plugin.py, spyder/plugins/shortcuts/plugin.py, spyder/plugins/tours/container.py, spyder/plugins/tours/plugin.py, spyder/plugins/updatemanager/container.py, spyder/plugins/updatemanager/plugin.py
A final set of changes following up from #24661 and #24664 to reorganize the Tools, View and Help menus. Specifically:
* Regrouped the three inconsistently split sections in Tools into two: Managers (Pythonpath, env vars and remote connections) and Preferences (show and reset).
* In View, move Maximize Pane above Close Pane per idiomatic/conventional action ordering
* Reorganize Help sections into one for bulit-in/overview documentation, one for external documentation, one for troubleshooting and one for about/general, and move external documentation next to overview documentation rather than splitting them with support
* Re-order the items within the sections to make more sense
* Move the Debug Logs item from the Tools menu to the Troubleshooting section of the Help menu, where it fits …
=> PR: Reorganize Tools, View and Help menus for better UX

spyder/utils/qstringhelpers.py
Those are emojis that don't fit in 16 bits.
Fixes #24713.
=> PR: Fix error when getting length of string with special emojis (Utils)

spyder/plugins/editor/widgets/codeeditor/codeeditor.py
=> PR: Fix uncommenting code in files with tabs (Editor)

spyder/plugins/ipythonconsole/plugin.py
Remove all blank lines and white space characters at the beginning and end of a code string.
Fixes #
=> PR: Remove blank lines and white space characters when running cells if their contents are copied (IPython console)

changelogs/Spyder-6.md
List the most important features added/fixed in this release.
Fixes #
=> PR: Update changelog with new features and fixes in 6.1.0a4

Announcements.md, changelogs/Spyder-6.md
=> PR: Update Announcements and Changelog for 6.1.0a4

spyder/plugins/editor/extensions/snippets.py
=> PR: Put cursor in the middle of braces when code snippets are not available (Editor)

changelogs/Spyder-6.md, spyder/api/plugins/new_api.py, spyder/plugins/application/container.py, spyder/plugins/application/plugin.py, spyder/plugins/application/tests/test_plugin.py, spyder/plugins/editor/api/actions.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/main_widget.py, spyder/plugins/help/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/onlinehelp/plugin.py
See https://github.com/spyder-ide/spyder/issues/23188#issuecomment-3054360054
A preview:
Fixes #23188
This only covers usage of the Search menu hook for the Editor and the IPython Console. Should other plugins/panes that instantiate a find related widget be also added here (Help, Variable Explorer, Debugger, etc)?
=> PR: Allow plugins to hook into search actions (Application/Editor/IPython Console)

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
Backport PR https://github.com/spyder-ide/spyder/pull/24902: PR: Update Changelog, Announcements and metadata files for 6.0.8
=> Backport PR #24902 on branch 6.x (PR: Update Changelog, Announcements and metadata files for 6.0.8)

.github/scripts/install.sh, spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
Our test suite started to fail on Windows and Linux a few hours ago and this tries to fix that.
Fixes #
=> PR: Fix some test failures (CI)

spyder/plugins/ipythonconsole/widgets/shell.py
That prevents removing useful results users can have in the console before changing the style.
Fixes #9896.
@jsbautista
=> PR: Don't clear console after applying a new color scheme (IPython console)

installers-conda/resources/osx_pkg_welcome.rtf
=> PR: Fix typographical error in macOS installer welcome page

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/te/LC_MESSAGES/spyder.po, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po, spyder/plugins/explorer/widgets/remote_explorer.py, spyder/plugins/profiler/confpage.py
* Update translations `*.pot` and `*.po` files for the upcoming Spyder 6.1.0 release following latest strings additions/changes
Part of #25039
=> PR: Update translations for 6.1.0 

spyder/app/tests/test_mainwindow.py, spyder/plugins/explorer/widgets/remote_explorer.py, spyder/plugins/profiler/confpage.py
- These strings were fixed in #25040 but only for the 6.x branch.
Fixes #
=> PR: Fix some strings for translation

changelogs/Spyder-6.md
Also, reorganize a few entries too.
Fixes #
=> PR: Add new features included in the last 6.1.0 pre-releases to Changelog

Announcements.md, changelogs/Spyder-6.md, scripts/org.spyder_ide.spyder.appdata.xml
=> PR: Update Changelog, Announcements and metadata files for 6.1.0
