spyder-ide/spyder

spyder/requirements.py

- Our current code was throwing an error if no Python Qt bindings were present.
- I also took the opportunity to update the code we have to display a message with Tkinter about that.
- This was reported in https://stackoverflow.com/q/71261324/438386

PR: Fix check for PyQt/PySide requirement

---

spyder/plugins/ipythonconsole/comms/kernelcomm.py

Added %s in logger.info("Dropping message because kernel is dead: ", str(call_dict)) .
Now "logger.info("Dropping message because kernel is dead: %s", str(call_dict))" .
```
BUG: Some log arguments are not converted to string format
Error in sys.excepthook:
File "C:\Users\dan-s\miniconda3\envs\ciermag-develop\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 767, in kernel_restarted_message
self.poll_std_file_change()
File "C:\Users\dan-s\miniconda3\envs\ciermag-develop\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 392, in poll_std_file_change
self.shellwidget.call_kernel().flush_std()
File "C:\Users\dan-s\miniconda3\envs\ciermag-develop\lib\site-packages\spyder_kernels\comms\commbase.py", line 554, in …
```

PR: Fix for arguments to be converted to string format

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/utils/mpl.py
spyder/plugins/ipythonconsole/confpage.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

- The Qt4 backend is no longer supported by Matplotlib.
- We have not received bug reports about the Gtk backends (even if they are broken with the latest Matplotlib), so we assume no one is using them.
- Depends on spyder-ide/spyder-kernels#375
Fixes #17172.

PR: Remove support for outdated and unused Matplotlib backends (IPython Console)

---

spyder/api/plugin_registration/_confpage.py

PR: Avoid external plugins to be disabled

---

bootstrap.py
setup.py
spyder/config/main.py
spyder/plugins/completion/confpage.py
spyder/plugins/completion/plugin.py

- Kite reached end-of-life last year, so we don't need to support it anymore.
- This does the minimal changes to disable Kite for now. After 5.3.0 is released, we can see how to remove it from our codebase.
Fixes #17108.
Fixes #16595.

PR: Completely disable Kite provider (Completions)

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/plugin.py
spyder/plugins/run/widgets.py
spyder/utils/programs.py

* Added option to use default run configuration in the per-file run configuration
* Moved external terminal elements moved to the console group
* Behavior is unchanged except that when this option is selected the file-specific run configuration is ignored and the default run configuration takes priority.
* Note: all other file-specific run configuration options are not modified. This will allow toggling the run configuration without requiring the user to re-establish file run configuration.
* Fixed an issue with running in an external terminal if path and/or script name had spaces.
Fixes #16207
with respect to all commits and content included in …

PR: Add option to per-file run configuration to use default run configuration

---

installers/macOS/setup.py

For the Windows installer and launching Spyder from the command line, user environment variables are inherited. This was not the case for the macOS application. This PR changes the macOS installer to inherit the user's environment variables, similar to the case for launching from the command line.
Fixes #14843 

PR: Update macOS app to import user environment variables

---

spyder/app/mainwindow.py

Allow only one PYTHONPATH Manager dialog instance
Fixes #14809 

PR: Ensure only one instance of PYTHONPATH Manager

---

spyder/plugins/editor/widgets/codeeditor.py

Minor change to the icons of the context menu to make them consistent and match that of the Run menu.
The run menu icons for running cell code looks like this, with different icon for `Run cell` and `Run cell and advance` and no icon for `Re-run last cell`. 
The context menu on 5.3.0.dev0 looks like this, with the `Run cell` icon repeated for `Run cell and advance` and `Re-run last cell`. 
This PR sets the proper icon for  `Run cell and advance` and removes `Re-run last cell` on the context menu, so that it is consistent with the Run menu.
No issue opened
and understand I am releasing …

PR: Make context run cell icons match run menu icons

---

spyder/plugins/projects/widgets/projectexplorer.py

Filter shown project explorer paths using only the last element in the path
Fixes #17217

PR: Use only paths last element for filtering in the project explorer

---

spyder/plugins/editor/widgets/codeeditor.py

The `urls` of `clipboard.mimeData()` can be empty and we were not accounting for that case.
Fixes #17521

Editor: Avoid error when getting urls content from clipboard's mime data

---

.github/workflows/installer-macos.yml
installers/macOS/packages.py
installers/macOS/req-build.txt
installers/macOS/setup.py

Updated macOS installer to use the latest `py2app=0.27` .
This version of py2app includes many improved recipes, greatly simplifying our lists of packages that have to be excluded from zip archive or included in the bundle.
`py2app` now also handles the `egg-info`/`dist` files.
A patch is still required and can be removed at a later `py2app` version.

PR: Update py2app to 0.27 (Mac app)

---

spyder/plugins/editor/plugin.py

In 5.2.2 I updated the entries that appear in this dropdown in Preferences:
However, I missed that we have the menu `Source > Convert end-of-line characters` to switch EOLs on demand, and the entries there should match the ones in Preferences:
This PR does precisely that
I also fixed a minor issue: we were not showing the right EOLs in the statusbar and that menu for the file that has focus after Spyder starts or when switching projects.

PR: Make entries of `Convert end-of-line characters` menu match the ones in Preferences

---

spyder/app/mainwindow.py

Force clean application close when not running under pytest (running the test suit)
Fixes #17500 

PR: Change validation to force clean application close

---

spyder/locale/de/LC_MESSAGES/spyder.po
spyder/locale/es/LC_MESSAGES/spyder.po
spyder/locale/fa/LC_MESSAGES/spyder.po
spyder/locale/fr/LC_MESSAGES/spyder.po
spyder/locale/hr/LC_MESSAGES/spyder.po
spyder/locale/hu/LC_MESSAGES/spyder.po
spyder/locale/ja/LC_MESSAGES/spyder.po
spyder/locale/pl/LC_MESSAGES/spyder.po
spyder/locale/pt_BR/LC_MESSAGES/spyder.po
spyder/locale/ru/LC_MESSAGES/spyder.po
spyder/locale/spyder.pot
spyder/locale/uk/LC_MESSAGES/spyder.po
spyder/locale/zh_CN/LC_MESSAGES/spyder.po

Update translations `*.pot `and `*.po` files.
Depends on #17526 and #17528 

PR: Update translations for 5.3.0

---

installers/macOS/req-build.txt
spyder/plugins/ipythonconsole/utils/kernelspec.py
spyder/plugins/ipythonconsole/widgets/client.py

- Removed relevant errors from the benign error filter in `ipythonconsole` plugin
- Added the environment variable `PYDEVD_DISABLE_FILE_VALIDATION` to IPython Console 
The advent of `debugpy=1.6.0` provided an environment variable to bypass the errors encountered in #16927, #16828, and #17552.
Currently, only 1.5.2 is available on conda-forge; when 1.6.0 is available, I'll mark as ready for review.
Fixes #17552

PR: Pass new environment variable to the kernel and remove some benign errors thanks to debugpy 1.6.0 (IPython console)

---

spyder/config/main.py

Users (especially newbies) are really confused by not seeing uppercase variables in the Variable Explorer. So it's better to disable that option by default, instead of having it enabled.
Fixes #16402

PR: Disable option that excludes uppercase variables (Variable Explorer)

---

spyder/config/lsp.py
spyder/plugins/completion/providers/languageserver/provider.py
spyder/plugins/editor/widgets/tests/assets/autopep8_max_line.py
spyder/plugins/editor/widgets/tests/assets/black_max_line.py
spyder/plugins/editor/widgets/tests/assets/yapf_max_line.py
spyder/plugins/editor/widgets/tests/test_formatting.py

- This was not working due to the lack of client-side options to configure `python-lsp-black`, which were added in its 1.2.0 version.
- Also set other configuration options added in that version.
Fixes #14558

PR: Fix setting max line length for Black (Completions)

---

spyder/app/mainwindow.py
spyder/utils/workers.py

When shutting down the application using `os._exit` we where not running the closing logic for the plugins. Although the majority of plugins only do cleaning tasks (stopping things running with threads or closing child widgets), some plugins also do tasks to preserver/check their state like for example the Editor (check for unsaved files, save recent files, save openend files, etc) and Projects (save if some project is active, recent projects, etc). 
Also since https://github.com/spyder-ide/spyder-terminal/pull/315 was merged and a [new release for spyder-terminal](https://github.com/spyder-ide/spyder-terminal/releases/tag/v1.2.2) done we can again just call `os._exit` when running in the macOS installer (since there an `abort 6` message appears when closing with the usual logic).
By …

PR: Fix usage of `os._exit` to save Editor and Projects plugins state

---

spyder/api/plugin_registration/registry.py
spyder/app/mainwindow.py

Close Editor first and not call `close()` in the plugin instance to prevent Editor layout issue when closing with unsaved files

PR: Fix layout issue when closing with unsaved files

---

spyder/utils/programs.py

`run_python_script_in_terminal` is revised to:
* ensure proper execution when spaces are present in `wdir` and/or python file path
* remove Python 2 consideration
* remove redundancies in changing the current working directory for execution
Fixes #17595

PR: Revise run_python_script_in_terminal

---

REVIEW.md

This PR adds `REVIEW.md`to the root directory. This document contains the draft Reviewer Guidelines myself and multiple Spyder reviewers would like to add to the project's contributing process. 
This document has mainly been a collaboration between myself, @juanis2112, @steff456, @CAM-Gerlach, and @ccordoba12. Review is absolutely welcome!
I'm looking to merge to `master` because the [contributing guide](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md#spyder-branches) lists that this is for breaking changes. This is a breaking community change and not tied to any particular software release. Please let me know if it needs to be merged to a different branch.
There is no related issue. This document was written in response to a review of Spyder's current Code of Conduct and …

PR: Create Reviewer Guidelines

---

.github/workflows/installer-macos.yml
installers/macOS/Readme.md
installers/macOS/packages.py
installers/macOS/req-build.txt
installers/macOS/setup.py

Update `py2app` to version 0.28.
This includes a new recipe for `black`, updated recipe for `pyqt`, and fixes for egg handling.
Some additions to the `setup` call brings the build into compliance with `setuptools>60.10.0`.
Fixes #17609
Fixes #17551

PR: Update py2app to 0.28 (Mac app)

---

setup.cfg
setup.py

`check-manifest` validation failing due to new `REVIEW.md` file. Building Windows installers failing on master due to wrong `spyder-kernels` version requirement patch.

PR: Ignore `REVIEW.md` from `check-manifest` and fix `setup.py` patch for Windows installers on PRs

---

spyder/plugins/shortcuts/widgets/summary.py

Thanks for your work on this version!  I'm close to getting it working for Debian....
The test `spyder/plugins/shortcuts/widgets/tests/test_summary.py::test_shortcutssummary` fails with Python 3.10 because `QFont().setPointSize()` requires an integer argument, and Python no longer performs implicit float -> integer conversions.  This patch fixes the cause.
I certify the above statement is true and correct: juliangilbey

PR: Ensure `QFont.setPointSize` receives an int argument (Shortcuts)

---

spyder/plugins/application/container.py

Not doing that generates an error in Python 3.10 because it doesn't automatically cast floats to ints.
Fixes #17677.

PR: Convert coordinates to position DPI message to int (Application)

---

spyder/plugins/explorer/widgets/explorer.py

Actions duplication in menu (SpyderMenu) since for that kind of menu the custom method `clear_actions` needs to be call to actually clear all actions references.
Fixes #15460

PR: Fix clear for `Open with` menu in the Files pane

---

spyder/api/_version.py
spyder/api/plugins/new_api.py
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/app/utils.py
spyder/plugins/console/plugin.py
spyder/plugins/console/tests/test_plugin.py
spyder/plugins/console/widgets/internalshell.py
spyder/plugins/console/widgets/main_widget.py
spyder/plugins/layout/plugin.py
spyder/plugins/preferences/tests/conftest.py
spyder/plugins/projects/plugin.py
spyder/plugins/projects/tests/test_plugin.py
spyder/plugins/workingdirectory/container.py
spyder/plugins/workingdirectory/plugin.py
spyder/plugins/workingdirectory/tests/test_workingdirectory.py

- Add a new API method for plugins to access command line options.
- Use it to simplify how different plugins handle those options (i.e. Projects, Internal console and Working directory).
- Fix the `--workdir`/`-w` cli option
- Remove some dead code in `MainWindow`.
- Add tests wherever possible.
Fixes #17589

PR: Improve the way command line options are handled by plugins

---

spyder/plugins/editor/widgets/completion.py

Add the item label and item type as accessible text role for each item in the Editor completion widget.
Fixes #17047 

PR: Add `Qt.AccessibleTextRole` data to completion widget items

---

spyder/plugins/editor/widgets/editor.py

This can happen on Windows for files on a network drive that is not available when Spyder starts.
Fixes #17685.

PR: Catch OSError when trying to open a not available file (Editor)

---

.github/scripts/install.sh
.github/workflows/test-mac.yml
.github/workflows/test-win.yml
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/onlinehelp/tests/test_pydocgui.py
spyder/plugins/pylint/tests/test_pylint.py
spyder/widgets/mixins.py

* Try to improve overall test suit robustness.
* Remove outdated test due to changes in the debugger
* Check patch code for QTextEdit based widgets for Qt <5.15
Fixes #17580 
Fixes #17499
Fixes #17498

PR: Check tests robustness, number of concurrent jobs and try to decrease segfault failures on CI

---

spyder/plugins/completion/providers/languageserver/client.py

Without this variable, the server won't start for Pip installations where the server and its dependencies are installed in the `APPDATA` directory.
Fixes #17661.

PR: Pass `APPDATA` env var to the process that starts the PyLSP server (Completions)

---

.github/workflows/installer-macos.yml
installers/macOS/req-extras.txt
spyder/app/mainwindow.py

Closing the Spyder application in `mainwindow.py` has a flow control fork for the macOS standalone application. This is removed.
Fixes #17729 
Partial fix for #17731

PR: Remove macOS app flow fork in closing Spyder

---

spyder/api/config/mixins.py
spyder/api/plugins/new_api.py
spyder/api/widgets/main_widget.py
spyder/api/widgets/mixins.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/console/widgets/main_widget.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/utils/kernelspec.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/ipythonconsole/widgets/debugging.py
spyder/plugins/ipythonconsole/widgets/main_widget.py

- This leads to use different configuration objects for setting and getting options, which can introduce inconsistencies in future tests. Actually, I found this problem while trying to create a test for issue #17737.
- It doesn't seem necessary anymore, i.e. tests pass without it.
- Skip some tests that hang sometimes on Mac.

PR: Remove possibility of passing separate configuration object for testing

---

spyder/plugins/editor/widgets/editor.py

PR: Calculate index when autoformating on save from the Editor

---

spyder/plugins/editor/widgets/base.py
spyder/plugins/editor/widgets/editor.py

I added navigation with XButtons (the typical extra two buttons on a mouse used for browsing backward and forward) in the code editor.
This improves code browsing if the mouse has this ability.
I don't know if this is testable and how, as it only adds a new trigger which is forwarded to the one in the EditorStack.
Fixes #15948
I certify the above statement is true and correct: Florian Maurer

PR: Implement mouse XButton navigation in the editor

---

spyder/api/plugin_registration/registry.py

See commit message for details. EDIT: This error has been detected while porting the Watchlist Plugin (see https://github.com/spyder-ide/spyder/issues/16438) to Spyder v5.3.0.
rear1019

PR: Fix saving of external plugin config in on_close()

---

spyder/plugins/editor/widgets/editor.py

Setting the Editor plugin as the parent for the EditorMainWindow was attaching it to the Main window
Fixes #17803

PR: Fix Editor new window to be indenpendent of the main window

---

spyder/plugins/preferences/plugin.py
spyder/plugins/preferences/widgets/container.py

It was not possible to close Spyder when the Preferences dialog is open because we were preventing that. However, now that's not a good idea because plugins are closed sequentially, so stopping the close process at Preferences caused our layout to be messed up the next time Spyder is started.
Fixes #17784.

PR: Close Preferences when closing Spyder

---

spyder/plugins/completion/providers/languageserver/providers/document.py

This was caused because the PyLSP can send an empty list as response for signatures if Jedi fails to get them, and we were not accounting for that possibility.
Fixes #17778.

PR: Check that signature response is not empty before processing it (Completions)

---

spyder/plugins/editor/confpage.py
spyder/plugins/editor/widgets/editor.py

There was a collision between the autoformat on save option other Editor formatting options available. Due to that those options need to be disregard if autoformat on save is on.
Fixes #17716 

PR: Fix collision between `format_on_save` and other Editor formatting options

---

spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/editor/widgets/tests/conftest.py
spyder/plugins/editor/widgets/tests/test_formatting.py

Since the autoformat option can take time we need to wait before returning on the editor `save` method to prevent lossing changes when closing an unsaved file.
Depends on https://github.com/spyder-ide/spyder/pull/17860
Fixes #17836 

PR: Wait for autoformat before returning on 'save' method (Editor)

---

.github/workflows/installer-win.yml
installers/Windows/installer.py
spyder/config/base.py

Depends on https://github.com/spyder-ide/windows-installer-assets/pull/8 and a new assets release
Part of https://github.com/spyder-ide/spyder/pull/17692
Updates the assets URL to get the micromamba executable when building the Windows installers
Checked installing locally the PR Windos full installer and the path from micromamba seems correct :+1:

PR: Add micromamba executable to the Windows installer

---

spyder/plugins/variableexplorer/widgets/main_widget.py
spyder/utils/icon_manager.py
spyder/widgets/collectionseditor.py
spyder/widgets/tests/test_collectioneditor.py

- This is a follow up of PR #17473 to improve the style of the new toolbar by using the same stylesheet of pane toolbars and reorganize its icons a bit.
- Add new icons for `Insert above`/`Insert below` actions (they were using the same as the `Insert` action).
- Set disabled state color for SVG icons. Before buttons associated to those icons appeared active even if they were disabled.
- Enable/disable buttons in the toolbar according to certain conditions (e.g. is there something selected and in the same row? Is it read only?)
- Improve the context menu of collections and the Variable Explorer.
----
**Before**
----
**After**
with respect to all …

PR: Improve style and UX of new toolbar in collections viewer (Variable Explorer)

---

spyder/config/manager.py

- This is a small enhancement over PR #17526 to not use our own functions to create a QApplication to avoid importing CONF when importing them, which makes our fallback fail.
Fixes #17889

PR: Don't use create_application when showing message about not being able to load CONF

---

spyder/plugins/maininterpreter/container.py
spyder/plugins/maininterpreter/widgets/status.py

- This takes advantage of the improvements done in PR #17788.
- Now we only need to change the `custom` or `default` interpreter options and an update to the status bar will be triggered automatically. So, we don't to do it manually anymore.
- I also eliminated the externally removed interpreter from the list of ones available to be set by the user.

PR: Improve updating Main Interpreter status bar widget when the current one is removed

---

spyder/plugins/preferences/api.py

Send `QFileDialog.DontResolveSymlinks` option to `select_file` in `create_file_combobox` for Python interpreter preferences.
This ensures that symlinks are not resolved.
Fixes #17872 

PR: Do not resolve symlink on Python interpreter file selection

---

installers/macOS/packages.py
installers/macOS/req-scientific.txt

`defusedxml` was already a dependency of `nbconvert`, so it was redundent to include in the scientific packages list for the full version, but this also caused it to be explicitly excluded for the lite version, hence the issue for `nbconvert`.
Related to #18106

PR: Fix issue where nbconvert was not importable in macOS application

---

.github/workflows/installer-macos.yml

Since artifacts for PRs are primarily used by developers for verification, only the Lite version of the macOS app is built on pull requests. On releases, both Lite and Full versions are built. This may free up some CI resources.
Additionally, `pandas` (and `numpy`) are added to the Lite build in order for `pandas` objects to be inspected in the Variable Explorer in the Lite app version.
@spyder-ide/core-developers, let me know what you think of these ideas. …

PR: Only build Full macOS app on pull requests

---

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

The current version of sympy (at least in Debian) is 1.10.1, so `test_sympy_client` xpasses.  This patch does a correct version number check in the `xfail` marker.  A simpler alternative, since sympy 1.2 was released about 4 years ago, is just to remove the `xfail` marker entirely. 
Julian Gilbey  @juliangilbey

PR: `test_sympy_client` xpasses with sympy version 1.10.1

---

spyder/plugins/editor/plugin.py

The previous code assumed that the options that come from the `Completion and linting` entry in Preferences, and have checkboxes in the Source menu, have the same form. But `underline_errors` belongs to the Editor plugin, so it's different.
Fixes #18290

PR: Fix error when enabling `Underline errors and warnings` in Preferences (Editor)

---

pytest.ini
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/main_widget.py

When restarting the console when for example opening a project, the cached kernel was being used which caused an inconsistency regardsing the PYTHONPATH modified when you have a project open, or you open/close a project
Fixes #17915

PR: Don't use cached kernel for a full console restart

---

.github/workflows/installer-macos.yml
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml

#18120 had syntax issues in the workflow file that resulted in the build job failing to start without indicating failure.
This PR remedies that.
Additionally, pytests are not run if only installer files are changed.

PR: Fix syntax issues in macOS installer workflow file

---

spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/outlineexplorer/api.py

Refactor is_valid for performance
5.x:
```
>>> spy.window.editor.new()
>>> spy.window.editor.get_current_editor().set_text("#%%\nprint(0)\n"*1000)
>>> import timeit
>>> timeit.timeit("spy.window.editor.run_cell_and_advance()", number=1000, globals={"spy":spy})
7.448802667999999
```
this PR:
```
>>> spy.window.editor.new()
>>> spy.window.editor.get_current_editor().set_text("#%%\nprint(0)\n"*1000)
>>> timeit.timeit("spy.window.editor.run_cell_and_advance()", number=1000, globals={"spy":spy})
4.625459233000015
```
60% faster to run cell  and advance
Fixes #
and understand I am releasing …

PR: Make validation of blocks with Outline explorer data faster

---

spyder/plugins/application/container.py

* Try to ensure the window scale change dialog is always in top to prevent blocking the main window
* Fix checkbox position overlaping other content or not being placed correctly
* Don't show editor scale change if auto high DPI is selected
Fixes #14883 

PR: Prevent showing monitor scale change message if auto high DPI is selected and some other fixes

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/variableexplorer/widgets/main_widget.py
spyder/widgets/dock.py

connecting a Signal to another signal's emit method might lead to a segfault. The signals must be connected directly.
Fixes #

PR: Don't connect Qt signals to the `emit` method of others to avoid segfaults

---

spyder/plugins/ipythonconsole/scripts/conda-activate.bat

Windows batch scripts do not expand variables inside logic statements if the variable is assigned inside the logic statement. Thus the micromamba activation script was not executed and the environment was not activated. The call to the activation script is moved outside the logic statement, so now it is executed and the environment is properly activated.
Fixes #18003

PR: Fix issue where micromamba activation script was not properly executed.

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py
external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py
external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
external-deps/spyder-kernels/spyder_kernels/utils/dochelpers.py
external-deps/spyder-kernels/spyder_kernels/utils/tests/test_dochelpers.py
spyder/app/mainwindow.py
spyder/app/start.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/completion/providers/languageserver/provider.py
spyder/plugins/ipythonconsole/utils/kernelspec.py
spyder/plugins/ipythonconsole/utils/tests/test_spyder_kernel.py
spyder/plugins/profiler/widgets/main_widget.py
spyder/utils/icon_manager.py
spyder/utils/misc.py
spyder/utils/programs.py
spyder/utils/tests/test_misc.py
spyder/widgets/pathmanager.py
spyder/widgets/tests/test_pathmanager.py

Explicitly excluded system `PYTHONPATH` paths from Editor completion paths, IPython Console `sys.path`, and IPython Console `os.environ['PYTHONPATH']`.
Added feature to import system `PYTHONPATH` paths into PYTHONPATH Manager.
The "Syncronize..." feature (Windows only) is changed to "Export" to better complement "Import" and comport with what it actually does. This remains a Windows only feature for the time being.
Resolved an issue where a path was added after canceling "Select directory" dialog.
Fixes #17511 
I …

PR: Consistently handle PYTHONPATH and add Import feature to PYTHONPATH Manager

---

.github/scripts/install.sh
installers/Windows/req-extras-pull-request.txt
installers/Windows/req-extras-release.txt
installers/macOS/req-scientific.txt

- Our completion tests for the editor and the console are failing with that version.
- Also constrain Numpy in our installers in case this problem is not fixed before the next release.
Fixes #18407.

PR: Use Numpy 1.22 because 1.23 is not giving completions

---

spyder/api/plugin_registration/registry.py
spyder/api/plugins/new_api.py
spyder/api/widgets/main_widget.py
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py

Panes sizes were not being kept after starting and also the way the main window closing was being handled was causing issues with the undocking state save behavior and panes sizes. This changes the way to close things by checking first if everything can be closed, docking and saving the undocked state for all the plugins and then closing and actually deleting all the plugins
Fixes #17945 
Fixes #15074 

PR: Ensure setting up last dockwidgets size distributions (Layout and Registry)

---

spyder/app/mainwindow.py
spyder/app/start.py

Also print an informative message to tell users what Spyder is doing when a second instance is trying to send files to the main instance to be opened because it could appear as hanging when the server didn't start.
Fixes #18262.

PR: Catch error when it's not possible to bind a port to `open_files_server` (Main Window)

---

spyder/plugins/profiler/widgets/main_widget.py

The profiler widget's start method uses a QProcess that does not remove PYTHONHOME from the process environment when running external environments. This PR resolves that issue.
Fixes #18010

PR: Remove PYTHONHOME from QProcess.processEnvironment in profiler

---

spyder/plugins/ipythonconsole/widgets/main_widget.py

Use `&hyphen;` instead of plain `-` to prevent copy-pasting an incorrect command following kernel instructions to update
Pinging @jnsebgosselin just in case to check if another approach for this was found
Fixes #17425 

PR: Escape hyphen from update instructions for spyder-kernels (IPython Console)

---

spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/tests/test_completions_hide.py

PR: Hide completion widget when keypress has modifiers (Editor)

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/framesexplorer/widgets/framesbrowser.py
spyder/plugins/framesexplorer/widgets/main_widget.py

After https://github.com/spyder-ide/spyder-kernels/pull/381 the full stack is not sent to the frontend after every pdb command, so executing a command causes the frames explorer to reset. This PR solves that issue and adds a regression test.
Fixes #

PR: Do not reset the frames explorer while debugging

---

spyder/plugins/plots/widgets/figurebrowser.py

Add validations to prevent raising a `ZeroDivisionError` when checking figures/plots scaling/size
Fixes #15223 
Fixes #17753 

PR: Prevent ZeroDivisionError when calculating plots scales and sizes (Plots)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py
external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
external-deps/spyder-kernels/spyder_kernels/customize/utils.py

* Debugging with remote kernels is broken due to this.
* Depends on spyder-ide/spyder-kernels#389
Fixes #18330 

PR: Fix filenames used for remote kernels while debugging

---

binder/environment.yml
requirements/tests.txt
runtests.py
setup.py

PR: Use `pytest-timeout` and set timeout to 120 secs

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/ipythonconsole/widgets/main_widget.py

- These methods (i.e. `create_client_for_kernel` and `rename_client_tab`) are necessary to finish the migration of Spyder-notebook to the new API (see spyder-ide/spyder-notebook#369)
- This PR also corrects the way we handle the current working directory to use it to start new consoles. That was implemented as part of PR #17760 but it didn't follow the patterns of our new API.

PR: Add new API methods to the IPython console

---

spyder/api/plugin_registration/registry.py

The validation for all the plugins was being done twice. Because of that the Editor was asking two times if a file need to be saved before exiting. This ensures is only done once for all the plugins before proceding to deleted them all
Fixes #18624

PR: Don't double validate if plugins can be deleted/closed (Registry)

---

spyder/plugins/variableexplorer/widgets/namespacebrowser.py

While this does not fix the major file save dialog problems mentioned in #7196 it allows to save the workspace in a pickle file without finding out which extension is needed.
Currently, `.mat` and `.spydata` is supported to write data, and it makes sense to prefer `.spydata` here.
I also removed the filename option from the save method, as it is never used.
If the method would be called with `filename='text.spydata'` it would anyway save as `self.filename` which would be wrong.
So I hope it is fine to remove the optional parameter.
Thank you!
Fixes #7196
and understand I am releasing the …

PR: Fix saving variables as .spydata if no file extension is given

---

.github/workflows/installer-macos.yml

Remove `@rpath` reference in `@rpath/libc++.1.dylib` in the `micromamba` executable to be compliant with runtime hardening.
Fixes #18661 

PR: Patch rpath in micromamba so that code signing doesn't break it

---

conftest.py

Some parametrized tests have spaces in their parameters, so they are not skipped on subsequent functions (the current `conftest.py` sees
```
spyder/utils/tests/test_syntaxhighlighters.py::test_python_outline_explorer_comment[# --- First variant] SKIPPED (Test passed in previous runs) [ 92%]
```
for example, and reads a node id of `spyder/utils/tests/test_syntaxhighlighters.py::test_python_outline_explorer_comment[#`, which does not match any test item.
This patch parses the log file a little more carefully to get any lines beginning `spyder` and to extract everything up to the test result for passing tests ("SKIPPED", in the above example).  As a further consequence, we now return all of the results, including the final one (as a failing test will not be captured by this modified code). …

PR: Catch all passed tests, including parametrized tests with spaces in parameters

---

conftest.py

Currently, on a subsequent test run, `conftest.py` will report the reason for skipping a "run-slow" test if `--run-slow` is not specified as "Test passed in previous runs", which is not true.  This patch changes the order of the conditionals so that the "Need/Don't need --run-slow option to run" reason will be given precedence.
@juliangilbey

PR: Prefer a run-slow skip reason over an already passed one (Testing)

---

spyder/plugins/editor/plugin.py

- This allows us to always use a light syntax highlighting theme when printing.
- The `Print preview` looks like this now
Fixes #2521.

PR: Use an instance of SimpleCodeEditor to print files (Editor)

---

.github/scripts/run_tests.sh
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml
conftest.py
runtests.py

You might be interested in this patch (or not); it more closely resembles what I have done on Debian.  Building on your improvements to `conftest.py`, this change is to attempt all the tests in the test suite on the first run (by removing the pytest `-x` option).  The reason for this is that most failures I have observed are transient, so typically all pass on the second pytest run.
The other small change this patch makes because of the above change is to append the log files together rather than starting afresh each run; in this way, if a pytest run crashes in the middle (which I have often seen on non-amd64 architectures), passes from previous runs are not lost.
The one thing I have not done in this patch, but I think would be reasonable, is to reduce the number of pytest runs …

PR: Run all tests, not stopping on first failure (Testing)

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/codeeditor_widgets.py
spyder/plugins/editor/widgets/gotoline.py
spyder/plugins/editor/widgets/printer.py
spyder/plugins/editor/widgets/tests/test_shortcuts.py
spyder/utils/icon_manager.py

- This is follow-up of PR #18808.
- I changed the dialog's icons to use Material design ones, made the toolbar follow the style of the other pane toolbars and also made the tooltip strings translatable.
**Before**
**After**

PR: Make style of "Print preview" dialog follow the rest of Spyder

---

spyder/plugins/editor/plugin.py

I recreated this after the CRLF PR
I added the "Debug Cell" icon to the toolbar. 
Before
After
I find it extremely annoying that all of the major Debug tools are in the toolbar _except_ for the Debug Cell tool. And sometimes, when trying to click on it from the Debug menu, I accidentally hit the "Run File" toolbar icon instead. This PR adds the icon, keeping the same ordering that is used in the Debug menu.
I certify the above statement is true and correct: stevetracvc

PR: Add debug cell icon to the debug toolbar

---

spyder/api/_version.py
spyder/api/plugins/new_api.py
spyder/config/manager.py
spyder/plugins/appearance/confpage.py
spyder/plugins/appearance/plugin.py
spyder/plugins/appearance/tests/test_confpage.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/help/widgets.py
spyder/plugins/history/widgets.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/preferences/api.py
spyder/plugins/pylint/main_widget.py

- Don't apply new color schemes if they require a restart. Instead, simply show users the restart message.
Right now users end up in this situation when changing to a light color scheme, which is confusing:
With this PR we only show the restart message, which is clearer according to this https://github.com/spyder-ide/spyder/issues/2521#issuecomment-1172457307
- Simplify the restart message to not mention the options that require it (see the second screenshot above). I think that's an implementation detail that users don't need to know.
- Update occurrences, line and cell selections in the editor when applying a new color scheme. This allows color schemes to be applied correctly after switching them.
**Before**
**After**
- Add new API methods to disable/restore notifications for options.
- …

PR: Don't apply color schemes that require a restart and fix other issues about them

---

spyder/app/mainwindow.py

If a plugin implements a compatibility check and it fails we were calling `show_compatibility_message` instead of `show_plugin_compatibility_message` causing an `AttributeError`
Fixes #18901

PR: Fix call to show compatibility message for plugins (Mainwindow)

---

spyder/api/plugins/new_api.py
spyder/api/widgets/main_widget.py
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/base.py
spyder/plugins/editor/confpage.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/explorer/plugin.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/widgets/debugging.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/layout/plugin.py
spyder/plugins/projects/plugin.py
spyder/plugins/tours/container.py
spyder/plugins/tours/plugin.py

- Avoid giving focus to the IPython console when it's undocked, the user runs/debugs code and `Maintain focus to editor` is enabled.
- Keep focus in the editor in any run or debug operation and that option is enabled.
- Unmaximize any plugin before running or debugging code.
- Correctly set the state of the `Maximize` button when unmaximizing a plugin programmatically from other plugins (this was totally broken).
- Add `sig_unmaximize_plugin_requested` to `SpyderPluginV2` so that plugins can request to unmaximize the currently maximized plugin from others programmatically.
- Add `unmaximize_dockwidget` and `unmaximize_other_dockwidget` methods to the Layout plugin. Also move `switch_to_plugin` to it.
- Expand tests to catch possible regressions in the future.
Fixes #3221
By submitting …

PR: Improve `Maintain focus in the editor` option and unmaximize plugins when running/debugging code

---

spyder/app/mainwindow.py

.ico icon needs a resample to not get blurry on Windows taskbar
Fixes #18283

PR: Pass resample kwarg when getting .ico icon for Windows

---

spyder/api/plugins/new_api.py
spyder/api/widgets/main_container.py
spyder/api/widgets/main_widget.py
spyder/plugins/console/plugin.py
spyder/plugins/console/widgets/main_widget.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/plots/widgets/main_widget.py
spyder/plugins/profiler/widgets/main_widget.py
spyder/plugins/pylint/plugin.py
spyder/plugins/tours/container.py
spyder/plugins/tours/plugin.py
spyder/plugins/variableexplorer/plugin.py
spyder/plugins/variableexplorer/widgets/main_widget.py

- This was an oversight in PR #18928.
- I need it to fix our tests in master.
- Use this addition in the Tours plugin because it's more natural.
- Connect `PluginMainWidget` default signals to its plugin (we were only doing that for `PluginMainContainer`). Some things were broken due to that and others are now redundant.

PR: Add the ability to request unmaximizing plugins from widgets

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/debugger/widgets/main_widget.py

Also fix `test_maximize_minimize_plugins`. This test was expanded in PR #18928, but it needs some changes to work in master. That's because it relies on a couple of debugger actions, which are now present in the Debugger plugin.

PR: Unmaximize debugger plugin when running debug commands

---

bootstrap.py
spyder/api/plugins/new_api.py
spyder/app/mainwindow.py
spyder/plugins/application/plugin.py
spyder/plugins/completion/plugin.py
spyder/plugins/completion/providers/languageserver/widgets/messagebox.py
spyder/plugins/completion/tests/conftest.py
spyder/plugins/preferences/plugin.py
spyder/plugins/preferences/tests/conftest.py
spyder/plugins/preferences/widgets/container.py

- Instances of `SpyderPluginV2`, `PluginMainWidget` and `PluginMainContainer` now only need to emit `sig_restart_requested` to ask for a Spyder restart.
- This was changed in PR #15629 to require the `Application` plugin, but it makes things more complicated.
- Remove `reset_spyder` method of `MainWindow` because it was not doing anything.
- Fix requesting multiple restarts when Spyder is started from `bootstrap.py`. Before only a single restart was possible.

PR: Allow plugins/widgets to ask for app restarts by emitting a signal

---

spyder/plugins/appearance/confpage.py
spyder/plugins/preferences/api.py

* If a custom syntax highlighting theme was named with a number errors could raise when trying to use the name to set widgets text/properties 
* Also, fix setting a default light theme when the current selected syntax highlighting theme is deleted
Fixes #18929

PR: Add cast for custom syntax highlighting themes names to string (Appereance)

---

spyder/widgets/tabs.py

* Seems like on MacOS the elide mode for QTabWidget is different from `Qt.ElideNone` which caused the tabs text to be elided at the right on MacOS.
* Clean/remove unused imports (`os` and `sys`  modules)
Fixes #18817

PR: Set elide mode to prevent tabs text eliding on MacOS (Tabs)

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole/widgets/main_widget.py

PR: Fix focus when debugging cells

---

spyder/plugins/ipythonconsole/widgets/main_widget.py

- After doing `git bisect`, I noticed that the problem reported on issue #19084 was introduced by PR #18781.
- The simplest way to fix it is to restore the changes done in it to the way all clients are closed.
Fixes #19084.

PR: Restore the previous way of closing all clients (IPython console)

---

spyder/utils/programs.py

Prevent showing text that is not expected when doing `<interpreter_path> -V` to get interpreter info. The expected result should pass the following regex: `^Python \d+\.\d+\.\d+$`. For example: `Python 3.10.5`
Fixes #19000

PR: Add regex check for interpreter info output (Programs)

---

spyder/plugins/completion/plugin.py

- It seems that sometimes the text of the Main Interpreter status bar widget can contain several parenthesis (see issue #19000), which causes an error when trying to only take the first value after splitting a string according to open parenthesis.
- This probably doesn't fix the whole problem, but it solves the one reported by users for now.
Fixes #19087 

PR: Avoid a ValueError when splitting a string (Completions)

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/explorer/plugin.py
spyder/plugins/explorer/widgets/explorer.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/workingdirectory/plugin.py

- This was working before but I don't know when it broke. Now it works in three ways:
1. When switching between consoles.
2. When opening new consoles.
3. When opening/closing projects.
- Add tests to check that the Working directory toolbar and Files are updated in those cases.
- Set the right working directory when opening a console from Files (this was reported on issue #19003).
- Restore functionality of IPython console's public API method `set_working_directory`, which I broke in PR #18544.
- Add a new method to it called `save_working_directory` to save the cwd reported by the Working directory plugin. This is necessary to start new consoles.
- Rename some methods related to the cwd in the IPython console for clarity.
Fixes #19003
By submitting this Pull Request or typing my …

PR: Fix syncing IPython console cwd with the Working directory toolbar

---

spyder/plugins/maininterpreter/widgets/status.py
spyder/utils/programs.py

Checking #19082 I noticed that the info for the default interpreter for the Windows standalone installer was not showing (it was empty - `Custom ()`). Checking this seems being caused due to the launch of Spyder from the shortcut using `pythonw.exe` instead of `python.exe` (to prevent showing any cmd/terminal) and also some logic trying to check for a fixed path for the Windows installer.
The actual value that should appear for the current Windows installer is `internal (Python 3.8.10)` …

PR: Handle default Win installer pythonw interpreter to get Python version (Status)

---

spyder/plugins/findinfiles/tests/test_plugin.py
spyder/plugins/findinfiles/widgets/main_widget.py
spyder/plugins/findinfiles/widgets/results_browser.py
spyder/plugins/findinfiles/widgets/search_thread.py
spyder/plugins/findinfiles/widgets/tests/test_widgets.py

- Catch any error when trying to create file items.
- Prevent showing file entries without any match. This was happening sometimes when the maximum number of results is reached.
For example, searching for `self` in the main Spyder repo when the max results is 15 was giving this
Now it gives this
Fixes #17443
Fixes #16256 

PR: Fix a couple of bugs in the Find plugin

---

spyder/plugins/projects/api.py
spyder/plugins/projects/plugin.py
spyder/plugins/projects/tests/test_plugin.py

- Remove the project's config directory in case of errors and generate it again.
- This makes the process of opening projects more robust, which should avoid crashes at startup when a project is left open in the previous session and we can't read its config during the next one.
Fixes #17907.

PR: Recreate config in case of errors while reading it (Projects)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/console/shell.py
spyder/plugins/ipythonconsole/__init__.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/utils/kernelspec.py
spyder/plugins/ipythonconsole/widgets/__init__.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/utils/programs.py

If the version of spyder and spyder kernels doesn't match, the user will see many errors. This PR show an error if spyder-kernels has an incompatible version. 
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/408
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/409

PR: Improve validation for the right Spyder-kernels version

---

spyder/api/plugins/__init__.py
spyder/api/plugins/enum.py
spyder/api/plugins/new_api.py
spyder/app/mainwindow.py
spyder/plugins/base.py
spyder/plugins/completion/tests/conftest.py
spyder/plugins/layout/api.py
spyder/plugins/layout/layouts.py
spyder/plugins/layout/plugin.py
spyder/plugins/preferences/tests/conftest.py
spyder/plugins/profiler/plugin.py
spyder/plugins/pylint/plugin.py
spyder/plugins/pylint/tests/test_pylint.py
spyder/plugins/workingdirectory/tests/test_workingdirectory.py

- Fix tabifying external and internal plugins (e.g. Spyder-notebook and Debugger) that are loaded after Spyder runs for the first time.
- Move methods related to tabifying plugins from MainWindow to the Layout plugin.
- Fix error when trying to restore visible plugins that are no longer available (this error was reported by @dalthviz).
- Show visible external plugins when switching layouts. For instance, if Spyder-notebook is displayed in the interface and the user switches to the Matlab layout, then that plugin is displayed again (it was not before).
- Fix `TABIFY` class attribute for the Pylint and Profiler plugins.
- Reorganize code a bit in the Layout plugin. …

PR: Several fixes related to the tabify plugins functionality

---

spyder/plugins/editor/utils/autosave.py

This error can happen when a file is changed externally but it's left unsaved in Spyder.
Fixes #19283.

PR: Catch error when removing autosave files (Editor)

---

spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/toolbar/plugin.py

Those attributes are no longer needed because the Main toolbar was migrated to the new API a long time ago.

PR: Remove `main_toolbar` and `main_toolbar_actions` attributes (Main Window)

---

spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/utils/stylesheet.py

- Remove blank pixels in widgets with tabs (i.e. the IPython console and the editor).
- Move time label to be first from left to right in the IPython console. That avoids a space wider than normal between the options button and the stop one. 
**Before**
**After**

PR: Improve style of the IPython console a bit

---

spyder/widgets/dependencies.py

Use the error and warning colour that indicate that a dependency is not met, as background instead of foreground colours. This increases readability and seems to be in keeping with the discussion at spyder-ide/ux-improvements#13.
Screenshot of the Dependencies dialog after the PR is applied (I changed the required version of three-merge for the picture):
For comparison, here is the corresponding screenshot of the current version:
Fixes #13090

PR: Change colours in Dependencies dialog window

---

spyder/plugins/debugger/plugin.py
spyder/plugins/debugger/utils/breakpointsmanager.py
spyder/plugins/debugger/widgets/framesbrowser.py
spyder/plugins/debugger/widgets/main_widget.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/tests/conftest.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/widgets/debugging.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py

PR: Move debug functions from IPython plugin to debugger plugin

---

spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/breakpoints/plugin.py
spyder/plugins/debugger/api.py
spyder/plugins/debugger/confpage.py
spyder/plugins/debugger/plugin.py
spyder/plugins/debugger/widgets/main_widget.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/tests/test_editor_config_dialog.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/mainmenu/api.py
spyder/plugins/mainmenu/plugin.py
spyder/plugins/toolbar/plugin.py

- Complement the work done by @impact27 on the Debugger plugin by using the new API to handle its toolbar and menu. 
- Remove old references to them on MainWindow.
- Add actions that control the debugger (i.e. Step into, Continue, etc) to the Debug menu. This restores feature parity with Spyder 5.
**Before**
**After**

PR: Use new API to handle creation and removal of debug toolbar and menu

---

external-deps/python-lsp-server/.gitrepo
external-deps/python-lsp-server/CHANGELOG.md
external-deps/python-lsp-server/CONFIGURATION.md
external-deps/python-lsp-server/README.md
external-deps/python-lsp-server/RELEASE.md
external-deps/python-lsp-server/pylsp/config/config.py
external-deps/python-lsp-server/pylsp/config/schema.json
external-deps/python-lsp-server/pylsp/plugins/jedi_completion.py
external-deps/python-lsp-server/pylsp/plugins/symbols.py
external-deps/python-lsp-server/pyproject.toml
external-deps/python-lsp-server/test/__init__.py
external-deps/python-lsp-server/test/plugins/test_completion.py
external-deps/python-lsp-server/test/plugins/test_pylint_lint.py
spyder/app/tests/conftest.py
spyder/app/tests/script_outline_3.py
spyder/app/tests/script_outline_4.py
spyder/app/tests/test_mainwindow.py
spyder/config/lsp.py

- Those are packages that don't have an `__init__.py` in the root of their repository.
- Also avoid showing relative imports in the Outline.
- Move `main_window` fixture to its corresponding `conftest.py` file to make it easier to contribute to it.
- Add tests to catch future regressions for these bugs.
- Depends on https://github.com/python-lsp/python-lsp-server/pull/261.
- No symbols for namespace packages
- Showing relative imports in multiple lines as symbols
- Symbols are shown for namespace packages
- Relative imports in multiple lines are not shown
Fixes #16406.
Fixes #16352.
and …

PR: Show symbols for namespace packages in the Outline

---

spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/projects/plugin.py

- Projects plugin now calls `update_python_path` instead of `pythonpath_changed` because `pythonpath_changed` only had the effect of ensuring that the project path never made it into `spyder_pythonpath`.
- `update_python_path` now correctly retrieves the existing path dictionary _before_ it is updated.
- Existing and new path dictionaries are compared to avoid unnecessary file read/writes and unnecessary notifications.
- Regression test added to the mainwindow test ensuring that project path is added to `spyder_pythonpath`.
Fixes #19205
and understand I am releasing the same under …

PR: Ensure that project path is added to `spyder_pythonpath`

---

spyder/plugins/editor/widgets/tests/test_save.py
spyder/plugins/outlineexplorer/editor.py
spyder/plugins/outlineexplorer/tests/assets/text_exp_test_widgets.json
spyder/plugins/outlineexplorer/tests/assets/text_test_widgets.json
spyder/plugins/outlineexplorer/tests/assets/text_test_widgets.py
spyder/plugins/outlineexplorer/tests/test_widgets.py
spyder/plugins/outlineexplorer/widgets.py

- Symbols were pointing to the original file instead of the renamed one. This PR fixes that by deleting the current symbols and requesting them for the new file.
**Before**
**After**
- Add a regression test for this.
- Expand Outline tests to check that we can display special comments and cells.
- Remove some dead code in the Outline and its tests.
Fixes #15517

PR: Reload symbols when saving a file through the `Save as` menu entry (Outline)

---

spyder/plugins/editor/widgets/editor.py

Autoformat is meant to be done only to Python files, trying do it on non Python files ends up in the launch of a never ending autoformat process
Fixes #19344
Fixes #19248
Fixes #17577
Fixes #16166 

PR: Only autoformat on save if the file is a Python file (Editor)

---

spyder/plugins/application/container.py
spyder/plugins/application/plugin.py
spyder/plugins/application/widgets/__init__.py
spyder/plugins/application/widgets/install.py
spyder/plugins/application/widgets/status.py
spyder/plugins/statusbar/plugin.py

* Show download status and status bar icon (Spyder version, if checking for updates, if an update is pending, downloading installer, installing, etc)
* Logic to download and run the new Windows/MacOS installer version if available
Part of #19112 
I certify the above statement is true and correct: @jsbautista

PR: Improve update UX and automatically download latest installers

---

spyder/plugins/pylint/main_widget.py

The process from where Pylint is launched didn't include the APPDATA dir on Windows which caused some installations to not recognie the installed Pylint version.
Fixes #19385

PR: Add `APPDATA` environment variable to Pylint process (Pylint)

---

spyder/api/plugins/new_api.py
spyder/plugins/breakpoints/plugin.py
spyder/plugins/completion/providers/kite/widgets/install.py
spyder/plugins/console/widgets/shell.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/editor/widgets/editorstack_helpers.py
spyder/plugins/explorer/widgets/explorer.py
spyder/plugins/explorer/widgets/fileassociations.py
spyder/plugins/history/widgets.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/layout/container.py
spyder/plugins/projects/widgets/qcookiecutter.py
spyder/plugins/pylint/main_widget.py
spyder/plugins/pylint/plugin.py
spyder/plugins/shortcuts/plugin.py
spyder/plugins/variableexplorer/widgets/arrayeditor.py
spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/requirements.py
spyder/widgets/browser.py

Remove unnecessary lambdas from signals
A lambda prevents qt from keeping a reference to the object, leading to:
```
RuntimeError: wrapped C/C++ object of type xxxx has been deleted
```
Fixes #19393

PR: Remove lambdas in Qt slots

---

spyder/plugins/debugger/widgets/main_widget.py

Add a button to go to the currently debugged line if the editor was moved.
I certify the above statement is true and correct: impact27

PR: Add button to debugger plugin to go to editor

---

spyder/utils/icon_manager.py

- SVG icons were looking like this in high dpi screens or when Spyder's `custom high DPI scaling` is set to `2.0` in Preferences:
Now they look like this
- This regression was introduced in PR #17811, when trying to set the disabled state of SVG icons.
Fixes #19520.

PR: Fix showing pixelated SVG icons on high dpi screens

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/tests/conftest.py
spyder/plugins/editor/tests/test_plugin.py
spyder/plugins/mainmenu/plugin.py

Fix two issues when Projects plugin is disabled:
* Fix re-opening of files from previous session when Projects plugin is disabled. Added test.
* Don’t add empty Projects menu when Projects plugin is disabled
rear1019

PR: Fix errors when Projects plugin is disabled

---

installers/macOS/req-build.txt

To prevent the MacOS installer build check from failing on PRs ping `sphinx` to be `5.1.1`
Fixes #19618

PR: Pin Sphinx to version 5.1.1 to prevent errors on MacOS installer build

---

spyder/plugins/findinfiles/widgets/tests/test_widgets.py

looks like the results of findinfiles.find() aren't deterministic and it's causing test_no_empty_file_items to fail
Fixes #19602
stevetracvc

PR: Temporary fix for function `test_no_empty_file_items`

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
installers/Windows/installer.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

- Update way tkinter assets are copy to build Windows installers
- Fix spyder-kernels debug handling of the Tkinter backend
- Depends on spyder-ide/spyder-kernels#415.
- Depends on [spyder-ide/windows-installer-assets release 0.9.0](https://github.com/spyder-ide/windows-installer-assets/milestone/2)
Fixes #17523

PR: Update Tkinter assets copy logic for the Windows installer and fix Tkinter backend handling when debugging

---

spyder/plugins/findinfiles/widgets/tests/test_widgets.py

This is the alternative simplification to this test discussed in #19602.  Since the purpose of this test is to ensure that there are no results picked up from files which do not match the search string, this simplified test only tests that rather than the precise details of the results obtained.  (Since `findinfiles` returns a non-deterministic result, the alternative is the current approach of listing all possible results.)

PR: Simplify `test_no_empty_file_items` to only check filenames and total number of results

---

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py

- Even though we warn about unsupported file extensions when users try to use them to load data to the Variable Explorer (e.g. a Python file), we were throwing an error about it, which is incorrect.
- This PR catches that error and shows an appropriate message instead:
**Before**
**After**
Fixes #19126

PR: Catch error when trying to load unsupported data files (IPython console)

---

spyder/app/mainwindow.py
spyder/plugins/application/container.py
spyder/plugins/application/plugin.py
spyder/utils/environ.py
spyder/utils/programs.py
spyder/utils/tests/test_environ.py
spyder/widgets/collectionseditor.py
spyder/widgets/pathmanager.py

- Provides a general tool for retrieving user environment variables: `spyder.utils.programs.get_user_environment_variables`. This returns a dictionary of string values.
- Updates `spyder.util.environ` classes and functions to be platform agnostic. Most notably, `WinUserEnvDialog` is renamed `UserEnvDialog`. The associated menubar item is now available on all platforms, though these are read-only, while Windows retains the ability to modify and export to the system environment.
- Removes Python 2.x dependence in `spyder.util.environ`.
#17512 Introduced a feature to import the user's `PYTHONPATH` environment variable into the PYTHONPATH Manager. This relies on Spyder inheriting this variable at runtime into `os.environ`. However, it may be more desirable to retrieve this environment …

PR: Show environment variables for all operating systems and modernize `spyder.utils.environ` module

---

spyder/api/widgets/auxiliary_widgets.py
spyder/api/widgets/main_widget.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/tests/test_editor_and_outline.py
spyder/plugins/editor/widgets/tests/test_save.py
spyder/plugins/outlineexplorer/editor.py
spyder/plugins/outlineexplorer/main_widget.py
spyder/plugins/outlineexplorer/tests/test_widgets.py
spyder/plugins/outlineexplorer/widgets.py

* Simplify and greatly speed up updating trees when new symbols arrive from PyLSP. For instance, this decreases the time necessary to update the tree of our `codeeditor.py` file from 700 ms to 30 ms in my laptop.
* Update trees when the Outline is undocked, but not if its window is minimized.
* Avoid the Editor plugin to update current tree when given focus (this was very inefficient).
* Dock plugins if they are undocked before hiding them when going to the `Panes > View` menu. I discovered that UX bug while working on this PR.
* Add a test to check that we update (don't update) the Outline when it becomes visible (is not visible) under different circumstances.
Fixes #16634 …

PR: Greatly improve Outline performance and update it correctly when it becomes visible

---

spyder/plugins/application/container.py
spyder/plugins/application/widgets/install.py
spyder/plugins/application/widgets/status.py
spyder/workers/updates.py

See https://github.com/spyder-ide/spyder/issues/19112#issuecomment-1228678444
A preview showing the new dialog without having the installer downloaded:
A preview showing the new dialog when the installer was already downloaded previously:
Part of #19112

PR: Add dialog to confirm downloaded installer installation and update related code organization (Application)

---

binder/environment.yml
installers/macOS/packages.py
installers/macOS/test_app.sh
requirements/main.yml
setup.py
spyder/dependencies.py
spyder/plugins/pylint/main_widget.py
spyder/plugins/pylint/tests/test_pylint.py

Added a function to get the path of the custom interpreter if one is active. Then activating the custom environment in pylint via an init-hook and the pylint_venv package.
Open question: Where pylint_venv should be added in the requirements (only available in pip)?
Fixes #15709
I certify the above statement is true and correct: mwawra

PR: Add environment of custom interpreter to Pylint plugin

---

spyder/config/main.py

- Changed "find next" to "Ctrl+G" and "find previous" to "Ctrl+Shift+G" for macOS in the `find_replace` context.
- Changed "switch to plots" to "Shift+F3" and "go to definition" to "F3" for macOS.
Fixes #15437

PR: Conform "find next" and "find previous" shortcuts to macOS standards

---

spyder/plugins/application/widgets/status.py

PR: Show installer download percentage progress in the status bar (Application)

---

spyder/widgets/browser.py

It seems Web widgets of MSys2 packages don't provide the `focusProxy` method. So, we need to catch the error generated due to that.
Fixes #19818.

PR: Catch an error when loading pages in `WebView` widgets

---

.gitignore
bootstrap.py

PR: Do not import spyder before install_repo in bootstrap.py

---

install_dev_repos.py

- I don't know when this stopped working, but now it introduces a huge delay when using `bootstrap.py`.
- I'm going to merge this to keep working during the weekend. But if someone else finds a better solution, please submit another PR for it.
Fixes #19712 

PR: Fix detecting that python-lsp-server is installed in editable mode (Development)

---

RELEASE.md
spyder/plugins/ipythonconsole/__init__.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/ipythonconsole/widgets/main_widget.py

- If users change their interpreter in `Preferences > Main Interpreter` to one without Spyder-kernels or the right version of it, we were showing the following after a restart:
Now we show this
- Disable kernel related actions when it fails to start because it makes no sense to have them enabled.
- Add a test that checks this.

PR: Show Spyder-kernels message on restarts (IPython console)

---

spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/completion.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/editor/widgets/tests/test_completions_hide.py
spyder/plugins/editor/widgets/tests/test_save.py

- The previous solution hid the widget so the corresponding shortcut could take effect on its parent. However, that had some odd side effects, like for example that pressing `Shift` to get an underscore or a capitalized letter hid and showed the completion widget, which was annoying:
- Now we detect the keyboard shortcut corresponding to Save in the Completion widget and ask its CodeEditor to perform that operation, so there are no side effects involved (the gif shows both saving and pressing `Shift`):
Fixes #19372  …

PR: Improve how to save a file when the completion widget is visible (Editor)

---

bootstrap.py

Missing Windows case to call git from subprocess from `bootstrap.py`
Fixes #19865 

PR: Fix `bootstrap.py` git subprocess call on Windows

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py

- We're not sure if this will solve the problem (see https://github.com/spyder-ide/spyder/issues/19735#issuecomment-1277218194), but it's the best we can do at the moment.
- Depends on spyder-ide/spyder-kernels#420 and spyder-ide/spyder-kernels#422
Fixes #19735 

PR: Prevent error when multiple threads try to write messages from comm handlers (IPython console)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/customize/utils.py

According to issue #19862, this is one of the most important things that is failing on that Python version.
Fixes #19862.

PR: Fix cell execution on Python 3.11 (IPython console)

---

spyder/plugins/application/widgets/install.py

The change in the size of the cancel button was not the correct one:
Before (changes done at #19871 ):
With this change:

PR: Update download installer update cancel button size (Application)

---

.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml
external-deps/qtconsole/.github/workflows/linux-tests.yml
external-deps/qtconsole/.github/workflows/macos-tests.yml
external-deps/qtconsole/.github/workflows/windows-tests.yml
external-deps/qtconsole/.gitrepo
external-deps/qtconsole/qtconsole/completion_html.py
external-deps/qtconsole/qtconsole/completion_widget.py
external-deps/qtconsole/qtconsole/console_widget.py
external-deps/qtconsole/qtconsole/qtconsoleapp.py

- This was fixed before for Windows and Linux in #18439.
Fixes #19888

PR: Fix out-of-order insertion of mixed stdin and stdout streams on macOS (IPython console)

---

.github/scripts/install.sh
external-deps/python-lsp-server/.gitrepo
external-deps/python-lsp-server/CONFIGURATION.md
external-deps/python-lsp-server/pylsp/_utils.py
external-deps/python-lsp-server/pylsp/config/config.py
external-deps/python-lsp-server/pylsp/config/schema.json
external-deps/python-lsp-server/pylsp/plugins/autopep8_format.py
external-deps/python-lsp-server/pylsp/plugins/hover.py
external-deps/python-lsp-server/pylsp/plugins/jedi_completion.py
external-deps/python-lsp-server/pylsp/plugins/rope_completion.py
external-deps/python-lsp-server/pylsp/plugins/signature.py
external-deps/python-lsp-server/pylsp/plugins/yapf_format.py
external-deps/python-lsp-server/pylsp/workspace.py
external-deps/python-lsp-server/pyproject.toml
external-deps/python-lsp-server/scripts/jsonschema2md.py
external-deps/python-lsp-server/setup.py
external-deps/python-lsp-server/test/plugins/test_autopep8_format.py
external-deps/python-lsp-server/test/plugins/test_completion.py
external-deps/python-lsp-server/test/plugins/test_hover.py
external-deps/python-lsp-server/test/plugins/test_signature.py
external-deps/python-lsp-server/test/plugins/test_yapf_format.py
installers/macOS/req-extras.txt
spyder/plugins/completion/api.py
spyder/plugins/editor/widgets/completion.py
spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py
spyder/plugins/outlineexplorer/widgets.py
spyder/widgets/mixins.py

- Request documentation in plain text to the server because it sends it now by default as Markdown, which we can't handle.
- Fix error when showing completion hints due to the previous change in the server as well.
- Fix not showing hovers for objects without docstrings. Signatures that come from the server are now separated from two LF characters, which was causing this problem.
- Update outline if a tree is empty but it has cached items from the server. I discovered this bug while working with Spyder these days and although it's not caused by a server update, I think it's important to fix it because it makes the Outline display files with no symbols when they actually have symbols for it.
I affirm the [Developer Certificate …

PR: Some fixes to make Spyder work with the latest changes in PyLSP

---

spyder/plugins/ipythonconsole/widgets/main_widget.py

- This uses the new API to build it instead of passing the Options menu actions to the `Tabs` widget, as before.
- That way we don't need to show the entire Options menu on the tabs context one. Instead, I decided to show only its first two sections, which are the most important ones.
Fixes #19991.

PR: Restore context menu on tabs (IPython console)

---

CONTRIBUTING.md

When updating subrepos in Spyder using the current instructions (`git subrepo clone`), the remote specification in `.gitrepo` is not updated to reflect the cloned remote, but remains as the original upstream specification. 
This can be an issue for any process that requires access to the remote repository at the commit and/or branch specified in `.gitrepo`, since that commit and/or branch may not exist on the (incorrectly) specified remote. The conda-based installers are an example of such a process.
This PR changes the instructions to use `git subrepo pull ... -r <remote> -u` to ensure that the remote specification is also updated.
with respect …

PR: Update remote when syncing subrepos

---

spyder/plugins/application/container.py

The application update status bar is only initialized for the standalone installers but no validations were added to prevent calling it inside the check updates logic available for all types of Spyder installations (standalone installers, conda, pip, etc).
Fixes #20035

PR: Add validation to prevent calling uninitialized `application_update_status` widget on conda installations (Application)

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole/widgets/main_widget.py

Added the option to run in a dedicated console without clearing variables. I forgot to make a branch in #19984 so I'm replacing it with this one.
Added the option to run in a dedicated console without clearing variables because it seems like that should be an option and I like my interactive plot windows to stay in place and not pop up all the time
Fixes #19983 

PR: Correctly handle the option to run in a dedicated console without clearing variables

---

.github/workflows/test-files.yml
.github/workflows/test-linux.yml
external-deps/python-lsp-server/.gitrepo
external-deps/python-lsp-server/CONFIGURATION.md
external-deps/python-lsp-server/README.md
external-deps/python-lsp-server/docs/autoimport.md
external-deps/python-lsp-server/pylsp/config/config.py
external-deps/python-lsp-server/pylsp/config/flake8_conf.py
external-deps/python-lsp-server/pylsp/config/schema.json
external-deps/python-lsp-server/pylsp/plugins/flake8_lint.py
external-deps/python-lsp-server/pylsp/plugins/rope_autoimport.py
external-deps/python-lsp-server/pylsp/python_lsp.py
external-deps/python-lsp-server/pylsp/workspace.py
external-deps/python-lsp-server/pyproject.toml
external-deps/python-lsp-server/test/fixtures.py
external-deps/python-lsp-server/test/plugins/test_autoimport.py
spyder/api/widgets/auxiliary_widgets.py
spyder/plugins/outlineexplorer/main_widget.py

* Currently the `python-lsp-server` subrepo is pointing to the v1.6.0 tag (was needed to prevent errors on the CI tests while also being able to build the conda-based installers). This makes the subrepo point again to the develop branch
* Change the Python version we use to test to Python 3.8 and Python 3.10

PR: Update python-lsp-server subrepo and change CI Python versions

---

spyder/plugins/pylint/utils.py

- That module has some global constants that depend on the filesystem and can fail to be initialized due to e.g. a `PermissionError` (see issue #20079 for more context).
- Small style improvements to the module that imports `pylint.config`
Fixes #20079

PR: Prevent crash at startup if importing `pylint.config` fails (Code Analysis)

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/codeeditor.py

This kind of errors are usually generated when the user closes the current `EditorStack` or `EditorMainWindow` before a method that access those objects can be processed completely.
Fixes #20071
Fixes #20055

PR: Catch a couple of reported RuntimeError's (Editor)

---

spyder/app/mainwindow.py
spyder/requirements.py

PYTHONPATH entries are removed on start, resulting in a the warning shown on `check_path` in requirements - program does not start.
Removing pythonpath was added to disable shadowed base libraries, but I think thats exactly how the PYTHONPATH could and would behave.
Still it makes sense to remove them so that it does not create problems.
Yet the resulting warning
"Spyder must be installed properly (e.g. from source: 'python setup.py install'), or directory 'dir' must be in PYTHONPATH environment variable."
is not helpful and is removed through this PR
~~I would therefore not remove entries on PYTHONPATH from PATH~~ …

PR: Remove check_path to allow running in debugger

---

spyder/plugins/editor/widgets/gotoline.py
spyder/plugins/editor/widgets/tests/test_gotoline.py
spyder/plugins/variableexplorer/widgets/importwizard.py

Somehow Qt QIntValidator allows to enter only a plus sign: '+'
While searching for QIntValidator, I found another occurance in the import dialog of the variable explorer.
Supersedes #13333
Fixes #12693
I certify the above statement is true and correct: Florian Maurer

PR: Fix QIntValidator to handle '+' sign

---

spyder/plugins/completion/providers/languageserver/transport/tcp/producer.py

See commit message for details.
Notes:
* We have observed the fixed error on Linux only.
* There is a (remote) possibility that the fixed error is the one reported in #9557, #9755 and #10108.
* The fix in this PR is strictly speaking a workaround. The “proper” fix is to _not_ use a port from the ephemeral port range for the language server. 
rear1019

PR: Fix random rare error in completion plugin

---

spyder/utils/stylesheet.py

- I fixed this problem in #19297 for Linux but I noticed it's still present on Windows.
**Before**
**After**
- Remove unnecessary class constant.

PR: Remove white dots on IPython console tabbar for Windows

---

spyder/widgets/helperwidgets.py

Add default values for new parameters of `IconLineEdit` widget (`elide_text` and `ellipsis_place`). An error occurs when using an `IconLineEdit` on the `spyder-env-manager` plugin when using Spyder dev version. Not giving those params a default value could cause issues to external plugins using that widget (the old constructor signature).

PR: Add default value for `IconLineEdit` helper widget constructor params (Widgets)

---

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

This PR fixes the `test_kernel_crash` for usage with ipython>=8. (one of the failing tests from https://github.com/spyder-ide/spyder/pull/19817) 
It now uses one of the documented properties (e.g. `c.InteractiveShellApp.extra_extensions`, instead of ` c.InteractiveShellApp.extra_extension` , https://ipython.readthedocs.io/en/stable/config/options/terminal.html), but setting it to an invalid value to trigger an error.
The updated test is not actually executed with ipython8+, but has been tested locally. Addition of ipython 8+ is explored in https://github.com/spyder-ide/spyder/pull/19817 …

PR: Fix `test_kernel_crash` to work with IPython 8+

---

.github/scripts/install.sh
.github/workflows/test-linux.yml
spyder/plugins/editor/widgets/completion.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

- This allows users to easily move to the beginning/end of the current line when this widget is visible.
- Also, hide Completion widget if users press the save shortcut when it's visible to reassure them that that operation took place.
- Select Ubuntu 20.04 to run our tests on Github actions because some are failing with 22.04 (which now corresponds to `ubuntu-latest`).
- Remove restriction on Numpy 1.23 on CIs.
Fixes #19989.

PR: Pass Home/End key events from Completion to CodeEditor widget (Editor)

---

spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py

- The cursor was placed at the end of the file after auto-formatting took place, even when formatting selections, which was really annoying.
- Fix header comments in CodeEditor so they appear in Spyder's Outline.
- Add docstrings for auto-formatting methods in CodeEditor.
- Improve code style a bit here and there.
Fixes #19958.

PR: Restore cursor position after inserting auto-formatted text (Editor)

---

spyder/api/widgets/menus.py
spyder/plugins/mainmenu/plugin.py
spyder/plugins/shortcuts/plugin.py
spyder/plugins/tours/plugin.py

- This approach always adds a new section to the menu even if it needs to be inserted before another one which hasn't been added yet.
- The previous approach gave errors if a section required to be inserted before another one which was not added when, for instance, the plugin in charge of doing it is disabled.
- Also, don't show `Consoles` menu if the IPython console is disabled.
Fixes #19610 
Fixes #16161 

PR: Simplify the way we add sections to menus (API)

---

spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py
spyder/widgets/collectionseditor.py

- Before the kernel manager was raising a RuntimrError if the kernel is no longer available, which was correctly reported by our users here.
- Also, remove usage of `numpy.bool` in our tests because it's no longer present in Numpy 1.24
Fixes #20212.
I certify the above statement is true and correct: @ccordoba12.

PR: Inform users when kernel can't be interrupted (IPython console)

---

spyder/plugins/editor/widgets/tests/test_introspection.py
spyder/widgets/mixins.py

When doing completions, the LSP provides also completions for file names. Files that start with number were not completed correctly since a validation for valid Python variables was being always made when getting the current word and position.
Preview
Fixes #20156 

PR: Prevent Python variable validation to get current word and position when doing completions

---

.github/scripts/install.sh
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/ipythonconsole/widgets/shell.py

- This was failing because I incorrectly set the same check for normal usage and tests, so I removed it.
- Improve test that checks this so that it works for all operating systems.
- Improve a bit the message we show when the kernel can't be interrupted.
Fixes #20023

PR: Fix showing Spyder-kernels message on kernel restarts (IPython console)

---

.github/scripts/install.sh
spyder/plugins/ipythonconsole/widgets/shell.py

- I found this bug when testing PR #20233 on master.
- I also fixed the env we use for `test_conda_env_activation` on master.
I certify the above statement is true and correct: @ccordoba12.

PR: Fix a small kernel restart issue (IPython console)

---

.github/workflows/installers-conda.yml

Recent concurrency specifications in Spyder GitHub workflows (spyder-ide/spyder#20254) do not prevent `build-installers` jobs in `installers-conda.yml` from running under a certain circumstance. Example [PR: Cancel runs in progress when pushing new commits (CI) #250](https://github.com/spyder-ide/spyder/actions/runs/3768853668)
Concurrence cancels jobs that are pending or currently running. However, `build-installers` jobs are neither pending nor running until _after_ `build-matrix` and `build-noarch-conda-pkgs` jobs are all complete. In the circumstance that one or more of these jobs is not complete, they will be cancelled but `build-installers` jobs will then commence.
This PR should remedy this by replacing the conditional for `build-installers` jobs with explicit dependence on the …

PR: Fix concurrency for installers-conda workflow

---

installers/macOS/req-build.txt
installers/macOS/req-scientific.txt

- The app is failing to build with 0.28.5, released five hours ago.
- Also, remove restriction on Numpy because it's no longer necessary.

PR: Require py2app 0.28.4 for the Mac installer

---

spyder/utils/icon_manager.py
spyder/widgets/comboboxes.py
spyder/widgets/findreplace.py
spyder/widgets/tests/test_findreplace.py

- The current icon (the warning one) did not represent correctly the lack of matches after searching for text.
**Before**
**After**
- This is a follow-up of #20049.
Fixes #20255.

PR: Use a better icon when no matches are found (Find/Replace widget)

---

runtests.py
spyder/api/_version.py
spyder/api/plugins/new_api.py
spyder/api/widgets/auxiliary_widgets.py
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/tests/test_plugin.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/outlineexplorer/editor.py
spyder/plugins/outlineexplorer/main_widget.py
spyder/plugins/outlineexplorer/plugin.py
spyder/plugins/outlineexplorer/widgets.py

- Remove EditorStacks present on EditorMainWindow when it's closed. We were not removing them from the list of EditorStacks maintained by the plugin, which made the Editor unusable by generating endless RuntimeErrors. 
- Fix Outline displayed on EditorMainWindow, which was not showing any symbol.
- Update Outline for cloned editors after editing text in them (this was not working).
- Update symbols when switching between cloned editors (this was not working either).
- Don't update Outline if EditorMainWindow or MainWindow are minimized (to avoid lags on the main interface if they are not visible).
- Add `sig_mainwindow_state_changed` to plugins so they can take different actions when the main window is maximized/minimized.
- Expand tests to check Outline is working on EditorMainWindow. …

PR: Several fixes for new Editor windows

---

external-deps/python-lsp-server/.gitrepo
external-deps/python-lsp-server/CONFIGURATION.md
external-deps/python-lsp-server/pylsp/config/schema.json
external-deps/python-lsp-server/pylsp/plugins/definition.py
external-deps/python-lsp-server/pylsp/plugins/hover.py
external-deps/python-lsp-server/pylsp/plugins/pylint_lint.py
external-deps/python-lsp-server/pylsp/plugins/symbols.py
external-deps/python-lsp-server/test/plugins/test_definitions.py
external-deps/python-lsp-server/test/plugins/test_pylint_lint.py
spyder/config/lsp.py

- PyLSP has now an option called `auto_import_modules` that makes Jedi directly import modules passed to it to provide completions for them. And that significantly improves completions and help for Numpy, Pandas, Matplotlib and Scipy.
- Disable the new PyLSP plugin for ruff until we have a graphical option for users to enable it.
- Resync latest PyLSP to see if our tests pass before releasing 5.4.1
Part of issue #20026 

PR: Improve completions for scientific modules (Code completion)

---

external-deps/python-lsp-server/.gitrepo
external-deps/python-lsp-server/pylsp/plugins/pydocstyle_lint.py
external-deps/python-lsp-server/pylsp/plugins/pylint_lint.py
external-deps/python-lsp-server/pyproject.toml

- This was broken with the new 6.2.0 release of Pydocstyle.
- Depends on https://github.com/python-lsp/python-lsp-server/pull/329

PR: Fix pydocstyle linting

---

spyder/app/tests/test_mainwindow.py

- This started to happen when we merged support for IPython 8 (don't know why).
- It's not urgent to solve for now, but we should get back to it later.

PR: Skip a test that started to fail on Windows

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/utils/dochelpers.py
spyder/plugins/ipythonconsole/widgets/shell.py

- We were using a function to get signatures which is deprecated since Python 3.5 and removed in Python 3.11. So, that's giving an error now in the latter version.
- Depends on spyder-ide/spyder-kernels#435.
Fixes #20296.

PR: Fix getting object signature from kernel in Python 3.11 (IPython console)

---

spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/tests/test_formatting.py

- The previous solution was giving a segfault when auto-formatting on save is enabled.
- Add test to check this functionality and auto-formatting on save.
Fixes #20282.

PR: Fix restoring current cursor line after autoformat takes place (Editor)

---

spyder/utils/environ.py

This function is now used indirectly by the Pythonpath plugin, so any error causes a crash at startup.
Fixes #20309.

PR: Catch any possible error when trying to get the user environment variables (Utils)

---

.github/workflows/installer-macos.yml
.github/workflows/installer-win.yml
.github/workflows/installers-conda.yml
RELEASE.md

The installer workflows will now run the same way for both a release event _or_ a push of a release candidate tag.
- Pushing a tag of the form `v*pre*` (e.g. `v5.4.2pre1`) will run these workflows in the same manner as a release
- Artifacts are uploaded, but _not_ uploaded to a release.

PR: Update installer workflows to run as release on push of `pre` tag

---

installers-conda/build_conda_pkgs.py

* Use `git diff` instead of `git format-patch`. This is more reliable on Linux and is the correct way to do it.
* ~~Do not normalize the tag name. This prevents `setuptools_scm` from replacing 'pre' with 'rc' in the version string.~~

PR: Fix patch for conda-based installers

---

external-deps/spyder-kernels/.github/workflows/linux-tests.yml
external-deps/spyder-kernels/.github/workflows/macos-tests.yml
external-deps/spyder-kernels/.github/workflows/windows-tests.yml
external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/requirements/posix.txt
external-deps/spyder-kernels/requirements/windows.txt
external-deps/spyder-kernels/setup.py

- New changes in PyZMQ 25 introduced some errors in jupyter-client, which were already fixed and released in its 7.4.9 version.
- Those errors break our IPython console, which is why we need to rely on that version now.
Fixes #20359.

PR: Rely on `jupyter-client` 7.4.9+ because it's compatible with PyZMQ 25 (IPython console)

---

.github/scripts/install.sh
.github/workflows/test-win.yml
external-deps/python-lsp-server/.gitrepo
external-deps/python-lsp-server/pylsp/plugins/jedi_completion.py
external-deps/python-lsp-server/pylsp/plugins/pylint_lint.py
external-deps/python-lsp-server/pyproject.toml
external-deps/python-lsp-server/test/plugins/test_completion.py
spyder/plugins/editor/extensions/closequotes.py
spyder/plugins/editor/extensions/tests/test_closequotes.py
spyder/plugins/editor/widgets/base.py
spyder/plugins/editor/widgets/tests/test_introspection.py
spyder/plugins/ipythonconsole/utils/tests/test_spyder_kernel.py
spyder/plugins/ipythonconsole/widgets/client.py

- Completions were not introduced correctly when one was selected in the completion widget after they were triggered automatically next to a dot.
- Fix introducing completions for files and directories that start with a dot (they were not introduced correctly either).
- Fix introducing completions for files and directories in empty strings, i.e. you can hit `Tab` in a empty string (`"<Tab>"`) and Jedi will provide file completions in that case. The problem was the selected entry was not placed correctly in the editor either.
- Fix introducing file and directory completions next to a path separator (i.e. `os.sep`).
- Expand tests to cover all those cases.
- Depends on https://github.com/python-lsp/python-lsp-server/pull/337
Fixes #20331 
By submitting this Pull Request or typing my …

PR: Introduce completions correctly for autocompletion characters and improve file completions (Editor)

---

.github/scripts/install.sh

- Tests started to hang in `master` since last week and this solves it.
- This probably happens due to issue #20381, which should be fixed in Jupyter-client 8.

PR: Pin PyZMQ to version 24 to prevent hangs in our CIs

---

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

- That version introduced a regression that broke the Tk backend, so the test can't pass successfully with it.
- I'll make sure that future IPykernel versions fix it.

PR: Skip `test_tk_backend` on Windows with IPykernel 6.21.0

---

spyder/app/tests/conftest.py
spyder/app/tests/test_mainwindow.py
spyder/py3compat.py

This is required to have compatibility with the latest version of `spyder-line-profiler`.
I also made the following fixes to our test suite, which I noticed after merging PR #20425:
- Make `test_switch_to_plugin` run before `test_tour_message`. This makes that test pass the first time is run, instead of requiring a second time.
- Move `preferences_dialog_helper` to the main window `conftest.py` files and mark some of its tests as flaky. This makes the main window tests more reliable.
Fixes #20430.
I certify the …

PR: Restore `pickle` import in `py3compat.py` and some fixes to the main window tests

---

.github/workflows/installer-macos.yml
.github/workflows/installer-win.yml
.github/workflows/installers-conda.yml
RELEASE.md
installers-conda/build_conda_pkgs.py
installers-conda/build_installers.py

* Added workflow trigger for pull requests labeled `build-installer-artifacts`
* Added workflow trigger for manually running installers
* Fix issue where installer version normalized tag version
Pull requests will continue to trigger all three installer workflows with limited artifacts (Full versions only) and without code-signing or uploading artifacts.
Labeling a pull request with `build-installer-artifacts` or pushing a tag matching the pattern `v*pre*` will also trigger all three installer workflows, but they will run _as if_ it were a release (Lite and Full versions, code-signing, etc.). However, workflow artifacts will not be uploaded to a release. These two trigger methods will not have any affect on a branch in which the latest commit message contains `[ci skip]` (or [equivalent …

PR: Add workflow triggers for release candidates and fix tag normalization

---

.github/scripts/install.sh
conftest.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

- We were using `conda run` to do that, but strangely that started to fail since some hours ago.
- Run `test_conda_env_activation` only on Windows because it started to fail on Linux and it's flaky on Mac (but this only happens on `master`).
- Run a percentage of IPython console tests on slow slots for Windows so the fast ones finish faster.

PR: Fix failure installing Spyder-kernels from master on Windows and other minor fixes on CIS

---

.github/workflows/installer-macos.yml
.github/workflows/installer-win.yml
.github/workflows/test-files.yml
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml

Update actions/checkout and actions/cache to v3, and actions/setup-python to v4
Resolves the following deprecation warnings:
* Node.js 12 actions are deprecated
* The `save-state` command is deprecated and will be disabled soon.
* The `set-output` command is deprecated and will be disabled soon.

PR: Update GitHub actions

---

.github/workflows/installer-macos.yml
.github/workflows/installer-win.yml
.github/workflows/installers-conda.yml
.github/workflows/test-files.yml
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml

Opening a PR and labeling it at the same time results in a race condition between the `opened` and `labeled` `pull_request` event triggers which can lead to cancelled installer workflows.
To fix this, we remove the `labeled` event trigger for `pull_requests`.
Since release candidates were the primary motivation for these triggers, but this must rely on the `workflow_dispatch` trigger anyway, the `workflow_dispatch` is now the recommended way to trigger workflows outside of `pull_request` and `release` events.
Additionally, `inputs` for the `workflow_dispatch` were added to the conda-based installer workflow for enhanced flexibility.
* `pull_request.labeled` trigger events are removed for installer workflows
* `push.tag` trigger events are removed for installer workflows
* …

PR: Fix installer triggers

---

spyder/plugins/editor/widgets/tests/test_formatting.py
spyder/plugins/variableexplorer/widgets/arrayeditor.py
spyder/plugins/variableexplorer/widgets/collectionsdelegate.py

- Users can subclass `ndarray` and set its `dtype` to an object that is not an actual `dtype`. In that case, Spyder was giving an error because it was unable to get some regular `dtype` attributes.
- Stop spinner when failing to show arrays or images. I noticed this error while testing the above problem.
- Mark `test_formatting_on_save` as flaky. I noticed that test requires several runs to pass on CIs.
Fixes #20462.

PR: Prevent error when trying to show arrays without an actual `dtype` (Variable Explorer)

---

conftest.py
spyder/app/tests/conftest.py
spyder/app/tests/test_mainwindow.py
spyder/utils/environ.py
spyder/utils/tests/test_environ.py

#20297 unsatisfactorily fixed #20097 by skipping environment variables that do not parse correctly. This PR remedies this.
* For unix, use a clean subprocess environment, invoke a login shell, extract `os.environ` from a python process. This circumvents any parsing issues and should reflect exactly what a user would expect from a python process in a standard terminal.
* For Windows, get environment variables directly from the system registry.
* Add regression test for #20097
* Modify user environment variables in system registry or shell startup file
* Restore user environment variables
* Only run on CI to protect developers' local user environment variables
See #20097

PR: Fix issue where user environment variables with line endings were not parsed correctly on Unix platforms

---

spyder/plugins/application/container.py

Needed to prevent errors when an update is available on pip based installations. For pip based installations the update available dialog will look like this:
Fixes #20406 

PR: Initialize `content` variable for update available message (Application)

---

spyder/config/manager.py
spyder/utils/qthelpers.py

Add `--no-sandbox` argument when instantiating QtApplication object, in order to avoid a bug linked to Ubuntu 22.04 (see https://discourse.slicer.org/t/extensions-not-showing-anything/23432/5 and https://doc.qt.io/qt-6/qtwebengine-platform-notes.html)
Note sure if this is needed in `manager.py` tho, put it here just for consistency.
Fixes #20358
I certify the above statement is true and correct: tlunet

PR: Add `--no-sandbox` argument for QtApplication

---

spyder/utils/stylesheet.py

- This regression was introduced in PR https://github.com/spyder-ide/spyder/pull/20122.
Fixes #20504.

PR: Make pane tabs to be left aligned on macOS again

---

spyder/widgets/findreplace.py
spyder/widgets/tests/test_findreplace.py

* Update replace pattern to respect whole words filter
* Added regression test
Fixes #20403

PR: Fix issue where replace all did not respect whole words filter

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/plots/widgets/figurebrowser.py

Only scroll down in the plots plane if the latest plot is selected or if a new execution started
Fixes #20474

PR: Stop automatic scrolling when a plot is selected (Plots)

---

spyder/plugins/editor/plugin.py

Fix “Source → Last edit location” action for new (yet unsaved) files.
rear1019

PR: Fix “Last edit location” for unsaved files

---

spyder/plugins/pythonpath/widgets/pathmanager.py

Reset references to Qt objects deleted by `listwidget.clear()`. This fixes a `RuntimeError` when Python Path Manager is reopened.
Fixes #20506
rear1019

PR: Fix error when Python Path Manager is reopened

---

spyder/app/tests/bash_example.sh
spyder/app/tests/test_mainwindow.py

`zsh` does not have the `-u` shell option. macOS can use `bash` instead of `zsh`.
Correct execution (via `bash`) looks like this:
```bash
(spy-dev) >> /bin/bash spyder/app/tests/bash_example.sh $(pwd)
allexport      	off
braceexpand    	on
emacs          	off
errexit        	on
errtrace       	off
functrace      	off
hashall        	on
histexpand     	off
history        	off
ignoreeof      	off
interactive-comments	on
keyword        	off
monitor        	off
noclobber      	off
noexec         	off
noglob         	off
nolog          	off
notify         	off
nounset        	off
onecmd         	off
physical       	off
pipefail       	off
posix          	off
privileged     	off
verbose        	off
vi             	off
xtrace         	on
+ TEMP_DIR=/Users/rclary/Documents/Repos/Spyder-IDE/spyder …
```

PR: Fix test_shell_execution for macOS

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole/utils/kernel_handler.py
spyder/plugins/ipythonconsole/widgets/main_widget.py

Make sure spyder doesn't quit while some threads are running, leading to a crash
Fixes #20561

PR: Wait on all shutdown threads (IPython console)

---

.github/workflows/installers-conda.yml

Remove macOS and Windows conda-based installers from 5.x branch since they have moved to the master branch for 6.0.0alpha and are no longer needed here. The Linux experimental conda-based installer will remain, along with the traditional macOS and Windows standalone installers.

PR: Remove macOS and Windows conda-based installers from 5.x branch

---

.github/workflows/installers-conda.yml
installers-conda/resources/post-install.sh
installers-conda/resources/spyder-menu.json

* Added `StartupWMClass` to Linux desktop file. This obviates the need to change the name of the desktop file in the post-install script.
* Minor CI workflow updates

PR: Update conda-based installers

---

spyder/plugins/onlinehelp/widgets.py

A warning when trying to show numpy inside Online Help was happening with Spyder from the Windows standalone installer. Setting `PYDEVD_DISABLE_FILE_VALIDATION = 1` prevents the warning message.
Fixes #20390 

PR: Set `PYDEVD_DISABLE_FILE_VALIDATION` to prevent errors when searching for numpy docs (Online Help)

---

.github/workflows/installers-conda.yml

* Added installer test for Linux
* Added installer test for Windows
* Ensure that installer tests exit with non-zero status
* Added option for ssh debugging

PR: Add installer tests for Linux and Windows

---

spyder/plugins/profiler/widgets/main_widget.py

Takes care of profiler bug in #20599 due to incorrectly set PYTHONEXECUTABLE env variable
Makes sure PYTHONEXECUTABLE is removed from environment prior to starting the profiler
Fixes #20599
I certify the above statement is true and correct: Mike

PR: Remove `PYTHONEXECUTABLE` for process that runs the profiler

---

spyder/plugins/editor/widgets/editor.py
spyder/plugins/editor/widgets/tests/test_editor.py
spyder/utils/icon_manager.py
spyder/widgets/findreplace.py
spyder/widgets/tests/test_findreplace.py

- This prevents that the widget buttons change position when users replace text with it and the number of matches start to change. The number is shown in the button's tooltip in that case, as shown below:
- Clear found results when clicking on the clear action, I noticed this bug while working on Spyder.
Fixes #20476.

PR: Show icon instead of text for small widths and clear found results correctly in Find/Replace widget

---

external-deps/qtconsole/.github/workflows/linux-tests.yml
external-deps/qtconsole/.github/workflows/macos-tests.yml
external-deps/qtconsole/.github/workflows/windows-tests.yml
external-deps/qtconsole/.gitrepo
external-deps/qtconsole/qtconsole/rich_jupyter_widget.py
external-deps/qtconsole/qtconsole/tests/test_jupyter_widget.py

- This was failing in Python 3.10+ for images generated by Seaborn 0.12
- Depends on https://github.com/jupyter/qtconsole/pull/570.
Fixes #20597

PR: Fix displaying images that have float width or height (IPython console)

---

spyder/plugins/variableexplorer/widgets/dataframeeditor.py

Exchange of iteritems() for items() in self.df.iteritems()
This "iteritems()" is deprecated and will be removed in a future release.
Fixes #20496.

PR: Change usage of `iteritems` for `items` in dataframe editor (Variable Explorer)

---

spyder/plugins/editor/plugin.py

Methods connected to signals that use the current editor can get evaluated while no editor is available. Add a validation for the current editor value returned to prevent errors.
Fixes #20643 

PR: Add validations before doing operations with the current editor (Editor)

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/editor.py

This problem happens if there's any error while reading the session files from disk.
Fixes #20670.

PR: Avoid crash at startup when trying to restore the previous session (Editor)

---

spyder/plugins/editor/widgets/codeeditor.py

Users can encounter this error when trying to rename a file in that scenario.
Fixes #20679.

PR: Fix error in `document_did_open` when the LSP failed to start (Editor)

---

installers/macOS/packages.py

Add keyring to PACKAGES to resolve "ModuleNotFoundError: No module named 'keyring.backends.macOS'"
Fixes #20681

PR: Fix issue where keyring backends are not found in macOS standalone app

---

spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/tests/test_editor_config_dialog.py
spyder/plugins/findinfiles/plugin.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/mainmenu/api.py
spyder/plugins/mainmenu/plugin.py
spyder/plugins/pylint/plugin.py

Move menu actions from the Editor code to use Mainmenu plugin:
Part of #17468

PR: Initial code changes for old menu actions to use the `Mainmenu` plugin (Editor)

---

spyder/plugins/editor/plugin.py

After #20620 the Source menu got an incorrect actions order:
This fixes the order:

PR: Fix `Source` menu order (Editor)

---

spyder/plugins/maininterpreter/widgets/status.py

Although I don't understand how, it seems under certain situations the worker in charge of getting the current pyenv and conda envs can return `None`, which gives the error this PR is fixing.
Fixes #20539.

PR: Avoid error when updating environments (Main interpreter)

---

spyder/config/main.py
spyder/plugins/editor/widgets/completion.py
spyder/plugins/explorer/widgets/explorer.py
spyder/utils/qthelpers.py

- I think those shortcuts were broken since the migration of Files and Projects to the new API.
- Add default shortcuts for copy/paste actions present in Projects.
- Change shortcut to copy relative paths to `Alt+Shift+C` because it's easier to introduce.
- Add `keyevent_to_keysequence` utility function and use it to simplify some code in the editor's completion widget.
Fixes #20068.

PR: Fix copy/paste shortcuts in Files and Projects

---

spyder/app/restart.py
spyder/app/start.py

Be sure to use the script the standalone installer uses in the shortcut to start and don't remove installer `pkgs` entry from the `PYTHONPATH` when starting Spyder.
See https://github.com/spyder-ide/spyder/issues/20658#issuecomment-1468338520

PR: Fix restart mechanism for the Windows standalone installer (Installers)

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole/widgets/control.py
spyder/plugins/ipythonconsole/widgets/figurebrowser.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/utils/misc.py
spyder/widgets/mixins.py

- The format for tracebacks changed in IPython 8. That's why our previous code to detect filenames inside them failed.
- Add a test for this functionality so we notice when it breaks in the future.
- Restore showing the pointing hand cursor when hovering over file names on tracebacks. This was broken in #15809.
- Change header for non-error messages from `Warning` to `Important` to better convey the meaning of those messages to users (not all of them are warnings). Also, use white color for it so that it's more readable in the light theme.
**Before**
**After**
- Change message shown the first time a plot is generated with the Inline backend. That message was written for Spyder 3 users so they understood where their plots went in Spyder 4. But it makes little sense now for new users. …

PR: Fix clicking on file names in tracebacks for IPython 8 and minor fixes for messages shown in the console

---

external-deps/qtconsole/.gitrepo
external-deps/qtconsole/qtconsole/client.py
external-deps/qtconsole/qtconsole/frontend_widget.py
spyder/plugins/ipythonconsole/widgets/debugging.py

This is necessary to fix the error reported in https://github.com/spyder-ide/spyder/issues/20381#issuecomment-1482990746.

PR: Check if the `iopub` channel is not closed before flushing it (IPython console)

---

spyder/widgets/tests/test_collectioneditor.py

Extra import added when merging #20766 from `5.x` into `master`

PR: Fix `test_collectionseditor` after merge (Widgets)

---

spyder/app/mainwindow.py
spyder/plugins/profiler/plugin.py
spyder/plugins/pylint/plugin.py

* Remove some methods from the mainwindow that seem unused:
* `show_shortcuts`
* `hide_shortcuts`
* `hide_options_menus`
* `get_focus_widget_properties`
* Fix position of code analysis and profiler actions in menus:
* Before:
* After:
Not totally sure if the actions should remain in the position where you find them when using 5.x but if not at least no action should be repeated in different menus I think

PR: Remove some unused methods from MainWindow and fix Code Analysis and Profiler actions in menus position

---

.github/scripts/install.sh
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml
runtests.py

Using the codecov package causes CI to fail with `pip` since the `codecov` package was removed from PyPI. The error from CI is the following:
```
ERROR: Could not find a version that satisfies the requirement codecov (from versions: none)
ERROR: No matching distribution found for codecov
```
Example CI run where this happens: https://github.com/spyder-ide/spyder/actions/runs/4681680400/jobs/8294575413?pr=20421#step:10:420
Remove codecov related install commands and use Codecov GitHub Action instead to upload coverage reports
and understand I am releasing the same under Spyder's MIT …

PR: Update codecov coverage upload to use GitHub Action (CI)

---

spyder/utils/environ.py

For the standalone macOS app, `PYTHONHOME` is required to correctly execute the Python subprocess for retrieving the user's system environment variables.
Note: after merging into 5.x, these changes should _not_ be merged into master.
Partially addresses #20808

PR: Keep `PYTHONHOME` in `get_user_environment_variables` for macOS standalone app

---

.github/scripts/install.sh

This was making our tests failed due to an internal warning issued by `pip`.

PR: Don't treat warnings as errors when installing Spyder and subrepos (CI)

---

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

- The test passes for me locally with the latest Matplotlib version, so I don't know what happens with it on CIs.
- Also, it only fails on `master`.
I certify the above statement is true and correct: @cc

PR: Skip a test that started to fail on Linux and Mac

---

.github/workflows/installer-macos.yml

Install `wheel` in macOS standalone build environment
Fixes #20834

PR: Install wheel in macOS build environment

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/utils/bookmarks.py
spyder/plugins/editor/widgets/base.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py

Replace direct `CONF` usage in the Editor related widgets for methods inherited from the `SpyderConfiguratorAccessor` class

PR: Move CONF usage for bookmarks logic and use `SpyderConfiguratorAccessor` class in Editor widgets (Editor)

---

spyder/plugins/onlinehelp/pydoc_patch.py
spyder/plugins/onlinehelp/tests/test_pydocgui.py

* Added handling of attributes that are classified as "readonly property", consistent with mechanisms in `pydoc.HTMLDoc`. This was the cause for `numpy` and `pandas` errors.
* Added error handling for `ModuleScanner`, consistent with mechanisms existing in `pydoc._url_handler`. This was the cause for keyword search errors.
* Updated unit tests. I believe that the root cause that motivated the skip filters may be the same issues that are remedied here and therefore the filters can be discarded.
Fixes #20866
I …

PR: Fix errors with OnlineHelp plugin regarding readonly properties and ModuleScanner errors

---

spyder/__init__.py
spyder/widgets/about.py

In About widget, changed system info reporting for macOS from "Darwin" to "macOS" with appropriately changed release designation.
Also added machine type ('arm64', 'x86_64', 'AMD64', etc) to the system info for all platforms.
In the system info for issue reporting (and "Copy version info" of About widget), operating system value is replaced with the value of `platform.platform`.
"macOS 13.3" is more meaningful than "Darwin 22.4.0" to users, issue reporters, and developers. Additionally, inclusion of machine type may eliminate the need for developers to ask issue reporters "Is your machine Intel or M1?".
* Spyder version: 6.0.0.dev0 47a906db (standalone)
* Python version: 3.9.16 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: macOS-13.3-x86_64-i386-64bit

PR: Change reporting of macOS system from Darwin to macOS and include machine type

---

spyder/plugins/completion/providers/kite/widgets/install.py
spyder/plugins/console/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/utils/palette.py

* <s>[ ] Wrote at least one-line docstrings (for any new functions)</s>
* <s>[ ] Added unit test(s) covering the changes (if testable)</s>
This small PR changes the misspelling "ocurred" to the correct "occurred" in both user-visible text and code comments. The latter is of course not necessary but it soothes my nerves. I noticed this when I came across issue spyder-ide/spyder-notebook#421.
Screenshot before:
Screenshot after:
None

PR: Fix typo in kernel error message (IPython console)

---

spyder/plugins/explorer/widgets/fileassociations.py

When running from a non-admin account on Windows the applications executables discovery can fail with a `PermissionsError`. Catch the error an fallback to an empty applications list.
Fixes #20907 

PR: Catch `PermissionsError` when trying to get applications executables (Files)

---

spyder/plugins/findinfiles/widgets/results_browser.py
spyder/plugins/findinfiles/widgets/search_thread.py
spyder/plugins/findinfiles/widgets/tests/test_widgets.py

- This replaces one of the fixes done in PR #19124, which was incorrect because it didn't alow to show the results found for a single file.
- Add a test to check that functionality.
Fixes #20964.

PR: Fix searching in a single file (Find)

---

spyder/plugins/editor/widgets/editor.py

The problem was that if users decide to close a file (through the dialog shown in `__check_file_status`) before Spyder runs the method that suggests them to save it, then an error was raised because Spyder can't find the index corresponding to the closed file to check its save status.
Fixes #20998.

PR: Prevent error when removing several unsaved files from Projects or Files (Editor)

---

spyder/plugins/editor/panels/scrollflag.py

Reverse paint order of scrollflags to make occurrences highest priority above warnings and errors
reversed scrollflag paint order.
RE: PR #20929 Reverse scrollflag paint order to make occurrences highest priority. Files with many errors or other flags in general obscure found occurrences which seem like they should be highest priority for viewing.
Fixes #

PR: Paint find matches above errors and warnings in scrollflags

---

spyder/plugins/findinfiles/widgets/main_widget.py
spyder/plugins/findinfiles/widgets/search_thread.py

Also, fix error on close because we were trying to disconnect a Qt signal from a slot that doesn't exist.
Fixes #20798.

PR: Catch error when a file is pointed by too many levels of symlinks (Find)

---

spyder/plugins/ipythonconsole/utils/manager.py

This can happen because `kill_proc_tree` is now async and the OS may have removed the kernel's children before that method was able to run.
Fixes #21012.

PR: Catch an error when trying to kill the kernel children processes (IPython console)

---

spyder/config/gui.py
spyder/plugins/completion/providers/languageserver/provider.py
spyder/plugins/console/widgets/main_widget.py
spyder/plugins/explorer/widgets/fileassociations.py
spyder/plugins/preferences/widgets/container.py
spyder/plugins/pylint/plugin.py
spyder/widgets/findreplace.py
spyder/widgets/github/gh_login.py

Various fixes to improve compatibility with PySide2. Notes
* `pyside2: Fix usage of keyword argument in QSpacerItem`: It should be possible to fix this globally via monkey patching in `qtpy`, similar to spyder-ide/qtpy#341. Please let me know if this is desired.
* `pyside2: Fix QObject.disconnect() calls`: Unfortunately, this cannot be fixed globally via monkey patching in `qtpy`.
rear1019

PR: Various Fixes to improve compatibility with PySide2. 

---

spyder/plugins/editor/widgets/codeeditor.py

When doing autocompletions there is some logic related with setting the cursor position to -1 which causes a warning when the cursor is already at position 0 (so the cursor position was being set to -1).
Preventing setting the position to negative values while handling the autocompletions prevents the warning message.
Fixes #21028 

PR: Prevent setting cursor in a negative position (Editor)

---

installers-conda/build_installers.py

To accommodate possible pre-release candidates of `spyder-kernels`, added `conda-forge/label/spyder_kernels_rc` to the channel list for building the installed environment.

PR: Add `spyder_kernels_rc` conda-forge label (Installers)

---

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/utils/syntaxhighlighters.py

Those keywords were added in Python 3.10, but we were not highlighting them as such.
Fixes #20963.

PR: Make `match` and `case` be highlighted as Python keywords (Editor)

---

spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/tests/test_formatting.py

When `Wrap lines` is enabled is possible for the `blockNumber` to not match the actual position expected for the cursor to be after formatting. Seems like using the actual cursor position overcomes this.
Fixes #20852

PR: Use cursor `position` instead of `blockNumber` when restoring cursor after format (Editor)

---

Announcements.md
changelogs/Spyder-6.md

I noticed these issues after doing the release.

PR: Small fixes to release files after 6.0a1

---

.github/workflows/installers-conda.yml
installers-conda/resources/post-install.sh
installers-conda/resources/spyder-menu.json

* Quote variable interpolation in conditional statements and check for file not just exists.
* Remove aliases before removing environment in uninstall.
* Set executable permission for user only for `uninstall-spyder.sh`.
* Only add aliases if `shell_init` is not null.
* Use relative path in shortcut command for macOS to allow Spyder.app to be moved. `menuinst` currently puts shortcut in `~/Applications` instead of `/Applications` for all-user install.

PR: Fix issues for all-user install in post-install script (Installers)

---

spyder/app/tests/conftest.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py

This PR fixes missing updates of the class and function selector of vertically/horizontally split (cloned) editors. See commit message for details.
Note: Update of indent guides and code folding in cloned editors is broken as well (similar root cause). I have looked into fixing that as well, however, have not succeeded so far.
rear1019

PR: Fix class/function selector for split editors (Editor)

---

spyder/config/gui.py

This prevents altering the same font with different deltas, which was applied incorrectly to plugins that didn't require a delta.
The most visible effect of this bug was seen in the interaction between the Variable Explorer and the IPython console. The Variable Explorer uses the `Plain text` font with a small delta, which was changing the font size used by the IPython console as a side effect.
**Before**
**After**
Fixes #20716.

PR: Save fonts with delta in our font cache (Config)

---

installers-conda/build-environment.yml
installers-conda/build_installers.py
installers-conda/resources/spyder-menu.json
setup.py

`menuinst` still presents a temporary `cmd.exe` window on Spyder startup. See conda/menuinst#128.
This can be eliminated by restricting the Windows shortcut link target to use `pythonw.exe`.
However, this comes with the tradeoff that the environment cannot be activated and additional pre-activation commands cannot be provided.
The pre-commands are not required by Spyder. Since Spyder application does not require intrinsic conda environment manipulation, then activating the runtime environment in the runtime shell environment is also not strictly required.

PR: Fix issue where cmd.exe window flashes on Spyder startup on Windows (installer)

---

installers-conda/resources/spyder-menu.json
spyder/plugins/ipythonconsole/utils/kernelspec.py
spyder/utils/environ.py

* Use a shell script in Spyder's config directory to retriev user environment variables on posix systems.
* The shell script is created on Spyder startup and only for posix systems.
To get user environment variables from login and interactive startup files on posix, both `-l` and `-i` flags must be used. Parsing the environment list is problematic if the variable has a newline character, but Python's `os.environ` can do this for us. However, executing Python in an interactive shell in a subprocess causes Spyder to hang on Linux. Using a shell script resolves the issue. Note that `-i` must be in the sha-bang line; if `-i` and `-l` are swapped, Spyder will hang.
Also note that for environment variables for `KernelSpec` objects are first set to the user's environment variables, then …

PR: Fix issue getting user environment variables on Posix systems and pass them to the IPython console

---

spyder/app/mainwindow.py
spyder/plugins/layout/plugin.py

Also, improve the `QMessageBox` we use to display those messages by centering it and adding the plugin name to the message:
**Before**
**After**
Fixes #21074.

PR: Fix crash at startup when plugins fail their compatibility checks

---

bootstrap.py

Calling `python .../spyder/bootstrap.py` when the current working directory is not the Spyder repo results in incorrectly determining the git branch. This PR fixes that.

PR: Fix issue where bootstrap incorrectly determines git branch

---

spyder/plugins/application/widgets/status.py

- This is not necessary anymore after PR #20933 and it was causing a crash at startup.
- I discovered this while testing PR #21084.

PR: Remove setting font for update status bar widget (Application)

---

.github/workflows/installers-conda.yml
installers-conda/build_installers.py
installers-conda/resources/post-install.bat
installers-conda/resources/post-install.sh

Automatically launch Spyder after install

PR: Automatically launch Spyder after installation (Installers)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/comms/decorators.py
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
external-deps/spyder-kernels/spyder_kernels/console/shell.py
external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py

- Depends on https://github.com/spyder-ide/spyder-kernels/pull/445
Fixes #20571.

PR: Add `exitdb` command and some speed optimizations to the debugger

---

spyder/widgets/tabs.py

Because macOS keyboards don't have PgUp/Down, I added shortcuts to switch edit tabs for macOS. The shortcuts are listed below.
- `command + 8` -> switch to the left tab
- `command + 9` -> switch to the right tab
Fixes #1741
I certify the above statement is true and correct: @ryohei22

PR: Add better shortcuts to switch edit tabs for macOS

---

spyder/plugins/completion/providers/languageserver/widgets/status.py

PR: Fix LSP status widget logic when it is `None` using early return

---

.github/workflows/test-files.yml
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml
spyder/plugins/editor/widgets/tests/test_formatting.py

- Codecov is quite flaky lately, which causes a full restart to make our test suite pass.
- We need to switch to `setup-micromamba` because `provision-with-micromamba` is now obsolete.
- Also, make `test_formatting_on_save` run more times because it's quite flaky.

PR: Prevent failures when Codecov action fails and switch to `setup-micromamba` (CI)

---

.github/workflows/installers-conda.yml

This reverts commit e829688cc43d6bb47ed2c908fb994682ace404bc.
With the replacement of our GitHub secrets with new Developer ID certificates, we can reinstate notariztion.

PR: Reinstate notarization of conda-based macOS installer

---

spyder/widgets/reporterror.py

- Fix spacing and alignment of dismiss checkbox.
- Increase monospace font size by one point because the current size is too small.
- Fix left alignment of the details widget.
**Before**
**After**

PR: Some fixes for the report error dialog (UI)

---

spyder/plugins/maininterpreter/confpage.py

Prevent an error when changing the Python interpreter config from the preferences:
```python-traceback
File "e:\acer\documentos\spyder\spyder\spyder\plugins\preferences\widgets\configdialog.py", line 142, in button_clicked
configpage.apply_changes()
File "e:\acer\documentos\spyder\spyder\spyder\plugins\preferences\api.py", line 119, in apply_changes
self.apply_callback()
File "e:\acer\documentos\spyder\spyder\spyder\plugins\maininterpreter\confpage.py", line 246, in perform_adjustments
if not self.def_exec_radio.isChecked():
AttributeError: 'QWidget' object has no attribute 'isChecked'
```
with respect to all …

PR: Fix config page radiobutton reference (Main interpreter)

---

spyder/app/tests/test_mainwindow.py

The new test in 5.4.3 or 5.4.4 `spyder/app/tests/test_mainwindow.py::test_clickable_ipython_tracebacks` modifies the sample script `script.py` used by other tests.  This means that those other tests will fail if they are run after this test.
This PR fixes this by copying `script.py` and editing the copy instead.  It also means that this test itself can be rerun.

PR: Do not overwrite test script to allow tests to be rerun

---

spyder/widgets/collectionseditor.py

Prevents an error when trying to get a tooltip for variables inside a collections editor instance shown from clicking a variable in the Variable Explorer
Fixes #21191 

PR: Fix `ReadOnlyCollectionsModel` tooltip logic (Widgets/Variable Explorer)

---

spyder/api/shellconnect/main_widget.py
spyder/api/widgets/main_widget.py
spyder/app/mainwindow.py
spyder/plugins/application/confpage.py
spyder/plugins/debugger/widgets/framesbrowser.py
spyder/plugins/editor/plugin.py
spyder/plugins/findinfiles/widgets/main_widget.py
spyder/plugins/help/widgets.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/onlinehelp/widgets.py
spyder/plugins/plots/widgets/figurebrowser.py
spyder/plugins/profiler/widgets/main_widget.py
spyder/plugins/pylint/main_widget.py
spyder/plugins/variableexplorer/widgets/namespacebrowser.py
spyder/plugins/workingdirectory/plugin.py
spyder/utils/stylesheet.py
spyder/widgets/browser.py
spyder/widgets/dock.py
spyder/widgets/findreplace.py
spyder/widgets/helperwidgets.py

- This is another take on the design discussed on spyder-ide/ux-improvements#4.
- Supersedes PR #21071.
**Dark theme**
**Light theme**
Fixes spyder-ide/ux-improvements#4.

PR: Improve style of dockwidget tabbars (UI)

---

spyder/api/shellconnect/main_widget.py
spyder/api/shellconnect/mixins.py
spyder/api/utils.py
spyder/app/mainwindow.py
spyder/plugins/debugger/plugin.py
spyder/plugins/debugger/widgets/main_widget.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/ipythonconsole/widgets/status.py
spyder/plugins/plots/plugin.py
spyder/plugins/plots/widgets/main_widget.py
spyder/plugins/variableexplorer/plugin.py
spyder/plugins/variableexplorer/widgets/main_widget.py
spyder/utils/stylesheet.py
spyder/widgets/about.py
spyder/widgets/helperwidgets.py

* For `PaneEmptyWidgets`: show description at the bottom and increase size of main text (these changes were suggested by @conradolandia); and load their icons in a way that doesn't make them appear pixelated at scale factors greater than one.
* For dead consoles: show an appropriate message using a `PaneEmptyWidget` on panes that depend on the console to work. This needs an additional icon that @conradolandia is going to design and add in a follow-up PR.
* This also includes some improvements to the About dialog: use font sizes relative to the interface one, correctly align buttons to the right, increase font size for its tabs, remove white pixels below tabs and make it bigger.
**Before**
**After**
* Fix color of links in Qt widgets, which was broken in #20933.
By submitting this Pull …

PR: Improve UI of `PaneEmptyWidget`, show message on panes connected to dead consoles and improve About dialog UI

---

.github/workflows/installers-conda.yml
installers-conda/resources/post-install.sh

A significant amount of time is spent building conda packages of the subrepos `python-lsp-server`, `qtconsole`, and `spyder-kernels` during standard PRs. These package versions are not necessarily stable release versions or release candidate versions and must be built from the commit states specified in their respective `.gitrepo` files. Nevertheless, they do not change very often and therefore are excellent candidates for caching.
Fixes #21157

PR: Cache subrepo conda builds for installers

---

spyder/plugins/editor/plugin.py

PR: Fix capitalization on Windows when opening a file in debug mode

---

.github/workflows/installers-conda.yml

Follow-up PR to #21212 
This PR revises the existing installer workflow to only restore caches of the subrepo conda packages. These packages will now be built and cached by the workflow introduced in #21212.

PR: Update installer workflow to only restore cache of subrepo builds (Installers)

---

spyder/plugins/completion/providers/languageserver/conftabs/otherlanguages.py
spyder/plugins/completion/providers/languageserver/widgets/serversconfig.py
spyder/plugins/completion/providers/snippets/widgets/snippetsconfig.py
spyder/plugins/shortcuts/confpage.py
spyder/plugins/shortcuts/widgets/table.py

- This was a regression introduced in PR #21101.
- I also took the opportunity to remove hard-coded colors from the Shortcuts table and other tables as well.
Fixes #21206.

PR: Fix showing text in the dark theme for keyboard sequences in the Shortcurts page (Preferences)

---

spyder/api/plugin_registration/_confpage.py

See commit message for details
rear1019

PR: Fix error after changes to Plugins page (Preferences)

---

spyder/plugins/pythonpath/tests/__init__.py
spyder/plugins/pythonpath/tests/test_utils.py
spyder/plugins/pythonpath/utils.py

* We were not detecting `site-packages` directories in Mac framework installations and two digit Python environments (e.g. Python 3.10).
* Add tests for the small utility function that does that job.
Fixes #21228.

PR: Expand patterns to detect possible `site-packages` directories (Pythonpath manager)

---

spyder/plugins/editor/widgets/editor.py

If errors appear while doing it, we close the file to prevent users from destroying external changes in Spyder.
Fixes #21248.

PR: Catch errors when trying to reload a file (Editor)

---

installers/Windows/req-extras-pull-request.txt
installers/Windows/req-extras-release.txt
installers/Windows/req-pull-request.txt
installers/Windows/req-release.txt
installers/macOS/packages.py
installers/macOS/req-plugins.txt

Removed `spyder-terminal` plugin from the standalone applications
Fixes #21258

PR: Do not include spyder-terminal in standalone applications

---

spyder/app/tests/test_mainwindow.py
spyder/app/utils.py
spyder/config/utils.py
spyder/plugins/editor/utils/switcher_manager.py
spyder/plugins/projects/plugin.py
spyder/plugins/projects/tests/test_plugin.py
spyder/plugins/projects/widgets/main_widget.py
spyder/plugins/switcher/container.py
spyder/plugins/switcher/plugin.py
spyder/plugins/switcher/widgets/item.py
spyder/plugins/switcher/widgets/switcher.py
spyder/utils/workers.py

- Since the initial implementation was synchronous, the interface was freezing when using the Switcher with large projects (i.e. projects that have more than 1000 files).
- Highlight matched characters of Projects switcher results that match the searched text.
- Remove binary files from the results computed by `fzf` because they can't be opened in the editor.
- Fix process workers because they were not working as expected.
- Simplify the way sections are shown in the Switcher, which was not very efficient and hard to understand.
- Improve test that checks the integration between Projects and the Switcher.
- Set app and monospace interface fonts when running single main window tests. That avoids a ton of Qt warnings to be displayed.
Fixes #20940.
By submitting this Pull Request or typing …

PR: Compute Projects switcher results in a worker to avoid freezes

---

spyder/app/mainwindow.py
spyder/plugins/editor/panels/scrollflag.py

- Unfortunately, PR #20970 broke compatibility with Python 3.7, which is generating a ton of errors in the Editor.
- This PR restores that compatibility.
Fixes #21286.

PR: Don't try to reverse the dict of scroll flags in Python 3.7 (Editor)

---

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py

This is a small PR which uses the new function `pandas.api.types.is_any_real_numeric_dtype()` to decide whether a Pandas dtype is a real number and thus gets the background colouring of numbers in the Dataframe editor. This allows us to supports the nullable integer types and also numeric types that were previously not supported like `numpy.int16`. A test is also included.
This PR imports `pandas` inside a function. As far as I can see, no part of Spyder explicitly imports `pandas` but I think that `pandas` is always imported when a Dataframe editor is opened, so this should not be a problem.
Screenshot after:
Screenshot before:
These are produced using the following code, from issue #21022:
```python
import pandas as pd
vals = [1, 2, 3, 4, 5]
vals_na = [1, 2, 3, None, 5]
df = …
```

PR: Support all real number dtypes in dataframe editor

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/plots/plugin.py
spyder/plugins/plots/widgets/figurebrowser.py
spyder/plugins/plots/widgets/main_widget.py
spyder/plugins/plots/widgets/tests/test_plots_widgets.py
spyder/plugins/variableexplorer/plugin.py
spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
spyder/plugins/variableexplorer/widgets/main_widget.py
spyder/plugins/variableexplorer/widgets/namespacebrowser.py
spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py
spyder/plugins/variableexplorer/widgets/objectexplorer/toggle_column_mixin.py
spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py
spyder/widgets/collectionseditor.py
spyder/widgets/tests/test_collectioneditor.py

The collection editor is opened when the user edits a list, set, dict or tuple in the Variable Explorer. At the moment, plotting in the collection editor opens a new window with the plot. This PR changes this so that the plot is displayed in the Plots pane, for consistency with the namespace browser. The Plots pane is brought to the front so that users notice the new plot. However, if the user unticks the setting "Mute inline plots" in the Plots pane, then the old behaviour is restored and plots are shown in a separate window.
The collection editor is also used in several places outside the Variable Explorer:
* The IPython Console uses it to show environment variables and sys.path contents. Neither of these can be plotted as far as I can see.
* The `oedit()` function can create a …

PR: Display plots from collections editor in the Plots pane

---

.github/workflows/installers-conda.yml

As part of the Spyder 6alpha2 release I did the release candidate step and tried to generate the installers, but seems like the manual worflow dispatch fails due to the spyder conda package build step being skipped (seems like it was skipped if the workflow is not being run from a PR). Not totally sure if this is the correct approach but opening a PR just in case and to discuss if something else needs to be done @ccordoba12 @mrclary 
* Workflow run that failed: https://github.com/spyder-ide/spyder/actions/runs/6053595167 …

PR: Remove installers workflow step validation for spyder conda package build to be done only on PRs (CI)

---

.github/workflows/installers-conda.yml

This is currently broken for constructor. Revert when solution is found

PR: Do not sign or notarize macOS installer pkg

---

spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py

This is a follow-up for PR #21235 which included a test that does not work under Python 3.8, as noted in https://github.com/spyder-ide/spyder/pull/21235#issuecomment-1712706071. This was not picked up by the automatic tests because of #21322.
Specifically, the `with (..., ...)` syntax was introduced in Python 3.10. Before, multiple context managers were possible but it had to be written without parentheses. Thus, this PR replace the parentheses with backslashes so that the test code works in Python 3.8 and 3.9.
I …

Fix syntax in test_namespacebrowser.py for Python 3.8 and 3.9

---

.github/workflows/build-subrepos.yml
.github/workflows/installers-conda.yml
installers-conda/build-environment.yml
installers-conda/certkeychain.sh

* Call `set-key-partition-list` after correcting the `codesign` executable path
* Set the keychain timeout
* Run the installer workflow daily at 06:30UTC
* Run the installer workflow for PRs only if relevant workflow files have changed
* Run the subrepo build workflow only on push to master or called from within the installer workflow.
The first two changes listed above seem to correct the issue where `codesign` would hang while replacing the signature for `conda.exe`, independently.
I suspect that a gui prompt is launched, waiting for user input and giving the appearance of hanging.
I think this may occur under two conditions:
* `set-key-partition-list` may have registered `.../spy-inst/bin/codesign` instead of `/usr/bin/codesign`, resulting in a gui prompt requesting user input …

PR: Fix Codesigning for the Installers and Run Workflow on Schedule

---

.github/workflows/installers-conda.yml
README.md

* Fixed typo that prevented using subrepos on schedule trigger.
* Fixed logic to notarize on schedule trigger.
* Added status badge to repo landing page.
In addition to the status badge, scheduled workflow failures will trigger notifications to the last person to enable the workflow or set the cron schedule (currently @mrclary). This is set in the user's notification setttings of his/her GitHub profile.

PR: Fix Installer workflow on schedule and add badge to Readme

---

conftest.py
spyder/app/tests/conftest.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/switcher/tests/test_switcher.py
spyder/plugins/switcher/widgets/switcher.py
spyder/tests/test_dependencies_in_sync.py
spyder/utils/environ.py

- That error was preventing to reuse the window between tests, which significantly increased its running time on CIs.
- Decrease percentage of IPython tests run on slow slots a bit.
- Fix some tests related to the switcher, dependencies and getting environment variables on Mac.
Fixes #21322.

PR: Fix error when running main window tests and failing tests

---

spyder/plugins/debugger/widgets/framesbrowser.py

Add an empty message to the Debugger pane

---

spyder/api/widgets/auxiliary_widgets.py
spyder/api/widgets/main_widget.py
spyder/api/widgets/mixins.py
spyder/app/mainwindow.py

* This happened when:
-  Spyder was closed in a screen which was not the primary one.
- The location of that screen was changed by the user (e.g. from left to right of the primary one) before Spyder was opened again.
- That caused Spyder to be placed in a non-visible region at startup.
* This PR detects if that's the case and moves Spyder automatically to the primary screen.
* It also does the same for undocked plugin windows.
Fixes #20344.

PR: Move main and plugin windows to the primary screen if not in a visible location at startup

---

.github/workflows/installers-conda.yml

Use Apple Developer ID Application Certificate for signing Windows installer.
Eventually, a different certificate will be required for full Windows security compliance.
Partially addresses #21389

PR: Temporarily use Apple Developer ID Application Certificate for signing Windows installer

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py
external-deps/spyder-kernels/spyder_kernels/console/start.py

- This was broken in Spyder-kernels 2.4.0
- I tested with a Python 2 env and things are working as expected again (including plots with Matplotlib).
- Depends on spyder-ide/spyder-kernels#469
Fixes #21310.

PR: Fix compatibility with Python 2 environments (IPython console)

---

.github/scripts/install.sh
external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py

This was broken in IPython 8.15+ due to the new support for chained exceptions in the debugger, which was introduced in that version.
Fixes #21377

PR: Fix calling the `%debug` magic after an error (IPython console)

---

spyder/workers/updates.py

* Replaced the use of `urllib.urlopen` and `urllib.urlrequest` with `requests.get` when checking and downloading updates.
* SSL certificates are now verified by default when checking for updates. This was already the default for downloading updates.
* Some error messaging was updated to reflect possible SSL certificate verification errors.
Fixes #21398

PR: Use `requests` instead of `urllib` for updates

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/utils/dochelpers.py
external-deps/spyder-kernels/spyder_kernels/utils/tests/test_dochelpers.py
spyder/plugins/application/container.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/help.py
spyder/workers/tests/test_update.py

- Improve how we get signatures from the kernel inspect replies (the previous code was not working as expected).
- Fix error for objects (e.g. `numpy.where`) for which Python gives an error when trying to get their signature with `inspect.signature`.
- Make some small followup improvements after #21402.
- Depends on spyder-ide/spyder-kernels#473.
- Depends on spyder-ide/spyder-kernels#474.
Fixes #21148

PR: Improve how we get signatures and catch error when trying to do it for certain objects (IPython console)

---

.github/workflows/installers-conda.yml
README.md

Change the name of the workflow for conda-based installers to be more generic. When merging into master, the name of the workflow should be adopted in master as well so that the workflow in both branches has the same `name` parameter.

PR: Change name of workflow for conda-based installers

---

spyder/workers/updates.py

Apply suggestions from code review:
https://github.com/spyder-ide/spyder/pull/21423/files/314c3eab9735500ca249619300fcca3628fa5be6

PR: Follow-up to using the `requests` library for updates

---

spyder/plugins/onlinehelp/widgets.py

This can also happen when Spyder is installed in a Python 3.11 environment besides our installer.
Fixes #21171.

PR: Avoid pydev warning under all circumstances (Online help)

---

spyder/plugins/application/container.py

Fix an issue where the statusbar status "Checking for updates..." would persist after `WorkerUpdates` completed. See: https://github.com/spyder-ide/spyder/pull/21423#issuecomment-1762232364

PR: Fix issue where statusbar status was not updated properly after checking for updates

---

spyder/plugins/ipythonconsole/widgets/client.py

This happened when Spyder is connected to a kernel in JupyterLab and the user restart it there.
Fixes #21165.

PR: Avoid error when restarting external kernel (IPython console)

---

spyder/config/manager.py

A validation fro existence and passing and arg (new config value) where missing for the logic that handles removing nested options values (like the config of the LSP).
Fixes #21161

PR: Prevent errors when removing nested options values (Config)

---

spyder/widgets/findreplace.py
spyder/widgets/tests/test_findreplace.py

- This problem happens when users try to replace all occurrences of some text by an expression that contains backslashes.
- Also, add a regression test for this case.
Fixes #21007 

PR: Escape backslashes when replacing all occurrences of some text by another with them (Find/Replace)

---

spyder/config/base.py

* [N/A] Wrote at least one-line docstrings (for any new functions)
* [N/A] Added unit test(s) covering the changes (if testable)
* [N/A] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))
The autoconfiguration of the language is currently completely broken: when starting spyder on a e.g. french-installed OS, spyder still displays english by default.
This is because `spyder/config/base.py`'s `get_available_translations()` currently always return `['en']`, because `LANGUAGE_CODES` is currently missing a few cases of `spyder/locale/`. One can of course just add the missing cases, but better just at least support autoconfiguring the cases which are in `LANGUAGE_CODES` rather than breaking them all (Except for developers, which do need to …

PR: Fix interface language auto-configuration

---

.github/workflows/test-files.yml
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml
spyder/utils/conda.py
spyder/utils/tests/test_conda.py

This problem only happens on Windows and it appeared in Conda 23.9.0

PR: Fix functions that need to parse conda output for its latest version (Utils)

---

spyder/plugins/completion/plugin.py

The start and shutdown providers logic was missing updating the `language_status` attribute which is used to determine the providers that are available for a certain language. In the case of a completion request all responses for the available providers need to be aggregated, so all providers need to be waited before a response is made available. This caused that by disabling one of the providers no reponse was able to be retrieved but still that provider was expected to give a reponse
Also, there is some logic to handle a timeout but only the LSP provider is marked as slow and at least 3 providers need to be marked as slow to trigger the logic. For more details about that see:
https://github.com/spyder-ide/spyder/blob/6d531015aaf0a91cc88a8fab945832206b2d93ab/spyder/plugins/completion/plug …

PR: Fix enabling/disabling individual providers (Completions)

---

spyder/plugins/variableexplorer/widgets/arrayeditor.py
spyder/utils/icon_manager.py

This PR adds a toolbar to the array editor with five buttons:  Edit, Copy, Format, Resize and Toggle Background. The last three are buttons currently at the bottom of the array editor, which are removed in this PR. The result looks as follows:
For 3d arrays, it's possible to save some space at the bottom by putting everything on one line; let me know if you would prefer that.
Here is a video showing the toolbar buttons in action:
https://github.com/spyder-ide/spyder/assets/7941918/78e207d8-dd68-45f7-8ad3-9c4cfd43040e
Fixes #21315
and understand I am releasing the same under Spyder's MIT …

PR: Add toolbar to array editor (Variable Explorer)

---

spyder/plugins/outlineexplorer/tests/test_widgets.py
spyder/plugins/outlineexplorer/widgets.py

This fixes https://github.com/spyder-ide/spyder/issues/21456 where unchecking "Display variables and attributes" in the outline does not work.
Issue debug log:
```
2023-10-31 11:28:00,930 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Refresh EditorStack
2023-10-31 11:28:00,931 [DEBUG] [spyder.plugins.outlineexplorer.widgets] -> Set current editor to file /Users/remisalmon/test.py
2023-10-31 11:28:00,940 [DEBUG] [spyder.config.manager] -> Sending notification to observers of display_variables option in configuration section outline_explorer
2023-10-31 11:28:00,940 [DEBUG] [spyder.plugins.outlineexplorer.widgets] -> Current and new trees for file /Users/remisalmon/test.py are the same, so no update is necessary
```
I believe this uses the wrong operator from the `intervaltree` package …

PR: Fix unchecking `Display variables and attributes` not updating tree (Outline explorer)

---

.github/scripts/install.sh

That's because that version is compatible with PyQt 5.12, which is what we're using for testing on Linux.

PR: Install QDarkstyle 3.2.0 on Linux pip slots (CI)

---

spyder/widgets/helperwidgets.py

Missing cast to int to prevent issues with PyQt5 on Python >= 3.10
Fixes #21520 

PR: Cast to `int` parameters used inside `ItemDelegate.sizeHint` return value (Widgets)

---

spyder/plugins/editor/extensions/docstring.py
spyder/plugins/editor/extensions/tests/test_docstring.py

Remove comments from the function definition lines before generating docstrings. Comments are removed, but # symbols inside quotes are kept as these might be default function arguments.
Before:
With this PR:
Fixes #21527
I certify the above statement is true and correct: @rhkarls

PR: Remove comments from the function definition lines before generating docstrings

---

.github/scripts/install.sh
.github/workflows/installers-conda.yml
installers-conda/build-environment.yml

- This avoids IPykernel 6.27.0, which broke the `%edit` magic, and QDarkstyle 3.2.1, which doesn't work with PyQt 5.12.
- Also, fix failures with the Conda-based Linux installer.

PR: Pin IPykernel to 6.26.0, QDarkstyle to 3.2.0 and fix building the Linux installer (CI)

---

spyder/workers/updates.py

Added keyword argument to string format method in order to resolve `KeyError`.
Fixes #21546

PR: Fix KeyError issue with format in update worker

---

spyder/plugins/variableexplorer/widgets/arrayeditor.py
spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py
spyder/plugins/variableexplorer/widgets/objectexplorer/tests/test_objectexplorer.py
spyder/plugins/variableexplorer/widgets/objectexplorer/toggle_column_mixin.py
spyder/plugins/variableexplorer/widgets/tests/test_arrayeditor.py
spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py
spyder/utils/qthelpers.py
spyder/widgets/collectionseditor.py
spyder/widgets/tests/test_collectioneditor.py

This adds a Refresh button to the array editor, the dataframe editor, the collection editor and the object explorer. 
Clicking the Refresh button in the array editor refreshes the editor with the current value of the array variable:
https://github.com/spyder-ide/spyder/assets/7941918/a481ba3b-544b-4b93-8cc6-a6c43d4cd13b
The same for the dataframe editor:
https://github.com/spyder-ide/spyder/assets/7941918/ff8ba761-909b-407d-9fde-c45b03e59f70
The same for the collection editor:
https://github.com/spyder-ide/spyder/assets/7941918/15c51175-185e-454d-a0e0-5865196157e6
The same of the object explorer:
https://github.com/spyder-ide/spyder/assets/7941918/41e88831-63a9-4566-87c9-05832548b0a5
It is possible to refresh editors opened from the Variable Explorer or editors opened from other editors, …

PR: Add Refresh button to editors from Variable Explorer

---

spyder/plugins/editor/widgets/codeeditor/codeeditor.py
spyder/plugins/editor/widgets/codeeditor/tests/test_comments.py

This PR changes the way spyder uncomments code and fixes an issue where toggling comments on and off over lines with an uneven number of leading whitespaces would add an extra whitespace (regardless of indentation level).
Example:
```python
from pprint import pprint
x = [1,
2]
y=[1,
2]
def f(x, y):
pprint(x,
y)
```
Commenting (Ctrl+1) then uncommenting (Ctrl+1), before:
```python
from pprint import pprint
x = [1,
2]
y=[1,
2]
def f(x, y):
pprint(x,
y)
```
Commenting (Ctrl+1) then uncommenting (Ctrl+1), after:
```python
from pprint import pprint
x = [1,
2]
y=[1,
2]
def f(x, y):
pprint(x,
y)
```
This PR breaks compatibility with spyder 3: commenting with spyder 3 and uncommenting with spyder 4 with break indentation but that should not be happening much.
This PR also break toggling comments …

PR: Fix commenting/uncommenting to not change leading whitespaces

---

spyder/plugins/variableexplorer/widgets/objectexplorer/tests/test_objectexplorer.py

The row counts for Python 3.11 appear to have changed in a couple of tests in the `test_objectexplorer.py` file.  This patch allows the tests to pass in Python 3.11.  They have been successfully applied in Debian.

PR: Fix two tests for Python 3.11

---

spyder/plugins/ipythonconsole/tests/conftest.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

Python 3.12 inlines comprehensions, so the number of steps in the debugger required to enter the list comprehension has reduced from 4 to 2.  This patch sets the number of steps to be conditional on the Python version being tested.
Fixes #21570

PR: Fix list comprehension test for Python 3.12

---

spyder/api/widgets/combobox.py
spyder/api/widgets/comboboxes.py
spyder/plugins/appearance/confpage.py
spyder/plugins/completion/providers/languageserver/widgets/serversconfig.py
spyder/plugins/completion/providers/snippets/conftabs.py
spyder/plugins/completion/providers/snippets/widgets/snippetsconfig.py
spyder/plugins/editor/panels/classfunctiondropdown.py
spyder/plugins/findinfiles/widgets/combobox.py
spyder/plugins/help/widgets.py
spyder/plugins/layout/widgets/dialog.py
spyder/plugins/preferences/widgets/config_widgets.py
spyder/plugins/projects/widgets/projectdialog.py
spyder/plugins/projects/widgets/qcookiecutter.py
spyder/plugins/run/confpage.py
spyder/plugins/run/widgets.py
spyder/plugins/tours/widgets.py
spyder/plugins/variableexplorer/widgets/arrayeditor.py
spyder/utils/stylesheet.py
spyder/widgets/comboboxes.py
spyder/widgets/helperwidgets.py

- This allows us to improve the style of all comboboxes used in the application.
- UI improvements:
- Add more padding to combobox items (it was almost non-existent).
- Change hover color to the one used for any other widget in Spyder.
- Remove visual glitch to the left of items for some comboboxes.
- Fix misalignment of combobox popup on Mac.
- Add padding around the combobox.
- Paint combobox separators according to the interface theme.
- Improve style of the class/function dropdown a bit by adding margins around it and between its comboboxes.
- Make the QFontComboBox'es used in Preferences to follow the style for other comboboxes as well.
- UX improvements: 
-  Disable context menu of editable comboboxes because it's not localized and it doesn't use our API.
- Other changes:
- Replace …

PR: Add new combobox widgets (API)

---

spyder/plugins/ipythonconsole/widgets/main_widget.py

Handle possible `RuntimeError` when hiding IPython Console infowidget and set related attributes to not use it after. 
Fixes #21509 

PR: Handle infowidget possible RuntimeError when hiding it (IPython Console)

---

spyder/plugins/editor/panels/scrollflag.py

I was unable to reproduce this but the fix is more or less straightforward.
Fixes #21600.

PR: Catch error when the scrollbar has zero height in the scrollflag panel (Editor)

---

spyder/plugins/findinfiles/plugin.py
spyder/plugins/findinfiles/tests/test_plugin.py
spyder/plugins/findinfiles/widgets/combobox.py
spyder/plugins/findinfiles/widgets/main_widget.py
spyder/plugins/findinfiles/widgets/tests/test_widgets.py

- In `SearchInComboBox`, disable clear list item and hide separator between regular items and other directories when users have not selected any other directory. 
- Remove tooltips from the `SearchInComboBox` items because they were annoying and unnecessary.
- Change text of the action shown in the `Search` menu that points to the Find pane. That's to give users a better idea about it.
- Fix bug when clicking on that action and (apparently) Spyder can't grab text for it.  
- Use an enum for the index items used in `SearchInComboBox`. This allows us to access them more easily.
- Leave results browser visible after the first search is performed. This was very annoying because the empty message was shown when a new search was started or when no results were found. 
**Before**
**After**
Fixes …

PR: Make some UI/UX improvements to the Find pane

---

spyder/plugins/editor/widgets/codeeditor.py

This fixes an issue where formatting a line selected by a double click includes and formats the next line.
In some cases this even breaks the code; when using black and selecting a line outside the range of the text the formatting wraps around:
```
> cat -n temp.py
1	a = 'hello'
2	b = ["a", "very", "very", "very", "very", "very", "very", "very", "very", "long", "line"]
3	c =  42
> black --diff --line-ranges 3-3 temp.py
--- temp.py	2023-12-27 04:53:07.369501+00:00
+++ temp.py	2023-12-27 04:58:40.860306+00:00
@@ -1,3 +1,3 @@
a = 'hello'
b = ["a", "very", "very", "very", "very", "very", "very", "very", "very", "long", "line"]
-c =  42
+c = 42
would reformat temp.py
> black --diff --line-ranges 3-4 temp.py
--- temp.py	2023-12-27 04:53:07.369501+00:00
+++ temp.py	2023-12-27 …
```

PR: Fix extra line in range when formatting selection

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/utils/switcher_manager.py
spyder/plugins/switcher/api.py
spyder/plugins/switcher/container.py
spyder/plugins/switcher/plugin.py
spyder/plugins/switcher/widgets/proxymodel.py
spyder/plugins/switcher/widgets/switcher.py

- This broke in #21275.
- Expand test suite to catch this problem in the future.
- Remove direct usage of `CONF` in `EditorSwitcherManager`.
- Correctly align Switcher vertically with the main menu and toolbar.
- Fix jumping to different symbols in the editor from the Switcher. This probably broke in #20837.

PR: Fix errors when displaying the Symbols switcher

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
spyder/config/main.py
spyder/plugins/ipythonconsole/confpage.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/variableexplorer/widgets/namespacebrowser.py
spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py

Add two new options, for the font size and the position of the bottom edge, for inline plots in the IPython console. The reason for this was discussed in issue #19672. Send these options to the Spyder kernels, where they will be used in a partner PR (I hope I'm doing that right, I have never done this before).
When writing the code, I noticed that the (?) icons for the tooltips of some spinboxes (resolution, width, height) was missing, so I added these as well.
The Preferences page now looks like this:
For comparison, this is what it looks before the PR:
Fixes #19672
Depends on spyder-ide/spyder-kernels#477
with respect to all commits and content …

PR: Add new options for font size and bottom edge for inline plot

---

spyder/plugins/plots/widgets/figurebrowser.py

Change the border around the thumbnail of the current plot in the Plots pane to 3px wide and gray (`COLOR_TEXT_3`) for clarity and consistency with the overall styling. This style was suggested in [this comment](https://github.com/spyder-ide/spyder/issues/21046#issuecomment-1825936157).
Screenshot after the change in dark theme:
Screenshot after the change in light theme:
Fixes #21046

PR: Change style of border around thumbnail of current plot

---

spyder/api/widgets/comboboxes.py
spyder/api/widgets/menus.py
spyder/api/widgets/toolbars.py
spyder/app/mainwindow.py
spyder/plugins/findinfiles/widgets/main_widget.py
spyder/plugins/findinfiles/widgets/results_browser.py
spyder/plugins/preferences/widgets/configdialog.py
spyder/plugins/shortcuts/plugin.py
spyder/plugins/variableexplorer/widgets/namespacebrowser.py
spyder/utils/qthelpers.py
spyder/widgets/collectionseditor.py
spyder/widgets/dock.py
spyder/widgets/simplecodeeditor.py

- Prevent freeze when switching and moving panes. That was calling `findChildren(QTabBar)`, which takes a long time now (probably due to the new style for special tabbars). To fix that, we call that method with a timer every minute in the main window, which avoids the freeze.
- Reposition menus so they are correctly aligned both horizontally and vertically. Small glitches were introduced due to our new usage of borders in menus.
- Make menus associated to extension button toolbars look like a `SpyderMenu`.
- Fix double clicks on the Variable Explorer. That was opening two editors per variable.
- Remove global proxy style because it was interfering with the new style for menus. Instead, apply the styles declared in it on `SpyderMenu` and `SpyderComboBox`.
- Fix setting the same shortcut in …

PR: Fix several UI regressions and errors

---

spyder/plugins/plots/widgets/main_widget.py

Change the icon for "Remove all plots" in the Plots pane to two rubbish bins, for consistency with the icon for "Remove plot" which is a simple rubbish bin.
Before | After
-- | --
Fixes #21675

PR: Change icon for "Remove all plots"

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/panels/linenumber.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/base.py
spyder/plugins/editor/widgets/codeeditor/codeeditor.py
spyder/plugins/editor/widgets/codeeditor/lsp_mixin.py
spyder/plugins/editor/widgets/codeeditor/tests/test_codeeditor.py
spyder/plugins/editor/widgets/codeeditor/tests/test_formatting.py
spyder/plugins/editor/widgets/codeeditor/tests/test_hints_and_calltips.py
spyder/plugins/editor/widgets/completion.py
spyder/plugins/findinfiles/widgets/main_widget.py
spyder/plugins/findinfiles/widgets/results_browser.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/help.py
spyder/widgets/calltip.py
spyder/widgets/mixins.py

* Show hovers on top of objects if there's space available. That prevents cluttering the view of code users are writing in the moment (I took this idea from VSCode).
* Show pointing hand cursor on top of hovers and completion hints that can display help.
* Hide calltip widget when users are scrolling the file and when they press the page up/down keys.
* Prevent hiding completion hints when clicking on them or moving the mouse out of them. Now they are hidden only when the completion widget is.
* Remove support for showing multiple signatures on hints and calltips. That failed in most cases because it was extracting signatures from anywhere in the corresponding docstring.
* Refactor code in `BaseEditMixin` related to tips so it's easier to understand and extend in the future.
* Cover …

PR: Improve hovers, completion hints and calltips

---

spyder/widgets/helperwidgets.py

Width and height values are being converted to integer type.
```python
def sizeHint(self, option, index):
options = QStyleOptionViewItem(option)
self.initStyleOption(options, index)
doc = QTextDocument()
doc.setHtml(options.text)
doc.setTextWidth(options.rect.width())
return QSize(int(doc.idealWidth()), int(doc.size().height()))`
```
Fixes #21694

PR: Fix error when computing the size hint of `ItemDelegate` in Python 3.10+

---

spyder/plugins/editor/plugin.py

A docstring was accidentally quoted with a single quote followed by a triple quote

PR: Fix triple-quoted docstring of a method (Editor)

---

spyder/plugins/editor/tests/test_plugin.py
spyder/plugins/editor/widgets/tests/test_warnings.py
spyder/plugins/variableexplorer/widgets/objectexplorer/tests/test_objectexplorer.py
spyder/widgets/tests/test_reporterror.py

These fix all of the issues identified in #21688 except for `test_move_to_first_breakpoint[False]`.  The tests using `called_with` were both broken, and this patch also fixes this.
Almost resolves (fixes) #21688, but not quite

PR: Fix some tests failing on Python 3.12

---

spyder/utils/conda.py
spyder/workers/updates.py

- That's necessary to unpack its result correctly in the worker in charge of checking if a new Spyder version is available.
- Also, improve a bit condition that checks the result of that function in the worker.
Fixes #21711 

PR: Make `get_spyder_conda_channel` return a tuple of None's if it fails (Utils)

---

spyder/plugins/editor/plugin.py

This follows the discussion in PR #21692 and fixes the issue identified there.  Turns out that `count=1` is not needed as the regex is anchored to the start of the string.

PR: Improve `renamed_tree` method (Editor)

---

spyder/config/lsp.py
spyder/plugins/completion/providers/languageserver/provider.py
spyder/plugins/editor/widgets/codeeditor/tests/conftest.py

This is a follow up to https://github.com/spyder-ide/spyder/pull/21629 removing some unused code for python-lsp-black 1.x that was removed in that pull request.
This is merging into master since some comments are mentioning Spyder 6. 
None
I certify the above statement is true and correct: remisalmon

PR: Remove old `python-lsp-black` related code

---

spyder/config/utils.py
spyder/plugins/projects/tests/test_plugin.py
spyder/plugins/projects/utils/watcher.py

- Switch from Watchdog's OS-based observer to the polling one because it emits less events on Linux and behaves better on Windows (there doesn't seem to be problems on Mac, but we prefer to have a single solution for all OSes).
- Exclude binary files and hidden directories from the watcher.
- Exclude directories such as `__pycache__` and `build` from the watcher too.
- Throttle changes reported by the watcher to avoid sending too many events to LSP servers.
Part of #10664.
I certify the above statement is true and …

PR: Improve performance of workspace watcher (Projects)

---

spyder/plugins/application/confpage.py

- Prevent setting scale factors less than one by making the regular expression we use to check for correct ones start at that value.
- If users try to set an empty scale factor, select automatically the `Normal` option instead.
Fixes #21733 

PR: Fix error when trying to set an empty scale factor (Preferences)

---

.github/workflows/installer-macos.yml
installers/macOS/req-build.txt
installers/macOS/setup.py

Add arm64 to build matrix
* Update Python to 3.10.11 (arm64 builds not available for Python 3.9 from setup-python)
* Update DMG name to include Spyder version and architecture
Note that py2app 0.28.5, I believe, should have updated the `black` recipe and resolved #19743. However, there is still an issue; see ronaldoussoren/py2app#518. The kluges from #21629 are still required.
Fixes #20232

PR: Build arm64 versions of Spyder's standalone macOS application

---

.github/workflows/installer-macos.yml

Spyder 5.5.1rc0 macOS x86_64 exhibits
```python
RuntimeError: tk.h version (8.5) doesn't match libtk.a version (8.6)
```
This exhibited previously for local arm64 builds and seemed to be the result of incorrect tcl-tk Python build flags. However, this did not exhibit for Python 3.9.14 x86_64. I suspect that there is a change in the `setup-python` build flags between 3.9, 3.10, x86_64, and arm64. Nevertheless, the easiest fix right now is to revert to 3.9.14 for x86_64. 🤞🏼

PR: Use Python 3.9.14 for x86_64 macOS application build

---

installers-conda/build_conda_pkgs.py
installers-conda/certkeychain.sh

Fix release build issues
* Make temp directory if it doesn't already exist when creating keychain
* Use a git patch to update Spyder's version when building conda package. This ensures a clean repo for `get_version` to report the version accurately.
Fixes #21776

PR: Fix release build issues

---

.github/workflows/installers-conda.yml

Added macOS-arm64 target platform using M1 runner in response to [this blog post](https://github.blog/changelog/2023-10-02-github-actions-apple-silicon-m1-macos-runners-are-now-available-in-public-beta/).

PR: Add macOS-arm64 target platform using M1 runner (Installers)

---

spyder/plugins/ipythonconsole/utils/kernelspec.py

Windows start menu shortcut target uses `cwp.py` which omits `%PREFIX%\bin` from the `PATH` environment variable and Spyder does not activate conda environment for interpreters that are the same as Spyder's runtime environment. This confluence results in failure to find certain DLLs. Always activating conda environments should resolve this issue.
Fixes #21749

PR: Always activate a conda environment for IPython consoles

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/codeeditor/tests/test_hints_and_calltips.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/utils/kernel_handler.py
spyder/plugins/ipythonconsole/utils/kernelspec.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/mixins.py
spyder/plugins/projects/widgets/main_widget.py

- We need this fix in master after #21783.
- Stop debugging before closing clients. That avoids freezes and segfaults when closing Spyder, which are side effects from the fixes done here.
- Disable `pdb_prevent_closing` option when opening/closing projects. That's necessary to correctly restore the project or program session when a console is left in debugging mode (I discovered that bug while testing these changes).

PR: Avoid `conda run` capturing output in env activation (IPython console)

---

spyder/api/widgets/mixins.py
spyder/app/mainwindow.py
spyder/app/utils.py
spyder/config/utils.py
spyder/plugins/explorer/widgets/explorer.py
spyder/plugins/explorer/widgets/utils.py
spyder/plugins/findinfiles/widgets/search_thread.py
spyder/plugins/projects/plugin.py
spyder/plugins/projects/utils/watcher.py
spyder/plugins/projects/widgets/main_widget.py
spyder/plugins/projects/widgets/projectexplorer.py
spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py
spyder/plugins/variableexplorer/widgets/objectexplorer/toggle_column_mixin.py
spyder/utils/icon_manager.py
spyder/utils/stylesheet.py
spyder/widgets/collectionseditor.py

- Use a generic icon for unknown files instead of trying to detect if they are binary or not. That should speed up performance because relying on `chardet` for binary detection is slow.
- Don't show full path in tooltips of files and directories in Projects because it's not really necessary.
- Hide `.orig` files from view in Projects. Those are generated by git when a merge fails so we don't really need to display them.
- Add more padding to QTreeWidget/QTreeView items to make the interface look less packed.
- Switch between open/closed folder icons when collapsing/expanding directories in Files and Projects. That provides a better UI for those panes.
- Use Spyder project icon for the project root directory and its plugin.
| - | - | 
| …

PR: Additional UI/UX improvements for Files and Projects

---

installers/macOS/setup.py
spyder/plugins/application/container.py
spyder/workers/updates.py

Do not use version in artifact name. Instantiate `ApplicationUpdateStatus` for all installation types, but leave only visible for Windows and macOS standalone applications.
Fixes #21781

PR: Do not use version in macOS artifact name and fix names for the future Spyder 6 installers (Installers)

---

spyder/plugins/application/container.py
spyder/plugins/application/plugin.py
spyder/workers/updates.py

- The widget was not actually hidden when Spyder is not installed through our Windows and Mac apps (this is a follow-up of #21784, which tried to do the same).
- Avoid updating the widget status when it's not visible.
- Also, make worker that checks for updates emit `sig_ready` when it can't find the conda channel from which Spyder was installed. That allows the slots connected to that signal to do its job as expected.
- And change the text of `check_updates_action` when checking for updates to give better feedback to users about why that action is disabled.
and understand I am releasing …

PR: Fix visibility of status bar widget that checks for Spyder updates (Application)

---

spyder/config/main.py
spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py

Change the default value for the config option `pylab/inline/resolution` from 72 to 144, as discussed at our last development meeting. This is a quick but incomplete fix for issue #9148, that plots are of low quality. See the discussion of that issue for further explanation.
(I deleted the checklist because none of the items are applicable.)
Fixes #9148
Jitse Niesen

PR: Change default resolution of plots to 144 dpi

---

.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml

Resolves warning "Node.js 16 actions are deprecated" in CI workflows.

PR: Update to `codecove/action@v4` (CI)

---

spyder/utils/conda.py
spyder/utils/programs.py
spyder/utils/tests/test_conda.py

For the cases where conda environments are in non-standard locations, including possibly Spyder's runtime environment for conda installations, a conda executable may not be found.
This PR adds `condabin` directories, relative to Spyder's runtime executable and an optional Python executable, to the paths searched.
Optional extra search paths are added to `is_program_installed`.
Part of #20357.

PR: Add `condabin` directory, relative to `sys.executable` and provided `pyexec`, to paths searched for conda executable

---

installers-conda/resources/post-install.bat

Fix an issue where Spyder would automatically startup before the conda-based installer exited. This was due to a glob pattern that was not updated in Spyder's post-install script to accommodate removing the version from the installer file name.

PR: Fix issue where Spyder started automatically before conda-based installer exited

---

spyder/plugins/application/container.py
spyder/plugins/application/plugin.py
spyder/workers/updates.py

- This is a follow up of #21851, which fixed the widget issue for our Linux experimental installer but broke things for our Windows and Mac apps.
- Don't show generic errors while checking for updates to users because we can't give proper feedback to them on how to address the error. They'd only see a long and probably incomprehensible traceback, which wouldn't be really useful.
- Always emit the `sig_ready` signal after a check was performed so that the `Check for updates` action in the Help menu is enabled again (it's disabled while doing the check and it depends on `sig_ready` to be enabled after the check ends).
Fixes #21861.
with respect to …

PR: Fix showing update status bar widget in our apps at startup and other fixes to the update process (Application)

---

spyder/workers/updates.py

Fix validation to use 5.x installers names. The validation was giving the 6.x/conda installers formatting for the installers names since the validation was doing something like `parse("5.5.3") > parse("5")` which evaluates to `True`. That was making things fail since there are not assets over the 5.x releases using the new naming.
Also, updated some code and added a try-catch to prevent errors when trying to remove outdated files/directories from the directory used to download the installers.
Fixes #21905 
I …

PR: Fix validation to use Spyder 5 installer names when needed

---

spyder/api/shellconnect/main_widget.py
spyder/plugins/ipythonconsole/widgets/client.py

- `debugpy` is an optional dependency of IPykernel, so it is not necessarily installed with it.
- Also, fix showing an error message in panes connected to the IPython console when something is printed to the kernel stderr stream after it starts but before the prompt is shown. 
Fixes #21900.

PR: Add bening error when `debugpy` is not available (IPython console)

---

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py

This PR fixes two scrolling-related bugs in the dataframe editor.
Firstly, after my PR implementing Refresh in the master branch, the scrollbars were no longer visible. To fix this, I changed it so that the view (the UI element) is created only once instead of every time that the data is refreshed. As before a new model (which exposes the data) is created every time that the data is refreshed.
Secondly, a bug already present in Spyder 5 caused the editor to jump back if you sorted the last column of a large data frame, as well as some more odd behaviour. The fix for this is to set  the number of rows and columns loaded in the DataFrameHeaderModel using the information in the corresponding DataFrameModel. This is the bug reported in issue #21627.
This PR also add regression test for both …

PR: Fix issues with scrolling in dataframe editor

---

spyder/plugins/ipythonconsole/scripts/conda-activate.bat
spyder/plugins/ipythonconsole/widgets/main_widget.py

This also fixes getting the Python version for external interpreters located in directories with spaces (getting the IPython version will be fixed in master because it requires additional changes).
Fixes #21662.

PR: Fix starting kernels in conda envs placed in directories with spaces (IPython console)

---

.github/workflows/installer-macos.yml
installers/macOS/notarize.sh

Copied notarize.sh from master branch, but retaining DMG variable.
Just used the version of `notarize.sh` from `master`.
`altool` was deprecated last year, but I anticipated that we would not be developing on 5.x for this long, so I did not update to `notarytool`. The notarizing on `master` has always used `notarytool`.
Fixes #21951

PR: Use `notarytool` instead of `altool` (Installers)

---

spyder/plugins/editor/widgets/status.py

- The worker we use to get git output in order to update `VCSStatus` can return `None` sometimes.
- This PR deals with that possibility to not report an error to users.
Fixes #21865.

PR: Prevent error when we don't get git output to update the `VCSStatus` widget (Editor)

---

binder/environment.yml
requirements/tests.yml
setup.py

Latest `pytest-timeout` (2.3.1) seems like is not compatible with `pytest` 6.x. This doesn't affect pip slots over the CI since there the package version selected to be installed is 2.2.0 but seems like the constraint is missing for the conda-forge recipe so the environment ends up having `pytest` 6.2.5 and `pytest-timeout` 2.3.1. See https://github.com/conda-forge/pytest-timeout-feedstock/issues/19
Try to overcome this by updating the `pytest` contraint from `<7.0` to `<8.0`
I certify the above statement is true …

PR: Update `pytest` constraint to `<8.0`

---

spyder/api/widgets/dialogs.py
spyder/api/widgets/menus.py
spyder/plugins/appearance/widgets.py
spyder/plugins/application/widgets/about.py
spyder/plugins/completion/providers/languageserver/widgets/serversconfig.py
spyder/plugins/completion/providers/snippets/widgets/snippetsconfig.py
spyder/plugins/editor/widgets/autosaveerror.py
spyder/plugins/editor/widgets/gotoline.py
spyder/plugins/editor/widgets/recover.py
spyder/plugins/explorer/widgets/explorer.py
spyder/plugins/explorer/widgets/fileassociations.py
spyder/plugins/ipythonconsole/widgets/kernelconnect.py
spyder/plugins/layout/widgets/dialog.py
spyder/plugins/mainmenu/plugin.py
spyder/plugins/preferences/widgets/configdialog.py
spyder/plugins/projects/widgets/projectdialog.py
spyder/plugins/pythonpath/widgets/pathmanager.py
spyder/plugins/run/widgets.py
spyder/utils/stylesheet.py
spyder/widgets/dependencies.py
spyder/widgets/sidebardialog.py

- On Linux, Qt adds by default icons to the standard buttons used in dialogs (e.g. `Ok`, `Cancel` , `Reset`, etc). However, that usually doesn't look good in Spyder because those icons come the operating system icon theme. So, in this PR I decided to remove them.
- Increase vertical padding of buttons a bit (from `3px` to `4px`) to make them look better.
- Fix a visual glitch with the positioning of app menus on Windows and Linux.
- Fix an error displaying app menus on Mac.
- No icons for buttons in dialogs and increased vertical padding for them
Before | After
-- | --
- Visual glitch in app menus
Before | After
-- | --
with respect to all commits …

PR: Remove icons from standard buttons in dialogs (UI/UX)

---

spyder/plugins/layout/plugin.py

- This is necessary if users start a Spyder 5 session after running a Spyder 6 one before.
- The reason is that we had to bump the window state version in Spyder 6 due to the migration of the Editor to the new API. And that requires reapplying the dock tabbar style because it's reset by Qt when a different state version is used.
- The changes in master to account for the inverse situation (i.e. starting Spyder 6 after a Spyder 5 session) are different. I'll apply them when merging this PR with that branch.
I …

PR: Reapply dock tabbar style if previous session was a Spyder 6 one (Layout)

---

spyder/workers/updates.py

The validation used when defining the installer name to be downloaded (to go from 5.x to 6.x) was using `platform.system == 'Darwin'` instead of `platform.system() == 'Darwin'`. That causes that the `.sh` Linux installer gets downloaded for not only Linux but also macOS. Noticed this when trying to update Spyder 5.5.3 to 5.5.4 on macOS.

PR: Fix macOS check when defining installer name string for download (Installers)

---

.github/workflows/installers-conda.yml
installers-conda/build_installers.py
pyproject.toml
spyder/__init__.py
spyder/plugins/updatemanager/container.py
spyder/plugins/updatemanager/plugin.py
spyder/plugins/updatemanager/scripts/install.bat
spyder/plugins/updatemanager/scripts/install.sh
spyder/plugins/updatemanager/widgets/status.py
spyder/plugins/updatemanager/widgets/update.py
spyder/plugins/updatemanager/workers.py

* The update manager statusbar widget is now hidden except when
* An update is available
* Downloading an update
* Bootstrap and dev versions no longer block checking for updates at startup. Bootstrap and editable installs of Spyder check for updates using the release url.
* "Check for updates" action removed from the statusbar widget
* "Spyder: " text is removed from the statusbar status value. This was used previously as a prefix to the Spyder version that would be displayed when idle. Now that the widget is hidden when idle, "Spyder: " prefix seems unnecessary.
* Uncaught exceptions in the update worker are sent to the error reporter.
* `version_info` now includes pre-release item. To ensure that the development version is greater than the latest release tag, including unstable …

PR: Only show UpdateManager statusbar widget while updating and when updates are available

---

spyder/api/widgets/__init__.py
spyder/api/widgets/auxiliary_widgets.py
spyder/api/widgets/main_container.py
spyder/api/widgets/main_widget.py
spyder/plugins/ipythonconsole/api.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/variableexplorer/widgets/main_widget.py
spyder/utils/qthelpers.py

- Corner widgets were not added in the right order after #21353. This is clear for the IPython console corner widgets, as seen below.
- Fix `before` kwarg of `PluginMainWidget.add_corner_widget` and remove the need to pass an ID to it to make it simpler.
- Allow to pass actions (i.e. not only widgets) to `PluginMainWidget.add_corner_widget`.
- Use these fixes to add corner widgets to the Variable Explorer using our API.
| Before | After
| - | - |
| ![image](https://github.com/spyder-ide/spyder/assets/365293/53ee9663-6d93-4cc1-b161-31929d6ab940) | ![image](https://github.com/spyder-ide/spyder/assets/365293/67a3b7e0-4b34-4681-b901-9ab75fe427ab)
with …

PR: Fix adding corner widgets in dockable plugins (API)

---

spyder/utils/conda.py

Fixes #22007.
```
File "/XXX/lib/python3.11/site-packages/spyder/workers/updates.py", line 119, in start
channel, channel_url = get_spyder_conda_channel()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/XXX/lib/python3.11/site-packages/spyder/utils/conda.py", line 235, in get_spyder_conda_channel
if package_info["name"] == 'spyder':
~~~~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```
Reponse from conda:
`{'caused_by': 'None', 'error': "CondaError: Expected exactly one `egg-info` directory in 'XXX', via egg-link 'lib/python3.11/site-packages/XXX.egg-link'. Instead found: ('XXX.egg-info', 'XXX.egg-info').  These are often left over from legacy operations that did not clean up correctly.  Please remove all but one of these.", 'exception_name': …

PR: Avoid iterating over non-dict objects if conda responds with errors

---

spyder/plugins/explorer/widgets/explorer.py
spyder/widgets/collectionseditor.py

This PR fixes multiple context menu actions when using PySide2. Note: This PR is for `5.x` branch, however, is also applicable to `master`. Please let me know if I should create a PR for `master` as well.
rear1019

PR: Fixes to improve compatibility with PySide2

---

spyder/plugins/ipythonconsole/scripts/conda-activate.bat

Kernel connection file argument needs to be quoted to prevent trying to use a faulty started kernel when the connection file path used has spaces (when, for example, the current user account name has spaces).
Fixes #21937

PR: Quote kernel connection file in conda activation script (IPython Console)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/comms/utils.py
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
external-deps/spyder-kernels/spyder_kernels/console/shell.py
spyder/plugins/ipythonconsole/confpage.py
spyder/plugins/ipythonconsole/tests/conftest.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/restartdialog.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/ipythonconsole/widgets/status.py

- The widget was not showing the actual backend but instead `Interactive` for interactive backends.
- Make the widget show the right backend after kernel restarts.
- Hide the widget on kernel failure or if Matplotlib is not available in the kernel (there's no need to show it if there's nothing to report) 
- Make `pylab/autoload` option require a kernel restart (that's necessary when disabled so that the Numpy and Matplotlib star imports are removed).
- Fix applying several options that require a kernel restart (before we were applying only the first option).
- Expand tests to cover most of these changes. 
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/485
- Move text about backend options to a tip in the IPython console config page
| - | - |
| …

PR: Make Matplotlib status bar widget show the right backend and fix some errors related to kernel restarts for options that require them

---

spyder/app/tests/conftest.py
spyder/plugins/completion/plugin.py
spyder/plugins/completion/providers/fallback/actor.py
spyder/plugins/completion/providers/languageserver/provider.py
spyder/plugins/completion/providers/languageserver/tests/conftest.py
spyder/plugins/completion/providers/snippets/provider.py
spyder/plugins/completion/providers/snippets/tests/conftest.py
spyder/plugins/completion/tests/conftest.py

Properly handle instrospection usage via the Completions plugin configuration
Fixes #22012

PR: Fix introspection testing (CI)

---

.github/scripts/installer_test.sh
.github/workflows/installers-conda.yml
installers-conda/build-environment.yml
installers-conda/build_conda_pkgs.py
installers-conda/build_installers.py
installers-conda/resources/post-install.sh
installers-conda/resources/runtime_env.yml
spyder/plugins/updatemanager/scripts/install.bat
spyder/plugins/updatemanager/scripts/install.sh
spyder/plugins/updatemanager/widgets/update.py

The update manager plugin now uses an explicitly rendered conda-lock file in order to perform an incremental (minor/micro) update to Spyder in a conda-based installation environment. Previously the update manager simply performed a `conda install`.
Since conda-forge packages for releases are not available at the time of installer workflow runs, the checksum is removed from the Spyder spec in the conda-lock file. The checksum will be different for the Spyder conda package built on our CI vs. conda-forge, resulting in a `ChecksumMismatchError`. Removing the checksum in the conda-lock file avoids this error.

PR: Use conda-lock files to incrementally update conda-based installers

---

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/main_widget.py

- This was a regression introduced by #22057.
- Also, expand test suite to check that action is working as expected.
Fixes #22084

PR: Fix callable associated to `restart_action` (IPython console)

---

.github/workflows/installers-conda.yml

Resolves "Error: EISDIR: illegal operation on a directory, read" on linux for release asset upload. constructor creates a tmp directory in the distribution directory for some reason, so must exclude it.
Successfully tested with a release on my fork: https://github.com/mrclary/spyder/releases/tag/v6.0.0b2.dev2

PR: Fix workflow glob (Installers)

---

.github/workflows/installer-macos.yml

Update macOS from 11 to 12. macOS 11 runner image will be removed from Github on 2024/6/28.

PR: Update macOS from 11 to 12 in installer workflow

---

.github/workflows/installer-macos.yml
installers/macOS/req-build.txt

Constrain `setuptools<70.0.0` for macOS standalone installer to resolve "ImportError: cannot import name 'packaging' from 'pkg_resources'".
Also, missed a macos-11 spec on PR #22102.

PR: Constrain setuptools for macOS standalone installer

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
external-deps/spyder-kernels/spyder_kernels/utils/mpl.py

- Matplotlib get_backend returns lowercase in version >=3.9.0.
- Update to `spyder-kernels` accommodates this change.
- Dependes on https://github.com/spyder-ide/spyder-kernels/pull/489.

PR: Fix detecting Matplotlib backend for its 3.9.0 version (IPython console)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
external-deps/spyder-kernels/spyder_kernels/console/shell.py
external-deps/spyder-kernels/spyder_kernels/console/start.py
spyder/plugins/ipythonconsole/tests/conftest.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py

- Depends on https://github.com/spyder-ide/spyder-kernels/pull/487.
Fixes #22034
Fixes #10932

PR: Fix issue where Spyder's inline graphics preferences were not applied

---

spyder/utils/conda.py

I really don't know when this situation could happen, i.e. Spyder installed in a conda env and yet not available in the output of `conda list`. But since it was reported by a user, we need to address it.
Fixes #22054.

PR: Fix error when we can't detect Spyder in `conda list` output (Utils)

---

spyder/plugins/remoteclient/api/client.py

Refactor server starting logic and getting server info to use with jupyter_server api
It's unnecessary to use jupyterhub when always only using one server per user.
Fixes #

PR: Use `jupyter_server` instead of `jupyterhub` for remote client plugin

---

spyder/api/asyncdispatcher.py

Allow AsyncDispatcher to get the "main thread" running loop without depending on `asyncio.set_event_loop` and `asyncio.get_running_loop` so it won't trigger conflict with how `jupyter_core.utils.run_sync` handles creating, setting and executing event loops.
Also, refactor type hints to help with hinting decoreted async functions.
@hlouzada

PR: Fix conflict between AsyncDispatcher and `run_sync` function of `jupyter_core`

---

spyder/plugins/editor/widgets/editorstack/editorstack.py
spyder/plugins/editor/widgets/splitter.py

- I followed the work done in https://github.com/spyder-ide/spyder/pull/21685
- PySide6 still doesn't work. tested with 6.7.0
- Just trying to help increase the compatibility of Spyder with our software stack (conda-forge + pyside6)
Fixes #
Mark Harfouche

PR: Address small PySide2 compatibility issues

---

installers-conda/build_installers.py
spyder/plugins/updatemanager/scripts/install.sh

* Fixed typo that prevented launching Spyder after completing update in runtime environment.
* Exclude `pip` from installer base environment.

PR: Fix issue where macOS installer update fails to launch Spyder

---

.github/workflows/installers-conda.yml
installers-conda/build-environment.yml
installers-conda/build_conda_pkgs.py
installers-conda/build_installers.py

* Patch recipe `conda_build_config.yaml` on CI in order to replicate the build string hash on conda-forge.
* Use `recipe_clobber.yaml` and `recipe_append.yaml` mechanisms to patch `meta.yaml` instead of find/replace.
* Include `label/spyder_dev` in the url for Spyder in the conda-lock file, if non-stable distribution
* Fix an issue where the shortcut was not found after macOS update, preventing post-update launching of Spyder.
Fixes #22201

PR: Fix issues with installers discovered after 6.0.0b2 was released

---

spyder/plugins/run/confpage.py
spyder/plugins/run/models.py
spyder/plugins/run/widgets.py

- Remove tabs in its confpage and improve wording in it to make easier for users understand how it works.
- Also, improve text shown in the `TipWidget`s of `RunDialog` to follow the text improvements done in the Run confpage.
Before
After
Fixes #

PR: Minor UI improvements to the Run entry in Preferences

---

Announcements.md
README.md
RELEASE.md

Basic changes to docs/processes files:
* Add an entry for the remote server work (Announcements) (I think I have not updated the details over the announcement message so probably there are more things worthy to mention :thinking:)
* Update conda badges links (README)
* Update badge for tests workflows syntax and point directly to each workflow page (README)
* Update instructions to made releases and remove mentions to 5.x branch (RELEASE)
* Update release steps order to follow https://github.com/spyder-ide/spyder/pull/22204#issuecomment-2196001799 discussion
and understand I am releasing …

PR: Update `README`, `RELEASE` and `Announcements` files

---

spyder/api/plugins/new_api.py
spyder/app/mainwindow.py
spyder/plugins/help/plugin.py
spyder/plugins/help/widgets.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/onlinehelp/plugin.py
spyder/plugins/onlinehelp/widgets.py

I've been involved with packaging on conda-forge for the last few years and unfortunately the situation for packaging QtWebEngine hasn't really improved.
I think Spyder is a REALLY important tool for those starting off with python and being able to co-install it in modern environments is also a really great asset.
However, ensuring that qt-webengine is updated is a constant challenge and we are having a hard time keeping up especially on windows and OSX.
I would really like to continue to recommend Spyder to users, but if there isn't a clear path toward compatibility with qt6 (for which we don't have the webengine plugin) it makes it a really hard sell.
The following patch would effectively silently disable the plugins that require WebEngine.
One modification I would like to propose is …

PR: Make QtWebEngine Optional

---

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/utils/kernel_handler.py
spyder/plugins/ipythonconsole/widgets/status.py

- Issue #22179 was caused because the kernel was not detected as alive after it starts in slow systems (i.e. those in which the kernel takes too long to start).
- Issue #22194 was a simple CommError when getting when the backend if the comm is not connected.
- Fix `test_restart_interactive_backend` on Windows. That allows to check if the `MatplotlibStatus` widget is working fine on it.
- Use `functools.partial` instead of `lambda` for the anonymous slots used in `MatplotlibStatus`. That's necessary because `lambda` slots prevent garbage collecting PyQt objects when `self` is used in them. However, `functools.partial` ones don't have that problem.
Fixes #22194.
Fixes #22179. …

PR: Fix errors when getting Matplotlib backend in the kernel (IPython console)

---

spyder/plugins/breakpoints/plugin.py
spyder/plugins/layout/plugin.py
spyder/plugins/onlinehelp/plugin.py
spyder/plugins/profiler/plugin.py
spyder/plugins/pylint/plugin.py

in developing https://github.com/spyder-ide/spyder/pull/22196 I found that this was a useful backport
Mark Harfouche - hmaarrfk

PR: Fix error when plugins required for tabification are unavailable (Layout)

---

spyder/plugins/variableexplorer/widgets/arrayeditor.py

Fix translation string due to missing space (`won'tbe` vs `won't be`) over the masked label tooltip of the `ArrayEditor` widget
Before:
After:

PR: Add missing space over masked label text (Variable Explorer - `ArrayEditor`)

---

spyder/api/plugins/new_api.py
spyder/app/mainwindow.py
spyder/plugins/help/plugin.py
spyder/plugins/help/widgets.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/onlinehelp/plugin.py
spyder/plugins/onlinehelp/widgets.py

xref: https://github.com/spyder-ide/spyder/pull/22196
Mark Harfouche hmaarrfk

PR: Backport of PR 22196 (Make QtWebEngine Optional)

---

.github/workflows/installers-conda.yml
installers-conda/build_installers.py
spyder/plugins/updatemanager/tests/test_update_manager.py
spyder/plugins/updatemanager/workers.py

We agreed to change the release workflow to PyPi -> conda-forge -> Github in order to produce sound conda-lock files on release for updating our conda-based applications. This results in the following changes to the installer CI workflow and update manager.
* The Spyder conda package will only be built on CI for PRs and workflow-dispatch triggers, not releases
* The conda-lock file will not be patched. For non-release events, this produces an accurate conda-lock file which cannot be used outside CI. For release events, this produces the accurate and portable conda-lock file.
* The update manager only looks at Github for releases.
This is a follow-up PR to #22204

PR: Update conda-lock for change in release workflow

---

CONTRIBUTING.md
bootstrap.py
spyder/api/plugin_registration/registry.py
spyder/api/plugins/new_api.py
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/app/utils.py
spyder/plugins/editor/widgets/main_widget.py
spyder/plugins/editor/widgets/window.py
spyder/plugins/layout/api.py
spyder/plugins/layout/layouts.py
spyder/plugins/layout/plugin.py
spyder/plugins/outlineexplorer/plugin.py
spyder/plugins/run/widgets.py
spyder/widgets/dock.py

- While translating our docs to Spanish, @LucyJimenez noted that the Outline is tabified next to Projects, but that's not the case for the default layout. So, this PR changes that, which I think is a good idea.
- For consistency, show Outline to the left when the editor is maximized and in editor windows.
- Fix setting any layout with the correct proportions declared in its definition. That was not working as expected, which made the Outline/Projects column in the default layout appear too thin.
- Fix bug that prevented to restore the previous layout at startup for some user defined layouts (see #21596).
- Fix bug that broke positioning Spyder in the right screen at startup. That was a regression introduced in #21572.
- Allow to run Spyder with PyQt6 or PySide6 from `bootstrap.py`. I did …

PR: Tabify Outline next to Projects in default layout and other layout improvements and fixes

---

.github/workflows/installer-macos.yml

Use the correct url for arm64 micromamba.
Fixes #22233

PR: Use the correct micromamba for arm64 architecture on macOS (Installers)

---

.github/workflows/installers-conda.yml

Temporarily suspend notarizing.
macOS notarizing is failing because new account terms and conditions agreement needs to be approved.
Revert this change after release of 6.0.0b3

PR: Temporarily suspend notarizing the macOS installer

---

spyder/api/widgets/menus.py
spyder/api/widgets/status.py
spyder/plugins/completion/providers/languageserver/widgets/status.py
spyder/plugins/ipythonconsole/widgets/status.py
spyder/utils/icon_manager.py

- Change background color and cursor shape (to pointing hand cursor) of widgets with which users can interact by clicking on them (I took this idea from VSCode).
- Fix position of menu shown when clicking on the LSP widget and build that menu with our API.
- Change icon shown when the LSP is down for a more meaningful one.
Fixes #

PR: Improve UI of status bar widgets (API/Completions)

---

spyder/config/utils.py

A non-ascii character in the list of file extensions appears to cause issues for the QFileDialog filter on macOS. This may be a bug in PyQt. Nevertheless, removing the offending extension resolves the issue.
Fixes #22248

PR: Remove a non-ascii file extension from QFileDialog filter

---

binder/environment.yml
conftest.py
install_dev_repos.py
installers/macOS/packages.py
requirements/main.yml
setup.py
spyder/app/find_plugins.py
spyder/dependencies.py
spyder/plugins/completion/plugin.py
spyder/utils/programs.py
spyder/utils/tests/test_programs.py

It is deprecated and the note says to move away when Python 3.7 is dropped.
Seems like now ;)
Python 3.8
Maintenance
Fixes #21545 
Mark Harfouche hmaarrfk

PR: Remove dependency on `pkg_resources` and use `importlib-metadata` instead

---

spyder/plugins/layout/api.py
spyder/plugins/layout/plugin.py

- We were not setting layouts correctly if the first plugin in the layout's area is missing.
- Also, tabify any plugin not available during the previous session (before we were doing that only for external plugins). That will include internal plugins that were automatically disabled in the first session (e.g. Help). 
- I found these problems while testing Spyder without WebEngine.
Fixes #

PR: Fix several errors with missing plugins when setting a layout

---

spyder/widgets/tabs.py

A tab removal makes the following ones to change their `index` (`<new index> = <old index> - 1`). Following that, there is a need to update the `index` attribute that the custom close button instances have. Otherwise, a `IndexError` (in the case of the Editor) can be raised. This fix also prevents raising an `AttributeError` when doing a similar interaction with IPython Console client tabs:
```python-traceback 
File "E:\Acer\Documentos\Spyder\spyder\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1970, in close_client
if not client.can_close:
AttributeError: 'NoneType' object has no attribute 'can_close'
```
Fixes #22033  …

PR: Update custom button tab index when removing intermediate tabs without changing current selected tab (Widgets)

---

spyder/plugins/layout/container.py
spyder/plugins/layout/plugin.py
spyder/plugins/layout/widgets/dialog.py

- The layout options were not reset as expected after a bump in `WINDOWS_STATE_VERSION`, which generated internal errors and missing menu entries in the UI the first time Spyder starts with a new version.
- I discovered these errors while testing that the layout is applied as expected when moving from Spyder 5 to 6.
- Also, remove some odd capitalization in several translation strings. 
Fixes #

PR: Fix resetting layout options (Layout)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/requirements/posix.txt
external-deps/spyder-kernels/requirements/windows.txt
external-deps/spyder-kernels/spyder_kernels/console/outstream.py

Depends on https://github.com/spyder-ide/spyder-kernels/pull/496
Fixes #22181 

PR: Filter unnecessary stream messages in the kernel (IPython console)

---

spyder/api/plugins/new_api.py
spyder/app/mainwindow.py
spyder/plugins/layout/plugin.py

- This solves the problem reported in https://github.com/spyder-ide/spyder/issues/22189#issuecomment-2248644546.
- It seems this is broken since Spyder 5.0a3 but it only affects Mac users and no one had reported it in all this time. That's why it slipped under our radar.
Fixes #

PR: Disable shortcuts for actions in the `View > Panes` menu when not visible (Layout)

---

spyder/plugins/variableexplorer/widgets/arrayeditor.py
spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/plugins/variableexplorer/widgets/preferences.py
spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py
spyder/plugins/variableexplorer/widgets/tests/test_preferences.py

This PR adds a new menu item `Display options ...` to the options menu of the array and dataframe editors. Clicking this menu item brings up a dialog window where the user can set float format, whether to use a background color and what coloring algorithm to use (the last option only appears for dataframe editors). The new menu item replaces the existing icons and menu items for setting these options.
The reason for this PR is that it is not clear what these options do and having a separate dialog window allows us to add more context. See issue #21824 for some discussion. I replaced the text `Additional preferences` for the menu item, which was suggested in that issue, because I thought we should remove the word "additional" as it is not clear in addition to what these preferences are. …

PR: New menu item for view options in array and dataframe editors

---

spyder/plugins/editor/widgets/codeeditor/lsp_mixin.py

Before:
After:
Part of #21660 

PR: Enable showing calltip widget even with signatures without parameters (Editor/Completion)

---

spyder/api/widgets/dialogs.py
spyder/config/appearance.py
spyder/config/main.py
spyder/plugins/findinfiles/widgets/main_widget.py
spyder/plugins/findinfiles/widgets/tests/test_widgets.py
spyder/plugins/remoteclient/api/__init__.py
spyder/plugins/remoteclient/api/client.py
spyder/plugins/remoteclient/plugin.py
spyder/plugins/remoteclient/widgets/connectiondialog.py
spyder/plugins/remoteclient/widgets/connectionstatus.py
spyder/plugins/remoteclient/widgets/container.py
spyder/utils/stylesheet.py
spyder/widgets/sidebardialog.py
spyder/widgets/simplecodeeditor.py

- It would be really hard for users to debug connection problems without this info. So, we want to have it easily available for them in 6.0.
Besides that, I also fixed other minor issues that were required to provide a good UI for this: 
-  Fix style of QPushButton's in all OSes. Previous fixes only worked on Linux.
- Use a uniform layout in SpyderDialogButtonBox for all OSes (otherwise buttons are placed in odd positions on Mac) and fix some style issues with it.
- Use background and text palette colors in several syntax highlighting themes. This was a major oversight in Spyder 5 that led to have different colors between the syntax highlighting and interface themes.
**Before**
**After**
Fixes #
I affirm the [Developer …

PR: Add a widget to show connection logs to `ConnectionDialog` (Remote client)

---

.github/workflows/installers-conda.yml

I believe that "Upload Assets" was skipped because "Build Subrepos" was skipped, and by default jobs require all previous jobs to "succeed", not just the immediately previous one.
Conditioning the job with `${{ ! failure() && ! cancelled() }}` resolves the issue.
Successful run: https://github.com/mrclary/spyder/actions/runs/10327346131

PR: Ensure "Update Assets" job runs when "Build Subrepos" is skipped

---

installers-conda/build_installers.py
spyder/plugins/updatemanager/scripts/install.bat
spyder/plugins/updatemanager/scripts/install.sh
spyder/plugins/updatemanager/widgets/update.py

Currently, major updates require downloading new installers and minor/micro updates use conda-lock files to update the Spyder runtime environment using `conda update`. This breaks the environment if the conda-lock file provides a minor update to Python. In order to permit Python minor updates, the runtime environment must be recreated.
This PR has the Update Manager plugin use `conda update` for micro releases of Spyder, and `conda remove` and `conda create` for minor releases of Spyder. This permits Python minor updates to be included with Spyder minor updates. This also has the advantage of removing obsolete packages from the runtime environment on minor updates.

PR: Recreate Spyder runtime environment on minor updates (Installers)

---

spyder/plugins/ipythonconsole/utils/kernelspec.py

`micromamba` does not recognize the redirection flag `--live-stream` (`--no-capture-output`). However, its equivalent flag is `--attach ""`
Fixes #22240

PR: Fix redirection flag for micromamba (IPython console)

---

spyder/api/widgets/dialogs.py
spyder/plugins/tours/widgets.py

That style was incorrect due to several changes to dialogs in the Spyder 6 cycle.
Before
After
Fixes #

PR: Fix buttons style of the start tour dialog (Tours)

---

.github/scripts/install.sh
spyder/api/shellconnect/status.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/completion/api.py
spyder/plugins/completion/plugin.py
spyder/plugins/completion/providers/languageserver/provider.py
spyder/plugins/editor/widgets/codeeditor/tests/test_introspection.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/status.py
spyder/plugins/maininterpreter/container.py
spyder/plugins/maininterpreter/plugin.py

- Given that now users will be able to work on multiple Pyenv/Conda envs at the same time, this will (most probably) be the expected UX for completions in the Editor: that they follow those of the the current console env.
- Expose `sig_interpreter_changed` as a plugin signal for Main interpreter (before it was at the container level but used by other plugins).
- This completes the work started in PR #22350.
Fixes #

PR: Sync the IPython console current env with the one used in the Editor for completions

---

spyder/plugins/remoteclient/api/client.py
spyder/plugins/remoteclient/api/jupyterhub/__init__.py
spyder/plugins/remoteclient/utils/installation.py

Fix some incompatibilities between Spyder and `spyder-remote-services` due to some changes in the latter in preparation for the final release.
Fixes #22363.

PR: Update `spyder-remote-services` installation script (Remote client)

---

spyder/plugins/ipythonconsole/utils/kernelspec.py

- This was a regression introduced by #22360.
- I noticed this because I have a very old Conda in one of my VMs
Fixes #

PR: Fix starting kernels for old Conda versions (IPython console)

---

changelogs/Spyder-6.md
spyder/api/_version.py
spyder/api/plugin_registration/registry.py
spyder/api/plugins/__init__.py
spyder/api/plugins/_old_api.py
spyder/api/plugins/new_api.py
spyder/app/mainwindow.py
spyder/plugins/preferences/plugin.py

- Since the migration to the new API is now complete, there are no internal plugins that rely on those classes anymore. So it's better not to support them for Spyder 6 (otherwise we wouldn't notice when we break them).
- Also, bump API version to `1.0.0` to try to keep it stable.
Fixes #

PR: Don't expose `SpyderPlugin` and `SpyderPluginWidget` as part of the public API

---

spyder/api/fonts.py
spyder/api/shortcuts.py
spyder/plugins/application/plugin.py
spyder/plugins/application/widgets/status.py
spyder/plugins/remoteclient/widgets/connectiondialog.py

- Show in-app appeal dialog the fifth time Spyder starts. We discussed about that with the UX team and think it's a good idea. After that, we'll only show the status bar widget.
- Hide config file connection method in `ConnectionDialog` of the Remote client. That's necessary because it's not implemented yet.
- Improve a couple of module docstrings in our API.
Fixes #

PR: Some last minute fixes before releasing Spyder 6

---

spyder/utils/programs.py

Fix issue where single-instance was not enforced due to incorrectly not identifying a Spyder process.

PR: Fix issue where single-instance mode was not enforced (Installers)

---

spyder/plugins/editor/widgets/main_widget.py

It seems in some Linux distros the `Edit` menu is tried to be rendered at startup, which was giving this problem. 
Fixes #22432

PR: Fix bug when calling `update_edit_menu` at startup (Editor)

---

spyder/config/main.py

- That magic was disabled for Windows and users that rely on it noticed it after Spyder 6.0 was released.
- This was a regression introduced in PR #21320.
Fixes #22433

PR: Enable `autoreload` magic on all operating systems (Config)

---

spyder/__init__.py

In our new backporting workflow, `master` doesn't really point to version `7.0` but to `6.1` instead.
Fixes #

PR: Update dev version to correctly reflect what `master` is pointing at

---

spyder/app/mainwindow.py
spyder/plugins/application/plugin.py

- Don't show message on every startup after the fifth one.
- Show it 20 secs after Spyder starts on Mac so it appears in front of the main window.
- Show it also the 25th time Spyder starts.
Fixes #22457.
Fixes #22454.

PR: Fix issues showing the in-app appeal message

---

spyder/plugins/layout/api.py

- This is necessary to apply the layout as expected, i.e. that all plugins are shown in their expected positions.
- It also avoids an error that leaves the main window in an inconsistent state.
Fixes #22494

PR: Reset `undocked before hiding` state of all plugins before applying layout

---

Announcements.md
CONTRIBUTING.md
MAINTENANCE.md
RELEASE.md

This not only simplifies our workflow by avoiding the need to manually forward-port PRs from the stable branch to master. It'll also help us to maintain a more stable branch, by only backporting what we think is really necessary. 
Fixes #

PR: Update contributing, release and maintenance instructions for backporting

---

.github/scripts/installer_test.sh
.github/workflows/installers-conda.yml
installers-conda/build_installers.py

Release of 6.0.0 revealed an issue where the conda solver would take `6.0.0rc2` as satisfying the specification `6.0.0`. I did not realize that `6.0.0` lacked the specificity required to distinguish it from `6.0.0rc2`, but not the other way around.
By setting the `conda-forge` channel first, it will take priority over `label/spyder_dev` and take the `6.0.0` package first. On developer and release candidate builds, the version specificity, e.g. `6.0.1.dev0` or `6.0.1rc1`, will ensure that stable versions are overlooked in the higher priority `conda-forge` channel and the specified version will be obtained from the appropriate channel.
Fixes #22416

PR: Prioritize conda-forge channel so that stable releases are pulled above unstable ones (Installers)

---

spyder/plugins/ipythonconsole/widgets/shell.py

This happened when the kernel was not available and users opened/closed projects or used the Python path manager.
Fixes #21563.

PR: Prevent error when updating `sys.path` in consoles (IPython console)

---

spyder/config/base.py
spyder/plugins/ipythonconsole/comms/kernelcomm.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/ipythonconsole/widgets/status.py

- The previous approach didn't work all the time because when the first prompt is shown, the kernel comm is not necessarily connected (and we need that to get the banner info).
- Also add some logging messages to better understand how actions are performed in the console.
Fixes #22440.

PR: Show banner when the kernel is ready (IPython console) 

---

spyder/app/find_plugins.py

- Before we were loading external plugins in a try/except that caught only a handful of errors.
- Now we catch any exception, which is more robust.
I think this is important after seeing what was reported on issue #22419.

PR: Avoid crashes at startup due to faulty/outdated external plugins

---

spyder/plugins/layout/plugin.py

- This is necessary to avoid breaking mouse clicks the next time Spyder starts on WSL.
Fixes #20851.

PR: Prevent storing a negative position when saving the main window settings (Layout)

---

.github/workflows/test-files.yml
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-win.yml

- Micromamba 2.0 was released a few hours ago and it's causing hangs when running our test suite on CIs (it seems it can't solve our env file).
- The fix is to pin its version to the last stable one before 2.0 (i.e. 1.5.10).
Fixes #

PR: Pin micromamba to the last version before 2.0 to prevent hangs (CI)

---

spyder/plugins/ipythonconsole/widgets/shell.py

That will make the banner available to other QtConsole methods, e.g. resets.
Fixes #22593.

PR: Set shell banner attribute to be the one computed by us (IPython console)

---

spyder/plugins/editor/widgets/codeeditor/tests/test_autoindent.py

Checking PR #22480 I was able to confirm that the test `spyder\plugins\editor\widgets\codeeditor\tests\test_autoindent.py::test_copy_paste_autoindent` had an error and it was being able to pass by forcing some text to be over the clipboard. The need to use the clipboard directly was due to an incorrect position definition (59 instead of 51) to select text. Also, this position definition was causing a warning (`QtWarningMsg: QTextCursor::setPosition: Position '59' out of range`) since the text used over the test doesn't have such position. This warning can be seen in the PR #22480 failed test `Captured Qt messages` section: https://github.com/spyder-ide/spyder/actions/runs/10797623921/job/30226163168?pr=22480#step:14:6338
I …

PR: Fix `test_copy_paste_autoindent` forcing text over the clipboard to work (Editor)

---

spyder/plugins/ipythonconsole/widgets/client.py

That warning happens during env activation and prevents the console from starting. But it's not an error that doesn't allow the kernel to work.
Fixes #22551

PR: Add harmless OpenCL warning to bening errors (IPython console)

---

MAINTENANCE.md

- `git cherry-pick` was missing an option without which it was not working.
- Simplify name of branches created when doing manual backports.

PR: Some small fixes to the Maintenance instructions

---

spyder/plugins/updatemanager/widgets/update.py

Check that `sys.executable` is not in `/usr/bin` or `/usr/local/bin`
Fixes #22407

PR: Do not check for updates if Spyder is in a system or managed environment

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/console/shell.py

- This can be necessary when there's a mismatch between the installed versions of IPython, matplotlib and matplotlib-inline.
- I don't know how to add a test for this, but I can confirm it solves the problem for me locally.
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/517
Fixes #22420 

PR: Manually register the Matplotlib inline backend in case it hasn't

---

.github/workflows/purge-cache.yml

Use `gh cache` instead of `gh actions-cache`.
`gh actions-cache` can only delete caches by key and some caches have spaces in the key name, resulting in errors.
`gh cache delete` has an `--all` option and no need to explicitly list all caches.

PR: Fix issue where cache keys with spaces are not removed (CI)

---

scripts/spyder

Don't use hard-coded path to python in shebang.
This allows spyder to work in other environments which have python installed in a different directory.
I certify the above statement is true and correct: Flamefire

PR: Don't use hard-coded path to Python in script shebang used to launch Spyder

---

spyder/plugins/updatemanager/tests/test_update_manager.py
spyder/plugins/updatemanager/widgets/update.py
spyder/plugins/updatemanager/workers.py

* Check that the download asset is available before alerting the user to an available update. If the asset is not available, also check the next-latest release, and so on, until either no update or no asset is available.
* Use osascript in order not to pollute shell history on macOS.
* Ensure `UpdateWorker.channel` is assigned.
Fixes #22566
Fixes #22572

PR: Check for asset availability when checking for updates

---

bootstrap.py
spyder/plugins/application/container.py
spyder/plugins/application/plugin.py
spyder/plugins/application/widgets/status.py

- This will help users to find where to donate to the project in our interface in case they miss the heart hint we show in the status bar.
- Also, don't install `spyder-remote-services` when running Spyder from `bootstrap.py` because it's not necessary.
Fixes #

PR: Add `Help Spyder` entry to the Help menu (Application)

---

spyder/utils/workers.py

- It seems the previous approach (using the Windows code page) was necessary to have compatibility with Python 2.
- That was affecting opening project files in our switcher with the help of `fzf`.
Fixes #22546.

PR: Always use `utf-8` when handling QByteArray data in `ProcessWorker` (Utils)

---

external-deps/qtconsole/.gitrepo
external-deps/qtconsole/qtconsole/ansi_code_processor.py
external-deps/qtconsole/qtconsole/console_widget.py
external-deps/qtconsole/qtconsole/tests/test_ansi_code_processor.py

QtConsole subrepo update to have jupyter/qtconsole#616 fixes
Fixes #6172

PR: Update QtConsole subrepo to take into account changes to support cursor move actions

---

spyder/api/_version.py
spyder/api/widgets/toolbars.py
spyder/config/main.py
spyder/plugins/debugger/plugin.py
spyder/plugins/debugger/widgets/main_widget.py
spyder/plugins/run/plugin.py
spyder/plugins/toolbar/api.py
spyder/plugins/toolbar/container.py
spyder/plugins/toolbar/plugin.py
spyder/plugins/toolbar/tests/__init__.py
spyder/plugins/toolbar/tests/test_toolbar.py

- That's necessary because many people are accustomed to the Spyder 5 workflow, where they could control the debugger and see the Variable Explorer and IPython console at the same time.
- Those buttons will be placed next to the current ones in the Debug toolbar, but they'll be shown only if there's an active debugging session in the current console.
- Changes to the Toolbar plugin:
* Declare a default order for toolbars.
* If a toolbar is added or removed, toolbars will be reordered with the default order and the Working Directory will be placed to the right of all others. That's because it's not easy to visually see where that toolbar ends, so it's better to not place other toolbars to its right.
* Fix loading last visible toolbars.
* Rename/improve a couple of methods for clarity.
- …

PR: Restore buttons that control the debugger to the main toolbar

---

spyder/plugins/explorer/widgets/explorer.py

- That was preventing other errors generated there to be raised.
- Also, replace old EnvironmentError by OSError and make some code style improvements.
Fixes #22732

PR: Remove unnecessary `return` in a `try/finally` statement (Files)

---

spyder/plugins/ipythonconsole/utils/client.py

Split ssh address into host and port provided from the external kernel connections dialog to ssh tunneling handler.
Fixes #22555

PR: Provide username, host and port from hostname info in ssh tunnels

---

Announcements.md
changelogs/Spyder-6.md
scripts/org.spyder_ide.spyder.appdata.xml

PR: Update Changelog, Announcements and metadata files for 6.0.2

---

spyder/plugins/run/container.py
spyder/widgets/mixins.py

- This problem occurred, for instance, when the last file to receive focus after Spyder started was a Markdown one. And that's because those files don't have a run configuration associated to them by default.
- Also, improve a couple of block comments in `BaseEditMixin`.
Fixes #22607

PR: Fix enabled state of Run plugin actions when a file type doesn't have an associated configuration

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/tests/test_plugin.py
spyder/plugins/editor/widgets/main_widget.py

- This error happened, for instance, when renaming a Python file to a Markdown one. Since we were not checking if there's a run configuration for that file type, the new file was marked as available for running. And that led to errors when trying to run the entire file or a selection in it. 
- Add a test to prevent regressions about this in the future.
Fixes #22630.

PR: Register run metadata on renames for supported file extensions (Editor)

---

.github/workflows/installers-conda.yml
.github/workflows/test-mac.yml
spyder/utils/tests/test_programs.py

See https://github.com/actions/runner-images/issues/10721

PR: Update workflows to accommodate GitHub deprecation of macos-12 runners (CI)

---

spyder/plugins/editor/widgets/base.py

QMouseEvent needs QPointF, not QPoint
* X[ ] Wrote at least one-line docstrings (for any new functions)
double click paste now works with PYQT5 and PYQT6
Fixes #22830
fxjaeckel

PR: Fix error with PyQt6 when pasting code with middle-click on Linux

---

spyder/plugins/pythonpath/tests/test_utils.py
spyder/plugins/pythonpath/utils.py
spyder/plugins/pythonpath/widgets/pathmanager.py

Fix issue where `user_widget` was not defined if `self.user_header` was defined but not visible in the PYTHONPATH Manager widget.
Reject PYTHONPATH paths that match conda base environment `/pkgs` directory.
Fixes #22827

PR: Fix `UnboundLocalError` when removing and adding paths to Pythonpath Manager

---

.github/workflows/build-subrepos.yml
.github/workflows/installers-conda.yml
.github/workflows/purge-cache.yml

This PR changes the schedule and context in which the installer workflow is run.
* The schedule is changed to run weekly on Sunday at 6:30 UTC instead of daily.
* The scheduled workflow will also create installers from both the master and 6.x branches.
* `workflow_dispatch` and `release` triggers will remain unchanged, i.e. they will only create installers for the currently selected branch or ref.

PR: Run installer build workflow on both master and 6.x weekly (CI)

---

.github/workflows/installers-conda.yml
.github/workflows/test-files.yml
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-remoteclient.yml
.github/workflows/test-win.yml
installers-conda/resources/post-install.bat
installers-conda/resources/post-install.sh
installers-conda/resources/pre-install.bat

Installing Spyder using our conda-based installers from the command-line will now recognize two environment variables: `CI` or `INSTALLER_UNATTENDED`. If either are set to 1, Spyder will not be launched upon completing the installation.
macOS `.pkg` installers do not receive command-line environment variables, so `CI` and `INSTALLER_UNATTENDED` will not have any affect. However, `COMMAND_LINE_INSTALL` is unique to macOS `.pkg` installers and set when launched from the command-line, so this variable is leveraged to refrain from launching Spyder in this circumstance.
Note that for the next `constructor` release (>3.9.3, see conda/constructor#885), `INSTALLER_UNATTENDED` is automatically set to 1 if `.sh` or `.exe` installers are run in batch mode (`-b` for `.sh` installers) or silent mode …

PR: Do not launch Spyder if installing in CI or batch/silent mode (Installers)

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/base.py
spyder/plugins/editor/widgets/editorstack/editorstack.py
spyder/plugins/editor/widgets/main_widget.py

- Don't advance line for multi-line selections when running them. That keeps the current selection in the editor, which users prefer.
- Don't save files when running cells and selections. This was the behavior in Spyder 5 and it seems users prefer it (e.g. see https://github.com/spyder-ide/spyder/issues/22637#issuecomment-2399707635).
- Remove extra end-of-line when getting selections. That introduced two extra blank lines in the IPython console when running multi-line selections, which was distracting.
- Fix running code up to the current line. Before we were not selecting that line, which was confusing if there are several blank lines before it.
Fixes #22060 …

PR: Fix several issues when getting selections to run them (Editor)

---

spyder/plugins/ipythonconsole/widgets/shell.py

It seems this error happens when the kernel crashes after it starts.
Fixes #22929

PR: Catch error when trying to compute the console banner (IPython console)

---

spyder/plugins/editor/widgets/editorstack/editorstack.py
spyder/plugins/editor/widgets/main_widget.py

This fixes the "Open last closed" shortcut in the editor, which stopped working in Spyder 6. 
<s>The proper way to implement this is perhaps via a signal instead of using get_main_widget(). However, I intend to replace this code in Spyder 6.1 as part of the fix for issue #22354, which will move all the shortcuts and actions for New/Open/Close/Save from the Editor plugin to the Application plugin, so that other plugins can also open and edit files. A minimal change seems better in this case.</s>
Fixes #22912
I …

PR: Activate `Open last closed` shortcut in `EditorStack` (Editor)

---

CONTRIBUTING.md
changelogs/Spyder-6.md
spyder/api/_version.py
spyder/api/widgets/comboboxes.py
spyder/api/widgets/menus.py
spyder/app/utils.py
spyder/plugins/appearance/confpage.py
spyder/widgets/config.py

- This fixes a regression with respect to the same functionality in Spyder 5, introduced by #21555.
- Show a preview of the interface font that is updated automatically when users browse among the available fonts in the system (the last part is important in case users have too many fonts installed). I decided to follow @dalthviz's excellent suggestion in https://github.com/spyder-ide/spyder/pull/21555#issuecomment-1830934497 about it.
- Prevent font names to be elided in the combobox dropdown.
- Automatically update the color scheme and monospace font shown in the editor preview widget when browsing them. This is to have feature parity with the new interface font preview.
- Document API changes in our Changelog and add missing ones for 6.0.2
**New interface font preview**
**Editor preview …

PR: Improve the way users can select the interface font in Preferences (Appearance)

---

.github/scripts/install.sh
spyder/app/tests/test_mainwindow.py

- After the release of Jedi 0.19.2 some days ago, `test_update_outline` (which only runs on Linux) started to fail frequently. But I tested it locally and it works fine.
- So, in order to have a stable CI for now, I prefer to pin Jedi to 0.19.1, which has been working fine for a long time.
Fixes #

PR: Pin Jedi to 0.19.1 for now on Linux (CI)

---

spyder/plugins/editor/panels/codefolding.py
spyder/plugins/editor/widgets/codeeditor/tests/test_folding.py

Edited `FoldingPanel._expand_selection`
- don't select a entire extra line with TextHelper.select_lines (eliminated `+1` from `end_line`)
- select the leftover newline using `MoveOperation.NextBlock` so blank line is not left after deleting folded portion
Fixes #23042 

PR: Fix `FoldingPanel._expand_selection` to not select text an extra line below a folded region (Editor)

---

spyder/plugins/remoteclient/__init__.py
spyder/plugins/remoteclient/api/client.py
spyder/plugins/remoteclient/api/ssh.py
spyder/plugins/remoteclient/plugin.py
spyder/plugins/remoteclient/tests/test_plugin.py
spyder/plugins/remoteclient/utils/installation.py
spyder/plugins/remoteclient/widgets/container.py

Modify server installation check and ensure server methods to check whether the spyder server version is compatible and updatable or display an error.
Show message when there's a mismatch between the Spyder and spyder-remote-services versions

PR: Check `spyder-remote-services` version compatibility (Remote client)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
external-deps/spyder-kernels/spyder_kernels/console/shell.py
external-deps/spyder-kernels/spyder_kernels/console/start.py
external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py
external-deps/spyder-kernels/spyder_kernels/customize/code_runner.py
external-deps/spyder-kernels/spyder_kernels/customize/umr.py
external-deps/spyder-kernels/spyder_kernels/utils/style.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/utils/misc.py

Enable context mode tracebacks to follow currently selected syntax style. A preview:
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/521
Fixes #22412
Fixes #1052
~Probably the logic here to set the syntax style via the import of the `VerboseTB` class and set the exception handler to `verbose` (`xmode` magic) should go over `spyder-kernels` and be added as a kernel comm handler method? What do you think @ccordoba12 ?~
Requires changes over spyder-kernels: https://github.com/spyder-ide/spyder-kernels/pull/521 …

PR: Initial traceback setup to use selected syntax style (IPython Console)

---

spyder/plugins/pylint/main_widget.py
spyder/plugins/pylint/tests/test_pylint.py

Add the `PYTHONPATH` environment from pythonpath-manager to the `pylint` plugin to access the root of the project without packages.
Example:
Suppose, you have a project with a single script (for simplicity in a spyder environment):
```
my-project
| - do_something.py
```
and you write a test:
```
my-project
| - do_something.py
| - tests
| - test_do_something.py
```
In *test_do_something.py* you access to `import do_something`. So if you start *Source -> Run code analysis* it will show the error *Unable to import 'do_something'*. But in the IPython console `!pylint tests/test_do_something.py` doesn't show this error because there is PYTHONPATH environment.
And you should take additional steps to solve this problem, for example, make a packages:
```
my-project
| - my_project
| - __init__.py …
```

PR: Pass paths from the Pythonpath manager to the Pylint plugin

---

setup.py
spyder/tests/test_dependencies_in_sync.py

This is a proposal  to allow the user to choose the Qt binding to be installed when installing with PIP.
for example using PyQt6 (or PySide6 in the future).
[Since the we could not rely on having other imports other than` stdlib `available on `setup.py` ](https://peps.python.org/pep-0517/#build-environment) when building and installing, we could not test if there is a binding already installed. For example, we could use `QtPy` to identify which one was installed, including it to `setup_requires`, and asking for `qtpy.QT_API. But, also without success. 
`
After testing some other ways to do that, I have implemented this version that checks the SPYDER_QT_BINDING environment variable to proper set the requirement during installation. 
We can use like this:
`SPYDER_QT_BINDING='pyqt6' pip …

PR: Choose Qt binding to install from `SPYDER_QT_BINDING` environment variable

---

spyder/plugins/editor/widgets/codeeditor/codeeditor.py
spyder/widgets/browser.py
spyder/widgets/mixins.py

changed instances of `sre_constants.error` to `re.error`
`re.error` has been available since 3.0.0 and is considered the public interface. `sre_constants`, `sre_compile`, and `sre_parse` are considered [depreciated as of 3.11](https://github.com/python/cpython/issues/105456). [As of 3.13](https://docs.python.org/3.13/library/re.html#re.PatternError) `re.PatternError` replaces `re.error` (which is still kept for backward compatibility).
Fixes #

PR: Fix `DeprecationWarning: module 'sre_constants' is deprecated`

---

spyder/plugins/editor/widgets/main_widget.py

Prevent actions from the Search menu (that come from the Editor) to interfere with local find/replace shortcuts from other plugins
Fixes #22453

PR: Don't register shortcuts for find/replace related actions that go in the Search menu (Editor)

---

spyder/api/shortcuts.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/codeeditor/tests/conftest.py
spyder/plugins/editor/widgets/codeeditor/tests/test_codeeditor.py
spyder/plugins/editor/widgets/editorstack/tests/test_shortcuts.py

- Shorcuts for widgets were not registered for new widget instances (e.g. new CodeEditor's) because they required a notification from `CONF`.
- This is a regression introduced by #23024, which we overlooked.
- Add a test to catch possible regressions about this.
Fixes #23151.

PR: Register shortcuts for widgets directly (API)

---

spyder/plugins/appearance/confpage.py
spyder/widgets/findreplace.py

- We were not showing the right interface font in the preview added in #22927, which was incorrect.
- Fix vertical spacing of some buttons in that page because it was too big.
- Fix horizontal and vertical spacing of find/replace widget on Mac because it was not good.
**Preferences page**
| - | - |
|![imagen](https://github.com/user-attachments/assets/f41d0a05-1e89-4cbb-a7ae-3f11d250072f) | ![imagen](https://github.com/user-attachments/assets/c1090a17-4e01-4bda-ac47-afe40fa1720d)
**Find/replace widget**
| - | - |
| ![imagen](https://github.com/user-attachments/assets/6acff2bb-e33e-4cd8-9a65-cd4288cba686) | ![imagen](https://github.com/user-attachments/assets/53151e8f-1b1d-48e0-a1f7-bcd71e6f2254)
Fixes #
By submitting this Pull Request or typing my …

PR: UI fixes for the Appearance config page and find/replace widget on Mac 

---

RELEASE.md

This describes how to update that channel with the changes in the `main` feedstock branch.

PR: Add release instructions on how to update the Conda-forge `rc` feedstock channel (Installers)

---

setup.py
spyder/tests/test_dependencies_in_sync.py

- A new version of that package was released yesterday which broke compatibility with Python 3.8, even when the other PyQt5 packages still support it.
- Without this constraint Spyder fails to be installed in that Python version.
- This commit was already included in #23201 for the `6.x` branch, but we also need to have it in master until we drop support for that Python version.
Fixes #

PR: Add constraint for `pyqt5-sip` on Python 3.8 (Dependencies)

---

spyder/plugins/run/container.py

That action was enabled for files without a run configuration, which was giving the same error as the one reported on issue #22607 when clicking on it.
Part of #22607.

PR: Enable/disable the `Configuration per file` action according to the current file run configuration (Run)

---

spyder/plugins/console/widgets/main_widget.py
spyder/plugins/console/widgets/shell.py

- Restore parent for `InternalShell`. This sets the right parent and style for the completion widget in the console (regression introduced in #17657).
- Fix saving command history, which was not working due to the incorrect initialization of some mixins (regression introduced in #23024).
Fixes #23196.

PR: A couple of fixes for the Internal console

---

spyder/plugins/variableexplorer/widgets/dataframeeditor.py

- This error was due to a comparison for the item's value that was not specific enough.
- It started to appear with Numpy 2.2.0 (released yesterday), which raises a `ValueError` for comparisons with empty arrays.
Fixes #

PR: Fix error when inserting items in DataFrameEditor (Variable Explorer)

---

spyder/plugins/ipythonconsole/__init__.py
spyder/plugins/ipythonconsole/utils/client.py
spyder/plugins/ipythonconsole/utils/kernel_handler.py

- Use `SpyderKernelError` for errors whose cause we are certain of. That displays just the error message, nicely formatted in the console, instead of a long traceback.
- Improve `SpyderKernelError` docstring to describe its proper usage.
Message when `jupyter_runtime_dir()` is not writable
| - | - |
| ![imagen](https://github.com/user-attachments/assets/91ac4509-d45b-4074-9b43-d803a3c5e9e6) | ![imagen](https://github.com/user-attachments/assets/3a6bc45b-16ef-4a5b-a5e4-364babf94842) |
Fixes #23124  …

PR: Improve displaying several kernel error messages (IPython console)

---

.github/workflows/build-subrepos.yml

Building a subrepo conda package will fail if `python_min` is not defined either as an environment variable or in `meta.yaml`, e.g. `qtconsole` (see conda-forge/qtconsole-feedstock#61).

PR: Set python_min environment variable for subrepo conda package builds

---

.github/workflows/build-subrepos.yml

The called reusable workflow requires specifying the git ref.
Merge after #23254.

PR: Fix invalid workflow issue with `purge_cache.yml`

---

spyder/plugins/debugger/widgets/main_widget.py

while debugging, clicking run (step in/out, etc) causes the debug actions on the toolbar to briefly hide until the current line has completed. This looks visually glitchy, and can cause mis-clicks. Instead continue to show the buttons if currently executing.
Fixes #23208

PR: Don't hide control debugger buttons from main toolbar while executing

---

spyder/plugins/ipythonconsole/widgets/control.py
spyder/widgets/mixins.py

- This fix was suggested by a user in #23313 but only for the editor. I decided to apply to `BaseEditMixin` so it also takes effect in the IPython console and other areas where users can edit text.
- Fix some block comments so they appear better in the Outline pane.
Fixes #23313

PR: Prevent Chinese input method to block edit input area

---

spyder/plugins/editor/widgets/base.py
spyder/plugins/editor/widgets/codeeditor/codeeditor.py

codeeditor.CodeEditor calls name mangled private function of parent class. That function should instead be made public if it needs to be called from the child.

PR: Make `TextEditBaseWidget.__move_line_or_selection` public

---

spyder/plugins/ipythonconsole/utils/kernelspec.py

- Due to this error we were not activating kernels correctly on Windows.
- This error was reported in https://github.com/spyder-ide/spyder/issues/22614#issuecomment-2542820448.
Part of #22614 

PR: Fix detecting Micromamba on Windows for kernel activation (IPython console)

---

.github/scripts/install.sh

Resubmitting #23366 but now based against master.
There is another occurrence in the same script:
https://github.com/spyder-ide/spyder/blob/5d3c74cc5a588ff875b685ac3fa4c231feeb36be/.github/scripts/install.sh#L56
which could be handled similarly; I could add this to the patch if you'd like.
There are also two occurrences of this pattern in `spyder-unittest` and `spyder-line-profiler` in `.github/workflows/run-tests.yml` which could have the `-e` removed. …

PR: Don't install `spyder-boilerplate` testing plugin in editable mode (CI)

---

spyder/widgets/findreplace.py
spyder/widgets/tabs.py

Add missing `__init__()` calls detected with PySide2. I have no idea why it works with PyQt5 and PyQt6.
rear1019

PR: Add missing `__init__()` calls in a couple of places

---

spyder/utils/programs.py

`set` does not guarantee order, so could be non-deterministic. Also, it is desirable for the priority to be `extra_paths`, `conda`, `pyenv`, then system paths
Part of #23061

PR: Replace set with list when searching for installed program

---

spyder/widgets/comboboxes.py

This error might happen when Preferences is closed too quickly, so the widget which we're trying to interact with doesn't exist anymore.
Fixes #23361.

PR: Avoid error in `PathComboBox` (Widgets)

---

spyder/plugins/plots/widgets/figurebrowser.py

This fixes going to the next/previous thumbnail with the Down/Up arrow keys.
Fixes #22458.

PR: Recreate thumbnails list after dropping one in a new position (Plots)

---

spyder/plugins/editor/widgets/codeeditor/tests/test_multicursor.py

This is a small follow-up PR after #22996.
Fixes #

PR: Fix code style for some multicursor tests (Editor)

---

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
spyder/plugins/variableexplorer/widgets/objectexplorer/toggle_column_mixin.py
spyder/utils/icon_manager.py
spyder/widgets/collectionseditor.py
spyder/widgets/tests/test_collectioneditor.py

- This is necessary because in Spyder 6 is not intuitive how to do that since we use a single click to open the editor associated to the cell.
- Add a test to cover this new UX.
Fixes #22524.

PR: Display a button to select the entire row when hovering it in `CollectionsEditor` (Variable Explorer)

---

changelogs/Spyder-6.md
spyder/api/_version.py
spyder/app/cli_options.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/widgets/main_widget.py

Fixes #23130
I certify the above statement is true and correct: [Social-Mean](https://github.com/Social-Mean)

PR: Add command line option to connect to an existing kernel at startup (IPython console)

---

spyder/plugins/updatemanager/widgets/update.py
spyder/plugins/updatemanager/workers.py

Spyder catches the exception caused by certificate related errors. When this exception occurs, an informative message is displayed
Fixes #22834
@jsbautista

PR: Catch error when checking for updates (Update Manager)

---

external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml
external-deps/spyder-kernels/.github/workflows/linux-tests.yml
external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/RELEASE.md
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
external-deps/spyder-kernels/spyder_kernels/console/shell.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

- We don't need to show those frames to users because they contain no relevant info that they need to look at.
- This is more necessary now that we use  verbose tracebacks because those frames make them much longer.
- Add test that checks the new behavior.
- This also fixes showing tracebacks in Python 3.8, which was broken in #22965.
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/526
**Before**
**After**
Fixes #23484 

PR: Filter frames that come from Spyder-kernels in tracebacks and fix tracebacks in Python 3.8 (IPython console)

---

binder/environment.yml
requirements/main.yml
setup.py
spyder/dependencies.py
spyder/plugins/ipythonconsole/widgets/debugging.py

The IPython Pygments lexers are moving to a separate package (https://github.com/ipython/ipython/issues/14520). Importing the IPython classes from `IPython.lib.lexers` will still work for a while, but importing the incidental things which that module imported from pygments won't, so I've switched those imports to point to pygments.
I certify the above statement is true and correct: @takluyver

PR: Add `ipython_pygments_lexers` as a new dependency

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/main_widget.py

This is necessary especially for `test_dedicated_consoles`, which started to fail constantly on Linux without an apparent reason.
Fixes #

PR: Improve reliability of some tests and fix teardown error for another one

---

spyder/plugins/ipythonconsole/widgets/main_widget.py

Check that the client was created, otherwise it will not be possible to rename
Fixes #21884 
@jsbautista

PR: Fix error when executing in a dedicated console and the interpreter doesn't have spyder-kernels installed or its right version

---

spyder/config/main.py
spyder/plugins/debugger/plugin.py
spyder/plugins/debugger/widgets/main_widget.py
spyder/plugins/shortcuts/tests/test_shortcuts.py

- This is necessary since now that those shortcuts are global (i.e. not prefixed by "debugger"), it was difficult to understand what a shortcut about "next" or "continue" referred to in Preferences.
- Also, make shortcut to debug a file global because that's how things worked in Spyder 5 and fix a test related to filtering shortcuts with the word "debug".
Follow-up of PR #23452.

PR: Give more descriptive names to the shortcuts that control the Debugger

---

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py

Improve note error and add except ModuleNotFoundError in Variable Explorer
Part of #22784 
@jsbautista

PR: Improve message when a variable can't be viewed due to a missing module (Variable Explorer)

---

spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/projects/plugin.py
spyder/plugins/projects/widgets/main_widget.py

Fixes #23497 
I certify the above statement is true and correct: @Social-Mean

PR: Fix `--connect-to-kernel` cli option when a project is loaded at startup

---

spyder/config/manager.py

This is most likely to occur on Linux or WSL when not using KDE or Gnome as desktop environments.
Fixes #22623 

PR: Catch error when there's no keyring backend available (Config)

---

spyder/app/tests/conftest.py
spyder/app/tests/test_mainwindow.py
spyder/config/main.py
spyder/plugins/externalterminal/plugin.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/run/container.py
spyder/plugins/run/widgets.py

- Before it was not possible to use a custom run config for the debugger unless it was selected as executor in the `Configuration per file` dialog. Now, we save the last run config per executor and use it for the one users choose in the main toolbar or menus. This way, each executor will use its own config regardless of what's selected in that dialog.
- This also declares a default executor for Python-like files to use it for the Run file, cell and selection actions regardless of the one selected in `Configuration per file`. That was a serious UX bug because if users had selected the Debugger in `Configuration per file`, then the Run actions were tied to that plugin instead of simply running the file (as in Spyder 5).
- Add a new action to the Run menu to run a Python file in an external …

PR: Fix setting custom run configurations for multiple executors (Run)

---

spyder/plugins/appearance/confpage.py
spyder/plugins/appearance/widgets.py

PR: Improve functionality for color scheme Cancel button (Preferences)

---

.github/workflows/test-files.yml
.github/workflows/test-linux.yml
external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py

- This error happened because we were not processing Pdb commands present in the debugger's command queue as expected (a command was added to it in Python 3.12.5, specifically in PR https://github.com/python/cpython/pull/120928).
- Use Python 3.12 on Linux CI's to verify that the bug was correctly fixed in our fast tests (some of the slow ones are failing but not due to this, so I skipped them for now).
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/530
Fixes #22500
I certify the above statement is …

PR: Fix error in debugger with Python 3.12.5+ 

---

spyder/plugins/updatemanager/widgets/update.py

zsh does not have the `history` option, but `unset HISTFILE` achieves the same result as `set +o history` in bash but works for both zsh and bash.
Fixes #23650
1. Installed Spyder 6.0.2 using the package installer
3. Changed my default shell to `zsh`
```
> chsh -s /bin/zsh
```
2. Attempted to update to 6.0.3 and reproduced #23650
4. Modified `~/Library/spyder-6/envs/spyder-runtime/lib/python3.11/site-packages/spyder/plugins/updatemanager/widgets/update.py` to match this PR.
5. Re-attempted update to 6.0.3 and was successfull.
6. Verified that update/install commands were not saved to history.

PR: Disable shell history for both zsh and bash when installing update for macOS (Installers)

---

.github/workflows/build-subrepos.yml
.github/workflows/installers-conda.yml
installers-conda/build_conda_pkgs.py

Follow-up PR for #23141 and conda-forge/spyder-feedstock#203.
This PR can be merged immediately after the next release, after conda-forge/spyder-feedstock#203 is merged.

PR: Update Spyder conda builds for PRs to accommodate split packaging (Installers)

---

spyder/plugins/preferences/widgets/configdialog.py

- This allows to import it without a running QApplication, which is necessary for testing.
- For instance, tests in https://github.com/spyder-ide/spyder-env-manager/pull/20 are failing due to that.
Fixes #23074

PR: Set icon in constructor for `ConfigDialog` (Widgets)

---

spyder/plugins/pythonpath/tests/test_utils.py
spyder/plugins/pythonpath/utils.py

PR: Prevent to add `site-packages` directories placed inside `AppData` ones to the Pythonpath manager

---

spyder/plugins/editor/widgets/editorstack/editorstack.py

Don't show Move, Undock and Close actions in new editor window
Fixes #23665 
@jsbautista

PR: Don't show move, undock and close actions in the Options menu of new editor windows

---

.github/scripts/install.sh
.github/workflows/test-linux-qt6.yml
runtests.py
setup.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/codeeditor/codeeditor.py
spyder/plugins/editor/widgets/codeeditor/tests/test_codeeditor.py
spyder/plugins/editor/widgets/codeeditor/tests/test_decorations.py
spyder/plugins/editor/widgets/codeeditor/tests/test_goto.py
spyder/plugins/editor/widgets/editorstack/tests/test_editorstack_and_outline.py
spyder/plugins/editor/widgets/editorstack/tests/test_save.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/utils/kernel_handler.py
spyder/plugins/run/tests/test_run.py
spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
spyder/tests/test_dependencies_in_sync.py

This is a draft to add PyQt6/PySide6 to the CI as suggested in PR #22620:
* The workflow file based on the existing one for Linux.
* For now the tests run on Linux only.
* Only pip-based installation is used as conda has no PyQt6 package yet.
* The tests don’t run at all with PySide6 (SEGFAULT at collection phase of pytest). I can reproduce it locally, but haven’t looked into it.
* The mostly run with PyQt6, however, there is a SEGFAULT at the end (haven’t looked into it).
Part of #20201. …

PR: Add workflow to run tests with PyQt6 (CI)

---

spyder/app/mainwindow.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/tests/test_plugin.py
spyder/plugins/editor/utils/autosave.py
spyder/plugins/editor/widgets/main_widget.py

- Before we were running that when `EditorMainWidget` was instantiated, which caused a noticeable delay at startup and the splash screen to be hidden while it was taking place.
- Also, remove unnecessary log messages when setting splash screen messages.
Fixes #

PR: Try to recover files from autosave before the main window is visible (Editor)

---

conftest.py
spyder/app/tests/test_mainwindow.py

- Address several errors at teardown introduced by the latest changes to the Run plugin.
- Make `test_update_outline` run less times if it fails. That's because it always fails during the first pass but passes without too many reruns in the next one.
- Reduce the amount of tests run the in slow slots for Mac and Linux because they're taking much more time than the fast ones.
Fixes #

PR: Fix some issues in our test suite (CI)

---

spyder/plugins/editor/widgets/codeeditor/codeeditor.py
spyder/plugins/editor/widgets/codeeditor/lsp_mixin.py

- Guides were not shown at startup for some files, when multiple files were open in the previous session, and for any cloned editor.
- I basically applied the changes related to guides in #21033 (with the proper attribution) because they contained the right fixes for those problems. And I improved them a bit by calling `update` to repaint them after they are applied.
Fixes #23297

PR: Fix indent guides at startup and for cloned editors (Editor)

---

spyder/plugins/variableexplorer/widgets/namespacebrowser.py

Catch `TypeError` errors when trying to load a } .spydata}  file and leave as message a possible reason for the error (having incompatible versions for the packages used to create and load the data/variables)
Fixes #22972

PR: Handle `TypeError` when loading a `.spydata` file (Variable Explorer)

---

spyder/plugins/variableexplorer/widgets/namespacebrowser.py

Ignore `OSError` that could be raised when trying to load data/variables from a `.spydata`  file with the Variable Explorer
Fixes #22358

PR: Ignore `OSError`  when trying to load data (Variable Explorer)

---

changelogs/Spyder-6.md
spyder/api/asyncdispatcher.py
spyder/plugins/ipythonconsole/utils/client.py
spyder/plugins/remoteclient/api/modules/base.py
spyder/plugins/remoteclient/plugin.py
spyder/plugins/remoteclient/tests/test_files.py
spyder/plugins/remoteclient/widgets/container.py

Fix typings issue with AsyncDispatcher, refactor to use as decorator and add minor improvements on logic for performace.
Allow to execute callbacks inside the main qt loops.
Non-Blocking usage (returns a concurrent Future):
```
@AsyncDispatcher()
async def my_coroutine(...):
...
future = my_coroutine(...)  # Non-blocking call
result = future.result()  # Blocking call
```
Blocking usage (returns the result):
```
@AsyncDispatcher(early_return=False)
async def my_coroutine(...):
...
result = my_coroutine(...)  # Blocking call
```
Coroutine usage (returns an awaitable Future):
```
@AsyncDispatcher(return_awaitable=True)
async def my_coroutine(...):
...
result = await my_coroutine(...)  # Wait for the result to be ready
```
Calling qt function:
```
@AsyncDispatcher()
async def …
```

PR: Use `AsyncDispatcher` as class decorator (API)

---

.github/scripts/run_tests.sh
.github/workflows/test-linux-qt6.yml
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-remoteclient.yml
.github/workflows/test-win.yml
conftest.py
spyder/app/tests/test_mainwindow.py

- That test fails frequently on the first CI run but passes on the next ones. So, I added a way to skip it for that run.
- I also increased again the number of runs required for that test to reduce the flakiness observed lately on CIs.
Fixes #

PR: Fix running `test_update_outline` on CI

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/run/container.py

- This is needed so that run actions for files in different plugins (e.g. 'Debug file') are declared correctly at startup.
- With this small change, Run can also correctly get all options declared in the `Configuration per file` dialog.
Fixes #23694

PR: Declare `File` as super context when Run plugin is created

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/workingdirectory/plugin.py

- The Run plugin is correctly connected to the signal provided by the Working directory one to receive updates about the cwd set there. But that plugin is actually not emitting that signal and instead is calling directly the methods related to the cwd for plugins that use or can set it.
- That's very convoluted and not something external plugins can work with. But we can't address it in a bugfix release, so for now I followed the same approach for Run.
- I also added a test to catch future regressions for this problem.
Fixes #23866.
and understand I am releasing the same under Spyder's …

PR: Set the current working directory used by the Run plugin directly in the Working directory plugin

---

changelogs/Spyder-6.md
spyder/app/tests/test_mainwindow.py
spyder/plugins/explorer/plugin.py
spyder/plugins/findinfiles/plugin.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/widgets/main_widget.py
spyder/plugins/workingdirectory/container.py
spyder/plugins/workingdirectory/plugin.py

* That signal was not emitted in all situations when a cwd change happened in Spyder, only when a new directory was selected in the Working directory toolbar.
* Instead, the Working directory was calling directly methods in other plugins to update their cwd. That not only worked against the way our API works (i.e. other plugins should connect to `sig_current_directory_changed` and do what they need to when it's emitted), but also prevented external plugins to react to cwd changes. So, I fixed that signal by making it work like that.
* In order to prevent a plugin to change its cwd if it requested it in the first place and after `sig_current_directory_changed` is emitted, I changed its signature to include the plugin's name. With that, the requesting plugin can avoid changing its own cwd …

PR: Fix `sig_current_directory_changed` signal of the Working directory plugin

---

spyder/plugins/plots/widgets/figurebrowser.py

This fixes a `ValueError: math domain error` reported by a user when the figure viewer had zero width.
Fixes #23677 
@jsbautista

PR: Prevent collapsing splitter widgets in the Plots plugin

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/main_widget.py

- We need to do this because on Windows because `editorstack.editor_focus_changed` is not emitted after saving the file.
- Also, skip `test_update_outline` when using pip packages because it fails too much.
Fixes #23716

PR: Update focused file for Run plugin after a `Save as` operation (Editor)

---

spyder/plugins/externalterminal/plugin.py
spyder/plugins/run/container.py

Also, fix bug in the Run plugin to select the default executor the first time a file is run
New shortcut that can be configured
Part of #23701.

PR: Allow to set keyboard shortcut for `Run in external terminal` action

---

spyder/config/main.py
spyder/plugins/projects/widgets/main_widget.py

Several users have reported that searching project files in the switcher introduces delays in the switcher or Spyder itself. So, we need to provide an option for them to disable it.
Fixes #22461

PR: Add option to disable searching files in the switcher (Projects)

---

spyder/plugins/remoteclient/utils/installation.py

- This prevents relying on the `SHELL` env var, which doesn't necessarily support the syntax we need to download the script with curl and run it.
- Also, fix small error with the script URL.
Fixes #22843.

PR: Use Bash to run the `spyder-remote-services` installation script (Remote client)

---

spyder/plugins/remoteclient/utils/installation.py

Backport PR #23968 on branch 6.x (PR: Use Bash to run the `spyder-remote-services` installation script (Remote client))

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole/utils/kernelspec.py
spyder/utils/environ.py

I propose raising the timeout to 5s for all scenarios.
This PR raises the timeout for the subprocess for getting user environment variables from 0.5s to 5s, and reduces superfulous calls to `get_user_environment_variables` by moving it to the instantiation of `SpyderKernelSpec` from `SpyderKernelSpec.env`.
I've run into a scenario where `get_user_environment_variables` can take up to ~1s or more. This triggers the timeout and renders the function useless, leaving users with incorrect environment variables sent to the console and language server.
Currently, `get_user_environment_variables` is called in `SpyderKernelSpec.env`, which is not appropriate since this is decorated with `@property`. `SpyderKernelSpec.env` can be referenced many times, resulting in superfluous exectution of …

PR: Reduce calls to get environment variables in `SpyderKernelSpec` and raise timeout threshold to do that 

---

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py

- Refer to "module" instead of "package" when a ModuleNotFoundError is raised. That's because a package is composed of set of modules, but the error is about a single module.
- Use monospace font for the module name to make it different from the rest of the message.
- Remove italics for error messages. That simplifies the UI for the text in that dialog.
- Remove a spurious dot and extra blank line at the end of messages, which are unnecessary.
| - | - |
| ![imagen](https://github.com/user-attachments/assets/0009b231-a639-49db-9184-973329180ec8) | ![imagen](https://github.com/user-attachments/assets/20da83b3-0737-4a26-b5ae-192b17992730) |
Fixes # …

PR: More improvements to the message shown when a variable can't be displayed (Variable Explorer)

---

installers-conda/build-environment.yml
installers-conda/build_installers.py
spyder/utils/conda.py

Spyder now looks for `conda` instead of `mamba` in the conda-based-app (installer) environment. `mamba` is removed from the requirements for both the build and base environment of the installer.
Fixes #23940

PR: Remove mamba from Spyder's installer build and base environment (Installers)

---

spyder/plugins/updatemanager/widgets/update.py

Fix check for updates at startup checkbox
Fixes #23953
@jsbautista

PR: Fix `Check for updates at startup` checkbox being ignored when an update is declined (Update manager)

---

external-deps/spyder-remote-services/.gitrepo
external-deps/spyder-remote-services/spyder_remote_services/services/files/base.py
external-deps/spyder-remote-services/spyder_remote_services/services/files/handlers.py
spyder/plugins/remoteclient/api/modules/file_services.py
spyder/plugins/remoteclient/tests/test_files.py

Modified `ls` method from `SpyderRemoteFileServicesAPI` to return an async generator and consume fron the stream of ls generated from the `spyder-remote-services`.
Implements the client-side update for: https://github.com/spyder-ide/spyder-remote-services/pull/12

PR: Return an iterable from `ls` method of `SpyderRemoteFileServicesAPI` (Remote client)

---

binder/environment.yml
requirements/main.yml
setup.py
spyder/dependencies.py
spyder/plugins/remoteclient/plugin.py
spyder/plugins/remoteclient/widgets/connectiondialog.py

- Fix typo in `passphrase` variable used in several places.
- Add `bcrypt` as a new dependency because it's required by `asyncssh` to decrypt the keyfile's passphrase.
- Also, set `known_hosts = None` when creating an SSH connection with `asyncssh`. That way users won't need to confirm first the remote host as known in a terminal.
Fixes #23375.

PR: Fix connecting to remote host with key file and passphrase (Remote client)

---

installers-conda/build_installers.py

The conda-based installer base environment should not change primary dependencies for a minor/micro release.
Fixes #24058

PR: Revert removing mamba from base environment specification

---

spyder/plugins/variableexplorer/widgets/dataframeeditor.py

It's hard to know why this error happens but the best we can do is to catch it and disable the associated functionality because it's an error raised by Pandas.
Fixes #24094.

PR: Catch error when computing max of columms in dataframe editor (Variable Explorer)

---

spyder/plugins/editor/widgets/main_widget.py

- Users expect selections to be preserved even when running a single line.
- I didn't consider that use case in PR #22940, but the fix was simple enough.
Fixes #24091

PR: Don't advance line when running code if there's selected text (Editor)

---

.github/workflows/installers-conda.yml
spyder/plugins/updatemanager/tests/test_update_manager.py
spyder/plugins/updatemanager/widgets/update.py
spyder/plugins/updatemanager/workers.py

In the course of testing #24072, @ccordoba12 discovered the possibility that a previously downloaded update artifact may not match the current update artifact on Github. This is the result of using the completed download artifact size as the verification tool. This works fine to verify the download immediately upon download completion or if the Github artifact does not change. However, it will be more robust to use the checksum of the artifact to both verify the completed download _and_ to verify an existing local artifact against the current Github artifact.
* The checksum digest for each asset is included in a single `Spyder-checksums.txt` asset. All 6.x release checksum assets are updated to reflect the new paradigm (unit tests will fail until this is completed).
* The …

PR: Use checksum to verify downloaded asset for updating Spyder (Update manager)

---

changelogs/Spyder-6.md
spyder/api/shellconnect/main_widget.py
spyder/api/shellconnect/mixins.py
spyder/api/widgets/main_widget.py
spyder/config/main.py
spyder/plugins/application/confpage.py
spyder/plugins/debugger/widgets/framesbrowser.py
spyder/plugins/debugger/widgets/main_widget.py
spyder/plugins/editor/confpage.py
spyder/plugins/findinfiles/widgets/main_widget.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/layout/plugin.py
spyder/plugins/plots/widgets/figurebrowser.py
spyder/plugins/plots/widgets/main_widget.py
spyder/plugins/profiler/widgets/main_widget.py
spyder/plugins/projects/plugin.py
spyder/plugins/projects/widgets/main_widget.py
spyder/plugins/pylint/main_widget.py
spyder/plugins/variableexplorer/widgets/main_widget.py
spyder/plugins/variableexplorer/widgets/namespacebrowser.py
spyder/widgets/helperwidgets.py

- This simplifies the way we were adding and handling empty message widgets to the current plugins that display them.
- By having a public API for this, it'll be possible for external plugins to make use of it too (e.g. `Spyder-env-manager`).
- An additional benefit is that it'll be possible to disable all empty messages by unchecking an option in Preferences (see below).
- Fix restoring visible plugins in the last session (I noticed that bug while working on this PR).
- With this refactoring it'll also be possible to vertically resize dockable plugins below its min size hint.
* Option to disable all empty messages
* Panes with empty messages can be resized below its min height
Fixes #21197
I affirm the [Developer Certificate …

PR: Add API to display an empty message in any dockable plugin (API)

---

changelogs/Spyder-6.md
spyder/api/plugins/new_api.py
spyder/api/widgets/menus.py
spyder/api/widgets/tests/test_menus.py
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/config/main.py
spyder/plugins/application/container.py
spyder/plugins/application/plugin.py
spyder/plugins/application/tests/conftest.py
spyder/plugins/application/tests/test_container.py
spyder/plugins/application/tests/test_plugin.py
spyder/plugins/editor/api/actions.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/completion.py
spyder/plugins/editor/widgets/editorstack/editorstack.py
spyder/plugins/editor/widgets/editorstack/tests/conftest.py
spyder/plugins/editor/widgets/editorstack/tests/test_editorstack.py
spyder/plugins/editor/widgets/editorstack/tests/test_editorstack_and_outline.py
spyder/plugins/editor/widgets/editorstack/tests/test_save.py
spyder/plugins/editor/widgets/editorstack/tests/test_shortcuts.py
spyder/plugins/editor/widgets/main_widget.py
spyder/plugins/editor/widgets/tests/test_editorsplitter.py
spyder/plugins/editor/widgets/window.py
spyder/plugins/explorer/plugin.py
spyder/plugins/projects/plugin.py
spyder/plugins/variableexplorer/plugin.py
spyder/widgets/tabs.py

In short, this PR allows plugins to hook into Spyder's new / open / save / close file operations. I have the Notebook plugin in mind for this but the functionality is more widely useful. There are only a few user-visible changes, unless the user installs a plugin that uses the new functionality. Thanks to PR #8798 for a first iteration on this idea.
Changes in more detail (there are videos at the end):
* The PR moves the actions associated to the following items in the `File` menu from the `Editor` plugin to the `Application` plugin, because the actions are no longer specific to the `Editor` plugin:
* `New file` (also a toolbar button)
* `Open` (also a toolbar button)
* `Open last closed`
* `Open recent` submenu
* `Save` (also a toolbar button)
* `Save all` (also a toolbar button)
* `Save …

PR: Allow plugins to hook into file actions (API)

---

spyder/plugins/layout/plugin.py
spyder/plugins/layout/widgets/dialog.py

- Improve style of `LayoutSettingsDialog`.
- Prevent flickering the first time Spyder starts on Windows and Mac. Although issue #15074 is closed, it's still happening in Spyder 6.
- Fix flickering on Mac at startup if the main window was maximized in the previous session.
- Fix removing custom layouts from `LayoutSettingsDialog`.
- Ask before removing a custom layout.
- Set placeholder text in `LayoutSaveDialog`.
- Fix tabifying plugins that don't set the TABIFY class constant.
* Style of `LayoutSettingsDialog`
| - | - |
| ![image](https://github.com/user-attachments/assets/4bcaef3e-0eb0-494e-8681-9c4d20cd27cc) | ![image](https://github.com/user-attachments/assets/c2831ac4-9c26-430a-9595-d18e5f4370c8) |
* Placeholder text in `LayoutSaveDialog`
| - | - …

PR: Fix several issues in the Layout plugin

---

spyder/plugins/plots/widgets/figurebrowser.py

* [N/A] Wrote at least one-line docstrings (for any new functions)
* [N/A] Added unit test(s) covering the changes (if testable)
* [N/A] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))
If one creates very large figures, `get_scaling` may result in 0, which then will give a math domain error in https://github.com/spyder-ide/spyder/blob/1baf8d1f6898e431e6ddf2a80788fedc8ec93390/spyder/plugins/plots/widgets/figurebrowser.py#L645
This fix results in get_scaling always returning at least 1. This is maybe not the best choice every time, but at least better than an error.
with respect to all commits …

PR: Avoid rounding scaling for figure browser to zero (Plots)

---

spyder/config/base.py
spyder/plugins/updatemanager/utils.py
spyder/plugins/updatemanager/widgets/status.py
spyder/plugins/updatemanager/widgets/update.py
spyder/plugins/updatemanager/workers.py

Use `spyder-updater` for minor/micro updates to Spyder's conda-based installer.
All update procedures and user interaction remains unchanged for all scenarios _except_ minor/micro updates to Spyder's conda-based installer. All major updates are still handled by Spyder, as well as all downloads. Minor/micro updates are only allowed for the conda-based installer, as before, but now `spyder-updater` is launched to provide the graphical user interface for the conda environment updates.
For minor/micro updates to Spyder:
* The user is first notified about its availability, as before. 
* However, upon affirmatively proceeding with the download (the first message window), rather than proceeding immediately downloading the Spyder lock files, Spyder will first check for and install updates to …

PR: Use `spyder-updater` to handle updates (Installers)

---

external-deps/python-lsp-server/.github/workflows/static.yml
external-deps/python-lsp-server/.gitrepo
external-deps/python-lsp-server/CHANGELOG.md
external-deps/python-lsp-server/pylsp/_utils.py
external-deps/python-lsp-server/pylsp/workspace.py
external-deps/python-lsp-server/test/plugins/test_completion.py
external-deps/python-lsp-server/test/test_utils.py
external-deps/python-lsp-server/test/test_workspace.py
external-deps/qtconsole/.github/workflows/linux-tests.yml
external-deps/qtconsole/.github/workflows/macos-tests.yml
external-deps/qtconsole/.github/workflows/windows-tests.yml
external-deps/qtconsole/.gitrepo
external-deps/qtconsole/qtconsole/jupyter_widget.py
external-deps/qtconsole/qtconsole/tests/test_inprocess_kernel.py
external-deps/qtconsole/requirements/environment.yml
external-deps/qtconsole/setup.py

Update python-lsp-server and qtconsole external-deps.
Our external-deps cache of conda packages for these repos have been behind and should have caused our weekly installers to fail. However, the weekly installers were erroneously discovering the latest releases of these packages from conda-forge rather than using the cached CI-built ones, allowing the workflow to succeed, i.e. a false-positive.
#23287 fixes this error, but then requires the external-deps specs to be updated so that the correct conda packages can be built and cached.

PR: Update `python-lsp-server` and `qtconsole` subrepos

---

spyder/plugins/editor/widgets/mouse_shortcuts.py

I missed this in my review of PR #23463.
Fixes #

PR: Remove `CONF` usage in `MouseShortcutEditor` (Editor)

---

spyder/plugins/editor/widgets/editorstack/editorstack.py
spyder/plugins/explorer/widgets/explorer.py

Also, improve a bit UI of the equivalent message in the Editor.
Reported in https://github.com/spyder-ide/spyder/issues/24205#issuecomment-2807211701

PR: Catch error when `xdg-open` is missing and show message instead (Files)

---

spyder/plugins/editor/widgets/mouse_shortcuts.py

PR: Remove CONF usage in MouseShortcutEditor (Editor)
https://github.com/spyder-ide/spyder/pull/24250#issuecomment-2817239603
Refactor setting mouse shortcuts CONF to use `SpyderConfigurationAccessor` api
Fixes #

PR: Follow-up to removing `CONF` from `mouse_shortcuts` (Editor)

---

.github/workflows/build-subrepos.yml
.github/workflows/installers-conda.yml
.github/workflows/test-files.yml
.github/workflows/test-linux-qt6.yml
.github/workflows/test-linux.yml
.github/workflows/test-mac.yml
.github/workflows/test-remoteclient.yml
.github/workflows/test-win.yml

setup-micromamba@v1 uses legacy caching that is no longer in service. Updating to setup-micromamba@v2 resolves the following warnings:
* "Failed to restore: Cache service responded with 422" 
* "This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP"
The "Cache conda" step in Linux and Windows workflows does not serve any purpose. This step remains for the macOS test workflow. Resolves:
* "Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved."
Explicitly remove the defaults channel from setup-miniconda (macOS only). Resolves:
* "The 'defaults' channel might have been added implicitly"

PR: Update workflow actions to address some warnings (CI)

---

installers-conda/build_conda_pkgs.py

Remove `24095_24156_qtwebengine_optional.patch` from patches to apply in spyder-feedstock `meta.yaml` when building Spyder conda package in our CI for >6.0.5 and <6.0.6.
This should be reverted for 6.0.6, when the patch is removed from spyder-feedstock repository.

PR: Remove qtwebengine patch from feedstock for 6.0.5+ (Installers)

---

Announcements.md
changelogs/Spyder-6.md

PR: Update Announcements and Changelog for 6.1.0a2

---

spyder/plugins/plots/widgets/figurebrowser.py

Change the logic in the Plots pane so that when a plot is added, the scrollbar at the right will scroll to the bottom if this is the first plot in the current execution OR (the scrollbar is currently at the bottom AND the last plot is selected).
Before, the scrollbar would scroll to be bottom if it is the first plot OR the scrollbar is currently at the bottom.
Fixes #21683 

PR: Do not scroll to the bottom if last plot is not selected (Plots)

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/codeeditor/tests/test_warnings.py

- I tried to fix those tests in PR #24234 but now it seems they fail sometimes and pass on other occasions. So, I think it's better to simply skip them.
- I also decided to skip `test_dedicated_consoles` on Mac because it fails frequently.
Fixes #

PR: Skip some tests about warnings on Mac because they became flaky

---

external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml
external-deps/spyder-kernels/.github/workflows/linux-tests.yml
external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/utils/nsview.py
external-deps/spyder-kernels/spyder_kernels/utils/tests/test_nsview.py

Show the contents of arrays of strings in the Variable Explorer.
This PR incorporates spyder-ide/spyder-kernels#535 and nothing more. 
Fixes #22570
Jitse Niesen

PR: Show contents of Numpy string arrays in the Variable Explorer

---

spyder/widgets/helperwidgets.py

This error happened when a resize event was triggered in panes that are not visible at startup (e.g. Find in the default layout).
Fixes #24280

PR: Fix error when resizing not visible `PaneEmptyWidget`'s

---

.github/workflows/installers-conda.yml

Remove 6.x branch from weekly scheduled installer build because the workflow on the master branch is incompatible with the installer build modules on 6.x after PR #23287.

PR: Remove 6.x branch from weekly scheduled installer build

---

spyder/plugins/updatemanager/scripts/install.bat
spyder/plugins/updatemanager/scripts/install.sh

Fix grammatical error in updater script.
Fixes #24318

PR: Fix grammatical error in updater script (Installers)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/utils/nsview.py
external-deps/spyder-kernels/spyder_kernels/utils/tests/test_nsview.py
spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
spyder/widgets/collectionseditor.py
spyder/widgets/tests/test_collectioneditor.py

This PR add supports for variables of type `frozenset` in the Variable Explorer. A `frozenset` will be treated like a `set`. The value is displayed as "frozenset({...})" and clicking on it opens a Collection Editor. Add a test for the latter.
Depends on spyder-ide/spyder-kernels#540.
Video of the new behaviour:
https://github.com/user-attachments/assets/13608bc1-5fa1-4d3c-a0b5-d960760857bf
Video of the old behaviour:
https://github.com/user-attachments/assets/f0623149-728d-49d0-bd49-dc946840d5bc
Fixes #24306
I …

PR: Treat `frozenset` as `set` in Variable Explorer

---

spyder/api/plugin_registration/_confpage.py
spyder/plugins/debugger/widgets/framesbrowser.py
spyder/plugins/shortcuts/confpage.py
spyder/plugins/shortcuts/widgets/table.py
spyder/plugins/variableexplorer/widgets/namespacebrowser.py
spyder/widgets/elementstable.py
spyder/widgets/helperwidgets.py

- The plan is to add a new table, based on `ElementsTable`, to select the default Python interpreter in a follow-up PR. And to facilitate that, in case users have many environments, we need to give them the ability to filter them.
- To check this new functionality, I added a lineedit to filter plugins in the Plugins config page.
- Improve the Shorcuts config page UI to match the new one of the Plugins page.
- Fix computing the width of widgets column and add kwarg to highlight hovered row in `ElementsTable`. These changes are necessary when the table has buttons.
- Make `FinderLineEdit`, `FinderWidget` and `CustomSortFilterProxy` more generic to be able to use them in connection to  `ElementsTable`.
* Filtering in the Plugins config page:
* UI improvements to the Shortcuts config page
| …

PR: Add ability to filter elements in `ElementsTable`

---

spyder/plugins/editor/utils/autosave.py

- We were using `EnvironmentError`, which was made equivalent to `OSError` in Python 3.
- We also need to use more fine-grained error types to catch errors such as the one reported on issue #24281.
Fixes #24281.

PR: Use modern and more fine-grained error types in autosave module (Editor)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/utils/nsview.py
external-deps/spyder-kernels/spyder_kernels/utils/tests/test_nsview.py

This PR incorporates spyder-ide/spyder-kernels#541 into Spyder so that variables of type `pathlib.Path` and variables containing `None` are displayed in the Variable Explorer. See that PR for screenshots.
Fixes #22351 
Fixes #6853 

PR: Display `pathlib.Path` variables and `None` in Variable Explorer

---

spyder/plugins/findinfiles/widgets/main_widget.py
spyder/plugins/findinfiles/widgets/results_browser.py
spyder/widgets/comboboxes.py

The Find pane width ended up being too large if the user searched for a very long string.
Fixes #24188.
@jsbautista

PR: Fix width of the Find pane when searching for long strings

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/spyder_kernels/console/shell.py
external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py

- This refers to magics like `%conda` or commands like `!pip`.
- It's been known for years that they don't work reliably when called in the IPython console. So, it's better to disable them and post a friendly message instead.
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/542.
Fixes #21894.

PR: Disable magics and commands to call Python package managers in the IPython console

---

installers-conda/build_installers.py
installers-conda/resources/post-install.sh

Rename resources->Resources in our runtime environment for macOS case-sensitive file systems.
Fixes #23415

PR: Rename resources to Resources in our runtime environment for macOS case-sensitive file systems (Installers)

---

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py

This problem happens when Spyder is using Python 3.11+ and the kernel 3.10-, or the other way around. In that case, `cloudpickle` can't deserialize the objects sent from the kernel and we need to inform users about it.
Fixes #24125.

PR: Show message when a mismatch of Python versions prevents to deserialize objects (IPython console)

---

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py

As @jitseniesen said on https://github.com/spyder-ide/spyder/issues/22411#issuecomment-2836587272 (and I agreed):
> I think it is a better user experience to suppress the traceback. It is not clear that the error in the IPython Console is related to what you are doing in the Variable Explorer.
Part of #22411.

PR: Don't display errors when calling `get_value` (IPython console)

---

spyder/plugins/ipythonconsole/utils/kernelspec.py
spyder/plugins/ipythonconsole/widgets/mixins.py

Conda 25.3.0 changed the way env activation works on Windows, which makes activating kernels fail when using cached kernels.
Fixes #24132.

PR: Don't use cached kernels on Windows with Conda 25.3.0+ (IPython console)

---

setup.py

Hi, just a tiny fix for a glitch I found while reviewing this for Debian

PR: Sanity check in `setup.py` will mistakenly let Python 2 pass

---

.github/scripts/install.sh
.github/workflows/test-win.yml

Tests on Windows are very flaky right now and the reason seems to be that we're not using cached kernels on CIs due to Conda 25.3 present.
Fixes #

PR: Fix cached kernels on Windows for CIs

---

spyder/app/__init__.py
spyder/app/restart.py
spyder/app/start.py
spyder/plugins/application/plugin.py

Spyder uses the `sys.executable` to start Spyder when a restart is enacted. For macOS shortcuts this value is resolved to the real location of the Python executable. However, when restarting Spyder the symlink executable should be used in order to retain macOS integration. i.e. macOS will still consider Spyder an application.
* The redefinition of `sys.executable` is moved to `spyder.app.__init__.py` and the original value is stored in the module constant `SHORTCUT_EXE`.
* Upon restart, the original `sys.executable` is used.

PR: Fix executable used for restarts on macOS

---

spyder/plugins/ipythonconsole/widgets/mixins.py

- This was an oversight on my side, introduced by #24389.
- It was not caught by our tests because we check a lot of Conda stuff for pip packages.
Fixes #24421.

PR: Fix hard crash when checking conda for cached kernels (IPython console)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/requirements/posix.txt
external-deps/spyder-kernels/requirements/windows.txt
external-deps/spyder-kernels/setup.py

- Versions between 5.12 and 5.14.2 have a nasty bug that prevents setting the Matplotlib inline backend formats. So, we require 5.14.3 (the latest one at the moment) in Spyder-kernels.
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/544.
Fixes #24390

PR: Require a minimal version of the `traitlets` package (IPython console)

---

spyder/plugins/application/container.py

If the dialog window is cancelled, `dialog._exec()` returns falsey, resulting in `filenames` not being defined. Removing the conditional on `dialog._exec()` allows `filenames` to be defined regardless of the exit status of the dialog. If cancelled, `dialog.selectedFiles()` returns an empty list, as expected.
Fixes #24370

PR: Fix UnboundLocalError when cancelling the open file dialog

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/requirements/posix.txt
external-deps/spyder-kernels/requirements/windows.txt
external-deps/spyder-kernels/setup.py

Backport PR #24450 on branch 6.x (PR: Require a minimal version of the `traitlets` package (IPython console))

---

spyder/plugins/explorer/widgets/remote_explorer.py

I noticed this small UI error when checking that widget to publish a tweet about it.
**Before**
**After**
Fixes #

PR: Remove unnecessary margins around `RemoteExplorer` widget (Files)

---

.github/scripts/install.sh
.github/workflows/test-linux.yml
.github/workflows/test-remoteclient.yml
README.md
setup.py
spyder/app/tests/spyder-boilerplate/setup.py
spyder/dependencies.py
spyder/plugins/editor/panels/scrollflag.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/tests/test_dependencies_in_sync.py
spyder/utils/tests/test_pyenv.py

- Python 3.8 reached end-of-life last year, so we don't need to keep supporting it anymore.
- Also, tests started to fail with Python 3.8 and there's no need to fix them.
Fixes #

PR: Increase minimal supported Python version to 3.9

---

spyder/plugins/explorer/plugin.py
spyder/plugins/ipythonconsole/widgets/client.py

Changes needed due to the fix done and released with `aiohttp` 3.12.4: https://github.com/aio-libs/aiohttp/releases/tag/v3.12.4

PR: Fix Remote client tests by passing `ClientSession` loop when closing APIs (Jupyter and Files APIs)

---

spyder/plugins/updatemanager/tests/test_update_manager.py
spyder/plugins/updatemanager/workers.py

- `test_update_non_stable` started to fail after releasing 6.1.0a3. When trying to fix it, I noticed it was not actually testing what we wanted to, so I took the opportunity to improve it a bit.
- Request the max amount of Github releases we can when checking for updates while testing to prevent that test from failing again in a long time.
Fixes #

PR: Fix an Update manager test

---

spyder/plugins/ipythonconsole/utils/kernelspec.py
spyder/utils/conda.py

Mamba 2.0 doesn't have the `--no-capture-output` option to pass the kernel's stdout/stderr to Spyder. Instead, it uses `--attach`, as Micromamba.
Fixes #24513.

PR: Fix kernel activation for Mamba 2.0+ (IPython console)

---

spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/variableexplorer/widgets/namespacebrowser.py
spyder/utils/environ.py
spyder/widgets/collectionseditor.py
spyder/widgets/tests/test_collectioneditor.py

This PR displays dictionaries in the collections editor by insertion order, instead of ordering them alphabetically by key. This reflects a change in Python 3.7, which guaranteed that the order is preserved.
Clicking on the column header now cycles through three states: sorting that column in ascending order, sorting that column in descending order, and reverting to insertion order. See the video below for a demonstration.
Collections editors showing anything but a dictionary are not changed by this PR. 
The cycling through three sorting states is implemented in the model. That is a bit of a hack, because it would be more logical to do it in the view, but it is not clear how to get this to work. In Qt 6, `QHeaderView` has a flag `sortIndicatorClearable` which implements the three-state …

PR: Sort dict in collections editor by insertion order initially

---

spyder/widgets/mixins.py

Added return statements to `BaseEditMixin.inputMethodQuery` which were previously omitted. This caused queries to not properly inform the Microsoft IME of the cursor location, leading to various special text input prompts to be mis-located.
Fixes #24561

PR: Fix input method positioning (Editor/IPython console)

---

spyder/api/shellconnect/status.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/plugins/ipythonconsole/widgets/client.py
spyder/plugins/ipythonconsole/widgets/shell.py

After requesting a console's kernel restart the related shellwidget `kernel_handler` instance changes. This change was preventing the status widget to detect the need for an update since the related update logic was connected to the initial `kernel_handler` instance.
This adds a signal to the `ShellWidget` to communicate that the kernel is ready (even if a kernel restart was requested and the `kernel_handler` instance was changed).
Fixes #24538

PR: Fix signal connection to trigger status bar update after kernel restart (IPython Console)

---

spyder/plugins/pythonpath/container.py

- This prevents a crash in `6.0.x` when users install and start `6.1.x` first and then downgrade to any of those versions. That behavior is not uncommon among users when they find something broken or that they don't like in a new version.
- I noticed this bug when trying to test something in the `6.x` branch.
Fixes #

PR: Don't remove old options when migrating to the new ones (Pythonpath manager)

---

changelogs/Spyder-6.md
spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/main_widget.py
spyder/plugins/mainmenu/api.py
spyder/plugins/pylint/plugin.py

Currently, a lot of items are crammed into the Source menu, with substantial overlap between it in the Edit menu, and to a lesser extent the Search menu. Following testing and discussion, it seems reasonable to move some sections out of the former menu where they would more convinviently fit in one of the others, and draw the boundary more clearly—namely, the Source menu is only for operations specific to (Python) source code, while operations that work on any text file belong in the Edit menu.
Therefore, we've implemented the following changes:
- Moved the Cursor section to the Search menu, since it involves navigation and applies to any file.
- Moved the Formatting section to the Edit menu as it (minus the autoformat item) applies to any file, as much or more so than the existing Editor …

PR: Split out Source menu sections to Edit and Search menus

---

spyder/plugins/remoteclient/plugin.py

Execute `load_client_from_id` outside of `asyncssh` async loop, as it freezes otherwise. Because the events creation on `asyncssh` are scheduled to be executed by SpyderRemoteAPIManagerBase init on this loop. On the future, more awaits needs to be added to release the event loop to complete or move all async function inside of `remoteclient` to a separate loop than `asyncssh`.

PR: Fix remote client connections dialog unresponsive

---

spyder/plugins/ipythonconsole/widgets/main_widget.py

get `remoteclient` options attribute from `manager`

PR: Fix getting options from manager instead of `jupyter_api` (IPython console)

---

spyder/plugins/remoteclient/api/modules/base.py
spyder/plugins/remoteclient/plugin.py

- Increased the timeout for the base jupyter server API requests
- set configuration after updating the `kernel_spec_name` for default consoles

PR: Hotfix for erros on setting and updating kernel specs (Remote client)

---

.github/workflows/installers-conda.yml
spyder/plugins/updatemanager/tests/test_update_manager.py
spyder/plugins/updatemanager/workers.py

Use GitHub's digest feature for release assets.
The checksum for a release artifact will now be available in the asset info from GitHub rest api so we no longer need a separate http request to read the checksum artifact.
We still need to generate the checksum artifact for future releases so that Spyder versions <6.1 can update. However, at some point in the future (assume Spyder 7), we can stop creating the checksum artifact.
Fixes #24531

PR: Use GitHub's digest feature for release assets (Update manager)

---

spyder/plugins/remoteclient/plugin.py

Pop the loaded remote-clients from the `_remote_clients` dict at `on_close` or `stop_remote_server`

PR: Unload remote client manager on stop or close (Remote client)

---

external-deps/spyder-kernels/.gitrepo
external-deps/spyder-kernels/SECURITY.md
external-deps/spyder-kernels/requirements/tests.txt
external-deps/spyder-kernels/setup.py
external-deps/spyder-kernels/spyder_kernels/comms/commbase.py
external-deps/spyder-kernels/spyder_kernels/console/kernel.py
external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py
external-deps/spyder-kernels/spyder_kernels/utils/nsview.py
external-deps/spyder-kernels/spyder_kernels/utils/tests/test_nsview.py
spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py
spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py

Support Polars data frames in the Variable Explorer. The user can open the Polars dataframe in Spyder, in which case the kernel converts it to a Pandas dataframe. This is so that we don't need to have `polars` installed in Spyder's runtime environment, only in the console environment. The disadvantage is firstly that the data frame can not be edited in Spyder, because converting from Polars to Pandas and then back to Polars does probably not always work. Therefore, the dataframe editor is read only. Secondly, the conversion from Polars to Pandas in the console environment only works if `pandas` and `pyarrow` are installed in the console environment. Thus, I added a new error message to handle the case where opening an editor in the Variable Explorer raises an `ModuleNotFoundError` in the …

PR: Support Polars data frames in Variable Explorer

---

installers-conda/resources/post-install.sh

Use relative path instead of calling `dirname` guards against unset variable.
Fixes #24762

PR: Fix issue `dirname: missing operand` when `PACKAGE_PATH` is not set

---

changelogs/Spyder-6.md
spyder/api/plugins/_old_api.py
spyder/api/plugins/new_api.py
spyder/api/widgets/main_widget.py
spyder/plugins/application/container.py
spyder/plugins/editor/widgets/codeeditor/tests/test_indentation.py
spyder/plugins/editor/widgets/editorstack/editorstack.py
spyder/plugins/editor/widgets/main_widget.py
spyder/plugins/editor/widgets/window.py
spyder/plugins/layout/plugin.py
spyder/plugins/mainmenu/api.py
spyder/plugins/mainmenu/plugin.py
spyder/plugins/toolbar/plugin.py

Final followup to #24673 , tweaking a few final UI text labels in the menus:
* Rename the View menu to Window in the UI, as its contents generally affect the entire window rather than the view of specific items, is in line with other applications and guidance, and befits its position to the left of Help. For backward compatibility with other plugins, we don't rename the machine-readable APIs referring to it and add explanatory text instead
* Fix #5565 , clarifying the name and description of the Fix indentation menu item to make clear what it actually does is convert tabs to spaces for indentation
* Rename "Spyder support" to "Spyder Google group" to clarify what it actually points to
| --- | --- |
| <img width="306" height="168" alt="image" …

PR: Make final clarifications to menus UI text

---

spyder/plugins/ipythonconsole/widgets/namespacebrowser.py

If the user tries to retrieve a Pandas dataframe with a numerical index, their console environment has Pandas version 1 and Spyder's runtime environment has Pandas version 2, then a ModuleNotFoundError on `pandas.core.indexes.numeric` occurs. In that case, show an error telling the user to upgrade Pandas in their console environment.
Fixes #24747 

PR: Handle Pandas version mismatch when getting dataframe with numeric index (Variable Explorer)

---

external-deps/spyder-remote-services/.gitrepo
external-deps/spyder-remote-services/spyder_remote_services/app.py
spyder/plugins/ipythonconsole/utils/websocket_client.py
spyder/plugins/remoteclient/api/modules/base.py

- Fixed websocket msg typing errors and handle receiver loop exceptions on jupyter websocket client.
- Added  `sig_ws_msg_size_overflow` signal to `SpyderWSKernelClient` that is emitted when the websocket receives a message frame bigger than the maximum specified size.
- Set maximum size for websocket messages to 100mb.

PR: Handle websocket message errors (IPython console)

---

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py

After removing a column in the dataframe editor, `max_min_col` needs to be updated because otherwise the background colors will be wrong. In some cases (if the dataframe contains both numbers and non-numbers), computing the color may even cause an exception. This PR fixes the issue.
The PR also adds a regression test, and a straightforward test that removing a column works.
Fixes #24796
Jitse Niesen

PR: Update `max_min_col` after removing column in dataframe editor (Variable Explorer)

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/debugger/widgets/main_widget.py
spyder/plugins/ipythonconsole/widgets/shell.py
spyder/plugins/ipythonconsole/widgets/status.py

- This not only simplifies the API but it's also necessary to correctly register handlers on kernel restarts.
- I found this bug while working on #24794.
- Also, move some `ShellWidget` private methods to its corresponding section.
Fixes #

PR: Add methods to (un)register call handlers to `ShellWidget` (IPython console)

---

spyder/app/start.py

Resolve issue on macOS that causes some issues with subprocesses when Spyder is started from the commandline.
Starting Spyder from the command line invokes `pypthonw` (`python.app`) which sets the environment variable `PYTHONEXECUTABLE`. This can cause problems for subsequent subprocess, but should not be needed after Spyder initially launches, so it should be safe to remove from `os.environ`.
Fixes #24743

PR: Remove `PYTHONEXECUTABLE` from `os.environ` upon launching Spyder

---

spyder/config/base.py

On windows use win32 GetUserDefaultLocaleName instead of locale.getlocale due to non-BCP47 locale code.
`locale.getdefaultlocale` is depreciated and is slated for removal in python 3.15. `locale.getlocale` as the suggested alternative does not return BCP47 locale codes (`"English_United States"` rather than `"en-US"`). Instead call the win32[`GetUserDefaultLocaleName`](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getuserdefaultlocalename) function via the `ctypes` builtin library in order to not add any dependencies.
Fixes #23318
and understand I am releasing the …

PR: Remove depreciated `locale.getdefaultlocale`

---

.github/workflows/test-mac.yml
.github/workflows/test-win.yml
spyder/app/tests/test_mainwindow.py
spyder/widgets/tests/test_sidebardialog.py

- Skip `test_connection_to_external_kernel`, `test_issue_4066` and `test_sidebardialog` on Mac because they started to timeout too much after switching to Python 3.12.
- Run `test_get_help_combo` only on Linux because it segfaults on Mac and Windows.
- Increase runs on Mac and Windows to avoid failures when tests timeout or segfault.
- This is a follow-up of #24837.
Fixes #

PR: Prevent test failures on Mac and Windows (CI)

---

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py

If an exception is raised when getting or setting variables in the IPython console from the Variable Explorer, then Spyder shows a dialog box to the user with some (hopefully) helpful and not too technical text. This PR adds a "Show details" button to the dialog box. When that button is clicked, the traceback of the exception is shown. If the exception is caused by an exception on the kernel side, then the traceback of the latter exception is also shown.
https://github.com/user-attachments/assets/c941d034-0304-425c-badb-678633bdc687
Fixes #22411
and understand I am releasing the same …

PR: Optionally show traceback on errors raised in console when getting or setting variables (Variable Explorer)

---

spyder/plugins/editor/widgets/codeeditor/codeeditor.py

Don't create a drag cursor when dragging in files to the editor window. The `CodeEditor._drag_cursor` is intended to indicate where dragged text will be pasted. Dragged files do not need a cursor as they are opened rather than pasted. Creating the drag cursor when dragging in a file causes the cursor to get stuck as there is never a subsequent `dropEvent` or `dragLeaveEvent` to remove the drag cursor from being rendered.
Fixes #24919

PR: Fix stuck drag cursor rendering (Editor)

---

spyder/widgets/sidebardialog.py

This is necessary in case users create remote connections with a name that has only numbers.
Fixes #24988.

PR: Cast page name to string when adding it to `SidebarDialog` (Widgets)

---

spyder/plugins/updatemanager/widgets/update.py
spyder/plugins/updatemanager/workers.py

* The updater's download validation now considers hexdigests that may begin with `"sha256:"`.
* Zip file artifacts are extracted during download validation.
* The progress bar is closed and threads are cleaned up when an exception occurs.
Fixes #24983

PR: Fix updater checksum comparison with `sha256` prefix

---

changelogs/Spyder-6.md
spyder/requirements.py

- Unfortunately Spyder crashes with PySide 6.9 at the moment.
- PyQt 6.9+ is the first version with which Spyder exactly looks the same as with PyQt5.
- Also, update message about a failure to import Qtpy when doing those checks.
Part of #24825.

PR: Prevent using Pyside 6.9+ and require PyQt 6.9+

---

installers-conda/resources/base_env.yml
spyder/plugins/updatemanager/tests/test_update_manager.py
spyder/plugins/updatemanager/workers.py

Minor updates should not include minor Python version updates to the installer base environment since the base environment is only rebuilt on major Spyder updates.
* Pin installer base environment Python version to 3.11.13 (partial reversion of #23285)
* Micro updates from pre-releases are elevated to minor updates in order to rebuild the runtime environment in case a minor Python update occurred.

PR: Revert Python version of installer's base environment to 3.11

---

spyder/plugins/editor/confpage.py
spyder/plugins/editor/widgets/main_widget.py

* Rewrite UI text throughout to be clearer, more concise and more polished
* Rename `Interface` tab to `Display` and `Advanced settings` tab to `Advanced`
* Split the `Display` section (of `Interface`) into more focused `Interface` and `Helpers` sections
* Split the whitespace options in the `Automatic changes` section (of `Source code`) into a more focused `Whitespace` section
* Add `Scroll past the end` to `Interface section` and remove now-empty `Other` section
* Move `Display code annotations` option from `Advanced` to `Display > Helpers`, the description to a tooltip and remove `Annotations` section
* Move `End-of-line characters` section to `Source code` and the description to a tooltip
* Remove `Warp lines` and `Show blank spaces` that duplicate more easily-accessible options in …

PR: Reorganize Editor preferences and improve UI text

---

spyder/plugins/shortcuts/confpage.py
spyder/plugins/shortcuts/widgets/table.py

* Clarify and polish the UI text throughout the preference pane and its dialogs
* Add missing description of the "Defaults" button to the keyboard shortcut editor
* Move the Clear button in the Keyboard Shortcuts editor from splitting the "Ok" and "Cancel" buttons (big no-no) to be instead next to the Defaults button that it is more similar to
| --- | --- |
| <img width="895" height="688" alt="image" src="https://github.com/user-attachments/assets/d3afbba5-f8cf-4715-8aa0-27e9123abfae" /> | <img width="884" height="695" alt="image" src="https://github.com/user-attachments/assets/ee3d927a-92fc-44ba-820e-9362eb74fa57" /> |
with …

PR: Clarify and polish UI text for keyboard shortcuts pref pane

---

.github/workflows/build-subrepos.yml
.github/workflows/installers-conda.yml
.github/workflows/test-win.yml

This avoids failures in some tests with the `windows-latest` image and potential issues with our installers.
Fixes #

PR: Use `windows-2022` image on Windows workflows (CI)

---

spyder/plugins/appearance/confpage.py
spyder/plugins/appearance/widgets.py

Presently, the Appearance preferences pane uses a mix of the newer "theme" and the older "scheme" to refer to syntax highlighting themes. This PR standardizes the UI text to consistently use "theme" throughout.
| --- | --- |
| <img width="902" height="692" alt="image" src="https://github.com/user-attachments/assets/6e11a8ef-a5fc-4034-aeb8-2dcb95797079" /> | <img width="888" height="692" alt="image" src="https://github.com/user-attachments/assets/9552c5c7-5678-4db0-8a97-803e553c92c8" /> |
| <img width="548" height="475" alt="image" src="https://github.com/user-attachments/assets/095b874a-1aa7-42dc-8d7b-7aa59e9b261c" /> | <img width="548" height="475" alt="image" src="https://github.com/user-attachments/assets/d660a290-9b1b-4b85-bf2e-bf2715217639" /> |
By submitting this …

PR: Use consistant terms for syntax highlighting theme in prefs

---

spyder/config/main.py
spyder/plugins/ipythonconsole/confpage.py

Followup to #25010 
Related to #19091
The current default value of the Console buffer size (scrollback length) under `Preferences > IPython Console > Interface` is very low at only 500 lines, barely a handful of screenfulls of text. Given in 2025 machines can easily handle, and many users expect, far more, and the default setting results in permanent data loss, it seems reasonable to increase it to at least 5000.
Meanwhile, the maximum value was apparently set to only 5000 due to #19091, where a user reported that Spyder was very slugging when the Console buffer size (scrollback length) was set to 50k lines. @ccordoba12 postulated that this could occur with a buffer size >10k lines, and although the maximum was set to half of that still.
However, the setting still allows (and even …

PR: Increase default max console buffer and warn if it's big (IPython console)

---

spyder/config/main.py
spyder/plugins/editor/confpage.py

Reworks the indentation options in the Editor preferences, which previously conflated the indentation width and the indentation character into a single setting with limited options, while splitting space width and tab width into separate settings, into two settings: indent character and indent width.
| --- | --- |
| <img width="892" height="843" alt="image" src="https://github.com/user-attachments/assets/1a6fa0cb-de92-4af6-8547-57a422579c8e" /> | <img width="893" height="890" alt="image" src="https://github.com/user-attachments/assets/d9b52821-c0ff-4301-977f-66bf8c7ddeae" /> |
with respect to all commits and content included in …

PR: Rework Editor indent prefs to separate char & width options

---

spyder/plugins/remoteclient/api/manager/base.py
spyder/plugins/remoteclient/api/manager/jupyterhub.py
spyder/plugins/remoteclient/api/manager/ssh.py
spyder/plugins/remoteclient/api/protocol.py
spyder/plugins/remoteclient/plugin.py
spyder/plugins/remoteclient/widgets/connectiondialog.py
spyder/plugins/remoteclient/widgets/connectionstatus.py
spyder/plugins/remoteclient/widgets/container.py

Added `is_connecting` property to remote client manager to check whether it's currently creating a new conenction;
Added `abort_connection` coroutine to abort current connection attempt;
Modified `create_new_connection` coroutine to allow idempotent connections creation and abortion;
Added `Connected` and `Starting` ConnectionStatus Enum for better status updates of current remote client connections stage.

PR: Allow aborting connections (Remote client)

---

spyder/plugins/application/plugin.py

- That fixes an error when showing the application context menu.
- Also, add comments about plugins that are not needed for on_plugin_available methods.
Fixes #25133.

PR: Restore Shortcuts as one of Application's optional plugins
