spyder-ide/spyder

- spyderlib/spyder.py
Redirect bug reports to the github issue tracker
> Redirect bug reports to the github issue tracker

- spyderlib/plugins/__init__.py
> Provide a base implementation for closing_plugin

- spyderlib/utils/introspection/plugin_manager.py
> Make rope the default plugin

- spyderlib/qt/QtCore.py
- spyderlib/utils/inspector/sphinxify.py
The problem is described in https://github.com/ContinuumIO/anaconda-issues/issues/272.
> Fix zlib segmentation fault in Anaconda 3.4 Linux

- spyderlib/utils/introspection/plugin_manager.py
> Fix a bug in completion if callback value is not converted to string

- spyderlib/utils/programs.py
Added support for xterm and xfce terminal to run programs on an external system terminal.
> Add support to run Python programs on xfce and xterm external terminals

- spyderlib/qt/__init__.py
> Setting Qt API n°2 for all supported objects

- spyderlib/utils/misc.py
- spyderlib/widgets/projectexplorer.py
- spyderlib/widgets/sourcecode/syntaxhighlighters.py
The notion of declarative function have been added in 0.9.6.
> Add "func" to enaml highlighter

- README.md
The rationale is based on assumption that README.md is written for GitHub users.
> README.md running from source is a killer feature

- spyderlib/utils/external/path.py
- spyderlib/utils/external/pickleshare.py
Closes #2361.
Feel free to use it for new core in Spyder, it greatly simplifies working with paths.
The documentation is here: https://pythonhosted.org/path.py/api.html
> Update Path.py to version 7.3

- spyderlib/utils/introspection/plugin_manager.py
> Avoid exception when the Editor is floating and users are trying to get completions

- spyderlib/widgets/shell.py
> Fix error when trying an empty complete in internal console

- spyderlib/dependencies.py
- spyderlib/spyder.py
Templates for issues in github had a few problems:
* The list of steps was mangled with the title and was also badly displayed is some cases
* The list of dependencies was hard to read
> Improve github issue template

- spyderlib/config.py
- spyderlib/plugins/configdialog.py
- spyderlib/spyder.py
Related to #2353 
Add option in preferences to show/hide status bar
**On**
**Off**
> Add option in preferences to show/hide status bar

- spyderlib/widgets/sourcecode/base.py
> Allow the last two lines in a file to be switched

- spyderlib/plugins/configdialog.py
- spyderlib/plugins/editor.py
- spyderlib/plugins/history.py
- spyderlib/plugins/ipythonconsole.py
Fixes #2481
The comboboxes in the interface section have been aligned as well as the spinboxes in the status section of the main config page, Editor page and Ipython page.
- Editor
- Ipython
- Add a richtext checkbox widget.
- Improve docstrings on helper methods (currently not very helpful)
> Improve appearance of options inside the preferences dialog

- setup.py
> fix misspelled extension

- spyderlib/spyder.py
> Fix default layout dockwidget on first Spyder start

- spyderlib/widgets/explorer.py
> Homogenize file explorer UI

- spyderlib/widgets/arraybuilder.py
- spyderlib/widgets/helperwidgets.py
> Import HelperToolButton from helperwidgets.py in arraybuilder

- spyderlib/workers/updates.py
> Opt out of certificate verification on check for updates

- continuous_integration/modules_test.sh
- spyderlib/utils/introspection/fallback_plugin.py
> Fix failing fallback_plugin tests and add to modules_test

- .travis.yml
- continuous_integration/build_test.sh
- continuous_integration/conda.recipe/meta.yaml
- continuous_integration/run_test.sh
- continuous_integration/travis_install.sh
Ok, let's keep going with more testing and now do this! :-)
All Spyder dependencies are available as conda packages in 3.5, so why not?
> Test Spyder with Python 3.5

- spyderlib/spyder.py
This makes Spyder (even more) beautiful, especially with the new icon theme.
> Use High dpi pixmaps

- spyderlib/widgets/findreplace.py
In findreplace, if nothing is highlighted, use word under cursor
> PR: Select the word under cursor if nothing is selected in Find/Replace

- spyderlib/utils/introspection/fallback_plugin.py
- spyderlib/utils/introspection/module_completion.py
- spyderlib/utils/introspection/rope_plugin.py
> Fix errant completions

- spyderlib/app/spyder.py
- spyderlib/dependencies.py
- spyderlib/plugins/externalconsole.py
- spyderlib/plugins/ipythonconsole.py
- spyderlib/widgets/variableexplorer/utils.py
This is to avoid people having partial installations, as in issue #3009.
> Report missing hard dependencies after startup

- .checkignore
- .coveragerc
- .gitignore
- .travis.yml
- README.md
- continuous_integration/appveyor/modules_test.bat
- continuous_integration/travis/install.sh
- runtests.py
- spyderlib/utils/fixtures.py
- spyderlib/widgets/arraybuilder.py
- spyderlib/widgets/tests/test_array_builder.py
> PR: Add pytests for array builder, code coverage and quantified code

- .travis.yml
- continuous_integration/appveyor/install.ps1
- continuous_integration/travis/install.sh
Also remove unneeded code in Travis
> Fix AppVeyor failures

- conda.recipe/meta.yaml
- continuous_integration/appveyor/modules_test.bat
- setup.py
- spyderlib/app/spyder.py
- spyderlib/plugins/configdialog.py
- spyderlib/plugins/editor.py
- spyderlib/plugins/externalconsole.py
- spyderlib/plugins/help.py
- spyderlib/plugins/workingdirectory.py
- spyderlib/widgets/browser.py
- spyderlib/widgets/editor.py
- spyderlib/widgets/ipython.py
- spyderlib/widgets/variableexplorer/namespacebrowser.py
Fixes #3073
Fixes #3145
----
TODO:
Pinging @stonebig and @Nodd about this one.
> Support PyQt 5.6

- spyderlib/config/main.py
I think this will please @SylvainCorlay :-)
> Make "Spyder 3" the default icon theme

- spyderlib/utils/introspection/plugin_client.py
- spyderlib/utils/introspection/plugin_server.py
> Fix keyboard interrupt handling in plugin_server.py

- spyderlib/plugins/editor.py
- spyderlib/plugins/explorer.py
- spyderlib/plugins/variableexplorer.py
Fixes #3186
Fixes #3187
Fixes #3188
> Fix small Explorer bugs about file operations

- spyderlib/app/spyder.py
- spyderlib/config/main.py
> Change Replace shortcut from Ctrl/Cmd+H to Ctrl/Cmd+R

- spyderlib/utils/syntaxhighlighters.py
- spyderlib/utils/tests/test_syntaxhighlighters.py
> Fix handling of unmatched end-of-HTML-comment.

- RELEASE.md
- continuous_integration/appveyor/run_test.bat
- continuous_integration/conda-recipes/spyder/meta.yaml
- continuous_integration/travis/modules_test.sh
- continuous_integration/travis/run_test.sh
- This is breaking our tests in release tags
> Testing: Don't use particular tags when installing local conda packages

- spyderlib/widgets/variableexplorer/utils.py
> Fix error when Beautiful Soup is installed incorrectly

- spyderlib/utils/help/js/fix_image_paths.js
- spyderlib/utils/help/sphinxify.py
> Fix showing images in the Help plugin for Windows

- spyderlib/utils/introspection/plugin_client.py
Fixes issue #3223 as the previous fix doesn't work
> Fix further freezes because of pyzmq

- .travis.yml
- appveyor.yml
- continuous_integration/appveyor/install.ps1
- continuous_integration/travis/install.sh
- runtests.py
- spyderlib/utils/tests/test_programs.py
- spyderlib/widgets/editor.py
- spyderlib/widgets/tests/test_editor.py
Fixes #3293: F9 does not auto advance when it's at the last line. Also add tests.
> Make 'run line' add a blank line if on last line.

- spyderlib/plugins/editor.py
- spyderlib/widgets/editor.py
> Fix dragging and dropping files to the Editor

- continuous_integration/appveyor/modules_test.bat
- continuous_integration/travis/modules_test.sh
- spyder/widgets/ipythonconsole/shell.py
* This is causing an error in Travis
* Besides, this file can't be really tested outside of our IPython console.
> Skip testing the Spyder kernel for IPython consoles

- spyder/plugins/projects.py
> Don't show a message when users press cancel in the "Open project" dialog

- spyder/utils/site/sitecustomize.py
Plotting was broken for the Python console and this fixes it in my local tests. It could also be a fix for issue #1831 (at least I don't get more hangups after pressing twice F5 with plots in a file).
@divenex, could you test this pull request and verify if that's true or not for you? Thanks ;-)
> Try to fix plotting on Windows for the Python Console

- appveyor.yml
- continuous_integration/appveyor/modules_test.bat
- spyder/utils/site/__init__.py
> Add an init file to utils/site so it can be added to our tarballs

- spyder/utils/qthelpers.py
Fixes #3484 
----
@ccordoba12 something like this?
> PR: Handle Mac menubar icon bug

- create_app.py
- spyder/utils/site/sitecustomize.py
> Update create_app.py for Spyder 3.0

- spyder/plugins/variableexplorer.py
- spyder/widgets/variableexplorer/collectionseditor.py
- spyder/widgets/variableexplorer/namespacebrowser.py
- spyder/widgets/variableexplorer/utils.py
> Truncate all values shown in the Variable Explorer

- spyder/widgets/ipythonconsole/control.py
- spyder/widgets/ipythonconsole/debugging.py
> Fix some ipdb issues

- spyder/app/mainwindow.py
- spyder/config/utils.py
- spyder/plugins/editor.py
- spyder/widgets/editor.py
Now it's possible select file extension when Save As files in Spyder Editor @goanpeca
> SOLVED Issue #3436: Default file extension should be .py 

- spyder/app/mainwindow.py
- spyder/config/utils.py
- spyder/plugins/editor.py
- spyder/widgets/editor.py
Reverts spyder-ide/spyder#3517
> Revert "PR: Default file extension should be .py "

- spyder/config/utils.py
- spyder/widgets/editor.py
Fixes #3436
Default file extension should be .py (Save_as Widget).
> PR: Fix issue #3436 

- spyder/app/mainwindow.py
- spyder/config/main.py
- spyder/plugins/projects.py
> Don't open files saved as part of a project twice at startup

- spyder/widgets/editor.py
- spyder/widgets/panels/edgeline.py
- spyder/widgets/sourcecode/codeeditor.py
Part of the decoupling of panels from code editor
Partially fixes #1778 missing add behavior in settings window
> Move edge line code out of editor to EdgeLine class

- spyder/widgets/ipythonconsole/shell.py
> PR: Added a verification for the existence of the 'text/plain' key

- spyder/widgets/ipythonconsole/shell.py
> PR: New warning message in IPython console when both pylab and sympy are enabled

- spyder/widgets/ipythonconsole/namespacebrowser.py
> Fix another error when connecting to external kernels

- spyder/widgets/fileswitcher.py
> PR: Allow underscore to be valid for Enter in File Switcher

- spyder/config/utils.py
- spyder/widgets/editor.py
This fixes my concerns with PR #3580, and also does some pep8 fixes :-)
> Some corrections after pull request #3580

- spyder/plugins/explorer.py
- spyder/plugins/projects.py
- spyder/widgets/explorer.py
- spyder/widgets/projects/explorer.py
> PR: Added management for delete operation of a project

- spyder/plugins/ipythonconsole.py
- spyder/plugins/maininterpreter.py
> PR: Fix error when trying to add a non-ascii module in Python 2 to the UMR blacklist

- spyder/widgets/ipythonconsole/shell.py
> IPython Console: Fix error when running "%reset -s"

- spyder/widgets/sourcecode/base.py
This is a minor fix after PR #3629
> Restore icons in the code completion widget

- spyder/config/base.py
I was about to disable our French translations with this code, but we could need it in the future for other languages :-)
> PR: Disable languages whose translations are outdated

- spyder/widgets/findreplace.py
> PR: Don't replace text in the find widget if there's text there

- spyder/config/base.py
> PR: Set English as default language if getdefaultlocale gives errors

- spyder/config/main.py
PR #3534 added the Solarized color schemes to master. This PR adds them to our 3.x branch and improves them a little bit.
> Backport pull request #3534 (Solarized themes)

- spyder/config/main.py
- spyder/plugins/editor.py
- spyder/widgets/editor.py
- spyder/widgets/mixins.py
- spyder/widgets/sourcecode/base.py
- spyder/widgets/sourcecode/codeeditor.py
- spyder/widgets/sourcecode/tests/test_autoindent.py
> PR: Define tabulation width in term of spaces instead of pixels

- spyder/widgets/findreplace.py
> PR: Modified behavior for the Find widget to replace contents with current selection

- spyder/app/mainwindow.py
- spyder/utils/qthelpers.py
> PR: Delete references to the 'xy' module.

- spyder/widgets/fileswitcher.py
> PR: Change file switcher entries to unicode

- spyder/config/main.py
- spyder/config/user.py
- spyder/plugins/configdialog.py
- spyder/plugins/editor.py
- spyder/widgets/editor.py
- spyder/widgets/panels/edgeline.py
- spyder/widgets/projects/config.py
- spyder/widgets/sourcecode/codeeditor.py
> PR: Multiple edge lines preferences

- spyder/app/mainwindow.py
> Add missing menus to show shortcuts for in macOS

- spyder/widgets/sourcecode/base.py
> PR: Fix "move line down" behavior in the presence of blank lines

- spyder/utils/site/sitecustomize.py
> PR: Catch UnicodeDecodeError when trying to import matplotlib in sitecustomize.py.

- circle.yml
This avoids mixing compiled dependencies from defaults and conda-forge channels
> Install ciocheck from the spyder-ide Anaconda channel

- spyder/widgets/variableexplorer/dataframeeditor.py
> PR: Add missing 'self' to DataFrameView.update_section_height

- appveyor.yml
> PR: Add code to cancel active Appveyor builds in a branch

- spyder/plugins/ipythonconsole.py
> PR:  Make Spyder not to freeze on new project creation

- spyder/utils/syntaxhighlighters.py
> PR: Add async and await as keywords for syntax highlighting

- spyder/app/mainwindow.py
- spyder/app/tour.py
> PR: Hide tour tips dialog when Spyder looses focus

- spyder/utils/help/tutorial.rst
> PR: Incorrect use of "it's" in tutorial 

- spyder/widgets/sourcecode/codeeditor.py
> PR: Remove question mark button on the 'Go to line' dialog.

- spyder/widgets/sourcecode/tests/test_autoindent.py
Closes #3700 
Closes #3473 
----
Indentation issues #3700 and #3473 are already solved (I think were solved in PR #3826) so, I just added test for this issues
> PR: Add some tests for indentation with brackets

- spyder/widgets/ipythonconsole/shell.py
- spyder/widgets/variableexplorer/namespacebrowser.py
> PR: Add validation for 'text/plain' key in all if clauses of handle_exec_method

- spyder/plugins/ipythonconsole.py
> PR: Add default value to clear_variables=False in execute code method

- spyder/plugins/editor.py
> PR: Prevent error when file with last focus is deleted from project

- spyder/plugins/editor.py
- spyder/widgets/editor.py
> PR: Allow new files to be saved before modifing them.

- spyder/widgets/sourcecode/codeeditor.py
- spyder/widgets/sourcecode/tests/test_autoindent.py
> PR: Unindent with tabs was deleting some text.

- spyder/widgets/sourcecode/codeeditor.py
> PR: Fix error when using TextSH (default highligher)

- spyder/plugins/editor.py
> PR: Remove file path from the Editor's plugin title.

- spyder/app/mainwindow.py
> PR: Fix hard crash when trying to open files in a new editor window

- spyder/plugins/externalconsole.py
> PR: Add a validation for the PyQt version used to show a message in the Python console

- .github/ISSUE_TEMPLATE.md
> PR: Add Qt and PyQt version in the report of the issue

- continuous_integration/appveyor/run_test.bat
- runtests.py
- spyder/app/mainwindow.py
- spyder/app/tests/test_mainwindow.py
This is needed now after adding tests for the main window
> PR: Correctly stop pytest's on failure

- spyder/plugins/ipythonconsole.py
- spyder/plugins/tests/test_ipythonconsole.py
> PR: Make loading IPython kernels by using their ids to work again

- spyder/plugins/findinfiles.py
- spyder/widgets/findinfiles.py
> PR: Some fixes for Find in files

- spyder/app/mainwindow.py
- spyder/config/base.py
> PR: Add an initialization value to img_path

- spyder/widgets/panels/manager.py
- spyder/workers/updates.py
Fixes errors introduced by #4155
> PR: Fix wrong usage of is_text_string

- spyder/plugins/externalconsole.py
> PR: Add a message informing the removal of the Python console

- spyder/utils/iofuncs.py
Uses the new streamlined parser from https://github.com/blink1073/oct2py/pull/108, and adds a simple test.
> PR: Update load_matlab and add test

- spyder/widgets/ipythonconsole/shell.py
> PR: Surround deprecated IPython quick_quide import by try/except block

- spyder/utils/syntaxhighlighters.py
Backport PR #4210 to the 3.x branch.
> PR: Backport PR #4210

- README.md
- circle.yml
- continuous_integration/travis/modules_test.sh
- doc/installation.rst
- spyder/app/tests/pyx_lib_import.py
- spyder/app/tests/pyx_script.pyx
- spyder/app/tests/test_mainwindow.py
- spyder/plugins/editor.py
- spyder/plugins/ipythonconsole.py
- spyder/utils/ipython/start_kernel.py
- spyder/utils/site/sitecustomize.py
- spyder/widgets/dependencies.py
> PR: Backport PR #4198 - Cython support

- circle.yml
- continuous_integration/circle/test-qt4.sh
- continuous_integration/circle/test-qt5.sh
> PR: Run tests for PyQt4 and Python 3.6 on CircleCI

- spyder/app/mainwindow.py
> PR: Add warning message about updating Spyder if installed with Anaconda

- spyder/plugins/tests/test_ipythonconsole.py
- spyder/utils/site/sitecustomize.py
Fixes #1855
Based on solution presented by DStauffman on SO: http://stackoverflow.com/questions/37669435/python-3-5-typeerror-init-got-an-unexpected-keyword-argument-nosigint/42660766#42660766
> PR: Added sigint argument to SpyderPdb constructor

- continuous_integration/circle/install.sh
- continuous_integration/circle/test-qt4.sh
- continuous_integration/circle/test-qt5.sh
- setup.py
- spyder/app/tests/test_mainwindow.py
@ghisvail, this is what you wanted :-)
> PR: Add pytest-xvfb to our test dependencies

- spyder/widgets/variableexplorer/arrayeditor.py
- spyder/widgets/variableexplorer/tests/test_arrayeditor.py
> PR: Add missing parameter to copy contents with the format defined in array editor

- spyder/widgets/externalshell/pythonshell.py
- spyder/widgets/shell.py
> PR: Only show removal message in Python consoles

- spyder/utils/introspection/jedi_patch.py
- spyder/utils/introspection/numpy_docstr.py
Pinging @ghisvail about this one.
> PR: Make jedi_patch.py to work with Jedi 0.10.x versions

- spyder/widgets/editor.py
Fixes #4376
----
I wasn't aware of the changes introduced in #3858 and relay in the old behavior
> PR: Update StackHistory when focus isn't given to the Editor

- spyder/config/main.py
- spyder/widgets/editor.py
- spyder/widgets/sourcecode/base.py
- spyder/widgets/tests/test_editor.py
Fixes: #1833
It's working, ~but I'll refactor It a little to eliminate duplicated code, also the shortcuts need to be defined.~
> PR: Implement go to previous/next cell shortcuts

- spyder/plugins/editor.py
- spyder/widgets/editor.py
Replaces PR #3362 of @ahed87
Rebase to the correct branch (3.x), and a little fix
> PR: Add "Save copy as..." to file menu

- spyder/utils/syntaxhighlighters.py
> PR: Fix error in decorators regex in syntaxhighlighter.

- spyder/config/main.py
- spyder/plugins/externalconsole.py
- spyder/plugins/variableexplorer.py
- spyder/utils/site/sitecustomize.py
- spyder/widgets/externalshell/monitor.py
- spyder/widgets/externalshell/pythonshell.py
- spyder/widgets/ipythonconsole/namespacebrowser.py
- spyder/widgets/variableexplorer/namespacebrowser.py
- spyder/widgets/variableexplorer/tests/test_namespacebrowser.py
- spyder/widgets/variableexplorer/utils.py
> PR: Remove connection between the Variable Explorer and the Python console

- spyder/config/main.py
- spyder/plugins/editor.py
> PR: Delete extra shortcut for the Outline Explorer

- spyder/app/mainwindow.py
- spyder/app/tests/test_mainwindow.py
- spyder/plugins/externalconsole.py
- spyder/plugins/projects.py
Also skip a test that was timing out for now.
> PR: Hide the Python console at startup until we completely remove it

- spyder/plugins/editor.py
> PR: Change Editor title to display file path again

- spyder/widgets/sourcecode/base.py
> PR: Force current cell to be before of current line in extra_selections

- spyder/config/main.py
- spyder/plugins/externalconsole.py
- spyder/plugins/help.py
> PR: Remove connection between Help and the Python Console

- spyder/plugins/editor.py
Fixes incompatibility with master from #4535
> PR: Fix update title signal

- spyder/widgets/mixins.py
- spyder/widgets/panels/edgeline.py
- spyder/widgets/sourcecode/base.py
- spyder/widgets/sourcecode/codeeditor.py
> PR: Take panels widths into account when calculating positions in the Editor 

- spyder/app/mainwindow.py
- spyder/app/tour.py
- spyder/plugins/explorer.py
- spyder/plugins/help.py
- spyder/plugins/history.py
- spyder/plugins/ipythonconsole.py
- spyder/plugins/projects.py
- spyder/widgets/explorer.py
- spyder/widgets/ipythonconsole/client.py
- spyder/widgets/mixins.py
- spyder/widgets/shell.py
This is part of issue #4524. It also removes the last connections between that console and all other plugins.
> PR: Stop loading the Python console

- spyder/widgets/sourcecode/codeeditor.py
> PR: Return value of fix_indentation_smart in fix_indentation

- spyder/app/tour.py
> PR: Prevent hangs and showing tips after tour 

- spyder/widgets/variableexplorer/tests/test_utils.py
- spyder/widgets/variableexplorer/utils.py
> PR: Display collections with None values in the Variable Explorer

- spyder/widgets/sourcecode/codeeditor.py
> PR: Fix error when calling keyPressEvent in keyReleaseEvent in CodeEditor

- spyder/widgets/fileswitcher.py
> PR: Give focus to right entry in the file switcher

- spyder/plugins/__init__.py
> PR: Add a check to verify compatibility to plugins

- spyder/otherplugins.py
Fixes #4487
Uses the proposed change in #4491
> PR: Register spyder_io plugins correctly

- spyder/app/tests/test_mainwindow.py
- spyder/widgets/variableexplorer/utils.py
> PR: Set Numpy threshold every time we run value_to_display

- spyder/app/mainwindow.py
- spyder/widgets/fileswitcher.py
> PR: Fix fileswitcher size during its setup

- spyder/plugins/ipythonconsole.py
- spyder/widgets/tests/test_dependencies.py
This implements #4679 to make IPython >= 4.0 a dependency
> PR: Added IPython >= 4.0 as a dependency

- spyder/widgets/findinfiles.py
> PR: Rename "Path" label to "Current working directory" in Find in Files

- spyder/app/tests/test_mainwindow.py
- spyder/widgets/fileswitcher.py
Fixes #4692 
Fixes #4411 
----
Preview:
-------------------------------------
Also adds a validation to avoid an error when going to previous row for instances with a parent that is not a plugin
> PR: Set width of file switcher according to main window width

- spyder/plugins/editor.py
- spyder/widgets/sourcecode/base.py
> PR: Update tabwidth when changing zoom in Editor.

- spyder/app/mainwindow.py
> PR: Fix error when closing window and we ask users if they want to close it or not

- spyder/app/tests/test_mainwindow.py
> PR: Add tests for dedicated consoles and runconfig options

- spyder/widgets/sourcecode/api/folding.py
- spyder/widgets/sourcecode/codeeditor.py
- spyder/widgets/sourcecode/folding.py
- spyder/widgets/sourcecode/tests/test_folding.py
> PR: Make folding to ignore indented comments

- spyder/utils/editor.py
- spyder/widgets/findreplace.py
> PR: Make searching text to expand folded blocks

- spyder/plugins/editor.py
> PR: Add validation for editorstacks in showing spaces function

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/editor.py
> PR: Fix error when printing source code

- spyder/utils/dochelpers.py
> PR: Prevent importing packages that raise SystemExit exceptions when verifying if an object is defined

- spyder/app/restart.py
- spyder/app/start.py
> PR: Use QT_SCALE_FACTOR when users set only one scale factor

- spyder/widgets/sourcecode/codeeditor.py
> PR: Use Editor font to paint line numbers on all platforms

- spyder/utils/ipython/spyder_kernel.py
> PR: Remove TypeError and AttributeError exceptions from SpyderKernel

- spyder_profiler/widgets/profilergui.py
> PR: Fix sorting in Profiler

- spyder/utils/qthelpers.py
- spyder/widgets/editor.py
> PR: Omit editor split menu option if its reference was deleted

- spyder/plugins/editor.py
> PR: Fix error at startup when trying to set indent_guides.

- spyder/plugins/tests/test_ipythonconsole.py
- spyder/utils/ipython/spyder_kernel.py
- spyder/widgets/ipythonconsole/debugging.py
- spyder/widgets/ipythonconsole/shell.py
> PR: Handle truncated dictionary of namespace view from the kernel

- .pep8speaks.yml
Looking at the configurations https://github.com/OrkoHunter/pep8speaks#configuration I think `diff_only` is the only option we need to change.
https://pep8speaks.com/
> PR: Add basic pep8speaks config file.

- continuous_integration/travis/runtests.sh
This can prevent failures in Travis
> PR: Clean Spyder config before re-running our tests

- spyder/plugins/ipythonconsole.py
> PR: Stop console before closing it

- spyder/plugins/editor.py
- spyder/plugins/tests/test_editor.py
> PR: Fix error when threre are no layout settings

- spyder/widgets/findinfiles.py
These are some minor fixes after PR #4822.
> PR: Minor fixes in Find in Files

- spyder/app/mainwindow.py
- spyder/widgets/pathmanager.py
- spyder/widgets/tests/test_pathmanager.py
Fixes #1105
----
This is an initial implementation for revision. This was developed in Windows 7 64bit with PyQt4.
> PR: Add checkboxes to PYTHONPATH manager to enable/disable paths

- spyder/widgets/fileswitcher.py
> PR: Fix handling of line count in the fileswitcher

- spyder/plugins/tests/test_ipythonconsole.py
- spyder/widgets/tests/test_pathmanager.py
- It seems 3 runs for these tests is not enough because they are failing too much lately.
- This also skips some tests that segfault too much in Python 3 and PyQt4.
> PR: Increase tries for a couple of flaky tests

- spyder/plugins/ipythonconsole.py
> PR: Increase dpi limit of inline plots

- spyder/widgets/variableexplorer/arrayeditor.py
- spyder/widgets/variableexplorer/tests/test_arrayeditor.py
> PR: Fix 1D Numpy arrays edition in the Variable Explorer

- spyder/utils/ipython/style.py
> PR: Add a style for word operator tokens in the IPython pygments dictionary

- spyder/plugins/runconfig.py
> PR: Fix cwd issues in the "Run > Configuration per file" dialog

- spyder/plugins/ipythonconsole.py
- spyder/widgets/ipythonconsole/client.py
> PR: Create Spyder TEMPDIR if it does not exist when creating new consoles

- spyder/utils/qthelpers.py
> PR: Add more handling to actions with reference deleted

- spyder/widgets/editor.py
> PR: Fix error when creating some error messagebox

- spyder/plugins/ipythonconsole.py
> PR: Add handling for non existing indexes in IPython Console clients

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/editor.py
- spyder/utils/ipython/spyder_kernel.py
- spyder/utils/site/sitecustomize.py
- spyder/widgets/ipythonconsole/namespacebrowser.py
> PR: Correctly move to first breakpoint after entering debugging

- spyder/api/panel.py
- spyder/widgets/panels/edgeline.py
- spyder/widgets/panels/indentationguides.py
Fixes #4590 
After some debugging I realize that the hardcoded `5` correspond to `self.editor.document().documentMargin()`
> PR: Improve how floating panels are painted

- spyder/config/main.py
- spyder/plugins/editor.py
- spyder/widgets/editor.py
- spyder/widgets/sourcecode/codeeditor.py
> PR: Deactivate class/function dropdown by default

- spyder/widgets/editor.py
> PR: Add handling for IndexError in the Editor when renaming folder containing file

- spyder/app/tests/test_mainwindow.py
- spyder/utils/site/sitecustomize.py
> PR: Exit the debugger if we are about to enter to sitecustomize.py

- spyder/widgets/variableexplorer/collectionseditor.py
> PR: Handle error when using deepcopy in the collections editor.

- spyder_profiler/widgets/profilergui.py
Fixes #5253.
Compare filename instead of "Diff"
> PR: Fix recursion error in profiler

- spyder/utils/ipython/start_kernel.py
- spyder/widgets/ipythonconsole/shell.py
> PR: Fix some execution delays in the IPython console

- spyder/plugins/editor.py
- spyder/plugins/tests/test_editor.py
> PR: Rearrange line count when opening files to correspond to the correct one

- spyder/app/start.py
> PR: Prevent a race condition with ZMQ during startup

- spyder/widgets/sourcecode/codeeditor.py
- spyder/widgets/sourcecode/utils/decoration.py
See https://github.com/spyder-ide/spyder/pull/4751#issuecomment-331008782
@andfoy could you test  if this fix the error with underlined decorations?
> PR: Update font decorations when adding them to the editor.

- spyder/app/mainwindow.py
PR #5159 was merged incorrectly against master.
> PR: Backport PR 5159

- README.md
- conda.recipe/meta.yaml
- doc/installation.rst
- setup.py
> PR: Update minimal QtPy required version

- spyder/widgets/variableexplorer/tests/test_dataframeeditor.py
This is making our tests to fail in master
> PR: Fix test_sort_dataframe_with_category_dtypes

- spyder/widgets/sourcecode/codeeditor.py
- spyder/widgets/sourcecode/tests/test_indentation.py
> PR: Fix indentation with selection

- spyder/plugins/editor.py
Fixes #5488
A pull request that fixes issue #5488
> PR: Add option to toggle code style checks from Source menu

- bootstrap.py
> PR: Fix bootstrap.py --debug

- spyder/utils/encoding.py
> PR: Add cp1251 (default Russian) encoding on Windows to be recognized by the Editor

- spyder/plugins/ipythonconsole.py
> PR: Add handling for RuntimeError while closing an IPython console instance.

- spyder/plugins/shortcuts.py
> PR: Add confirmation message to reset shortcuts.

- spyder/plugins/help.py
> PR: Add validation for attribute 'is_running' in the Help plugin

- spyder_profiler/widgets/profilergui.py
> PR: Catch not found file error when loading profiler results.

- spyder/config/base.py
- spyder/widgets/variableexplorer/utils.py
> PR: Support datetime.timedelta in variable explorer

- spyder/app/tests/test_mainwindow.py
- spyder_pylint/widgets/pylintgui.py
> PR: Change position of data loading to prevent not calling validation in the Pylint plugin

- spyder/utils/site/sitecustomize.py
> PR: Ignore warning generated by ipykernel.datapub

- spyder/utils/icon_manager.py
- spyder/widgets/dependencies.py
- spyder/widgets/tests/test_dependencies.py
Fixes #5652 
Following are screenshots of the new dialog.
Regular Spyder session:
Test case with some errors:
> PR: Improve dependencies dialog

- spyder/widgets/editor.py
- spyder/widgets/explorer.py
- spyder/widgets/projects/explorer.py
> PR: Update obsolete enums in QMessageBox

- spyder/plugins/ipythonconsole.py
> PR: Catch TypeError while executing code instructions in the IPython console

- spyder/widgets/comboboxes.py
> PR: Add a tooltip showing the full path of highlighted item in the working directory dropdown box

- spyder/widgets/sourcecode/codeeditor.py
> PR: Fix broken shortcuts for changing editor tabs (Ctrl+PageUp, Ctrl+PageDown)

- spyder/utils/dochelpers.py
> PR: Catch AttributeError while using the Help plugin

- spyder/app/tour.py
- spyder/utils/icon_manager.py
This is a minor change and I don't know if you agree with it. If you don't, simly reject it. I didn't bother to first create an issue to discuss it, because it would be more work than just doing the pull request.
The current tour looks like this
IMHO OS design trends have changed to more flat and square style. So the rounded corners look a bit old-fashioned. I propose to just remove them.
> PR: Give a more modern appearence to the tour

- spyder/app/mainwindow.py
Fixes #5728.
Fix missing doc links.
See issue #5728.
> PR: Fix missing documentation links

- spyder/utils/sourcecode.py
- spyder/widgets/sourcecode/codeeditor.py
- spyder/widgets/sourcecode/tests/test_indentation.py
Fixes #5678.
`fix_indentation` was hard-coded to convert tabs to 4 spaces.   Now it will change tabs to the indentation character from preferences.
> PR: Change fix_indentation to use preference for number of spaces

- spyder/app/start.py
> PR: Avoid errors when importing pyopengl at startup

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/ipythonconsole.py
- spyder/plugins/tests/test_ipythonconsole.py
- spyder/utils/test.py
- spyder/widgets/editor.py
- spyder/widgets/tests/test_save.py
> PR: Fix renames when moving IPython console tabs

- spyder/widgets/ipythonconsole/shell.py
> PR: Catch error when resetting console namespace and no kernel_client is available

- spyder/widgets/findreplace.py
> PR: Fix error when searching text in the Editor in translated interfaces

- spyder/widgets/variableexplorer/dataframeeditor.py
- spyder/widgets/variableexplorer/tests/test_dataframeeditor.py
> PR: Catch OutOfBoundsDatetime errors from pandas

- spyder/plugins/shortcuts.py
> PR: Update super() call to use Python 2 style call

- spyder/app/mainwindow.py
- spyder/app/start.py
- spyder/app/tests/test_mainwindow.py
- spyder/plugins/ipythonconsole.py
- spyder/utils/external/lockfile.py
> PR: Fix %edit magic on Windows

- spyder/config/user.py
- spyder/plugins/editor.py
- spyder/plugins/help.py
- spyder/plugins/shortcuts.py
- spyder/utils/introspection/fallback_plugin.py
- spyder/utils/introspection/jedi_plugin.py
- spyder/utils/introspection/numpy_docstr.py
- spyder/utils/introspection/utils.py
- spyder/utils/programs.py
- spyder/utils/stringmatching.py
- spyder/utils/syntaxhighlighters.py
- spyder/widgets/arraybuilder.py
- spyder/widgets/explorer.py
- spyder/widgets/ipythonconsole/help.py
- spyder/widgets/sourcecode/base.py
- spyder/widgets/variableexplorer/utils.py
- spyder_profiler/widgets/profilergui.py
- spyder_pylint/widgets/pylintgui.py
Fixes #6254.
Mostly straightforward change, but we probably all need to run the code to make sure there aren't any gotchas.  I tested the more complicated ones and they worked the same before and after the change.
> PR: Change to re strings for Deprecation Warning

- spyder/app/mainwindow.py
Fixes #6202.
I couldn't recreate this issue, so I made a change to display a message when it occurs.
> PR: Custom layouts not working when hexstate is None

- spyder/widgets/ipythonconsole/debugging.py
> PR: Don't add repeated entries to history while on pdb

- spyder/widgets/ipythonconsole/client.py
> PR: Catch RuntimeError when no kernel is running

- spyder/plugins/editor.py
- spyder/plugins/help.py
- spyder/plugins/tests/test_help.py
- spyder/utils/introspection/fallback_plugin.py
- spyder/utils/introspection/jedi_plugin.py
- spyder/utils/introspection/manager.py
- spyder/utils/introspection/rope_plugin.py
- spyder/utils/introspection/tests/test_fallback_plugin.py
- spyder/utils/introspection/tests/test_jedi_plugin.py
- spyder/utils/introspection/tests/test_rope_plugin.py
- spyder/utils/introspection/utils.py
> PR: Fix some completion errors in the Editor and show again no docs message in Help

- spyder/plugins/ipythonconsole.py
> PR: Handle AttributeError when running code in the IPython Console.

- spyder/widgets/editor.py
- spyder/widgets/tests/test_editorsplitter.py
PR #5512 introduced some problems in the management of the editorsplitters due mainly to the use of the signal `sig_close_split` [here](https://github.com/spyder-ide/spyder/pull/5512/files#diff-0308a6d064ae2a204bd97de4f832e1f4R730) and [here](https://github.com/spyder-ide/spyder/pull/5512/files#diff-0308a6d064ae2a204bd97de4f832e1f4R1371) instead of closing the editorstacks explicitly. This prevented the [closeEvent](https://github.com/csabella/spyder/blob/7c0643466ffa4b9c7576a5eb51b16236130ee568/spyder/widgets/editor.py#L813) of the editorstack to be called, and thus, the editorstacks were not removed correctly from the outlineeditor, introducing a regression bug in the master branch that was fixed in PR #5083.
Secondly, the use of  the signal `sig_close_split` …
> Fix EditorStack and EditorSplitter not closing correctly.

- spyder/utils/external/lockfile.py
> PR: Add error handling for the lockfile symlink on Windows

- scripts/spyder.desktop
- scripts/spyder3.desktop
Added keywords to the desktop files to fix #5316
> PR: Add keywords to desktop files

- spyder/plugins/tests/test_ipythonconsole.py
See https://github.com/ipython/ipykernel/pull/307
> PR: Xfail test_auto_backend for certain versions of zmq and ipykernel

- conftest.py
- runtests.py
- spyder/app/mainwindow.py
- spyder/app/start.py
- spyder/plugins/editor.py
- spyder/plugins/outlineexplorer.py
- spyder/plugins/tests/test_ipythonconsole.py
- spyder/widgets/editor.py
- spyder/widgets/editortools.py
This also removes all code related to full path sorting, which was eliminated as part of PR #3946.
> PR: Fix all test files to be run independently

- conftest.py
- runtests.py
- spyder/app/mainwindow.py
- spyder/app/tests/test_mainwindow.py
- spyder/config/base.py
- spyder/plugins/projects.py
- spyder/plugins/tests/test_editor_introspection.py
- spyder/plugins/tests/test_projects.py
- spyder/utils/introspection/jedi_plugin.py
- spyder/widgets/variableexplorer/tests/test_dataframeeditor.py
> PR: Make projects work on unicode directories

- spyder/widgets/mixins.py
> PR: Handle errors when writing history to disk in the IPython Console

- doc/installation.rst
> PR: Update broken matplotlib project URL in install doc 

- spyder/utils/introspection/tests/test_jedi_plugin.py
> PR: Skip test_completions_custom_path if jedi version before 0.10.0

- setup.py
- spyder/app/tests/test_mainwindow.py
> PR: Demand PyQt5 less than 5.10 in our wheels

- spyder/utils/introspection/jedi_plugin.py
- spyder/utils/introspection/tests/test_jedi_plugin.py
Also add a regression test.
Fixes #6516.
> PR: Fix AttributeError in jedi_plugin

- spyder/app/mainwindow.py
This way it's easier to read, at least for me.
@CAM-Gerlach?
> PR: Restore the previous wording for package versions in error report

- spyder/plugins/editor.py
- spyder/plugins/explorer.py
- spyder/plugins/projects.py
- spyder/plugins/tests/test_editor.py
- spyder/widgets/explorer.py
> PR: Allow rename from Explorer to work for directories

- spyder/utils/help/conf.py
Fixes #6570.
http://www.sphinx-doc.org/en/stable/config.html#confval-html_use_smartypants
> PR: Update deprecated Sphinx directive html_use_smartypants

- spyder/otherplugins.py
> PR: Add handling for AttributteError when importing module from path

- spyder/plugins/editor.py
- spyder/plugins/tests/test_editor.py
- spyder/widgets/editor.py
> PR: Be able to open files in the Editor if no template is found

- continuous_integration/travis/install.sh
- spyder/app/tests/test_mainwindow.py
- spyder/plugins/ipythonconsole.py
- spyder/utils/ipython/kernelspec.py
- spyder/utils/ipython/start_kernel.py
- spyder/utils/site/sitecustomize.py
> PR: Run Cython files in a dedicated console

- spyder/utils/external/lockfile.py
> PR: Fix new instance validation on Windows.

- spyder/utils/site/sitecustomize.py
- spyder/widgets/ipythonconsole/shell.py
> PR: Fix Mayavi plotting in our consoles

- CONTRIBUTING.md
Modest updated of CONTRIBUTING.md to improve the organization (mainly, moving the Troubleshooting section further up for visibility), add the standard links from the new readme to the bottom for easy access, and a few minor textual fixes.
> PR: Update contributing doc with better organization, standard links and minor fixes

- setup.py
Just what it says on the tin, following the discussion and readme updates in #6909 .
> PR: Update minimum Python version in setup.py to 3.4

- appveyor.yml
- continuous_integration/travis/install.sh
This was making our tests fail.
> PR: Remove Jedi pinnings in our CIs

- CONTRIBUTING.md
- README.md
Currently, our Facebook and especially Twitter links aren't really linked from anywhere but our OpenCollective to my knowledge, and correspondingly have very low SEO rankings and are very hard to find. Therefore, this PR adds them to our readme and contributing guide.
N/A; very minor change to meta-item
> PR: Add Twitter and Facebook links to Readme, for SEO/visibility

- spyder/utils/ipython/kernelspec.py
- spyder/utils/ipython/start_kernel.py
> PR: Avoid loading/saving IPython console history in safe mode or testing

- spyder/app/start.py
- spyder/config/base.py
Fixes #7051.
Fixes #6886.
*Note*: I couldn't come up with a test for these problems.
> PR: Fix a couple of problems when setting and detecting the system locale

- spyder/plugins/ipythonconsole.py
> PR: Show errors generated when creating QtKernelManager inside the IPython console

- spyder/utils/syntaxhighlighters.py
- spyder/widgets/editortools.py
- spyder/widgets/tests/test_editortools.py
**Goal:** Being able to use code cells to organize and group the code blocks in the outline panel.
1. The first necessary change is to group all code blocks into code cells.  When present, code cells are now the top level objects in the outliner and all code block will be grouped under them.
2. Second the ability to use `# %%%` as a grouped cell that will be place under the previous top level `# %%` cell.
See it in action:
I didn't actually change much code and seems to cover most cases.  If you put a code cell comment in a code block like a class or a function the out line misses the rest of the block.  I don't see a use case of a code cell in a function or class. Unfortunately this simple code doesn't know about function or classes in defined in a code block such as an if statement so I …
> PR: Show group cells in Outline Explorer

- spyder/widgets/ipythonconsole/client.py
Add try catch to handle `AttributeError` when setting color scheme in the IPython Console
Fixes #6996
> PR: Handle AttributeError when setting color scheme in the IPython Console.

- spyder/widgets/explorer.py
Handle `AttributeError` in DirView when updating not initialized menu
Fixes #6975
> PR: Handle not initialized menu in DirView.

- spyder/plugins/ipythonconsole.py
Add Matplotlib as optional dependency of the IPython console (therefore showing it at the dependencies dialog).
Fixes #6887
> PR: Add Matplotlib as optional dependency for the IPython Console.

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/tests/test_editor_introspection.py
- spyder/widgets/panels/tests/test_scrollflag.py
- spyder/widgets/tests/test_editorsplitter.py
I missed those after merging #6961 with master.
> PR: Remove missing PyQt4 references in our tests

- spyder/utils/site/sitecustomize.py
Add `astropy` and `pytorch` by default to the UMR blacklist
Fixes #7041 
Fixes #6962
> PR: Add astropy and pythorch to UMR blacklist by default.

- spyder/utils/programs.py
- spyder/utils/tests/test_programs.py
Prevent the test of `-h` for validating a custom interpreter selected when using `pythonw`
Fixes #7059
> PR: Change validation to allow pythonw executables as valid interpreters

- spyder/utils/site/sitecustomize.py
Add `fastmat` (Python 2 only) and `pythoncom` to UMR blacklist
Fixes #7190
> PR: Add fastmat and pythoncom to UMR blacklist.

- spyder/widgets/variableexplorer/tests/test_utils.py
- spyder/widgets/variableexplorer/utils.py
> PR: Add bytes or unicode ellipses in value_to_display

- spyder/widgets/mixins.py
- spyder/widgets/tests/test_mixins.py
> PR: Fix error when using unicode to search text with regular expressions in the Editor

- spyder/app/mainwindow.py
- spyder/plugins/editor.py
- spyder/plugins/workingdirectory.py
- spyder/utils/encoding.py
- spyder/widgets/editor.py
- spyder/widgets/explorer.py
- spyder/widgets/mixins.py
- spyder/widgets/shell.py
> PR: Catch EnvironmentError in all places we write to disk

- spyder/plugins/ipythonconsole.py
> PR: Show message in our consoles when trying to run a file while on debugging

- spyder/plugins/help.py
> PR: Catch possible errors when writing Help's history to disk

- spyder/otherplugins.py
> PR: Catch any error when trying to load third-party plugins

- spyder/app/mainwindow.py
- spyder/plugins/variableexplorer.py
- spyder/widgets/variableexplorer/collectionseditor.py
- spyder/widgets/variableexplorer/namespacebrowser.py
Add signals to call the garbage collector from the Main Window after closing Variable Explorer editors.
Fixes #7157 
Fixes #5830
> PR: Call garbage collector from Main Window after closing Variable Explorer editors

- README.md
@ccordoba12 
Modifies the funding message to better reflect the current situation, shortens it to be more concise to take up less space at the top of the readme, and makes it more robust to status changes up to the planned Spyder 4 final release. Can/will also be applied to ``spyder-docs``, ``QtPy`` and ``spyder-unittest`` (as actively supported core or plugin projects that have the old message) once approved here. 
Meanwhile, the version to replace the current one on the Spyder plugins (``spyder-xxx`` other than ``spyder-unittest``) would have a heavily modified first paragraph making clear the current development pause and the plan to restart it after the Spyder 4 release (absent specific funding), while keeping …
> PR: Update donation/funding status message in Readme

- README.md
I hit "Request" next to your name under reviewers and github *submitted the PR*. Thanks, ~~Github~~ Microsoft.
...
Anyway, that nonsense aside, this just makes a few minor tweaks to the badges/links:
* Updates the PyPI link to the new PyPI
* Standardizes the links at the bottom with the others to use ``https`` on the Google Groups URL
* Minor tweaks to the badge order for sensibility and standardization
As usual, you can preview the changes over on [my fork](https://github.com/CAM-Gerlach/spyder/blob/update-funding-message/README.md).
Very minor change to Readme; not needed.
> PR: Fix links to Travis CI and Google Group

- spyder/plugins/ipythonconsole.py
> PR: Don't allow multiple executions in the IPython console when one is taking place

- spyder/widgets/ipythonconsole/debugging.py
Resets hist_wholeline
Fixes #7295
> PR: Fix history browsing while debugging

- spyder/widgets/variableexplorer/tests/test_collectioneditor.py
- spyder/widgets/variableexplorer/tests/test_dataframeeditor.py
Add handling for deprecated methods in the tests when using pandas.
Fixes #7312
> PR: Handle deprecated Pandas methods in tests

- spyder/app/mainwindow.py
> PR: Catch AttributeError when trying to get the active project path

- CONTRIBUTING.md
- README.md
Following the separation of the ``spyder-kernels`` module in 3.3.0, running Spyder from a github clone needs to have the correct version of ``spyder-kernels`` installed. Therefore, this PR ensures that is made clear in the readme and contributing guide, the counterpart of spyder-ide/spyder-docs#69
Fixes #7337
> PR: Update the running Github clone procedure in the readme and contributing guide to include spyder-kernels

- spyder/widgets/ipythonconsole/shell.py
- spyder/widgets/shell.py
> PR: Really hide reset namespace warning in IPython console

- .travis.yml
- appveyor.yml
- circle.yml
- continuous_integration/circle/install.sh
- continuous_integration/circle/modules_test.sh
- continuous_integration/travis/install-qt.sh
- continuous_integration/travis/install.sh
- spyder/plugins/ipythonconsole.py
- spyder/plugins/tests/test_ipythonconsole.py
> PR: Fix connection to external kernels

- spyder/config/main.py
> PR: Remove old shortcut for the Python console

- spyder/config/base.py
> PR: Avoid raising an error when getting available translations

- spyder/workers/tests/test_update.py
- spyder/workers/updates.py
Improve update notifications by checking agains anaconda instead of github.
Fixes #7452
> PR: Change way to check for updates

- spyder/widgets/internalshell.py
Handle input commands correctly in the internal console (checking the `--multithread` option). Running such commands in an internal console in the same thread makes Spyder hang.
Fixes #1329
> PR: Handle input commands correctly in the internal console.

- spyder/widgets/projects/type/__init__.py
> PR: Catch errors when saving/getting the list of open files per project

- scripts/spyder3.appdata.xml
Fixes a bug (stray letter that presumably breaks the syntax) introduced into our ``spyder3.appdata.xml`` file by #7598 . Not sure how that happened; I check the diffs every time before I commit to spot things like this but it must have slipped through.
> PR: Fix bug in spyder3.appdata.xml

- spyder/config/utils.py
> PR: Catch errors when getting file type extensions supported by Pygments

- spyder/config/main.py
- spyder/plugins/configdialog.py
- spyder/plugins/maininterpreter.py
- spyder/plugins/workingdirectory.py
> PR: Simplify how custom interpreters are loaded/saved

- spyder/plugins/ipythonconsole.py
> PR: Catch error when writing to stdin and there's no kernel client available

- spyder/widgets/variableexplorer/collectionseditor.py
> PR: Catch any error when trying to copy the contents of a dataframe

- spyder/plugins/editor/widgets/editor.py
- spyder/plugins/editor/widgets/tests/test_save.py
> PR: Fix saving a new file or renaming an existing file in master

- spyder/widgets/editor.py
> PR: Catch error when dropping a file on the Editor doesn't have an associated url

- spyder/utils/tests/test_vcs.py
- spyder/utils/vcs.py
- spyder/widgets/explorer.py
Fixes #7733.
Also add some tests for `utils/vcs.py`
> PR: Fix Browse and Commit vcs actions in file and project explorers

- .coveragerc
Exclude all code in `if __name__ == .__main__.:` code block from coverage reports.
> PR: Exclude non-runnable code from coverage reports

- spyder/plugins/editor/widgets/editor.py
- spyder/plugins/editor/widgets/tests/test_editor_and_outline.py
- spyder/plugins/outlineexplorer/widgets.py
> PR: Remove file from the outline explorer when it is closed

- CONTRIBUTING.md
- README.md
- requirements/requirements.txt
- requirements/test_requirements.txt
- setup.py
- spyder/plugins/editor/plugin.py
- spyder/utils/codeanalysis.py
- spyder/utils/introspection/jedi_plugin.py
- spyder/utils/introspection/manager.py
- spyder/utils/introspection/rope_plugin.py
* Part of issue #7724.
* @CAM-Gerlach, we need an update to our docs for this too.
TODO:
> PR: Add pyls as a new dependency

- spyder/config/main.py
- spyder/plugins/findinfiles.py
- spyder/plugins/tests/test_findinfiles.py
- spyder/widgets/findinfiles.py
- spyder/widgets/variableexplorer/collectionseditor.py
Fixes #6176.
This PR also removes some old options in Find in Files.
> PR: Correctly save Find in Files options when closing Spyder

- spyder/plugins/ipythonconsole.py
- spyder/plugins/tests/test_ipythonconsole.py
- spyder/widgets/ipythonconsole/client.py
> PR: Remove unnecessary code to restart kernels

- spyder/plugins/ipythonconsole/plugin.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/plugins/ipythonconsole/widgets/shell.py
- spyder/plugins/variableexplorer/widgets/namespacebrowser.py
By submitting this Pull Request, I affirm that:
* I release the content of this PR under Spyder's MIT (Expat) license.
* I hold the copyright to all the content in this PR, have not copied any of it
directly or indirectly from any source other than the public domain,
and no other party owns the rights to this work.
Uses the environment vars to determine which packages where initially loaded and reloads those after the kernel is reset.
Reloads without touching matplotlib backends.
This code doesn't check if the packages are installed.
Fixes #7224
> PR: Reinitialize Pylab, Sympy and Cython after clearing all variables

- spyder/plugins/ipythonconsole.py
By submitting this Pull Request, I affirm that:
* I release the content of this PR under Spyder's MIT (Expat) license.
* I hold the copyright to all the content in this PR, have not copied any of it
directly or indirectly from any source other than the public domain,
and no other party owns the rights to this work.
Revises the Connect to kernel dialog text to be more clear, descriptive and stylistically correct, particularly with regard to specifying that only a SSH keyfile *or* user password is required, not both.
Fixes #7868
> PR: Clarify and improve Connect to kernel dialog text

- spyder/utils/tests/test_programs.py
- spyder/workers/tests/test_update.py
- spyder/workers/updates.py
> PR:  Improve detection of new Spyder versions to be offered for updates

- README.md
- spyder/app/mainwindow.py
- spyder/plugins/ipythonconsole.py
- spyder/plugins/tests/test_ipythonconsole.py
- spyder/utils/misc.py
- spyder/widgets/ipythonconsole/client.py
This was broken after PR #7829.
> PR: Fix showing kernel creation error messages

- .github/PULL_REQUEST_TEMPLATE.md
By submitting this Pull Request, I affirm that:
* I release the content of this PR under Spyder's MIT (Expat) license.
* I hold the copyright to all the content in this PR, have not copied any of it
directly or indirectly from any source other than the public domain,
and no other party owns the rights to this work.
Updates the pull request template to simply link to the standard and accepted [Developer COI ](https://developercertificate.org/) used by many open source projects, rather than lengthier bespoke legal text included previously. Also does some minor cleanup, refinements and clarification to the template text.
> PR: Update PR template to link to developer COI and clarify other text

- spyder/plugins/editor/lsp/providers/document.py
> PR: Fix error in LSP when closing file

- spyder/plugins/editor/widgets/base.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/widgets/reporterror.py
> PR: Make all editor's background color to be applied correctly

- spyder/widgets/pathmanager.py
Prevent the addition of paths with unicode characters in the PYTHONPATH in Python 2. A message will appear when this situation happens.
Fixes #7236
> PR: Add validation in Python 2 to prevent the addition of paths with unicode characters to the PYTHONPATH

- spyder/widgets/variableexplorer/dataframeeditor.py
> PR: Catch errors when trying to display dataframe values as strings

- spyder/widgets/findreplace.py
- spyder/widgets/tests/test_editor.py
> PR: Catch errors when trying to replace text in the Editor with a regexp

- spyder/utils/icon_manager.py
Currently in the editor, lines starting with "TODO" get marked with a checkmark at the left border.
I am associating a checkmark with "done", i.e. the opposite of "todo" ;-)
So I suggest to replace this checkmark with an unchecked checkbox symbol, as discussed in #2264.
Screenshot of the new label:
Fixes #2264
> PR: Change the TODO checkmark

- spyder/plugins/configdialog.py
> PR: Catch errors when trying to change the interface language

- spyder/app/mainwindow.py
- spyder/plugins/profiler/widgets/profilergui.py
- spyder/widgets/github/backend.py
- spyder/widgets/reporterror.py
Setup parent reference to dialogs to ensure the set up of the dark style sheet for the dark theme.
Part of #8068
> PR: Add parent reference to dialogs to ensure correct setup of the dark theme

- spyder/app/mainwindow.py
- spyder/plugins/__init__.py
- spyder/plugins/editor.py
- spyder/plugins/help.py
- spyder/plugins/ipythonconsole.py
- spyder/plugins/projects.py
- spyder/plugins/tests/test_help.py
- spyder/plugins/tests/test_ipythonconsole.py
- spyder/plugins/tests/test_projects.py
- spyder/widgets/ipythonconsole/namespacebrowser.py
- spyder_breakpoints/breakpoints.py
- spyder_profiler/profiler.py
- spyder_pylint/pylint.py
> PR: Unmaximize plugins when an action or menu calls another plugin

- spyder/app/tests/script.py
- spyder/app/tests/test_mainwindow.py
- spyder/plugins/ipythonconsole/plugin.py
Changed `runcell` to use a r-string to preserve escape charaters
Fixes #8241
> PR : Fix for escaped string in runcell

- spyder/app/tests/script.py
- spyder/plugins/editor/widgets/base.py
- spyder/plugins/editor/widgets/editor.py
- spyder/widgets/tests/test_shortcutssummary.py
Added a new line to the end of the code to separated the triple quotes of run cell and removed the `rstrip()` calls.
Also removed the code that added a new line after every key word block. This code seems to indicate that it is necessary to have the code run in the console but this dosen't seem to be needed in the ipython console. This code was changing the traceback line numbers.
Fixes #8244 
Fixes #8242
> PR: Fix quotes and traceback lines in runcell

- spyder/app/tests/script.py
- spyder/plugins/ipythonconsole/plugin.py
`runcell` can't escape triple quotes when using raw string. So I've replaced all `\` with `\\` instead.
Fixes #8267
> PR: Add additional escape slashes instead of a raw string in runcell

- spyder/api/plugins.py
- spyder/app/mainwindow.py
- spyder/config/gui.py
- spyder/config/main.py
- spyder/plugins/ipythonconsole/plugin.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/plugins/lspmanager.py
- spyder/preferences/configdialog.py
- spyder/utils/icon_manager.py
- spyder/utils/syntaxhighlighters.py
- spyder/widgets/reporterror.py
Centralize theme-related preferences under a 'Theme' pane. Includes old Syntax coloring, Fonts , Qt Window Style and Icon theme preferences.
Initial preview:
Fixes #8071
Fixes #8080 
Part of #8068
> PR: Centralize theme-related preferences under an 'Appearance' entry

- scripts/spyder.desktop
- scripts/spyder3.desktop
> PR: Add StartupWMClass to Linux desktop files

- spyder/app/mainwindow.py
* [*] Included a screenshot (if affecting the UI)
I added qdarkstyle to dependencies in mainwindow.py for solving the issue 8291
Fixes #8291 
I certify the above statement is true and correct: @juanis2112
> PR: Add qdarkstyle to dependencies dialog

- README.md
- appveyor.yml
- continuous_integration/posix/install.sh
- requirements/conda.txt
- requirements/pip.txt
- setup.py
- spyder/utils/encoding.py
Use of `atomicwrites` to prevent possibility of Spyder wiping user's files.
Fixes #8237 
> PR: Do atomic writes when saving files

- spyder/plugins/editor/lsp/client.py
- spyder/plugins/editor/lsp/transport/producer.py
Use `sys.executable -m pyls` to start `pyls`.
Fixes #8159 
> PR: Improve robustness when starting pyls

- spyder/api/plugins.py
Add a validation for the dockwidget existence at the `visibility_changed` method of the `PluginWidget` class to prevent an AttributeError on startup.
Fixes #8283 
> PR: Validation of dockwidget existence before raising it

- spyder/app/mac_stylesheet.qss
> PR: Add dark background to the light theme buttons on macOS

- spyder/plugins/editor/tests/test_introspection.py
Improve existing introspection test to cover issue case
Fixes #8297 
> PR: Modify test_introspection to test module completion

- spyder/app/tests/test_mainwindow.py
- spyder/config/main.py
- spyder/plugins/ipythonconsole/widgets/figurebrowser.py
- spyder/plugins/plots/widgets/figurebrowser.py
Improvements discussed for the Plots plugin
Fixes #8320 
> PR: Increase width of the ThumbnailScrollBar and add render message

- spyder/locale/pt_BR/LC_MESSAGES/spyder.po
Fixed a wrong written word
Issue(s) Resolved
Fixes #8309
Affirmation
I affirm the Developer Certificate of Origin
JensHumrich
> PR: Fix translation error in the Brazilian Portuguese translation

- spyder/plugins/plots/widgets/figurebrowser.py
Add a argument to set the background color of the `FigureCanvas` of the Plots plugin
A preview:
Fixes #8443 
> PR: Add kwarg for FigureCanvas background color

- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/widgets/editor.py
> PR: Fix actions shown on the Editor Options menu for undocked and new windows

- spyder/plugins/editor/tests/test_introspection.py
- spyder/plugins/editor/widgets/base.py
- spyder/widgets/mixins.py
* Check for the common prefix between the current word and the completion selected. 
* Improve calculation of current word for completions (taking into account special characters).
A preview:
Fixes #8297
> PR: Fix completion insertion in the Editor

- spyder/app/mainwindow.py
I tested the full screen mode only in windows 7, 10.
Thank you.
Fixes #8545
> PR : Fix full screen action in dual monitor enviroment for Windows

- spyder/plugins/variableexplorer/widgets/dataframeeditor.py
Improve resize limits to handle better the index column in the DataFrame Editor
Fixes #7629 
> PR: Improve index column resize in dataframe editor

- spyder/plugins/console/widgets/shell.py
- spyder/plugins/editor/widgets/base.py
- spyder/plugins/editor/widgets/codeeditor.py
> PR: Fix code completion in the Internal Console

- spyder/plugins/variableexplorer/plugin.py
- spyder/plugins/variableexplorer/widgets/collectionseditor.py
- spyder/plugins/variableexplorer/widgets/namespacebrowser.py
- spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py
> PR: Handle namespace browser column width

- spyder/plugins/variableexplorer/widgets/arrayeditor.py
- spyder/plugins/variableexplorer/widgets/dataframeeditor.py
Enclosed the entire contents of the load_more_data method in a try/except NameError block to solve issue 7880
Fixes #7880 
Juanis2112
> PR: Enclose contents of load_more_data method in try/except NameError Block

- azure-pipelines.yml
- requirements/conda.txt
- setup.py
- spyder/plugins/editor/lsp/transport/consumer.py
This change fixes the failure of LSP response on windows.
Fixes #8565.
Fixes #8153
Fixes #8022
> PR: Fix LSP consumer reading block on Windows

- spyder/plugins/editor/extensions/closequotes.py
- spyder/plugins/editor/extensions/tests/test_closequotes.py
This PR allows quotations to be completed inside brackets and before commas, colons and semi-colons 
This was a simple but effective patch so I didn't need to refactor anything.
Fixes #6827
> PR: Close quotes inside brackets and before commas, colons and semi-colons

- spyder/plugins/projects.py
- spyder/plugins/tests/test_projects.py
Please see #8452 for the details.
> PR: Backport PR 8452

- README.md
[A preview](https://github.com/dalthviz/spyder/blob/sponsors/README.md)
> PR: Update README's sponsors section

- spyder/widgets/fileswitcher.py
Make the file switcher taller, changing the max number of files in the file switcher to 15.
Fixes Item 4 of #8580 
Juanis2112
> PR: Change the max number of files in the file switcher to 15

- spyder/plugins/explorer/widgets.py
- spyder/utils/icon_manager.py
- spyder/widgets/fileswitcher.py
I implemented the file type icons in the file switcher.
Fixes item 5 of #8580 
Juanis2112
> PR:  Use file type icons in the File Switcher

- spyder/widgets/fileswitcher.py
…how to use it.
Included a place holder text in the switcher text field to explain users how to use it.
Fixes Item 9 #8580 
Juanis2112
> PR: Show a place holder text in the switcher text field to explain users how to use it

- spyder/widgets/variableexplorer/collectionseditor.py
> PR: Backport PR 8559

- spyder/plugins/editor/widgets/editor.py
- spyder/plugins/editor/widgets/tests/test_save.py
An autosave file is generated if the user changes a file in the editor. If the user closes the file (or quits Spyder), they are asked if they want to save the file. If they say "No", then at the moment the autosave file persists, and the user will be presented with a recovery dialog the next time they start Spyder, even though they already said that they want to discard their changes.
This PR removes the autosave file if the user closes the file or quits Spyder and chooses not to save.
Fixes #8655
I certify the …
> PR: Remove autosave file if user chooses not to save when asked

- continuous_integration/travis/install.sh
- setup.py
> PR: Add pyqtwebengine as a new dependency

- spyder_io_hdf5/__init__.py
* [x ] Included a screenshot (if affecting the UI)
Plugin no longer available - apparently due to PLUGIN_CLASS global not being present and True
Fixes #8789
smjorda
> PR: Fix missing spyder_io_hdf5 plugin

- .travis.yml
- spyder/plugins/tests/test_ipythonconsole.py
Does three things:
* Removes the deprecated ``sudo: false`` build configuration activating the containerized images that is or will shortly be removed from Travis
* Upgrades the distribution to Xenial to provide a more modern build environment, which will soon become the default
* Changes the ``xvfb`` start code from bespoke logic to the standardized, modern ``service: xvfb`` syntax.
CAM-Gerlach
> PR: Upgrade Travis config to use Xenial image

- spyder/config/base.py
> PR: Avoid errors when trying to save LANG_FILE

- spyder/config/fonts.py
- spyder/config/main.py
- spyder/plugins/explorer/widgets.py
- spyder/utils/icon_manager.py
- spyder/widgets/fileswitcher.py
Added new font size for file switcher according to the OS in the fonts file in config.
This is the screenshot for Mac OS X
This is the screenshot for Linux
This is the screenshot for Windows
Part of #8580 
Juanis2112
> PR: Add new font size for file switcher according to the OS

- spyder/plugins/editor/panels/debugger.py
- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/utils/debugger.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/utils/icon_manager.py
```python
File "C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\spyder\plugins\editor\panels\debugger.py", line 99, in mousePressEvent
edit_condition=shift)
File "C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\spyder\plugins\editor\utils\debugger.py", line 103, in toogle_breakpoint
condition)
TypeError: getText(QWidget, str, str, echo: QLineEdit.EchoMode = QLineEdit.Normal, text: str = '', flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags(), inputMethodHints: Union[Qt.InputMethodHints, Qt.InputMethodHint] = Qt.ImhNone): argument 1 has unexpected type 'DebuggerManager'
```  
Fixes #8846  …
> PR: Fix stuck arrow and conditional breakpoints in the debugger panel

- spyder/config/fonts.py
- spyder/config/main.py
- spyder/widgets/fileswitcher.py
These are just some minor adjustments for things to look better after @juanis2112's work on the file switcher.
> PR: Adjust font sizes to look better for Linux and Windows

- spyder/plugins/help.py
> PR: Don't fail on UnicodeEncodeError when saving Help's search history to disk

- spyder/locale/fr/LC_MESSAGES/spyder.po
> PR: Change 'Supprimer' for 'Effacer' in remove variables text for French translation

- spyder/plugins/outlineexplorer/widgets.py
> PR: Catch error in Outline explorer when renaming file

- requirements/conda.txt
- setup.py
- spyder/config/main.py
Change the default settings for the pyls server to correct our tests and completion.
Fixes #8828 
steff456
> PR: Disable parameter inclusion in the PyLS

- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_warnings.py
Reconnect the output of PyLS to the options under Source:
1. Show warning/error list
2. Previous warning/error
3. Next warning/error
Fixes #8985 
> PR: Reconnect warning menu with PyLS output

- spyder/widgets/status.py
> PR: Fix bold editor issues when setting bold status widgets

- spyder/plugins/history.py
- spyder/utils/external/lockfile.py
> PR: Avoid some permission errors at startup on Windows 

- README.md
This will make our Readme to display better on PyPi.
> PR: Add sponsors sections and remove relative links to images in Readme

- spyder/config/main.py
- spyder/plugins/explorer/plugin.py
- spyder/plugins/explorer/tests/test_explorer.py
- spyder/plugins/explorer/widgets.py
> PR: Add single click to open files on file and project explorer

- spyder/plugins/editor/confpage.py
**Before:**
----
**After:**
**Note**: All `Advanced Settings` are displayed in the last screenshot.
> PR: Reorganize preferences entry for the Editor

- spyder/widgets/arraybuilder.py
Lastest Master
---
PR
---
Related to #8068 
> PR: Apply dark theme to help icon of arraybuilder

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/editor/panels/linenumber.py
- spyder/plugins/editor/widgets/base.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/ipythonconsole/widgets/help.py
- spyder/widgets/calltip.py
- spyder/widgets/mixins.py
> PR: Use calltip widget to display calltips and tooltips

- spyder/config/main.py
- spyder/plugins/editor/lsp/manager.py
- spyder/preferences/languageserver.py
Properly set the `external` property for the lsp-server
Fixes #9195 
> PR: Add option to connect to external PyLS servers

- .github/PULL_REQUEST_TEMPLATE.md
Adds extra info on PR template
> PR: Ask for animations in pull request template

- spyder/plugins/editor/plugin.py
Display extension type icons in Recent Files menu and create entries as soon as file is opened in editor.
Fixes #9150 
Juanis2112
> PR: Display extension type icons and create entry as files are opened in "Open recent" menu

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/explorer/plugin.py
- spyder/plugins/findinfiles/plugin.py
- spyder/plugins/history/plugin.py
- spyder/plugins/projects/plugin.py
- spyder/plugins/pylint/plugin.py
Renamed plugins for a simpler, less crowded interface.
Fixes #9207 
Juanis2112
> PR: Rename plugins to have a simpler interface

- spyder/plugins/editor/widgets/editor.py
Fix the names of the update functions for the status bars in the Editor
Fixes #9236 
> PR: Fix update calls of status bars for new Editor windows

- spyder/widgets/calltip.py
This should fix the position issues of calltips @ccordoba12 !
Fixes #9287
> PR: Fix window flags for linux calltips

- spyder/plugins/editor/widgets/base.py
- spyder/plugins/editor/widgets/tests/test_warnings.py
> PR: Request a didChange when deleting a line in the Editor

- spyder/app/mainwindow.py
- spyder/preferences/general.py
> PR: Fix About dialog format on macOS

- spyder/app/mainwindow.py
> PR: Fix about dialog missing breaks

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py
- spyder/widgets/mixins.py
> PR: Fix hover/calltip for Python objects without signature

- spyder/plugins/editor/widgets/base.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_introspection.py
This PR solves the Issues below
Fixes #9257
Fixes #9267
Fixes #9268
Fixes #9269
Fixes #9273
impact27
> PR: Improvements to autocompletion

- spyder/app/tests/test_mainwindow.py
- spyder/widgets/fileswitcher.py
Fixes the file switcher search being broken as described in the linked issue. Also, adds some tests for it, improves the existing test and makes it work on all platforms (not just Linux as before).
Fixes #9332
I certify the above statement is true and correct: CAM-Gerlach
> PR: Fix fileswitcher search and add/improve tests

- spyder/plugins/editor/widgets/codeeditor.py
* [x ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))
Hide debugger panel for files that are not Python ones
Fixes #9208 
> PR: Hide debugger panel for files that are not Python ones

- spyder/plugins/editor/widgets/base.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/editor.py
- spyder/widgets/calltip.py
- spyder/widgets/mixins.py
> PR: Fix some hover and calltip issues

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/widgets/mixins.py
This is a regression of PR #9301.
> PR: Fix showing signatures in the IPython console after an open paren

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/preferences/languageserver.py
> PR: Reorganize LSP server editor dialog

- spyder/app/mainwindow.py
- spyder/plugins/console/plugin.py
- spyder/plugins/editor/lsp/client.py
- spyder/plugins/editor/lsp/manager.py
- spyder/widgets/reporterror.py
Show PyLS server errors on the main window using a Qt signal 
Improve the logging for LSP PyLS errors
Fixes #9211
> PR: Show PyLS server errors in Spyder's error report dialog

- spyder/plugins/editor/extensions/closebrackets.py
- spyder/plugins/editor/extensions/closequotes.py
- spyder/plugins/editor/widgets/tests/fixtures.py
- spyder/plugins/editor/widgets/tests/test_warnings.py
Add document_did_change to closequotes and closebrackets so the LSP will update.
The LSP would remove errors after typing brackets or quotes to correct them. Now it does.
Fixes #9323
> PR: Have LSP update after closequotes and closebrackets

- spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py
- spyder/widgets/mixins.py
Fixed problems with calltips methods using *args and **kwargs on the signature text
> PR: Add fix for calltips with args and kwargs

- spyder/plugins/editor/lsp/manager.py
Refactor the code in LSPManager to not imply that we are passing signals, only codeeditors.
Part of issue #7724
Steff456
> PR: Refactor code in LSPManager to not imply that we're still passing signals around

- MANIFEST.in
- setup.py
This is to avoid Linux distributions to ask us how to test Spyder because it's a very complex matter. They really need to trust that we're doing our job correctly.
> PR: Don't package our tests in our wheels and tarball

- spyder/plugins/plots/widgets/figurebrowser.py
- spyder/plugins/plots/widgets/tests/test_plots_widgets.py
> PR: Resize plot when Plots pane is resized and "Fits plots to window" is checked.

- spyder/plugins/projects/plugin.py
- spyder/plugins/projects/widgets/explorer.py
> PR: Connect project explorer to file explorer when single click to open is updated

- spyder/preferences/appearance.py
> PR: Minor layout improvement to the "Appearance" preference panel.

- spyder/widgets/calltip.py
Change to tooltip to prevent losing main window focus.
Fixes #9393 
bcolsen
> PR: Change calltip from tool to tooltip on linux

- spyder/config/main.py
- spyder/plugins/editor/confpage.py
- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/editor.py
- spyder/plugins/editor/widgets/tests/test_codeeditor.py
- spyder/utils/syntaxhighlighters.py
When a line is left, by pressing return, the mouse, or a direction arrow, if the line was empty except for spaces, remove the spaces.
Fixes #8564
impact27
> PR: Remove blanks if no content is added in a line and Enter is pressed to create a new line

- setup.py
> PR: Require pyqtwebengine only in Python 3

- spyder/plugins/editor/panels/scrollflag.py
> PR: Fix editor scrollflag area position and height under the dark theme

- spyder/plugins/editor/panels/classfunctiondropdown.py
- spyder/plugins/editor/panels/tests/test_classfunctiondropdown.py
- spyder/plugins/editor/utils/debugger.py
- spyder/plugins/editor/utils/editor.py
- spyder/plugins/editor/widgets/base.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/editor.py
- spyder/plugins/editor/widgets/tests/test_bookmarks.py
- spyder/plugins/editor/widgets/tests/test_breakpoints.py
- spyder/plugins/outlineexplorer/api.py
- spyder/plugins/outlineexplorer/editor.py
- spyder/plugins/outlineexplorer/plugin.py
- spyder/plugins/outlineexplorer/tests/test_outline_explorer.py
- spyder/plugins/outlineexplorer/tests/test_outline_explorer_editor.py
- spyder/plugins/outlineexplorer/tests/test_widgets.py
- spyder/plugins/outlineexplorer/widgets.py
- spyder/utils/syntaxhighlighters.py
- spyder/widgets/fileswitcher.py
- spyder/widgets/mixins.py
- Use blocks instead of lines number to identify a line, so spyder can find the line of the number changes.
- Change default cell name from '' to 'Unnamed cell'
- Ensure cell names are unique by appending a #N at the end if the cell name is not
- Update the outline explorer automatically
Fixes #9085
Fixes #7976
> PR: Use blocks to identify lines and add unique cell names

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_goto.py
- spyder/utils/syntaxhighlighters.py
> PR: Add uri hover and click detection for horthand github/bitbucket/gitlab issues

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/editor/plugin.py
- spyder/plugins/pylint/plugin.py
- spyder/plugins/pylint/widgets/pylintgui.py
> PR: Make Code Analysis pane follow the currently active file

- spyder/plugins/editor/widgets/editor.py
> PR: Fix editor tab switcher vertical position

- NOTICE.txt
- spyder/app/tests/test_mainwindow.py
- spyder/images/binary.svg
- spyder/images/binary_light.svg
- spyder/plugins/editor/plugin.py
- spyder/plugins/explorer/widgets.py
- spyder/utils/icon_manager.py
- spyder/widgets/fileswitcher.py
Added Icon for non-text files which extension is not recognized. 
Fixes #
Juanis2112
> PR: Add icon for binary files

- spyder/widgets/fileswitcher.py
Prevent that a call for the Symbol Switcher uses attributes for the File Switcher
Fixes #9474 
> PR: Add validation for Enter in the File Switcher

- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/tests/test_plugin.py
> PR: Fix Prev/Next cursor position for unsaved files

- spyder/widgets/mixins.py
> PR: Fix calltip size on linux

- spyder/plugins/editor/api/folding.py
- spyder/plugins/editor/utils/folding.py
- spyder/plugins/editor/widgets/tests/test_folding.py
Add cases for the identation folding using a regular expression
Fixes #9434 
> PR: Correct indentation folding cases

- spyder/plugins/editor/widgets/codeeditor.py
Calculate the line count taking into account collapsed code. This fixes the mapping for the debugger panel and new breakpoints can be created.
Fixes #9457
> PR: Fix line count when code is collapsed

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/help/widgets.py
> PR: Don't stay with selected text when it's found valid in the Help pane

- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/plugins/ipythonconsole/widgets/help.py
- spyder/widgets/mixins.py
Support documentation again in the calltips from the IPython Console:
Fixes #9529 
> PR: Add documentation element to calltips in the IPython Console

- spyder/plugins/editor/widgets/status.py
The idea is to  get the Git active branch, state, branches (plus tags) in the `VCSStatus ` with a worker so that the flow of the UI is not affected by this process.
I also added some logic to prevent outdated or duplicated calls to Git. 
I tried to follow the instruction in https://github.com/spyder-ide/spyder/issues/9497#issuecomment-500038143 for the implementation of the worker.
Fixes #9497
> PR: Add a worker to VCSStatus for getting Git active branch, state, branches (plus tags)

- spyder/plugins/ipythonconsole/widgets/shell.py
Enclosed kernel_env assignation in try except.
Fixes #9505 
Juanis2112
> PR: Enclose kernel_env assignment in a try/except

- spyder/config/main.py
- spyder/plugins/findinfiles/plugin.py
- spyder/plugins/findinfiles/widgets.py
> PR: Add and get "Search in" combo box index of the "Find" plugin from/to config

- spyder/plugins/ipythonconsole/plugin.py
- spyder/plugins/ipythonconsole/widgets/help.py
> PR: Add validation for empty signature while getting calltip in the IPython Console

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_goto.py
- spyder/utils/syntaxhighlighters.py
- spyder/utils/tests/test_vcs.py
- spyder/utils/vcs.py
> PR: URL awareness improvements

- spyder/plugins/editor/lsp/__init__.py
- spyder/plugins/editor/lsp/client.py
- spyder/plugins/editor/lsp/manager.py
- spyder/plugins/editor/widgets/codeeditor.py
Enable additional completion characters different from <kbd>.</kbd>, this enables further completions for LSP languages different from Python. i.e., Elixir, C/C++
Fixes #9596 
@andfoy
> PR: Enable other LSP completion characters

- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/projects/plugin.py
Fix some race conditions and LSP call ordering to prevent project LSP malfunction. This is also required for testing https://github.com/palantir/python-language-server/pull/601
Fixes #9628
@andfoy
> PR: Fix project workspace startup

- spyder/plugins/editor/lsp/manager.py
- spyder/preferences/configdialog.py
- spyder/preferences/languageserver.py
Fix the behaviour of toggling some checkboxes in the preferences for macOS
An untoggled checkbox
Change the state of the checkbox, hit apply and re-open preferences
Fixes #9511 
I certify the above statement is true and correct:Steff456
> PR: Fix checkboxes loading from config file in macOS

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_goto.py
> PR: Fix url awareness missing variable and add regression test

- spyder/plugins/editor/widgets/editor.py
This generated an error in CircleCI after PR #9504.
> PR: Fix EditorPluginExample test

- spyder/plugins/ipythonconsole.py
> PR: Catch error when pressing the link of a traceback in IPython console

- spyder/widgets/calltip.py
> PR: Catch an error when disconnecting a signal in calltip widget

- spyder/plugins/ipythonconsole.py
> PR: Catch error when loading kernel connection file

- spyder_breakpoints/widgets/breakpointsgui.py
- spyder_profiler/widgets/profilergui.py
- spyder_pylint/widgets/pylintgui.py
> PR: Remove usage of QTextCodec because it's not really needed

- requirements/conda.txt
- setup.py
- spyder/config/lsp.py
- spyder/plugins/editor/plugin.py
- spyder/plugins/explorer/widgets/fileassociations.py
This is needed until we fix the problem between Jedi 0.14 and the PyLS.
> PR: Demand PyLS 0.27+ and disable Pylint linting

- CONTRIBUTING.md
> PR: Update Contributing guide

- spyder/plugins/pylint/widgets/pylintgui.py
In the current master, the tree with code analysis issues collapses on selection:
After this PR, no collapse:
It does not solve #9564 but at least mitigates one of the issues mentioned there.
Oscar Gustafsson/oscargus
> PR: Avoid that code analysis tree collapses on selection

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/plugins/ipythonconsole/widgets/help.py
- spyder/widgets/mixins.py
Manage paragraphs wrapping instead of wrapping all the text for calltips, tooltips and hints
Fixes #9668
> PR: Fix formating of text/documentation in tooltips and calltips

- spyder/preferences/configdialog.py
- spyder/preferences/tests/conftest.py
- spyder/preferences/tests/test_config_dialog.py
> PR: Fixes content type attribute error for global config dialog

- spyder/utils/introspection/plugin_client.py
Fixed spyder's plugins listening to all hosts including external ones via tying them to localhost.
No new functions were added and no UI changes. 
(Wasn't a public issue)
I certify the above statement is true and correct: Houkime
> PR: Fix completion plugins listening to external hosts

- spyder/plugins/languageserver/client.py
Prevent LSP listen to external hosts
Fixes #9721 
> PR: Prevent LSP listen to external hosts

- spyder_profiler/widgets/profilergui.py
> PR: Avoid an error when profdata is None in Profiler

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/help.py
Backport fix implemented for the Help pane PR #9552  
Fixes #9757 
> PR: Backport PR #9552

- spyder/widgets/arraybuilder.py
- spyder/widgets/mixins.py
- spyder/widgets/tests/test_array_builder.py
> PR: Fix inf handling and generalize array builder for initial support on other languages

- spyder/app/mainwindow.py
- spyder/plugins/console/plugin.py
- spyder/widgets/reporterror.py
> PR: Remove CONF calls on widgets for issue reporter

- spyder/plugins/variableexplorer/widgets/namespacebrowser.py
> PR: Remove backslash of path for import_data on Windows

- spyder/app/mainwindow.py
- spyder/dependencies.py
- spyder/plugins/editor/plugin.py
- spyder/plugins/help/plugin.py
- spyder/plugins/ipythonconsole/plugin.py
- spyder/plugins/pylint/widgets/pylintgui.py
- spyder/plugins/variableexplorer/plugin.py
- spyder/utils/syntaxhighlighters.py
- spyder/widgets/dependencies.py
- spyder/widgets/status.py
- spyder/widgets/tests/test_dependencies.py
> PR: Add package name to dependencies

- spyder/plugins/editor/widgets/tests/conftest.py
- spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py
After PR #9704 those tests are failing too much.
> PR: Improve robustness of LSP tests

- spyder/plugins/help/utils/js/math_config.js
- spyder/plugins/help/utils/sphinxify.py
> PR: Improve rendering of equations with MathJax on Windows in the Help pane

- pytest.ini
- requirements/conda.txt
- requirements/tests.txt
- setup.py
- spyder/app/tests/test_mainwindow.py
- spyder/plugins/editor/widgets/tests/test_save.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/plugins/projects/widgets/tests/test_project_explorer.py
Now that Pytest is at version 5, I think it's time to support more recent versions of it.
> PR: Increase maximum Pytest supported version

- setup.py
> PR: Add rst files again to our tarballs

- spyder/app/mainwindow.py
- spyder/plugins/editor/widgets/status.py
- spyder/utils/icon_manager.py
- spyder/widgets/status.py
- spyder/widgets/tests/test_status.py
> PR: Add conda environment status widget

- spyder/widgets/browser.py
- spyder/widgets/tests/test_browser.py
Add a try catch to prevent the ValueError in tutorial
Fixes #9849
> PR: Fix control-click URL in tutorial ValueError

- spyder/config/main.py
- spyder/plugins/editor/confpage.py
- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/editor.py
- spyder/plugins/editor/widgets/tests/test_introspection.py
Completion calls are sent each time a alphabetic character is introduced, or if the last character after a backspace correspond to either an special completion character or to an alphabetic one.
Fixes #1914
@andfoy
> PR: Perform code completions on the fly

- spyder/plugins/variableexplorer/widgets/collectionseditor.py
- spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py
Set `sectionsClickable` to `True` in the custom header view of the Variable Explorer to enable sorting by column
Fixes #9835 
> PR: Fix sorting by column in the Variable Explorer

- spyder/pil_patch.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/editor.py
- spyder/plugins/ipythonconsole/widgets/figurebrowser.py
- spyder/plugins/variableexplorer/widgets/collectionseditor.py
- spyder/plugins/variableexplorer/widgets/dataframeeditor.py
- spyder/plugins/variableexplorer/widgets/objecteditor.py
- spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py
- spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py
- spyder/py3compat.py
- spyder/tests/test_dont_use.py
- spyder/utils/environ.py
- spyder/utils/external/github.py
Removed most of the deprecation warnings related to spyder (under Python 3.7).
I certify the above statement is true and correct: Oscar Gustafsson/@oscargus
> PR: Remove several deprecation warnings

- spyder/plugins/pylint/widgets/pylintgui.py
> PR: Inherit style in the output dialog from code analysis

- spyder/plugins/editor/widgets/codeeditor.py
Put default values for some keys in case the server doesn't contain them
Fixes #9755 
> PR: Prevent errors when LSP servers don't specify some settings

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_introspection.py
- spyder/plugins/editor/widgets/tests/test_warnings.py
- spyder/plugins/projects/tests/test_plugin.py
Disable automatic completions when whitespace or backspace characters are introduced, as they cause an unpleaseant experience and a one-size-fits-all solution is not clear.
Fixes #9871 
@andfoy
> PR: Disable automatic completions when spacebar or backspace are pressed

- spyder/config/base.py
> PR: Add new config files to reset

- requirements/conda.txt
- setup.py
- spyder/plugins/ipythonconsole/plugin.py
This version has several fixes for the dark theme.
> PR: Increase minimum required version of qtconsole to 4.5.2

- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/widgets/mixins.py
> PR: Fix wrapping calltip text for elements without signature in the IPython console

- spyder/plugins/editor/plugin.py
- spyder/preferences/configdialog.py
> PR: Fix preferences not being set

- spyder/config/manager.py
- spyder/config/tests/conftest.py
- spyder/config/tests/test_user.py
- spyder/config/user.py
Fixes issues found by @dalthviz on https://github.com/spyder-ide/spyder/pull/9894
> PR: Fix loading from old defaults and removing deprecated options

- spyder/preferences/shortcuts.py
Add a text label and placeholder for users to know they can customise their shortcuts. 
Fixes #9891 
> PR: Improve shortcuts entry in Preferences

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_warnings.py
> PR: Add last line warnings/errors to their menu list

- spyder/plugins/variableexplorer/widgets/objectexplorer/tests/test_objectexplorer.py
- spyder/plugins/variableexplorer/widgets/objectexplorer/tree_model.py
> PR: Improve error handling while getting objects attributes

- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/plugins/ipythonconsole/widgets/debugging.py
Avoid empty commands from ending up in history.
Get a white line when pressing up in debug mode.
Fixes #
> PR: Do not add empty messages to history

- spyder/plugins/variableexplorer/plugin.py
Correct PR #9343 error
Fixes #
> PR: Correct Pympler required version

- spyder/plugins/ipythonconsole/plugin.py
- spyder/plugins/ipythonconsole/widgets/kernelconnect.py
> PR: Connect Plots plugin to external Spyder kernels

- spyder/plugins/ipythonconsole/plugin.py
- spyder/plugins/ipythonconsole/widgets/shell.py
> PR: Allow setting the cwd through our toolbar for local external Spyder kernels

- spyder/plugins/ipythonconsole/widgets/debugging.py
Add syntax highlighter to debugger
Fixes #
impact27
> PR: Add syntax highlighting to the debugger

- continuous_integration/azure/install.sh
- continuous_integration/travis/install.sh
- spyder/app/tests/test_mainwindow.py
- spyder/plugins/variableexplorer/widgets/dataframeeditor.py
> PR: Resize dataframeeditor header to contents

- spyder/plugins/variableexplorer/widgets/collectionseditor.py
- spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py
- spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py
Fix sorting when using non text indexes (numbers for example)
Fixes #9973 
Fixes #9516 
> PR: Don't convert values to text strings and fix sorting issues in the Variable Explorer

- continuous_integration/circle/modules_test.sh
@dalthviz, I know you fixed this in PR #9897, but we need this in master so that other PRs stop failing.
> PR: Skip new switcher test in CircleCI because it gives a segfault

- azure-pipelines.yml
- spyder/app/tests/test_mainwindow.py
Those tests were failing after PR spyder-ide/spyder-kernels#131.
> PR: Fix a couple of main window debugging tests

- spyder/plugins/editor/plugin.py
- spyder/plugins/ipythonconsole/plugin.py
- spyder/preferences/runconfig.py
This allows running a file in the current namespace of the IPython console. This is necessary to work around the new default of running files in a new namespace and appending the results into the current console. See https://github.com/spyder-ide/spyder-kernels/pull/131
Related to #4180 
> PR: Add an option to run a file in the console's current namespace

- spyder/plugins/editor/widgets/tests/test_codeeditor_1.py
- spyder/widgets/mixins.py
> PR: Escape regex characters from parameters while processing a signature

- spyder/plugins/ipythonconsole/widgets/client.py
Decreases the shutdown time from 14 seconds to < 1s
Fixes #
> PR: Speedup of console shutdown time

- spyder/config/appearance.py
- spyder/config/main.py
I was never satisfied with the current color because it doesn't have enough contrast with respect to the background one. However, I think this new color has.
**Before**
**After**
@goanpeca, what do you think?
> PR: Change the current cell color of the Spyder Dark theme

- spyder/app/mainwindow.py
- spyder/app/start.py
- spyder/config/base.py
- spyder/preferences/general.py
Changes needed for #10054 to work
Fixes #
> PR: Improve check to see if Spyder is running in a macOS app

- spyder/plugins/completion/kite/client.py
- spyder/plugins/completion/kite/plugin.py
- spyder/plugins/completion/kite/providers/document.py
- spyder/py3compat.py
> PR: Check if responses are not None in Kite plugin handlers

- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/tests/test_plugin.py
- spyder/plugins/editor/utils/autosave.py
- spyder/plugins/editor/utils/tests/test_autosave.py
If the user renames a file in the files or project pane, then this is propagated to the editor. This PR updates the autosave information as well.
Fixes #10038
Jitse Niesen
> PR: Update autosave information after file is renamed

- spyder/utils/syntaxhighlighters.py
Prevent the disappearance of background decorations due to syntax highlighting
Fixes #9950 
@andfoy
> PR: Prevent background overrides to extra decorations

- spyder/widgets/reporterror.py
- spyder/widgets/tests/test_reporterror.py
> PR: Fix Del key on report error dialog

- spyder/widgets/reporterror.py
> PR: Set error dialog as non-modal

- spyder/preferences/configdialog.py
> PR: Revert windows on top for config dialog

- spyder/app/tests/test_mainwindow.py
- spyder/config/manager.py
- spyder/config/user.py
- spyder/plugins/completion/languageserver/confpage.py
- spyder/plugins/editor/plugin.py
- spyder/preferences/configdialog.py
This fixes the UI problems, however, the actual action is not working and I opened #10144 to track it.
Fixes #10139
> PR: Fix PyLS actions triggering in Preferences

- spyder/plugins/ipythonconsole/widgets/shell.py
Change foreground color of Sympy to match current color scheme
Fixes #3798 
Depends on spyder-ide/spyder-kernels#137
> PR: Handle Sympy foreground color setting following a color scheme change

- spyder/plugins/ipythonconsole/plugin.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/plugins/ipythonconsole/widgets/shell.py
- spyder/plugins/workingdirectory/tests/test_workingdirectory.py
They were not showing correctly for Windows on external interpreters.
> PR: Fix banners for the IPython console

- spyder/plugins/ipythonconsole/widgets/shell.py
Revert changes made in https://github.com/spyder-ide/spyder/pull/4914 as underlying error is now corrected.
Fixes #
> PR: Remove adding second interpreter prompt after error

- spyder/api/plugins.py
- spyder/config/manager.py
- spyder/config/user.py
- spyder/plugins/base.py
- spyder/plugins/breakpoints/plugin.py
- spyder/plugins/completion/languageserver/plugin.py
- spyder/plugins/console/plugin.py
- spyder/plugins/editor/plugin.py
- spyder/plugins/explorer/plugin.py
- spyder/plugins/findinfiles/plugin.py
- spyder/plugins/help/plugin.py
- spyder/plugins/history/plugin.py
- spyder/plugins/ipythonconsole/plugin.py
- spyder/plugins/onlinehelp/plugin.py
- spyder/plugins/outlineexplorer/plugin.py
- spyder/plugins/plots/plugin.py
- spyder/plugins/profiler/plugin.py
- spyder/plugins/projects/plugin.py
- spyder/plugins/pylint/plugin.py
- spyder/plugins/variableexplorer/plugin.py
- spyder/plugins/workingdirectory/plugin.py
The plugin API now includes CONF_FILE, CONF_DEFAULTS, CONF_NAME_MAP
```python
class Explorer(SpyderPluginWidget):
    """File and Directories Explorer DockWidget."""
    CONF_SECTION = 'explorer'
    CONFIGWIDGET_CLASS = ExplorerConfigPage
    CONF_FILE = True
    CONF_DEFAULTS = [            ('explorer',
             {
              'enable': True,
              'wrap': True,
              'name_filters': [],
              'show_hidden': True,
              'show_all': True,
              'show_icontext': False,
              'single_click_to_open': False,
              }),]
```
This enables the use of a dedicated configuration file per plugin.
This is by default `True` so external plugins default to use their own configuration file.
The location of storage is (for the example):
Fixes # …
> PR: Add class variables to set configuration options for plugins

- spyder/plugins/completion/kite/client.py
Verify that the response is not None before passing it to the converter function.
Fixes #10159 
> PR: Fix error when response is None in Kite client

- spyder/plugins/completion/languageserver/client.py
This PR allows to display completion responses from other sources when LSP raises an exception.
Fixes #
@andfoy
> PR: Gather responses from other completion sources when LSP raises an error

- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/plugins/ipythonconsole/widgets/control.py
- spyder/plugins/ipythonconsole/widgets/debugging.py
- spyder/widgets/mixins.py
Fix issues with multiline statements in pdb history.
Fixes #
> PR: Fix multiline support for pdb history

- spyder/app/mainwindow.py
- spyder/dependencies.py
This has been bugging me for a long time.
Before
After
> PR: Fix formatting of missing dependencies dialog

- spyder/plugins/completion/languageserver/client.py
This was broken after PR #10164.
> PR: Fix connection to an external LSP server

- spyder/plugins/completion/kite/providers/document.py
Validate there are sigantures to retrieve
Fixes #10203 
> PR: Fix signature processing when no signature is retrieved with Kite

- spyder/config/main.py
- spyder/plugins/completion/languageserver/confpage.py
Add a checkbox to the preferences to ensure that the user wants to modify the advanced options under the completions and linting tab
> PR: Add checkbox to verify changes in advanced options of LSP preferences

- setup.py
Add minimal version requirement for pyxdg package in setup.py file
Fixes #10214 
> PR: Add minimal requirement for pyxdg to 0.26

- spyder/app/mainwindow.py
- spyder/plugins/completion/languageserver/client.py
This PR prevents multiple running instances of Spyder to overwrite LSP log files, it also deletes previous existing instance logs on the next Spyder startup.
Fixes #
@andfoy
> PR: Create LSP logs for all active instances of Spyder

- .github/FUNDING.yml
Add the configuration file for generating the Github _support_ button at the top of the repo
Fixes #10118
> PR: Add open collective funding button

- spyder/plugins/completion/languageserver/confpage.py
- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/editor.py
> PR: Always enable hovers on the PyLS

- spyder/plugins/plots/widgets/figurebrowser.py
The highlighted figure is not properly shown in the Plot thumbnail
in the dark mode. Use red color in the dark mode and increase frame outline thickness in both modes.
Dark mode before the change
Light mode before the change
Dark mode after the change `#148CD2`  `2px`
light mode after the change `2px`
Fixes #10255
@Khalilsqu 
> PR: Better highlight selected figure in thumbnail.

- spyder/plugins/completion/languageserver/confpage.py
- spyder/plugins/editor/confpage.py
- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/widgets/completion.py
> PR: Move some options from editor to LSP Preferences page

- spyder/preferences/general.py
- spyder/preferences/tests/test_config_dialog.py
> PR: Fix regression and add test for language selection on preferences

- NOTICE.txt
- spyder/images/kite_dark.svg
- spyder/images/kite_light.svg
- spyder/plugins/completion/fallback/actor.py
- spyder/plugins/completion/kite/providers/document.py
- spyder/plugins/completion/languageserver/providers/document.py
- spyder/plugins/editor/widgets/completion.py
- spyder/utils/icon_manager.py
> PR: Add branding for Kite completion items

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/completion/kite/utils/tests/test_install.py
- spyder/plugins/editor/widgets/tests/test_introspection.py
- spyder/plugins/ipythonconsole/comms/tests/test_runcell.py
A couple of tests related to the Help pane started to hang or fail for no apparent reason on Windows.
> PR: Fix tests on Windows

- spyder/app/tests/test_mainwindow.py
- spyder/utils/switcher.py
Fix test_switcher taking into account path shortening when testing locally
Fixes #10308
> PR: Fix test and path shortening for the switcher

- spyder/plugins/completion/kite/providers/document.py
A `provider` value was missing for completions of code snippets. Thanks to @ok97465 for letting us know about this.
Fixes #
> PR: Add branding for code snippets completions

- spyder/app/tests/test_mainwindow.py
- spyder/preferences/appearance.py
- spyder/preferences/configdialog.py
> PR: Fix regression for set_font method

- spyder/plugins/editor/plugin.py
- spyder/plugins/editor/widgets/editor.py
> PR: Apply autocompletion options at startup

- spyder/plugins/completion/kite/providers/document.py
Add an if statement for checking that the arguments in the signature are not None
Fixes #10352 
> PR: Fix Kite error when args in signature is None

- spyder/app/tests/test_mainwindow.py
Try to have a more stable test_c_and_n_pdb_commands
Fixes #
> PR: Update test_c_and_n_pdb_commands test

- spyder/plugins/completion/languageserver/providers/document.py
This PR prevents https://github.com/palantir/python-language-server/pull/623 to break compatibility with Spyder
Fixes #
@andfoy
> PR: Improve LSP support for MarkupString[] for hover requests

- spyder/utils/syntaxhighlighters.py
Update regex for 'as' keyword highlighting to prevent selected alias to be taken as a keyword too:
Fixes #10351
> PR: Update highlighter regex for 'as' keyword

- setup.py
This is needed for Kite's call-to-action
Fixes #10424.
> PR: Add bloom files to our tarballs

- requirements/conda.txt
- setup.py
- spyder/plugins/completion/kite/utils/tests/test_install.py
This is required to add several new features to our debugger.
> PR: Increase minimal required version of spyder-kernels to 1.6

- spyder/plugins/projects/projecttypes/__init__.py
- spyder/plugins/projects/tests/test_plugin.py
Handle recent files saving in cases where paths doesn't have a relative path to the project root path
Fixes #10045
> PR: Handle paths for recent files on a different mount than the project root path

- spyder/utils/qthelpers.py
> PR: Skip opening launch script in macOS application

- spyder/plugins/completion/fallback/actor.py
- spyder/plugins/completion/kite/__init__.py
- spyder/plugins/completion/kite/providers/document.py
- spyder/plugins/completion/languageserver/providers/document.py
- spyder/plugins/completion/languageserver/providers/utils.py
- spyder/plugins/editor/widgets/codeeditor.py
> PR: Fix encoding issues when using Python 2

- spyder/app/tests/conftest.py
- spyder/app/tests/test_mainwindow.py
Reuse same window for all test_mainwindow tests
Fixes #
> PR: Use a single main window instance to run all its tests

- spyder/plugins/completion/kite/utils/tests/test_install.py
> PR: Update kite test

- requirements/tests.txt
- runtests.py
- setup.py
> PR: Use pytest-faulthandler to debug segmentation faults in our tests

- spyder/app/tests/test_mainwindow.py
> PR: Cleanup test_mainwindow tests

- spyder/images/kite_dark.svg
- spyder/images/kite_light.svg
- spyder/utils/icon_manager.py
- spyder/widgets/status.py
The kite logo was being scaled as a pixmap and then passed to the icon which would distrot the icon for scale factor that did not adjust to specific ratios. I edited the Kite logo images (in SVG) so that the image includes a padding, like most of the Font Awesome icons. I based the size to 16 and left a padding of 1, which results in a kite logo of 14px (effective) height. This removes the need to pass a custom scale factor, and since the icon is used as is, it does not get distorted.
As an extra for this PR I removed the padding o the layout between icons and text which results in a better UI and reduced status widgets total width.
Fixes #10442  …
> PF: Fix kite logo for OSX

- spyder/app/mainwindow.py
Clear the logs menu prior to adding the logs to avoid creating duplicates.
> PR: Clear logs menu to avoid creating duplicates

- spyder/plugins/completion/kite/utils/status.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/ipythonconsole/tests/conftest.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
> PR: Print shell content upon failure and try to correct segfaults in IPython console tests

- spyder/plugins/projects/utils/watcher.py
> PR: Handle inotify error on Linux

- spyder/app/tests/test_mainwindow.py
Print the info_page content if it is not blank. Indeed this contains errors while the kernel is starting up, which is useful to debug the tests.
Fixes #
> PR: Print info_page content in the IPython console tests

- spyder/plugins/outlineexplorer/widgets.py
.line() can return None, so handle it correctly.
Fixes #
> PR: Handle case where a line is destroyed in outline explorer

- spyder/plugins/completion/kite/__init__.py
- spyder/plugins/completion/languageserver/transport/common/producer.py
- spyder/plugins/onlinehelp/widgets.py
This avoids issues with corrupted `/etc/hosts` files. Therefore, it helps to mitigate the problem found in issue #10209.
> PR: Replace usage of localhost for 127.0.0.1

- spyder/widgets/mixins.py
Takes into account the document margin
Fixes #10131 
> PR: Fix tooltip for hints position

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/projects/plugin.py
Add missing parameter `console_namespace` to run a file from the Project Explorer. Add a test for the action.
Fixes #10590 
> PR: Fix 'run file' project explorer action and add test for it

- spyder/plugins/completion/kite/plugin.py
Add validation to prevent the request for the onboarding file
Fixes #10609 
> PR: Prevent reload of kite onboarding file

- .travis.yml
- azure-pipelines.yml
- conftest.py
- runtests.py
- spyder/app/tests/test_mainwindow.py
- spyder/plugins/editor/widgets/tests/test_editor.py
- spyder/plugins/explorer/widgets/explorer.py
- spyder/plugins/ipythonconsole/comms/tests/test_comms.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
This should cut in half the time it takes to run our tests in those CIs.
> PR: Split slow and fast tests in different slots on Travis and Azure

- spyder/config/main.py
- spyder/plugins/findinfiles/plugin.py
- spyder/plugins/findinfiles/tests/test_widgets.py
- spyder/plugins/findinfiles/widgets.py
- The find in files now adds the files in batches that increase over time in power of 2
2^1, 2^2 etc.... up to a max of 9 (512 items per load batch)
- The maximum is now configurable, default is 1000
- The stop button and search button now act as "one single button"
- Enter now toggles between searching and stoping (instead of always restart a search.
- The regex section ins hidden by default
Fixes #10264
> PR: Add results in batches and limit results on Find pane to a maximum

- spyder/plugins/editor/widgets/codeeditor.py
Enable Spyder to send completion requests after a bracket character
Fixes #10275 
@andfoy
> PR: Trigger completions after braces

- spyder/plugins/projects/utils/watcher.py
Correctly check string exception message
Fixes #10653
> PR: Fix handling of inotify error

- spyder/plugins/editor/utils/autosave.py
- spyder/plugins/editor/widgets/recover.py
Fixes #9125
Juanis2112
dalthviz
> PR: Add scrollbar to autosave dialog

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/editor/widgets/editor.py
> PR: Fix Fileswitcher for 'EditorStack' instances #2

- spyder/plugins/editor/extensions/snippets.py
Add verification if the snippet node is valid after 'enter' is pressed.
Fixes #10650 
> PR: Fix completion of function/method definition in Kite

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
Fix frequent segmentation faults in macOS tests (eg: https://dev.azure.com/spyder-ide/spyder/_build/results?buildId=4457)
Fixes #
> PR: Fix segmentation fault in test_ipythonconsole.py

- spyder/app/mainwindow.py
- spyder/widgets/pathmanager.py
- spyder/widgets/tests/test_pathmanager.py
> PR: Reenable path manager sync on windows

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/variableexplorer/widgets/collectionseditor.py
- spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py
> PR: Map indexes from proxy model when removing variables

- spyder/plugins/editor/widgets/codeeditor.py
> PR: Add delay to dot completion logic

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/completion.py
- spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py
- spyder/widgets/mixins.py
> PR: Fix hint for completion and title of help on click

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/variableexplorer/widgets/collectionseditor.py
- spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py
Map indexes from `proxy_model` to `source_model` to prevent doing actions over incorrect variables
Fixes #10735 
> PR: Map indexes from proxy model to source model for Variable Explorer actions

- spyder/plugins/editor/widgets/completion.py
- spyder/plugins/editor/widgets/tests/test_introspection.py
> PR: Fix underscore completions

- spyder/utils/programs.py
- spyder/utils/tests/test_programs.py
> PR: Fix logic for removing extra quotes on windows path applications

- spyder/utils/programs.py
> PR: Fix opening files with spaces

- spyder/widgets/findreplace.py
The segmentation fault in #10521 is happening when `find_next` is called from `replace_find` but not when it is called directly. The main difference I can see between these two situations is that the call takes place between `cursor.beginEditBlock()`and `cursor.endEditBlock()`. Therefore I think that a `paintEvent` taking place while editing a block might lead to a segfault.
Fixes #10521
> PR: Fix segfault in replace by calling setFocus outside of EditBlock

- azure-pipelines.yml
- spyder/app/tests/test_mainwindow.py
- spyder/plugins/completion/kite/parsing/__init__.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/completion.py
- spyder/plugins/editor/widgets/tests/conftest.py
- spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py
- spyder/plugins/editor/widgets/tests/test_introspection.py
- spyder/plugins/editor/widgets/tests/test_warnings.py
> PR: Fix hover regression and improve tests for it

- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- spyder/widgets/mixins.py
> PR: Fix show_calltip for the IPython console

- spyder/plugins/ipythonconsole/widgets/shell.py
> PR: Don't switch tabs in runfile or runcell

- spyder/locale/de/LC_MESSAGES/spyder.po
- spyder/locale/es/LC_MESSAGES/spyder.po
- spyder/locale/fr/LC_MESSAGES/spyder.po
- spyder/locale/hu/LC_MESSAGES/spyder.po
- spyder/locale/ja/LC_MESSAGES/spyder.po
- spyder/locale/pt_BR/LC_MESSAGES/spyder.po
- spyder/locale/ru/LC_MESSAGES/spyder.po
- spyder/locale/spyder.pot
- spyder/locale/zh_CN/LC_MESSAGES/spyder.po
- spyder/preferences/runconfig.py
> PR: Remove non-ascii character in a translation string

- spyder/plugins/editor/widgets/codeeditor.py
> PR: Show indent guides for splited editor panels

- spyder/config/base.py
- spyder/preferences/general.py
They will be re-enabled when they're are updated again.
Fixes #10672.
Closes #10809.
Closes #10810.
> PR: Disable Hungarian and Russian translations

- spyder/plugins/completion/languageserver/client.py
This will prevent us being flooded by errors that we can't solve directly (i.e. Jedi errors), but still give users a chance to report those errors if they break the PyLS completely.
> PR: Show PyLS errors only in debug or development modes

- spyder/plugins/editor/widgets/codeeditor.py
> PR: Hide tooltip widget with mouse click and keypress

- spyder/app/mainwindow.py
> PR: Correctly show several missing deps in our dialog

- spyder/plugins/editor/widgets/codeeditor.py
This was introduced by PR #10855.
> PR: Fix simple error in a test widget

- spyder/plugins/editor/utils/languages.py
- spyder/plugins/editor/widgets/codeeditor.py
- spyder/utils/syntaxhighlighters.py
Fixes #7998
and understand I am releasing the same under Spyder's MIT (Expat) lic@goanpeca e.
> PR: Fix showing spaces for generic files

- spyder/app/mainwindow.py
- spyder/plugins/help/plugin.py
> PR: Fix help intro message with correct shortcut and update if shortcut changes

- crowdin.yml
> PR: Add crowdin config

- README.md
> PR: Create sections for project and build status in README.md

- spyder/plugins/variableexplorer/widgets/arrayeditor.py
- spyder/plugins/variableexplorer/widgets/tests/test_arrayeditor.py
> PR: Check if arrays have inf values and add test

- spyder/utils/qthelpers.py
> PR: Unquote url properly for drag and drop

- spyder/plugins/ipythonconsole/widgets/figurebrowser.py
> PR: Fix extra blank line added to qtconsole when plotting

- spyder/widgets/github/backend.py
> PR: Do not import keyring when running through SSH

- spyder/plugins/editor/utils/switcher.py
- spyder/utils/stringmatching.py
- spyder/widgets/switcher.py
- spyder/widgets/tests/test_switcher.py
Handle encoding issue in the Switcher by using `to_text_to_string` and marking templates as unicode
Fixes #7362 
> PR: Handle non-ascii text in the switcher

- spyder/plugins/editor/utils/editor.py
- spyder/plugins/editor/widgets/codeeditor.py
> PR: Fix marking linting occurrences

- spyder/plugins/editor/widgets/codeeditor.py
> PR: Call data instead of block to fix AttributeError in the editor

- spyder/dependencies.py
This PR also reorganizes our list of dependencies in alphabetical order.
Fixes #11047.
> PR: Add Jedi as a new dependency for users to be aware of its right version

- spyder/plugins/editor/panels/codefolding.py
> PR: Catch KeyError when trying to draw a folding region

- spyder/plugins/variableexplorer/widgets/dataframeeditor.py
> PR: Set time limit to calculate columns size hint for Dataframe Editor

- spyder/plugins/variableexplorer/widgets/dataframeeditor.py
> PR: Copy index and headers of dataframe

- spyder/plugins/editor/widgets/editor.py
> PR: Keep finfo.newly_created state when cancelling save_as

- spyder/plugins/editor/widgets/base.py
- spyder/plugins/editor/widgets/tests/test_editor.py
As discussed in https://github.com/spyder-ide/spyder/pull/11089, there is a visual glitch when duplicating current line or selection.
This PR proposes a workaround to avoid this glitch. @ccordoba12 feel free to close this PR if you don't like what I'm proposing.
Also I would like to add a test to cover the copy and duplicate features. Should I do this here or in another PR?
Without the workaround:
With the workaround:
> PR: Workaround to avoid a glitch when duplicating current line or text selection

- spyder/plugins/variableexplorer/widgets/arrayeditor.py
- spyder/plugins/variableexplorer/widgets/tests/test_arrayeditor.py
> PR: Fix updates with complex values on variable explorer

- spyder/plugins/plots/widgets/figurebrowser.py
> PR: Fix simple typo in docstring

- binder/environment.yml
- requirements/tests.txt
- spyder/utils/sourcecode.py
- spyder/widgets/findreplace.py
- spyder/widgets/tests/test_findreplace.py
> PR: Fix find/replace widget for multiline regex

- spyder/plugins/console/tests/__init__.py
- spyder/plugins/console/tests/test_plugin.py
- spyder/plugins/console/widgets/console.py
- spyder/plugins/console/widgets/shell.py
- spyder/plugins/editor/widgets/base.py
This PR also adds some simple tests for the internal console.
Fixes #10893.
> PR: Fix completions in the internal console and prevent hard crash

- spyder/app/tests/test_mainwindow.py
- spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
> PR: Skip some failing tests for the IPython console

- spyder/app/tests/test_mainwindow.py
- spyder/config/manager.py
- spyder/preferences/shortcuts.py
> PR: Fix shortcut reset error and add test

- spyder/plugins/variableexplorer/widgets/dataframeeditor.py
- spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py
Use formatted values for dataframe indexes and headers
A preview with numpy datetime64:
Fixes #11129 
> PR: Use Pandas tolist to get formatted indexes and headers in the DataFrame editor

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_codeeditor.py
Fixes #11148
I certify the above statement is true and correct: impact27
> PR: Fix infinite loop when commenting first block

- spyder/widgets/findreplace.py
> PR: Do not show replace widget when it is not enabled

- spyder/plugins/completion/languageserver/client.py
> PR: Fix freeze when LSP client queue is full

- spyder/widgets/calltip.py
Handle window blocked state to prevent showing the tooltip and bloking other actions
Fixes #11244 
> PR: Hide tooltip when the window is blocked

- spyder/preferences/general.py
Add a validation for the custom scale factor preference (it must be at least `1.0` for any given per screen value)
A preview:
Fixes #11240 
> PR: Validate custom scale factor not being below 1.0

- spyder/plugins/editor/panels/codefolding.py
> PR: Catch KeyError when trying to highlight folding region

- spyder/plugins/editor/extensions/closebrackets.py
- spyder/plugins/editor/extensions/tests/test_closebrackets.py
> PR: Change unmatched brackets in line validation

- spyder/plugins/editor/widgets/editor.py
- spyder/plugins/help/plugin.py
- spyder/plugins/help/utils/sphinxify.py
- spyder/plugins/help/utils/static/css/default.css
- spyder/plugins/help/utils/static/dark_css/default.css
- spyder/plugins/help/utils/static/dark_css/pygments.css
- spyder/plugins/help/utils/templates/loading.html
- spyder/widgets/mixins.py
- spyder/widgets/tests/test_mixins.py
* Change `Note` section style:
* Change code snippets style;
* Add loading page:
* Table style:
Fixes #11267 
> PR: Improvements to the Help pane (style, loading page and some other issues)

- spyder/app/mainwindow.py
Handle OS scale change by restarting Spyder. Inform users about the auto high DPI scale option.
A preview:
Fixes #6181 
> PR: Add a restart message when a monitor scale change is detected

- spyder/config/main.py
- spyder/plugins/projects/plugin.py
- spyder/plugins/projects/tests/test_plugin.py
Make adjustable the maximum number of Recent Projects to fix issue #10640 
Fixes #10640 
Juanis2112
> PR: Make adjustable the maximum number of recent projects

- spyder/plugins/ipythonconsole/widgets/client.py
- spyder/plugins/ipythonconsole/widgets/shell.py
- spyder/plugins/onlinehelp/tests/test_pydocgui.py
Wait for shutdown but in a thread to avoid blocking.
Fixes https://github.com/spyder-ide/spyder-kernels/issues/197
> PR: Finalise kernel shutdown in a thread

- spyder/app/tests/script_unicode.py
- spyder/app/tests/test_mainwindow.py
- spyder/widgets/mixins.py
Use function to get current word instead of regex to inspect current object from the Console
Fixes #7699 
> PR: Get current word to inspect current object from the IPython console

- spyder/api/plugins.py
- spyder/app/mainwindow.py
- spyder/dependencies.py
- spyder/widgets/dependencies.py
- spyder/widgets/tests/test_dependencies.py
```
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.3.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.2.2 (OK)
diff_match_patch >=20181111   :  20181111 (OK)
intervaltree                  :  None (OK)
IPython >=4.0                 :  7.9.0 (OK)
jedi =0.14.1                  :  0.15.1 (NOK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  0.9.1 (OK)
pexpect >=4.4.0               :  4.7.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=0.3                  :  5.6.7 (OK)
pygments >=2.0                :  2.5.2 (OK)
pylint >=0.25                 :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0         :  0.31.1 (NOK)
qdarkstyle >=2.7              :  2.7 (OK)
qtawesome >=0.5.7             :  0.6.0 (OK) …
```
> PR: Include plugins in dependencies dialog

- spyder/plugins/editor/widgets/tests/test_goto.py
- spyder/utils/syntaxhighlighters.py
> PR: Fix infinite loop with issue shorthand within comments

- spyder/app/mainwindow.py
- spyder/plugins/onlinehelp/tests/test_pydocgui.py
> PR: Make scale restart optional

- spyder/preferences/appearance.py
This minor change enables the third party plugins to receive the signal when Spyder's theme is changed.
Fixes #10911 
> PR: Add support for third party plugins to react to color scheme changes

- spyder/utils/snippets/lexer.py
This PR enables underscore prefixed snippets to be introduced correctly:
Fixes #11399
> PR: Prevent underscore prefixed snippets to be omitted

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/tests/test_autoindent.py
- spyder/plugins/editor/widgets/tests/test_codeeditor.py
Fix indentation:
- after a comment
- when doing backspace with a blank line
- search a maximum of two lines up when looking for indentation
Fixes #11128
> PR: Fix several indentation cases

- spyder/plugins/completion/plugin.py
If multiple requests occur before displaying a widget, only the last request is displayed.
Fixes #10798 
> PR: Display the latest result of requested completions

- spyder/plugins/editor/confpage.py
- spyder/plugins/editor/extensions/docstring.py
- spyder/plugins/editor/extensions/tests/test_docstring.py
Add docstring of sphinx format.
Fixes #11435 
> PR: Add automatic introduction of docstrings in Sphinx format

- CONTRIBUTING.md
This was necessary to make the formatting the same across the entire document (it was modified in PR #11350).
> PR: Improve formatting of Contributing guide

- spyder/plugins/editor/widgets/codeeditor.py
- spyder/plugins/editor/widgets/editor.py
Add some logging for the Editor's `dragEnterEvents`
Part of #11447 
> PR: Add debug logger calls for dragEnterEvent in the Editor
