spyderlib/tour.py

Fix issue 2204 in tour - blocking file and edit menu

---

spyderlib/widgets/tabs.py

"Ctrl+Tab cycles through tabs, while Ctrl+PageUp/PageDown stops at last/first tab. This patch changes the behavior: when Ctrl+PageUp is pressed on the last tab, it moves to the first tab, and vice versa."  Closes #1749.

Allow tab cycling with ctrl+pageup/down

---

spyderlib/userconfig.py

This change is related to issue 2081 for the case when user home directory contains non-ascii characters and Spyder reads/writes INI file into that directory.
This change does NOT resolve the issue 2081 (there are cases with non-ascii working directory and plus some dependencies out of Spyder codebase).
This change seems failsafe.
Fixes #2081

Open configuration file with utf-8 encoding on Windows and Python 2 

---

spyderlib/widgets/projectexplorer.py

Added catch of AttributeError caused by try to read old format on loading .spyderproject files when actually is loading new format project file.
fixes #1845

catch a reason to crash on startup

---

spyderlib/spyder.py

Fixes #2289. The setting works, but I'm not sure if it's in the right place. Strangely, `running_in_mac_app()` returns `False` on my machine.

Hide menu icons on Mac OS X

---

.travis.yml
bootstrap.py
continuous_integration/travis_install.sh
spyderlib/spyder.py

Add travis support for basic start of spyder

---

spyderlib/widgets/sourcecode/codeeditor.py

The context menu editor action for run selection or current line was disabled in case of empty selection, which is not the expected behavior since it runs the current line when the selection is empty.

Run selection enabled even with empty selection

---

spyderlib/plugins/externalconsole.py
spyderlib/qt/__init__.py

because if the support for a newer and better version of a library is there, why wouldn’t we want to use it?

Add PyQt5 to Qt binding choices for Python consoles

---

spyderlib/widgets/externalshell/baseshell.py

Fixing crashes on very long output being written to the console in a short time.
Fixes #2251

Try to avoid crashes on long output into Python console in a short time

---

spyderlib/plugins/inspector.py

OS X uses `Cmd+I` as the default keyboard shortcut for the Object Inspector.  This updates the help string to avoid confusion.
Fixes #2317

Fix Object inspector message for OSX

---

spyderlib/widgets/sourcecode/base.py

Make completions scroll to top of list

---

spyderlib/utils/introspection/plugin_manager.py

Fixes error in introspection found in #2313, due to `CodeInfo` using `None` as the default `obj` token.

Use empty string instead of None for fallback.  Fixes #2313.

---

spyderlib/plugins/runconfig.py

This extends the global Run config to match the file-level one.
Results in:

Fill in missing global run config options

---

spyderlib/spyder.py

I was getting the following traceback on shutdown, which is now avoided:
```python
*** End of MainWindow setup ***
Exception in thread Thread-3:
File "/Users/silvester/anaconda/lib/python3.4/threading.py", line 920, in _bootstrap_inner
self.run()
File "/Users/silvester/anaconda/lib/python3.4/threading.py", line 868, in run
self._target(*self._args, **self._kwargs)
File "/Users/silvester/workspace/spyder/spyderlib/spyder.py", line 2641, in start_open_files_server
req, dummy = self.open_files_server.accept()
File "/Users/silvester/anaconda/lib/python3.4/socket.py", line 187, in accept
fd, addr = self._accept()
ConnectionAbortedError: [Errno 53] Software caused connection abort
```

Handle a connection abort error on shutdown

---

bootstrap.py
spyderlib/config.py
spyderlib/restart_app.py
spyderlib/spyder.py
spyderlib/spyder_restart.py
spyderlib/start_app.py

Fixes #2306
Add a restart method. Used the restart image as the ones used by the consoles. The shortcut for restarting is set as `Shift+Alt+R`.

Fixes #2306: Add a restart method

---

spyderlib/config.py
spyderlib/plugins/configdialog.py
spyderlib/spyder.py
spyderlib/utils/programs.py
spyderlib/workers/updates.py

Fixes #2307 
(Note from @ccordoba12: Please leave *Fixes* instead of *Implements* because that way when I merge the PR, GH will automatically close the corresponding issue. If you don't like *Fixes*, [here](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) are the other words you can use to make this happen)
Add a method to check for updates querying the Github API, using a QThread and Worker to avoid blocking the GUI.
The method is called on startup if running from installed version and will only display a message if there is an update. If running in `DEV` mode versions it will not be triggered on startup. 
There is also an entry in the Help menu to check for updates at any moment, unlike the one on startup, this action will give feedback …

Add a check for updates method

---

spyderlib/utils/introspection/fallback_plugin.py
spyderlib/utils/introspection/plugin_manager.py
spyderlib/widgets/sourcecode/base.py

Fix some completion issues on the Editor (issue #2352)

---

spyderlib/baseconfig.py

This happens to work today because directories are only one level deep
under images so "path" was always the same as "_root".
Also, rename variables to match os.walk's documentation.

Don't add invalid paths to IMG_PATH

---

spyderlib/plugins/__init__.py

This related to dockwidgets that are tabified. Dockwidgets, when tabified, are put inside a QTabBar, but there is no access method to this bar, so to get it and process the event an eventFilter plus some search is needed. I added all the logic inside the event filter class.. but not sure if it is the best approach.
I attach a [video](http://youtu.be/wfvJupX4T5U) so you get the idea.

Add drag support for dockwidgets sharing same position

---

spyderplugins/widgets/profilergui.py

Fixes #2305
---
@Nodd could you check if this fixes your problem?

Replace obsolete setTextColor method by setForeground in qtreewidgetitem

---

spyderlib/spyder.py

If a (third-party) plugin fails to create its preferences page, it prevents the dialog to be created at all.
This PR allows to skip plugins that raise errors. The errors are still displayed in the intenal console, but the loop can continue (show must go on!).

Open preferences dialog even if a plugin raises errors

---

spyderlib/config.py
spyderlib/plugins/ipythonconsole.py
spyderlib/widgets/ipython.py

I dislike both the `droplist` and `ncurses` completers. It seems to me to be an omission that there is no way (short of patching the source) to select the `plain` tab completion.
This PR changes the completion checkbox into a combobox which gives the user the option of all three possible completers.

Changed the IPython completion option from a checkbox to a combobox

---

spyderlib/config.py
spyderlib/plugins/editor.py
spyderlib/spyder.py
spyderlib/widgets/editor.py
spyderlib/widgets/sourcecode/codeeditor.py
spyderlib/widgets/sourcecode/kill_ring.py

Fixes #729
Fixes #1212
Fixes #2047
Fixes #2347
----
Adds the following keybindings, including kill-ring support:
```python
'editor/start of line': "Meta+A",
'editor/end of line': "Meta+E",
'editor/previous line': "Meta+P",
'editor/next line': "Meta+N",
'editor/previous char': "Meta+B",
'editor/next char': "Meta+F",
'editor/previous word': "Meta+Left",
'editor/next word': "Meta+Right",
'editor/kill to line end': "Meta+K",
'editor/kill to line start': "Meta+U",
'editor/yank': 'Meta+Y',
'editor/rotate kill ring': 'Shift+Meta+Y',
'editor/kill previous word': 'Meta+Backspace',
'editor/kill next word': 'Meta+D',
'editor/start of document': 'Ctrl+Up',
'editor/end of document': 'Ctrl+Down',
```
Also makes the follow existing key sequences configurable:
```python
'editor/undo': 'Ctrl+U', …
```

Keybinding Enhancements

---

spyderlib/utils/introspection/jedi_plugin.py

There was an API change in Jedi.  Fixes #2439.

Fix handling of jedi completions for jedi 0.9

---

bootstrap.py
spyderlib/__init__.py
spyderlib/utils/vcs.py

bootstrap.py still searched for a mercurial revision number. Now it uses git.
I added the search for the branch name.

Print git revision and branch in bootstrap.py instead of mercurial

---

spyderplugins/widgets/pylintgui.py

Pylint program is invoked using PYLINT, which can now be pylint, pylint3, python3-pylint. Fix the regex to just search for PYLINT.

Match for pylint when parsing pylint output

---

spyderlib/plugins/ipythonconsole.py

Fixes #2468
----
It is unnecessary to prefix the connection file with `kernel-` and add the `.json` extension. IPython's [find_connection_file](https://github.com/jupyter/jupyter_client/blob/1c77df8fe707171504c4a761093041c7ff130c86/jupyter_client/connect.py#L136) already does that for you.
Besides, by doing it forcibly, we prevent the use of kernel files named otherwise than kernel-*.json, which occurs quite often  when connecting to a remote kernel.

Remove unnecessary changes to detected kernel json file when connecting to external kernels

---

spyderlib/plugins/ipythonconsole.py

- `find_connection_file` was being imported from `IPython.lib.kernel` which is a shim to `IPython.kernel.connect` since 1.0. Therefore, this does not change anything for IPython 1.0 to 3.2. We are just using a more direct path.
- Starting with IPython 4.0, 
- `IPython.lib.kernel` is a shim to `ipykernel.connect`
- `IPython.kernel.connect` is a shim as well, which first imports everything from `ipykernel.connect` and then everything from `jupyter_client.connect`. The latter sets the default directory for connection files from `~/.ipython/profile_*/security` to `JUPYTER_DATA_DIR`, which is the correct behavior.

Stop using IPython.lib.kernel 0.13.2 shim and add initial support for Jupyter

---

spyderlib/baseconfig.py

Related to #2471 
Avoids the 
```
Gtk-WARNING **: Locale not supported by C library.
Using the fallback 'C' locale.
``` 
message in ubuntu systems

Remove warning message associated to language on Linux

---

scripts/spyder_win_post_install.py

Fixes #2188
----
* add missing `bdist_wininst` functions from `pywin32_postinstall.py`:
`file_created()`, `directory_created()`, `get_root_key()`, `create_shortcut()`
and `get_special_folder_path()`
* test for `pythoncom` and return message "pywin32 required" on `ImportError`
* replace `CSIDL_COMMON_PROGRAMS` with `CSIDL_PROGRAMS` to be consistent with
desktop shortcut which is in user profile, and so that user doesn't have
to elevate rights in order to install Spyder
* add TODO to remove error message "try running installer as
administrator" since it's unnecessary if admin rights not required.
* if running `spyder_win_post_install.py -install` manually after installing
with pip, then `spyder.ico` and `spyder_light.ico` are in the
`Python27\Scripts\` folder not in the distribution folder, …

Fix the fact that spyder_win_post_install.py can't be run from pip

---

spyderlib/plugins/shortcuts.py
spyderlib/qt/QtGui.py

Fixes #478
Fixes #494
Fixes #1940
Fixes #2125
----
Allows the user to enter keyboard shortcut preferences by typing them in.

New KeySequence Editor for Keyboard Shortcut Preferences

---

spyderlib/widgets/sourcecode/codeeditor.py
spyderlib/widgets/sourcecode/syntaxhighlighters.py

Less apparent blank space, improved readability, fixing #2175.
Foreground color of blank space (if shown) is blended with the background color, therefore being less strongly present in both light and dark schemes.

Make blank space less apparent.

---

MANIFEST.in

Fix the issue in the PyPI installer that was reported in the qtawesome issue https://github.com/spyder-ide/qtawesome/issues/24.

Fix "pip install ." because of new Spyder 3 theme

---

spyderlib/plugins/configdialog.py
spyderlib/restart_app.py
spyderlib/spyder.py

Fixes #2401
---
Adds a new entry on the tools menu for reseting spyder from within the application
Or as an option in preferences... decision pending
After clicking a message box will ask to confirm, probably the message can be more explanatory so the user knows what he\she is about to do.

Reset spyder and restart from within running application

---

spyderlib/widgets/externalshell/sitecustomize.py

Closes gh-2395
Ping @DSLituiev - this should fix the problem you showed me yesterday.

Fix resetting IPython custom exception hook

---

spyderlib/config.py
spyderlib/spyder.py

Related to #2353 
Adds a toggle toolbars visibility button on view menu. Visibility on (action checked) visibility off (action unchecekd).
The last visible toolbars are updated only when using the toggle action.

Add option to toggle toolbars visibility

---

spyderlib/widgets/sourcecode/base.py
spyderlib/widgets/sourcecode/codeeditor.py

Fixes #680.  Automatically appends parens to completions that are known to be a `function`, `method`, or `class`, respecting the same rules as the standard auto parens in the code editor.

Automatically add parens for function completions

---

spyderlib/plugins/shortcuts.py
spyderlib/utils/stringmatching.py
spyderlib/widgets/helperwidgets.py

Fix #2475 
Fix some pending issues from https://github.com/spyder-ide/spyder/pull/2367
----
- Fix text color on selected text (in Mac)
- Fix dead strokes input

Keyboard shortcut editor enhancements

---

spyderlib/spyder.py
spyderlib/tour.py

This PR adds the missing contents of the *Introduction tour*.
I decided to create it given that this was @goanpeca's work, so I'd like to know his thoughts about my additions.

Finish Introduction tour

---

spyderlib/plugins/editor.py
spyderlib/spyder.py
spyderlib/widgets/editor.py
spyderlib/widgets/sourcecode/base.py

Fixes #2573 
----
Fix issue that codes like QByteArray().fromHex(str(state)) raise Type Error in Python3/PyQt5.5
A Type Error is raised when codes like QByteArray().fromHex(str(state)) are called.
It seems the error is because in python3, str(state) will return an string while the QByteArray().fromHex expect an hex array. 
I search the whole project of spyder and modifed codes like  QByteArray().fromHex(str(state)) to QByteArray().fromHex(str(state).encode('utf-8')). The encode method of string will return a byte array in python3 and a string in python2. 
I'm not familiar with  PyQt and the source code of spyder. Feel free to reject my pull request if you have a better solution for this issue.

Fix issues in Python3/PyQt5.5

---

spyderlib/plugins/history.py

Remove pane border around history pane for UI consistency

Homogenize History Pane UI

---

spyderlib/plugins/inspector.py
spyderlib/widgets/browser.py

Insert QWebView inside a QFrame to homogenize the UI

Homogenize Object inspector UI

---

spyderlib/spyder.py
spyderlib/widgets/helperwidgets.py
spyderlib/workers/updates.py

Fix #2389 
---
Move `MessageCheckBox` widget from `spyderlib/workers/updates.py`, to `helperwidgets.py`

Move MessageCheckBox widget from workers to helperwidgets.py

---

spyderlib/plugins/ipythonconsole.py
spyderlib/plugins/variableexplorer.py
spyderlib/widgets/externalshell/namespacebrowser.py

The "toolbar"  is now horizontal and the options button is aligned to the right, like other plugins.
Also now the variable explorer margins are updated when selection this option for panes inside the preferences

Homogenize variable explorer UI

---

spyderlib/widgets/sourcecode/base.py

Since we can't properly tell exactly when it is warranted, prefer consistent behavior and do not automatically insert open parentheses.  Fixes #2581.

Revert auto open parens on completion

---

spyderlib/widgets/sourcecode/codeeditor.py

Fixes #2614
When there is no previous line, the variable is unassigned and the whole function crashes. With this edit it exits gracefully.

Fix error when indenting on the first line of a file

---

spyderlib/widgets/calltip.py

Fixes #2596
There is a similar problem of ipython console's auto-completion droplist. That can be fixed by https://github.com/cy18/ipython/commit/cd9551183d8d025c77a3c09a6ec772270624bb80. But the IPython.qt has been deprecated in the master branch of IPython.

Show call tips at right position when there are multiple screens

---

spyderlib/utils/iofuncs.py

This fixes an issue at least on Windows while tring to load data saved earlier in the Variable Explorer
At least on Windows, pickle can raise a UnicodeDecodeError when the new format file is opened without mode='wb'. This was not caught and resulted in the failure of the loading of the data.

Fix missing exception on Windows when importing data on the Variable Explorer

---

spyderlib/qt/__init__.py

Failed sip import blocks fallback to PySide

---

spyderlib/widgets/sourcecode/base.py

Fix single item completion

---

spyderlib/qt/__init__.py

When QT_API environment variable has not been set properly, which is safe to assume when using PyQt5 for the first time, importing the `spyderlib.qt` package will fail. This change allows PyQt5 to be imported and used if QT_API has not been set and if both PyQt4 and PySide packages are not installed.

Fixed PyQt5 detection without QT_API env var

---

spyderlib/external/qtawesome/iconic_font.py

Fix issue with qtawesome fonts not rendering on OS X

---

spyderlib/plugins/__init__.py

Fixes #2598
I think now the user can switch the tab when clicking, however when moving tabs the displaced tab will retain a weird color until it has been selected again. I am not sure why, but at least this PR will fix the main issue.

Fix tabbar issue in OSX

---

spyderlib/widgets/dicteditor.py

Previously, if you go to variable explorer, right clicked
on a (large) numpy array and clicked copy if copied in the form
`[[1.0, 2.0 ... 3.0 ]]` (i.e. with dots in place of the middle
of the array)
Now it copies the whole array with as a tab separated string.
This is more useful since you can paste directly into Spyder
or into a spreadsheet, and no data is omitted.
The downside is that the clipboard can get quite large

Make "copy" work better with numpy arrays

---

spyderplugins/p_profiler.py

Fixes #2736
When the profiler is run from the top menu or from a shortcut, and if the run config has disabled command line arguments, the profiler should be called with `args=[]` instead of `args=None`, to ensure that no argument will be given to the script.

Read correctly the run config for profiling

---

spyderlib/widgets/varexp/arrayeditor.py

This replaces https://github.com/spyder-ide/spyder/pull/2579 (so close that request if you're happy with this one).
The justification remains the same:
The reason for this change is that if you went to the array editor and used the top left square to select everything, it only selected the currently loaded data. For large arrays that was a subset of the whole thing (because extra data is fetched on demand). It wasn't obvious that it had done this unless you scrolled to check what it had selected, or copied the selection and found it was smaller than expected.
I've changed two things:
1) When an array is copied and the selected ranges reach the edges of the currently loaded data, the range copied goes to the end of the array, not the end of the loaded data.
2) When a whole row or column is …

Improved copying and selection behaviour of array editor

---

spyderlib/qt/QtCore.py
spyderlib/qt/QtGui.py
spyderlib/widgets/varexp/arrayeditor.py

Fix arrayeditor import error in PyQt5

---

.travis.yml
README.md
continuous_integration/build_test.sh
continuous_integration/conda-recipes/spyder/meta.yaml
continuous_integration/modules_test.sh
continuous_integration/run_test.sh
continuous_integration/travis_install.sh
setup.py
spyderlib/dependencies.py
spyderlib/qt/QtCore.py
spyderlib/qt/QtGui.py
spyderlib/spyder.py
spyderlib/widgets/dependencies.py
spyderlib/widgets/externalshell/systemshell.py
spyderlib/widgets/varexp/utils.py

Fixes #2574
----
Times have changed :-) Now pip is a decent package manager, so it's time for us to demand all modules we really depend on (like `rope`, `pyflakes` and `sphinx`) as real dependencies.
This PR also wants to fix:

Add dependencies to pip

---

appveyor.yml
continuous_integration/appveyor/build_test.bat
continuous_integration/appveyor/install.ps1
continuous_integration/appveyor/modules_test.bat
continuous_integration/appveyor/run_test.bat
continuous_integration/conda-recipes/spyder/meta.yaml
continuous_integration/travis/modules_test.sh
continuous_integration/travis/run_test.sh
spyderlib/spyder.py
spyderlib/utils/qthelpers.py
spyderlib/widgets/formlayout.py

Let's see if we can make it happen :-)

Use Appveyor to test on Windows

---

scripts/spyder_win_post_install.py

The post install script assumes the ```spyder``` script is in the site scripts directory, but it isn't always installed there, i.e if spyder was installed using ```pip install --user spyder``` 
If the user then runs spyder_win_post_install.py -install manually, the shortcuts will be created pointing to a non-existent script.

Move the spyder script to the right place if it isn't present in the site Scripts directory

---

spyderlib/widgets/externalshell/sitecustomize.py

Changed `sitecustomize.runfile()` to parse arguments using `shlex` instead of `string.split()`. This allows users to run scripts with arguments containing escaped spaces in ipython.
Fixes #2010

Fix runfile argument parsing error by using shlex

---

spyderplugins/p_profiler.py

Fixes #1761. One liner: add a call to editor.save() before running the profiler.

Make F10 (profile) save the current file before running

---

spyderlib/plugins/inspector.py
spyderlib/plugins/workingdirectory.py
spyderlib/widgets/comboboxes.py
spyderlib/widgets/helperwidgets.py

Fixes #2677
The PathComboBox now has auto completion which improves the UX. This affects the Global Working Directory Toolbar and the Find in Files pane.

Add tab completions for PathCombobox

---

spyderlib/widgets/__init__.py

- Crashes happened when pandas or numpy were not installed because dataframeeditor and arrayeditor import them directly.
- It seems we can't improve further this situation, but at least API changes are documented.
----
I made this PR to let @goanpeca and @PierreRaybaut know about this change. Leaving those imports in `widgets/__init__` to maintain compatibility with Spyder 2 would make Spyder 3 to hard depend on Pandas and NumPy, but we can't afford that for this simple change :-)

Remove imports from widgets/__init__ because they are making Spyder crash

---

spyderlib/widgets/sourcecode/codeeditor.py

Fixes #2795
----
Restore the insertion of the "(" character when parameter close_parentheses_enabled is False.
I suspect some patch destroyed the functionnality formerly in handle_close_parentheses(text)
This is the simple fix, maybe a more complete fix would remove unused path in def  handle_close_parentheses()

Restore the insertion of the "(" character when parameter close_parentheses_enabled is False

---

spyderlib/otherplugins.py

Import spyplugins only if there's a valid spec/module

---

spyderlib/qt/__init__.py

i think i did this once.
you stated then that it wasn’t ready, but that’s been some time ago and there are now PyQt5 travis tests.
also 3.0 should really ship like that.

Use PyQt5 as default API

---

README.md
bootstrap.py
doc/installation.rst
doc/overview.rst
setup.py
spyderlib/__init__.py
spyderlib/qt/__init__.py
spyderlib/requirements.py

This removes references to PySide in our official docs, in our Readme and in `setup.py`.
However, there is (and will always be) support for PySide in `bootstrap.py` and in our Qt shim, in case people want to keep using it.
Reasons to do this:
1. PySide future is uncertain and very little is happening with it currently.
2.  Now that we've moved to support PyQt5 officially (see PR #2879), I want to reduce the number of bindings we support so it be easier to maintain Spyder.
3. PySide support is currently broken in master (Preferences is crashing with it)
4. Nobody has helped to support it (besides Pierre and me).
This was not only my decision, all @spyder-ide/core-developers agreed with it.

Remove official support for PySide

---

README.md
doc/installation.rst
spyderlib/config/ipython.py
spyderlib/plugins/help.py
spyderlib/plugins/ipythonconsole.py
spyderlib/spyder.py
spyderlib/widgets/explorer.py
spyderlib/widgets/externalshell/start_ipython_kernel.py
spyderlib/widgets/ipython.py
spyderlib/widgets/sourcecode/codeeditor.py

We are already requiring Jupyter packages (i.e. `qtconsole` and `nbconvert`) since beta2, so this reflects that in our code too.
Besides, we can express more easily and directly our dependencies by using Jupyter packages instead of the big and monolithic IPython.

Move to use Jupyter imports and remove support for IPython 3

---

spyderlib/interpreter.py
spyderlib/plugins/editor.py
spyderlib/plugins/externalconsole.py
spyderlib/utils/codeanalysis.py
spyderlib/utils/programs.py
spyderlib/utils/vcs.py
spyderlib/widgets/externalshell/sitecustomize.py
spyderlib/widgets/findinfiles.py
spyderlib/widgets/internalshell.py
spyplugins/ui/pylint/widgets/pylintgui.py

I had many fights with line-endings!  It looks like some of the patch and diff tools between mercurial and git don't respect the various autocrlf settings in dot files.

Prevent cmd.exe shell windows popping up in the background when calling subprocess

---

spyderlib/plugins/help.py
spyderlib/spyder.py

As it's been our tradition, we try not to crash on import errors, but for Spyder 3.0 I decided to deactivate things in case our requirements are not installed.

Hide Help plugin if Sphinx is not installed

---

spyderlib/plugins/editor.py

Add 3,5,6,7,8 spaces as options in indentation of the Editor

---

spyderlib/widgets/explorer.py

Very simple but needed change to avoid using the mouse :-) when moving within the file explorer
Pressing backspace triggers `go_to_parent_directory` as many OS file managers do.

PR: Make backspace move to parent directory in file explorer

---

spyderlib/utils/encoding.py

Fixes #2703 
----
In UTF-8 one character can be represented by multiple bytes. If such bytes have not been placed in the same chunk (CHUNKSIZE=1024), function 'is_text_file' from encoding.py will fail on this input.
Solution is to use IncrementadDecoder.
It is possible that issue #2703 is related to this fix. Since the file attached to issue is determined as binary, spyder tries to open it with external program (console) (instead of editing)

PR: More accurate test for text-like files

---

spyderlib/plugins/editor.py

At the moment 'Save All' is enabled if editor stack 0 has more than one file open and if one of the files opened in editor stack 0 has been changed. However, the 'Save All' action saves all changed files in the current editor stack (not editor stack 0), with no condition on the number of files opened.
This change ensures that 'Save All' is enabled precisely when 'Save All' would do something, that is, when the current editor stack has a file that has been changed.

PR: Enable 'Save All' if there are files to be saved

---

spyderlib/plugins/workingdirectory.py

Changing the directory in the interface tree will now affect consoles' cwd. 
This fixes #2910.

PR: Synchronize entry in Working Directory toolbar with console's current working directory

---

spyderlib/app/spyder.py
spyderlib/config/main.py
spyderlib/config/utils.py
spyderlib/plugins/configdialog.py
spyderlib/plugins/editor.py
spyderlib/plugins/findinfiles.py
spyderlib/utils/sourcecode.py
spyderlib/widgets/editor.py

This will let people know that we not only support Python files but all text files supported by Pygments.

PR: Show all supported text files when opening files with "File > Open"

---

spyderlib/utils/introspection/plugin_client.py

@blink1073, this fixes completions for me when using bootstrap.
I think the solution is the right one because we should only touch `PYTHONPATH` for the `QProcess` that starts `plugin_server` when using bootstrap. In other situations `plugin_server` should be able to find `spyderlib` (the only third-party module it needs) in `site-packages`.
Please review and let me know what you think about this one, given that now you're our Editor completion expert :-)

Editor: Fix code completions when working with bootstrap

---

appveyor.yml
conda.recipe/meta.yaml
continuous_integration/appveyor/run_test.bat
continuous_integration/conda-recipes/qtconsole/meta.yaml
continuous_integration/conda-recipes/spyder/meta.yaml
continuous_integration/travis/run_test.sh

Now that #2932 is in, we can safely remove some code that we were using just for Jedi 0.8.1

PR: Remove Jedi special code in tests and other minor fixes

---

spyderlib/utils/encoding.py

The get_coding function can return an encoding that is not valid. This caused spyder to crash during startup. This pull request makes sure only valid encodings are returned.
An example text which returns an invalid encoding:
`# Try decoding as utf-8 bytestring        return __builtins__.unicode(msg, encoding="utf-8")    except:        pass    try:        # Try guessing system default encoding and decode as such        import locale        return __builtins__.unicode(msg, encoding=locale.getpreferredencoding())    except:        pass    try:        # Attempt using filesystem encoding        import sys        return __builtins__.unicode(msg, encoding=sys.getfilesystemencoding())    except: `

Fix bug in get encoding from "coding" comment line

---

profiling.txt
spyderlib/utils/introspection/fallback_plugin.py
spyderlib/utils/introspection/jedi_plugin.py
spyderlib/utils/introspection/rope_plugin.py
spyderlib/utils/introspection/utils.py
spyderlib/utils/syntaxhighlighters.py

Uses the Pygments lexer in introspection instead of the previous regex-based approach.  This will help completions in non-python-like files.  We will do a better job of finding the right object to complete, and finding suitable objects within the same syntax type for completion.

PR: Use pygments in introspection

---

spyderlib/widgets/sourcecode/base.py

Fixes #2835 
----
My first attempt at contributing to open source... constructive criticism welcome!

Copying when nothing is selected no longer affects the clipboard.

---

spyderlib/plugins/editor.py

It makes it easier to run scripts outside of spyder on linux.
The template could be further enhanced (add `if __name__ == "__main__"` for example).

Add shebang line to default template.py

---

README.md
conda.recipe/meta.yaml
setup.py
spyderlib/utils/introspection/manager.py
spyderlib/utils/introspection/plugin_client.py
spyderlib/utils/introspection/plugin_server.py
spyderlib/utils/introspection/utils.py

Implements streamlined async server for introspection, fixes #3033, fixes #3041.
Uses a single port for communication that is managed by zmq.
Uses socket notification rather than a thread in the client.
Adds a heartbeat to keep the server alive.
The main classes will be moved elsewhere and used for code analysis background tasks after beta3.

Implement a new Async Server approach based on pyzmq to get completions on the Editor

---

spyderlib/widgets/externalshell/sitecustomize.py

Fixes #3061 
----
Here is the fix for the bug described in #3061.
@PierreRaybaut  as author if that piece of code should review my change and check if not I broke more than I fixed. :D 
best regards Sebastian

Fix consoles encoding in Python 3

---

spyderlib/app/spyder.py

The Windows `SetConsoleCtrlHandler` was only sending one argument to the function.

Fix interrupt handling on Windows

---

spyderlib/requirements.py

I installed `PyQt5` and `spyder` from source, but `setuptools` did not install `qtpy`. When opening `spyder`, the failure message suggests that `PyQt*` is missing, whereas it was only `qtpy` that was missing. This behavior can be reproduced with `pip uninstall qtpy` in an environment where `spyder` is already working correctly.

Note failure to import `qtpy` in message about missing PyQt libraries

---

spyderlib/plugins/shortcuts.py

fix crash on shortcut assignment (Qt5 'dataChanged' signal has 3 parameters)

PR: Crashing on shortcut assignment with PyQt5

---

spyderlib/app/cli_options.py
spyderlib/app/spyder.py

Add an option to set window title to the command line

---

spyderlib/app/spyder.py

If a plugin has a problem to initialize, it will crash spyder.
This PR avoids to crash while still providing the full traceback.

More robust plugin initialization in layout

---

spyderlib/widgets/editor.py

Fixes #3115 
-----
@jitseniesen I rewrote the header to the standard we try to use (`Fixes #<issue number>`)

Editor: Move to next line in run_selection() if nothing selected

---

spyderlib/widgets/externalshell/start_ipython_kernel.py

Fixes  #3206.
I couldn't reproduce the error but the fix is quite obvious.

Fix undefined `backends` when starting IPython kernel

---

conda.recipe/bld.bat

This fix is necessary to make a conda build on windows. You could maybe consider to also build the beta releases on conda-forge :)

Fix icon name in conda windows build script.

---

spyderlib/widgets/sourcecode/codeeditor.py
spyderlib/widgets/sourcecode/tests/test_autocolon.py

This PR prevents the automatic insertion of a colon at the end of one-line if statements like:
````python
if True: print "Yes!"
````
It also prevents the automatic insertion of a colon at the second line of two-line list comprehensions like:
```python
yes_list = [x for x in [None, None, None, "Yes!"]
if x is not None]
```
Fixes #872

PR: Fix automatic insertion of colon

---

spyderlib/plugins/help.py
spyderlib/utils/help/tutorial.rst

The path was incorrect (folder 'static' was doubled).
Now it works on win7, python2.7, sphinx 1.4.1.
It could be seen, eg in the section "Documentation string formatting" of the tutorial.

PR: Fix tutorial images on Windows

---

spyderlib/widgets/sourcecode/codeeditor.py
spyderlib/widgets/sourcecode/tests/test_autoindent.py

I added some tests to check for the indentation function.
It is motivated by a new but that was introduced lately, the cursor is placed at the same column as an opened parenthesis even if no text is entered after the parenthesis (this is my last commented test case).
This way of testing works but isn't practical at all, it would be really better to use libs like pytest for this. Those tests don't need the QApplication to run, only its creation so it doesn't have the same problem other tests have. Some hints were stated in #2268

Add some indentation tests

---

spyderlib/utils/programs.py
spyderlib/utils/tests/test_programs.py

Fixes #3155: Executing a python script in external terminal without
specifying a working directory leads to wdir = '', which is not handled
correctly.
In the previous version, the working directory was passed as an option
to the script if xterm is used. This did not make sense to me, so I
removed that.

PR: Allow empty wdir option to run_python_script_in_terminal

---

spyderlib/widgets/variableexplorer/tests/test_utils.py
spyderlib/widgets/variableexplorer/utils.py

Variable explorer: Disregard list1 when sorting list1 against list2

---

spyderlib/utils/qthelpers.py

sig_open_external_file is present in spyderlib/app/spyder.py and doesn't match open_external_file (had to add sig_)

Fix a bug preventing Spyder to open external file In Mac application 

---

spyderlib/plugins/editor.py
spyderlib/utils/introspection/manager.py
spyderlib/widgets/editor.py

Before we were creating one instance of IntrospectionManager per EditorStack, which was causing freezes when adding more EditorStacks (e.g. when a new Editor window was created or when the Editor was splitted).
@blink1073, could you take a look at this one?

Create only one instance of IntrospectionManager for the application

---

spyderlib/widgets/variableexplorer/dataframeeditor.py
spyderlib/widgets/variableexplorer/tests/test_dataframeeditor.py

Dataframe editor: Make sorting stable; handle order correctly.
Fixes #3010 
Fixes #3020

Improve sorting in dataframe editor

---

README.md
conda.recipe/meta.yaml
doc/installation.rst
setup.py
spyderlib/plugins/ipythonconsole.py
spyderlib/utils/syntaxhighlighters.py
spyderlib/widgets/ipython.py

Update minimal required version of several of our dependencies

---

spyderlib/widgets/variableexplorer/arrayeditor.py
spyderlib/widgets/variableexplorer/tests/test_arrayeditor.py

Fixes #3237. Includes one new test, and moving existing tests to py.test format.

Support float16 values in array editor

---

spyderlib/plugins/help.py
spyderlib/widgets/browser.py
spyderlib/widgets/findreplace.py

Fix searching text in our Web widgets

---

spyderlib/config/main.py
spyderlib/config/utils.py
spyderlib/plugins/findinfiles.py
spyderlib/plugins/tests/test_findinfiles.py

PR: Fix/Find in files

---

spyderlib/widgets/sourcecode/codeeditor.py

Add keyboard shortcuts to context menu in editor

---

spyderlib/app/spyder.py

Fix monkey-patching of QApplication

---

spyderlib/widgets/editor.py
spyderlib/widgets/fileswitcher.py

Toggle file switcher when pressing its keyboard shortcut

---

MANIFEST.in
setup.py
spyder_breakpoints/locale/breakpoints.pot
spyder_breakpoints/locale/es/LC_MESSAGES/breakpoints.po
spyder_breakpoints/locale/fr/LC_MESSAGES/breakpoints.po
spyder_breakpoints/locale/pt_BR/LC_MESSAGES/breakpoints.po
spyder_breakpoints/locale/ru/LC_MESSAGES/breakpoints.po
spyder_breakpoints/widgets/breakpointsgui.py
spyder_profiler/locale/es/LC_MESSAGES/profiler.po
spyder_profiler/locale/fr/LC_MESSAGES/profiler.po
spyder_profiler/locale/profiler.pot
spyder_profiler/locale/pt_BR/LC_MESSAGES/profiler.po
spyder_profiler/locale/ru/LC_MESSAGES/profiler.po
spyder_profiler/widgets/profilergui.py
spyder_pylint/locale/es/LC_MESSAGES/pylint.po
spyder_pylint/locale/fr/LC_MESSAGES/pylint.po
spyder_pylint/locale/pt_BR/LC_MESSAGES/pylint.po
spyder_pylint/locale/pylint.pot
spyder_pylint/locale/ru/LC_MESSAGES/pylint.po
spyder_pylint/widgets/pylintgui.py
spyderlib/otherplugins.py

Fixes https://github.com/spyder-ide/spyder/pull/3210#issuecomment-232092226
I forgot this change when switching to flask model.

Re-include plugins in setup.py packages

---

appveyor.yml
continuous_integration/appveyor/build_test.bat
continuous_integration/appveyor/install.ps1
continuous_integration/appveyor/modules_test.bat
continuous_integration/conda-recipes/spyder/meta.yaml

All our testing so far has been done with Qt 5.5

Test Spyder with Qt 5.6 in AppVeyor

---

spyderlib/app/spyder.py

Enable high DPI scaling on Qt >= 5.6

---

README.md

- Reorganize badges for build and project status
- Include Quantified Code badge
- Include Gitter chat bagde

PR: Update readme and organize badges

---

spyderlib/app/spyder.py
spyderlib/app/start.py
spyderlib/config/base.py
spyderlib/config/main.py
spyderlib/config/user.py

Fixes #2629 
----
This also:
- Avoids copying settings from Spyder 2 (for all OSes) because it's a very brittle process and makes the code to save settings very complicated.
- Develops an easier way to test Spyder with clean settings by passing `--test` to `bootstrap.py`. The previous version created a temp directory to save our settings, but that also made things too complex and hard to understand. Now we use that option to avoid reading and writing our settings from/to the hard disk.

Use XDG_CONFIG_HOME to save our settings on Linux

---

spyderlib/app/cli_options.py
spyderlib/app/spyder.py
spyderlib/app/start.py
spyderlib/config/base.py
spyderlib/utils/iofuncs.py

Remove lock file as part of --reset

---

spyderlib/app/spyder.py
spyderlib/plugins/editor.py

Fixes #3288 
----
- We had a couple of actions that contained the strings "quit" and
"exit" in their names, and that was interfering with the "Quit
Spyder" action.
- That's because Qt creates automatically that action based
on any action in the main application menus that contains those
substrings.

Fix "Quit Spyder" action on OS X

---

spyderlib/widgets/fileswitcher.py
spyderlib/widgets/helperwidgets.py
spyderlib/widgets/sourcecode/codeeditor.py

Fixes #3274 
----
* This improves our file swticher to make it more similar to the Sublime and VisualCode ones. In particular, I decided to:
* Remove line numbers for symbols. This way users can see much more symbols in the dialog.
* Use the system font for symbols (it was used already for files).
* Remove tokens for symbols (i.e. `def`, `class`, etc).
* Make the initial dialog size to be about the same for files and symbols.
* Use FontAwesome icon for files instead of the one assigned to the Editor tabs.
* I was a bit dissatisfied with the way the switcher looked before, but now I think it looks quite good :-)
* Pinging @goanpeca and @Nodd about it.
----

Some improvements to our file switcher

---

spyderlib/plugins/history.py
spyderlib/plugins/ipythonconsole.py
spyderlib/widgets/editor.py
spyderlib/widgets/tabs.py

This
* ~~Removes the left corner button from tabs, which contained a menu to browse them.~~ 
* Removes icons from our tabs (except for the Python Console, where they are useful because we have several types of tabs).
We talked about this with @goanpeca during SciPy and we think this helps to simplify how Spyder looks by removing visual clutter from the interface. It also improves our UI because the icons for the IPython console and Python files on the Editor are a bit ugly.
----

Remove icons from tabs for the Editor and IPython Console

---

spyder/config/tests/test_user.py
spyder/config/user.py
spyder/utils/tests/test_programs.py

Using `eval()` has unintended side-effects, and may be considered a security risk. Instead, do nothing if we expect a string, and use `ast.literal_eval()` for other types (list, tuple, etc.). Also add tests.
Fixes #3354. That issue also talks about problems with IPython startup configuration, which I will leave for @ccordoba12.

Avoid eval() when reading config file

---

spyder/plugins/__init__.py

- ~~Restore plugin compatibility (`PluginConfigPage` was removed from `__init__.py`)~~
- Allow plugins with no dockwidgets (set to None for example, the attribute must exist for now)

Allow plugins with no dockwidgets

---

spyder/widgets/ipythonconsole/control.py
spyder/widgets/ipythonconsole/debugging.py
spyder/widgets/ipythonconsole/namespacebrowser.py
spyder/widgets/ipythonconsole/shell.py

Fixes #3419
----
This also contains some other minor fixes for the IPython console

Don't try to use "?" to automatically get help in the IPython console

---

spyder_profiler/widgets/profilergui.py

Fix using `add_pathlist_to_PYTHONPATH` in _profilergui.py_
This function was moved to utils/misc in commit 252c9adc49

Fix profiler

---

continuous_integration/appveyor/install.ps1
continuous_integration/travis/install.sh

* This avoids errors when conda-build is updated.
* We don't need anything fancy from conda-build, so there's no need for us to live in its bleeding edge :-)

Pin conda-build to 2.0.0

---

spyder/plugins/ipythonconsole.py
spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/namespacebrowser.py
spyder/widgets/ipythonconsole/shell.py

Fix problems when connecting to external kernels

---

spyder/utils/ipython/spyder_kernel.py

Don't try to get shape and ndim for objects that are not ndarrays

---

spyder/widgets/browser.py

Prevent WebEngine to steal focus when setting html on the page

---

spyder/widgets/dependencies.py

PR: Change of the label in the dependencies dialog

---

spyder/plugins/console.py
spyder/plugins/editor.py
spyder/plugins/history.py
spyder_pylint/pylint.py

Fixes #3519 
This also was causing error in maximum lines in console and history deep

PR: Change deprecated funtion QInputDialog.getInteger for QInputDialog.getInt

---

spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_autoindent.py

Fixes #1373 
When a structure is defined in the same line, the autoindent was failing

Fix autoindentation after data structures.

---

spyder/app/mainwindow.py
spyder/config/main.py
spyder/plugins/configdialog.py

Add option to set/unset dpi scaling for screens that are not high resolution

---

spyder/utils/syntaxhighlighters.py

Fix builtin and keywords highlighting depending on indentation

---

spyder/config/main.py

Fixes #3127 
----
This will prevent Spyder to crash and force users to run
spyder --reset
to come back to a clean state :-)

Load default settings if there is any error in spyder.ini

---

spyder/plugins/ipythonconsole.py
spyder/plugins/workingdirectory.py
spyder/utils/ipython/spyder_kernel.py
spyder/widgets/ipythonconsole/shell.py

Fix connection between the IPython Console and the Working Directory toolbar

---

spyder/app/mainwindow.py

PR: Fix unclickable update message box

---

spyder/widgets/sourcecode/base.py

Revert error introduced by linenumber migration

---

spyder/plugins/ipythonconsole.py

@mariacamilaremolinagutierrez, you should have detected this error if you had tested live (i.e. by starting a new instance of Spyder) the commit that introduced this change.
That's why I told you and @dalthviz to never push any change that hasn't been tested live. Let's hope this doesn't happen again :-)
----
This was (in part) also my fault because I wasn't sure if `copy()` works for lists or not, but I trusted you did the check yourself ;-)

IPython Console: Simple fix after PR #3641

---

spyder/widgets/variableexplorer/collectionseditor.py

Fixes #3513.
----
This doesn't completely solve #3513, but it's the best I could come up with. Unfortunately, I don't know how things could be improved :-/
* Pros:
- It prevents Spyder to fully eat your RAM when inspecting several large variables.
* Cons:
- It doesn't free RAM for the *first* variable you inspect. A trick to make Spyder freeing that memory is to create a small variable (e.g. an empty dataframe), and then open and close it.

Free memory when closing a Variable Explorer editor

---

spyder/plugins/ipythonconsole.py

Fixes #3444.
----
@dalthviz, could you check if this increase is enough for you, given that you're experiencing this problem locally? Thanks :-)

Increase time to detect if an IPython kernel is alive

---

spyder/widgets/editor.py

Fixes #3678 
Fixes #3026 
Edit: Include reference to a related issue

PR: Fixed weird behavior of "Save as"

---

spyder/widgets/variableexplorer/utils.py

PR: Added support to the principal numeric Numpy types in the Variable Explorer

---

spyder/utils/syntaxhighlighters.py

Fixes #3608
---
I fixed it in a really simple way, I reused instance decorator, is that ok? or should I add a new color theme color for decorators?

PR: Add regex to highlight decorators

---

spyder/plugins/ipythonconsole.py

PR: Load kernel json files anywhere in the filesystem

---

spyder/widgets/mixins.py

Partially fixes #3408 (only PyQt5)
`QRegExp` didn't support lazy quantifiers, like *?, +?, etc. It's better to use `QRegularExpression`.
Although `QRegularExpression` is only avalaible since Qt5, so It'll continue using `QRegExp` for PyQT4

PR: Use QRegularExpression for find and replace (only for PyQt5)

---

spyder/widgets/mixins.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_autoindent.py

Fixes #3508 
----------------
- Added some test for indenting with tabs, I used the 3dr way that I mencioned in #3651 (but didn't change spaces indentation tests)
- Added test for #3508 
- Change how `correct_indent` is calculated, when using tabs It will be calculated with spaces (each tab 4 spaces) and then convert it to tabs and reminder to spaces
I think this could be improved if the option `tab_stop_width` is defined in terms of spaces instead of pixels.

PR: Fix some errors of Indentation with tabs

---

spyder/config/main.py
spyder/plugins/externalconsole.py
spyder/plugins/variableexplorer.py
spyder/widgets/ipythonconsole/namespacebrowser.py
spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/namespacebrowser.py
spyder/widgets/variableexplorer/utils.py

This PR also removes the connection between the Variable Explorer and the Python Console. This starts the process of moving that console out of Spyder because it's unmaintained.

PR: Refactor and simplify NamespaceBrowser widget

---

spyder/widgets/comboboxes.py

PR: Remove logic to delete last dir separator (\, /) in find and replace widget

---

README.md
conda.recipe/meta.yaml
continuous_integration/conda-recipes/spyder/meta.yaml
doc/installation.rst
setup.py
spyder/utils/encoding.py
spyder/utils/external/__init__.py
spyder/utils/external/binaryornot/__init__.py
spyder/utils/external/binaryornot/check.py
spyder/utils/external/binaryornot/helpers.py
spyder/utils/tests/test_encoding.py

~~Add misc.is_supported_file function, and use it instead of encoding.is_text_file~~
**EDIT**
Add [binaryornot](https://github.com/audreyr/binaryornot) package  and use it to determinate if a file is text
Fixes #3631 
Fixes #3670

PR: Check if files are text files using the binaryornot package

---

spyder/utils/programs.py

Fixes #3738
----
This will avoid simple crashes when importing a module fails with errors other than `ImportError`

Utils: Make is_module_installed to catch all errors when importing a module

---

spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_autoindent.py

Fixes #3480 
----
This commit has an option for hanging indent at menu - python - Preferences - Editor - Advanced settings - Hanging indentation. It is unchecked by default, but when checked, allows hanging indentation, as follows:
```
def long_function_name(
var1, var2):
print("This works. Yeah!")
if long_function_name(
var1, var2):
print("also works")
```
The case I found not working is the following, where the subsequent line is indented one step too much:
```
if long_array_name[
var1]:
print("this does not work yet")
```
But such cases are rarer for me, so it would be useful even as it stands now. I haven't found why this happens, and I would appreciate help.
I checked the following and they work as expected, too:
- the new option is saved after quitting, and
- the default behavior, …

PR: Add hanging Indentation to the Editor

---

spyder/utils/qthelpers.py

PR: Fix View/Toolbars menu

---

spyder/config/utils.py

Take a look to this @ccordoba12 and @goanpeca.
This PR can solve your problems @rlaverde with save_as feature.
any suggestions  and comments are welcome. :+1:

PR: Set Python as default file extension for the "Save As" dialog

---

spyder/config/gui.py
spyder/config/main.py
spyder/plugins/editor.py
spyder/widgets/editor.py
spyder/widgets/findreplace.py
spyder/widgets/ipythonconsole/shell.py
spyder/widgets/shell.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/tabs.py
spyder/widgets/variableexplorer/arrayeditor.py
spyder/widgets/variableexplorer/dataframeeditor.py

Fixes #3395 
Fixes #3415
----
The idea of this PR is to remove fixed_shortcuts and leave only config_shortcuts as suggested by @ccordoba12 
I have encounter several issues:
- Some fixed_shortcuts use QKeySequence (copy, zoom in, and zoom out), I replaced by the corresponding shortcuts (Ctrl+c Ctrl++, Ctrl+-), because It is not possible to import QKeySequence in spyder/config/main.py
- `RUN_CELL_SHORTCUT` and `RUN_CELL_AND_ADVANCE_SHORTCUT` variables in spyder/config/gui.py are platform dependent (I moved that code to spyder/config/main.py but I change Qt imports to strings)
- Some actions have two shortcuts, I created two different configurations keys (example: `editor/close file 1`  `'editor/close file 2`) There is another workaround? should shortcuts have several options?
- It's ok to …

PR: Change fixed shortcuts for configurable ones

---

spyder/app/mainwindow.py
spyder/config/user.py

PR: Added validation to window/position config value saved in spyder.ini

---

spyder/utils/syntaxhighlighters.py

In  #3654 I didn't take in account that decorators are variables separated by points, and variables contain letters, numbers and underscores, and should start by a letter or underscore
Some decorators weren't detected:
```
@decorator_with_underscore
@decorator12
```
and others were detected and shouldn't be detected:
```
@.decorator
@decorator..points
@decorator.
```

Improve highlighter decorator regexp

---

spyder/scientific_startup.py

- Moved the `__has_...` so it is not defined in two different locations
- Import all packages uniformly (no special treatment of guiqwt)
- Use new style formatting.
- Give correct "Imported ..." message even if numpy is not installed.

PR: Improve style of scientific startup script

---

spyder/config/main.py
spyder/plugins/tests/test_variableexplorer.py
spyder/plugins/variableexplorer.py
spyder/widgets/externalshell/pythonshell.py
spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/dataframeeditor.py
spyder/widgets/variableexplorer/namespacebrowser.py
spyder/widgets/variableexplorer/tests/test_collectioneditor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py
spyder/widgets/variableexplorer/tests/test_namespacebrowser.py
spyder/widgets/variableexplorer/utils.py

Fixes #2728.
----
This is #3539 <s>raised from the dead</s> but based now against 3.x branch. 
This pull request is to make Spyder remember the format that the user sets for floats in the DataFrameEditor by storing it in the user configuration settings.
- A new config setting `dataframe_format` is introduced in the variable explorer section in the user config. This setting contains the format, without the leading `%` character (e.g., if the format is `'%.3f'` then the setting is stored as `'.3f'`). The reason for this is that it is apparently impossible to have a config setting with a `%` character, because this is used in `ConfigParser` for interpolation.
- This setting is passed (after adding a `%` character in the front) from the `VariableExplorer` plugin via the `NamespaceBrowser` and …

 PR: Remember format for floats in DataFrame editor

---

spyder/plugins/editor.py

PR: Redefinition of upper/lower shortcuts was not updated in Edit menu

---

.ciocheck

It seems this is the cause of repeated hanging in CircleCI

PR: Don't run Pylint with ciocheck

---

spyder/app/mainwindow.py
spyder/config/main.py

Fixes #3818
Removed shortcut for opening spyder documentation from /app/mainwindow.py
Registered shortcut for opening spyder documentation in /app/mainwindow.py
Created default configuration for opening spyder documentaion in /config/main.py

PR: Make Spyder documentation keyboard shortcut configurable

---

spyder/plugins/editor.py
spyder/widgets/editor.py

PR: Added management for toolbars in new Editor windows instances.

---

spyder/app/mainwindow.py
spyder/app/tour.py

Fixes #3452 
The issue is solved. I have some comments: 
- What I did was deleting the ```self._set_modal(False, [self.tips])``` call when closing the tour, this affects only windows. However I am not exactly sure why it was needed before. 
- Also deleted the option that makes the tour available only in DEV mode.

PR: Closing tour does not freeze Spyder on windows

---

spyder/utils/encoding.py

After #3640 an error was caused when right clicking over a directory in project explorer (I didn't notice while doing #3640, sorry :disappointed:)
```
>>> Traceback (most recent call last):
File "/home/rlaverde/code/spyder/spyder/widgets/explorer.py", line 404, in contextMenuEvent
self.update_menu()
File "/home/rlaverde/code/spyder/spyder/widgets/explorer.py", line 383, in update_menu
add_actions(self.menu, self.create_context_menu_actions())
File "/home/rlaverde/code/spyder/spyder/widgets/explorer.py", line 370, in create_context_menu_actions
actions += self.create_file_manage_actions(fnames)
File "/home/rlaverde/code/spyder/spyder/widgets/explorer.py", line 270, in create_file_manage_actions
only_valid = all([encoding.is_text_file(_fn) for _fn in fnames])
File …
```

PR: Catch error raised in isbinaryornot when trying to open a directory

---

circle.yml

This prevents fetching several unnecessary packages from conda-forge

PR: Make conda respect channel priority in CircleCI

---

README.md
circle.yml
conda.recipe/meta.yaml
continuous_integration/conda-recipes/spyder/meta.yaml
doc/installation.rst
setup.py
spyder/docstrings.py
spyder/utils/introspection/docstrings.py
spyder/utils/introspection/jedi_patch.py
spyder/utils/introspection/jedi_plugin.py
spyder/utils/introspection/test/__init__.py
spyder/utils/introspection/test/test_jedi_plugin.py

This pull request uses code from davidhalter/jedi#796 to add completions of returns that are in numpydoc doc format.  This pull fixes #2162 for numpy and matplotlib.
In order for this to work you need the "numpydoc" module installed
Here is some "test" code to copy into the Spyder editor.
import numpy as np
import matplotlib.pyplot as plt
x = np.array([1,2,3])
y = np.ones()
y.                        # works
x.                        # works
w = x + y
w.                        # works
v = y.transpose()         # finds the docstring with Ctrl-i and params pop-up
v.                        # works
fig = plt.figure()
fig.                      # works
fig.add_axes()            # finds the docstring with Ctrl-i and params pop-up
ax = plt.subplot(111)
ax.                       # works (fails on …

Patch Jedi to get completions for compiled objects in Numpy and Matplotlib

---

spyder/widgets/findreplace.py

PR: Make regex fully functional when using find & replace 

---

spyder/plugins/externalconsole.py

PR: Add disambiguation functionality to the Python console

---

spyder/app/mainwindow.py
spyder/config/main.py
spyder/plugins/ipythonconsole.py
spyder/utils/programs.py
spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/shell.py

Fixes #3458.
----
This PR does several things:
1. Redirects the kernel process stderr output to a file and shows it in case of failure in our consoles. With this I'm trying to avoid the infinite stream of *Kernel died, restarting* messages and give feedback to users of what's the cause of the error.
2. Introduces a shortcut to restart kernels, so that we can override the one defined in qtconsole and control this process ourselves.
3. Clears the console on restarts.

PR: Show kernel initialization errors in the IPython console

---

spyder/utils/misc.py

PR: Make running a file with single quotes on its path not to throw an error on Windows

---

spyder/widgets/sourcecode/codeeditor.py

PR: Show calltips when 'Automatic insertion of parentheses, braces and brackets' is unchecked

---

README.md
conda.recipe/meta.yaml
continuous_integration/conda-recipes/spyder/meta.yaml
continuous_integration/travis/modules_test.sh
doc/installation.rst
setup.py
spyder/__init__.py
spyder/app/mainwindow.py

Fixes #3843 
----
Is important to know that for this to actually work this [PR](https://github.com/spyder-ide/qtawesome/pull/60) has to get a merge in the qtawesome project because of the `FontError` import.

PR: Add a way to handle font errors in QtAwesome

---

spyder_profiler/profiler.py

Fixes #3923.
self.profiler.analyze should not take self as otherwise filename=self, wdir=filename and wdir=wdir

Fix "TypeError: got multiple values for argument" in Profiler

---

spyder/app/mainwindow.py

PR: Raise the menu bar to the top of the main window widget's stack.

---

spyder/widgets/editor.py

Fixes #3322
---------------
Using `encoding.encode` function won't throw an error if the text can't be encoded with the current encoding, instead It will try to guess the text encoding.

PR: Use encoding.encode function in run_code_analysis.

---

spyder/utils/encoding.py

Fixes #3753
---------------
`encodings.write()` will try to save the file with the original encoding as first option.

PR:  Save file with original encoding if possible

---

spyder/utils/encoding.py

In #3929 I forget to catch LookUpError, when encoping text

PR: Catch LookupError when encoding in encode() function

---

spyder/utils/dochelpers.py

inspect.getargspec() doesn't get the function annotations, which causes Help to fail on annotated functions in Python 3. getfullargspec does have the capability, but it doesn't exist in Python 2. Suggested fix provided here.
Fixes #3571.

PR: Use inspect.getfullargspec() in getdoc for PY3 to support annotated functions.

---

spyder/utils/dochelpers.py

PR: Backport PR #3577 - Use inspect.getfullargspec to support annotated functions in the Help pane

---

spyder/plugins/editor.py
spyder/plugins/ipythonconsole.py
spyder/plugins/runconfig.py
spyder/widgets/ipythonconsole/shell.py

PR: Add option to "clear all" variables before running file

---

spyder/widgets/projects/explorer.py
spyder/widgets/variableexplorer/dataframeeditor.py

Fixes #3943
-----------------
There is also another call to this method in https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/variableexplorer/dataframeeditor.py#L432 but I tested and doesn't throw that error

PR: Change setResizeMode to setSectionResizeMode

---

README.md

PR: Update AppVeyor badge in Readme because of move to org account

---

spyder/widgets/panels/scrollflag.py
spyder/widgets/sourcecode/codeeditor.py

- Migration of ScrollFlagArea to panels folder.
- Use panel API.
- Move some functions from the CodeEditor to ScrollFlagArea class.
This is a continuation of the decoupling of code editor panels.

PR: Change ScrollFlagArea panel to use panel API

---

continuous_integration/appveyor/modules_test.bat

This fixes errors in Appveyor with Python 2.7

PR: Don't run pytest tests when running modules_test.bat in Appveyor

---

spyder/widgets/mixins.py

PR: Use QRegularExpression only for Qt 5.5+

---

circle.yml
spyder/app/mainwindow.py
spyder/plugins/tests/test_ipythonconsole.py

Fixes #4012
After making the edit menu correctly enabled, I realize that edit actions wasn't working (I also fixed that)
Changes also fix an error with search menu: Go to line wasn't enabled

PR: Edit menu disable error

---

spyder/app/mainwindow.py

Fixes #4025 
Sorry I introduced this error, I forget to add that variable to the `MainWindow.__init__` I think was the hurry fixing #4022.

PR: Fix error when running cells because previous_focused_widget is not initialized in main window

---

spyder/plugins/editor.py

Fixes #4020 
This also removes the "Run settings" icon. The run toolbar looks like this now:

PR: Add "run selection" icon to run toolbar

---

spyder/widgets/editor.py

PR: Use the "at" symbol to represent the symbol finder everywhere

---

spyder/utils/fixtures.py
spyder/widgets/mixins.py
spyder/widgets/tests/test_editor.py

PR: Add a flag to use case sensitive search/replace

---

spyder/config/main.py
spyder/plugins/editor.py
spyder/widgets/editor.py

Fixes: #564
Fixes: #1170
------------
I made it really simple, just reused some code from #2372

PR: Make Editor tabs movable

---

spyder/widgets/variableexplorer/dataframeeditor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

This handles the case where the data frame contains a NaN and the user specifies the format `%d`. Fixes #4139.

PR: Gracefully handle ValueError in DataFrameModel

---

continuous_integration/appveyor/install.ps1
continuous_integration/travis/install.sh

Tests are failing with the latest Miniconda on Appveyor and Travis.

PR: Use an older Miniconda version for Python 3

---

spyder/tests/tests_py3compat_usage.py
spyder/widgets/panels/edgeline.py
spyder/widgets/panels/manager.py
spyder/workers/updates.py

PR: Fix error edge line in python2.7

---

spyder/utils/tests/test_iofuncs.py

I think this test should be skipped, because SciPy is an optional dependency.

PR: Skip matlab import test if SciPy is not installed.

---

spyder/config/user.py

PR: Try to eval string setting values after decoding in python2.7

---

spyder/widgets/panels/edgeline.py

Fixes #4163
This was caused because the edge line doesn't take in account the width of the codefolding panel.
Although we need a way to define panels with arbitrary position

PR: Fix error edgeline offset, take codefolding panel width in account.

---

spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_autoindent.py

Fixes #4096 
Fixes #4074 
I fixed some issues reported applying hanging indent for long text only
```
a = {
} #not hanging indent
```
```
some_long_name = {
} #hanging indent (8 spaces)
```

PR: More autoindentation fixes

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole.py
spyder/utils/ipython/spyder_kernel.py
spyder/widgets/ipythonconsole/debugging.py

PR: Set new breakpoints in the IPython console while on a debugging session

---

MANIFEST.in

The PyPI release is missing the change log due to a typo that this PR is rectifying.

PR: Fixup MANIFEST.in to include the changelog

---

scripts/spyder.desktop
scripts/spyder3.appdata.xml
scripts/spyder3.desktop
setup.py

See https://github.com/spyder-ide/spyder/pull/4112 for details.

PR: Add AppStream metainfo file

---

spyder/py3compat.py
spyder/utils/help/conf.py
spyder/utils/iofuncs.py
spyder/widgets/editor.py
spyder/widgets/internalshell.py
spyder/widgets/mixins.py

- That function was needed for Python 3.2 compatibility only.
- This PR also fixes a failing test.

PR: Remove u function from py3compat

---

spyder/utils/syntaxhighlighters.py

Add some missing Cython keywords to syntax highlighter.

PR: Fix syntax highlighter missing Cython keywords

---

README.md
circle.yml
continuous_integration/travis/modules_test.sh
doc/installation.rst
spyder/app/tests/pyx_lib.pyx
spyder/app/tests/pyx_lib_import.py
spyder/app/tests/pyx_script.pyx
spyder/app/tests/test_mainwindow.py
spyder/plugins/editor.py
spyder/plugins/ipythonconsole.py
spyder/utils/ipython/start_kernel.py
spyder/utils/site/sitecustomize.py
spyder/widgets/dependencies.py

This PR improve Cython support by adding ".pyx" importing and running abilities to consoles.
- Automatically compile ".pyx" files when importing them with `import` (Enable `pyximport` with file reload option and NumPy support).
- Allow to run ".pyx" file with the "Run" button and the `runfile ` function (Using `cython_inline` function).
- Automatically enable IPython Cython magic.

PR : Add Cython files import and run support

---

continuous_integration/travis/install.sh
continuous_integration/travis/run_test.sh
setup.py

Fixes: #4174
-------
I take the packages that I found in the continuum integration recipes.
I'm not sure if `numpy` should also be added (pandas will install it as a dependency), and if `pillow` if needed (circle-ci recipe doesn't install it)

PR: Add testing requirements to setup.py

---

spyder/app/mainwindow.py
spyder/workers/updates.py

PR: Don't show internet conection errors on startup when trying to check for new releases

---

spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/shell.py

PR: Make %matplotlib magic to really change backends

---

spyder/plugins/externalconsole.py
spyder/widgets/shell.py

PR: Change how to add removal message for the Python console to not make it steal focus

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/projects.py
spyder/utils/tests/test_dochelpers.py

PR: Add missing signal to convert notebooks from the project explorer 

---

spyder/api/panel.py
spyder/widgets/panels/codefolding.py

Fixes: #4147
------
Now It looks like this:
And in darker themes:

PR: Improvements to visual style of code-folding

---

spyder/plugins/editor.py
spyder/utils/introspection/manager.py
spyder/utils/introspection/plugin_client.py
spyder/utils/introspection/tests/test_plugin_client.py

Fixes: #4141
-------------
I think this is ready, but this is causing plugins to be restarted at startup, (normally 1 time, and 2 times when there is a project open)
It's that ok? or how It could be avoided?

PR: Add Spyder PYTHONPATH to PluginClient

---

spyder/widgets/externalshell/pythonshell.py
spyder/widgets/shell.py

Backport PR #4286 to `3.1.x` (it was made by mistake against `master`).

PR: Backport PR #4286

---

spyder/widgets/fileswitcher.py

Changes to make the fileswitcher work with the notebookplugin https://github.com/spyder-ide/spyder-notebook/issues/45

PR: Add support for other plugins in File Switcher

---

spyder/plugins/editor.py

The issue is described in #1170 and reappear after removing `StrongFocus` from the `MainWindow` (#4109)
I added `ClickFocus` to the `Editor` plugin.

PR: Avoid tab scrolling when changing current tab.

---

spyder/utils/programs.py

The current method for querying the username via the `USER` envvar is fragile and may yield to [problems](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859080). This PR proposes to use the `getpass` module from the stdlib instead, which should be more robust according to the [docs](https://docs.python.org/3/library/getpass.html#getpass.getuser).

PR: More robust username query

---

CONTRIBUTING.md
README.md
requirements/requirements.txt
requirements/test_requirements.txt

Fixes #3986 
Fixes #3573
The issue is label for 3.2 but I made it against 3.1.x because It doesn't change anything (only add documentation), and could me merged early.
When creating requirements file I noticed that `flaky` isn't available through conda so I make a little exception for this package

PR: Add Contributing file

---

spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/ipythonconsole/client.py

PR: Add encoding handling to stderr files in the IPython Console

---

spyder/locale/fr/LC_MESSAGES/spyder.po

*Superseeds #4446, targetting the right branch this time :sheep:.*
Some fixes for the French locale of Spyder. Mainly:
* échèle <- échelle (“scale”)
* barre d'outil <- barre d'outils (plural form on “tools”)
* miscellaneous typos like missing ending "s" for some plural forms, weird phrasing, fixes to follow French typography rules, etc.
* translation of a couple of missing messages
*Disclaimer*
I am a French native speaker from France: if some of the modified phrasings were correct Canadian (or elsewhere) French idioms, please let me know and I will be glad to revert the modifications.
Unfortunately, I do not currently have time to check the thousands of lines in the locale file. Hopefully I will be able to have a further look in the future if nobody else does it before.
**Edit:**
Ugh, …

PR: Fix a few typos in the FR locale file

---

spyder/utils/codeanalysis.py

Fixes #4452 
----
The PR corresponds to the #4452 issue. It adds code tags HACK, BUG, OPTIMIZE, !!!, ??? to the common TODO and FIXME.
To keep the most common ones, I did a compromise according to the pep8-350 and many forums/websites relating to this topic.
hopefully I PR-ed pushed pulled all correctly :)

PR: Add more regular code annotation types

---

.gitignore
spyder/config/main.py
spyder/plugins/editor.py
spyder/widgets/editor.py
spyder/widgets/panels/classfunctiondropdown.py
spyder/widgets/panels/tests/test_classfunctiondropdown.py
spyder/widgets/sourcecode/codeeditor.py

This PR adds a class and function dropdown to the top of the editor and below the tabs. This implements #2627.
The idea is to mimic Visual Studio's feature:
**This PR is still a WIP**. I have the very basics of the widget done, but I'm having trouble with:
1. how to integrate it with the editor
2. how to connect the signal to the cursor_move event.
> Note: This PR is currently based against the `v3.1.3` tag. Let me know if this should be changed.
+ Displayed class and method names update as the cursor moves. It will always display the current class and method that the cursor is in.
+ If not in a class or method, "\<None\>" will be displayed.
+ Optionally show line number and part of the call signature
+ Class dropdown is populated with all classes in the file
+ **To discuss:** sorted by …

PR: Add a new panel to show/explore class and methods/functions present in the current file

---

spyder/plugins/editor.py

In PR #4456, I forgot some parts: as suggested by afvincent, I complete the new annotations for the Source toolbox and the Preferences menu.

PR: Complete annotation types in Preferences and Source toolbox

---

spyder/plugins/editor.py

A little usability change, tab stop width is only used when indenting with tabs, and the GUI should reflect that.

PR: Disable tab with setting when indent chars are spaces.

---

spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_autoindent.py

PR: Fix indentation error when a line starts with return but it's not a return statement

---

spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_autoindent.py

Fixes #4475
- indentation chopping text when indent with tabs
- inline comments breaking indentation
no xfail tests in auto_indentation 😄🙈

PR:  Some indentation fixes

---

doc/conf.py
doc/manpage.rst

The first commit adds the manpage configuration for Sphinx. The second commit adds the source of the manpage. The manpage can be generated from the root of the source tree via `sphinx-build -b man doc/manpage.rst build/man`, which will output the manpage under `build/man/spyder.1`.
Closes #4423.

PR: Add manpage for Spyder

---

appveyor.yml
spyder/plugins/tests/test_ipythonconsole.py

Also skip Python 3.5 in Appveyor during the sprint to speed things up.

PR: Skip test_values_dbg because it times out too much

---

spyder/app/mainwindow.py

PR: Handle socket creation errors during start up

---

spyder/config/fonts.py
spyder/config/main.py

After PR #4454 there's no need to have a bigger font size for the Help plugin. This PR addresses that.

PR: Fix font size for the Help plugin

---

spyder/widgets/findreplace.py
spyder/widgets/tests/test_editor.py

PR: Make Shift+Enter search backwards in Find and Replace widget

---

spyder/plugins/shortcuts.py
spyder/widgets/sourcecode/codeeditor.py

Fixes #4496 
Fixes #3405 
----
This also prevents using shortcuts of the form `Shift+<key>`, where `<key>` is a single key (e.g. `Shift+Space`).

PR: Add Shift+Del shortcut to delete lines in the Editor 

---

spyder/utils/external/binaryornot/check.py
spyder/widgets/findinfiles.py

PR: Find in Files style and UI improvements

---

spyder/plugins/shortcuts.py
spyder/widgets/sourcecode/codeeditor.py

PR #4538 was done incorrectly against `master`. This backports it to `3.x`.

PR: Backport PR 4538

---

spyder/plugins/ipythonconsole.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/utils/environ.py
spyder/utils/ipython/spyder_kernel.py
spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/shell.py

PR: Add actions to show sys.path and environment variables contents to the IPython console

---

spyder/config/main.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_autoindent.py

Fixes: #3406
Fixes: #4157
I added configurable shortcuts for indent/unindent, with `Ctrl+[`/`Ctrl+]` as defaults, I didn't change `Tab`/`Shift+Tab` logic because Tab can't be a shortcut (so I leave it hardcoded), also it could interfere with autocompletion 
I didn't add new preferences for simple indentation, It's activated in non-Python files. as discussed in #4157

PR: Add indentation shortcuts and simple indentation for non-Python files

---

spyder/config/main.py

The defaults for indent shortcuts added in #4567 are exchanged. This PR fixes that.

PR: Invert indent shortcuts

---

spyder/widgets/variableexplorer/importwizard.py

This PR fixes #4581 by adding continuous whitespace as an option to the column separator section of the import wizard.
Let me know if this needs a test, and I'll write one.
Currently the data import wizard doesn't play nicely with text data with multiple spaces as delimiters(or maybe I don't play nicely with the data importer ;-). This is common in fixed width data sets like this:
```
FIRST  LAST           STATE     TELEPHONE      AGE   WEIGHT
John   Smith          WA        418-Y11-4111    26    3.0456
Mary   Hartford       CA        319-Z19-4341     5   13.5687
Evan   Nolan          IL        219-532-c301   145   45.7890
```
Putting a `' '` (a space) in a the 'other' text box gives this:
When it could give this:
It looks like this:

PR: Add Whitespace option in the import wizard

---

spyder_pylint/pylint.py
spyder_pylint/widgets/pylintgui.py

I ran into a problem getting the right version of pylint to launch within the plugin since it's not configurable and expects 'pylint' to used for Python 2 and 'pylint3' or 'python3-pylint' to be used for Python 3.
In my configuration (Fedora 25) the system-installed pylint is 'pylint' and 'python3-pylint', however in order to use a newer version, I've installed pylint using pip3 and the --user option to install it under ~/.local. This creates a 'pylint' executable for Python3 in ~/.local/bin.
In order to use the newer version within Spyder, I have to modify my system PATH as well as rename or symlink ~/.local/bin/pylint to 'pylint3' or 'python3-pylint'.
My proposal is to avoid all this by using the pylint module which is already a requirement for Spyder. The module can be imported to …

PR: Use Python module to launch pylint

---

spyder/utils/syntaxhighlighters.py
spyder/widgets/sourcecode/api/folding.py
spyder/widgets/sourcecode/folding.py
spyder/widgets/sourcecode/tests/test_folding.py

Fixes: #4463
Now `IndentFoldDetector` will take in account previous fold indentation before using `CodeEditor.indent_chars`
I tried the solution that I propose in https://github.com/spyder-ide/spyder/issues/4463#issuecomment-301543920 but didn't work very well, the solution that I implemented is partially based in https://github.com/spyder-ide/spyder/issues/4463#issuecomment-301705657

PR: Fold improvements

---

spyder/api/panel.py
spyder/config/main.py
spyder/plugins/editor.py
spyder/widgets/editor.py
spyder/widgets/panels/edgeline.py
spyder/widgets/panels/indentationguides.py
spyder/widgets/panels/linenumber.py
spyder/widgets/panels/manager.py
spyder/widgets/panels/scrollflag.py
spyder/widgets/sourcecode/base.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_panels.py

Fixes: #2987 
I added a floating type panel, and move `edgeline` and `indentguides` to use it.
I didn't find a way to abstract all the logic in the `PanelManager`, and floatings Panels need to have a `set_geometry` method
This is how it looks like, It uses the comments color (same as edgeline)

PR: Add indentation guidelines

---

spyder/utils/syntaxhighlighters.py

Fixes: #4595
I copied this from BaseWebSH highlighter

PR: Add break condition to Markdown syntax highlighter loop

---

README.md
conda.recipe/meta.yaml
doc/installation.rst
requirements/requirements.txt
setup.cfg
setup.py

Fixes #4285 
Also add  `setup.cfg` to create universal wheels

PR: Update Rope to 0.10.5+

---

setup.py
spyder/app/start.py

PR: Add pyopengl to setup.py to fix errors with some Nvidia/Intel drivers

---

spyder/widgets/sourcecode/base.py
spyder/widgets/tests/test_editor.py

PR: Add same behaviour for go to previous cell as the one in Matlab

---

spyder/widgets/editor.py

Fixes #4597 
Original bug was #1170
The solution implemented in 2228e83b656a476683f27e9ddd5e234a08135be6 wasn't the best, focus should be give to the Editor when changing tabs.
I reverted 2228e83b656a476683f27e9ddd5e234a08135be6, and traced the error until `self.tabs.setTabText(index, tab_text)` I'm not sure why this line was causing that error, maybe it raises again the `currentChanged` signal.

PR: Fix unwanted scrolling when selecting tabs

---

spyder/widgets/ipythonconsole/help.py

The 4th argument of `re.sub()` is maximum number of substitutions, not flags.
`re.UNICODE` is the default in Python 3, so it doesn't have to be passed explicitly to re.sub().
Found using [pydiatra](https://github.com/jwilk/pydiatra).

PR: Remove misplaced flags from re.sub() call

---

spyder/app/mainwindow.py
spyder/config/main.py
spyder/plugins/console.py
spyder/widgets/sourcecode/base.py

Fixes: #1525 
~~This isn't ready, I implemented but the behavior isn't the expected, the QMessageBox is shown but for every single line of the traceback (because `traceback_available` signal is emitted for every line).~~
~~any ideas of how I could fix this?~~
I implemented using a QMessageBox with non modal behavior

PR: Show internal errors in a QMessageBox

---

RELEASE.md
setup.py

The problem is there are no wheels for `pyopengl` on Windows or macOS, so people would need a compiler to pip-install Spyder in those platforms.

PR: Add pyopengl to Linux wheels only

---

CONTRIBUTING.md

PR: Add git command for changing base branch to Contributing guide

---

scripts/spyder.bat

Use right python.exe to run spyder when multiple versions of python installed on windows

PR: Use right python.exe to run Spyder when multiple versions of Python are installled on Windows

---

spyder/plugins/ipythonconsole.py
spyder/utils/ipython/kernelspec.py
spyder/utils/ipython/tests/__init__.py
spyder/utils/ipython/tests/test_spyder_kernel.py

Fixes #4632.
This is also needed to create Spyder kernels in `spyder-notebook`.

PR: Move Spyder kernel spec to its own file

---

spyder/app/mainwindow.py

Fixes #4665 
It works with the Notebook plugin when running with PyQt4 (for example)

PR: Don't register external plugins if check_compatibility fails

---

spyder/widgets/variableexplorer/arrayeditor.py

Changed numpy boolean subract operator '-' to np.logical_xor. As suggested in the numpy deprec warning.
Tested locally with no error originally described in #4663

PR: Update ArrayEditor to correct deprecated Numpy operator

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole.py
spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/shell.py

PR: Add detection of external Spyder kernels

---

spyder/app/mainwindow.py
spyder/plugins/editor.py
spyder/plugins/ipythonconsole.py
spyder/plugins/runconfig.py
spyder/utils/ipython/spyder_kernel.py
spyder/widgets/ipythonconsole/client.py
spyder/widgets/tabs.py

Fixes #4418.
This is part of issue #4524.
----
TODO

PR: Implement dedicated IPython consoles

---

spyder/plugins/ipythonconsole.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/utils/sourcecode.py
spyder/utils/tests/test_sourcecode.py
spyder/widgets/editor.py

PR: Add disambiguation for dedicated IPython consoles

---

spyder/widgets/sourcecode/codeeditor.py

As discussed in PR #4651 
---------------------
This leaves the change in the block commenting functionality (a space between the `'#'` and the `'='`).

PR: Revert PR #4651

---

spyder/widgets/findreplace.py

Fixes #358 
----
Supports replacing all instances of the search text with the replace text in a selection of text. Changes find/replace dialog to add buttons for "replace in selection" and "replace all" and removes the "replace all" checkbox. Tweaks behavior of automatically filling the searchbox depending on whether multiple lines were selected.
A refinement would be to either add shortcuts for the three buttons or combine the three buttons into one and use radio/combo to control scope.

PR: Implement "Replace in selection" in the Editor

---

spyder/app/mainwindow.py
spyder/plugins/configdialog.py
spyder/plugins/ipythonconsole.py
spyder/widgets/editor.py
spyder/widgets/tabs.py

* There was a bug after PR #4694, which I fixed here.
* Make drag and drop of tabs in the IPython console to work.
* Use `TexFileIcon` in the Editor tab switcher.
* Fix wording of *Screen resolution* section in Preferences/General. Also remove a repeated option about that.

PR: Fix running in dedicated consoles and other UI fixes

---

spyder/plugins/console.py
spyder/widgets/sourcecode/base.py

PR: Show complete exception (not only the traceback) in error QMessageBox.

---

spyder/utils/sourcecode.py

In #4352 I only add `md` as supported extension for Markdown, this is causing `mdw` files to appear as plain text.
This is a quick fix, a more robust solution should be implemented in spyder reports (https://github.com/spyder-ide/spyder-reports/issues/6), using the languages API (to be developed in spyder4)

PR: Add mdw as markdown extension.

---

spyder/utils/site/sitecustomize.py

Fixes spyder-ide/spyder-notebook#85
- This was only needed for IPython 2, but we don't support that version anymore.
- This was also breaking the display of Dataframes as html tables in spyder-notebook.

PR: Don't set pandas.core.common.in_qtconsole anymore

---

spyder/api/plugins.py

A missing import after the 3.x changes was merged in master
```
def show_compatibility_message(self, message):
"""Show compatibility message."""
>       messageBox = QMessageBox(self)
E       NameError: name 'QMessageBox' is not defined
```

PR: Add missing QMessageBox import

---

spyder/utils/introspection/manager.py

Fixes #3940
After receiving first response from either rope or jedi,
`self.introspection_complete.emit(response)` caused a delay before
`self.info` was set to `None`. This _sometimes_ allowed the response
from the other plugin to pass through. If the command was to open a file, this resulted in a crash. 
Switching these two lines removes the delay in the attribution of `None` value to self.info, which allows to systematically block the second response from the other introspection plugin after the first one has passed through.

PR: Prevent Jedi and Rope to open two previously unopened files simultaneously

---

spyder/config/main.py
spyder/plugins/workingdirectory.py

Those options are conflicting with the console ones, so we have to remove them.
I discovered this during my SciPy talk.

PR: Remove startup options of working directory plugin

---

spyder/app/start.py
spyder/config/base.py
spyder/pyplot.py
spyder/utils/ipython/spyder_kernel.py
spyder/utils/site/sitecustomize.py
spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/importwizard.py
spyder/widgets/variableexplorer/utils.py

Fixes ContinuumIO/anaconda-issues#3287
----
This also prevents Spyder from crashing in macOS if locale is not defined correctly there.
TODO

PR: Prevent potential problems when importing third-party modules

---

spyder/utils/editor.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/tests/test_editor.py

Fixes:  #4778
Fixes: #4777 
Related to #4732 (I only unify goto_line, some functions missing)
Should I completely delete the `Codeeditor.go_to_line()` and change its callings by `TextHelper(editor).goto_line()`?
~I'm also planing to merge the remaining functions of `TextHelper` that are duplicated in the `CodeEditor`~ to be addressed after improving Editor coverage.

PR: Fix some code folding related errors

---

spyder/app/mainwindow.py
spyder/utils/site/sitecustomize.py
spyder/widgets/helperwidgets.py

Fixes #3609
----
Add an icon to the MessageCheckBox while avoiding the unclickable update message issue in PyQt5 and preserving backward compatibility with PyQt4.
Please revised that this fix works correctly in PyQt5. I cannot install PyQt5 alongside PyQt4 without messing my installation on my current setup. Feel free to give me advice to improve the way I can contribute.

PR: Add icon to MessageCheckBox while avoiding unclickable  issue

---

spyder/widgets/sourcecode/codeeditor.py

Fixes #4734 
----
The font height and pixmap height were in incompatible units when DPI scaling is on.  Dividing the qpixmap height by self.devicePixelRatio() converts it into device independent units.  See http://doc.qt.io/qt-5/qpixmap.html#devicePixelRatio

PR: Update pixmap height calculation

---

spyder/widgets/sourcecode/codeeditor.py

Fixes #3166
This was also causing the fold panel to be empty.

PR: Avoid visible_blocks to be empty when first visible block is wrapped

---

spyder/widgets/editor.py
spyder/widgets/sourcecode/codeeditor.py

Fixes #4763
----
It seems like the ctrl key release event never reach the [EditorStack ](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/editor.py). It seems to be swallowed by the [CodeEditor](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/sourcecode/codeeditor.py).
The proposed solution to solve this issue it to install an eventFilter on each `editor` added to
the `EditorStack` and to move the code that is in the `keyReleaseEvent` in the `eventFilter` method.
There may be a more elegant way to solve this directly in the CodeEditor class. I can look into it if this approach is preferred.

PR: Fix tab does not switch when ctrl is released issue

---

spyder/app/tests/test_mainwindow.py

The print test segfaults too frequently.

PR: Delete print test because it segfaults too frequently

---

spyder/utils/ipython/style.py
spyder/widgets/ipythonconsole/shell.py

Fixes #4806
----
- Changes in `style.py` is to let the text highlighting color in the IPython console to be the same as for the Spyder main application instead of using the light gray color that was hard-coded.
- Changes in `shell.py` is to set the _matched-bracket_ highlighting color to the color defined in Spyder
preferences instead of using the hard coded light gray color.

PR: Make highlighting colors in the IPython Console match those used in the Spyder Editor

---

spyder/widgets/sourcecode/codeeditor.py

PR: Set eol_chars in cloned editor on split editor panes

---

spyder/plugins/editor.py

Both the spinbox and slabel of the `edgeline_spin` and `occurrence_spin`
widget were not disabled properly when their respective checkbox was
unchecked.

PR: Fix enable/disable spinbox bug in Editor preferences panel

---

spyder/plugins/editor.py

PR: Update only current editor stack when moving tabs.

---

appveyor.yml
continuous_integration/travis/install.sh
continuous_integration/travis/test-qt4.sh
continuous_integration/travis/test-qt5.sh

This way we will always be sure that Spyder is not broken when we make new releases of those packages.

PR: Install qtpy and qtconsole from Github when testing

---

spyder/app/tests/test_mainwindow.py
spyder/widgets/editor.py

Fixes: #4453 
Fixes: #4442 
I tried different solutions, like returning the focus, or checking if the widget is alive, but didn't work
This solution works better, and I think that's a cleaner solution (thanks @goanpeca for the idea)
Only two of the message box was related two the errors mentioned above, but I also change the others because they could raise the same error (but that use cases are less common)

PR: Save a reference to messagebox in EditorStack to avoid memory to be freed.

---

spyder/widgets/sourcecode/base.py
spyder/widgets/tests/test_editor.py

Fixes #4754
----
**Solves multiple issues with the code for shifting lines vertically in the editor:**
- Solve out of range error when trying to shift up a block of code that is already at the top of the file
- Code remains properly selected after shifting down multiples lines of code
- Code remains properly selected when shifting down a single line of code with an empty line
- Fix various issues when shifting up or down code at the end of the file:
- when shifting penultimate line down, an extra empty line was added at the end of the file
- when shifting last line down, an extra empty line was added above and below.
- when shifting last line up, an extra empty line was added at the end of file

PR: Fix shifting code selection issues in the Editor

---

spyder/plugins/explorer.py
spyder/plugins/ipythonconsole.py
spyder/plugins/projects.py
spyder/utils/programs.py

PR: Fix Run option in File and Project explorers

---

spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/shell.py

This is no longer needed. It should have been removed in 3.2, but I forgot to do it.

PR: Remove capture_dir_change method of IPython console shell widget

---

spyder/widgets/comboboxes.py

PR: Check that combobox text is not empty string before emiting valid signal

---

spyder/widgets/mixins.py
spyder/widgets/tests/test_editor.py

Fixes: #4943 
I tried to use @stonebig suggestion of `isidentifier()` but It was not possible because it was used in a regex expression, I instead improve the regex according in this answer https://stackoverflow.com/a/10134719/1335555

PR: Fix error when the selecting an unicode word

---

spyder/widgets/projects/tests/test_project.py
spyder/widgets/projects/type/__init__.py

Fixes: #4839 
When saving loading files from project configuration the order wasn't preserved, `set` doesn't preserve the order (except in python3.6).
Searching I found that using `collections.OrderedDict` is maybe the best way to delete duplicates and preserve order regardless the python interpreter implementation.

PR: Preserve order when saving/loading files from a project.

---

spyder/app/mainwindow.py
spyder/app/restart.py

Fixes #4444
This adds the spyder icon to the mac dock when running from bootstrap.

PR: Add icon earlier when running application

---

spyder/plugins/shortcuts.py

The rows of the shortcut table have unneccesarily large heights. This patch reduces the height to the minimal possible height, so that more entries are visible -> increased usability.
before:
after:

PR: Reduce row height in shortcut dialog

---

spyder/widgets/ipythonconsole/shell.py

PR: Fix shortcut to make array builders appear in the IPython Console

---

spyder/app/mainwindow.py
spyder/plugins/help.py
spyder/utils/qthelpers.py
spyder/widgets/browser.py
spyder/widgets/editortools.py
spyder/widgets/explorer.py
spyder/widgets/variableexplorer/namespacebrowser.py

fixes #4953 
`create_control_layout()` provides a unified way of creating the required layouts. Here's an example how it will look like:
The panes with multiple lines of control widgets (bottom panes in the screenshot) can be addressed at a later time.

PR: Unify layout for panes and widgets

---

spyder/widgets/findreplace.py
spyder/widgets/tests/test_editor.py

PR: Remove regex escape characters from replacement string on the Find/Replace widget

---

spyder/widgets/browser.py
spyder/widgets/findreplace.py
spyder/widgets/mixins.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/tests/test_editor.py

It now looks like this:
---------------------------------
Edit:
Fixes #4001.

PR: Show the number of matches in the Find/Replace widget

---

spyder/app/mainwindow.py

Fixes #4829 
------------------------------------------------
In Windows running something like `3 or True` will return `3` however running something like `True or 3` will return `True`. Also running something like `False or 3` will return 3. As a reference:

PR: Fix setting SPYDER_DEBUG variable on Windows

---

spyder/utils/site/sitecustomize.py

PR: Prevent subprocess.Popen calls to create visible consoles on Windows.

---

spyder/utils/syntaxhighlighters.py
spyder/utils/tests/test_syntaxhighlighters.py

Fixes #4884 
----
As suggested in #4884 the string prefixes should be highlighted with the same color as the string itself. The list of all possible prefixes is given [here](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) for Python 3 and [here](https://docs.python.org/2/reference/lexical_analysis.html#string-literals) for Python 2. 
I have added a small test as well but not sure it is actually necessary. Is it?

PR: Add all possible string prefixes for syntax highlighting

---

spyder/widgets/ipythonconsole/namespacebrowser.py
spyder/widgets/ipythonconsole/shell.py

This solves issue #4504  but will sometimes display two `in[]`

PR: Display prompt after errors

---

spyder/config/tests/test_user.py
spyder/config/user.py

PR: Allow values with '%' in config system

---

README.md
spyder/plugins/tests/test_ipythonconsole.py

This also removes the reference to our DMG installers because they are outdated.

PR: Increase waiting time and repetitions for tests that enter debugging

---

appveyor.yml
continuous_integration/circle/install.sh
continuous_integration/travis/install.sh
requirements/test_requirements.txt
setup.py
spyder/widgets/pathmanager.py
spyder/widgets/tests/test_pathmanager.py

This PR is to expand the new feature (PR: https://github.com/spyder-ide/spyder/pull/4756) that allowed to check and uncheck paths in the pathmanager to quickly add or remove them from the Spyder's path list.
With this PR, paths that are unchecked won't be added to the PYTHONPATH environment variable when synchronizing with  Spyder's path list. Note that the "synchonize Spyder's PYTHONPATH with PYTHONPATH environment variable" feature is valid only for Windows environment.
Also, added a test for the synchonize feature.

PR: Make inactive paths to be ignored when Spyder's path list is synchronized with PYTHONPATH on Windows

---

spyder/plugins/ipythonconsole.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/ipythonconsole/client.py

PR: Add test with non-ascii directory for consoles stderr file

---

spyder/plugins/tests/test_editor_introspection.py
spyder/utils/introspection/jedi_plugin.py
spyder/utils/introspection/manager.py
spyder/utils/introspection/plugin_client.py
spyder/utils/introspection/rope_plugin.py
spyder/utils/introspection/tests/test_jedi_plugin.py
spyder/utils/introspection/tests/test_manager.py
spyder/utils/introspection/tests/test_plugin_client.py
spyder/utils/introspection/tests/test_rope_plugin.py
spyder/utils/introspection/utils.py
spyder/widgets/sourcecode/base.py

Fixes: #4410
Supersedes #4915
Undo some changes of  #4263
At the moment the spyder path is only used by jedi

PR: Send Spyder python path to introspection plugins

---

spyder/widgets/variableexplorer/tests/test_utils.py
spyder/widgets/variableexplorer/utils.py

Fixes #4221 
----
This PR
1. Improves how any object is displayed in the Variable Explorer. Now objects will be shown as `foo object of bar module` (except for know objects, like Dataframes).
2. Doesn't try to display subclasses of list, dict and tuple, to avoid things like issue #4221 (which was using a generalization of a dict that doesn't have an optimized `repr`).
3. Applies `value_to_display` recursively to the elements of lists, dicts and tuples. This prevents freezes in the Variable Explorer when people add objects with huge `repr`'s as elements of those collection types.
Screenshots:
*Before*
*After*
----
TODO:
[skip pep8]

PR: Make value_to_display more robust

---

spyder/widgets/editor.py

Fixes: #4844 
I also move some logic out to the editor to the TabSwitcher widget

PR: Deactivate editor actions when Tab Swither is shown

---

spyder/plugins/editor.py

Fixes #4681 
I implement another approach that could be less error prone than manually checking for the first line of code.
I take advantage that when ipdb stops, the editor goto the line being debugged.
This could be improved when addressing #528 and adding a variable (or method) that will return the current line being debugged.

PR: Don't run continue when starting debug if there is a breakpoint in the first line with code.

---

spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_warnings.py

PR: Fix traceback error when selecting Next/Previous warning/error

---

spyder/otherplugins.py

Fixes #4851.
Fixes spyder-ide/spyder-notebook#114.

PR: Skip package names that end in certain suffixes when loading third-party plugins

---

spyder/widgets/sourcecode/codeeditor.py

Accept keyboard event in CodeEditor to avoid it being handled by the parent.
Not accepting the event cause that the editor will lose the focus when pressing <Tab>, maybe other malfunctions could be caused too.
I introduced this error in #5002 sorry 😞

PR: Fix error Editor loosing focus

---

spyder/widgets/findinfiles.py

PR: Avoid KeyboardInterrupt to raise an error in waitingspinner

---

spyder/plugins/editor.py
spyder/widgets/editor.py
spyder/widgets/editortools.py

Fixes #4705
Fixes 3 issues related to splitting the Editor in master branch :
First issue :
----
**Steps to reproduce the problem:**
- Open Spyder
- Split the Editor through the cog menu
**Traceback:**
_Traceback (most recent call last):
File "C:\Users\jsgosselin\spyder\spyder\widgets\editor.py", line 2274, in 
lambda: self.split(orientation=Qt.Vertical))
File "C:\Users\jsgosselin\spyder\spyder\widgets\editor.py", line 2335, in split
unregister_editorstack_cb=self.unregister_editorstack_cb)
File "C:\Users\jsgosselin\spyder\spyder\widgets\editor.py", line 2269, in init
self.register_editorstack_cb(self.editorstack)
File "C:\Users\jsgosselin\spyder\spyder\plugins\editor.py", line 1241, in register_editorstack
editorstack.set_outlineexplorer(self.outlineexplorer)
File …

PR: Fix unable to split editor

---

spyder/widgets/ipythonconsole/shell.py

Fixes #5158 
I don't know why but using `super` was failing completely in PyQt4 and now some Windows users report that it also fails in PyQt5.
Overriding completely `_handle_error` (by taking the code it uses in `qtconsole`) fixes the issue completely.

PR: Don't use super in _handle_error method of IPython console

---

spyder/plugins/editor.py
spyder/widgets/editor.py
spyder/widgets/editortools.py

Fixes 2 issues related to splitting the Editor in 3.x branch.
**Important:** These issues were fixed in the master branch with PR #5083

PR: Fix RuntimeError and AttributeError when using outline and split code editor

---

RELEASE.md
setup.cfg
spyder/plugins/tests/test_ipythonconsole.py

Fixes #5144 
Even though all our dependencies now support Python 2 and 3, we can't create universal wheels because we want our `entry_point` name to depend on the Python version being used.

PR: Stop creating universal wheels

---

spyder/widgets/sourcecode/codeeditor.py

PR: Fix unblock comments

---

spyder/config/main.py
spyder/plugins/ipythonconsole.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/ipythonconsole/shell.py
spyder/widgets/variableexplorer/namespacebrowser.py

Fixes #313
----
When clicking on the button, %reset is called in the corresponding
IPython console with `force=True`, i.e. no confirmation is asked from
the user before doing it.

PR: Add a button in the Variable Explorer toolbar to reset namespace

---

spyder/utils/programs.py

Fixes #5165.
Attempt to fix #5165 based on the suggestion to use `get_python_executable()` from @jitseniesen 
I tried to run the tests but got errors which seem unrelated to my changes (they also occur in clean 3.x branch.)

PR: Use get_python_executable to run in external terminals

---

doc/variableexplorer.rst
spyder/config/base.py
spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/dataframeeditor.py
spyder/widgets/variableexplorer/tests/test_collectioneditor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py
spyder/widgets/variableexplorer/utils.py

Fixes #3758 
----
Hi team, 
This is a proposal in order to solve #3758. 
In addition to the support of pandas `DatetimeIndex` (#3849) in the Variable Explorer it is possible to support all pandas `Indexes`. 
Results are exactly the same as before for `DatetimeIndex` and very similar for all other types (`RangeIndex`, `MultiIndex`, `CategoricalIndex`, etc.).

PR: Support for all Pandas indexes in Variable Explorer

---

spyder/config/main.py
spyder/plugins/editor.py
spyder/widgets/editor.py

Fixes #4081 
----
Sorry about the diff.  I'm not sure why so many lines showed up?
I used `Ctrl+Alt+Shift+,`  (<) and `Ctrl+Alt+Shift+.` (>) for the Previous and Next based on shortcuts in Eclipse to move to the previous/next error in compiled source.  When I used the `<` and `>` in the definition, it didn't work, thus the `,` and `.`.  I also didn't know if I needed tests to specifically test the shortcut action since the actual functionality already existed.  I couldn't find existing tests for other shortcuts, although I did find some for menu options.
Thanks!

PR: Add keyboard shortcuts for Next|Previous Warning/Error

---

spyder/utils/site/sitecustomize.py

PR: Fix calling pdb.pm() in a console

---

spyder/widgets/explorer.py

Fixes #2406 
This pull request fixes issues in #2406, plus a few minor improvements
Changes:
* Add "Open With OS" to all files, but not folders. This action opens the selected files with the default program.
* Remove "Open" from folders, because it was a duplicate functionality of "Open in external file browser"
* Add multi-select (ctrl / shift + click)
* Remove global options from context menu. These are not file related actions and are all present in the gear menu on the top right of the file explorer.
* Rename "Open in external file browser" to the more commonly used "Show in Folder" (MacOS remains "Show in Finder").
* Make "Show in Folder" action highlight the file in Windows Explorer. Previously it would open the folder but not highlight the file. MacOS already has this implemented, …

PR: Some File Explorer Enhancements

---

spyder/config/main.py
spyder/plugins/configdialog.py
spyder/plugins/editor.py
spyder/widgets/editor.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/tests/test_codeeditor.py

Fixes #3345
Hi team, 
This is an attempt to solve #3345 and #2063: I added an option (default to `False`) to enable the user to scroll past the end of the document in order to have the last line of code on top of the screen (without having to added unnecessary blank lines). 
I don't know if this is an option you are willing to add to Spyder. I find it very useful but that is not my call :-)
The option is already available in QtPlainTextEdit (`setCenterOnScroll(True)`) so it did not add a lot of complexity to the editor code. The `scrollflagarea` does not need to be modified.
For some reason however I can't find a way to update the editor immediatly after adding the option. The tab that has focus is not updated while the others are updated. As soon as I add a new line (or remove one) it …

PR: Enable scrolling past the end of the document

---

spyder/widgets/editor.py

Fixes: #5226 
I think the error was the unnecessary side effect of `_get_previous_file_index`, although I wasn't able to reproduce #5226

PR: Editor historystack improvements

---

spyder/app/mainwindow.py

This error happens when moving from Anaconda envs to virtualenvs on KDE because Anaconda doesn't recognize `breeze` as a Qt theme, and so Spyder crashes at startup.

PR: Apply window style only if it's not None

---

spyder/config/utils.py
spyder/widgets/editor.py

Fixes #4156.
This PR:
1. Shows a much smaller set of supported extensions on Windows because extensions can't be hidden from the dialog on that platform.
2. Don't show any filter on KDE because they make the dialog incredible slow there.
3. Optimize the method used to show the dialog.

PR: Fix some issues with the Editor Save dialog

---

spyder/plugins/ipythonconsole.py
spyder/widgets/ipythonconsole/shell.py

Fixes #5053.
`kernel_client` can be None if the console failed to started for whatever reason.

PR: Don't show errors when kernel_client is None

---

spyder/widgets/panels/codefolding.py
spyder/widgets/sourcecode/api/decoration.py
spyder/widgets/sourcecode/base.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_extra_selections.py
spyder/widgets/sourcecode/utils/decoration.py

Fixes: #5176 
I'm not sure if adding `DecorationManager` to the `TextEditBaseWidget` is ok (commit f408110), or should `DecorationManager` belong to `CodeEditor` and use `try..  except` in `TextEditBaseWidget` methods

PR: Unify how extra selections are added to the Editor

---

spyder/widgets/variableexplorer/arrayeditor.py
spyder/widgets/variableexplorer/tests/test_arrayeditor.py

PR: Prevent hard crash when inspecting certain structured arrays

---

spyder/plugins/editor.py

Fixes: #5131
I think this could be improved but that will need a refactoring of how actions are created, `create_action` logic could be moved to `__init__` method of `SpyderAction` and that will allow to inherit from that class, and create a  `CheckableEditorAction` and abstract the logic in that class. (Although that is out of the scope of this PR)

PR: Remove duplicated logic in Editor checkable Actions

---

doc/variableexplorer.rst
spyder/config/base.py
spyder/utils/ipython/spyder_kernel.py
spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/importwizard.py
spyder/widgets/variableexplorer/objecteditor.py
spyder/widgets/variableexplorer/tests/test_utils.py
spyder/widgets/variableexplorer/utils.py

Fixes #2355
----
`set` is now a supported type in the variable explorer. Now I chose the `Qt.darkGreen` color as it was not already used for other objects: if that is not ok there are some other colors left :smile:

PR: Support for sets in the Variable Explorer

---

continuous_integration/circle/modules_test.sh
spyder/utils/introspection/jedi_plugin.py

We were using a deprecated method without noticing it, and that was the cause of our incompatibility with the latest Jedi release.

PR: A couple of fixes for Jedi 0.11

---

spyder/widgets/variableexplorer/arrayeditor.py

Fixes #5003 
By default, the validator uses the system locale, which may use a comma as a decimal point. I don't think, we'd want localization here. Python itself does always use a decimal point and that's what we should do as well.

PR: Fix editing floats in array editor

---

spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/tests/test_collectioneditor.py

PR: Enable sorting by values in Variable Explorer

---

spyder/plugins/editor.py
spyder/widgets/editor.py

Fixes #5271
----
- When closing a file in a given Editorstack, a signal is emitted with the index of the file relative to its position in the tab bar of this Editorstack.
- Files are then closed in every other Editorstack using this index.
- Problem arises when files are ordered differently across Editorstack tab bars.
- Editorstacks data order are sync with the tab order of their respective tab bar in the `move_editorstack_data` method.
- Instead of emitting an index from the Editorstack from which the file is closed, we emit the name of the file instead.
- The good index corresponding to this filename is then retrieved in each Editorstack using its data.
- The file is then closed using this index instead.
After the changes made in PR #4850, I propose that we move the …

PR: Sync correctly the closing of files in multiple editorstacks.

---

spyder/widgets/variableexplorer/tests/test_utils.py
spyder/widgets/variableexplorer/utils.py

Fixes #5313
---------
To fix this issue we can remove the chunk of code that is under `elif iterate:` (in [`is_supported`](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/variableexplorer/utils.py#L511) function) but I did not feel confortable about it. There may be a reason for this piece of code that I am not able to see right now. 
As a compromise I just turned it off by default but it is still there in case we figure out why it was here in the first place.
Does it seem acceptable?

PR: Display all lists in the variable explorer

---

spyder/widgets/ipythonconsole/debugging.py
spyder/widgets/mixins.py

Fixes #5202 
------------------------------------------
Edit:
Add reference to the issue

PR: Fix history browsing while debugging

---

spyder/plugins/workingdirectory.py
spyder/widgets/explorer.py

PR: Add handling for OSError's when changing directories.

---

spyder/app/mainwindow.py

Fixes #5289
Related to Issue #1105 and PR #4756
----
- Made the [remove_path_from_sys_path ](https://github.com/spyder-ide/spyder/blob/master/spyder/app/mainwindow.py#L2496) method more robust
- Made the [get_spyder_pythonpath ](https://github.com/spyder-ide/spyder/blob/master/spyder/app/mainwindow.py#L2486)  method return  only the active spyderpaths.
----

PR: Prevent unchecked paths in the pathmanager to be added to the IPython console sys.path

---

spyder/widgets/variableexplorer/namespacebrowser.py

Fixes #5330
-------
This is a temporary fix waiting for #5341 (in Spyder 4). 
@ccordoba12 I was not really sure what you meant so the patch is very simple: just catch the error and display an error message to the user.

PR: Add an error message when failing to serialize an object

---

spyder/app/mainwindow.py

Fixes #5305
Related to #5114
See: https://github.com/spyder-ide/spyder/pull/5129#discussion_r136875502

PR: Make Ctrl+C to quit Spyder on Posix systems

---

.gitignore
spyder/config/base.py
spyder/widgets/projects/type/__init__.py

After the projects rewrite  #3377 `.spyderproject` was still in some places, e.g. `.spyproject` wasn't ignored because the `.gitignore` wasn't updated

PR: Change spyderproject for spyproject in some missing places.

---

spyder/app/mainwindow.py
spyder/interpreter.py
spyder/plugins/configdialog.py
spyder/plugins/console.py
spyder/plugins/editor.py
spyder/plugins/findinfiles.py
spyder/plugins/projects.py
spyder/plugins/runconfig.py
spyder/plugins/workingdirectory.py
spyder/utils/iofuncs.py
spyder/utils/misc.py
spyder/widgets/explorer.py
spyder/widgets/findinfiles.py
spyder/widgets/internalshell.py
spyder/widgets/pathmanager.py
spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/namespacebrowser.py
spyder_profiler/widgets/profilergui.py
spyder_pylint/widgets/pylintgui.py

Fixes: #5099
I think that returning home directory is better than returning None, because the calls of getcwd expect a directory, and returning None will cause other errors
Maybe a warning should be printed when falling back to home directory
I change it everywhere, except the tests and ipykernel file

PR: Add a safe getcwd function to handle errors when the current working was deleted

---

spyder/app/mainwindow.py
spyder/widgets/editor.py
spyder/widgets/fileswitcher.py

Fixes #5317 
Issues #5317 occurs when  `self.update_fileswitcher_dlg()` is called in the method [remove_from_data](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/editor.py#L1205) right after the last file has been closed in the Editor.
To fix this issue, I propose that we remove all calls to update the fileswitcher from the [Editor](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/editor.py) and the [MainWindow](https://github.com/spyder-ide/spyder/blob/master/spyder/app/mainwindow.py) and move it to the `show` method of the [FileSwitcher](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/fileswitcher.py).

PR: Fix crashing of the fileswitcher after closing the last file of the Editor.

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/ipythonconsole.py
spyder/utils/ipython/start_kernel.py
spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/shell.py

Fixes #5296 
Fixes #4856 
This also:
* Waits until the prompt is ready before hiding the loading animation.
* Increases time_to_dead check to avoid spurious prompts.
TODO:

PR: Wait until console is ready before executing code for dedicated consoles

---

spyder/widgets/variableexplorer/dataframeeditor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

Fixes #5361
-----
The error is caused by a bug in pandas. This PR just displays an error message to the user.

PR: Add an error message when sorting a dataframe on categorical dtypes 

---

spyder/widgets/sourcecode/codeeditor.py

PR: Use indentation preferences to comment/uncomment.

---

spyder/plugins/base.py
spyder/plugins/editor.py

PR: Handle 'unlocked panes' state for undocking without generating a new window

---

requirements/requirements.txt
spyder/plugins/ipythonconsole.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/ipythonconsole/client.py

This address https://github.com/ContinuumIO/anaconda-issues/issues/6557#issue-264362196

PR: Make consoles to start without an stderr file

---

spyder/config/main.py
spyder/plugins/editor.py
spyder/utils/sourcecode.py
spyder/widgets/editor.py

This PR adds an option to the editor to convert EoL characters on save.
It simply adds another check to the `widgets.editor.EditorStack.save()` method, right after the remove_trailing_whitespace action.
The configuration was added to the `Editor -> Advanced settings` tab in the preferences and looks like so:
**Note:** At the time of submitting this PR, no unit tests are included - I might need some help with that if it's something I need to add. (e.g.: where are tests located? What's the procedure for testing something like this?)
This fixes #5365.

PR: Add an option to the Editor to convert EOL characters on save

---

spyder/widgets/editor.py
spyder/widgets/tests/test_editor.py

Fixes #5475.  
In the editor menu, the option for 'Show in external file explorer' was shown multiple times, once for each time the editor panel was split.  This fix removes the code that changed a list parameter.

PR: Fix EditorSplitter menu_actions and add test.

---

spyder/app/mainwindow.py
spyder/widgets/dependencies.py

By default, Qt uses an unnecessarily large row height for tables. This results in not many rows being visible in the dependency dialog.
This patch reduces the row height of the dependency table.
Before:
After:

PR: Reduce row height in dependencies dialog

---

spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/shell.py

Fixes: #5558
I'm not sure if it's the best solution because the `Shift+Esc` shortcut isn't replaced, instead a new shortcut is added for the same action

PR: Make clear line shortcut configurable in the IPython console

---

spyder/widgets/comboboxes.py

PR: Add clear button to find comboboxes

---

spyder/utils/ipython/spyder_kernel.py

PR: Add validation to not publish pdb_state after gettings values of variables

---

spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_breakpoints.py

Fixes issue #2179.
1.  The unit tests were written before the change to make sure the change fixed the bug reported.
2.  I refactored the code slightly to keep my change cleaner.  I hope that's OK.
3.  With the unit tests, in the `clear_breakpoints` method, I put a note regarding the `del`.  It's not calling the `__del__` in the class.

PR: Fix syncing of line number and plugin list for breakpoints and add unit tests.

---

CHANGELOG.md
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py
spyder/widgets/variableexplorer/tests/test_texteditor.py

These tests were making other tests to fail in strange ways.

PR: Skip some dataframe tests on Linux

---

spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/tests/test_codeeditor.py

Fixes #5588
Sorry for the two char indentation, but the strict 80 char line limit give me really a hard time here. I don't see how one could format this reasonably otherwise without changing functionality (i.e. pre-evaluating `cursor.block().text()` and/or `__unmatched_braces_in_line()` even when that is not necessary because of `not key_matches_next_char`).

PR: Do not overwrite unmatched braces

---

spyder/widgets/findreplace.py
spyder/widgets/tests/test_editor.py

fixes #5386
Perfroming `replace_find()` and `replace_find_selection()` with an invalid regexp used to raise an exception. After this patch, they will do nothing and silently return.

PR: Catch search regexp error while doing replace/find

---

spyder/app/mainwindow.py
spyder/plugins/editor.py
spyder/widgets/editor.py
spyder/widgets/fileswitcher.py
spyder/widgets/sourcecode/codeeditor.py

PR: Make the fileswitcher aware of split editorstacks

---

spyder/widgets/explorer.py
spyder/widgets/projects/explorer.py

fixes #5594 
The fix works, even though, I'd recommend a change in the design. IMHO `setup_view()` should be part of the `__init__`, because it's necessary to obtain a fully functional (even if maybe emtpy) widget.

PR: Fix crash on empty project explorer context menu

---

bootstrap.py
doc/options.rst
spyder/app/cli_options.py
spyder/app/mainwindow.py

Fixes: #5495
- Deprecate --show-console
- Add hide console cli parameter

PR: Change default behavior of --show-console option

---

spyder/app/tests/test_mainwindow.py

It's generating a segfault lately.

PR: Skip test_issue_4066 in our CIs with PyQt >= 5.9

---

spyder/widgets/variableexplorer/arrayeditor.py
spyder/widgets/variableexplorer/tests/test_arrayeditor.py

PR: Handle 3d empty numpy arrays

---

spyder/widgets/findreplace.py

Based on [#5386] in which the user did not realize that he was searching with an invalid regular expression.
This patch gives feedback on invalid regular expressions by coloring the search field and adding a tooltip.

PR: Better feedback for regexp errors in find/replace

---

spyder/widgets/fileswitcher.py

PR: Set focus for filter line when doing symbol search

---

spyder/widgets/findreplace.py
spyder/widgets/tests/test_editor.py

Fixes #5494
the regex `\\(?![nrtf])(.)` will replace escaped characters like `\$`, `\#` for `$`, `#`; but won't replace `\n`, `\r`, `\t`, `\f`, for `n`, `r`, `t`, `f`

PR: Don't unescape control characteres in replace in selection

---

spyder/widgets/editor.py

PR: Add validation for mimedata2url in Editor's dragEnterEvent

---

spyder/plugins/maininterpreter.py

Fixes #5402.
In issue #5402, the call to sys.version_info was returning `b''` instead of `b'3'`.  The ValueError was a result of calling int() on an empty bytes value.  The change checks for this exception and treats it the same as the call to `programs.is_python_interpreter()`.
I don't know why the subprocess call with the program name and -h option would work in `is_python_interpreter()`, but the -c option call from `warn_python_compatibility` wouldn't returning a valid value.  The assumption made was that if the -c option doesn't work, then something else might be wrong with the interpreter, so it switches back to the default.

PR: Fix ValueError when switching Python interpreters

---

bootstrap.py
spyder/app/cli_options.py
spyder/app/mainwindow.py
spyder/app/tests/test_cli_options.py

Fixes #5639.
I tried to minimize the changes by keeping the return value from `cli_options.py` the same as it was before, even though `parse_args` returns one value instead of two.

PR: Convert command line options from optparse to argparse

---

spyder/images/splash.svg

Fixes #5667 
Previous Splash:
New Splash:
I decided that I would be easier to include editable text and instructions for use in the svg file.
splash.svg looks like this in Inkscape:
> You haven't added new icons to Spyder. Please leave decisions about what
icons to use to us :)
I'm glad I only changed the splash screen :)

PR: Splash SVG font change and convert font to path

---

RELEASE.md
setup.py

This will avoid us to build wheels for Linux.

PR:  Simplify how pyopengl is declared in setup.py

---

spyder/plugins/editor.py
spyder/widgets/editor.py

Fixes #5776.
The code calling `has_filename` and `is_file_opened` was sometimes checking for a None or False value using `if not index`.  This allowed the code to skip index 0 as a valid value.
I also added docstrings because I think it's confusing that a function called `has_filename` would return an integer and not a boolean.  Additionally, `is_file_opened` can return a boolean or an integer depending on the parameter value.

PR: Adjust calls to use has_filenames return value of None

---

spyder/utils/help/conf.py

This fixes #5514 by disabling smartypants quotes in sphinx to fix the crash in the help widget.  See #5514 for more details 
This is a work around of course, but it is simple. Hopefully next time anaconda compiles Qt the problem will be fixed.

PR: Disable smartpants quotes in Sphinx to prevent crash with MathJax

---

spyder/plugins/editor.py
spyder/widgets/editor.py
spyder/widgets/tests/test_save.py

Fixes #5703.
This affected `save()`, `save_as()`, and `save_copy_as()` directly.  Also added changes for `set_todo_results()` and `set_analysis_results()` as they were affected by the issue of using the same index across editor stacks.

PR: Change for file save on split editor when tabs are moved

---

spyder/plugins/editor.py

Fixes #5791 
-------------------------
Thanks to @CAM-Gerlach for pointing this out :+1:

PR: Change pep8 check_executable for pycodestyle.

---

README.md

Add open collective urls and links on README
https://opencollective.com/spyder
---
To see how it looks [click this](https://github.com/goanpeca/spyder/blob/516e6f0573e07a758c9cca03959a275d4d578cf2/README.md)

PR: Announce that Anaconda stopped funding Spyder and add Open Collective URL

---

spyder/plugins/editor.py

Fixes #2883 
Before PR #3824, Issue #2883 was hard to reproduce. But now that separate windows are created by default when undocking widgets, this issue has become easily reproducible and is much more annoying. One simply has to undock the editor and click on the outline explorer to trigger it (see animation below).
This is due to the fact that a `setVisible(True)`, `setFocus()` and `raise_()` is systematically called on the editor dockwidget in the [load](https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor.py#L2033) method, which is the method that is connected to the action of clicking on the outline explorer. To fix Issue #2883, we simply have to prevent these calls when the editor is in a separate window and call `setFocus` and `raise_()` on this separate window …

PR: Prevent Editor dockwidget to become visible when clicking on the outline explorer if the Editor is in a separate window

---

spyder/utils/external/lockfile.py

Fixes #4186 
----
Instead of relying on the process name, up to the first three command line arguments are reduced to their basenames and compared against 'spyder', 'spyder3', and 'bootstrap.py'.
This should mimic the existing behavior and address cases where the process name does not show spyder.
When submitting this pull request, I found another option, using setproctitle. Will mention in #4186.

PR: Don't rely on process name when detecting a previous instance

---

requirements/requirements.txt
setup.py

Fixes #3242.
Just added PyQt5 as dependency; nothing else.
See issues #3242, #5736.

PR: Add PyQt5 as a new wheel dependency

---

spyder/widgets/tabs.py

It's was odd to have one behavior in the Editor and a different one for the IPython console.

PR: Make tabs drag behavior in the IPython console to be the same as the Editor one

---

spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/tests/test_collectioneditor.py

Fixes #5885
---
- `Rename` is disabled for `list`, `set` and `tuple` in the collection editor
- `Duplicate` is disabled for `tuple`
- `Duplicate` behavior is modified for `list` and `set` (it appends or adds a element at the end)

PR: Disable renames for list, set and tuple in the Variable Explorer

---

spyder/config/main.py
spyder/plugins/ipythonconsole.py
spyder/plugins/runconfig.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/utils/ipython/kernelspec.py
spyder/utils/ipython/spyder_kernel.py
spyder/utils/ipython/start_kernel.py
spyder/utils/site/sitecustomize.py
spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/namespacebrowser.py
spyder/widgets/ipythonconsole/shell.py
spyder/widgets/variableexplorer/namespacebrowser.py

Fixes #5944 
Fixes #5759 
Fixes #5360 
This PR seeks to fix several issues with our IPython consoles, discovered after we removed the old Python console. In particular, we want to

PR: Several improvements to the IPython console

---

spyder/utils/ipython/spyder_kernel.py
spyder/utils/ipython/start_kernel.py

PR: Load %autoreload magic at kernel startup

---

doc/installation.rst

Fixes #5978
First PR, but figured it was good to start small...hopefully I haven't messed too much stuff up. Removed the outdated references to the Mac DMG installers that are apparently no longer offered, to fix issue #5978 . 
Also, as a tangentially related general formatting note (I didn't modify anything to this effect here, of course), it might make more sense to replace the numbers with bullets or (perhaps better yet) just simple headings under the Linux section, as they don't represent a sequential list of steps nor an ordered list of preferable alternatives, as a numbered list would imply. If its important enough, I can make another PR to do so.

PR: Remove/update outdated refs to Mac OS X, Mac DMG installers and Continuum.io

---

.gitignore

Just as it says on the tin, a rather trivial pull request to add all code coverage files (`coverage.MACHINENAME.####.####`) to the `.gitignore` list, along with Notepad++ auto-backup directories, the former per consultation with @ccordoba12  and the latter mostly for convenience (if not desired, I'm fine with omitting it).

PR: Add coverage files and Notepad++ backups to gitignore

---

.codecov.yml
README.md
appveyor.yml

PR: Add test coverage reporting with AppVeyor to Codecov

---

doc/installation.rst

In technical writing, numbered lists are generally used for lists of steps, or items in a clear order of precedence; bulleted lists for at least several items or alternatives, and headings for different scenarios that a reader might be interested in. Accordingly, I've reformatted the installation documentation to reflect this, for clarity and consistency.
Also, add a short section on Anaconda's availability for the Linux platform as a potentially easier all in one install method versus navigating the web of distribution repos and dependencies for various distros.

PR: Make bullets/numbers/headings more consistent and add Anaconda for Linux in install doc 

---

spyder/plugins/editor.py
spyder/widgets/editor.py

Fixes #1584.
When pulling in the default template for a new file, don't add a newline.

PR: Don't add extra newline when using new file template

---

spyder/widgets/variableexplorer/tests/test_utils.py
spyder/widgets/variableexplorer/utils.py

Currently, dates, datetimes and timedeltas are displayed as "Datetime(yyyy, mm, dd, hour)...etc. in the variable explorer (while not being "edited"); here, we instead properly display them in the standard (ISO 8601) shorter and more human readable format produced by str(), and without the duplicative type name (as that is already shown in its own column). This currently also works for the supported Pandas timestamp, etc. types as well.

PR: Display date/times in human readable format in Variable Explorer

---

spyder/app/tests/script.py
spyder/app/tests/script_pylint.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/tests/test_editor_introspection.py

Per @ccordoba12 's request, I went through the tests and disabled the 4 that were currently consistently failing, at least for me on Windows. Also, I skipped a test that randomly failed on a specific Travis build for that build (Py3.5 with PyQT5, Py2 and PyQT4 were already skipped; it didn't fail on any of the other CIs or builds, had nothing to do with the code I added and succeeded when I merely changed some whitespace to my next otherwise identical commit so I was almost sure it was spurious; it already had flaky(3) but failed all three times). I ran them about 20 times in total over the course of my testing.
A few key points to look at for in reviewing:
* Did I choose the right left of specificity for my `skipif`s (skipping the test for Windows, but not drilling down into my specific …

PR: Skip several failing tests on Windows and one on a specific CI build

---

spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/tests/test_collectioneditor.py

Fixes #5953
@ccordoba12 @Prikers 
First "real" (code) PR. Before, values in immutable (readonly=True) collections were able to be "edited" in a textbox on doubleclick in a Variable Explorer subwindow, but the changes wouldn't stick (as they shouldn't) once enter/etc was pressed, leading to inconsistency and potential user confusion. 
To remedy this, a naive fix as presented here would be to simply check if the readonly property is set when attempting to edit a directly editable value (i.e. not an object that can itself be inspected in a variable explorer subwindow, which might be desired even inside a tuple), and if so, do nothing. Took about 60 seconds to actually write and test the relevant line, and 60 minutes to manually track down where to stick said line...no surprise, lol.
Is this …

PR: Properly disable editing in Variable Explorer for values in immutable collections (e.g. tuples)

---

spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_indentation.py

Fixes issue #1754.
`Fix indentation` converts all the tabs in a document to 4 spaces.  Allow undo/redo on this operation.

PR: Allow undo/redo on Source > Fix indentation

---

spyder/widgets/editortools.py
spyder/widgets/tests/test_editortools.py
spyder/widgets/tests/test_outline_explorer.py

Fixes #5821
The goal of this PR is to prevent `if/else/try/for` statements from showing in the outline explorer tree.

PR: Remove `if/else/try/for` statements from the outline explorer tree

---

spyder/plugins/shortcuts.py
spyder/widgets/sourcecode/codeeditor.py

For issue #5973.
Another issue will address being able to overload shortcut events, so for now, I enhanced the hard-coding to create the expected behavior for Shift+Ins and Shift+Del.

PR: Add expected default behavior for Shift+Del and Shift+Ins

---

spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/tests/test_collectioneditor.py

Fixes #6080 , where Spyder would produce an error instead of viewing module contents, likely related to the recent introduction of `cloudpickle`.
Also includes a regression test making sure the editor is created without error and is properly readonly.

PR: Fix error when attempting to view module contents in CollectionsEditor

---

RELEASE.md
setup.py

PR: Make pyqt5 a wheel dependency only for Python 3

---

spyder/config/utils.py

PR: Improve how we detect if we are running under Anaconda

---

spyder/plugins/shortcuts.py

For issue #5426.
To recreate the issue (at least on Ubuntu):
- Open Preferences and click on Keyboard Shortcuts.  
- Select a shortcut to edit, either by using Enter on the keyboard or by double clicking the line (meaning that mouse vs. keyboard isn't important at this step). 
- Without this change, if you immediately click Cancel, the seg fault occurs.  
- However, if instead of clicking, you use the keyboard 'Tab' to highlight cancel (as the text in the dialog suggests to do to switch focus), then you can press Enter on the Cancel button and not get the seg fault. 
- The same thing happens with the OK button.
This seemed to be a difference between keyboard entry and mouse clicking on the buttons.   In the code, the only difference was setting widget focus, so by adding focus to the …

PR: Fix segfault on shortcut preferences when using mouse

---

spyder/widgets/explorer.py

Fixes #5080.
On Windows, the Windows registry has the entry for `.sql` as `text\plain` instead of `text/plain`.  `mimetypes` is returning the value as stored, even though the docs say it should be `None` or in the format `type/subtype`.
I'm going to see if this is an open CPython bug or if the documentation needs to be changed.

PR: Fix mime type error detection in the File Explorer

---

spyder/widgets/findreplace.py
spyder/widgets/tests/test_editor.py

Fixes #3674 .
After way too many hours trying to trace exactly _why_ tab (and not shift-tab) was suppressed on those fields, and only those fields, I eventually gave up and just stuck in a crude little hack that _seems_ to do the job. However, I'm not sure I'm at all happy with it. Thoughts? Better approaches? Side affects I'm missing? My lack of GUI/Qt experience is really showing here, but I certainly learned quite a bit.
Also, there is a probably not too meaningful in everyday use, but not entirely trivial difference in behavior between when just the find vs. when the find and replace boxes are visible. For the latter, tab only goes from the find box to the replace box, and no further; for the former, successive tab depresses takes one from the find box to the buttons to its right …

PR: Make Tab key properly switch between find and replace fields

---

spyder/utils/introspection/manager.py

Fixes #6060.
If introspection returns a 'docstring' value of None, Spyder crashes with a seg fault.

PR: Avoid a calltip crash when docstring is None

---

spyder/plugins/tests/test_editor_introspection.py

I would have lumped this in with another PR as it is so small, but I didn't want it to go out of scope. Basically, I previously added flaky to the introspection test as it was failing, but both locally and on the CIs (when I tested enabling it), it didn't help; it either failed no runs or all of them, and takes an incredibly long among of time (over 30s per run), so I disabled it again and removed the import, as well as some minor cleanup around the lines that I changed. Sorry about that, and no need to rush it out for 3.2.6 if its anywhere near the critical path.

PR: Remove unnecessary flaky from introspection test, minor cleanup

---

spyder/widgets/fileswitcher.py

Fixes #5384 
The issue this PR fix and the steps to reproduce it are described here: https://github.com/spyder-ide/spyder/issues/5384#issuecomment-334753512

PR: Prevent an error in the FileSwitcher when all tabs are closed in the last focused widget.

---

spyder/widgets/variableexplorer/arrayeditor.py
spyder/widgets/variableexplorer/dataframeeditor.py
spyder/widgets/variableexplorer/tests/test_arrayeditor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

Fixes #6114 .
Spyder array and dataframe editor now fail gracefully when a value too large for the given (int) datatype is entered in a cell, showing a warning message rather than crashing or displaying an error dialog, respectively (the former due to a Python3-incompatible ``e.message`` syntax of retrieving the error string in that case). Also, a bit of minor associated cleanup.
TODO: Add a simple test for each, ETA Tomorrow...err, later today (Wednesday). Assuming that happens in time, it could be included in 3.2.6, though no pressure on my end.
Also, one really weird bug I wasn't yet able to track down: Before the Array Editor change, Spyder would crash completely ("Python has stopped working...") due to the exception handling bug, *except* when SPYDER_DEBUG=3. In that case, it would …

PR: Fix crash and error dialog when triggering OverflowError (too large int) when editing arrays and dataframes

---

runtests.py
spyder_profiler/widgets/profilergui.py
spyder_profiler/widgets/tests/test_profiler.py

PR: Fix negative deltas on profiler

---

spyder/config/main.py
spyder/plugins/shortcuts.py
spyder/widgets/editor.py
spyder/widgets/tabs.py

Fixes #4842.  
- Added shortcuts to cycle through files.
- If statement to convert `Backtab` to `Shift+Tab` was only for 'nt', but problem existed on linux too, so removed the conditional.
- Tab navigation routine already existed in `Tabs` class, so moved it to `BaseTabs` class for it to be used in the editor (which creates a `BaseTabs` widget) without affecting existing code (like in iPython console).

PR: Allow tab cycling shortcuts to be configurable in Editor

---

conftest.py
runtests.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

@spyder-ide/core-developers, @spyder-ide/junior-developers:
I added a new `@pytest.mark.slow` marker to mark slow tests (i.e. most of the main window and IPython console ones), so they are run only in Travis and AppVeyor.
This will make far more easier to run our test suite locally.

PR: Run slow tests only in our CIs

---

spyder/widgets/variableexplorer/dataframeeditor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

Fixes #6115 
Currently, complex datatypes are treated as being editable in dataframe editor, but they actually aren't currently (though they are in arrays, and that functionality will be ported over Soon™). This leads to DataFrameEditor raising an uncaught ``TypeError`` if one is attempted to be edited, even if no changes are made. 
Also, while investigating that bug, it was also noticed that bools were not allowed to be edited, even though they were intended to be, due to only including the python `bool` type which the numpy `bool_` type, i.e. the actual standard boolean type for numpy arrays, not inheriting from the former, which was also easily fixed. 
In addition, minor enhancements were made to "false detection" for booleans to cover the standard values treated as "False" by Python. …

PR: Fix TypeError editing any complex val in DataFrameEditor, and bug resulting in bool_s being treated as uneditable

---

spyder/plugins/tests/test_editor_introspection.py

A one line PR: Just mark the ``editor_introspection`` test as ``slow``, as due to the timeouts required to make it pass reliably on all systems, it is the slowest in the entire suite, taking over 30s just by itself. Therefore, mark it as such.

PR: Mark introspection test slow as its the slowest in the entire suite

---

spyder/plugins/findinfiles.py

Fixes #4111.
- Add shortcut to action item on search menu.  The shortcut context avoids an ambiguous shortcut overload message. 
- Changed triggered event so that the 'Find in Files' option would be checked in View -> Panes.

PR: Add shortcut to Find in Files in Search menu

---

spyder/app/mainwindow.py

Fixes #6152.
The setup code for creating the layout configuration was saving the current layout and then overwriting the state to be None.
When this config was initially saved, it was also creating `self.defaults` in UserConfig.  However, later changing the `state` to None was not changing the value in `self.defaults`.  This was causing an issue when trying to change the layout because the defaults didn't have the same `None` value that the non-defaults had.

PR: Cannot change windows layout on first start after reset

---

spyder/app/mainwindow.py

PR: Fix error when trying to maximize plugins that don't have a dock widget

---

spyder/app/mainwindow.py
spyder/dependencies.py
spyder/plugins/console.py
spyder/widgets/reporterror.py
spyder/widgets/sourcecode/base.py
spyder/widgets/tests/test_reporterror.py

Fixes #5247.
----
It looks like this, the ok button is activated when each text has more than 10 words, this has to be improved because it isn't obvious how the ok button will be activated
Also a button to dismiss and don't show the dialog again should be added

PR: Change error report dialog to enter issue description before submitting it

---

spyder/__init__.py
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py

Adds a link and a short blurb regarding the new troubleshooting guide/FAQ in various appropriate places around the Spyder UI, including:
- About dialog
- Blurb/link as part of any crash/error dialog
- Blurb/link as part of the "crashed last time" startup message recommending spyder --reset
- Blurb/link in default Spyder issue template under .github/ISSUE_TEMPLATE.md
- And the auto-created/submitted one
- In the Readme, contributing.md, documentation index, and install doc
- Menu item in the help menu
Also some associated cleanup and polishing of related error and help guidance text, to help better guide users.
Finally, also includes a ``TROUBLESHOOTING.md`` document, along the lines of ``CONTRIBUTING.md`` which features a link and blurb to the full online guide/FAQ, as well as a few of …

PR: Add Troubleshooting links and blurb to various appropriate places in Spyder and doc

---

spyder_profiler/widgets/profilergui.py

Fixes #6220.
This pull request addresses a few aspects of the issue reported.
- When the `Stop` button was clicked when a profile was running, Spyder still attempted to display the profiler results even know there wouldn't have been any.  The profiler only writes results when it finishes.  The fix is to recognize the button event and display a different text to the user, along with clearing the datatree.
- The `load_data` method in the `ProfilerDataTree` class assumed that the default results file existed, but if the run had been canceled, then this file doesn't exist.  A try/except was added to this to catch file errors.  Note that item 1 should prevent this from being called.

PR: Fix Profiler error when run is stopped

---

runtests.py
spyder/app/tests/test_mainwindow.py
spyder/config/base.py

PR: Use a temporary config directory to run our tests

---

spyder/widgets/variableexplorer/utils.py

Currently, numpy arrays of types int64, int32, float64, float32, complex64, and complex128 are displayed with `repr` instead of `str`, leading to unnecessarily/redundant clutter being displayed (that its an array, and its dtype usually, both already displayed natively by VarExp. Further, the types  int16, int8, uint64, uint32, uint16, uint8, float16, and bool aren't displayed at all; just as ``ndarray object of numpy module``. Therefore, this PR fixes both of those issues.
Before:
After:
TODO: Add simple tests for proper display

PR: Enable the display of many more numpy array types in the Variable Explorer

---

CONTRIBUTING.md
README.md
TROUBLESHOOTING.md
doc/index.rst
doc/installation.rst

To partially address #6075 as well as a related problem that @csabella and I reproduced that prevented installing from source, as well as more generally make clear our recommendation to use `conda`/Anaconda over `pip` and other distributions and our inability to intervene to solve installation issues with those who choose the latter (as we get many every day on our repo), I've revised the readme, CONTRIBUTING.md and installation documentation accordingly. As part of that, as I'd been hoping to for a while, I took the opportunity to reorganize those sections to eliminate redundancy and outline the alternatives clearly, as well as associated minor cleanup and copyediting. I left the dependancy, etc. and other sections as alone as possible to avoid possible conflicts when forward-porting to …

PR: Major overhaul of Readme, contributing and install docs

---

.travis.yml
spyder/app/tests/test_mainwindow.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/tests/test_editor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

I've been noticing consistent problems with tests failing on Travis when focus and other GUI elements are involved. Accordingly, in #6132 @ccordoba12 suggested installing a window manager, as that fixed similar issues with CircleCI in #4151 . Therefore, this is a shot at doing the same for Travis, which would hopefully resolve a ton of frustration I'm having with a the tests in a number of recent PRs. First crack at it will just ensure the code runs without error, and then I'll try enabling tests that failed due to focus/etc. issues to see if this fixes it. However, it can be limited to ensure this PR can get merged quickly; the primary objective is to verify this is actually working and fixes at least some of the problems.

PR: Install and run window manager in Travis to fix focus issues and unskip now-passing tests

---

spyder/widgets/sourcecode/codeeditor.py

This is related to issue #5588. Eg:
my cursor is |. if I type ']', I would expect it to not be written. 
( [|]
)
But as the parenthesis is closed on the next line, this is not closed! even though my brackets are all closed.

PR: Differenciate between ), }, and ] when closing brackets

---

spyder/app/mainwindow.py
spyder/config/main.py
spyder/plugins/configdialog.py
spyder/plugins/console.py
spyder/widgets/reporterror.py
spyder/widgets/tests/test_reporterror.py

Screenshot:
@CAM-Gerlach, what do you think?
----
TODO:

PR: Use a checkbox in error dialog to dismiss it instead of a button

---

spyder/widgets/findreplace.py
spyder/widgets/tests/test_editor.py
spyder/widgets/tests/test_editor.py.bak

Fixes #4482
When the search field is highlighted in find/replace and TAB is pressed, the search text is copied to the replace field for modification.

PR: Find/replace - Copy search text to replace textbox on tabbing between them

---

spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/shell.py

PR: Preserve color scheme on kernel restart

---

spyder/plugins/ipythonconsole.py

PR: Catch any error when creating stderr files in the IPython console

---

spyder/utils/dochelpers.py

PR: Catch any error in the isdefined method of dochelpers

---

spyder/widgets/editortools.py

Fixes #6361
Added the `Collapse All` and `Expand All` buttons to the toolbar of the Outline Explorer and placed the buttons in the same order as their corresponding actions in the context menu.

PR: Harmonized the toolbar of the Outline Explorer with its context menu.

---

spyder/utils/ipython/kernelspec.py
spyder/utils/ipython/tests/test_spyder_kernel.py

PR: Add validation for custom interpreter option

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/__init__.py
spyder/plugins/tests/test_init.py
spyder/widgets/tests/test_editor.py

Fixes #5813 .
We're not sure why this happens, but this PR adds several protections aimed at both avoiding its occurrence and catching it just in case it occurs anyway. Also added a simple unit and an integration test to check this, though they may not be perfect as they can't really get to the root cause, and fixed a few issues with a recently added test that was causing random test failures (and re-enabled it on the CIs, since it should run now that I added the window manager).
Wasn't exactly sure where to best catch the errors, so please comment on that decision. Thanks!

PR: Fix and catch typeerror thrown when from_index is None while moving plugin tab

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/help.py
spyder/plugins/tests/test_help.py

Fixes #6317 .
The actual change is a simple one, just showing the help plugin if it is closed or hidden when the user selects the tutorial from the help menu, for a better Ux and to avoid user confusion particularly when trying to learn the basics of Spyder. However, the more extensive changes are in some cleanup and minor fixes to the newly added help tests, and both unit and integration tests to cover this scenario as well as general help functionality.
Not a huge priority, but fits in the realm of user help/doc/error/quality of life improvements that 3.2.7 is centered around, so would be nice to have it in that.

PR: Show Help if closed when opening tutorial to avoid user confusion

---

spyder/app/tests/test_mainwindow.py
spyder/widgets/explorer.py
spyder/widgets/projects/explorer.py
spyder/widgets/projects/tests/test_project_explorer.py

PR: Add test for file directory change in the Project Explorer.

---

spyder/widgets/browser.py
spyder/widgets/findreplace.py
spyder/widgets/mixins.py
spyder/widgets/tests/test_mixins.py

PR: Find/replace - return match counts on unescaped characters

---

spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/sourcecode/tests/test_codeeditor.py

Fixes #4231.
The method attached to `delete` for the shortcut key only deleted selected text.  This change adds the functionality of deleting the next character is no text is selected.

PR: Allow shortcut key for editor/delete to work like Del key

---

spyder/app/mainwindow.py
spyder/app/start.py
spyder/config/base.py
spyder/plugins/editor.py
spyder/plugins/ipythonconsole.py
spyder/utils/external/lockfile.py
spyder/widgets/editor.py

Currently, the test whether the environment variable `SPYDER_PYTEST` is set (which indicates whether we are running under pytest) is done at import time. However, if the tests are run using the unittest plugin, this import happens before the environment variable is actually set. Thus, this PR delays the test until run time.
With this PR and spyder-ide/spyder-unittest#114, I can run the Spyder test suite successfully within Spyder. :tada:

PR: Delay check whether we are running under pytest until run time

---

spyder/config/main.py
spyder/widgets/sourcecode/base.py
spyder/widgets/sourcecode/codeeditor.py

Fixes #5466
A keybind to start a new line without breaking the current (bevore it ends) is included in many editors. This is very handy for people using autocompletition for brackets

PR: Add Ctrl+Shift+Enter to enter a new line in the Editor

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/help.py
spyder/plugins/tests/test_help.py

Fixes #6519.
----
The problem is those plugins are initialized after Help, so we can't set a reference to them in register_plugin.

PR: Remove ipyconsole and editor attrs from the Help plugin

---

spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/ipythonconsole/client.py

Also, fix other tests and remove several skipif's on Windows.

PR: Avoid showing dialogs in IPython console tests to avoid segfaults

---

spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/ipythonconsole/shell.py

PR: Fix error when setting a path with a single quote

---

spyder/utils/introspection/utils.py
spyder/utils/tests/data/example.java
spyder/utils/tests/data/example.md
spyder/utils/tests/test_get_words.py

PR: Fix typo in utils.introspection.get_words

---

spyder/utils/codeanalysis.py
spyder/utils/tests/data/example.py
spyder/utils/tests/test_codeanalysis.py
spyder/utils/tests/test_get_words.py

PR: Allow TODO check marks with blank line

---

spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/ipythonconsole/client.py
spyder/widgets/ipythonconsole/namespacebrowser.py

Fixes #6682.
On Windows, `time.gmtime` doesn't work for large negative values, but that function is used to show the elapsed time in the console.  If the system clock is changed to a past date, then the 'start' time is later than the 'current' time, which creates a negative elapsed time, and could result in an OSError.  
- Use `time.monotonic()` when possible (Python 3.3+).  `time.monotonic` doesn't use the system clock, so there is no risk of it being negative.
- For releases before 3.3, continue to use `time.time()`, but add a check to make sure that the elapsed time isn't negative.  If it is negative, reset the start time to be the current time, which restarts the counter.

PR: Change time elapsed calculation to prevent OSError

---

spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/tests/test_collectioneditor.py

Fix #6284 .
Just catch and pass the error, allowing for the viewing of MultiIndexes as generic Python objects in the CollectionEditor without it raising errors and refusing to load the rest of the object as previously. Also added a test for it.

PR: Fix NotImplementedError when browsing a MultiIndex in the Collection Editor

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/widgets/variableexplorer/tests/test_arrayeditor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

I've encountered a number of sporadic test failures with ``test_get_help`` and ``test_set_elapsed_time`` on the CIs, so I've increased the relevant timeouts. I also went back and made similar changes to timeouts and tweaks to the methods used in a few of my previous tests that were apparently sporadically failing locally on Linux in a similar manner. Finally, I improved the docstrings of the affected functions; and also standardized the headers as I've been doing for the other files I've modified recently.

PR: Make several GUI/qtbot tests more reliable by increasing timeouts and tweaking the methods used

---

spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/tests/test_collectioneditor.py

Fix #5696 .
Currently, any window launched from the Variable Explorer (Dataframe Editor, Collections Editor, etc) will cause Spyder to stay open even if the main window is closed, leading to extra resources and cluter, user confusion and general sub-optimal Ux. Therefore, this PR sets that properly to fix it, and additionally adds a specific test for this as well as improves the existing ones to make them less brittle (as this change broke one of them, my own). Also, updated file/section headers to the consistent standard and did a few bits of minor cleanup around lines that were changed.

PR: Set parent for Variable Explorer editors so Spyder closes properly

---

.gitignore

On recent builds, running pytest results in this dir, which clutters ``git status``. This PR fixes that.

Add .pytest_cache to gitignore

---

spyder/widgets/variableexplorer/collectionseditor.py

In the inline tests for CollectionsEditor, ``np.random.random_integers`` is called, which has been deprecated for quite some time. To avoid problems when/if it is finally removed, I replaced it with ``np.random.randint``. Also, added a number of additional datatypes which we now support in the years since the test was written, for full coverage, and did some minor cleanup/refinements to the docstrings.

PR: Replace deprecated function in inline CollectionsEditor tests and add recently supported data types

---

MANIFEST.in
setup.py
spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/tests/dom_element_test.xml
spyder/widgets/variableexplorer/tests/test_collectioneditor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

Fix #5642 .
Fix #6727 .
Fix #6728 .
Fix #6729 .
Spent all night and morning going down this rabbit hole on what was supposed to be a "quick" PR, finding, fixing and testing numerous additional related issues ultimately stemming from the same line(s) on top of the original problem (nominally #6727 on my end, with the orignal impetus starting all the way back in the abortive #5999 ) including a full on application crash, but here we are, and everything is fixed so not only are the errors handled gracefully, but everything actually works perfectly.

PR: Fix various bugs in Variable Explorer, including an application crash to desktop

---

appveyor.yml
continuous_integration/travis/install.sh
spyder/widgets/reporterror.py

To help raise the bar slightly as to the quality of reports and avoid user mistakes, this PR bumps up the font size on the issue dialog (as its currently quite small), makes the "Paste clipboard here" text on the automatic github report even more blaring, and increases the minimum character count to 50 so users put a little more thought into their reports.
Screenshot of issue dialog with larger font:

PR: Error report stopgap to make instructions harder to miss

---

spyder/widgets/ipythonconsole/client.py

Fixes #6767.
No reason to initialize self.t0 to None since time is already imported.  Initialize it to a valid time and then allow the other methods to update it just as they have been doing.  That way it will always have a valid value even if the kernel fails to start.

PR: Initialize start time to a time and not None

---

spyder/utils/syntaxhighlighters.py

It's the same as [#6804](https://github.com/spyder-ide/spyder/pull/6804) except this is for branch 3.x
The word "cls" usually use in the class method.
I thought we should highlight "cls" just like "self".
For example
```
class Foo:
@classmethod
def clsmethod(cls, x):
pass
```

PR: Add instance pattern "cls" for class methods

---

spyder/widgets/editor.py

The file switcher widget is now `Qt.Popup` instead of `Qt.SubWindow`.
This makes it usable with tiling window manager since it appears as floating and do not move the main spyder window.
Fixes #6834
Fixes #6743

PR: Change Editor's tab switcher from Qt.SubWindow to Qt.Popup for tiling window managers

---

spyder/config/main.py
spyder/defaults/defaults-3.0.0.ini
spyder/plugins/ipythonconsole.py
spyder/utils/ipython/kernelspec.py
spyder/utils/ipython/start_kernel.py

This adds an  option for Jedi Code completion in the ipython shell.
It also adds a warning text for the Greedy completer, to inform users, that the current version of the Greedy completer in ipython needs an extra space to split commands.
Related Spyder-ide issues: #6803 #6700 
Related Ipython Console Issues:
https://github.com/ipython/ipython/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+greedy+completer

PR: Add option to use Jedi in the IPython console + warning on greedy completer

---

appveyor.yml
continuous_integration/circle/modules_test.sh

Anaconda updated its PyQt packages to 5.9 and that's causing some problems to our tests.
I had to pin PyQt to 5.6 for now on Windows to avoid segfaults and hang ups.

PR: Fix tests after update to PyQt 5.9

---

spyder/plugins/tests/test_ipythonconsole.py

``test_set_elapsed_time`` in test_ipythonconsole fails very frequently, causing builds to have to rerun very often and occasionally fail completely, apparently because sometimes due to small timing inconsistencies the timer will have already ticked off one second by the time everything processes and the check runs, thus causing it to fail.  Therefore, I've made it slightly "fuzzy" such that if one second ticks off, it still passes, and also run it a few more times just in case, which should eliminate the problem.

PR: Fix often failing elapsed time test with fuzzier check and more reps

---

README.md

As somewhat of a follow-on to #6909 except just for ``master``, this PR:
* Positions the screenshot above the funding announcement, with the rationale that it is more important to hook users' interest about the application itself first, showing them what it can do, before hitting them with a plea for funds for an application they don't yet have any compelling reason to support, and potentially scaring them into thinking it is no longer modern or actively developed.
* Improves the text of the announcement itself, including:
* Fixes grammar errors, awkward/unidiomatic prose, and unclear portions
* Updates the blurb to better reflect the current situation
* Tries to give it a more optimistic and productive tone to avoid scaring potential users into thinking the project is in decline, while …

PR: Improve and update wording of funding announcement, and put screenshot above it

---

appveyor.yml
continuous_integration/travis/install.sh
spyder/utils/introspection/tests/test_jedi_plugin.py

On the newest CI builds, the jedi tests ``test_numpy_returns`` and ``test_matplotlib_figure_returns`` are failing to get completions, causing the test to fail. @ccordoba12 determined this was due to ``jedi`` 0.12, and thus we're skipping the test for now on this version and later until a more permanent fix can be devised.

PR: Skip tests numpy_returns and matplotlib_figure_returns for now on jedi >=0.12 and pin CIs to 0.11.1

---

setup.py
spyder/app/start.py

Fixes #6968.
Loading libGL at the very start fixes a segmentation fault on some Linux systems (including mine!). This uses a low-level function from cdll to load libGL instead of requiring and importing pyopengl which implicitly loads libGL (I guess). Thus, we also drop the pyopengl requirement.
See discussion at ContinuumIO/anaconda-issues#9199 (where @ccordoba12 approved this approach) and #3226.

PR: Load libGL using low-level function without requiring pyopengl

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
spyder/app/mainwindow.py

This PR adds a checklist for the user to complete before submitting an issue report (both in the issue template and submitted from the Spyder Help menu; automatic/semi-auto error reports are unaffected), to hopefully help increase the quality of issues received and enable speedy closure of those that aren't helpful. To avoid any chance of an incomplete report due to length limitations, the text verbosity for the Help menu report (particularly the mostly redundant reminder) was cut down where possible.
Also, it adds a heavily revised PR template (as used here) with a checklist (top), along with formatting enhancements, some additional items and helpful tips in the comments.
As this is an internal change to the Github …

PR: Add checklists for Github issue report and pull requests

---

bootstrap.py
spyder/config/base.py
spyder/config/main.py
spyder/config/user.py

Thanks to @bcolsen for his detailed report leading to this PR.
Currently, passing the ``--test`` flag to ``bootstrap.py`` just sets the ``SPYDER_TEST`` env variable which instead tells spyder to not load and save the user's individual settings file, e.g. ``spyder.ini``, while not affecting handling of anything else inside for ``spyder-py3`` directory, including the history logs for the normal and internal consoles, along with your pylint, profiler, working dir, help, and online help histories, your language and ``rope`` settings, any third party plugins you may have installed, and your default ``temp.py`` and ``template.py`` (new file template) files. Obviously, this is not particularly desirable for most testing …

PR: Add --safe-mode option to start with a clean config directory

---

spyder/utils/help/sphinxify.py

In sphinx 1.8 (dev), the source and destination directory cannot be the same for a build, so `sphinxify` fails. This sets the destination directory to be a subdirectory.

PR: Adapt sphinxify for changes in Sphinx 1.8

---

.travis.yml
CONTRIBUTING.md
README.md
bootstrap.py
continuous_integration/circle/test-qt5.sh
continuous_integration/travis/install-qt.sh
continuous_integration/travis/install.sh
doc/installation.rst
doc/overview.rst
setup.py
spyder/__init__.py
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/tests/test_editor_introspection.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/requirements.py
spyder/utils/dochelpers.py
spyder/widgets/editor.py
spyder/widgets/explorer.py
spyder/widgets/sourcecode/codeeditor.py
spyder/widgets/tests/test_pathmanager.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

PR: Remove support for PyQt4

---

spyder/app/mainwindow.py
spyder/utils/programs.py

Fixes #6746
Enclose the path of the python executable in double quotes so that executing a script in an external system terminal works correctly when the path to the Python interpreter contains spaces.

PR: Enclose python exe path in double quotes

---

spyder/widgets/variableexplorer/namespacebrowser.py

Add a validation of the length of the serialized values send to the kernel in the Variable Explorer.
Fixes #7158

PR: Limit length of serialized values in Variable Explorer when applying modifications

---

spyder/widgets/variableexplorer/arrayeditor.py
spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/dataframeeditor.py
spyder/widgets/variableexplorer/texteditor.py

Change behavior of default `OK` and `Cancel` buttons. Now `OK` is `Save and close` (disabled by default) and `Cancel` is the `Close` button.
Fixes #7156

PR: Change behavior of Variable Explorer editor buttons

---

.travis.yml
spyder/app/tests/test_mainwindow.py
spyder/utils/tests/test_programs.py
spyder/utils/tests/test_sourcecode.py
spyder/widgets/tests/test_array_builder.py
spyder/widgets/tests/test_editor.py
spyder/widgets/variableexplorer/tests/test_arrayeditor.py
spyder/widgets/variableexplorer/tests/test_dataframeeditor.py

Now that we don't have to support PyQt4 anymore, there's room in Travis to test with macOS.

PR: Run tests in macOS

---

spyder/utils/programs.py
spyder/utils/tests/test_programs.py

It turns out Anaconda defines `pythonw` as a script on macOS.

PR: Improve pythonw detection

---

spyder/utils/site/sitecustomize.py

I want to be able to add a breakpoint somewhere without spyder jumping to another tab.
Fixes #5201

PR: Stop editor from jumping around when adding/removing lines with breakpoints while debugging

---

spyder/plugins/history.py
spyder/plugins/tests/test_history.py
spyder/utils/sourcecode.py
spyder/utils/tests/test_sourcecode.py

A better thing would be to read the history from ipython, but I am not sure that this would work in every cases.
Fixes #7080

PR: Limit the number of lines in history according to the relevant setting

---

spyder/config/base.py

The problem was we were not checking if what's saved in env vars `HOME`, `USERPROFILE` and `TMP` is really a file system path. 
Please see https://github.com/ContinuumIO/anaconda-issues/issues/9593 for the context.

PR: Improve detection of users' home directory

---

spyder/plugins/ipythonconsole.py

The message needed to be clearer about the right version of `spyder-kernels` needed in our stable branch.

PR: Improve message about the lack of spyder-kernels in external interpreters

---

spyder/widgets/editor.py
spyder/widgets/sourcecode/base.py
spyder/widgets/sourcecode/codeeditor.py

Sets the width of tabulations after the font is set so they are arn't set to the width of the default font.
Before:
After:
Fixes #7432
Still dosen't update the spacing when changing the font face/size.
I guess there needs to be a callback somewhere?

PR: Fix tabulation spacing by setting tab spacing after the font

---

appveyor.yml

This fixes a problem that started yesterday with Appveyor and Python 3.6

PR: Reinstall Matplotlib in Appveyor in case it had been removed

---

spyder/widgets/sourcecode/base.py

The width of one space in text is not always an integer number. So multiplying the width of a single space does not always give the right result. I think it is better to take the width of multiple spaces instead.
Fixes #7432

PR: Setting tab stop width by using the width of multiple spaces

---

spyder/locale/ja/LC_MESSAGES/spyder.po

In Japanese message file (spyder/locale/ja/LC_MESSAGES/spyder.po), I found that some of "Spyder"'s are misspelled as "Spypder". This pull request fixes it.

PR: Fix misspelling in Japanese translation

---

spyder/config/main.py
spyder/plugins/projects.py
spyder/plugins/tests/test_projects.py

Create a new config option for the projects plugin called `visible_if_project_open`, defaulting to `True` to mimic current behaviour. When closing a project or quitting Spyder with a project open, set or clear this according to whether the Project Explorer is open. When creating a new project or opening an existing project, open the Project Explorer only if the config option is set.
The effect is that if a user opens a project, closes the Project Explorer and then restarts Spyder, the Project Explorer is not opened again, as opposed to the current situation where it is opened.
Fixes #6292

PR: Do not automatically open Project Explorer when opening project if user closed it

---

spyder/widgets/reporterror.py

Issues were sent to my fork before. We introduced that for testing but it affects people running Spyder with `bootstrap.py`.

PR: Send reported issues to Spyder's main repo in DEV mode

---

CONTRIBUTING.md
README.md

Per the discussion in spyder-ide/spyder-docs#69 , this PR corrects the install command for ``spyder-kernels`` 1.x to use ``conda-forge``, since it isn't available for all platforms on the main ``defaults`` channel. Also, fixes a few minor but silly typos in the lines near it.

PR: Update conda install command for spyder-kernels 1.x

---

setup.py

This is because in that case keyring depends on system packages.

PR: Don't require keyring for Python 2 and Linux in our wheels

---

MANIFEST.in

Fixes #7639.
This will allow external developers to run our test suite as we do in our CIs.

PR: Add runtests.py and conftest.py to our tarball

---

spyder/utils/help/tutorial.rst

A follow-on to #7641 / #7643 with the primary purpose of conforming the tutorial to our doc style guide to further enhance its appearance and external consistency, and also improve maintainability and internal consistency between them. Also, fixed some minor typos and refined the prose and formatting. See #7652 for the full list of what was done.
The final version was built with Sphinx in nitpicky mode, with no issues reported and the result was examined to confirm everything rendered well; also, it was run through Sphinx linkcheck with all green. Finally, it was examined as it will appear to users in Spyder itself reading through all sections, and no issues were found except for an issue where if ref tags (``.. …

PR: Conform tutorial to docs style guide and further minor improvements

---

spyder/widgets/explorer.py

Prevent raising an error while updating browser history of the File Explorer and handle it by changing working directory to the users home directory.
Fixes #7328

PR: Handle error when doing a browser history update

---

spyder/config/main.py
spyder/plugins/configdialog.py
spyder/plugins/maininterpreter.py
spyder/widgets/comboboxes.py

Improve custom interpreter selection.
Fixes #7529

PR: Improve selection of custom interpreter

---

spyder/widgets/variableexplorer/collectionseditor.py
spyder/widgets/variableexplorer/tests/test_collectioneditor.py

If a CollectionEditor is created then Spyder tries to copy the object which
is being edited. If the .copy() method is not implemented correctly, then
the copy will not be a true copy but have a different type. If that is the
case, we make the editor read-only so that the user does not inadvertently
change the type of the object.
Fixes #6936

PR: Make editor for collection types which copy incorrectly read-only

---

spyder/app/cli_options.py
spyder/app/mainwindow.py
spyder/config/main.py
spyder/plugins/configdialog.py

To try to avoid the many issues people are finding with WebEngine, we will allow them to select the OpenGL implementation used by Qt, like this:
They could also select it with a new `--opengl` command line option, that can have two options: `software` and `desktop`.
----
Note: We are following RStudio's lead in this camp. See:
https://github.com/spyder-ide/spyder/issues/7447#issuecomment-412700201
and
https://github.com/rstudio/rstudio/issues/3185#issuecomment-412575262
for the details.

PR: Add option to select OpenGL implementation used by Qt

---

spyder/plugins/variableexplorer.py
spyder/widgets/variableexplorer/namespacebrowser.py

The layout of the `VariableExplorer` plugin consists mainly of a `StackWidget`.  When an IPython console is created, a corresponding `NamespaceBrowser` is instantiated and added to the stack.
The cog menu button (cmb) is created by the variable explorer plugin and passed as a class argument when instantiating a new namespace browser (nsb ), which is later added to its layout during the setup. So this means that the cmb is shared among all the nsb of the stack.
The problem is that, when the current IPython console change, and so the current nsb of the stack widget, there is no mechanism to update the cmb  actions and to move it from the previous current nsb layout to that of the new current nsb. In order to solve this …

PR: Fix cog menu not showing in the variable explorer when more than one IPython console is opened

---

spyder/config/main.py
spyder/plugins/ipythonconsole.py
spyder/widgets/ipythonconsole/client.py

There is now an option to not show the dialogue box when restarting the ipython kernel. This will be less annoying for users who may wish to do this often.
Fixes #7561

PR: Make "Are you sure you want to restart the kernel?" warning optional

---

spyder/plugins/variableexplorer.py

This is a follow up of PR #7710.
Because `VariableExplorer.get_plugin_actions` was implemented in  PR #7710 so that it actually returns the actions of the plugin instead of an empty list, we need to set the plugin option `DISABLE_ACTIONS_WHEN_HIDDEN` to `False` or else the plugin actions will be disabled when the plugin is undocked in a new window.

PR: Fix variable explorer actions are disabled when undocked in a new window

---

spyder/plugins/ipythonconsole.py

PR: Catch any error generated when trying to start kernels

---

spyder/app/mainwindow.py

Due to limitations of the Windows DWM, compositing is not handled correctly for OpenGL based windows when going into full screen mode.
To get around this issue, this PR propose to use the workaround described here:
https://bugreports.qt.io/browse/QTBUG-41309
Fixes #4291

PR: Implement a workaround to toggle on/off fullscreen mode for Windows systems

---

spyder/app/mainwindow.py

To make the text of a `QMessageBox` selectable in Windows 10 when using the `WindowsVista` theme, the `setTextInteractionFlags` of the message box has to be set to `Qt.TextSelectableByMouse`.
To my knowledge, this is not possible to do this by using the `QMessageBox.about()` function of the static functions API. So a custom about message box has to be constructed manually instead.
Fixes #6535

PR: Make the text of the About Spyder message box selectable

---

spyder/plugins/outlineexplorer/editor.py
spyder/plugins/outlineexplorer/tests/test_widgets.py
spyder/plugins/outlineexplorer/widgets.py

PR: Add a "get_cursor_line_number" method to OutlineExplorerProxyEditor

---

spyder/plugins/outlineexplorer/tests/test_widgets.py
spyder/plugins/outlineexplorer/widgets.py

PR: Make the "Go to cursor position" button of the outline explorer work also when the cursor is in the last item of the Editor

---

spyder/plugins/ipythonconsole.py
spyder/utils/environ.py

PR:  Catch errors generated when creating the env vars dialog 

---

spyder/utils/help/tutorial.rst

Makes the minor fixes/tweaks suggested by Dr. @fangohr himself in review comments on #7659 and #7643 .

PR: Fix minor issues with the tutorial as pointed out by Dr. Fangohr himself

---

continuous_integration/travis/install-qt.sh
spyder/widgets/editor.py
spyder/widgets/variableexplorer/tests/test_arrayeditor.py

From time to time, a test is failing on our CI with this error:
https://travis-ci.org/spyder-ide/spyder/jobs/422626738#L932
```python
==================================== ERRORS ====================================
ERROR at setup of test_reorder_filenames[filenames2-expected_filenames2-None-None] 
SETUP ERROR: Qt exceptions in virtual methods:
________________________________________________________________________________
File "/home/travis/build/spyder-ide/spyder/spyder/plugins/editor/widgets/editor.py", line 2629, in <lambda>
self.editorstack.destroyed.connect(lambda: self.editorstack_closed())
File "/home/travis/build/spyder-ide/spyder/spyder/plugins/editor/widgets/editor.py", line 2654, in editorstack_closed …
```

PR: Protecting calls to unregister_editorstack_cb and pin sip in our tests

---

spyder/app/tests/test_mainwindow.py
spyder/plugins/editor/widgets/tests/test_warnings.py

It seems that tests related to the LSP are failing on AppVeyor with this error:
This PR proposes to skip the problematic tests on Windows CI. Note that the tests are passing locally on my Windows 10 laptop.
Also this PR proposes to split the `test_mainwindow.test_help` in two so that `Help` is tested independently when called from the Editor or from the IPython console. Otherwise, it is not possible to know if the test is timing out because of the action made in the Editor or in the IPython console.
Unfortunately, after the split, I found out that both tests were timing out on AppVeyor, so they had to be skipped. Still, I think splitting the test in two is an improvement, so I'm proposing it here anyway.
This PR will allow the tests on Appveyor to pass for the following three PR:
PR #7790 …

PR: Split "test_mainwindow.test_help" and skip tests on Windows CI because they are timing out.

---

spyder/widgets/pydocgui.py

Added a try/except to handle the difference in parameters on pydoc library between py 3.6 and 3.7.
Fixes #7721

PR: Correctly handling pydoc._start_server on Python 3.7

---

spyder/widgets/findinfiles.py
spyder/widgets/tests/test_findinfiles.py

This addresses issue #7811, making findinfiles not ignore all files if the exclude pattern is empty.
Fixes #7811

PR: Don't ignore all files when exclude pattern is empty

---

spyder/widgets/variableexplorer/collectionseditor.py

It was raising an AttributeError when `data` was a list, and not a dict
On `collectioneditor` Ctrl+V handler, `data` could be a list and not a dict, so it would raise an `AttributeError` while trying to call `data.keys()`
Fixes #7244

PR: Don't import objects in collectionseditor that are not dicts

---

spyder/py3compat.py
spyder/widgets/findinfiles.py
spyder/widgets/tests/test_findinfiles.py

PR: Truncate results correctly in Find in Files for Python 2

---

.circleci/install.sh
continuous_integration/travis/install-qt.sh
continuous_integration/travis/install.sh
continuous_integration/travis/runtests.sh

This uses `conda activate` to activate the test env. This is the new way to activate envs since conda 4.5, updated by ci-helpers.

PR: Fix tests after ci-helpers updated conda version

---

runtests.py

This is a simple change to remove the detailed info about lines not covered by tests from our `pytest` reports.
This option adds a lot of noise to our reports. Besides, this information can be consulted on [codecov](https://codecov.io/gh) or [coverall](https://coveralls.io) in a much nicer format.

PR: Remove '--cov-report=term-missing' from pytest args

---

setup.py
spyder/app/cli_options.py
spyder/app/mainwindow.py
spyder/app/tests/test_mainwindow.py
spyder/plugins/configdialog.py

Fixes #7447.
This also adds `GLES` to the list of available OpenGL implementations users can select from.

PR: Set selected OpenGL implementation for QtQuick too

---

spyder/app/mainwindow.py
spyder/plugins/ipythonconsole.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/utils/misc.py
spyder/utils/programs.py
spyder/utils/tests/test_programs.py
spyder/widgets/ipythonconsole/client.py

The main change is that temp folder used by Spyder is not more removed when application closes, mainly because when multiple instances of Spyder are running and one of them is closed, temp folder were remove, and remaining ones didn't detect this action.
Another related change is that, every time temp folder is needed, a function to ensure that the folder exists was created. This was implemented using a function and removing a constant called TEMPDIR. This can cause that another projects or branches that have been using this constant crashes.
Because tempdir is not more removed when application closes, now some code to ensure that files are removed after been used was added. The points where this was done are:
* When …

PR: Use a function to create and get our temporary directory

---

spyder/widgets/sourcecode/codeeditor.py

- Fixes #7872 for the 3.x branch
- PR #7874 was opened to fix the same issue in Master
Replace the `StartOfWord` and `EndOfWord` variable name by `PreviousWord` and `NextWord` for the `Previous Word` and `Next Word` shortcut, so that the right callback is associated with these shortcuts.
Due to the situation with builtin shortcuts in 3.x, it is not worth doing more than that:
The builtin `Ctrl+Left` and `Ctrl+Right` works by default as valid key sequence for these shortcuts.
These two key sequences are reserved and will not work when used for another shortcut anyway as explained in PR #7768. So there is no point in assigning them by default here.
By submitting this Pull Request, I affirm that:
* I release the content of this PR under Spyder's MIT (Expat) license.
* I hold the copyright to …

PR: Correct next/previous word shortcut callback

---

spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/editor/widgets/tests/test_shortcuts.py

Fixes #7883
Blocking #7929
In this PR, we propose to revert some of the changes made in PR #7768 and to go back to use `QShortcut` to manage local keyboard shortcuts in the Editor.
The reason is that I found a way to fix all the problems we had with builtin shortcuts in the editor using the Qt Framework and the same architecture that is used everywhere to manage shortcuts in Spyder.

PR: Improve how keyboard shortcuts are handled in the Editor (Take 2)

---

spyder/plugins/editor/widgets/tests/test_editor_and_outline.py
spyder/plugins/outlineexplorer/widgets.py

Fixes #7214
First, when `Show all Files` is selected in the `Outline explorer`, the root item will not automatically expand and collapse when the current `Editor` change. IMO, this change brings 3 UX improvements:
- The Outline Explorer can now be used more easily as a "vertical tab bar".
- Double clicking a root file item will now expand/contract that item, like it does for the other tree items.
- This allows to keep more than one file expanded at the same time, which is very convenient to navigate between elements that are not saved in a same file.
Second, if a root file item is clicked and that item corresponds to the current Editor, the cursor will be moved at the start of the file. Double-clicking a root file item, whether this item correspond to the current Editor or not, will …

PR: Improvement to navigation and file switching in the Outline Explorer

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/tests/test_plugin.py
spyder/plugins/editor/widgets/editor.py

PR: Sync Outline Explorer at startup and preserve the file order in the tabbar

---

spyder/plugins/editor/lsp/providers/document.py

Fixes #7726
Basically, I simply followed what was suggested in the following StackOverflow answer, which in turn was based on code from the pip project.
https://stackoverflow.com/a/43925228
I tested it in Windows 7 with Python 3.6 and `Go to definition` is working with the proposed changes, I must say even better than before the changes introduced with the new LSP.

PR: Fix Go to definition feature in the Editor in Windows after the changes introduced with the new LSP

---

spyder/plugins/editor/widgets/editor.py
spyder/plugins/editor/widgets/tests/test_editor_and_outline.py
spyder/plugins/outlineexplorer/api.py
spyder/plugins/outlineexplorer/editor.py
spyder/plugins/outlineexplorer/tests/test_outline_explorer.py
spyder/plugins/outlineexplorer/widgets.py

Fixes #7982
- Outline Explorer stays enabled even if the file that has focus is not a python file.
- Root file items of non-python files are now listed in the Outline Explorer.
- Clicking on a non-python Root file items that already has the focus will move the cursor at the beginning of the file.
- Rework the tests to cover this new feature.
- @ccordoba12 I reworked the tests to take into account the comments you made about pytest fixtures in another PR. Tell me if this is Ok please. …

PR: Show the root file item of files that are not Python files in the Outline Explorer

---

appveyor.yml
continuous_integration/posix/install.sh

Conda package for `testpath` **0.4.1** contains wrong METADATA and that's breaking pip.
Easy way to reproduce:
conda create -n pip-break python=3.6 testpath
conda activate pip-break
pip install ipython
Then see the last command generate a long traceback.
Pinging @mingwandroid and @jjhelmus about this. This requires an urgent fix.

PR: Fix tests by pinning testpath and switching to Python 3.5 on Windows

---

spyder/config/user.py

This is because they are reported to us as errors and they interrupt users work.
Fixes #8046.

PR: Don't raise exceptions when writing config to disk fails

---

spyder/plugins/editor/widgets/codeeditor.py

Fixes  #8056
We need to accept the event in the `keyPressEvent` of the editor when the hardcoded `Shift+Tab` key sequence is pressed to unindent code, else the editor is loosing focus.

PR: Accept event if Shift+Tab is pressed in the CodeEditor keyPressEvent to avoid losing focus

---

spyder/plugins/lspmanager.py
spyder/plugins/workingdirectory/plugin.py

Fixes #7111
This is a long standing issue that can be traced back to https://github.com/spyder-ide/spyder/commit/bdd1ed6d835abbd2895e8c7d9b02f075ecdacfce
The  plugins inherit from QWidget. If a plugin is meant to be used without a layout, it must be explicitly hidden or else, it will appear as an invisible rectangle in the top left corner of the MainWindow and will block mouse interaction with a part of the Toolbar.
Currently, this include the `LSPManager` and the `WorkingDirectory`.
In the screenshot below, you can see the empty `WorkingDirectory` in red, that span above the Toolbar, but below the Menus. The solution is simply to call `show` in the `__init__` of these plugins.
[Developer Certificate of …

PR: Hide plugins that do not have a layout

---

spyder/app/tests/script.py
spyder/app/tests/test_mainwindow.py
spyder/config/main.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/base.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/outlineexplorer/widgets.py
spyder/utils/syntaxhighlighters.py

This PR makes a function that runs a cell instead of copying the cell contents into the current console. With this function the tracebacks give the correct lines in the file the cell was run from!!  Also if the file is run in a dedicated console the code cells will also run in that console regardless of the console in focus.
A variable with the cell contents is made in the ipython namespace of the console so there will be no interference with user variables.  The function executes this code then deletes the variable. The function displays an error if it is run from the console. I can leave the variable so the function can run the last cell, but it's not obvious that it won't reflect any subsequent changes to the block …

PR: Run cells through a function instead of pasting their contents to the console

---

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py

When opening a Pandas DataFrame with missing values in the Variable Explorer, the missings are displayed with red cell background, which is similar to the red background of the minimal values. So the missings are difficult to spot, see #8037.
I suggest using a white background for the missings instead:
Fixes #8037

Variable Explorer: Use distinctive background for missings in DataFrames

---

runtests.py

This PR does a few things to improve usability of both runtests locally (that have been bothering me and perhaps others for quite some time), as well as the CI reports for users developing both Spyder 3 and Spyder 4, and does a little opportunistic cleanup/refacotring of code that hasn't been touched between ``3.x`` and ``master``.
Namely, it:
* Adds the ability to pass any arbitrary additional pytest options of the users choosing through to …

PR: Improve usability of runtests locally and test output on the CIs

---

spyder/plugins/findinfiles/plugin.py
spyder/plugins/findinfiles/tests/test_widgets.py
spyder/plugins/findinfiles/widgets.py
spyder/plugins/lspmanager.py
spyder/preferences/shortcuts.py
spyder/widgets/fileswitcher.py

Change font color to according to theme in various widgets: 
Part of #8068

PR: Fix font color in dark theme for several widgets

---

spyder/plugins/configdialog.py

PR: Don't associate the combobox of FileComboBox to the same option as its lineedit

---

runtests.py

This was my fault for recommending @CAM-Gerlach to remove the argparse option associated to `--run-slow` in PR #8123.

PR: Fix passing --run-slow to runtests.py

---

spyder/app/mainwindow.py
spyder/app/tour.py
spyder/config/gui.py
spyder/plugins/plots/plugin.py
spyder/plugins/plots/widgets/figurebrowser.py
spyder/plugins/profiler/plugin.py
spyder/plugins/profiler/widgets/profilergui.py
spyder/plugins/pylint/plugin.py
spyder/plugins/pylint/widgets/pylintgui.py
spyder/plugins/variableexplorer/widgets/dataframeeditor.py
spyder/utils/icon_manager.py

Apply dark style sheet to QMenus, and elements of the Tour, Pylint, Profiler and DataFrameEditor
Part of #8068

PR: Missing dark style for QMenus, Tour, Pylint, Profiler and DataFrameEditor

---

spyder/plugins/editor.py

This was introduced in PR https://github.com/spyder-ide/spyder/pull/8116
Some plugin variables need to be defined before the call to `self.initialize_plugin()` to prevent this error from happening.
Fixes #8216
<!--- TYPE YOUR GITHUB USERNAME AFTER THE FOLLOWING STATEMENT ---!>

PR: Prevent an error during the initialization of the Editor plugin

---

appveyor.yml
continuous_integration/posix/install.sh
pytest.ini
requirements/test_requirements.txt
setup.py
spyder/app/tests/test_mainwindow.py
spyder/app/tests/test_tour.py
spyder/plugins/tests/test_findinfiles.py
spyder/plugins/tests/test_ipythonconsole.py
spyder/plugins/tests/test_layoutdialog.py
spyder/plugins/tests/test_shorcuts.py
spyder/utils/tests/test_environ.py
spyder/widgets/github/tests/test_github_login.py
spyder/widgets/projects/tests/test_configdialog.py
spyder/widgets/projects/tests/test_projectdialog.py
spyder/widgets/pydocgui.py
spyder/widgets/tests/test_browser.py
spyder/widgets/tests/test_dependencies.py
spyder/widgets/tests/test_editor.py
spyder/widgets/tests/test_explorer.py
spyder/widgets/tests/test_findinfiles.py
spyder/widgets/tests/test_helperwidgets.py
spyder/widgets/tests/test_pathmanager.py
spyder/widgets/tests/test_pydocgui.py
spyder/widgets/tests/test_reporterror.py
spyder/widgets/tests/test_status.py
spyder/widgets/variableexplorer/tests/test_importwizard.py
spyder/widgets/variableexplorer/tests/test_texteditor.py

@spyder-ide/core-developers, please take a look at this PR. Now we can't call fixtures as functions so we have to pass parameters to them with `parametrize`.

PR: Fixes due to the new Pytest 4

---

spyder/plugins/editor/panels/tests/test_scrollflag.py

This avoids possible focus stealing problems with other tests.

PR: Close scrollflag tests after they run

---

.github/PULL_REQUEST_TEMPLATE.md

Per the suggestions of @jnsebgosselin , I've greatly simplified the PR template, reducing its total size by ~40% (by character count).
* Split the PR checklist into two parts: 
* One with a condensed version of the basics that apply to every PR on submission (Contrib Guide, correct branch, PEP8/PEP 257, no-nos) and make that all just one checkbox,
* One with the other three (Docstrings, Unit tests, screenshot) as individual bullets that can …

PR: Greatly simplify and clarify Github pull request template

---

spyder/plugins/ipythonconsole/widgets/kernelconnect.py
spyder/plugins/ipythonconsole/widgets/tests/test_kernelconnect.py

afzalive
I use remote kernels quite often and every time I start a new kernel on a remote machine, I have to fill in all the fields. So finally, this change allows saving these fields so all you have to do is press enter.
In a new section called "existing-kernel" in the CONF, I'm saving the following fields when the user has checked "Save connection settings" checkbox and clicks "Ok" in the …

PR: Save last accepted kernel settings in config

---

spyder/plugins/ipythonconsole/plugin.py

the default for close_fds changed to True in Python 3.7, resulting in closing the handles needed for interrupt and parent polling.
This is a workaround setting `close_fds=False` on Windows to keep kernels interruptible on Python 3.7
without having to wait for https://github.com/jupyter/jupyter_client/pull/408 to be released. jupyter-client > 5.2.3 will do the same thing by default.
Fixes #8013
I certify the above statement is true and correct: Benjamin Ragan-Kelley

PR: Specify close_fds=False on Windows

---

spyder/widgets/reporterror.py

I set the FieldGrowthPolicy of the QFormLayout to QFormLayout.ExpandingFieldsGrow to solve Issue8344
Fixes #8344 
juanis2112

PR: Set right size of error dialog title field in macOS

---

spyder/preferences/configdialog.py

Disable the `Qt windows style` option while using the dark UI theme since the option has no observable effect with the theme.
A preview:
Part of #8068 

PR: Disable Qt windows style if using the dark UI theme

---

spyder/plugins/editor/plugin.py

This error was reported on Windows by @CAM-Gerlach and @jnsebgosselin.

PR: Fix error when Editor's dockwidget is not yet initialized

---

continuous_integration/azure/install.sh

@spyder-ide/core-developers, Anaconda updated Qt to 5.9.7 yesterday and it seems that broke our tests in macOS. 
The workaround (for now) is to use 5.9.6

PR: Fix macOS tests by pinning to Qt 5.9.6 for now

---

spyder/plugins/editor/panels/indentationguides.py

This resolves the issue Indent guides going too far down #7339
This PR solves the issue https://github.com/spyder-ide/spyder/issues/7339
Sample code before the fix
Sample code after the fix
Fixes #7339

PR: Make indentation guides to go up to last line with text

---

spyder/plugins/help/widgets.py
spyder/plugins/ipythonconsole/assets/templates/blank.html
spyder/plugins/ipythonconsole/widgets/client.py

A white background was showing in the initialization of the Help and IPython Console plugins. This sets the background to the correct color in the dark theme.
A preview:
Fixes #8477 

PR: Set dark background color for webview in the Help and IPython Console plugins

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/tests/test_plugin.py

When opening a project with a clean preferences file, the project's previously opened files fail to load into the Editor, an exception is raised, and is the project is then closed or switched, the previously opened files are wiped; this even happens when closing a project and trying to load the prevously open files in the Editor. Therefore, here we check that the relevant preferences item exists before trying to get the saved layout (focused file, file position, etc) and if it no layout information is remembered, just load the files without restoring the focused line and file.
In functional testing both switching projects and opening and closing them, no errors were generated and all behavior was expected when examining opening, saving and restoring the correct files.
I used an if block …

PR: Handle non-existing saved editor layout when loading projects

---

spyder/plugins/help/widgets.py
spyder/plugins/ipythonconsole/widgets/client.py

Fix the background color setting when using QWebView in the IPython Console and Help plugins.
Fixes #8506 

PR: Fix handling background color of Webview when using QWebView

---

spyder/plugins/plots/widgets/figurebrowser.py

Fix the Plots widget's shortcut when there are multiple consoles.
Fixes #8511 

PR: Fix the "Copy Figure" shortcut of Plots pane with multiple consoles

---

spyder/plugins/projects/plugin.py
spyder/plugins/projects/tests/test_plugin.py
spyder/plugins/projects/widgets/explorer.py

I simply moved the `delete_project` method from the `ProjectExplorerWidget` to the `Projects` plugin where the `current_active_project` variable was already defined. I also think this is more coherent to have the `delete_project` method defined there, alongside the `open_project` and `close_project` methods.
Fixes #8515

PR: Fix delete project by moving the code from the project explorer to the plugin

---

spyder/plugins/outlineexplorer/tests/test_widgets.py
spyder/plugins/outlineexplorer/widgets.py

If the `Go to cursor position` is clicked in the Outline explorer and the currently selected file in the Editor doesn't contain any code outline item, the root file item is then selected. 
Fixes #8510

PR: Fix go to cursor position in Outline for newly created files

---

spyder/plugins/plots/widgets/figurebrowser.py

- I've refactored the code to blink the plots so that the size of the figure canvas was not changed during blinking.
- I've prevented the stylesheet applied to the `FigureViewer` and `FigureCanvas`  to be propagated to their context menu.
Note: the blinking of the plot is not visible in the animation due to the low FPS of the captured animation.
Fixes #8523

PR: Fix bad context menu stylesheet and figure blinking in the Plots plugin

---

spyder/config/main.py
spyder/preferences/configdialog.py
spyder/preferences/shortcuts.py

This also improves the default size of our Preferences, which was too small for the new Appearance entry (precisely).
Before
After

PR: Improve layout of Appearance entry in Preferences

---

spyder/widgets/tabs.py

Setup parent reference to QLineEdit of EditTabNamePopup to ensure the set up of the dark style sheet for the dark theme.
Dark Theme
Light Theme
I tested in windows 7, Linux.
Thank you
Part of #8068

PR: Add parent reference to QLineEdit of EditTabNamePopup

---

spyder/config/main.py
spyder/preferences/configdialog.py

This PR builds on the work done in PR #8548. Two things are proposed:
- Stretches only the `Preview` panel
- Center the buttons without harcoding any length values.
These two changes allow the appearance preference dialog to adjust better to various screen, resolution, and theme and when the preference dialog width is increased by the user by mouse dragging.

PR: Improve layout of Appearance entry in Preferences (2)

---

spyder/plugins/variableexplorer/widgets/collectionseditor.py

PR: Avoid KeyError when closing Variable Explorer editors

---

spyder/plugins/editor/widgets/codeeditor.py

Old behaviour:
New behaviour
This PR prevents pasting files/folders paths into Spyder editor when they are copied into the OS clipboard. Text data still can be pasted safely within spyder editor, from spyder editor to external file or from an external source into spyder editor.
Folders/files but can be pasted into Project/File explorers if #8494 is accepted and merged into the master.
Fixes #8566
@Khalilsqu

PR: Prevent pasting non-text data from clipboard into the editor

---

spyder/plugins/ipythonconsole/widgets/figurebrowser.py

I enclosed the warning about plots being rendered in the Plots plugin in top and bottom horizontal bars to solve issue 8520
Fixes #8520
I certify the above statement is true and correct: Juanis 2112

PR: Enclose console warning about rendering of plots

---

spyder/plugins/ipythonconsole/widgets/figurebrowser.py

fix the behavior of the ipython command line after "render_message" is displayed.
Fixes #8603 

PR: Fix missing IPython prompt

---

spyder/plugins/explorer/tests/test_explorer.py
spyder/plugins/explorer/widgets.py

As promised. Here is my solution of the issue: #8567.
The issue only happens in windows and the reason behind it is explained in [Here](https://github.com/pypa/pip/issues/4910) and [Here](https://github.com/ansible/ansible/issues/34335). 
Although the sub-folder(s) are deleted yet an error is raised stating that they are not empty which are in fact empty. therefore, we delete this sub-folder(s) silently and retry shutil.rmtree within a while loop. 
Another solution is to call the function `shutil.rmtree` recursively and introduce sleep before deleting the folder which raises the error as has been done [here](https://stackoverflow.com/a/25831267) and [here](https://github.com/hashdist/hashdist/blob/a322a66d4bcd4b989a6a163cd2569f3e71995f60/hashdist/core/fileutils.py#L69-L89).
I tested both …

PR: Add ability to delete long nested directories on Windows from File/Project Explorers

---

spyder/plugins/ipythonconsole/widgets/figurebrowser.py

Fix printing warning about rendering of plots below the new prompt
Fixes #8626

PR: Fix printing warning about rendering of plots below the new prompt

---

spyder/app/tests/test_mainwindow.py
spyder/widgets/variableexplorer/arrayeditor.py

Currently, the Variable Explorer's Array Editor manually sets the ``flags.writeable`` of the array to True. This is a potentially dangerous practice, and unsupported in Numpy >= 1.16 per numpy/numpy#12791 , while given a copy was made of the array already by Spyder so the flag should already be set if the array is properly writable. Therefore, this PR instead merely checks that it is already ``True`` and sets the ArrayEditor to a ``readonly`` state if for some reason it is not.
Presuming that Numpy 1.16 still allows you to manually set the flag to ``False``, I should be able to add a simple test that ``readonly`` is set and saving is not allowed, if that's necessary.
Fixes #8582  …

PR: Don't force write flag to True in ArrayEditor, to fix compat with Numpy >=1.16

---

spyder/widgets/fileswitcher.py

Changed file switcher to use a single row for a file name and its path and changed paths color to gray.
Part of #8580 (Items 1 and 3)
Juanis2112

PR: Use single row for file name and path and use gray for paths in file switcher

---

spyder/config/main.py
spyder/plugins/plots/widgets/figurebrowser.py

PR: Assign a keyboard shortcut for "next figure" and "previous figure" of the Plots pane

---

spyder/plugins/editor/widgets/recover.py
spyder/plugins/editor/widgets/tests/test_recover.py

The call to os.replace() fails if the original file and the autosave file are
stored on different file systems. In that case, we fall back to copying the
autosave file over the original file and then deleting the autosave file.
Fixes #8631 
I certify the above statement is true and correct: jitseniesen

PR: Fall back to copy and delete if replace fails when restoring autosave

---

spyder/plugins/editor/extensions/closebrackets.py
spyder/plugins/editor/extensions/tests/test_closebrackets.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/tests/test_codeeditor.py

I made a `CloseBrackets` extension to the editor like the `CloseQuotes` extension
Fixes #3414

PR: Make a closebrackets extension for smarter brackets

---

continuous_integration/circle/modules_test.sh
spyder/plugins/editor/extensions/__init__.py
spyder/plugins/editor/panels/__init__.py
spyder/plugins/editor/panels/linenumber.py
spyder/plugins/editor/widgets/codeeditor.py

This is just a bit of refactoring to decrease the amount of imports in CodeEditor

PR: Simplify the way to import Editor extensions and panels

---

README.md
spyder/app/mainwindow.py
spyder/widgets/variableexplorer/namespacebrowser.py

We should presumably merge spyder-ide/spyder-kernels#81 first, just in case, so I marked it WiP (it should be done otherwise).
Once spyder-ide/spyder-kernels#81 is merged and released as part of Spyder-Kernels 0.4.0, Spyder-Kernels will include, as part of the error message, a list of the objects from the namespace that did not serialize successfully, although the operation as a whole did succeed. In that case, Spyder will currently state ``Unable to save current workspace`` followed by ``Some objects could not be saved: obj1, obj2, obj3...``. To be clearer for users while still fully backward and forward compatible in both directions, with the changes in this PR Spyder will automatically detect these strings and display a more appropriate warning message:
Also, it updates the copyright …

PR: Improve warning for when only some namespace objs couldn't be saved

---

spyder/widgets/fileswitcher.py

I changed the font size for the file name and the path in the file switcher to solve issue 8580 item 2.
The following screenshot is using the default rich font size.
The following screenshot is setting the rich font size to 15pt.
Part of #8580 Item 2 
Juanis2112

PR: Change font size for file name and path in the file switcher

---

setup.py

This way users will get the very important fixes in that version related to saving the current namespace of the console.

PR: Increase minimal required version of spyder-kernels

---

spyder/utils/icon_manager.py

We did the initial size selection on macOS with @juanis2112, but things need to be adjusted for other platforms.
This is how things look on Linux:
Before:
After

PR: Adjust attribute icons size on Linux and Windows

---

setup.py

This is because spyder-kernels **0.4.1** is broken.

PR: Increase minimal spyder-kernels version in setup.py to avoid faulty release

---

spyder/widgets/ipythonconsole/client.py

If the kernel takes too much time to start, two things can be causing that:
1. Your system is slow (for whatever reason); or
2. There's a real error preventing the kernel to start.
Even if point 1. is the cause, we still try to read the kernel stderr_file for errors (this change was introduced by me in 3.3.2). But we were not detecting correctly if stderr_file contents are empty (and hence no error was generated) because its contents are read as bytes and then transformed to unicode, which gives `b''` in case of an empty bytes string instead of simply `''`.
What's worst (and the reason why a lot of people is seeing this error) is that we no longer display additional kernel errors after an initial error is shown. This was another change done by me in 3.3.2 to avoid updating the displayed …

PR: Don't show empty kernel error messages

---

spyder/plugins/ipythonconsole/plugin.py
spyder/plugins/ipythonconsole/widgets/client.py

This avoids creating one infowidget per console, which in turn creates one QtWebEngineProcess. If the user creates lots of consoles, these processes start to consume a lot of memory which is not freed until Spyder is closed.
TODO:
Fixes #7091.

PR: Use a single infowidget in the IPython console

---

spyder/plugins/editor/tests/test_introspection.py
spyder/plugins/editor/widgets/base.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/widgets/mixins.py

While an autocomplete is being processed, the cursor can move. Auto completing on another line is clearly not what is expected. The cursor is therefore moved back if this happens. 
Also, the selection of an option in the list was broken.
Fixes #8727 
Fixes #8723 
Impact27

PR: Add position to text completion

---

spyder/utils/syntaxhighlighters.py

PR: Avoid errors when using Pygments to detect the lexer used to highlight a file

---

requirements/conda.txt
setup.py
spyder/plugins/editor/widgets/editor.py

This is needed to avoid an error generated after moving/renaming files outside Spyder while in debug mode.
Fixes #8749.

PR: Enclose logger.debug call in a try/except

---

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py

`test_sympy_client` started to fail today, probably due to a new IPython release (7.3) yesterday.
This tries to fix it.

PR: Fix failing Sympy test

---

spyder/plugins/outlineexplorer/tests/test_outline_explorer.py
spyder/plugins/outlineexplorer/tests/test_widgets.py
spyder/plugins/outlineexplorer/widgets.py
spyder/utils/syntaxhighlighters.py

The outline explorer now works with async keyword function definitions.
```python
import asyncio
class Foo():
def __init__(self):
self.a = 10
async def foo(self):
while self.a:
await asyncio.sleep(self.a)
self.a -= 1
def bar(self):
self.a = 10
async def baz():
pass
```
Before:
After:
Fixes #8556

PR: Handle async functions and methods properly in Outline Explorer

---

spyder/plugins/editor/lsp/client.py
spyder/plugins/editor/lsp/transport/producer.py

This PR solves the following problems:
1. We were not starting the PyLS server with logging options when Spyder is in debug mode, so nothing was logged from it.
2. Our client was logging thousands of failed connection attempts before the PyLS was really ready to receive connections. So this added a ton of useless info to the client's log.
Pinging @steff456 so she's aware of this change. I discovered these problems while trying to find why Rope completions are not working on the PyLS.

PR: Improve logging of PyLS server and our client in debug mode

---

spyder/config/base.py
spyder/config/tests/test_base.py
spyder/utils/programs.py
spyder/utils/tests/test_programs.py
spyder/workers/updates.py

Spyder betas and development versions (i.e. anything with alphabetical characters in the last version element), or with the ``SPYDER_DEV`` set) will automatically use a separate, but persistent config directory, in order to not pollute, modify or wipe the user's primary production config. This behavior can be customized/overriden (necessary for the test) with a environment variable ``SPYDER_USE_DEV_CONFIG_DIR`` environment variable. The tests took far more effort and complexity than they should to get working, but I finally got everything to play nice in the end.
Fixes #7680
and …

PR: Automatically use a separate but persistent configuration directory for non-stable releases

---

spyder/app/mainwindow.py
spyder/plugins/editor/lsp/client.py
spyder/plugins/editor/lsp/manager.py
spyder/plugins/editor/lsp/tests/test_client.py
spyder/plugins/editor/lsp/transport/consumer.py
spyder/plugins/editor/lsp/transport/main.py
spyder/plugins/editor/lsp/transport/producer.py
spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/tests/test_warnings.py
spyder/plugins/projects/plugin.py

* Before we were using HOME by default for `root_path` and that was causing a huge delay when trying to get Rope completions. Now we use an empty dir inside our config one, just like we did in Spyder 3.
* This PR also refactors and renames several methods and constants related to our LSP integration.
@steff456, this should fix the Rope delays you found before. Please try it on your side (by enabling `rope_completion` and disabling `jedi_completion`) and let me know if it works for you or not.

PR: Change default root_path for PyLS and refactor LSP related code

---

spyder/widgets/fileswitcher.py

I implemented an enter function so that users have to press enter to switch files in the file switcher and it does not displays while charging the file with the arrows.
Fixes #
Item 8 of #8580 
Juanis2112

PR: Don't show a file in the Editor immediately after it's selected in the switcher.

---

setup.py

That version fixes the problem with our icons not displaying correctly with PyQt 5.12
Fixes #8748.

PR: Increase minimal QtAwesome version to 0.5.7

---

spyder/plugins/help.py

Use value of the `ObjectComboBox.valid` signal to ensure a force refresh only with valid values
Fixes #8762 

PR: Fix force_refresh to only force with valid object entries (Help plugin)

---

spyder_pylint/widgets/pylintgui.py

Set enabled property of Analize button with `filecombobox.is_valid` to prevent running an analysis without a file path
Fixes #8841 

PR: Set enabled value of start_button with is_valid (Static Code Analysis)

---

spyder/widgets/ipythonconsole/shell.py

See #8908 -- this just goes to `3.x` instead of `master`. Updates message about Qt bindings for `mayavi`.
I affirm the Developer Certificate of Origin
larsoner

PR: Use generic Qt name instead of Qt4 when switching backend for Mayavi

---

spyder/utils/introspection/plugin_client.py

Since we completely replaced our completion architecture in Spyder 4, there's no point in trying to solve this issue, so we simply log the problem and pass.
Fixes #8934.

PR: Don't raise an error if completion plugins fail to start

---

spyder/widgets/github/gh_login.py

The height of the `QSpacerItem` used for the blank space in the dialog where excesive and trigger a resize to use all the height available in the screen.
A preview of the dialog with the change:
Fixes #8978 

PR: Fix over-height resize of the Github login dialog

---

spyder/plugins/editor.py

This was broken after PR #7205.

PR: Fix warning and todo action menu entries

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/editor/widgets/tests/test_warnings.py
spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
spyder/utils/icon_manager.py

This fixes a minor regression after PR #9011 and also:
* Makes todo and warning menus scrollable
* Fixes `next_wng` icon color.
* Fixes cursor positioning after clicking warning actions (it was off by one line).

PR: Fix error at startup when updating warnings menu

---

spyder/plugins/editor/lsp/providers/document.py
spyder/plugins/editor/widgets/codeeditor.py
spyder/plugins/ipythonconsole/plugin.py

This was making our completion and linting facilities to die completely after a `None` completion response from the server.

PR: Fix error when PyLS completions response is None

---

spyder/plugins/editor/plugin.py
spyder/plugins/editor/widgets/editor.py
spyder/plugins/editor/widgets/status.py
spyder/plugins/editor/widgets/tests/test_status.py
spyder/widgets/status.py

Fixes #9006
- The idea is to simplify the UI and remove the clutter. This removes unnecessary labels and uses monospace font to avoid jumps when using the CPU/Mem status widgets.
- The code has also been simplified as well.
- Also, the status widgets that belonged to the editor have been moved to `plugins.editor.widgets.status` as that is the place they should be.
- The lines and cols were moved to the front of all widgets, since that widget size will be changing constantly.
Before:
After: …

PR: Simplify status bar content and reorganize code

---

spyder/config/main.py

As in issue #8640, now with this change, Ctrl+Shift+G can switch to plots.
The feature `adding shortcuts for "next figure" and "previous figure" of plots pane`  mentioned in this issue is still not done.  There are ''Ctrl+PgUp" and "Ctrl+PgDown" in the plots plugin, but they only work when the plugin gets focused. If someone can give me some guidance, maybe I can do something more. Or I may have to leave it to others.
Fixes #8640.

PR: Add Ctrl+Shift+G to switch to plots plugin

---

spyder/widgets/status.py

When status widgets are disabled timers keep running on the background. This PR stops the timer if the widgets are not visible and restart's them once they become visible once again.
Fixes #

PR: Disable status timers if widget is not visible

---

spyder/plugins/editor/widgets/editor.py

Remove the condition that prevents cloned editor tabs in split panels to perform LSP calls
Fixes #8865 

PR: Make completion work in split panels again

---

spyder/preferences/shortcuts.py
spyder/preferences/tests/test_shorcuts.py

Adds the ability to automatically unbind a conflicting shortcut when clicking okay in the shortcut manager.
I'm not an expert but want to contribute. So could anyone help me with this?
Fixes #8293 
I certify the above statement is true and correct: gepcel

PR: Automatically unbind conflicting shortcuts when pressing okay in shortcut manager

---

spyder/plugins/editor/extensions/closebrackets.py
spyder/plugins/editor/extensions/closequotes.py
spyder/plugins/editor/tests/test_introspection.py
spyder/plugins/editor/widgets/codeeditor.py

Dismiss the completion popup if a space is typed in the editor
Fixes #8859 

PR: Fix completion popup dismissed after typing delimeters or operators

---

spyder/app/mainwindow.py

Fixes #9120
@ccordoba12 @dpizetta, is this an option we could consider as a default on `QDarkStyle`?
It would require something like
```css
/* QStatusBar ------------------------------------------------------------- */
QStatusBar {
background: #32414B;
border: 1px solid #32414B;
}
QStatusBar QLabel {
background-color: transparent;
}
```

PR: Force darkstyle style on status bar

---

spyder/widgets/variableexplorer/collectionseditor.py

On Mac we need to use `Qt.Tool` to obtain the desired behavior.
Fixes #9051

PR: Make several varexp editors stay on top
