spyder-ide/spyder

spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/tests/test_plots_widgets.py
---
* ThumbnailScrollBar is not scrolled after the go_next_thumbnail button is pressed.
---
* ThumbnailScrollBar is scrolled after the go_next_thumbnail button is pressed.
Fixes #
=> PR: Scroll to the selected item after go next thumbnail

conftest.py, runtests.py, spyder/plugins/editor/lsp/manager.py, spyder/plugins/editor/lsp/tests/fixtures.py, spyder/plugins/editor/lsp/tests/test_client.py, spyder/plugins/editor/widgets/tests/fixtures.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/plugins/editor/widgets/tests/test_warnings.py
This PR adds a new fixture called `lsp_manager` to avoid creating an LSP client per test (which is very costly). Now we create a client per module and run all tests with it.
=> PR: Use a single LSP manager instance per module in our tests

continuous_integration/azure/install.bat, spyder/app/tests/test_mainwindow.py, spyder/plugins/help.py
Fix validation to correctly check if an object is defined in the shell attached to the Help or current Console.
Fixes #9143 
=> PR: Fix Help plugin string validation for the console

spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/utils/syntaxhighlighters.py
Previously, rehighlighting an open file may set the changed_since_autosave flag and thus trigger an autosave. To guard against this, I added code so that after loading a file, the changed_since_autosave is cleared. This worked for Python files. However, text files use a different highlighter, which delays the call to rehighlight(), so my solution did not work for it and text files always got autosaved.
This PR prevents rehighlight() from setting changed_since_autosave_flag, which is more robust, and also fixes the bug with text files.
Fixes #8654
and understand I am releasing the same …
=> PR: Prevent rehighlight() from setting changed_since_autosave_flag

spyder/config/main.py, spyder/plugins/plots/plugin.py, spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/tests/test_plots_widgets.py
While using the plotting plugin, I found it annoying to have to zoom in and out the image frequently when testing different sizes of image. Feels like an `Auto fit plotting` option is necessary.
So I tried adding one, like (default to False, aka, unchecked):
An example of the original behavior when dealing with different sizes of images (with the auto_fit_plotting option set to false):
Compared to the new behavior when set to true:
Example code:
```python
from matplotlib.pyplot import figure, text
def test_plot(w, h):
figure(figsize=(w, h))
text(.5, .5, f'figsize={w}, {h}', ha='center', fontsize=2.5*w)
test_plot(4, 3)
test_plot(15, 7)
test_plot(8, 12)
```
Fixes # …
=> PR: Add an "Fit plots to window" option to the plots pane

spyder/plugins/editor/lsp/manager.py, spyder/plugins/editor/widgets/tests/test_warnings.py
=> PR: Handle empty options in pycodestyle and pydocstyle preferences

spyder/app/mainwindow.py
Fixes #9281
I noticed on OSX that pressing the shortcut several times in a row would display several Preferences dialogs.
This checks if one is already open to prevent duplicate instances.
=> PR: Avoid the possibility of duplicate preferences dialogs

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/widgets/tests/test_warnings.py
I forgot to suggest this to @jnsebgosselin in PR #9300, but it's pretty important.
=> PR: Mark test_update_warnings_after_delete_line as slow and second

setup.py, spyder/plugins/editor/plugin.py
That's because 0.25 added support for Pylint as a linter but now it it's not possible to turn it off.
Pinging @stonebig about it.
=> PR: Restrict PyLS version to be less than 0.25

spyder/utils/programs.py, spyder/utils/tests/test_programs.py
You can test this change with this script :
```python
import sys
from PyQt5.QtWidgets import QPushButton, QWidget, QApplication, QGridLayout
class SomeClass(QWidget):
def __init__(self):
super().__init__()
layout = QGridLayout(self)
btn_crash = QPushButton('Crash')
btn_crash.clicked.connect(self.crash)
btn_crash2 = QPushButton('Crash2')
btn_crash2.clicked.connect(self.crash2)
btn_close = QPushButton('Close')
btn_close.clicked.connect(self.close)
layout.addWidget(btn_crash)
layout.addWidget(btn_crash2)
layout.addWidget(btn_close)
def show(self):
super().show()
def crash(self):
raise ValueError
def crash2(self):
return self.crash2()
if __name__ == '__main__':
app = QApplication(sys.argv)
window = SomeClass()
window.show()
sys.exit(app.exec_())
``` 
With the proposed changes, executing the …
=> PR: Improvements to the cmd used to start external terminals on Windows

spyder/plugins/editor/plugin.py, spyder/plugins/editor/utils/autosave.py, spyder/plugins/editor/utils/tests/test_autosave.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/editor/widgets/tests/test_save.py
Partially mitigates the impact of #9265 .
It was much more complex than initially anticipated, but with this PR Spyder now removes autosave files after successfully closing them (either choosing not to save, or with no changes present) if an autosave exists, either when closing individual files or when closing the editor entirely. In order to do the latter, since the action is not already synchronized between panes like closing files and the autosaves are not in the ``name_mapping`` dict of the first split pane, I just iterate through all the EditorStacks, ignoring errors (which will occur if there are more than two, or if another Spyder instance removes them first), to make sure all autosaves are removed.
I also added both unit (autosave) and functional (editor) tests of the …
=> PR: Remove autosaves on successful file close to partially mitigate spurious creation bugs

spyder/plugins/editor/lsp/providers/document.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/fixtures.py, spyder/plugins/editor/widgets/tests/test_editorsplitter.py
Send ```textDocument/didClose``` notification on all codeeditor instances that belong to a split tab that is closed.
Fixes #9341 
@andfoy
=> PR: Remove CodeEditor instances from LSP client when split editor is closed

spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/codeeditor.py
From Qt documentation, it is said that `QPalette` should not be used in conjunction with `QtStyleSheets`, because the later override the former.
Since custom stylesheet are propagated to the children when applied to the parent, this means that the background and foreground color of the `TextEditBaseWidget` need to be set with a stylesheet extended with an ID Selector if we want this to be robust instead of doing it by setting a new a color palette.
Moreover, some styles do not use the palette for all drawing such as the Windows Vista and macOS styles.
https://doc.qt.io/qt-5/qapplication.html#setPalette
https://doc.qt.io/archives/qt-5.8/stylesheet-syntax.html#selector-types
Fixes #9248 …
=> PR: Fix code editor background color

spyder/utils/tests/test_vcs.py
I found this problem after releasing beta2 (it was not possible to notice it before).
=> PR: Fix test_get_git_refs when run by Travis on tags

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py, spyder/plugins/editor/widgets/tests/test_introspection.py
Move test_calltip to test_introspection, even though I wasn't able to remove `sig_signature_invoked` to detect the visibility of the calltip.
This PR is part of the issue #7724
Steff456
=> PR: Move test_calltip to test_hints_and_calltips.py

spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/outlineexplorer/api.py, spyder/plugins/outlineexplorer/editor.py, spyder/plugins/outlineexplorer/tests/test_outline_explorer.py, spyder/plugins/outlineexplorer/tests/test_widgets.py, spyder/plugins/outlineexplorer/widgets.py, spyder/utils/syntaxhighlighters.py
Add the possibility to follow the cursor in the outline explorer, so the user knows where (s)he is.
Updates automatically the cell name when the syntax highlighter sees a change
Fixes #885.
impact27
=> PR: Highlight current entry in the Outline Explorer and update it on-the-fly

spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py, spyder/widgets/mixins.py
Signatures that included `kwargs` with default values using `dicts` were interfering with the `''.format`
Fixes #9395
=> PR: Fix signature format for dict kwargs

CODE_OF_CONDUCT.md
In view of the recent and sometimes ugly discussions between @CAM-Gerlach and me, I decided it is time to adopt a code of conduct to try to avoid them in the future.
Both @CAM-Gerlach, me and all other members of our community will be accountable to this code from now on. So if I fall out of line with my comments according to this code, please let me or @goanpeca know about it.
I also want to apologize to @CAM-Gerlach and the rest of the @spyder-ide/core-developers and @spyder-ide/junior-developers for my behavior. I'll try to handle my disagreements better in the future.
=> PR: Add a code of conduct

spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/tests/test_plots_widgets.py
=> PR: Disable zooming and update displayed scaling percent when "Fits plot to window" is checked

spyder/app/mainwindow.py, spyder/config/main.py, spyder/plugins/editor/plugin.py
As per https://bugreports.qt.io/browse/QTBUG-8596, the action needs to be added to a menu for this to work on OSX. Created a "hidden" menu to try this out and it is working :-). now... where should we add these actions? We cannot disable or hide them or this will cease to work
This PR now updates the default shortcut on MAC to use the `control` key as chrome firefox and similar applications do on OSX.
There is a separate issue on the `Spyder Preferences` related to setting shortcuts on OSX that use `tab` and `control`, which currently do not seem to work.
Fixes #6055 …
=> PR: Fix Ctrl+Tab to cycle files on the editor

spyder/plugins/ipythonconsole/widgets/client.py
Everytime I close a console that is running, I have to wait 5s for anything to happen. Not anymore.
Fixes #
Impact27
=> PR: Shutdown running kernels more forcefully so they close faster

spyder/plugins/outlineexplorer/editor.py, spyder/utils/syntaxhighlighters.py
This error shouldn't currently happen in the highlighting code logic but at some point `has_cell_separators` is returning false when there are cell separators in the code.
It looks like `found_cell_separators` is being popped then subsequent calls  `get_outlineexplorer_data` return false.
Fixes #9443
=> PR: Fix code cells that fill the whole screen lose their background highlight

spyder/config/main.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/utils/qthelpers.py
Verify the displayed shortcut in menus for run cell and run cell and advance commands.
*** We need to restart spyder to see the changes.
Fixes #8076 
=> PR: Fix custom shortcut not displayed in menu entries for "Run cell" and "Run cell and advance" 

spyder/utils/tests/test_vcs.py, spyder/utils/vcs.py
=> PR: Handle git not found error and add regression test

spyder/plugins/editor/panels/linenumber.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/utils/icon_manager.py, spyder/widgets/mixins.py
=> PR: Enhance the display of warnings and errors 

spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/widgets/mixins.py
Sometimes I want to autocomplete a word while I have something on the right of it:
```
import math
value = angle / 2
```
In this example, I want to take the `sin` of this angle:
```
import math
value = math.s|angle / 2
```
If I press `<tab>`, nothing will happen. But I want ` math.sin|angle`.
Fixes #
=> PR: Autocomplete only left part of selected word.

spyder/plugins/editor/lsp/manager.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py
Disable LSP availability on codeeditors that have opened files of a particular language, whose LSP server requires a restart.
Fixes #9425
@andfoy
=> PR: Disable LSP services on CodeEditors before restarting LSP client

spyder/plugins/editor/widgets/base.py, spyder/utils/syntaxhighlighters.py
Syntax highlighting is not reliable for cell detection, but now we can use our updated oedata.
Running a loop when ever you scroll probably isn't the best solution but I don't see any performance impacts. 
Fixes #9443
=> PR: Remove cell seporator detection from syntax highlighting and use oedata instead

spyder/plugins/editor/widgets/codeeditor.py
In the animation below, first I'm pressing and releasing the `Ctrl` key two times, than I do the following shortcuts: `Ctrl+C`, `Ctrl+F` and `Ctrl+R`.
Fixes #9501
=> PR: Restore cursor properly in the Editor after a key release or a focus out event.

spyder/plugins/editor/plugin.py, spyder/utils/icon_manager.py
Add icons to toggle uppercase/lowercase menu action from the Material Design Icons.
Fixes #9512
=> PR: Add icons to toggle uppercase/lowercase menu action

spyder/plugins/editor/widgets/codeeditor.py
When the `Ctrl + Tab` and `Ctrl + Shift + Tab` key sequences are not assigned to any shortcut, pressing these keys will be handled in the `keyPressEvent` of the `CodeEditor`.
This PR adds conditions so that the current line is not indented or unintended when these shortcuts are pressed and so that the event is passed to the parent instead, resulting in a cycling forward or backward of the tabs of the Editorstack.
Note that in Windows, when the `Ctrl + Tab` and `Ctrl + Shift + Tab` key sequences  are assigned to a shortcut, the event related to the pressing of these keys is handled by the corresponding shortcut, not by the `keyPressEvent` of the `CodeEditor`. By default, these two key sequences are assigned to the `go to next file` and `go to previous file` shortcut, which trigger the tabs …
=> PR: Prevent indentation/unindentation in the CodeEditor when Ctrl+Tab or Ctrl+Shift+Tab is pressed

spyder/widgets/helperwidgets.py
Removed  background and border color to information icon in file switcher so that it uses MAIN_FG_COLOR. 
Fixes #9442 
Juanis2112
=> PR: Fix background color of information icon in File Switcher

spyder/plugins/editor/widgets/editor.py
Get plugin name from an EditorStack instance to use the file switcher
Fixes #9469 
=> PR: Fix Fileswitcher for 'EditorStack' instances

spyder/plugins/editor/plugin.py, spyder/plugins/editor/tests/test_plugin.py, spyder/plugins/editor/utils/autosave.py, spyder/plugins/editor/utils/tests/test_autosave.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/editor/widgets/tests/test_save.py, spyder/utils/syntaxhighlighters.py
This PR changes the autosave system so that it uses the file contents to decide whether to autosave or not. Currently, we use Qt's `textChanged` to see whether the user made any changes since the last autosave, and if yes, we autosave. It turns out that this leads to a lot of false positives. Running the highlighter emits `textChanged`, as does splitting the editor window. This leads to files being autosaved needlessly and possibly to user confusion when the user is asked whether to recover from these unnecessary autosave files. We can guard against this, but I think the design is quite fragile. In particular, if a user makes an edit and then undoes the edit, it will count as a change for the autosave system and I don't see a good way to detect this.
Here, I try a different approach: …
=> PR: Use file contents to decide when to autosave

spyder/utils/encoding.py, spyder/utils/tests/test_encoding.py
Preserve file permission when saving with `atomic_writes`
Fixes #9381 
=> PR: Preserve file permissions when saving in the editor

spyder/plugins/plots/plugin.py, spyder/plugins/variableexplorer/plugin.py
As noticed in PR https://github.com/spyder-ide/spyder/pull/9452#issuecomment-497460070, there is some extra padding around the `Plots` and `Variable Explorer` plugin under the dark theme.
This PR fixes this by setting the padding and margin of the stack widget used in the layout of both of these plugins to 0 px. I think there is no need to add this under a `is_darkmode` condition because we don't want to have any padding or margin for the stack widget in these plugins under any theme.
This was initially part of PR #9452, but I believe that this change should have its own PR because it is not really related to the size of the icons.
Fixes the issue reported in PR https://github.com/spyder-ide/spyder/pull/9452#issuecomment-497460070
By submitting this Pull Request or typing my (user)name …
=> PR: Remove extra padding around plots and variable explorer plugins

.gitignore
This PR is simply to add `desktop.ini` file to our `.gitignore`
> A Desktop.ini file is a file that determines the way a folder is displayed by Windows. These files can be found in any folder, anywhere on your computer, as long as that folder has a custom appearance set for it. Desktop.ini files control things like the icon used for that folder and its localized name.
=> PR: Add desktop.ini file to .gitignore

spyder/plugins/findinfiles/widgets.py, spyder/utils/qthelpers.py, spyder/widgets/waitingspinner.py
- I fixed the color of the spinner when under the dark mode.
- I created a qthelper function to make the creation of the wait spinner easier if we have to use it somewhere else in the future.
- I added the option to decrease the size of the trail in the spinner class
- I changed the look of the spinner so that plain dots are used instead of lines for the animation.
Here are animations that show the wait spinner after this PR under the dark and WindowsVista theme :
<br>For comparison, here is an animation that shows the wait spinner before this PR :
Fixes #9578 …
=> PR: Style improvement to the wait spinner used in the Find plugin

spyder/plugins/editor/fallback/actor.py
A character 'z' is prepended to the sortText response of the ``FallbackActor``, such that LSP completions are presented first, and then the fallback ones. If LSP is not available, then the fallback ones are displayed sorted.
Fixes #
@andfoy
=> PR: Send fallback completions to the end of the completion widget

spyder/plugins/editor/widgets/codeeditor.py
Restore underlining errors and warning in the editor from PyLS 
I'm not sure if we should use wave underline, it is not showing as much as expected.
However the single line underline is more visible,
Fixes #9472 
=> PR: Restore underlining errors and warnings in the Editor

spyder/config/main.py, spyder/plugins/editor/confpage.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py, spyder/preferences/appearance.py
- Added the `Underline errors and warnings` option to the `Source` menu and to the `Editor\Display` preferences.
Fixes #9627
=> PR: Add an option to turn on/off the underlining of errors and warnings in the Editor. 

spyder/plugins/editor/widgets/codeeditor.py
- I removed the timer for clearing the errors and warnings highlight. Now it is cleared instantly when the errors and warnings tooltip is hidden.
- I have split the logging of the errors and warnings highlight and underline in the extra selections so that we can clear one without affecting the other.
Fixes #9635
Fixes #9631
=> PR: Fix and improvement to the highlighting and underlining of errors and warnings in the Editor

spyder/plugins/editor/tests/conftest.py, spyder/plugins/editor/tests/test_plugin.py, spyder/plugins/editor/utils/autosave.py
This is a temporary stop gap to work around bugs in the autosave system like #9420 when multiple Spyder instances are running simultaneously. Once a more permanent fix is developed, this can be reverted.
<s>I did not include a test, because the code is already run by existing tests and it seems a bit too much effort to write a test for what is meant to be a temporary change, </s>
This does not truly resolve the issue, so no "Fixes #..."
=> PR: Disable autosave if not running in single instance mode

spyder/plugins/editor/widgets/tests/test_editor.py, spyder/widgets/findreplace.py
Earlier backslashes were mishandled in "Replace selection", see #6416 and comments. Basically, most backslashes were removed except before certain characters.
This line 
"This functions must not be used for the replacement string in sub() and subn(), only backslashes should be escaped."
from https://docs.python.org/3/library/re.html#re.escape gave the solution. Earlier, the replace text had been escaped using `re.escape`, now it is only a simple replace as `replace_text.replace('\\', r'\\')`
A test has been added to show that it can handle any type of combination of backslashes in the code, not only the control character combinations \n etc as the previous fix was for.
Fixes #6416 …
=> PR: Fix replace in selection with backslashes

spyder/widgets/findreplace.py
Added tooltip texts for find next and find previous buttons in findreplace. (Sort of a small PR, but coudn't really figure out anything else related to add...)
(Turns out that it LICEcap does not trigger tooltips...)
I certify the above statement is true and correct: Oscar Gustafsson/oscargus
=> PR: Add tooltips for find next/previous buttons

spyder/plugins/editor/widgets/editor.py
Make sure that the active tab is also the one set for the find/replace widget. This was a problem on startup as the find/replace widget had the last opened tab even though another tab may be on top.
Fixes #9688
I certify the above statement is true and correct: Oscar Gustafsson/oscargus
=> PR: Replace in correct file after startup

spyder/plugins/editor/widgets/tests/test_editor.py, spyder/widgets/findreplace.py
After performing "Replace selection", the selection used to go away. With this PR it is restored after replacement.
As far as I can tell there are not tests for the findreplace widget, so it is not straightforward to add a test for it.
Fixes #9685
I certify the above statement is true and correct: Oscar Gustafsson/oscargus
=> PR: Restored selection after replaced in selection

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_codeeditor.py
Strip tabs added by spyder in strings as well.
When line stripping is disabled, it will still remove spaces added by spyder. This adds this behaviour in strings for any state of line stripping.
Before:
After
Fixes #
=> PR: Fix stripping on return for strings

spyder/plugins/plots/widgets/figurebrowser.py
Fixes #9746
As pointed out in https://github.com/spyder-ide/spyder/pull/9720#issuecomment-507902110, the height of the arrow buttons in the thumbnail scrollbar of the plot plugins was too small.
I think this is a macOS issue caused by the fact that scrollbars do not seem to have arrow buttons in this OS.
So instead of setting the height of the arrow button by getting the value from the style, we will set it from the size hint height of the horizontal scrollbar.
=> PR: Fix height of thumbnail scrollbar arrow buttons in the Plots plugin

spyder/app/mainwindow.py, spyder/preferences/configdialog.py
Preferences now stay on top, before if you clicked the Spyder main window the preferences would go to the background. Also if the preferences looses focus, calling the dialog (by shortcut) or toolbutton will give focus to the current open preferences dialog.
Also changed the name of the method as show is more telling that the thing is a dialog
=> PR: Keep preferences on top and give focus if the shortcut is called

spyder/plugins/projects/api.py, spyder/plugins/projects/tests/test_plugin.py
* When closing a project, recent_files are written to workspace.ini relative to project root_path
* Relevant tests changed to expect the recent files fetched from workspace.ini to be relative paths from project root
This allows better portability of projects. Project directories can be moved, or stored in different locations on different systems, and opening the project will still successfully open all the recent files into tabs.
Fixes #5491
I certify the above statement is true and correct: Shannon Keough
=> PR: Save project recent files as relative paths in workspace.ini

spyder/plugins/editor/extensions/closebrackets.py
Automatic insertion of parentheses, brackets and braces should be done against the text of the key press event instead of the key in the `CloseBracketsExtension`.
This is because on some international keyboards, the key that was pressed does not always correspond to the text when some key modifiers are used.
For example, on the macOS with a french keyboard, the key combination `Alt + (` results in the key press event text `{`, while the key would be `Qt.Key_ParenLeft`.
PS: I have no mean to test that this is actually fixing #9749, so please review carefully :)
Fixes #9749
=> PR: Use text instead of key in the editor close bracket extension

spyder/plugins/editor/extensions/closequotes.py
After working on PR #9813, I realized that we needed to use the text of the key press event instead of the key in the `CloseQuotesExtension` too.
This is because on some international keyboards, the key that was pressed does not always correspond to the text when some key modifiers are used.
For example, on my keyboard, I need to press `Qt.Key_Apostrophe` followed by the `Spacebar` to type a single quote character. So, this feature was not working on my own computer and I never realized it until now!
=> PR: Use text instead of key in the editor close quotes extension

spyder/plugins/variableexplorer/widgets/collectionseditor.py
Added milliseconds (and seconds) editing capabilities to variable explorer. Small problem is that QDateTime only supports milliseconds, while timeedit uses microseconds. Hence, any fractional milliseconds will be lost.
No idea how to test this though.
Fixes #9451
I certify the above statement is true and correct: Oscar Gustafsson/@oscargus
=> PR: Add millisecond editing capabilities to variable explorer

spyder/preferences/shortcuts.py, spyder/preferences/tests/test_shorcuts.py
Earlier, the sorting capabilities of the keyboard shortcut table was not re-enabled after the filter text was cleared. Now it is.
Also added a bit of testing for the filtering (including the thing I fixed). Not ideal to hard code the number of names containing "debug", but I selected a string that is probably quite stable...
Finally, renamed `shorcut_table` to `shortcut_table` leading to more changed lines than the actual contribution.
I certify the above statement is true and correct: Oscar Gustafsson/@oscargus
=> PR: Reenable sorting of keyboard shortcuts table after clearing filter text

spyder/plugins/pylint/plugin.py, spyder/plugins/pylint/widgets/pylintgui.py
Earlier, pressing the Analyze button in Code Analysis did not save the file even if the setting requested it (Pressing the shortcut or selecting the menu option did it though.) This is fixed here.
A small change of behavior comes with this PR. Earlier, the code analysis pane was not activated if the automatic save. Now, it is activated, but the analysis is not executed.
Didn't find any suitable tests to base a possibly new test on.
Fixes #9604
I certify the above statement is true and correct: Oscar …
=> PR: Made Analyze button respect "save before" setting

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_indentation.py
Improved the unindent behavior as suggested in https://github.com/spyder-ide/spyder/issues/5734#issuecomment-346209380
For a multiline selection, the lowest number of spaces is used
So assuming four spaces indentation level:
```
5 spaces
9 spaces
```
becomes:
```
4 spaces
8 spaces
```
Also,
```
5 spaces 
6 spaces
```
becomes:
```
4 spaces 
5 spaces
```
which next time becomes:
```
0 space
1 space
```
and stays as
```
0 space
1 space
```
Not sure what the actually expected behavior is here. One may consider first time aligning all rows to the next lower spacing multiple, so 
```
5 spaces
6 spaces
```
becomes
```
4 spaces
4 spaces
```
That require a bit more work though and I do not know if there are any obvious drawbacks with it.
Also added tests for unindent in general, which I do not …
=> PR: Improve unindent behavior

spyder/app/mainwindow.py
Changed the scaling ratios for window layouts from fractions to integer which avoids the `QMainWidget::resizeDocks: all sizes need to be larger than 0` error message and makes the functionality work again.
I do not really have any idea how this can be tested.
Fixes #9878
I certify the above statement is true and correct: Oscar Gustafsson/@oscargus
=> PR: Rescale window layout parameters

continuous_integration/azure/install.sh, spyder/plugins/editor/widgets/tests/test_warnings.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
They started to segfault too much lately.
=> PR: Skip most IPython console tests in macOS and Python 2.7

spyder/plugins/completion/languageserver/client.py, spyder/plugins/completion/languageserver/plugin.py
We were reporting only the traceback but not the error message. This will allow us to understand better errors like #9825.
=> PR: Add error message when reporting PyLS internal errors

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py, spyder/plugins/variableexplorer/widgets/collectionseditor.py
Set the edition of items in the Variable Explorer only with double click
Fixes #9945 
=> PR: Enable edition only with double click (Variable Explorer)

spyder/plugins/breakpoints/plugin.py, spyder/plugins/breakpoints/widgets/breakpointsgui.py, spyder/utils/icon_manager.py
When having breakpoints in files with the same name, it was hard to tell the difference. (Although I realized at a rather later stage that there was a tooltip hover on the file name with the full path.) This PR adds unambiguous file names to the Breakpoints pane.
It should also be slightly more efficient as the name is only computed once per data update.
I also added/corrected an icon for the Breakpoints pane. After some deliberation, I thought that mdi-dots-vertical probably was the best I could find. Three stacked dots.
Earlier, it was the profiler icon, although it wasn't shown in the menu.
In addition, I right-aligned the line numbers (not shown in the screen shot), and refactored the code a bit, using constants for the different columns.
By submitting this Pull Request or typing my …
=> PR: Add unambiguous file names to Breakpoints pane

spyder/plugins/completion/kite/plugin.py, spyder/utils/programs.py
This PR handles Kite on macOS systems properly. Specifically, it fixes the lookup for the Kite application and it also adds the functionality to open `.app` applications properly (which is then used to run Kite).
* Modify `KiteCompletionPlugin` to properly check for the Kite app on macOS
* Implement support to open `.app` applications in `spyder.util.programs`
@its-dhung
=> PR: Improve support for Kite on macOS

continuous_integration/azure/install.bat, continuous_integration/travis/install.sh
Tests started to fail with a new version of Python 3.7 released by Anaconda (pip is not pulling wheels on Linux for all packages with Python 3.7.4).
The fix was to downgrade to 3.7.3 in the meantime.
=> PR: Fix tests in Travis

README.md, setup.py
Python 3.4 reached end of life several months ago, so there's no need to keep supporting it.
=> PR: Drop support for Python 3.4

spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/tests/test_introspection.py
Remove no match entry on code completion widget when there's no completions available.
Fixes #10002 
=> PR: Remove "No match" entry in editor's code completion widget

spyder/plugins/projects/plugin.py
Fixed opening any recent project except 1st
The root of problem was incorrect work with closures. On each iteration lambda was created, but it used `project` variable reference defined outside lambda. So, all lambda store the same reference to variable which changes each iteration. After stopping iteration it stores last iteration value
Fixes #10014
=> PR: Fix "Projects > Recent" menu entries

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_codeeditor.py, spyder/py3compat.py, spyder/utils/qstringhelpers.py, spyder/utils/syntaxhighlighters.py, spyder/widgets/mixins.py
Attempt to correct some of the problems that arise from the string length difference between `QString` and Python3 `str`
Searching for `🚫`:
Before
After
Fixes #10039 almost completely
a = '💆🏽‍♂️' still gives:
And highlighting is broken in qtconsole.
=> PR: Solve some issues with QString compatibility with emojis

spyder/app/mainwindow.py, spyder/utils/qthelpers.py
Keep track of file open events that appen before the app is fully up. This is useful when the app is opened by clicking on a python file. The current behaviour is to open the app but not display the opened file.
Fixes #
=> PR: Avoid discarding file open event in macOS app

spyder/plugins/editor/extensions/docstring.py, spyder/plugins/editor/panels/scrollflag.py, spyder/plugins/editor/utils/editor.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_breakpoints.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/outlineexplorer/tests/test_outline_explorer.py, spyder/plugins/outlineexplorer/tests/test_outline_explorer_editor.py, spyder/plugins/outlineexplorer/widgets.py, spyder/widgets/fileswitcher.py
Replaced `block.firstLineNumber` by` block.blockNumber`, which is what is meant by line number:
Here `class C():` is on `firstLineNumber` 14 and on `blockNumber` 18
Fixes #10073
=> PR: Fix getting blocks by numbers in the editor

spyder/plugins/completion/kite/plugin.py
If I close Kite on OSX and start spyder I was getting a `psutil.ZombieProcess` error.
Fixes #
=> PR: Prevent Kite error at startup if Kite is closed on macOS

spyder/plugins/editor/tests/conftest.py, spyder/plugins/editor/tests/test_plugin.py, spyder/plugins/editor/utils/autosave.py, spyder/plugins/editor/utils/tests/test_autosave.py, spyder/plugins/editor/widgets/recover.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/editor/widgets/tests/test_recover.py, spyder/utils/external/lockfile.py, spyder/utils/programs.py
This PR stores which files are autosaved and where in a separate file called `pidNNN.txt` in the autosave directory, where `NNN` is the pid of the Spyder process. This information is used when the files are recovered after a crash. Before this information was stored in the Spyder config file.
The new approach has two advantages. Firstly, if the user is running multiple Spyder instances simultaneously, then one instance overwrites the changes the other instance makes to the config file, so the autosave info got muddled in the old system, while now each instance has its own location to write its data to. Secondly, by also recording the pid of the Spyder process that created the autosave file, we can check whether that process is still running. and not change the autosave file if it is. …
=> PR: Store autosave information in separate files instead of the Spyder config

spyder/plugins/completion/kite/__init__.py, spyder/plugins/completion/kite/client.py
Previously, we were using logic to ping Kite up to 40 times before considering Kite unreachable, and permanently disabling the Kite completions plugin.
It is much more robust to always make Kite completions requests, and let the connection error out. The `ConnectionError` happens very quickly, so this has no noticeable performance impact. There are many other types of I/O happening per-keystroke that are much slower.
In order for the user experience to be pleasant, this depends on completely ignoring `ConnectionError`s: #10029. This PR does not address that issue. …
=> PR: Always enable Kite completions

spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/editor.py
If a tooltip is displayed and the file was siwtched, the tootlip of the previous file remained on top. Now tooltips are hidden on file change.
See animation
Fixes #
=> PR: Hide tooltips if switching editor in stack

spyder/plugins/editor/widgets/codeeditor.py
Changed code to find next/previous warnings use a for loop instead of a while as in this case we know the max amount of possible iterations. Also refactored the code a bit.
Related to #10024
=> PR: Fix code editor freeze when searching for next/previous warnings

spyder/plugins/completion/kite/providers/document.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_introspection.py
Fixed completion entries order depending on the first letter of the word to complete.
Fixes #10109
@andfoy
=> PR: Fix completion order for lower/upper case entries

spyder/plugins/completion/fallback/plugin.py, spyder/plugins/completion/languageserver/client.py, spyder/plugins/completion/plugin.py, spyder/plugins/editor/widgets/codeeditor.py
These errors were triggered when a CodeEditor instance was removed before responses can be processed by it.
=> PR: Avoid RuntimeError when handling completion responses

spyder/plugins/projects/confpage.py, spyder/preferences/maininterpreter.py
This helps to reduce the time necessary to change the main Python interpreter in our preferences by a significant amount.
=> PR: Don't call MainWindow's apply_settings method when no needed

spyder/config/main.py, spyder/plugins/completion/languageserver/client.py, spyder/plugins/completion/languageserver/confpage.py, spyder/plugins/completion/languageserver/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/preferences/general.py
This PR avoids touching LSP server configurations when selecting a free port for the server. That was triggering a server restart, which (due to another bug, fixed here too) was stopping LSP services for the current open files.
This PR also renamed the PyLS option about the "command" we use to start it. Since we really use `sys.executable -m <command>`, that option doesn't correspond to a command (or executable) in your system, but to a Python module that implements the server.
Fixes #9933
=> PR: Fix PyLS options not being updated correctly when a previous server was running

spyder/app/mainwindow.py, spyder/plugins/explorer/plugin.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/projects/plugin.py
Hide size/type (or kind on mac) columns on file explorer and a add show/hide actions to header with right click (context menu) and plugin options.
- Explorer is now on the left and tabbed with the project explorer
- Size/Modified/Kind Columns have been removed
- Sorting by these columns is still possible via Context menu
Fixes #
=> PR: Hide size/type columns and add show/hide actions to header (right click) and plugin opts.

spyder/plugins/completion/kite/client.py, spyder/plugins/completion/kite/plugin.py
- Verify name and process status to check if kite is running to prevent zombie processes interfering with the check.
- Default available languages for the Kite client to `python` to ensure initial registration of the client even when a connection error raise.
Fixes #
=> PR: Detect zombie process and add python as default Kite client available language 

spyder/plugins/findinfiles/widgets.py, spyder/widgets/helperwidgets.py
Add a None parameter to the `style.subElementRect(QStyle.SE_ItemViewItemText, options)`  function to prevent the crash
Fixes #7008 
=> PR: Fix keyboard shortcut dialog crash

spyder/plugins/completion/languageserver/transport/tcp/producer.py, spyder/py3compat.py
This avoids a total freeze at startup when there's a TCP socket listening at `host:port` (as defined in our preferences), which rejects our connection.
I also tested things with a simple ping/pong server and (fortunately) in that case Spyder doesn't freeze, but this fix is not really needed.
=> PR: Catch errors when sending messages to tcp sockets that reject a connection from our LSP client

spyder/plugins/completion/kite/providers/document.py, spyder/plugins/editor/widgets/codeeditor.py
The kited application needs the current cursor position to find out about the currently edited token. This token is then used to show the documentation in Kite Copilot.
This pull request adds the missing properties to the event requests which are send to Kite on localhost.
I certify the above statement is true and correct: jansorg
=> PR: Send current cursor position to Kite to enable autosearch in Kite Copilot

spyder/api/plugins.py, spyder/api/preferences.py, spyder/plugins/base.py, spyder/plugins/editor/confpage.py, spyder/preferences/configdialog.py, spyder/preferences/general.py
Other plugins can now change other plugin options. This is needed to group some settings that are better displayed on a different configuration page of the config dialog. Should be used with care and sparingly!
Fixes #
=> PR: Add ability to modify other plugin options

spyder/config/main.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_codeeditor.py
This also turns off that option by default because it's really more for power users.
Fixes #10248.
=> PR: Only remove trailing spaces when option is turned on in Preferences

spyder/plugins/editor/widgets/editor.py, spyder/utils/encoding.py
Catch a system error and write the file normally. This happens because some systems doesn't support the option to sync directories.
Fixes #10208 
=> PR: Fix OSError when saving files on Linux

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_codeeditor.py
When the editor is split, a change in one editor should not trigger a strip in the other editor. Here, the focus is checked before stripping.
Fixes #
=> PR: Avoid stripping if the event comes from another editor

spyder/plugins/completion/languageserver/client.py, spyder/plugins/completion/languageserver/confpage.py, spyder/plugins/completion/languageserver/plugin.py, spyder/utils/misc.py
Add several validations to avoid problems with external servers
1. Don't allow to activate the external server option when the address of external server is not different from the one of current one (this avoids issue #9992).
2. Don't allow to activate the external server option when there's no external server listening at `host:port`:
3. Don't create an LSP client to an external server at startup if that server is not listening at `host:port` (this should avoid issue #10209):
4. Allow to start an internal server if the session started with a non-working external server. 
Fixes #10209 
Fixes #9992.
with respect to all commits and content included …
=> PR: Add several validations for external LSP servers

spyder/plugins/completion/fallback/actor.py, spyder/plugins/completion/fallback/tests/test_fallback.py, spyder/plugins/completion/fallback/utils.py, spyder/plugins/editor/widgets/codeeditor.py
This is a proposal to change the completions filtering behavior to show completions that exactly match what the user has typed under the cursor.
As far as I can tell, the main reason to have the filtering was that the fallback plugin would generate "identity" completions via tokenization, so I filter out tokens that are under the cursor there.
The advantage to showing exact matches is primarily if there are many other completions, and exact matches are not shown, then if I hit enter, the wrong completion will be inserted:
Please let me know if you disagree with this change. Also, I'm sure tests will fail, so I'll fix those.
with respect to all …
=> PR: Show exact match completions

spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/kite/providers/document.py, spyder/plugins/editor/extensions/snippets.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/utils/snippets/ast.py, spyder/utils/snippets/lexer.py
This PR addresses all of the code snippets errors reported on #10230 
Fixes #10289.
Fixes #10230
@andfoy
=> PR: Fix several code snippets corner cases

spyder/config/main.py
It was introduced because I had the option in two PRs that both got merged. It doesn't actually break anything, since if you duplicate keys in a dict literal, the latter one is taken. But we should fix it.
@ccordoba12
=> PR: Remove extraneous Kite config option

spyder/plugins/completion/plugin.py
Fix a deadlock that occur when using go to definition. I was able to get a traceback but I think this happens when going to a definition in a file that is not open.
Deadlock traceback (this is a faulthandler traceback, so it is inverted)
```python-traceback
File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/completion/plugin.py", line 114 in receive_response
File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/plugin.py", line 1925 in load
File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/plugin.py", line 1297 in <lambda>
File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/editor.py", line 2389 in <lambda>
File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/codeeditor.py", line 1229 in handle_go_to_definition
File …
```
=> PR: Fix deadlock when going to a definition

spyder/widgets/mixins.py
We were detecting documentation of Kite completions as signatures making huge hint/tooltips full of spaces (`&nbsp`) when parsing them.
Fixes #10388 
=> PR: Add validation for completion signature processing

requirements/conda.txt
That version brings Jedi 0.15, which has several errors.
=> PR: Don't use PyLS 0.29 for now in our tests

spyder/plugins/editor/widgets/codeeditor.py
Prevent an `IndexError` when trying to get parameters for a function's calltip that doesn't have any parameters (for example with the range function):
Fixes #10372
=> PR: Add validation for number of parameters in function calltip

spyder/plugins/editor/widgets/codeeditor.py
Ensure activeParameter isn't outside parameters list range. Thanks @ok97465 for proposed solution :+1:
Fixes #10372 
=> PR: Check length of parameters data vs active parameter index

spyder/plugins/editor/plugin.py, spyder/plugins/editor/utils/switcher.py
Add a switch to plugin to the editor widget for raising when there's another plugin over the editor.
Fixes #10335 
=> PR: Editor plugin is raised after selecting file in the switcher

spyder/plugins/profiler/widgets/profilergui.py, spyder/plugins/pylint/widgets/pylintgui.py
#7031 and #9536 are both caused by the profiler and code analysis running in a QProcess, which uses the default system encoding. This PR fixes this by setting the encoding, currently to utf8, but ideally to the encoding used by the file in question.
This is rather straightforward if the file is opened in the editor, but not that straightforward otherwise. Any ideas how to do that in these cases? Or is utf8 a good enough guess in general?
I'll try to figure out some tests. Probably code analysis is easiest (as there were no results earlier). For profiling one will have to check that no error dialog shows up.
Fixes #7031
Fixes #9356
with respect to …
=> PR: Set encoding to unicode for Profiler and Pylint processes

spyder/plugins/ipythonconsole/widgets/shell.py
For now, the `runfile` function executes files on the frontend machine if the file is open in the editor, and on the kernel machine if they are not. This means that running `runfile` in the console might not run the same file depending on the files open in the editor.
This PR would have the frontend open the file instead of the backend to avoid this inconsitancy.
The solution for running local files would be to use `%run` magic in the console.
Fixes #
=> PR: Try opening closed files in the frontend side

spyder/plugins/editor/widgets/codeeditor.py
The issue  #10453 occured because parameter_idx = -1 and len(parameters)=0.
Fixes #10453 
=> PR: Check length of parameters when trying to parse signatures

spyder/plugins/completion/kite/providers/document.py
LSP and Qt both "talk about" UTF-16 code units (i.e. UTF-16 16-byte chunks, of which 1 or 2 may be used for a single code point):
- https://doc.qt.io/qt-5/qtextcursor.html#position
- https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#text-documents
So Qt / LSP should be compatible by default. Kite, on the other hand, allows the client to specify an encoding, but uses UTF-32 (i.e. Unicode code points) as the default.
So we need to tell Kite that we're using UTF-16.
Let me know if you have suggestions for test cases here.
fixes #10401 
and understand I …
=> PR: Send correct Unicode offset encoding to Kite

spyder/plugins/editor/panels/manager.py, spyder/plugins/plots/widgets/figurebrowser.py
Calling deleteLater in qtpy is a bad idea:
- It might delete the C++ object while leaving the python wrapper intact, leading to a segmentation fault
- It is not needed as as soon as the wrapper is collected by the python garbage collector, the C++ object will be deleted as well.
The proper way is to remove all existing regerences to the python object, not deleting the underlying C++ object as this might lead to segfaults in random places.
Fixes #
=> PR: Remove deleteLater calls

spyder/plugins/editor/utils/switcher.py, spyder/plugins/outlineexplorer/api.py, spyder/plugins/outlineexplorer/widgets.py
When a file is shortened outside of spyder (Like checkout something with git), this file is reloaded in spyder. If the line the cursor was on doesn't exist anymore, a segfault takes place because the block no longer exists: see traceback:
```
Fatal Python error: Segmentation fault
Current thread 0x0000000117862d40 (most recent call first):
File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/outlineexplorer/widgets.py", line 84 in line
File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/outlineexplorer/widgets.py", line 154 in <lambda>
File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/outlineexplorer/widgets.py", line 154 in get_item_children
File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/outlineexplorer/widgets.py", line 164 in item_at_line
File …
```
=> PR: Fix blocknumber segfault

spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/tests/test_plots_widgets.py
Fix the removal of thumbnails on the plots pane when they are removed from the parent widget without using deleteLater method.
Fixes #10489 
=> PR: Remove thumbnails on plots pane successfully

spyder/config/main.py, spyder/plugins/completion/languageserver/confpage.py, spyder/plugins/completion/plugin.py, spyder/plugins/editor/widgets/tests/test_introspection.py
This is an update of https://github.com/spyder-ide/spyder/pull/10493, based on the feedback provided there: https://github.com/spyder-ide/spyder/pull/10493#discussion_r337796602
1. Before the timeout, we continue waiting until all "`wait_for`" providers have returned.
- this behavior is new
2. After the timeout, we wait until any "`wait_for`" provider has returned a non-empty response (or until all "`wait_for`" providers have returned empty responses).
- this is the same as the current default behavior
Fixes #10447 …
=> PR: Add a "wait_for" timeout for completions

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_introspection.py
Word under cursor selection fails (Qt issue 🤷‍♂?) if the cursor is next to a parens. Added a workaround for this and a test.
Fixes #10448
=> PR: Fix on the fly completions inside braces

spyder/config/main.py, spyder/plugins/completion/languageserver/confpage.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/completion.py, spyder/plugins/editor/widgets/editor.py, spyder/utils/icon_manager.py, spyder/widgets/calltip.py, spyder/widgets/helperwidgets.py, spyder/widgets/mixins.py
I used cProfile & the [profilehooks](https://mg.pov.lt/profilehooks/) library to profile completions-related logic. The reason for the lag was all in the rendering logic, so I focused on reducing wasted work there. In particular some Qt functions are slow, so we should avoid calling them when necessary.
1. reduce calls to `hide_tooltip()`
2. reduce calls to `icon_manager.icon()`
3. use `''.join()` instead of string formatting with `str.format`
4. reduce calls to `setStylesheet`
5. use a fixed size hint for completions list items, because creating a `QTextDocument` and calling `idealWidth` every time is very slow.
- I tested it on various screen sizes, and it seems to scale very well.
- I used the size that I was seeing the old behavior typically return (it always returned the same size in …
=> PR: Completions performance improvements

spyder/plugins/completion/kite/providers/document.py, spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/completion.py, spyder/plugins/editor/widgets/tests/test_introspection.py
Kite returns a replacement range with each completion indicating where to insert the completion within the buffer. This is particularly useful for more non-traditional completions, such as Kite's dict completions, where simply matching the preceding identifier is not enough. Kite's dict completions were previously broken in Spyder, but this change fixes them.
1. Support the `textEdit` functionality of the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_completion)
2. Properly respect the `filterText` when deciding whether completions are still valid.
3. Update the Kite provider to specify a `textEdit` instead of `insertText`, and also not use `filterText`, since Kite filters internally (and will always do so -- it is part of …
=> PR: Correctly handle Kite replacement range, fixing dict completions

spyder/plugins/completion/kite/providers/document.py, spyder/plugins/editor/widgets/codeeditor.py
This PR enables Kite copilot to display documentation whenever the cursor is moved on click.
Fixes #10349
@andfoy
=> PR: Retrieve Kite copilot documentation on click

spyder/plugins/completion/kite/widgets/install.py
I also fixed an annoying issue where the install dialog would show up centered on a different display than the main Spyder window, and every time the screen changed, it would move itself back to that display.
Fixes #10571 
I certify the above statement is true and correct: @metalogical
=> PR: Update Kite installer links & remove centering logic

spyder/plugins/editor/widgets/codeeditor.py
Filter completion list to prevent completions with an empty 'insertText' value.
Seems like the LSP is returning this as a completion:
```python
{'label': '',
'kind': 9,
'detail': 'cv2.cv2',
'documentation': 'cv2.cv2()\n\nPython wrapper for OpenCV.',
'sortText': (1, 'a'),
'insertText': '',
'filterText': '',
'insertTextFormat': 1,
'provider': 'LSP'}
```
Fixes #10593 
=> PR: Filter completions with an empty value for the 'insertText' key

spyder/app/tests/test_mainwindow.py, spyder/config/main.py, spyder/plugins/ipythonconsole/widgets/namespacebrowser.py, spyder/plugins/variableexplorer/widgets/namespacebrowser.py, spyder/utils/icon_manager.py
=> PR: Add button and keyboard shortcut to refresh the variable explorer during execution

spyder/plugins/editor/widgets/editor.py
Remove modifying asterisk when cancelling "Save As", fix bug #9865
if cancelling "Save as", don't treat the file like it was newly created. 
Fixes #9865
Rotem Gabay
=> PR: Don't mark files as dirty if "Save as" operation is canceled

spyder/plugins/completion/kite/plugin.py
Currently, we send a request many times, due to many events triggering that code path.
This isn't a huge deal, but every time the file is requested, a new file is written (to a temp directory). So it's better to avoid sending a new request whenever possible.
Not tested, but not that critical, so it's not worth the time.
I certify the above statement is true and correct: @metalogical
=> PR: Don't repeatedly request Kite onboarding file

spyder/plugins/completion/kite/providers/document.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/conftest.py, spyder/plugins/editor/widgets/tests/test_introspection.py
Fixes exception raised due to #10605 (described [here](https://github.com/spyder-ide/spyder/pull/10605#issuecomment-550529046))
How can we make sure we don't regress again? Maybe we need fixturized test cases with sample completions dicts that we return to the completions logic and ensure it works properly with `textEdit`s. Thoughts?
I certify the above statement is true and correct: @metalogical
=> PR: Fix completions bug in Kite introduced by PR 10605

spyder/widgets/status.py
This is to fix some widget blinking that occurs during the startup of Spyder after PR #10483
=> PR: Prevent status bar widget blinking during startup

spyder/plugins/completion/kite/providers/document.py, spyder/plugins/editor/widgets/codeeditor.py
Send a selection to Kite when the cursor is in fact a selection.
Makes ctrl-space when a placeholder is selected correctly return Kite completions.
Addresses part of the issue noted in #10277 
I certify the above statement is true and correct: @metalogical
=> PR: Send Kite completions requests correctly for selections

spyder/plugins/findinfiles/widgets.py
For performance reasons, `setUniformRowHeights` was set to `True` for the `ResultsBrowser` in PR #10582.
However, this results in a lot of vertical space between each line match item, due to the fact that the file match items are displayed on two lines.
This PR proposes to put the file match items on one line, like it is done for the file switcher.
Follow PR #10582
=> PR Display file match items on one line in the find in files browser

spyder/widgets/switcher.py
The goal here is to calculate the height of the file switcher items based on (1) their content, (2) the hard-coded padding value and (3) the font size, instead of using a hard-coded value (that was defined in `_HEIGHT`).
Here is how it looks after the changes :
The file switcher was not displaying it's content correctly for me on Spyder 4.0.0.dev0 (Commit: bae9aaff4) in Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 
=> PR: Calculate switcher items height from content, padding and font size instead of hard-coded values

spyder/widgets/helperwidgets.py
From the [documentation](https://srinikom.github.io/pyside-docs/PySide/QtGui/QStyle.html#PySide.QtGui.PySide.QtGui.QStyle.drawControl):
> PySide.QtGui.QStyle.drawControl(element, opt, p[, widget=None])
> The widget argument is optional and can be used as aid in drawing the control. The option parameter is a pointer to a PySide.QtGui.QStyleOption object that can be cast to the correct subclass using the qstyleoption_cast() function.
Apparently, if we do not pass an appropriate widget argument, it causes some minor issues with the UI (see image below).
and understand I am releasing the …
=> PR: Make to HTMLDelegate drawControl

spyder/widgets/switcher.py
Trick the html delegate that is used in the list view of the file switcher into thinking that it is active at all times, even if strictly speaking it is not.
See #10682 for more details.
Fixes item number 2 in https://github.com/spyder-ide/spyder/issues/10682
=> PR: Make the list view of the file switcher look active at all times.

spyder/app/mainwindow.py
This is simply to fixed a minor bug that was introduced by PR #10623.
Fixes the following error :
```python
File "C:\Users\User\spyder\spyder\app\mainwindow.py", line 3016, in show_path_manager
"""Update dockwidgets features settings"""
File "C:\Users\User\spyder\spyder\widgets\pathmanager.py", line 98, in __init__
text=_("Move to top"),
File "C:\Users\User\spyder\spyder\widgets\pathmanager.py", line 197, in setup
if path not in self.not_active_pathlist:
TypeError: can only concatenate tuple (not "list") to tuple
``` …
=> PR: Fix an error with the Python path manager widget

spyder/widgets/switcher.py, spyder/widgets/tests/test_switcher.py
- Items in the switcher are now sorted in Ascending order instead of Descending order.
- The filtering is now done by the `SwitcherProxyModel(QSortFilterProxyModel)` instead of hiding rows in the `Switcher(QDialog)`, which was causing problems with the new sorting order and was prone to errors.
Fixes #10682
=> PR: Sort items in Switcher in ascending order and move logic to filter items in the proxy model

spyder/preferences/shortcuts.py
- Removed window context help button (because it doesn't do anything)
- Show `<None>` in `Current shortcut` label when there is no key sequence assigned to a shortcut
- Set layout size constraint to SetFixedSize, which allows the dialog to resize properly when the text of the warning label changes.
- Improved and made the text and style of the warning label more uniform.
=> PR: Minor improvements to the shortcut editor

spyder/app/mainwindow.py, spyder/config/gui.py, spyder/config/manager.py, spyder/config/user.py, spyder/plugins/base.py, spyder/plugins/console/widgets/shell.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_shortcuts.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/shell.py, spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/variableexplorer/widgets/arrayeditor.py, spyder/plugins/variableexplorer/widgets/dataframeeditor.py, spyder/plugins/variableexplorer/widgets/namespacebrowser.py, spyder/preferences/shortcuts.py, spyder/utils/qthelpers.py, spyder/widgets/findreplace.py, spyder/widgets/shortcutssummary.py, spyder/widgets/tabs.py
Moved shortcut management from `config/gui.py` to `config/manager.py`
Now the shortcut handling is used via `CONF` which will correctly parse external plugin configuration.
Fixes #3254 
Fixes #3321 
=> PR: Add methods to handle external plugins shortcuts

spyder/plugins/editor/widgets/recover.py
Add window flag to the `RecoveryDialog` to ensure is on top of the `Splash` widget
Fixes #
=> PR: Show the recovery dialog on top of the splash screen

spyder/utils/qthelpers.py
=> PR: Fix updating actions tooltips after a change is applied to the shortcuts

spyder/api/preferences.py, spyder/preferences/configdialog.py
This change allows to restart spyder from any configuration page that inherits from PluginConfigPage. 
This change is necessary for PR https://github.com/spyder-ide/spyder-terminal/pull/156 to work
=> PR: Add restart option to PluginConfigPage

continuous_integration/azure/install.bat, continuous_integration/azure/install.sh, continuous_integration/travis/install.sh, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/config/lsp.py, spyder/plugins/completion/languageserver/plugin.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/preferences/configdialog.py, spyder/preferences/maininterpreter.py
- Tests on actual working of LSP are on https://github.com/palantir/python-language-server/pull/680
- This is part of issue #7724.
Fixes #10299
Fixes #10646
Fixes #1004 
=> PR: Add LSP support for handling jedi script extra paths and environment

spyder/plugins/editor/widgets/codeeditor.py, spyder/utils/syntaxhighlighters.py
This avoids making a folding request per block for the entire document.
Fixes #10766.
=> PR: Don't request folding when rehighlighting the whole document

spyder/plugins/ipythonconsole/plugin.py
=> PR: Improve error message of spyder-kernels version in external interpreter

spyder/plugins/editor/widgets/codeeditor.py
This PR fixes a regression where return and backspace would trigger automatic completions
Fixes #10797
@andfoy
=> PR: Prevent automatic completions on backspace and return

spyder/plugins/base.py
(https://www.cockos.com/licecap/))
Since external plugins might not define a shortcut for the pane, this extra exception needs to be caught.
=> PR: Catch extra exception for external plugins

spyder/app/tests/test_mainwindow.py
=> PR: Skip test_debug_unsaved_file in macOS and Python 3

spyder/app/mainwindow.py, spyder/app/restart.py, spyder/utils/programs.py
- The problem was caused because we were adding sys.path to PYTHONPATH, so the restart script could import the Spyder modules.
- But we only need to add the directory from which bootstrap.py was started.
- This was generating an error in both the IPython console and the PyLS.
=> PR: Fix restart when using an external interpreter in development mode

spyder/plugins/editor/widgets/recover.py
Hide SplashScreen to show on top the RecoveryDialog since there is an issue regarding dialogs on MacOS: https://bugreports.qt.io/browse/QTBUG-49576 
Fixes #
Juanis2112
=> PR: Show autosave dialog on top of splash screen in macOS

spyder/plugins/variableexplorer/widgets/collectionseditor.py
Use `proxy_model` instead of `source_model` to properly map the update of the plot actions state
to the correct items in the Variable Explorer
A preview:
```python
import numpy as np
import matplotlib.pyplot as plt
def get_mse(target, synth):
weights = np.sum(target, axis=0)
mse = None
return mse, weights
spec = np.random.rand(128, 159)
mse, energy_mel = get_mse(spec, spec)
mse, energy_spec = get_mse(spec, spec)
```
Fixes #10917 
=> PR: Use proxy_model when refreshing plot actions state

.circleci/config.yml, .travis.yml, azure-pipelines.yml, setup.py
This is the first (and pretty simple) step to support only Python 3 in Spyder 5. Additionally, our plan is to support only Python 3.6+ in that version.
This will also be helpful to reduce the amount of available slots required to run our tests in each CI service.
=> PR: Remove Python 2 and 3.5 from our CIs

binder/environment.yml, requirements/conda.txt, setup.py, spyder/dependencies.py, spyder/plugins/ipythonconsole/widgets/namespacebrowser.py, spyder/plugins/variableexplorer/widgets/collectionseditor.py
- asizeof doesn't seem to work correctly:
```
In [1]: import numpy as np
In [2]: from pympler.asizeof import asizeof
In [3]: val = np.zeros(1000*1000*20)
In [4]: asizeof(val)
Out[4]: 160000096
In [5]: # modify val in the variable explorer
In [6]: asizeof(val)
Out[6]: 96
In [7]: np.shape(val)
Out[7]: (20000000,)
In [8]: 
```
- If a variable was loaded from the kernel, it should be sent back to the kernel.
- I am not sure spyder-ide/spyder#7158 still applies with the current architecture anyway.
- It there must be a limit, it should be implemented at the comms level, not here.
Fixes #10955 …
=> PR: Remove serialized length limit when sending modified variables back to the kernel

spyder/app/tests/test_mainwindow.py
=> PR: Skip test_go_to_definition completely on macOS

spyder/preferences/shortcuts.py
With this change, I can now register correctly the `Ctrl + Space` keysequence in the `ShortcutEditor`.
This may also solve #10786, but this will need to be tested, because on Windows, `Alt + Space` is still not usable after these changes.
=> PR: Fix the shortcut override in the ShortcutEditor.

spyder/preferences/maininterpreter.py, spyder/widgets/status.py, spyder/widgets/tests/test_status.py
1. Updated [MainInterpreterConfigPage.apply_settings](https://github.com/dtrent1/spyder/blob/d2278009d4a8aa5b58446fe7ae9153783e10243c/spyder/preferences/maininterpreter.py#L251) method to call the main window apply_settings method so that the interpreter is updated in the status bar. Fixes #11006.
2. Conda on windows puts the main interpreter .exe in the root environment folder, so the environment name is only one folder up. Modified [CondaStatus._process_conda_env_info](https://github.com/dtrent1/spyder/blob/d2278009d4a8aa5b58446fe7ae9153783e10243c/spyder/widgets/status.py#L248) by adding a check for the platform type to provide the proper environment name for the status bar update. Fixes #11007.
Fixes #11006
Fixes #11007
I …
=> PR: Correctly update Python interpreter on status bar when modified for Windows

spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/codeeditor.py
Paint Events are quite slow on my machine, which makes Spyder not really responsive. This improves the situation by avoiding a useless call to `select`, which is relatively slow.
Fixes #
=> PR: Implement a faster paint event for cells

spyder/plugins/editor/panels/scrollflag.py, spyder/plugins/editor/widgets/codeeditor.py
This makes the painting of the flags a lot more efficient.
However, I get the feeling that the scrollflag is getting updated way to often due to signals sent by the editor. So I think there is still room for improvements on the editor side.
Here is what made the most impacts on improving the performance of the scrollflag panel painting:
- Caching the `QColor` instead of generating them for every flag.
- Passing the `x, y, width, height` values directly to `QPainter.drawRect` instead of creating a `QRect`
- Caching the style pixel metrics instead of calculating them for every flag.
I think this Fixes #11000, but as I said, there is still room for improvement on the editor side. …
=> PR: Optimize editor scrollflag panel painting

spyder/plugins/editor/panels/scrollflag.py
Set the minimum height of the srollflag slider to the pixel metric set in the style for the scrollbar's slider.
Fixes #11050
=> PR: Set a minimum value for the scrollflag's slider height

spyder/plugins/editor/widgets/base.py
@ccordoba12 Ok, so the fix for this is pretty straightforward. I also fixed an issue where the position of the cursor was not preserved after duplicating or copying current line or selected text. I also would like to add a test since this feature doesn't seemed to be covered by one.
However, as you can see in the animation below, there is a glitch that is clearly noticeable when duplicating due to the fact that text selection gets automatically expanded when inserting text at the current position of the cursor. That, is not easy to fix...
After some efforts, I found a workaround that allow to avoid the glitch that I have implemented in my third commit. I don't like workarounds, but I haven't been able to find a better way. Maybe I've missed something... Anyway, feel free to reject this …
=> WIP: Fix copying or duplicating multiple selected lines

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
Handle `UnicodeEncodeError` while copying from a Dataframe in Python 2
Fixes #4833 
=> PR: Handle enconding error when copying dataframes in Python 2

spyder/api/plugins.py, spyder/plugins/base.py, spyder/plugins/editor/plugin.py
=> PR: Handle CompletionWidget position when undocking editor

spyder/dependencies.py
Keyring can't work in that situation because it requires system packages.
This error was reported in https://stackoverflow.com/q/59436107/438386
=> PR: Don't register keyring as a dependency on Linux and Python 2

spyder/config/main.py, spyder/config/manager.py, spyder/config/tests/test_manager.py, spyder/config/user.py, spyder/plugins/console/plugin.py
The previous code was mixing the contents of the old Spyder 3 ini file with the configuration of the plugin itself. This was what was causing the shortcuts conflict reported on issue #11132.
This PR removes all previous config files for external plugins and regenerates them again once when users start 4.0.1 for the first time.
Fixes #11132
=> PR: Fix creation of config files for external plugins

spyder/config/main.py, spyder/widgets/github/backend.py, spyder/widgets/github/gh_login.py, spyder/widgets/github/tests/test_github_backend.py, spyder/widgets/github/tests/test_github_login.py
That's going to be removed by Github in the future for external applications, so it's better for us to do it right now.
This is how things look now:
Fixes #11059.
=> PR: Remove password-based authentication from the Github login dialog

spyder/app/restart.py
Handle encoding to prevent an `UnicodeDecodeError` when restarting (in Python 2.7)
Fixes #11024
=> PR: Handle encoding when restarting Spyder to fix an error with Python 2.7

spyder/plugins/editor/widgets/editor.py
Handle error in the Editor when resuming from idle 
Fixes #11228 
=> PR: Handle error when disconnecting object info signal after idle

spyder/widgets/dock.py
Handle `AttributeError` when pressing dock tabs
Fixes #11226 
=> PR: Handle AttributeError when generating context menu on dockwidget tabs

spyder/utils/icon_manager.py
`get_icon_by_extension_or_type` is really slow for some files types. Here, I am caching the results to the calls.
Fixes #11247 (Makes things better)
=> PR: Cache call to get_icon_by_extension_or_type

requirements/tests.txt, spyder/plugins/completion/languageserver/tests/conftest.py, spyder/plugins/editor/extensions/snippets.py, spyder/plugins/editor/widgets/tests/conftest.py, spyder/plugins/editor/widgets/tests/test_introspection.py
Caused by trying to get a list of a node instead of the tokens of the node
Fixes #10971 
=> PR: Fix snippets completion with a single token with placeholder

spyder/plugins/completion/languageserver/client.py
=> PR: Remove "The send queue is full! Retrying..." when LSP is not initialised

spyder/plugins/editor/widgets/completion.py
When you enter one or more letters and then press _tab_ in the spyder editor, you get an autocompletion popup window. With this pull request the popup window doesn't close on pressing the _AltGr_ key anymore.
I've added a new variable (**altgr**) that will be true if the pressed key is _AltGr_. This variable is being checked in order to identify modifier keys.
I made this change because in my keyboard layout (and others like _Neo2_ and _Aus der Neo-Welt_) the down arrow can be sent with _AltGr_+_D_, so the popup window shouldn't be closed when _AltGr_ is pressed.
Fixes #11293 
and …
=> PR: Don't close autocompletion menu when AltGr is pressed

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_introspection.py
=> PR: Add escape key to completion ignore keys

spyder/plugins/editor/widgets/editor.py, spyder/widgets/calltip.py, spyder/widgets/mixins.py
=> PR: Fix tooltip position after the editor is undocked

spyder/plugins/ipythonconsole/widgets/shell.py
Use `os.path.normpath` to handle backward slashes instead of escaping them with `\\` to prevent errors while setting network folders as cwd on Windows
Fixes #10785 
=> PR: Use normpath to set network folders as cwd on Windows

spyder/app/mainwindow.py
Since the screen where Spyder is being displayed could change, the handle of signals to trigger the restart message for proper display needs to take the screen change into account.
Fixes #
=> PR: Handle screen change to trigger restart and prevent display issues

spyder/plugins/variableexplorer/plugin.py, spyder/plugins/variableexplorer/widgets/namespacebrowser.py
Properly register shortcuts for the `NamespaceBrowser` and `CollectionsEditor` widget of the Variable Explorer to update shortcuts without a restart:
~~- [ ] Copy (seems like it's being done using a `keyPressEvent`?)~~ The copy shortcut preference is only for the `ArrayEditor` and `DataframeEditor`
Fixes #10627 
=> PR: Properly register shortcuts for some actions of the Variable Explorer

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py
The request for the signature calltip was not being made when the inserted text was '('
Fixes #11417 
=> PR: Enable signature request without automatic bracket completion

spyder/app/mainwindow.py
When Spyder is invoked with `-p project`, this resolves `project` relative to the directory of invocation. IMO this is generally expected behaviour for running CLI tools. Currently it is interpreted relative to Spyder's working directory, which is generally my home directory.
E.g. if I am in `/home/akdor1154/src/python`, if I type `spyder -p folder1` or `spyder -p .`, I expect these to be interpreted as `/home/akdor1154/src/python/folder1` and `/home/akdor1154/src/python`, respectively. Currently they are interpreted as `/home/akdor1154/folder1` (surprising) and `/home/akdor1154` (really surprising).
N.B. existing behvaiour of `-p`, to create a project if it does not exist, is unchanged.
Fixes #11363 
I affirm the [Developer …
=> PR: Interpret -p project argument relative to the directory of invocation

spyder/utils/encoding.py, spyder/utils/tests/test_encoding.py
This PR keeps track of the original creation date for any file saved before executing an atomicwrite. If the file does not exist, then the current timestamp is assigned.
Fixes #11403
Fixes #
@andfoy
=> PR: Preserve creation time when performing an atomic_write

spyder/utils/encoding.py
This PR captures and ignores OSError exceptions raised when trying to change permissions/timestamp information for files located in Samba network endpoints.
Fixes #11308 
@andfoy
=> PR: Prevent operation not permitted errors when writing to samba shares

spyder/plugins/base.py
Keep a reference to the window being closed when redocking a widget to avoid a segfault.
Fixes #10704
=> PR: Avoid Python destroying Qt window and causing segfault

spyder/plugins/projects/utils/watcher.py
This PR prevents Spyder to complain about watchdog failling to update a network folder that is not longer available.
Fixes #11370 
@andfoy
=> PR: Add monkeypatch on watchdog's main dispatcher to prevent network failures

binder/environment.yml, requirements/conda.txt, setup.py
I noticed this while testing Spyder in Binder.
=> PR: Pin parso to 0.5.2 because version 0.6.0 is incompatible with Jedi 0.14

spyder/plugins/ipythonconsole/widgets/client.py
I think we should just remove the restart logic and create a new widget at some point to avoid these bugs.
Fixes #11477
=> PR: Fix errors when restarting the kernel while in debugging

spyder/plugins/editor/widgets/base.py
Doing some updates while handling the `wheelEvent` (scroll related event) in the Editor, stealed focus of widgets like the Find widget:
A preview:
Fixes #11502 
=> PR: Prevent editor stealing focus of other widgets while scrolling

spyder/plugins/explorer/plugin.py
Missing positional arg when calling `Run` action from an Explorer widget
Fixes #11532 
=> PR: Add console_namespace positional arg (set to False) when calling Run in an Explorer widget

spyder/plugins/editor/plugin.py, spyder/plugins/editor/tests/test_plugin.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/explorer/widgets/tests/test_explorer.py
This PR fixes a bug in the file explorer, which caused the explorer to always emit `sig_renamed_tree` after a rename, instead of emitting `sig_renamed` if a file is renamed and `sig_renamed_tree` if a directory is renamed.
This PR also fixes a second bug, which became more apparent after the first fix. Before, the editor plugin propagated all file renames to the autosave component, which leads to an error if the file is not opened. Now, only renames of open files are propagated.
Fixes #11348  …
=> PR: Handle file renamed in the explorer correctly in the editor

spyder/otherplugins.py
When 3rd party plugin load fails, we do not get much information on what happened, this add a call to logging to provide information when running with `--debug`
It will look like:
```bash
2020-02-12 17:50:03,187 [DEBUG] [spyder.otherplugins] -> plugin: 'spyder_autopep8' load failed with `cannot import name 'fixed_shortcut' from 'spyder.config.gui' (/Users/goanpeca/Dropbox (Personal)/develop/quansight/spyder/spyder/config/gui.py)`
```
=> PR: Add debug calls for 3rd party plugin loading

spyder/plugins/editor/widgets/base.py, spyder/widgets/mixins.py
This PR prevents errors when LSP completion returns entries that contain TextEdit objects.
Fixes #11526
@andfoy
=> PR: Handle TextEdit correctly when receiving completions

spyder/plugins/help/plugin.py
Enable all the actions when refreshing them for example when undocking:
Fixes #11591 
=> PR: Ensure Help pane actions are enabled after being undocked

conftest.py
This is a follow up of PR #11541 to implement the same fix for `conftests.py`.
Whithout this, running a test file locally results in the following traceback:
```python
ImportError while loading conftest 'C:\Users\User\spyder\conftest.py'.
..\..\..\..\..\conftest.py:27: in <module>
for path in os.listdir('external-deps'):
E   FileNotFoundError: [WinError 3] The system cannot find the path specified: 'external-deps'
```
=> PR: Fix running tests locally from file

spyder/plugins/editor/utils/autosave.py, spyder/plugins/editor/utils/tests/test_autosave.py
The autosave component stores information in pid files with filenames of the form `pidNNN.txt`. This PR ignored pid files whose contents cannot be parsed. The pid files will be deleted as normal.
A regression test is also included.
Fixes #11375 
=> PR: Handle corrupted pid files in autosave component

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/panels/tests/test_scrollflag.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/editor/widgets/tests/test_goto.py
I don't know why but some tests started to fail for no good reason a couple of days ago (the installed dependencies are exactly the same then and now). This just skips them.
=> PR: Skip some tests that are failing or timing out too much

spyder/plugins/editor/widgets/editor.py
Tab indexes could be invalid if, while trying to open a file, the current open file is removed/renamed outside Spyder.
Fixes #11464 
=> PR: Validation for tab indexes when refreshing the Editor

spyder/plugins/editor/utils/autosave.py, spyder/plugins/editor/utils/tests/test_autosave.py
Convert the autosave mapping to ASCII before saving in on disk, because saving Unicode filenames in a text file opened with the default encoding may raise an UnicodeEncodeError. Also add a regression test.
Fixes #11609
=> PR: Convert autosave mapping to ASCII before saving

spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/kite/providers/document.py, spyder/plugins/completion/kite/utils/tests/test_install.py, spyder/plugins/editor/widgets/editor.py
* Missing `:` to use the hover endpoint in Windows.
* Allow render of documentation without signature in the Help pane.
A preview:
Fixes #11579 
=> PR: Fix hover endpoint for Kite on Windows and allow docs without signature in Help

spyder/plugins/plots/widgets/figurebrowser.py
In the Plots pane, store the last directory used to save figures in CONF and retrieve and use it as the default directory when saving subsequent figures.
Fixes #10863
=> PR: Remember last saved path in Plots pane

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_introspection.py
This PR prevents triggering autocompletions when Tab/Backtab is pressed.
Fixes #11625
@andfoy
=> PR: Prevent Tab/Backtab from triggering completions

spyder/plugins/plots/widgets/figurebrowser.py
Make the default filenames generated when saving figures in the Plots pane date/time-based. 
Fixes #10864
=> PR: Date/time-based filename (when saving) figures in Plots pane

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_introspection.py
This PR fixes some regressions of autocompletion triggering behaviour, such as ignoring "dot" completions and preventing whitespace from triggering completions.
Fixes #
@andfoy
=> PR: Fix issues with autocompletion characters and prevent whitespace from triggering completions

spyder/utils/encoding.py, spyder/utils/tests/test_encoding.py
To properly handle saves of files using symlinks the path used for atomicwrites needs to be the real path of the file
Fixes #11718 
NOTE: Seems like using `realpath` only works on Windows with Python 3.8+: https://bugs.python.org/issue9949 so maybe `pathlib` is a better alternative (although for Python 2 `pathlib2` needs to be used)
=> PR: Use resolved path (without symlinks) to save files

spyder/config/main.py, spyder/plugins/editor/confpage.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py
This PR introduces a preference option to disable code folding. Additionally, a flag is introduced in order to notify users about code folding unavailability when large files (lines > 2000) are opened.
Fixes #
@andfoy
=> PR: Disable code folding when files are too long and add an option to disable code folding

spyder/plugins/editor/widgets/codeeditor.py, spyder/utils/syntaxhighlighters.py
This improves highlighting with Pygments and avoids using it for txt files.
This also reverts PR #11664 because it broke re-highlighting for files that use Pygments.
=> PR: Fix highlighting based on Pygments

spyder/plugins/editor/widgets/editor.py
Open the protected files in Windows by verifying if they have only read access, so they cannot be modified inside spyder and saved.
Fixes #10657 
=> PR: Fix saving protected files on Windows by checking if they are read-only

spyder/plugins/help/utils/sphinxify.py
Use as base dir, for temp sphinx build, one that is in the same drive than the Sphinx config
**Note:** Seems like the issue only happens with Sphinx 2.2.0. Testing with Sphinx 2.2.2, 2.3.1 and 2.4.0 the Help render works.
Fixes #11652 
=> PR: Use the same temp base dir for Sphinx config, src and build paths

spyder/plugins/ipythonconsole/utils/style.py
The entries were swapped, resulting in no highlighting for the current
entry when using 'terminal' style completion.
Fixes #11765
I certify the above statement is true and correct: keepiru
=> PR: Fix broken completions highlighting in the iPython console

spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/fallback/actor.py, spyder/plugins/completion/fallback/tests/test_fallback.py, spyder/plugins/completion/fallback/utils.py, spyder/plugins/completion/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/conftest.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/widgets/mixins.py
This PR does the following things:
* It sends the current word to be completed to the fallback plugin, so it can filter among all tokens those that start with that word.
* It avoids the waiting logic between Kite and the LSP when fallback is the only client available.
With these changes, now we can have nice fallback completions for any file, as shown below:
=> PR: Some improvements to fallback completions

continuous_integration/azure/install.sh, continuous_integration/travis/install.sh
jupyter_client 6 was incorrectly built as `noarch`, which installs it for Python 2 no matter what.
=> PR: Install the right version of jupyter_client for Python 2 in our CIs

CHANGELOG.md, azure-pipelines.yml, spyder/plugins/editor/widgets/tests/test_introspection.py
It seems Azure changed the way it handles conda envs in its images.
* First, this fixes an error when conda tries to save files in its pkgs directory.
* And second, this fixes `test_completions_environment` because now conda creates its envs in the expected place.
=> PR: Fix tests in Azure/macOS

spyder/plugins/editor/panels/scrollflag.py, spyder/plugins/editor/panels/tests/test_scrollflag.py, spyder/plugins/editor/widgets/recover.py, spyder/plugins/findinfiles/widgets.py, spyder/plugins/variableexplorer/widgets/arrayeditor.py, spyder/plugins/variableexplorer/widgets/basedialog.py, spyder/widgets/mixins.py, spyder/widgets/switcher.py
Some Qt functions expect `int` but get `float`. Implicit conversion results in a `Deprecation Warning`
which tripped a unit test. Fixed some more warnings on the way.
Fixes #11885 
=> PR: Fix deprecation warnings

spyder/app/mainwindow.py
Verify the screen mode before generating a warning pop-up of a monitor scale change when using spyder in the fullscreen mode.
Fixes #11846 
=> PR: Disable screen resolution change message in macOS and allow to hide it during the current session

spyder/plugins/editor/confpage.py
The configuration page for `Advanced settings` in the Editor plugin had an untranslated label.
I did not regenerate the strings yet, because I am not familiar with the workflow in and out of Crowdin. (see #11977)
German translation would be "Typ:"
=> PR: Make a string translatable

spyder/config/main.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_classfunc_selector.py, spyder/plugins/editor/widgets/tests/test_folding.py, spyder/plugins/editor/widgets/tests/test_warnings.py
Remove the case when the folding panel is not visible, this makes that the folding is available to all files and not the only the one that starts with Spyder.
Fixes #11869 
=> PR: Activate code folding when the panel is not visible

spyder/app/mainwindow.py
Catch the runtime error that happens after disconnecting monitors 
Fixes #11997 
=> PR: Catch RuntimeError to prevent errors when disconnecting monitors

spyder/plugins/editor/panels/scrollflag.py, spyder/plugins/editor/widgets/editor.py
#12026 seems to be caused by the usage of blocks. If a block is valid but all the next blocks are destroyed, `blockBoundingRect` creates a segmentation fault. The solution here is to get a new block iterator so the reference to the destroyed block is not used by `blockBoundingRect`.
This also simplifies the code and reduces the number of operations done while painting 
Fixes #12026
=> PR: Avoid segfault when painting flags after removing lines

spyder/utils/programs.py
* fix typo in list of Windows executable filename extensions
* add `.cmd` as alternative to `.bat` files
I certify the above statement is true and correct: @StefRe
=> PR: Fix typo in Windows executable filename extensions

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_completion.py, spyder/plugins/editor/widgets/tests/test_completions_hide.py
This pull request contains two commits:
* e1b39295a **corrects** a bug in #11732: now the completion widget is actually hidden when no completion is available.
* 5a51edc2b **modifies** the behavior to match these described in  https://github.com/spyder-ide/spyder/issues/11600#issuecomment-591374070. This is obviously a personal choice and I would understand if you prefer previous behavior.
* 0813477d6 **adds** a regression test for this PR.
Result can be seen (with only letter keys stroke):
I did not include new test since the one introduced by #11732 should be sufficient (even if it doesn't test everything).
Should fix better #11600
Correct #11732 …
=> PR: Correctly hide already complete word in completion widget

spyder/app/mainwindow.py
Fix and update links to PyQt5 docs
The link to the PyQt5 API Reference is dead; the link to the Reference Guide
gets redirected from sourceforge to riverbankscomputing, so I updated
it too to have it consistent.
I certify the above statement is true and correct: @StefRe
=> PR: Fix links to PyQt5 docs

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_completions_hide.py
Completion widget hiding for complete words failed when within a function or comprehension.
I didn't open any issue for this one.
@ElieGouzien
=> PR: Fix completion hiding when within function or comprehension.

spyder/plugins/profiler/widgets/profilergui.py
Remove the `size` parameter in TextEditor constructor call in the profiler to avoid crash.
Fixes #11875 
=> PR: Remove size parameter in TextEditor constructor call

spyder/app/mainwindow.py, spyder/plugins/base.py, spyder/widgets/dock.py
This simplifies a bit the logic moving fowrard with the new API
=> PR: Move dock attributes from plugin to dockwidget

spyder/app/mainwindow.py, spyder/preferences/shortcuts.py, spyder/preferences/tests/conftest.py, spyder/preferences/tests/test_shorcuts.py
We currently load shortcuts from the configuration. This means anything there will be loaded, even if it is a leftover from a shortcut name rename or similar.
This PR adds a check on the shortcut preferences so that we displayed shortcuts that ara registered on the main window. This way we display only valid active shortcuts. Additional to this we update the `apply_shortcuts` method so that actions without a shortcut in CONF can be successfully registered. With the new work on API migration we will expose many actions without shortcuts and leave it to the user to define them if they want to use them.
Also by using the `shortcut_data` info  from the main window, we can offer translations for shortcuts via those QActions and QShortcuts. (Work for a separate PR)
Fixes #12179
By submitting …
=> PR: Register actions without shortcuts and only display registered actions

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
Fixed the loading signal for datetime objects in Variable Explorer
Fixes #
Juanis2112
=> PR: Emit sig_editor_shown for objects that can be edited inline in the Variable Explorer

.gitignore, runtests.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py
* ~~[x] Added unit test(s) covering the changes (if testable)~~
* ~~[x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))~~
Fixes #11870.
Currently, passing any arg/option, such as ``--run-slow`` to ``runtests.py`` doesn't work, because if `test_mainwindow.py` is run, which imports `mainwindow.py`, Spyder's arg parser sees the args it doesn't recognize and causes the tests to fail during initial collection. While there is code that is supposed to handle this, it isn't executed nearly early enough to catch parser errors due to this. I didn't use the utility function to get whether we're running in a pytest env since it is only imported a number of lines after, so I didn't want to import it too early and cause latent bugs.
Furthermore, …
=> PR: Fix issues parsing runtests.py args and passing them properly to Spyder and Pytest

spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py, spyder/plugins/variableexplorer/widgets/objectexplorer/tests/test_objectexplorer.py, spyder/plugins/variableexplorer/widgets/objectexplorer/tree_model.py
=> PR: Remove restriction to populate object attributes in the Object Explorer

spyder/app/mainwindow.py
@CAM-Gerlach, could you quickly review this one? I don't understand very well why you decided to pass `sys.argv` to `get_options` when not running our tests.
Fixes #12313
=> PR: Don't pass sys.argv to get_options if not running tests

spyder/plugins/editor/widgets/codeeditor.py
Does not fix the original issue where for ex. a `if` statement is immediately followed by a `else` statement (not valid Python)
To fix the original issue, `if ind(leading_text) == ind(prevtxt.rstrip()) and not prevtxt[-1] == ':':` works but is unnecessary in my opinion
Fixes #10148
I certify the above statement is true and correct: remisalmon
=> PR: Correctly unindent code for valid Python

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
If the max and min values of a column are the same, using the difference to get the color can cause a `ZeroDivisionError` or the hue value to be `nan`
Fixes #11790 
=> PR: Validate column max/min difference (Variable Explorer)

spyder/plugins/variableexplorer/widgets/dataframeeditor.py, spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py
=> PR: Use def instead of lambda to define slots for data conversion (Variable Explorer)

spyder/utils/tests/test_vcs.py
That test started to fail after PR #12298.
=> PR: Make test_get_git_refs work when merging against 4.x

spyder/plugins/completion/kite/client.py
When using a VPN, requests to Kite can end up being unable to convert to json and passing as str to the handler methods like `get_language` or `get_status`
Fixes #12410 
=> PR: Add support for a str response when getting Kite available languages

spyder/app/mainwindow.py, spyder/widgets/dock.py
This messages kept appearing on undocking panes. Seems like a Qt issue but this seems to fix it,
I think this also fixed the issue of being able relocate a pane from a tiny pixel region even when the lock panes option was enabled.
Fixes #
=> PR: Remove warning message when undocking panes

spyder/plugins/editor/plugin.py
Seems like there is a possibility to try to load files without having a current line number from the layout settings previously stored.
Fixes #12201 
=> PR: Add validation for current line values when loading files (Editor)

spyder/plugins/editor/plugin.py, spyder/plugins/editor/tests/conftest.py, spyder/plugins/editor/tests/test_plugin.py
Change the counter to start in the following number after the open `untitled` file. This check is done only when creating the first default name file.
Fixes #7831
=> PR: Fix inconsistent behavior when creating/saving files with default names

spyder/plugins/editor/utils/autosave.py, spyder/plugins/editor/utils/tests/test_autosave.py
This is similar to PR #11647 which handled KeyErrors when deciding whether to autosave. As explained there, the immediate reason is that the hash of the file currently considered is not stored in the autosave component, but I do not know why not. If a file whose hash is not recorded, is renamed, then when handling this rename a KeyError will be raised in a different function. This PR catches and handles the KeyError when handling file renames.
I had a look and I don't think there are other places where we can get a KeyError, but given that I don't understand the root cause I am not certain of this.
Fixes #12396 …
=> PR: Handle KeyError when processing rename in autosave

spyder/plugins/editor/widgets/codeeditor.py
Remove check of `_last_pressed_text` and length of current text to trigger `document_did_change` and do completions on the fly.
Fixes #12417
I certify the above statement is true and correct:Steff456
=> PR: Fix unstable completions when using backspace

spyder/plugins/completion/kite/utils/status.py
To check that Kite is running we iterate over all the available process and check if any of them refers to Kite. The case where the operation to retrieve the processes information fails wasn't being handled.
Fixes #12510 
=> PR: Handle error when checking if Kite is already running

spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/tests/test_plots_widgets.py
It seems `thumbnail.setParent(None)` was causing the problem.
Fixes #12459
=> PR: Fix segfault on Unix systems when removing plots

.gitignore, bootstrap.py
* Ignore setuptools development files in the PyLS subrepo.
*   Improve the way we detect if there's an stable version of the PyLS we need to remove in `boostrap.py` (the previous method was failing, which made `boostrap.py` to take longer to start).
=> PR: A couple of fixes for the python-language-server subrepo

.github/scripts/install.sh
* This solves the errors we were seeing in our tests for the last couple of days.
* A real fix needs to be provided by the Anaconda team, by declaring the right dependencies for 2.5.0.
=> PR: Install Pylint 2.4 in our CIs

.github/workflows/test-linux.yml, .github/workflows/test-mac.yml, setup.cfg
Our tests started to fail due to this a couple of hours ago.
=> PR: Update check-manifest ignore rules to work with its 0.42 version

spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py, spyder/widgets/calltip.py
This should fix:
* `spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py::test_automatic_column_width`, which started to fail intermittently on Linux and Python 2.
* `spyder/plugins/editor/widgets/tests/test_completions_hide.py::test_automatic_completions_hide_complete`, which fails sometimes during teardown on macOS and Python 3.
=> PR: Fix a couple of failing tests 

spyder/widgets/tabs.py
Add offset to remain the region of tab given an event and be able to close intended tab
Fixes #12558 
=> PR: Make middle mouse button click on editor tabs close the intended tab

spyder/preferences/maininterpreter.py
This is very useful for testing but we were failing to register it correctly.
=> PR: Allow the default interpreter to be selected as a custom one in our Preferences

spyder/widgets/comboboxes.py
* Remove the need to press `Tab` twice to get completions when there are several completions available. I forgot this was added several years ago and found it very confusing.
* Style the completer's popup. No one noticed it was not following the dark theme.
* Don't remove valid directory names when pressing `Enter` after selecting them. This was really confusing because the completer offered several directories but then pressing `Enter` in any of their names remove it from the combobox.
* Add file completions. The combobox was only showing directories.
----
**Before**:
**After**:
=> PR: Improve completions provided by FileComboBox

spyder/plugins/completion/languageserver/client.py
This finally fixes the "linter is dead" problem reported a lot during the last couple of months!
By changing the server's stdout to None on Windows, our client is now able to process errors correctly (e.g. errors that come from Jedi, which are the most frequent).
Before this, the client was unable to process any message coming from the server after the error. So not only the linter, but also folding and symbols totally died.
Fixes #11506.
=> PR: Set LSP server stdout to None on Windows

spyder/plugins/editor/widgets/status.py
Noticed one of 'summary descriptions' had a tooltip missing, figured it's worth adding; if additional code / tests needed for this, can close this PR or complete without me as I have no knowledge on IDEs.
=> PR: Add tool tip to EOLStatus

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_completions_hide.py
Add counter to backspace and check if the text is not empty before showing the completions widget.
Fixes #12704 
=> PR: Fix showing/hiding completions when backspace is pressed

spyder/plugins/editor/utils/autosave.py, spyder/plugins/editor/utils/tests/test_autosave.py, spyder/plugins/editor/widgets/tests/test_editor.py
This PR ensures that if a file is autosaved, the name of the autosave file does not coincide with the name of an existing file. Currently, if the user opens an autosave file in the editor (for instance, from the recovery dialog which Spyder displays at startup when finding autosave file) and then makes changes to the file, Spyder makes an autosave file with exactly the same name, which eventually leads to an error. This fixes that error.
Fixes #12755
=> PR: Ensure autosave files don't overwrite existing files

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/tests.txt, external-deps/spyder-kernels/setup.py, external-deps/spyder-kernels/spyder_kernels/console/__main__.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
This is due to a change in Python 3.7, which added the current working directory to `sys.path` when running modules with `python -m`. And that's is precisely the way we start our kernels.
Depends on spyder-ide/spyder-kernels#222
=> PR: Test that a file with the same name of a standard library module doesn't break the console

spyder/plugins/projects/plugin.py, spyder/plugins/projects/tests/test_plugin.py
Previously new/open/close/delete project called `.switch_to_plugin()` and this latter function was overridden so that the plugin is only shown if the `visible_if_project_open config` option is set. This override broke the Ctrl+Shift+P shortcut (issue #12491).
This commit replaces the `.switch_to_plugin()` override by a new `.unmaximize()` function and calls this on new/open/close/delete. As far as I can see, the unmaximize functionality is the only part of `.switch_to_plugin()` that is actually used on new/open/close/delete, because the new/open/close/delete functions have code later to show or hide the Project plugin.
Fixes #12491
with respect to …
=> PR: Unmaximize on new/open/close/delete project

spyder/plugins/completion/languageserver/client.py
This avoids the server to pick up user files such as `random.py` or `string.py` instead of the standard library modules named the same.
Note: I tried to remove the cwd on `pyls/__main__.py` but it was not so simple as this because that file is kind of complex.
=> PR: Set the Python language server current working directory to an empty dir

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_completions_hide.py
Dear spyder devs,
Using the fix brought by #12710, I realized it was not working as expected when not at the beginning of a line (or when end of previous line is a word).
Here is a proposition to fix those issues with #12637. 
Main idea is to also check for previous character, since "previous word" from qt behaves strangely.
@ElieGouzien
=> PR: Fix hiding completion on backspace when nothing before cursor

spyder/api/plugins.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/config/tests/test_manager.py, spyder/plugins/console/api.py, spyder/plugins/console/plugin.py, spyder/plugins/console/tests/test_plugin.py, spyder/plugins/console/widgets/console.py, spyder/plugins/console/widgets/internalshell.py, spyder/plugins/console/widgets/main_widget.py, spyder/plugins/console/widgets/shell.py, spyder/plugins/editor/plugin.py, spyder/plugins/help/plugin.py, spyder/plugins/history/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/workingdirectory/plugin.py, spyder/widgets/mixins.py
Fixes #12727
Depends on https://github.com/spyder-ide/spyder/pull/11741
=> PR: Migrate Console Plugin to the new API

spyder/plugins/completion/languageserver/__init__.py, spyder/plugins/completion/languageserver/client.py, spyder/plugins/completion/languageserver/plugin.py
* This will allow us to have better control over those external processes. Specifically, Qt emits signals when they fail to start and when they crash, so we only need to connect to those signals and run our restart mechanism.
* In particular, this fixes the infinite restarting-ready-starting sequence we have right now when the PyLS fails to start. That happens because `subprocess` doesn't have an option to check if the process started correctly (calling `poll` works if we wait a little bit for the process to start, but that little bit depends on the OS and user hardware).
* Finally, this has some refactoring of the `LSPClient` code to make it more readable and easier to follow.
Fixes #12225.
TODO:
=> PR: Use QProcess instead of subprocess for the LPS transport layer and server

.github/scripts/install.sh, CONTRIBUTING.md, binder/environment.yml, requirements/conda.txt, setup.py, spyder/dependencies.py, spyder/plugins/projects/utils/cookie.py, spyder/plugins/projects/utils/tests/__init__.py, spyder/plugins/projects/utils/tests/test_cookie.py, spyder/plugins/projects/widgets/qcookiecutter.py, spyder/plugins/projects/widgets/tests/test_qcookiecutter.py, spyder/plugins/pylint/tests/test_pylint_config_dialog.py
Add a generic cookiecutter parser so we can generate a UI on the fly with the correct widgets. This work will be used to enable cookicutter projects of different types:
- Data science
- Python Package
- Spyder Plugin. (Example in image)
Fixes #12938
=> PR: Add cookiecutter widget

spyder/widgets/colors.py
Set a minimum width for the color names in the edit appearance panel so the widget will show the complete name.
Fixes #12562 
=> PR: Add minimum width for the color names in the edit appearance panel

spyder/plugins/completion/fallback/utils.py
This PR prevents spurious IndexError when computing the prefix for a fallback completion. As we don't have a clear, reproducible case of the error, we return false as prefix and prevent completions on cases where the error would appear
Fixes #12266
=> PR: Check when prefix size is less than zero or longer than the string size (Fallback completions)

spyder/plugins/editor/panels/codefolding.py, spyder/plugins/editor/widgets/codeeditor.py
This PR disables folding guides visibility by default, instead, they will be shown only if the cursor enters the left panel and disabled when the cursor leaves it. We also re-enable the folding support for large files that was disabled previously. 
Fixes #12315.
=> PR: Enable/disable folding guides when cursor enters/exits the left panel

spyder/plugins/editor/plugin.py
Catch the error an initialize the `untitled_num` variable in 0
Fixes #12892 
=> PR: Fix ValueError when an untitled file is open in the editor

spyder/plugins/explorer/widgets/explorer.py
Add an empty element to the filenames in case there's not any filename selected in the files explorer. In this way, the context menu will be visible in Windows.
Fixes #13004 
=> PR: Show the context menu with disabled options in the file explorer when it is empty

spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py
If a shortcut conflict is detected, and the user decides to do an overwrite of a shortcut, the old action needs to unset the shortcut to prevent having two actions with the same shortcut.
Fixes #12992 
=> PR: Clear old set shortcuts if they are now empty (Shortcuts)

spyder/plugins/profiler/tests/test_profiler.py, spyder/plugins/profiler/widgets/profilergui.py
Changed time units in profiler to match International Systems of Units. "sec was changed to "s" and "us" was changed to μ
Fixes #13059 
Juanis2112
=> PR: Change time units in Profiler to match the International System of Units

spyder/plugins/editor/panels/scrollflag.py, spyder/plugins/editor/panels/tests/test_scrollflag.py, spyder/plugins/editor/widgets/codeeditor.py
Expand the width of the scrollflag object if macOS so the scrollbar doesn't place on the minimap. The fix works for light and dark themes,
An important note for the light theme is that the user needs to have the scrollbars always present in their system. That can be modified by `System preferences>General>Show scrollbar>Always`. If this option is not checked, both the scrollbar and scrollflag will hide given the position of the mouse or trackpad.
Fixes #12637  …
=> PR: Show the scrollflag in macOS

.github/workflows/test-linux.yml, spyder/plugins/completion/fallback/actor.py, spyder/plugins/completion/kite/client.py, spyder/plugins/completion/languageserver/client.py, spyder/plugins/completion/languageserver/providers/document.py, spyder/plugins/console/widgets/shell.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/tests/conftest.py, spyder/plugins/editor/tests/test_plugin.py, spyder/plugins/editor/utils/editor.py, spyder/plugins/editor/widgets/base.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_editorsplitter.py, spyder/plugins/editor/widgets/tests/test_save.py, spyder/widgets/findreplace.py, spyder/widgets/mixins.py
* Try to detect all places where we need to call or stop calling `document_did_change`. That's very important because:
* Not calling `document_did_change` leads to completion, linting and folding not being updated correctly.
* Calling it in excess leads to numerous requests to the language server, which consumes a lot of CPU. For instance, this was done when pressing *any* key in the editor, without checking if the key really introduced text on it or not.
* Call `notify_close` and `document_did_open` when doing "Save as" and "Save copy as".
* Correctly set highlighting and language when renaming files to another language.
* Don't call `notify_close` nor `document_did_open` for cloned editors when it's not necessary.
* Make uniform logging messages for …
=> PR: Make an in-depth audit of different LSP calls

spyder/app/tests/test_mainwindow.py, spyder/plugins/history/widgets.py
This problem was introduced in PR #13085.
=> PR: Fix rename of CodeEditor kwarg (History)

spyder/plugins/help/utils/tutorial.rst
So we can have that change for 4.1.4, because (unfortunately) there was no way to move that PR to 4.x.
=> PR: Backport PR 13122

spyder/plugins/projects/plugin.py, spyder/plugins/projects/tests/test_plugin.py
- This can happen either when you have an open project and (i) Change to another, existing project; or (ii) Create a new project.
- It's important to emit that signal to let language servers know that the previous open project needs to be removed from the list of workspaces.
- This won't be necessary once we support multiple workspaces in the interface, but for now I think it is.
=> PR: Emit sig_project_closed when switching projects 

spyder/plugins/completion/languageserver/tests/test_lsp_config_dialog.py, spyder/preferences/tests/conftest.py
This was due to a mismatch between 4.x and master introduced by PR #13146.
=> PR: Fix test_lsp_config_dialog

spyder/api/widgets/__init__.py, spyder/api/widgets/auxiliary_widgets.py, spyder/app/mainwindow.py, spyder/plugins/onlinehelp/tests/test_pydocgui.py, spyder/plugins/onlinehelp/widgets.py
This PR correctly addresses some issues with plugins on startup and on close. With this PR online server is never started unless the plugin was open on shutdown. This includes the first startup as well.
Fixes #13142
Fixes #13127
=> PR: Fix visible plugins on restart and online server start

spyder/plugins/explorer/widgets/explorer.py
Right clicking on any item in the Project explorer tree causes Spyder to segfault. This issue was introduced in PR #13032.
The problem was caused by trying to access data from the source model of the project explorer tree view using indexes from its proxy model.
Supersede PR #13216
=> PR: Fix segfault when right-clicking any entry in the project explorer (2)

spyder/app/tests/test_mainwindow.py, spyder/preferences/configdialog.py, spyder/preferences/maininterpreter.py, spyder/widgets/comboboxes.py
* Validate a custom interpreter when trying to apply our Preferences. That prevents saving a wrong interpreter to our config file and also forces users to select a valid interpreter if they want to apply their changes. Before, the validation was done after our preferences were applied, which lead to several odd situations.
* Call `main.apply_statusbar_settings` Instead of `main.apply_settings` after applying our preferences because the first one is much less expensive than the second. That prevents a very long pause when changing interpreters.
* Remove wrong interpreters introduced in the custom line edit after applying our preferences. That (again) prevents saving a wrong interpreter in our config file.
* Update the custom interpreters combobox as soon as a …
=> PR: Validate Python interpreter when applying options (Main interpreter)

binder/apt.txt
This is to make Spyder look better on Binder.
=> PR: Add fonts-ubuntu to the list of deb packages installed on Binder

spyder/plugins/editor/panels/codefolding.py
Add a couple of try excepts wraping `_highlight_block` that raise a KeyError when folding regions
Fixes #13230 
=> PR: Catch KeyError in codefolding when folding regions

spyder/api/plugins.py, spyder/app/mainwindow.py, spyder/plugins/findinfiles/api.py, spyder/plugins/findinfiles/plugin.py, spyder/plugins/findinfiles/tests/test_plugin.py, spyder/plugins/findinfiles/tests/test_widgets.py, spyder/plugins/findinfiles/widgets.py
=> PR: Migrate Find in files plugin to new API

spyder/plugins/projects/plugin.py, spyder/plugins/projects/tests/test_plugin.py, spyder/plugins/projects/widgets/projectdialog.py
=> PR: Fix project logic to allow for extra dialogs

spyder/plugins/projects/api.py, spyder/plugins/projects/plugin.py, spyder/plugins/projects/widgets/projectdialog.py, spyder/plugins/projects/widgets/tests/test_projectdialog.py
- Now the project type methods (create/open/close) return a bool and a message in case of issues and a MessageBox is displayed
- The project type now only has access to the parent plugin via the `self.plugin` attribute
- The project type now provides a (optional) static method for validating project names. The result of this validation is displayed on the bottom of the create project dialog.
=> PR: Add name validation and status of project methods

spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/tests/test_plots_widgets.py
I simply updated the following code in the function `get_unique_figname` to get it to start numbering at zero. My only concern is that it affects the functionality to save only one plot, because now that only file will have (0) appended. If this is an issue, I could rewrite it by adding a parameter `start_at_zero` to the function in order to make it work differently when saving only one and when saving multiple.
```python
i = 0
figname = '{} ({}){}'.format(root, i, ext)
```
Fixes #13254 …
=> PR: Fix for consistent numbering when saving multiple plots

spyder/plugins/findinfiles/plugin.py, spyder/plugins/findinfiles/widgets.py, spyder/plugins/pylint/plugin.py
* Remove the Search and Stop button tooltips in Find. Those don't say anything important.
* Make the "Max number of results" input dialog non-modal in Find.
* Make the "History" dialog in Code Analysis also non-modal (at @CAM-Gerlach's suggestion).
=> PR: Fix some issues with the Find and Code Analysis panes

.github/workflows/binder-badge.yaml, .github/workflows/chatops-binder.yaml
This way we could launch a Binder instance on every PR, which will make far more easier to test other people's PRs directly on the browser.
For previous PRs, a member of our organization can make a comment with the `/binder` text on it and a comment will be added with the right badge.
*Notes*:
* I'm still unsure if this works because first I need to add the new actions, but I'm adding them through a PR so other people know about this new functionality.
* In case others want to know more about this, I got the idea from the [Binder docs](https://mybinder.readthedocs.io/en/latest/howto/gh-actions-badges.html).
=> PR: Add Github actions to display a Binder badge in our PRs

spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py, spyder/widgets/tests/test_shortcutssummary.py
=> PR: Fix some failing tests

setup.py, spyder/app/solver.py, spyder/plugins/breakpoints/__init__.py, spyder/plugins/console/__init__.py, spyder/plugins/findinfiles/__init__.py, spyder/plugins/help/__init__.py, spyder/plugins/history/__init__.py, spyder/plugins/onlinehelp/__init__.py, spyder/plugins/plots/__init__.py, spyder/plugins/profiler/__init__.py, spyder/plugins/pylint/__init__.py, spyder/plugins/workingdirectory/__init__.py
- This PR correctly finds internal plugins by checking in the `spyder.plugins` folder for installs running outside the normal spyder tests environment. This is needed to run Spyder with other plugins like the [ATE one](https://github.com/Semi-ATE/Semi-ATE/pull/10)
- PLUGIN_CLASS is replaced with PLUGIN_CLASSES as one plugin folder could potentially expose more than 1 plugin. Now that entry points are the way to expose plugins, this PLUGIN_CLASS is no longer needed for external plugins. …
=> PR: Find internal plugins in plugin module for Spyder installs

spyder/api/widgets/mixins.py, spyder/api/widgets/toolbars.py, spyder/plugins/findinfiles/plugin.py
=> PR: Add option to disable tooltip on toolbars when creating actions

spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/plugin.py, spyder/plugins/profiler/plugin.py, spyder/plugins/run/__init__.py, spyder/plugins/run/confpage.py, spyder/plugins/run/plugin.py, spyder/plugins/run/widgets.py, spyder/preferences/tests/conftest.py
=> PR: Migrate RunConfig to Plugin with new API

spyder/plugins/profiler/widgets/profilergui.py
The regex expression in the times parser had the old characters so replacing u by μ and sec by s fixed the issue. 
Fixes #13363 
Juanis2112
=> PR: Fix sorting of files in profiler by fixing parser

.github/workflows/chatops-binder.yaml
- This will avoid rebuilding the images on every commit here, hence greatly decreasing the time to start an instance on the cloud.
- Instead, those images now contain nbgitpuller, so we can add the content of this repo (or others in our org in the future) to them.
- The only difference with the previous approach is that now comments need to contain "/show binder" to display a Binder badge.
=> PR: Use Binder images from our binder-environments repo

spyder/plugins/projects/plugin.py
=> PR: Fix parent of project type

spyder/plugins/explorer/widgets/explorer.py
Add support for adding new files/folders/etc in the selected directory on the explorer tree
Fixes #13444 
=> PR: Explorer "New" actions now depend on selected files

spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py
=> PR: Fix missing Run section on Preferences

spyder/plugins/help/widgets.py
The browser widget was missing a call to the `setup()` method. 
Fixes #13422
=> PR: Fix error when showing context menu on Help plugin

spyder/app/mainwindow.py, spyder/widgets/about.py, spyder/widgets/dependencies.py
I changed spyder about and dependencies dialogs to non-modal
Fixes #
=> PR: Change About and Dependencies dialogs to non-modal

spyder/__init__.py
Fixes thsi problem:
```
In [1]: import spyder
In [2]: dir(spyder)
File "<ipython-input-2-d9a631b9c2b0>", line 1, in <module>
dir(spyder)
TypeError: 'str' object is not callable
```
Fixes #
=> PR: Fix using dir in the spyder module

spyder/plugins/editor/widgets/codeeditor.py
This PR prevents errors when a client returns a list response instead of a string when calling hover
Fixes https://github.com/spyder-ide/spyder/issues/13297
=> PR: Prevent raising an exception when a hover request returns a list

spyder/plugins/variableexplorer/widgets/collectionseditor.py, spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py
as I'm getting merge conflicts when rebasing to 4.x in #13548  I've simply created a new PR. Hope that's okay.
#########
As suggested in  https://github.com/spyder-ide/spyder/issues/13481#event-3658990833 I've implemented natural/human sorting for the keys. This means that numbers within strings are sorted correctly as well, e.g. test3 comes before test10, which with standard sorting would not be the case (as it just compares per character). However, this is now only implemented for dictionaries that are opened in the collections editor. It could also be easily added to the main sorting mechanism of the variable explorer I guess? Should that be given a try?
I had to do a workaround so that non-strings and mixed types are not sorted. Else the other tests would fail and I didnt want to …
=> PR: Add natural sorting for dicts (Variable Explorer)

spyder/plugins/appearance/confpage.py, spyder/plugins/appearance/plugin.py, spyder/plugins/help/widgets.py, spyder/plugins/history/plugin.py, spyder/plugins/history/tests/test_plugin.py, spyder/plugins/history/widgets.py, spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py, spyder/utils/syntaxhighlighters.py, spyder/widgets/reporterror.py, spyder/widgets/simplecodeeditor.py
This is a preliminary step in the migration of the Editor Plugin to the new API. 
The CodeEditor is a very complex widget and has been used by many other plugins for providing a code editor, where the only basic need seems to have syntax highlighting capabilities at most.
Currently, the following widgets use the CodeEditor
Object Editor (For python highlight)
For python highlight
For the plain text view (For python highlight)
For the Syntax Highlighter preview (For python highlight)
For markdown highlight. This one uses more of the editor cursor and selection capabilities, but only a handful.
As an initial attempt to really decouple the different plugins the simplest way (by far) is to provide a simple code editor with the needed capabilities in the `spyder.widgets` module. This boils …
=> PR: Create a simple code editor and use that for other plugins

spyder/plugins/projects/plugin.py
Prevent using an empty path to notify a project was open.
Note: I'm unsure why that was the first thing that was done since a validation of the path is already being done in the method.
Fixes #13346 
=> PR: Verify path before notifying project was open

spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/main_widget.py
@dalthviz added the fixes for the different reported issues.
Fixes #13659
=> PR: Fix several issues with the plots pane from API migration

spyder/api/plugins.py, spyder/api/widgets/__init__.py, spyder/api/widgets/auxiliary_widgets.py, spyder/api/widgets/toolbars.py, spyder/app/mainwindow.py, spyder/plugins/findinfiles/widgets.py, spyder/plugins/help/widgets.py, spyder/plugins/onlinehelp/widgets.py, spyder/plugins/profiler/widgets/main_widget.py, spyder/widgets/comboboxes.py, spyder/widgets/tabs.py, spyder/widgets/waitingspinner.py
- The code was simplified so instead of using a QMainWindow and QToolBars added to the ToolBar Areas, we use a QWidget and QToolBars added to QBoxLayouts. This way we have full control of the location, and stretches which fix the issue.
- The API itself remained unchanged, the changes were internal to the `PluginMainWidget`.
- This is how Help and Find in Files look (which also had the similar issue found in Pylint)
- Included an extra fix on the find in files button, to make it have the same size, regardless of Search/Stop text.
- The spinner widget is "permanently visible"  so that it takes width and there are no jumps when it starts spinning (and is actually displayed).
- Added a fix for find in files to keep the search combobox and exclude combobox the same size.
By submitting this …
=> PR:  Refactor the toolbar handling on main widgets

spyder/plugins/variableexplorer/widgets/collectionseditor.py
Added option **insert above/bellow** in variable explorer(to add new line when editing a list for example) as there was only the option **insert**, and the native behavior was to insert above. So to add new line in the end of a list, you had to duplicate that line and edit it(which is not very intuitive). 
Fixes #13371 
dpturibio/Diego Prosperi Turibio
=> PR: Add option to insert elements above/below in lists (Variable Explorer)

.github/scripts/install.sh, bootstrap.py, conftest.py, spyder/plugins/completion/languageserver/client.py
* This uses the PyLS subrepo to run our tests, which was missing from PR #13621.
* This also fixes starting Spyder from `bootstrap.py` on Windows after PR #13621.
=> PR: Fix some issues with the PyLS subrepo

spyder/api/widgets/__init__.py, spyder/api/widgets/mixins.py, spyder/plugins/console/widgets/main_widget.py
I think the [Apple HIC guidelines](https://developer.apple.com/design/human-interface-guidelines/) do not recommend having Icons in SubMenus (they generally also advise against having submenus). So that is why this PR needs to override the default  settings Qt uses for Mac with:
`internal_settings_menu.menuAction().setIconVisibleInMenu(True)`
Fixes #13683
=> PR: Restore submenu icon on internal console settings

spyder/plugins/ipythonconsole/widgets/debugging.py
=> PR: Correctly import IPythonInputSplitter for IPython < 7.0

.github/scripts/install.sh
This is until a new version of python-language-server is released.
=> PR: Pin python-jsonrpc-server to a working version in our CIs (for now)

spyder/plugins/explorer/widgets/explorer.py
This PR fixes an error that prevented creating a new folder in project explorer. The cause of the problem was the wrong form of the path generated by the script that looked like this:
`OS (C:)\\Users\\Admin\\test_project\\some_module`
This form caused `os.mkdir()` throws an error. 
Now, corrected script produces valid paths like this: `C:\\Users\\Admin\\test_project\\some_module`
Fixes #13722
=> PR: Fix create folder in Projects

spyder/plugins/help/plugin.py, spyder/plugins/help/utils/static/dark_css/default.css, spyder/plugins/help/utils/templates/usage.html
=> PR: Fixes to Help plugin according to UX review

.github/scripts/install.sh, CONTRIBUTING.md
- This is to avoid mixing dependencies with `defaults` (and it's done like this already in master).
- I preferred to change the label to `dev` (instead of `alpha`, as in `master`) to not tie the new dependencies we've decided to add to a specific release name.
- This also pins `ujson` to a version that works with our PyLS subrepo.
=> PR: Update contributing guide to install main dependencies from the dev label in our channel

spyder/app/mainwindow.py
Call QGuiApplication.setDesktopFileName to fix generic icon on GNOME/Wayland
See #13786 for screenshots of the icon bug this fixes and for links to further details on the underlying issue.
This PR adds a call to [QGuiApplication.setDesktopFileName](https://www.riverbankcomputing.com/static/Docs/PyQt5/api/qtgui/qguiapplication.html?highlight=setdesktopfilename#setDesktopFileName), which ensures the correct icon is displayed for the running application on GNOME/Wayland (#13786). Manual testing showed that this change resolved the issue.
Fixes #13786
and understand I am releasing the same …
=> PR: Call QGuiApplication.setDesktopFileName to fix generic icon on GNOME/Wayland

spyder/plugins/completion/languageserver/__init__.py
This was introduced in PR #13109 but it's not necessary because it was already among the LSP constants.
=> PR: Remove repeated SymbolKind enum

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/utils/nsview.py, spyder/plugins/variableexplorer/widgets/collectionseditor.py, spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py
related: https://github.com/spyder-ide/spyder-kernels/pull/246
I've re-implemented the natural sorting, now it should also work when sorting for types, etc.
Fixes #13733 
skjerns
=> PR: Restore sorting of types and natural sorting

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
`test_console_complete` fails with recent versions because the completion widget expects a press of Enter instead of Tab and thus never completes the desired line:
```
[   39s] python3-qtconsole-4.7.7-1.1           ########################################
[   39s] jupyter-qtconsole-4.7.7-1.1           ########################################
...
[   59s] ============================= test session starts ==============================
[   59s] platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
[   59s] cachedir: .pytest_cache
[   59s] PyQt5 5.15.0 -- Qt runtime 5.15.1 -- Qt compiled 5.15.1
[   59s] rootdir: /home/abuild/rpmbuild/BUILD/spyder-4.1.5, configfile: pytest.ini
[   59s] plugins: lazy-fixture-0.6.3, mock-3.1.1, flaky-3.7.0, xvfb-2.0.0, …
```
=> PR: Press enter on completion test

spyder/app/mainwindow.py
Makes the tooltip of the PYTHONPATH manager toolbar button match the title of the dialog it opens.
Fixes #13741 
juanitagomezr
=> PR: Change tooltip of PYTHONPATH manager to match title in dialog

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py, spyder/plugins/variableexplorer/widgets/tests/test_collectioneditor.py
Only try to get value.time() if the value is a date object
Fixes #13557 
=> PR: Make date objects editable in the object explorer

.github/scripts/install.sh, spyder/utils/tests/test_icons.py
Use QtAwesome master for tests. Add test for the mapping of icons 
Related to #13858 
Related to #13875
=> PR: Test icons for naming changes in QtAwesome

.github/workflows/duplicates.yml
This update a couple of duplicate messages because those errors are already solved in 4.1.5.
=> PR: Update duplicate messages after the release of 4.1.5

MAINTENANCE.md
I forgot to add this instruction on PR #13871. I just remembered about it after merging #13902.
=> PR: Add missing instruction to Maintenance guide

spyder/app/mainwindow.py
- Disabled toolbar fullscreen action for macOS because is redundant with the OS fullscreen
- Changed tooltip to explain why it is disabled
Fixes spyder-ide/ux-improvements#5
Juanis2112
=> PR: Disable toolbar fullscreen button for macOS

spyder/utils/encoding.py
I have added a workaround/fix that atomicwrites left a trail of tempfiles behind when the a script was saved in a dropbox-folder. I found no way of testing this easily, so there is no test. As discussed, it will only do so when 'dropbox' is in the filepath
Fixes #13041
skjerns
=> PR: Avoid atomic writes leaving trail of temporary files in Dropbox directories

spyder/app/tests/test_mainwindow.py, spyder/plugins/projects/plugin.py
* Fix `EmptyProject` import in `test_mainwindow.py`
* Remove `notify_project_open` from `open_project` function.
Fixes #13947 
Related with merge of #13828 
=> PR: Fix EmptyProject test fixture. Remove notify_project_open call

spyder/plugins/editor/panels/indentationguides.py
Now we only paint those guides present in the visible region or that cross it. With that I was able to avoid the sluggishness observed when scrolling and typing in the editor for large files, specially on Windows.
A simple way to reproduce that slugishness is to open one of our largest files (mainwindow.py or codeeditor.py), activate "Show indent guides" in the Source menu and:
* Scroll by holding down the up/down arrow keys in the file (you'll see the current highlighted line stays at a specific place instead of moving with the cursor).
* Delete text by holding down the Backspace key (you'll see text is not removed smoothly but in chunks).
@CAM-Gerlach, sorry that it took us so long to fix this. It was not that hard after I understood how indent guides are painted (but I also had the …
=> PR: Improve performance when painting indent guides

spyder/plugins/help/utils/static/css/default.css, spyder/plugins/help/utils/static/dark_css/default.css
Changed the colors of the kernel error in the IPython console to enhance contrast. I used the new darker red proposed by @isabela-pf for errors in https://github.com/spyder-ide/ux-improvements/issues/13.
Fixes #13754 
Juanis2112
=> PR: Change colors for kernel errors in IPython console

spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/kite/utils/tests/test_install.py, spyder/plugins/completion/languageserver/plugin.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_decorations.py, spyder/plugins/editor/widgets/tests/test_editor_and_outline.py, spyder/plugins/editor/widgets/tests/test_save.py, spyder/plugins/outlineexplorer/api.py, spyder/plugins/outlineexplorer/editor.py, spyder/plugins/outlineexplorer/plugin.py, spyder/plugins/outlineexplorer/tests/test_widgets.py, spyder/plugins/outlineexplorer/widgets.py
- Update the outline for all files from the previous session. Before, an update was performed only after those files were edited somehow.
- Update the outline when there are no symbols to show to an empty tree.
- Hide the spinner for untitled files or files without an LSP that can provide symbols for them.
TODO:
=> PR: Update outline for files in previous session after Spyder started

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/widgets/tests/test_editor_and_outline.py
This is necessary to fix our tests in master, but better to make the change in 4.x to avoid conflicts in the future.
=> PR: Use a better method to check the spinner is not shown in a couple of Outline tests

spyder/app/mainwindow.py, spyder/widgets/status.py, spyder/widgets/tests/test_status.py
* display interpreter status in statusbar, even if it isn't a conda interpreter or spyder isn't started from conda environment.
The conda status bar no longer tests if Spyder's python interpreter is from a conda environment.
Currently, when updating the conda status in the status bar, Spyder's python environment is tested for being a conda environment rather than the iPython console's interpreter environment.
When Spyder is launched from a non-conda environment (such as in a standalone Mac application), the iPython console interpreter status is not displayed.
This PR fixes that.
Fixes spyder-ide/mac-application#6 …
=> PR: Display interpreter status if Spyder not launched from conda envrionment (Mac app)

spyder/dependencies.py, spyder/plugins/ipythonconsole/plugin.py, spyder/preferences/maininterpreter.py, spyder/utils/programs.py
Use a clean shell environment when obtaining python interpreter version or installed module version.
Currently, when checking for python version or installed module versions in subprocesses in preparation for launching a `spyder_kernel`, the subprocess inherits Spyder's environment variables, which can lead to incorrect results if Spyder's environment is not a conda environment (such as in a standalone Mac application). By using a clean subprocess environment, the python version and installed module versions are correctly checked.
Currently, installed module versions are checked by writing a new script to a temporary script file and running it in a python subprocess, possibly several times, depending on the version requirements. This is replaced with a much simpler, single python …
=> PR: Use clean environment for Python version and module checks (Mac app)

spyder/plugins/editor/widgets/editor.py
Added warning dialog for xdg-file when trying to open files in external file explorer
Fixes #13507 
Juanis2112
=> PR: Add warning for xdg-utils when trying to open a file in the editor in the external file explorer

spyder/config/lsp.py, spyder/plugins/completion/languageserver/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/utils/kernelspec.py, spyder/plugins/ipythonconsole/utils/tests/test_spyder_kernel.py
Currently, `spyder_kernel` shell environment variables are inherited from Spyder's environment _implicitly_. This prevents `spyder_kernel` from launching if Spyder is not launched from a conda environment (such as in a standalone Mac application). This PR solves this issue by _explicitly_ passing the desired environment variables to the `spyder_kernel` via `kernel_spec`.
This allows a stand-alone Mac application to work properly.
@mrclary
=> PR: Start kernels and Jedi envs with explicit environment (Mac app)

spyder/app/tests/test_mainwindow.py, spyder/plugins/outlineexplorer/plugin.py, spyder/plugins/outlineexplorer/widgets.py, spyder/plugins/projects/plugin.py
This also updates all files in the Outline after switching projects and finally solves issue #13897.
Fixes #13897
=> PR: Update Outline when opening or closing projects

spyder/plugins/breakpoints/widgets/breakpointsgui.py, spyder/plugins/editor/utils/debugger.py
On windows, breakpoints are sometimes saved with filenames using different capitalisation. 
This causes removable breakpoints.
This solves this annoying issue.
I was not able to understand how the bug is caused so there is no tests.
Fixes #
=> PR: Normcase breakpoints to avoid issues on Windows

spyder/app/mainwindow.py
We don't know how this error is generated (it's been reported several time), but this should avoid it.
Fixes #13977.
=> PR: Catch TypeError when loading third-party plugins (Main Window)

spyder/app/mainwindow.py, spyder/config/main.py, spyder/preferences/appearance.py, spyder/preferences/general.py
This PR avoids calling `MainWindow.apply_settings` when applying changes in Appearance, which was unnecessary.
It also removes the following options from Preferences/General:
- Vertical title bars in panes
- Animated toolbars and panes
- Tear off menus
The first one was breaking the interface. And by removing the others, now changes in Appearance (e.g. syntax highlighting and fonts) apply much faster.
=> PR: Improve how the options in Preferences/Appearance are applied

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py
This PR prevents an unwanted naming clash introduced in #13295 where `remove_trailing_spaces` was defined both as a method and an attribute
Fixes #14001
=> PR: Fix remove_trailing_spaces method and attribute clash

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/utils/kernelspec.py
- This avoids a kernel crash when users have files with the same names as standard library modules either in their projects or the directories they set through our PYTHONPATH manager.
- Instead, we pass it through a new env var called SPY_PYTHONPATH, whose contents are added to sys.path in the kernel's sitecustomize.
Depends on spyder-ide/spyder-kernels#253.
Fixes #13519.
=> PR: Don't pass PYTHONPATH directly to the kernel (IPython console)

spyder/utils/misc.py, spyder/utils/tests/test_misc.py
After PR #14017, we are no longer using `add_pathlist_to_PYTHONPATH` in our kernelspec. That allowed us to simplify its code and fix some bugs about it.
Fixes #13964
Fixes #12564
Fixes #3161
=> PR: Simplify add_pathlist_to_PYTHONPATH

spyder/preferences/runconfig.py
This is a follow up of PR #13979 to fix the layout for the single file version of the `RunConfigOneDialog`.
I'm sorry for that, I totally missed this in my previous PR.
=> PR: Some improvements to the "Run > Configuration per file" dialog (2)

spyder/plugins/projects/widgets/projectdialog.py
This PR proposes very minor changes to improve the style of the `ProjectDialog`:
- Remove the window context help button. Since we are not using this feature, there is no need to have this button there.
- Standardize the style of the 'Select directory' button to that used elsewhere in Spyder.
=> PR: Some improvements to the create project dialog.

spyder/plugins/ipythonconsole/utils/kernelspec.py
Remove `PYTHONPATH` from `env_vars` passed to external IPython consoles on the macOS application.
Commit cb13febc87d0b365d01ee184aaaf536076f96d48 introduced an error in which Spyder's runtime PYTHONPATH was passed to the kernel preventing external IPython consoles from launching.
Now that the Python Path Manager values no longer overwrite `PYTHONPATH` in `env_vars`, we can just drop it for macOS app external consoles.
mrclary
=> PR: Fix issue where external IPython consoles do not launch for macOS application

.github/workflows/installer-macos.yml, installers/macOS/Readme.md, installers/macOS/dmg_settings.py, installers/macOS/req-build.txt, installers/macOS/req-const.txt, installers/macOS/req-extras.txt, installers/macOS/setup.py
Added files for creating Spyder.app macOS standalone application.
Included the necessary resources to build a standalone macOS application.
See spyder-ide/mac-application#3
Fixes #13978 
mrclary
=> PR: Add scripts and files necessary to create a macOS installer

spyder/widgets/about.py
@ccordoba12 Feel free to revert any changes you don't agree with. I should have opened an issue first, but since I'm a little bit short on time these days, it is more efficient to open a PR directly, I apologize for that.
Also, I don't know how this will look in macOS or Linux.
1. Make text in the dialog selectable.
2. Change dialog logo to fit that used in the `Help` menu
3. Scale Spyder logo with a Smooth transform instead of Fast to improve how it look on-screen.
4. Don't hardcode the dialog size and let Qt determine the best size to fit the content.
and understand I am releasing the …
=> PR: Improvements to the About Spyder dialog

spyder/app/mainwindow.py, spyder/plugins/ipythonconsole/plugin.py
=> PR: Fix loading of external (non dockable) plugins and other fixes

external-deps/python-language-server/.gitrepo, external-deps/python-language-server/pyls/plugins/pycodestyle_lint.py, external-deps/python-language-server/pyls/workspace.py, external-deps/python-language-server/test/fixtures.py, external-deps/python-language-server/test/plugins/test_completion.py
The fix made in https://github.com/palantir/python-language-server/pull/879 allows us to have completions for files placed next to a module and out of the workspace's `root_path`.
Fixes #11118.
=> PR: Update subrepo with python-language-server#879

binder/environment.yml, spyder/tests/test_dependencies_in_sync.py
Removed the following deprecation warning:
```
spyder/tests/test_dependencies_in_sync.py::test_dependencies_for_binder_in_sync
/home/runner/work/spyder/spyder/spyder/tests/test_dependencies_in_sync.py:58: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
data = yaml.load(fh)
```
Also figured out https://github.com/spyder-ide/spyder/pull/14014#issuecomment-716539881 and corrected the files.
I certify the …
=> PR: Remove PyYAML deprecation warning

.gitattributes, spyder/app/mainwindow.py, spyder/app/tour.py
This PR also does the following:
* Improve the style and docstrings of several layout related methods. Those were really bad, so I took the opportunity to improve them while I was reviewing how their code works.
* Improve how git displays diffs for Python files. That's something I just found on [this page](https://tekin.co.uk/2020/10/better-git-diff-output-for-ruby-python-elixir-and-more) and it was useful while reviewing the diffs generated by my changes.
@juanis2112, could you review if this PR fixes the problem you reported? It does on my manual tests.
=> PR: Use current size and position when saving window settings (Main Window)

spyder/plugins/pylint/widgets/pylintgui.py
This avoids collapsing the results tree after pressing in one of its entries.
Fixes #13347
=> PR: Don't try to reload analysis for the currently displayed file (Code Analysis)

spyder/plugins/completion/kite/client.py, spyder/plugins/completion/kite/plugin.py
This PR handles wrong Kite responses by displaying an error message and disabling Kite on Spyder 
Fixes #13121
=> PR: Display an error message when Kite sends a non-dict response

spyder/app/mainwindow.py
This PR improves the message we show at startup about new releases. Its purpose is to simplify that message significantly, especially for people that will start using our new installers. I also changed the title of that dialog to make it clearer.
* Before, using Anaconda:
* Before, not using Anaconda:
----
* After, using Anaconda:
* After, not using Anaconda:
Fixes #12677
=> PR: Improve message about new releases (Main Window)

spyder/utils/conda.py, spyder/utils/programs.py
Temporarily add required paths to `sys.environ['PATH']` in `spyder.utils.programs.is_program_installed`.
By adding platform dependent paths to `os.environ['PATH']`, developers will not have to consider macOS application cases when using `find_program`. Additionally, developers will not have to consider cases in which Spyder is not launched from login shells (i.e. user profiles are not sourced).
Since `PATH` is only temporarily modified to locate a given program, it should not affect the behavior of Spyder or Consoles.
Developers should update the `req_paths` in the respective platform control sequence to include paths in the search for programs.
Fixes #14136  …
=> PR: Add search paths to PATH in is_program_installed

external-deps/python-language-server/.gitrepo, external-deps/python-language-server/pyls/plugins/symbols.py, external-deps/python-language-server/pyls/workspace.py, spyder/app/tests/test_mainwindow.py, tools/rm_whitespace.py
This was an important regression after moving the Outline to use the LSP symbols information.
Depends on palantir/python-language-server#882
Fixes #13928.
=> PR: Check that we can get symbols in a file not part of a Python module

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py, spyder/widgets/about.py
The text in the warning for variable explorer was separated which didn't allow translations
I created two separated messages to allow translations
Fixes #
Juanis2112
=> PR: Fix some strings for translation

spyder/plugins/editor/extensions/snippets.py
This PR fixes a corner case with indented code snippets where the root TextNode was picked instead of the nearest one.
Fixes #14125
=> PR: Prevent code snippet search from picking the root text node

spyder/config/main.py, spyder/plugins/completion/languageserver/confpage.py, spyder/plugins/completion/languageserver/plugin.py, spyder/plugins/editor/confpage.py, spyder/plugins/editor/panels/edgeline.py
Enhance the UI of the autoformatter options in the completion engine.
Fixes #14082
=> PR: Set column width automatically after changing autoformatter

spyder/plugins/completion/snippets/trie.py
Might not be perfect, but helps with #14183.
As this bug makes Spyder completely unusable, I suggest this patch to be released as soon as possible.
I replaced
```python
if len(sequences) == 0:
[1]
else:
[2]
```
by
```python
if sequences:
[2]
else:
[1]
```
@ElieGouzien
=> PR: Fix TypeError in text snippets

spyder/plugins/completion/snippets/actor.py
This PR prevents spurious errors when trying to index the text snippets' prefix tree with a None value
Fixes #14183
=> PR: Prevent indexing prefix tree with None values

spyder/utils/programs.py
* add SYSTEMDRIVE to required environment variables on Windows for `alter_subprocess_kwargs_by_platform`
* fixes issue where interpreter environments are not found
* fixes issue "pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)"
Upon testing the Windows installer for 4.2.0 release, I discovered that external conda environments were not found.
Further investigation from the internal console revealed the following traceback.
```python
File "C:\Users\rclary\Anaconda3\Scripts\conda-env-script.py", line 5, in <module>
from conda_env.cli.main import main
File "C:\Users\rclary\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 44, in <module>
from . import main_create
File …
```
=> PR: Fix conda environment list on Windows application

installers/Windows/req-extras-pull-request.txt, installers/Windows/req-extras-release.txt
Prevent an error when importing NumPy:
```
RuntimeError: The current Numpy installation ('C:\\Users\\Daniel\\AppData\\Local\\Programs\\Spyder\\pkgs\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```
Fixes #
=> PR: Pin NumPy version to prevent RuntimeError - sanity check on Windows installer (Windows 10)

spyder/app/mainwindow.py, spyder/dependencies.py, spyder/utils/programs.py
This improves startup time a bit by doing the following:
* Delaying computation of missing dependencies 2 seconds after the window is up.
* Not running the check for optional dependencies when computing missing deps.
It also fixes a bug in `is_module_installed` that was making Spyder crash at startup if a module was not uninstalled correctly.
=> PR: Improve startup time a bit

spyder/utils/encoding.py
Set default permission without execution 
Fixes #14112 
=> PR: Set base permission to 0o666 minus umask for files when saving

spyder/app/mainwindow.py, spyder/app/utils.py
After PR #12926, I noticed we could simplify those two things a lot.
Benefits:
* It helps to make the code way more readable
* It avoids the hacks of using constants for the app and splash screen that need to be passed around in several places.
=> PR: Simplify creation of main application and splash screen

spyder/app/start.py
Sets QT_MAC_WANTS_LAYER to '1' when launching spyder. This will hopefully solve the launch issue on Big Sur. I am not 100% on what that does exactly, as I couldn't find doc about it.
Fixes https://github.com/spyder-ide/spyder/issues/14222
Fixes https://github.com/spyder-ide/spyder/issues/14218
=> PR: Set QT_MAC_WANTS_LAYER env var to solve problems in Big Sur

installers/macOS/setup.py, spyder/plugins/pylint/widgets/pylintgui.py
* when running in mac app, ensure PYTHONHOME is passed to QProcessEnvironment
* include pylint in build packages: 'No module named pylint.__main__; 'pylint' is a package and cannot be directly executed'
Fixes #14262 
@mrclary
=> PR: Fix Code Analysis in macOS Application

spyder/plugins/outlineexplorer/widgets.py
This PR fixes some issues where symbols were collapsed when the `Follow cursor` option is disabled.
Fixes #14152
=> PR: Fix issues with expanded symbols when cursor is not being followed up

spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/languageserver/__init__.py, spyder/plugins/editor/utils/switcher.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/outlineexplorer/widgets.py
This PR enables the symbol switcher to use the information provided by the `textDocument/symbols` LSP call.
Fixes #14221 
=> PR: Migrate the symbol switcher to use the LSP information

spyder/plugins/ipythonconsole/comms/kernelcomm.py
If the comms channel is not opened when trying to reply to a comms message, spyder would freeze and crash.
Fixes #
=> PR: Prevent comms from crashing spyder

spyder/plugins/pylint/widgets/pylintgui.py
Mixture of slash and back slash paths on WIndows
Fixes #13535 
=> PR: Normalize file paths for correct handling of filenames for static code analysis

spyder/plugins/editor/panels/utils.py
This PR replaces Jaro-Wrinkler distance by the Jaccard index distance used to compare text among folding regions. The former metric was causing significant delays on the editor updates.
Fixes #14309
=> PR: Replace Jaro-Wrinkler distance by normalized Jaccard index (Folding)

spyder/plugins/variableexplorer/widgets/collectionseditor.py
This PR fixes a bug where columns in the variable explorer could get out of sync when sorting on size.
Fixes #14155 
By submitting this Pull Request and typing my username below,
I certify the above statement is true and correct: hengin
=> PR: Fix variable explorer sort by size bug

spyder/api/panel.py, spyder/plugins/help/widgets.py
Fixed variable name
I think there was a typo in variable name, so I fixed it. Also logging put among third party libraries which is not correct 
Fixes #
=> PR: Fix typo in variable name

.github/workflows/installer-macos.yml, installers/macOS/req-const.txt, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/explorer/widgets/tests/test_explorer.py
This updates the Files view if the filter button is on and the user changed its filters.
We now emit a signal (`sig_update_filters`) after the filters dialog is closed. This signal is connected to a new method in the tree widget called `filter_files`, which is in charge of filterting the view.
*Note*: I took the opportunity to fix a minor issue with the Mac installer caused by a new version of `pyobjc`. The solution was simply to pin that package to version `6.2.2` (the one that it's currently working).
Fixes #14328 …
=> PR: Update view after applying filters if filters are on (Files)

spyder/plugins/variableexplorer/widgets/arrayeditor.py
In the Array Editor, when editing boolean values, they toggle instead of opening an actual editor. However, the logic to detect boolean values could not distinguish between booleans and arrays of booleans. This caused errors to be raised in the latter case.
This pull request adds an extra clause to detect this case and prevent errors. As a bonus, it prevents a QLineEdit from being created when the view is readonly. This is the case for object arrays such as `np.array([1, 'abc', [3,2,1]])`. Previously, the creation of a QLineEdit gave the user the impression that editing was possible; even though all such edit attempts would silently fail when the QLineEdit was closed.
Fixes #12877 
By submitting this Pull Request and typing my username below, …
=> PR: Fix error when opening array of boolean arrays in Variable Explorer

spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/projects/tests/test_plugin.py
We were using a different tooltip if the button was pushed or not, which was really confusing.
Fixes #14329
ccordoba12
=> PR: Use a single tooltip for the Files filter button

spyder/otherplugins.py, spyder/plugins/completion/fallback/utils.py, spyder/plugins/io_hdf5/plugin.py, spyder/utils/introspection/old_fallback.py, spyder/utils/programs.py
imp is deprecated and should be replaced by importlib. I have changed all but one of the places where it was used. Not sure what the code in `get_parent_util` exactly should do.
I certify the above statement is true and correct: oscargus
=> PR: Replace deprecated imp with importlib

spyder/app/mainwindow.py
This is to avoid users confusion about the version displayed there and the one used in our IPython console.
Fixes #14377
I certify the above statement is true and correct: ccordoba
=> PR: Don't show Python version on window title for our Mac and Windows apps

.github/scripts/install.sh, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, spyder/plugins/ipythonconsole/plugin.py
- This is not necessary anymore with Tornado 6.1+, released a couple of weeks ago.
- This PR also fixes an error when running our tests after merging and don't install pyenv in our slow slots.
Fixes #14404
=> PR: Don't apply asyncio patch for Tornado 6.1+ (IPython console)

.github/workflows/installer-macos.yml, installers/macOS/req-extras.txt, installers/macOS/req-scientific.txt, installers/macOS/setup.py, spyder/utils/pyenv.py, spyder/utils/tests/test_pyenv.py, spyder/widgets/status.py
Snippets are now fully functional in the macOS application. It turns out that we don't need a wheel for Rtree, but just need to include the `spatialindex` libraries in the `py2app` setup file.
Also fixed issue (since PR #14332) where macOS app and bootstrap (non-conda) fail to launch with error
```python
File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/status.py", line 336, in update_envs
self.update_interpreter()
File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/status.py", line 398, in update_interpreter
self.value = self._get_env_info(self._interpreter)
File …
```
=> PR: Add Rtree and other fixes for the macOS app

spyder/utils/programs.py
- This fixes the Profiler, which requires the presence of some modules to work.
- The previous validation was incorrect because a module can be present and don't have a version. That was precisely the case for the modules requested by the Profiler.
=> PR: Fix validation for incorrectly uninstalled packages in is_module_installed

spyder/config/main.py, spyder/plugins/console/widgets/shell.py, spyder/plugins/history/confpage.py, spyder/plugins/history/plugin.py, spyder/plugins/history/tests/test_plugin.py
While writing docs for this pane, @juanis2112, @CAM-Gerlach and I came to the conclusion that this option doesn't add much value and it's also hard to understand because it's not applied instantly but when Spyder is restarted.
Preferences for history now look like this
Before they looked like this
=> PR: Remove option to set max number of lines (History)

spyder/plugins/editor/utils/languages.py, spyder/plugins/editor/widgets/codeeditor.py
This was requested in https://github.com/spyder-ide/spyder/issues/638#issuecomment-719724646. According to the user, ArcGIS uses `pyt` as the extension for its Python scripts.
Also, `pyi` files are very becoming common in compiled libraries (e.g. Numpy).
=> PR: Add .pyt and .pyi as extension recognized as Python files (Editor)

spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/__init__.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/control.py, spyder/plugins/ipythonconsole/widgets/shell.py
The IPython console has a pager to show long texts in a separate widget to not overflow it with them. It was deactivated by default, but I removed that option with PR #14056 because I thought the pager was broken.
However, our users quickly found out that was not the case and @OverLordGoldDragon suggested we should add a warning to tell people how to get out of the pager. And that's what I've done in this PR.
Fixes #14192.
=> PR: Show a warning telling people how to get out of the pager (IPython console)

spyder/app/tests/test_mainwindow.py
The problem was caused by merging PR #14418 from `4.x` because the `RunConfiguration` dialog is now part of the Run plugin.
=> PR: Fix wrong import (Testing)

spyder/preferences/maininterpreter.py
This preserves custom interpreters introduced manually in Preferences after reopening them again and across different Spyder sessions.
This was something we missed when implemented these changes in 4.2.0
=> PR: Preserve custom interpreters introduced manually (Main interpreter)

spyder/config/main.py, spyder/plugins/completion/kite/plugin.py
We had an interesting call with Adam Smith (Kite's CEO) yesterday about this. He understood our rationale for showing the tour's dialog the first time Spyder is started. And we agreed to show Kite's on-boarding dialog again, but this time the third time Spyder is started.
=> PR: Show Kite's on-boarding dialog the third time Spyder is started

CONTRIBUTING.md
* `## Spyder Branches` : Added `H` to `<SPYDER-BASE-BRANC>`
* `## Spyder Branches` : Added `<>` around `NAME-NEW-BRANCH`
=> PR: Fix two typos in Contributing guide

spyder/api/widgets/mixins.py, spyder/api/widgets/toolbars.py, spyder/plugins/profiler/widgets/main_widget.py
>In macOS when I hit the option to expand all, the last entry is not visible even in the bottom of the scrollbar
I cannot reproduce this, see GIF
Fixes #13698
=> PR: Fix some issues with the profiler

spyder/api/plugins.py, spyder/api/widgets/menus.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/breakpoints/plugin.py, spyder/plugins/console/plugin.py, spyder/plugins/console/tests/test_plugin.py, spyder/plugins/console/widgets/main_widget.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/findinfiles/plugin.py, spyder/plugins/help/api.py, spyder/plugins/help/plugin.py, spyder/plugins/help/widgets.py, spyder/plugins/mainmenu/__init__.py, spyder/plugins/mainmenu/api.py, spyder/plugins/mainmenu/container.py, spyder/plugins/mainmenu/plugin.py, spyder/plugins/profiler/plugin.py, spyder/plugins/pylint/plugin.py, spyder/plugins/shortcuts/plugin.py, spyder/utils/programs.py, spyder/utils/qthelpers.py
- A new `MainMenu` plugin in charge of managing the application menu bar, menus, and menu sections.
- Plugins that need to add menus or add items (Actions or submenus) to the main application menu bar will require this plugin.
- The API of menus now lives in this plugin instead of the global `spyder.api` since the plugin is in charge of those specifics.
=> PR: Create new MainMenu plugin

spyder/api/plugins.py, spyder/api/widgets/__init__.py, spyder/api/widgets/mixins.py, spyder/api/widgets/toolbars.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/config/main.py, spyder/plugins/findinfiles/plugin.py, spyder/plugins/findinfiles/widgets.py, spyder/plugins/help/api.py, spyder/plugins/help/widgets.py, spyder/plugins/mainmenu/api.py, spyder/plugins/onlinehelp/widgets.py, spyder/plugins/plots/widgets/main_widget.py, spyder/plugins/profiler/api.py, spyder/plugins/profiler/widgets/main_widget.py, spyder/plugins/pylint/api.py, spyder/plugins/pylint/main_widget.py, spyder/plugins/toolbar/__init__.py, spyder/plugins/toolbar/api.py, spyder/plugins/toolbar/container.py, spyder/plugins/toolbar/plugin.py, spyder/plugins/workingdirectory/container.py, spyder/plugins/workingdirectory/plugin.py
- A new ToolBar plugin in charge of managing the application toolbars, and toolbar sections sections.
- Plugins that need to add a toolbar or add items (Actions/Widgets) to the main application toolbar area bar will require this plugin.
- The API of toolbars now lives in this plugin instead of the global `spyder.api` since the plugin is in charge of those specifics.
=> PR: Add new toolbar plugin

spyder/app/mainwindow.py
After PR #14229, we were opening the script that starts Spyder at each startup (but only in Anaconda and Mac). The changes in this PR prevent that.
The idea is simply to not open a filename that contains `bin/spyder` as part of its name (which is the ending of our start script in Mac).
Fixes #14483
=> PR: Don't open script that starts Spyder at startup on macOS

spyder/plugins/ipythonconsole/utils/kernelspec.py
- That variable was preventing kernel creation for custom interpreters in Anaconda and macOS.
- That's because Anaconda's `pythonw` Bash script exports `PYTHONEXECUTABLE` as part of it.
Fixes #13252 
=> PR: Remove PYTHONEXECUTABLE from env vars passed to the kernel

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_codeeditor.py, spyder/widgets/mixins.py
This pull-request provides workarounds for a quirk in QTextEdit that is illustrated in the GIFs below:
When text is deleted (whether by backspace, delete or cursor operations), the QTextEdit does not forget its last horizontal position. When navigating Up/Down right after a delete operation, the horizontal cursor will be restored to that position. Can be very detrimental to the editing experience!
The root cause is a 7 year old Qt bug: [QTBUG-35861](https://bugreports.qt.io/browse/QTBUG-35861). It seems unlikely to ever be fixed upstream. Still, I've added a regression test `test_qtbug35861` that will fail if the upstream bug is fixed.
~~Note that one edge case (deleting a selection) is only covered when the "delete" shortcut is bound to the "Delete" key. This is the default setting, but …
=> PR: Workaround for Qt-bug where cursor moves unintuitively after text deletion

spyder/utils/color_system.py
According to https://github.com/spyder-ide/ux-improvements/issues/13 @isabela-pf helped us design a new palette for Spyder 5 in which the shades of Gray and blue will still be used from Qdarkstyle and we will have 5 more groups of colors added in this PR. 
1. Several shades for green for success elements
2. Several shades for orange for warning elements
3. Several shades for red for error elements
4. A rainbow group for other elements as the variable explorer in dark mode
5. A rainbow group for other elements as the variable explorer in light mode
For the rest of the palette see https://github.com/ColinDuquesnoy/QDarkStyleSheet/pull/253/files
Fixes # …
=> PR: Add color system file for new scale of colors in Spyder 5

spyder/plugins/completion/manager/api.py, spyder/plugins/editor/widgets/codeeditor.py
This PR adds a temporary hack to detect languages based on their extensions, and adds STIL as a supported language (required by TDK).
cc @nerohmot
Fixes #
=> PR: Add STIL to the list of supported languages

spyder/plugins/editor/panels/codefolding.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_folding.py
This PR moves the code folding region update and merge calls into its own thread, by doing this, we expect to fix some performance issues related to calls to textdistance specially in Mac.
Fixes #14570
=> PR: Move folding update to a thread

spyder/widgets/findreplace.py
Added button to show and hide replace widget from find widget as discussed in https://github.com/spyder-ide/ux-improvements/issues/25
Fixes https://github.com/spyder-ide/ux-improvements/issues/25
Juanis2112
=> PR: Add button to show and hide replace widget from find widget

installers/macOS/setup.py
Move ipython out of zipped libraries in macOS application. Resolves an issue where [[SpyderKernelApp] WARNING | Could not copy README_STARTUP to startup dir.](https://github.com/spyder-ide/spyder/issues/14656#issuecomment-769600472)
@mrclary
=> PR: Move IPython out of zipped libraries in macOS application

spyder/api/widgets/menus.py, spyder/plugins/mainmenu/plugin.py
Flag to preserve UI even with a mix of migrated and non-migrated menus
Preview:
Fixes #14661 
=> PR: Add flag to prevent adding initial empty QAction on Mac for non-migrated menus

spyder/api/plugins.py, spyder/api/widgets/mixins.py, spyder/api/widgets/toolbars.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/application/__init__.py, spyder/plugins/application/confpage.py, spyder/plugins/application/container.py, spyder/plugins/application/plugin.py, spyder/plugins/console/plugin.py, spyder/plugins/console/widgets/main_widget.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/tests/test_editor_config_dialog.py, spyder/plugins/help/plugin.py, spyder/plugins/maininterpreter/tests/test_confpage.py, spyder/plugins/mainmenu/plugin.py, spyder/plugins/preferences/plugin.py, spyder/plugins/preferences/tests/conftest.py, spyder/plugins/run/widgets.py, spyder/plugins/toolbar/api.py, spyder/plugins/toolbar/container.py, spyder/plugins/toolbar/plugin.py
=> PR: Add a new Application plugin

binder/environment.yml
conda-forge has working websockify now
conda-forge now [has](https://github.com/conda-forge/staged-recipes/pull/12168) websockify,
so we no longer need to add the manics channel (helpfully maintained by @manics)
to our environment.yml
yuvipanda
=> PR: Don't add manics conda channel to Binder's environment.yml

spyder/app/mainwindow.py
Try to simplify the logic to handle the DPI change to trigger a restart of Spyder if needed (Monitor scale change message). ~Use `show` instead of `exec` to prevent crashing when no painting device is found.~ Actually `open` needs to be use and also connect to the finished signal of the dialog to handle the result.
Needs manual testing on Mac and Linux and also in a setup using a secondary screen (connecting/disconnecting, changing scale/DPI settings, etc)
Fixes #14273 
I certify the above statement is true and …
=> PR: Improve DPI change detection 

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_classfunc_selector.py, spyder/plugins/editor/widgets/tests/test_decorations.py, spyder/plugins/editor/widgets/tests/test_editor_and_outline.py, spyder/plugins/editor/widgets/tests/test_folding.py
This avoids requesting symbols and folding after linting results arrive from the PyLS. Instead, it does that after a timeout.
This should avoid the freezes reported on issue #14384.
=> PR: Synchronize symbols and folding after a timeout (Editor)

spyder/plugins/ipythonconsole/comms/kernelcomm.py, spyder/plugins/ipythonconsole/plugin.py
=> PR: Tunnel comm port to make all features that depend on comms work for remote kernels

spyder/plugins/outlineexplorer/widgets.py
This PR fixes issues with the outline explorer when the symbol items are None.
Fixes #14413
=> PR: Prevent None items in Outline Explorer

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/editor.py
This PR fixes some autoformatting overlaps when a file is run in the iPython console due to duplicate calls to save when autoformatting on save is enabled
Fixes #14653
I certify the above statement is true and correct:  @andfoy
=> PR: Prevent double saving when running a file

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
These tests started to fail with `ipykernel` 5.5.0, released yesterday. I found the fix was entering directly to debugging mode instead of generating a traceback first.
=> PR: Simplify how we enter debugging mode in IPython console tests

binder/environment.yml, requirements/conda.txt, setup.py, spyder/dependencies.py
This fixes an error in macOS when switching projects.
Fixes #14779.
=> PR: Constrain Watchdog to be less than 2.0.0

setup.py, spyder/api/plugins.py, spyder/api/utils.py, spyder/api/widgets/toolbars.py, spyder/app/solver.py, spyder/app/tests/test_solver.py, spyder/plugins/appearance/__init__.py, spyder/plugins/application/__init__.py, spyder/plugins/application/plugin.py, spyder/plugins/explorer/__init__.py, spyder/plugins/maininterpreter/__init__.py, spyder/plugins/mainmenu/__init__.py, spyder/plugins/preferences/__init__.py, spyder/plugins/pylint/__init__.py, spyder/plugins/run/__init__.py, spyder/plugins/shortcuts/__init__.py, spyder/plugins/shortcuts/plugin.py, spyder/plugins/toolbar/__init__.py, spyder/plugins/toolbar/container.py, spyder/plugins/toolbar/plugin.py
This PR fixes several problems we discovered in 5.0 alpha4 when loading external plugins:
- Add missing entry_points and fix init files for new plugins added in alpha3 and alpha4.
- Fix solving list of required plugins for external plugins.
- Fix adding third-party toolbars to the toolbars menu.
- Make Preferences a required plugin for a couple of plugins that had it as optional.
=> PR: Several fixes to load external plugins

spyder/plugins/ipythonconsole/comms/kernelcomm.py, spyder/plugins/ipythonconsole/widgets/client.py
When the kernel restarts, it will close the comm and reopen it. THis doesn't make sense to close it as the comm is not open at this point.
Fixes #
=> PR: Remove "No such comm" warning

spyder/api/panel.py, spyder/plugins/editor/panels/classfunctiondropdown.py, spyder/plugins/editor/panels/codefolding.py, spyder/plugins/editor/panels/edgeline.py, spyder/plugins/editor/panels/indentationguides.py, spyder/plugins/editor/panels/linenumber.py, spyder/plugins/editor/panels/manager.py, spyder/plugins/editor/panels/scrollflag.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_panels.py, spyder/widgets/simplecodeeditor.py
This PR adds the possibility to add custom panels to the top, right, left, bottom and floating to the editor.
Example of a pane in the right:
Example of a pane in both left and right:
=> PR: Add external panels API to the editor

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/preferences/api.py
This change fixes some exceptions caused due to a missing argument to calls to `set_option` in some old API preference pages, such as Appearance.
Fixes #
=> PR: Add missing recursive_notification argument to set_option calls in old API preference pages

.github/workflows/installer-macos.yml, bootstrap.py, setup.py
The LSP server was not starting for macOS applications, and apparently bootstrap worked around the same issue some time ago by explicitly adding the spyder.completions entry-points in `bootstrap.py`. However, this is not necessary if `lsp` is added in `setup.py`.
* Added `lsp` to `spyder.completions` entry-points; this resolves issue with LSP not starting for macOS application.
* With `lsp` added to entry-points, the entry-point patching in `bootstrap.py` is not needed (in fact causes an error); instead just create Spyder's egg-info
Fixes #14923
and understand I am releasing the same …
=> PR: Add lsp to spyder.completions entry-points

spyder/plugins/preferences/api.py
Added missing "self" argument
Fixes #
=> PR: Add missing "self" argument in a method

spyder/app/mainwindow.py, spyder/app/tests/test_solver.py, spyder/config/main.py, spyder/plugins/mainmenu/api.py, spyder/plugins/preferences/plugin.py, spyder/plugins/preferences/widgets/container.py, spyder/plugins/toolbar/container.py
This also solves the circular dependency between Preferences and Shortcuts reported by @dalthviz. What I did was to remove shortcuts to open Preferences and show toolbars because those plugins need to be loaded before Shortcuts.
=> PR: Move actions to open preferences and reset to defaults to the Preferences plugin

spyder/app/mainwindow.py
This simply avoids showing our error message dialog when (for some reason) we fail to update the Source menu at startup.
Fixes #14901.
=> PR: Catch an error when updating the Source menu at startup

spyder/app/mainwindow.py
Use the version argument of `QMainWindow.restoreState` to validate the hexstate that will be loaded
Part of #13629
=> PR: Update hexstate handling to fallback to default layout when moving from Spyder 5 to Spyder 4

spyder/app/mainwindow.py
- This allows to really reset the layout when moving from Spyder 4 to 5 and viceversa.
- It's a followup of PR #14956.
=> PR: Use version arg explicitly in saveState/restoreState (Main Window)

.github/workflows/test-linux.yml, spyder/app/mainwindow.py, spyder/plugins/editor/widgets/tests/test_decorations.py
This is a followup to PR #14957. Unfortunately, in that PR I didn't set `version` in all calls of those methods, which broke custom layouts and restoring the main window state saved in previous sessions.
Fixes #14962.
=> PR: Pass version kwarg in every call to saveState/restoreState (Main Window)

spyder/plugins/ipythonconsole/widgets/client.py
Avoid crash when restarting kernel multiple times
Fixes #15002
=> PR: Avoid segfault when restarting kernel

spyder/app/tests/test_mainwindow.py, spyder/app/tour.py
Not passing a `QColor` to `QPen` was causing a segfault when trying to display the tour. 
=> PR: Fix a segfault with the intro tour

spyder/plugins/variableexplorer/widgets/main_widget.py, spyder/plugins/variableexplorer/widgets/namespacebrowser.py, spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py, spyder/widgets/collectionseditor.py
Multiple instances of the finder (close button + line edit) were being created. The main problem was not related to creating the whole finder element multiple times but the close button (which was like declaring the same action multiple times).
Now only one instance of the finder is created.
Fixes #15010
=> PR: Fix for search/find close button error (Variable Explorer)

spyder/plugins/application/container.py, spyder/plugins/preferences/widgets/container.py
Add Qt Roles for About and Preferences main menu actions for adding the actions in the applications menu
Fixes #14917 
=> PR: Set right roles for some actions on macOS menu bar

spyder/plugins/plots/widgets/figurebrowser.py
This fixes the error of the thumbnail section in the plots pane to occupy all the space afer restarting Spyder,
=> PR: Prevent setting negative sizes in the Plots pane

spyder/config/main.py
This fix removes the extra column that was appearing in the projects pane when Spyder opened with a project loaded.
=> PR: Add option to hide the date column from Projects

spyder/app/tour.py
Fix the tour icons
Fixes #14996 
=> PR: Fix tour icons

.github/workflows/installer-macos.yml
Use the `qdarkstyle` subrepo on pull requests in the pipeline build of the macOS application.
Fixes #15053
@mrclary
=> PR: Use qdarkstyle subrepo in macOS app

spyder/plugins/console/widgets/main_widget.py, spyder/widgets/reporterror.py
This PR fixed the regression where the report error dialog did not react to clicks to go to the position where a traceback had occurred.
Fixes #
=> PR: Fix issue with the report dialog that prevented to click on the traceback error

spyder/plugins/completion/plugin.py, spyder/plugins/completion/providers/fallback/provider.py, spyder/plugins/completion/providers/snippets/actor.py, spyder/plugins/completion/providers/snippets/provider.py, spyder/plugins/completion/providers/snippets/tests/test_snippets.py
This PR prevents snippet completion results to appear before fallback ones.
Fixes #
=> PR: Send snippets provider completion results to last

spyder/plugins/completion/api.py, spyder/plugins/completion/plugin.py, spyder/plugins/completion/providers/kite/provider.py, spyder/plugins/completion/providers/languageserver/provider.py, spyder/plugins/completion/providers/snippets/actor.py, spyder/plugins/editor/widgets/tests/conftest.py
This PR prevents starting the completion timeout timer when only a single slow completion provider (e.g., lsp and kite) is running. 
Fixes #
=> PR: Prevent completion timeouts when a single slow provider is up

spyder/app/tour.py, spyder/plugins/completion/providers/kite/widgets/install.py
This PR fixes hover and pressed states of buttons in tour and kite dialog to match the style of the rest of the buttons in the interface.
Fixes #
Juanis2112
=> PR: Fix hover and pressed states of buttons in Tour and Kite dialog

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/utils/nsview.py, external-deps/spyder-kernels/spyder_kernels/utils/tests/test_nsview.py, spyder/plugins/variableexplorer/widgets/importwizard.py, spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py, spyder/widgets/collectionseditor.py
This uses the group colors defined in the new Spyder palette to represent different kinds of objects in the Variable Explorer.
Fixes spyder-ide/ux-improvements#7
=> PR: Use group colors for objects in the Variable Explorer

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/CHANGELOG.md, external-deps/spyder-kernels/RELEASE.md, external-deps/spyder-kernels/setup.py, external-deps/spyder-kernels/spyder_kernels/_version.py
- This syncs our 5.x branch with the new 2.x branch in spyder-kernels.
- This is also necessary to avoid showing our Dependencies dialog when running Spyder from `bootstrap.py`.
=> PR: Sync spyder-kernels subrepo with the 2.x branch

spyder/utils/stylesheet.py
We thought this problem only happened on macOS, but it was really caused by old PyQt versions (i.e. less than 5.12).
Fixes #15116.
=> PR: Increase padding in checkboxes for old PyQt versions

spyder/plugins/history/widgets.py, spyder/utils/stylesheet.py
- Remove top border around corner widgets for the Editor and IPython console.
- Remove 1px border between tabbar and pane for selected tabs in those panes too.
**Before**
**After**
- Make corner widgets in History to have the right height
**Before**
**After**
=> PR: Improve the style of tabs

spyder/plugins/layout/container.py
The call to save the layout was missing the `_plugin` (since the logic is in the plugin)
Fixes #15129 
=> PR: Fix call to plugin method when saving a custom layout

.github/scripts/modules_test.sh, spyder/api/__init__.py, spyder/api/_version.py, spyder/api/config/mixins.py, spyder/plugins/layout/plugin.py
- Fix crash at startup when Spyder is closed in a secondary screen, that screen is unplugged and then Spyder is opened in the primary screen.
- Add `get_conf_default` method to `SpyderConfigurationAccessor` to make that fix easier.
- Start to version our API to let developers know about additions or removals.
=> PR: Fix a crash at startup when switching screens

spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/outlineexplorer/widgets.py
This PR fixes some issues where some invalid keywords were passed to initialize the outline explorer on the separate editor main window.
Fixes #15104 
=> PR: Fix OutlineExplorerWidget creation on separate editor window

.github/scripts/install.sh, spyder/app/mainwindow.py
The old API plugins call the mainwindow instance to provide the switch to plugin functionality, maximize/restore panes
Fixes #15164 
=> PR: Add maximize_dockwidget method for old API compatibility (mainwindow)

spyder/app/mainwindow.py, spyder/app/utils.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py, spyder/utils/icon_manager.py
- Make style of Object Explorer tool buttons match the one of pane toolbars:
- Add padding to checkboxes in Object Explorer options menu, so they don't overlap the text:
- Use QDarkstyle palette for the color of links
- Change color of `exit` icon to main color so it has more contrast in the dark theme:
Fixes #15148 
Fixes #15146
=> PR: More style fixes

spyder/plugins/editor/widgets/editor.py, spyder/utils/stylesheet.py, spyder/widgets/tabs.py
- Move editor's spinner to be next to the filename label. This gives more space in the tabbar for 
- Fix tabbar scroller buttons style:
**After**
**Before**
- Fix ordering of imports in `plugins/editor/widgets/editor.py`
=> PR: Fix style of the tabbar scroller buttons

spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/control.py, spyder/widgets/collectionseditor.py
- Restore the ability to go the error line in the editor after clicking on the corresponding line in a console traceback.
- Don't use Qt4Agg as Matplotlib backend in the Variable Explorer.
Fixes #15166.
=> PR: Fix traceback links in the IPython console

NOTICE.txt, spyder/app/mainwindow.py, spyder/app/utils.py, spyder/plugins/editor/widgets/editor.py, spyder/widgets/tabs.py
- Remove most small white dots around toolbuttons in tabwidgets:
**Before**
**After**
- Remove 1px margin between new top toolbar in the editor and tabwidget.
- Add entry in `NOTICE.txt` about the code we're using from QDarkstyle
- Update message we show when the screen DPI changes.
=> PR: Remove most small white dots around toolbuttons in tabwidgets

spyder/plugins/layout/api.py
Following #15177 if a dockable plugin is pruned and it's used to define an area for a layout (for example the Outline Explorer) the related area should not be taken into account when applying the layout. Prevents seeing errors like the following when a plugin is pruned:
```
File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\plugins\layout\container.py", line 125, in <lambda>
triggered=lambda: self.quick_layout_switch('default'),
File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\plugins\layout\container.py", line 393, in quick_layout_switch
possible_current_layout = self._plugin.quick_layout_switch(index)
File "C:\Users\Daniel\Documents\Spyder\spyder\spyder\plugins\layout\plugin.py", line 320, in quick_layout_switch
self.setup_default_layouts(index, …
```
=> PR: Update layout setup to discard areas where the base plugin doesn't exists

spyder/plugins/plots/widgets/main_widget.py
Plots uses some logic to disable actions when no plot is available. In the validation to enable/disable actions base actions need to be skipped.
=> PR: Add base plugin actions to validation (to not disable them) - Plots

pytest.ini, scripts/spyder_win_post_install.py, spyder/app/mainwindow.py, spyder/app/solver.py, spyder/app/tests/test_mainwindow.py, spyder/dependencies.py, spyder/plugins/completion/plugin.py, spyder/plugins/console/tests/test_plugin.py, spyder/plugins/console/widgets/console.py, spyder/plugins/console/widgets/main_widget.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/requirements.py, spyder/utils/programs.py
- Remove usage of `distutils` except in our `setup.py`.
- Don't register completion providers with the same name several times. That will avoid people replacing our current providers for theirs.
- Update check of spyder-kernels version
- Avoid showing warnings in our error report dialog.
- Fix reporting errors to external repos for external plugins.
Fixes #15093.
=> PR: Remove usage of distutils

spyder/plugins/plots/widgets/main_widget.py, spyder/plugins/toolbar/container.py
The Plots toggle view action was missing the skip to not be disabled and the show/hide toolbars action was not working as expected.
=> PR: Fix update of plots toggle view and show/hide toolbars actions

spyder/api/widgets/auxiliary_widgets.py, spyder/api/widgets/main_widget.py
In this PR, I propose that we make `MainCornerWidget` inherit from `QToolBar` instead of `QWidget` so that we can set more easily a style that is consistent with that of the `MainWidgetToolbar` .
I also suggest to add a strut to the corner widget so that there is a space between the last item of the `MainWidgetToolbar` and the first item of the corner widget.
- there is no space to the left of the spinner
- the space to the right of the spinner is too large (though it is very subtle)
I certify the above statement …
=> PR: Minor layout improvements to the cornet widget of the panes toolbar

spyder/plugins/ipythonconsole/utils/ssh.py
Spyder was freezing if the other end of the tunnel asks for a passphrase instead of a password.
Fixes #15388.
=> PR: Add passphrase to the text expected by ssh tunnels (IPython console)

spyder/app/mainwindow.py, spyder/plugins/editor/plugin.py
The change in the load of the plugins affected the non-migrated `Edit` menu
Fixes #15394 
=> PR: Add missing actions in the Edit menu

binder/environment.yml, pytest.ini, requirements/tests.txt, setup.py, spyder/app/tests/test_cli_options.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/providers/kite/utils/tests/test_install.py, spyder/plugins/completion/providers/languageserver/tests/test_client.py, spyder/plugins/completion/tests/test_plugin.py, spyder/plugins/editor/widgets/tests/test_classfunc_selector.py, spyder/plugins/editor/widgets/tests/test_completions_hide.py, spyder/plugins/editor/widgets/tests/test_editor_and_outline.py, spyder/plugins/editor/widgets/tests/test_editorsplitter.py, spyder/plugins/editor/widgets/tests/test_folding.py, spyder/plugins/editor/widgets/tests/test_formatting.py, spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/plugins/editor/widgets/tests/test_warnings.py, spyder/plugins/explorer/widgets/tests/test_explorer.py, spyder/plugins/explorer/widgets/tests/test_fileassociations.py, spyder/plugins/findinfiles/tests/test_plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/plots/widgets/tests/test_plots_widgets.py, spyder/utils/tests/test_encoding.py, spyder/utils/tests/test_programs.py
pytest-ordering is not maintained and broken:
https://github.com/ftobia/pytest-ordering/issues/73
This PR removes it. Tests should be written in a way that they are independent of each other.
Alternatively, if the order of tests is really needed, you may consider using forked and maintained https://github.com/pytest-dev/pytest-order with more concise mark names.
=> PR: Remove unmaintained pytest-ordering package

spyder/plugins/plots/plugin.py
plots plugin doesn't switch without this
Fixes #15411.
=> PR: Fix showing plots for different consoles in Plots

spyder/config/base.py
This change puts ``sys.prefix`` on the config search path. With this change we have the option of providing a centrally managed spyder installation which can be pre-configured without setting global (machine-wide) config.
The use case that this comes from:
> I want to be able to provide a spyder installation to a large number of users (200+) who have all got a specific NFS drive mounted on their Linux (Centos) machines. I therefore cannot setup a config in ``/etc/``, and cannot control the user's ``~/.config``; I therefore want to be able to put a config in ``{sys.prefix}/etc/spyder/spyder.ini`` and it affect the global config (which can be overridden by the user config, should a user so choose).
In my case, I wanted to provide a spyder installation which is pre-configured to use a …
=> PR: Put the sys.prefix in the config search path

spyder/plugins/completion/plugin.py
This PR checks that a response for a non-aggregated completion request (e.g., folding, symbols, etc) is not empty.
Fixes #15139 
=> PR: Fix issues with empty responses for non-aggregated completion requests

spyder/app/tests/test_mainwindow.py, spyder/plugins/plots/plugin.py
- Don't switch to Plots automatically when the `Mute inline plotting` option is deactivated.
- Skip a test that fails for IPython 7.23 and ipykernel 5.5.3. I'll submit a PR to ipykernel to fix it.
Fixes #15467.
=> PR: Only switch to Plots when inline plotting is muted

spyder/app/mainwindow.py, spyder/plugins/help/widgets.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
Part of the IPython Console migration
=> PR: Move css_path to Appearance config section (IPython Console)

installers/Windows/req-extras-pull-request.txt, installers/Windows/req-extras-release.txt, installers/Windows/req-pull-request.txt, installers/Windows/req-release.txt
`rtree >= 0.9.7` has proper wheels in PyPI
Depends on https://github.com/spyder-ide/spyder/pull/14496
Part of https://github.com/spyder-ide/windows-installer-assets/issues/1
=> PR: Remove rtree wheel from Windows installer extra packages

spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/control.py
It was not possible to scroll the pager content using Page up/down or the up/down arrow keys.
=> PR: Scroll pager content with keys (IPython console)

spyder/app/mainwindow.py
See issue #15692 for description.
The `path` file in the spyder configuration directory, which holds the user provided paths added with the PYTHONPATH manager is not read with correct encoding, and thus not allowing for unicode characters in the paths (e.g. 'ö'). The current read functionality is handled by `encoding.readlines()`, with subsequent calls to `encoding.read()`,` encoding.decode()`, `encoding.get_coding()` which finally calls `chardet.UniversalDetector()`. `chardet` returns (at least sometimes) the wrong encoding as per issue #15692. 
Other fixes were considered
- write BOM to the path file to make sure `chardet` detects utf-8. Using BOM with utf-8 appears, however, to be generally discourages (https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-u …
=> PR: Force reading of path stored in Spyder configuration folder as utf-8

spyder/app/mainwindow.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/mainmenu/plugin.py
Move mainmenu actions registration for IPython Console inside the plugin
=> PR: Initial reorganizations of IPython Console actions for the mainmenu

spyder/plugins/editor/utils/editor.py
This shows up after editing some text and then trying to highlight the block.
Fixes #15712
=> PR: Catch another KeyError when trying to highlight a folding block (Editor)

external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/macos-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
I decided to override a comms method in our kernel to not show that warning once and for all.
Fixes #15498.
I certify the above statement is true and correct: @ccordoba12.
=> PR: Avoid showing "No such comms" warning when restarting the kernel (IPython console)

.github/scripts/install.sh
IPython 7.24.0 broke our debugger, which should be fixed by PR https://github.com/ipython/ipython/pull/12999. Until then, we need to run our tests with a lower version.
=> PR: Install IPython 7.23 until debugger issues are solved (Testing)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/utils.py
This fixes the `pkgs` directory detection in our Windows installer.
Fixes #15417.
=> PR: Sync subrepo with spyder-kernels#298

binder/environment.yml, requirements/tests.txt, setup.py
`pytest-qt` 4.0.0 makes the test fail
=> PR: Add restriction to pytest-qt to be < 4.0

spyder/plugins/completion/providers/languageserver/provider.py
This was missing in PR #15657. Without it Spyder was trying to load the previous `pyls` server when moving from a 5.0.4 settings to 5.x, master or the upcoming 5.1.0.
=> PR: Bump CONF_VERSION after move to pylsp server (Completions)

spyder/plugins/explorer/widgets/explorer.py
That functionality was broken after the release of Spyder 5.
Fixes #15458.
=> PR: Fix VCS browse and commit functionality (Files)

spyder/plugins/onlinehelp/pydoc_patch.py
Just use a absolute URL for style sheets.
Can't test new code because of dependencies problems.
Fixes #15847 
@Virinas-code
=> PR: Fix error in link to css files (Online Help)

.github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, spyder/config/gui.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/onlinehelp/widgets.py, spyder/utils/stylesheet.py, spyder/widgets/browser.py
We were not drawing borders around WebView widgets such as the ones used in Help and Online Help.
**Before**
**After**
Other changes include:
* Paint the border with an accent color when it has focus.
* Fix layout for Online Help main widget.
* Prevent to give focus to WebView widgets only for old PyQt versions (5.12+ doesn't have this problem).
* Make tests run for any `5.*` branch.
=> PR: Add border around WebView widgets

spyder/api/config/mixins.py, spyder/config/main.py, spyder/plugins/ipythonconsole/utils/kernelspec.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/debugging.py, spyder/plugins/ipythonconsole/widgets/kernelconnect.py, spyder/plugins/ipythonconsole/widgets/shell.py, spyder/plugins/ipythonconsole/widgets/tests/test_kernelconnect.py, spyder/plugins/shortcuts/tests/test_shortcuts.py, spyder/plugins/variableexplorer/widgets/dataframeeditor.py
Move IPython Console widgets and other components to use the `SpyderConfigurationAccessor` instead of using `CONF` directly
=> PR: Make IPython Console widgets and other elements to use the SpyderConfigurationAccessor

spyder/plugins/editor/widgets/codeeditor.py
This avoids displaying those message several times on hover.
Fixes #15618.
=> PR: Don't add linting messages to block data for cloned editors (Editor)

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_warnings.py
`# noqa`, `# NOQA` and `# analysis:ignore` inline comments are supported now.
**Before**
**After**
Fixes #11033.
=> PR: Restore ability to ignore linting messages with inline comments (Editor)

spyder/plugins/projects/plugin.py, spyder/plugins/projects/tests/test_plugin.py
* When switching projects, project close emit will call `editor.setup_open_files` only when not switching projects.
* Removed redundant code in `create_new_project`. This lead to multiple unnecessary calls to `sig_project_closed.emit` and `restart_consoles`.
* Removed unnecessary test for project close signal on create new project. This test fails because a project `root_path` is not set in the mocked dialogue window so a project is not _actually_ created and the active project is not closed. This test is unnecessary since `create_new_project` should not send `sig_project_closed.emit`, which is sent in `open_project` (if switching projects) or the `close_project` and is already tested.
Fixes #14787
I affirm the [Developer …
=> PR: Fix extraneous reloading documents on project switching

spyder/config/gui.py, spyder/plugins/appearance/confpage.py
The detection of the current interface theme was broken after the release of Spyder 5, so we couldn't ask for a restart when needed.
Fixes #15904.
=> PR: Fix asking for restart when changing interface theme options (Appearance)

spyder/plugins/application/container.py, spyder/plugins/application/plugin.py, spyder/plugins/ipythonconsole/widgets/shell.py, spyder/widgets/helperwidgets.py
* Move that check to the `on_mainwindow_visible` method of the Application plugin.
* Add a small delay before running that check to prevent showing it before the window is really up.
* Make all usages of `MessageCheckBox` to be non-modal to avoid interrupting users as much as possible.
Fixes #15839
=> PR: Move check for possible updates after the main window is visible (Application)

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py, spyder/widgets/mixins.py
Replace the ``toPlainText`` method used to get the text to use in LSP Requests  with ``get_text_with_eol`` that corrects the ``toPlainText`` EOL. This fixes the wrong position returned by the Language Servers when a document has line endings different from line feed.
Modify ``get_text_with_eol`` to replace LF with correct document EOL and keep the same string encoding as ``toPlainText``.
Fixes #15900
=> PR: Fix Wrong EOL in  LSP Requests text

spyder/plugins/editor/extensions/snippets.py
This simply avoids inserting snippets when a necessary variable for them is `None`.
Fixes #15960
=> PR: Catch error in snippets extension (Editor)

binder/environment.yml, requirements/tests.txt, setup.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/providers/fallback/tests/conftest.py, spyder/plugins/completion/providers/languageserver/tests/conftest.py, spyder/plugins/completion/providers/snippets/tests/conftest.py, spyder/plugins/completion/tests/conftest.py, spyder/plugins/findinfiles/tests/test_plugin.py, spyder/plugins/history/tests/test_plugin.py, spyder/plugins/workingdirectory/tests/test_workingdirectory.py
This reverts #15782 and fixes the reason why pytest-qt was pinned: qtbot.addWidget() expects a widget as argument, but a few plugins were not widgets.
I certify the above statement is true and correct: @bnavigator
=> PR: Fix compatibility with pytest-qt >= 4

spyder/app/mainwindow.py, spyder/app/utils.py
This is a small refactoring that moves those self-contained functions out of `mainwindow.py`
=> PR: Move create_application and create_window to utils (Main window)

spyder/plugins/editor/widgets/tests/conftest.py, spyder/widgets/mixins.py
- We were not preserving EOLs when saving files.
- This was broken after PR #15903
=> PR: Fix getting text with end-of-lines (Editor)

spyder/plugins/ipythonconsole/widgets/shell.py
- The problem was I made non-modal the warning dialog we show to inform users that variables are going to be removed. And that changed the way we need to handle the reset, which is done in this PR.
- This was broken after the changes I made in PR #15988.
=> PR: Fix resetting variables after clicking on the reset button (IPython console)

spyder/plugins/plots/plugin.py, spyder/plugins/plots/widgets/figurebrowser.py, spyder/plugins/plots/widgets/main_widget.py
- This avoids raising the plugin when users have focus on other plugins.
- It also fixes the issue with the thumbnail scrollbar size not being correctly at startup.
Fixes #15705
=> PR: Only switch to Plots plugin once per session

spyder/api/plugin_registration/registry.py, spyder/api/plugins.py, spyder/api/widgets/menus.py, spyder/api/widgets/mixins.py, spyder/app/mainwindow.py, spyder/plugins/application/api.py, spyder/plugins/application/container.py, spyder/plugins/application/plugin.py, spyder/plugins/completion/plugin.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/tests/test_editor_config_dialog.py, spyder/plugins/help/plugin.py, spyder/plugins/layout/plugin.py, spyder/plugins/toolbar/plugin.py, spyder/plugins/tours/container.py, spyder/plugins/tours/plugin.py, spyder/preferences/__init__.py
- After #15582, several menus had missing entries or their layouts were not correct.
- Remove the `Debug with Winpdb` action from the Debug menu, because we don't need an external debugger anymore.
=> PR: Fix layout and missing entries in main menus

spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/tests/test_hints_and_calltips.py
- Hovers were displayed with no content at all, which was very annoying.
- I think this was a regression after the migration to the new API, which was not caught by our tests.
Fixes #16079.
=> PR: Don't try to display hovers when there's no content to display (Editor)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/README.md, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/outstream.py, external-deps/spyder-kernels/spyder_kernels/console/start.py, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py
- This makes the `isatty` attribute of the `OutStream` instance in our kernel to return `True`, which adds out of the box support for Rich and Colorama in our consoles.
- It also makes `os.get_terminal_size` to return a proper value in our consoles.
Associated PRs:
- Depends on spyder-ide/spyder-kernels#306
- Depends on spyder-ide/spyder-kernels#305
Fixes #1917.
=> PR: Support Rich and Colorama in the IPython console

external-deps/python-lsp-server/.gitrepo, external-deps/python-lsp-server/CONFIGURATION.md, external-deps/python-lsp-server/pylsp/config/schema.json, external-deps/python-lsp-server/pylsp/plugins/definition.py, external-deps/python-lsp-server/pylsp/plugins/hover.py, external-deps/python-lsp-server/test/plugins/test_definitions.py, external-deps/python-lsp-server/test/plugins/test_hover.py, external-deps/python-lsp-server/test/test_language_server.py
- Those features were broken since we migrated to the LSP architecture.
- Depends on python-lsp/python-lsp-server#62
Fixes #15400
Fixes #13358
=> PR: Make go-to-defintion and hover work for files when no project is active or outside of it (Completions)

spyder/config/main.py, spyder/plugins/explorer/confpage.py, spyder/plugins/explorer/widgets/explorer.py
- Filters were blank since Spyder 5.0 due to a wrong `set_conf` call that made them like so.
- This also avoids setting default values for other options in Files and Projects, which will prevent us from changing those values in the future.
Fixes #15459.
=> PR: Fix setting filters in Files

spyder/plugins/completion/providers/kite/utils/status.py
This prevents Spyder from hanging when that url can't be accessed for some reason.
Fixes #16064.
=> PR: Add a timeout when doing a request to Kite url installers

external-deps/python-lsp-server/.gitrepo, external-deps/python-lsp-server/CONFIGURATION.md, external-deps/python-lsp-server/pylsp/config/schema.json, external-deps/python-lsp-server/pylsp/plugins/symbols.py, external-deps/python-lsp-server/pylsp/python_lsp.py, external-deps/python-lsp-server/pylsp/workspace.py, external-deps/python-lsp-server/test/test_language_server.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/providers/languageserver/client.py, spyder/plugins/outlineexplorer/plugin.py, spyder/plugins/outlineexplorer/widgets.py, spyder/plugins/projects/plugin.py
- Symbols were not shown for files in projects when an `__init__.py` file is present at the root of the project.
- Symbols were not updated when switching projects.
- Don't send requests to the LSP server before it's been initialized (this was not compliant with the LSP protocol).
- Remove from `sys.path` entries that come from our config system when passed to the LSP server and transport layer, and Spyder is running in dev or testing modes. That allows us to better test things in those modes.
- Depends on python-lsp/python-lsp-server#53
Fixes #15648 
Fixes #14871 …
=> PR: Fix several issues with the Outline

spyder/api/widgets/mixins.py, spyder/app/mainwindow.py, spyder/plugins/application/container.py, spyder/plugins/application/plugin.py, spyder/plugins/console/widgets/main_widget.py, spyder/plugins/mainmenu/plugin.py, spyder/plugins/preferences/widgets/container.py
- This correctly positions actions with a menu role in Mac's menu bar.
- Also, add a `menurole` kwarg to the `create_action` method of `SpyderActionMixin`.
- Remove unnecessary check for MainMenu in Application.
Fixes #14917
=> PR: Pre-render menus when main window is visible on macOS

.github/scripts/install.sh, conftest.py, setup.cfg, spyder/app/find_plugins.py, spyder/app/tests/test_find_plugins.py, spyder/config/base.py, spyder/dependencies.py, spyder/plugins/completion/providers/languageserver/client.py, spyder/plugins/editor/panels/tests/__init__.py, spyder/plugins/editor/utils/tests/__init__.py, spyder/plugins/editor/widgets/tests/assets/autopep8_range.py, spyder/plugins/editor/widgets/tests/assets/autopep8_result.py, spyder/plugins/explorer/tests/__init__.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/ipythonconsole/utils/kernelspec.py, spyder/plugins/ipythonconsole/utils/tests/test_spyder_kernel.py, spyder/plugins/ipythonconsole/widgets/tests/__init__.py, spyder/plugins/ipythonconsole/widgets/tests/test_kernelconnect.py, spyder/plugins/onlinehelp/tests/__init__.py, spyder/plugins/outlineexplorer/tests/__init__.py, spyder/plugins/plots/widgets/tests/__init__.py, spyder/plugins/pylint/tests/__init__.py, spyder/plugins/variableexplorer/tests/__init__.py, spyder/widgets/github/tests/test_github_backend.py, spyder/workers/tests/__init__.py
- Internal plugins were not detected correctly when the package was not installed but running from git.
- This generated a crash at startup that went undetected before releasing 5.1.0.
- That's why I also took the opportunity to make the necessary changes to run our tests as if the package were installed. That way we can be sure this won't happen again.
Fixes #16136
Fixes #16117
=> PR: Fix loading internal plugins and run tests as if the package were installed in our CIs

spyder/plugins/editor/widgets/codeeditor.py
- Now we pass on empty responses, instead of passing them to the completion widget.
- We also catch the usual errors that can happen with any response.
Fixes #16125 
=> PR: Improve how we handle responses of completion item resolution (Editor)

runtests.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/panels/tests/test_scrollflag.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/editor/widgets/tests/test_goto.py, spyder/plugins/editor/widgets/tests/test_introspection.py, spyder/plugins/editor/widgets/tests/test_shortcuts.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/maininterpreter/widgets/tests/test_status.py, spyder/plugins/shortcuts/tests/test_shortcuts.py, spyder/utils/tests/test_conda.py, spyder/utils/tests/test_programs.py, spyder/utils/tests/test_pyenv.py, spyder/utils/tests/test_vcs.py, spyder/widgets/tests/test_pathmanager.py
- This just helps us to simplify code around.
- I also removed a test that only applied to Python 2.
=> PR: Use running_in_ci instead of checking for the 'CI' env var directly

spyder/app/tests/test_mainwindow.py, spyder/plugins/completion/providers/fallback/tests/test_fallback.py, spyder/plugins/completion/providers/kite/utils/tests/test_install.py, spyder/plugins/completion/providers/languageserver/provider.py, spyder/plugins/completion/providers/languageserver/tests/test_client.py, spyder/plugins/completion/providers/snippets/tests/test_snippets.py, spyder/plugins/completion/tests/test_configdialog.py, spyder/plugins/completion/tests/test_plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/variableexplorer/widgets/tests/test_arrayeditor.py, spyder/workers/tests/test_update.py
- I did that by removing the `slow` marker from some tests so the rest can run faster.
- This also catches an odd error in `LanguageServerProvider` that only happens when running tests and skip a test on Linux because it fails too often.
=> PR: Improve running time of slow tests

spyder/app/cli_options.py, spyder/app/start.py, spyder/config/base.py
- This is useful to set different configuration directories according to your needs.
- It works like this
spyder --conf-dir <abs-path-or-relative-path>
Fixes #15551 
=> PR: Allow to set a custom configuration directory through the command line

spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/projects/widgets/projectexplorer.py
- Double clicking on a file when single-click mode is active opened it several times.
- That was a regression introduced by #16182. Unfortunately, I only noticed it after that PR was merged.
- Also, don't show VCS directories in Projects.
=> PR: Fix double clicks when single-click mode is active

spyder/utils/programs.py
Added `PYTHONHOME` environment variable to the shell environment when executing a Python script with "Execute in an external system terminal" is selected and using the macOS application.
Environment variables cannot be inherited by the shell environment in the Terminal application, so `PYTHONHOME` must be explicitly set in the executed shell script.
Replaces PR #16199
Fixes #16185
@mrclary
=> PR: Add PYTHONHOME to shell environment when executing in external terminal from macOS app

spyder/plugins/editor/widgets/completion.py, spyder/utils/icon_manager.py
This also scales the icon a bit to better match the size of the others.
**Before**
**After**
=> PR:  Change entry name for file completions to 'file' (Editor)

spyder/plugins/editor/widgets/codeeditor.py
PR #16164 fixed bug #16159, where the indentation of code pasted into the editor was lost.
This failed the border case, when just one line + newline is pasted (https://github.com/spyder-ide/spyder/issues/16159#issuecomment-898484641 ff). This PR solves this by calculating the list of indentation and then only uses this list, if it is not empty.
Fix an issue found after merging PR #16164.
sphh
=> PR: Solves pasting of one line + newline into the editor

spyder/plugins/editor/widgets/codeeditor.py
Code formatting with Autopep8 or Black was introducing errors for files with line endings other than LF.
Fixes #16180.
=> PR: Use toPlainText to get the file's text when applying formatting (Editor)

spyder/api/widgets/main_widget.py, spyder/api/widgets/menus.py, spyder/api/widgets/mixins.py, spyder/app/mainwindow.py, spyder/plugins/application/plugin.py, spyder/plugins/breakpoints/plugin.py, spyder/plugins/completion/api.py, spyder/plugins/editor/plugin.py, spyder/plugins/findinfiles/plugin.py, spyder/plugins/help/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/layout/plugin.py, spyder/plugins/mainmenu/plugin.py, spyder/plugins/profiler/plugin.py, spyder/plugins/projects/plugin.py, spyder/plugins/pylint/plugin.py, spyder/plugins/shortcuts/plugin.py, spyder/plugins/toolbar/container.py, spyder/plugins/tours/plugin.py, spyder/utils/qthelpers.py
This PR updates the Main Menu plugin methods to exclusively use string identifiers as opposed to using object references when adding items to a specific menu and/or before a given menu item. This is a breaking API change.
Fixes #
=> PR: Use menu and item identifiers to add items to the main menu plugin

spyder/app/restart.py, spyder/app/utils.py
* Wait for a bit when showing the screen so users know that a restart is happening (before the screen was practically not shown).
* Use `create_splash_screen` from `app/utils.py` to show the same screen when starting and restarting.
=> PR: Fix splash screen when restarting Spyder

.github/scripts/install.sh, external-deps/python-lsp-server/.gitrepo, external-deps/python-lsp-server/pylsp/plugins/pylint_lint.py, external-deps/python-lsp-server/pylsp/plugins/symbols.py, external-deps/python-lsp-server/test/test_language_server.py, pytest.ini, spyder/app/tests/script_outline_1.py, spyder/app/tests/script_outline_2.py, spyder/app/tests/script_outline_3.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/plugin.py, spyder/plugins/outlineexplorer/plugin.py, spyder/plugins/outlineexplorer/widgets.py
- The fix in #16111 was not enough to skip all imported symbols from other libraries.
- Expand our tests for the Outline to cover those missing cases.
- Restore the functionality to update the outline for all files after opening/closing a project (I incorrectly removed that in #16111).
- Depends on python-lsp/python-lsp-server#71
=> PR: Improve skipping imported symbols (Outline)

spyder/plugins/editor/widgets/codeeditor.py
Decorations were not updated when the option to underline errors was active but there were no underline errors to decorate in the visible portion of the screen.
Fixes #14268
=> PR: Update decorations whether there are or not underline errors

spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_editor_and_outline.py, spyder/plugins/editor/widgets/tests/test_save.py, spyder/plugins/outlineexplorer/main_widget.py, spyder/plugins/outlineexplorer/plugin.py, spyder/plugins/outlineexplorer/tests/test_widgets.py, spyder/plugins/outlineexplorer/widgets.py
- Move `OutlineExplorerWidget` to be in `plugins/outlineexplorer/main_widget.py`. This is to have a uniform code layout for all dockable plugins.
- Also remove some dead code in `plugins/outlineexplorer/widgets.py`
=> PR: Create main_widget module for the Outline plugin

spyder/plugins/editor/panels/linenumber.py, spyder/widgets/mixins.py, spyder/widgets/simplecodeeditor.py
- Code was not centered when searching for text and the next result was out of the visible region. This fixes that.
- I tested in other editors (e.g. Sublime and VSCode) and that's also their behavior, which is nice because you can view results in context and your sight is always focused on the center of the screen.
- This also removes some dead code for unsupported Qt versions.
=> PR: Center cursor when searching for text (Editor)

external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/macos-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/python-27.txt, external-deps/spyder-kernels/setup.py, external-deps/spyder-kernels/spyder_kernels/py3compat.py, external-deps/spyder-kernels/spyder_kernels/utils/misc.py
- This was a regression introduced PR #15857.
- The solution was memoizing the results of `is_module_installed` in spyder-kernels, so it's only called once to determine if a module is installed.
- Depends on spyder-ide/spyder-kernels#313
Fixes #16247.
=> PR: Prevent slowdowns in the Variable Explorer when Numpy and Pandas are not installed

spyder/plugins/editor/panels/edgeline.py
The vertical line indicating the maximum characters per line (edge line) is shifted 3 units to the right so that it aligns with the characters of the editor.
Current behavior:
Shifting line to the right by 3 units:
This is tested also for other font sizes (7-16) and works well, as well as other standard monospace fonts shipping with Windows.
Why shift by 3?
I tested with 3 first based on this being added to the line number margin https://github.com/spyder-ide/spyder/blob/bb2ed9a6c90df30f370f7f67413d31b363cbfe15/spyder/plugins/editor/panels/linenumber.py#L186
And it works quite well, by chance I suppose. I also tried removing the 3 from the line number margin (without shifting edge line), but this has no effect. 
An alternative solution which also appears to work quite well is to shift the …
=> PR: Shift maximum character edge line to match editor characters

spyder/api/widgets/main_widget.py, spyder/api/widgets/menus.py, spyder/plugins/completion/providers/kite/client.py, spyder/plugins/completion/providers/kite/provider.py, spyder/plugins/completion/providers/kite/utils/install.py, spyder/plugins/completion/providers/kite/widgets/calltoaction.py, spyder/plugins/completion/providers/kite/widgets/install.py, spyder/plugins/completion/providers/kite/widgets/messagebox.py, spyder/widgets/onecolumntree.py
- We have to cover that special case in our API because the External menu section in the Tools menu can be empty, so we can't add another section before that one.
- The same problem can happen for external plugins, but now we raise an informative error about it.
- I also took the opportunity to remove unused imports and variables in several places.
Fixes #16287 
=> PR: Fix error when rendering the Tools menu and Kite is not available

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/start.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py
- That version adds a `runfile` function to `builtins` from the Pydev debugger that shadows our own `runfile`.
- Depends on spyder-ide/spyder-kernels#318
Fixes #16316.
=> PR: Fix error in runfile/debugfile with IPykernel 6.3.0

spyder/plugins/editor/extensions/snippets.py
- It seems Kite returns snippets that can't be processed in our side.
- Since Kite is not supported anymore, we simply catch and pass on them.
Fixes #16358
Fixes #16346 
=> PR: Catch a couple of errors generated by Kite (Snippets)

spyder/api/widgets/main_widget.py, spyder/utils/stylesheet.py
- Adding a popup menu to a button in our main toolbar was showing an arrow to indicate the menu presence. This simply removes it.
- This also moves an style applied to pane toolbars to PanesToolbarStyleSheet.
=> PR: Remove indicator of popup menus in main toolbar

installers/macOS/setup.py
Ensured that `debugpy` is bundled outside zip folder in macOS application.
Fixes #16336
=> PR: debugpy is not zip compatible (macOS app)

spyder/plugins/workingdirectory/container.py
- The working directory didn't have those sizes, so when adding toolbars to its right, it looked like this
Now it looks like this
- I also changed its tooltip to show the current path
=> PR: Set minimum and recommended sizes for the Working directory combobox 

spyder/plugins/completion/confpage.py
- `Show automatic completions after keyboard idle` and `Show completion details after keyboard idle` were not added to the config page of Completion and linting in Spyder 5. This PR restores them.
- This is how they look now:
Part of issue #16342.
=> PR: Restore a couple of completion options lost during the migration (Completions)

.github/scripts/install.sh
CI tests with conda failing due to `jupyter_client` 7.x being available in the conda main channel
=> PR: Add constraint for jupyter_client version on conda based test

spyder/plugins/editor/utils/editor.py, spyder/plugins/editor/widgets/codeeditor.py
- Fix another serious memory leak when underlining errors.
- Stop connecting the `finished` signal of threads that update folding and linting to the same slot over and over again. That was causing a lot of delays after some time.
- Decrease time to update folding and symbols. It's not necessary to have large update times now.
- Remove a list that accumulated BlockUserData for each CodeEditor for no reason.
- Don't compute `get_buffer_block_numbers` for each decoration when underlining errors.
Fixes #16384.
I …
=> PR: Improve linting and folding performance (Editor)

spyder/api/widgets/toolbars.py, spyder/utils/icon_manager.py
- The size and icon of that button were almost imperceptible. This PR aims to improve that.
- Thanks to the new API, this fix will apply to both the main and pane toolbars as well.
**Before**
**After**
=> PR: Improve appearance of toolbar extension button

spyder/api/panel.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/config/manager.py, spyder/config/user.py, spyder/plugins/completion/providers/languageserver/provider.py, spyder/plugins/completion/tests/conftest.py, spyder/plugins/completion/tests/test_configdialog.py, spyder/plugins/console/plugin.py, spyder/plugins/console/tests/test_plugin.py, spyder/plugins/console/widgets/main_widget.py, spyder/plugins/mainmenu/plugin.py, spyder/plugins/preferences/tests/conftest.py, spyder/plugins/pylint/tests/test_pylint.py, spyder/plugins/statusbar/widgets/tests/test_status.py
- Fix tabifying external plugins which are installed after Spyder was installed.
- Fix setting configuration defaults for external plugins without `CONF_DEFAULTS`.
- Remove old attributes that hold a reference to plugin instances. Now that's all handled by the new plugin registration mechanism.
- Prevent internal error when switching layouts.
Fixes #16419.
=> PR: Fix some issues with external plugins

spyder/plugins/projects/utils/watcher.py
Simply catch and pass when the projects watcher can't be started due to `inotify` issues on Linux.
=> PR: Catch error when starting watcher (Projects)

spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/explorer/widgets/tests/test_explorer.py
I think this makes more intuitive to use that option because, thanks to browsers, you know what to expect when clicking on something and the cursor has that shape.
=> PR: Change cursor to pointing hand when single click option is on in Files and Projects

spyder/plugins/help/widgets.py
We were not trying to load url's using the webview widget of the RichText one in Help.
Fixes #16477.
=> PR: Fix error when loading urls (Help)

.github/scripts/install.sh, .github/workflows/test-files.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, CONTRIBUTING.md, binder/environment.yml, requirements/conda.txt, spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/widgets/tests/test_editor.py, spyder/plugins/editor/widgets/tests/test_editor_and_outline.py, spyder/plugins/outlineexplorer/tests/test_widgets.py, spyder/plugins/variableexplorer/widgets/tests/test_arrayeditor.py, spyder/tests/test_dependencies_in_sync.py
- Installing from conda-forge is necessary to add new binary dependencies to Spyder which are not available in the `defaults` channels (e.g. `jellyfish`).
- This also helps to test that our core deps (`spyder-kernels` and `python-lsp-server`) are in sync with our other installation methods (i.e. `setup.py` and Binder).
=> PR: Use conda-forge and mamba for testing

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/start.py, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- This was broken because `debugpy` (a new dependency since IPykernel 6) registers its own breakpoint hook.
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/322. This makes `sys.breakpointhook` to simply be `pdb.set_trace`.
Fixes #16444.
=> PR: Add a test to check that the breakpoint builtin is working

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/CHANGELOG.md, external-deps/spyder-kernels/setup.py, external-deps/spyder-kernels/spyder_kernels/console/kernel.py, external-deps/spyder-kernels/spyder_kernels/console/shell.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/namespace_manager.py, external-deps/spyder-kernels/spyder_kernels/customize/spydercustomize.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
=> PR: Sync subrepo with spyder-kernels#327

spyder/plugins/explorer/widgets/explorer.py
- In some circumstances the pointing hand cursor is shown when single click to open is not active.
- This could help to solve that problem. However, I'm not really sure it does because this bug is really hard to reproduce.
=> PR: Try to fix bug when setting cursor shape for single click to open (Files/Projects)

spyder/widgets/browser.py
It seems this problem appears only in older PyQt versions (i.e. 5.9)
Fixes #16703.
=> PR: Catch error when trying to install event filter in WebView widget

spyder/plugins/projects/widgets/main_widget.py
Minor patch to improve compatibility with PySide.
rear1019
=> PR: PySide - Do not pass `None` to QTreeView.setExpanded() (prevents a TypeError)

spyder/api/config/mixins.py, spyder/api/plugins/new_api.py, spyder/api/widgets/main_widget.py, spyder/api/widgets/mixins.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/config/appearance.py, spyder/config/main.py, spyder/config/manager.py, spyder/plugins/appearance/confpage.py, spyder/plugins/console/widgets/main_widget.py, spyder/plugins/editor/plugin.py, spyder/plugins/help/plugin.py, spyder/plugins/ipythonconsole/confpage.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipython_config_dialog.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/utils/kernelspec.py, spyder/plugins/ipythonconsole/widgets/__init__.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/debugging.py, spyder/plugins/ipythonconsole/widgets/main_widget.py, spyder/plugins/ipythonconsole/widgets/shell.py, spyder/plugins/layout/plugin.py, spyder/plugins/shortcuts/tests/test_shortcuts.py
IPython Console to Spyder 5 plugin API
Supersedes #12749 #15934 
Depends on #15922
=> PR: Migrate the IPython Console to the new API

spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
- I don't understand why but sometimes when we try to display an image through the Variable Explorer, Spyder throws an error saying that ArrayEditor is not defined.
- This avoids that error by reimporting ArrayEditor before using it.
Fixes #16731
=> PR: Reimport ArrayEditor when displaying PIL images to avoid error (Variable Explorer)

spyder/plugins/projects/plugin.py
The main reason was the kwarg flag for `open_project` inside `reopen_last_project` being `False`.
Also, seems like the logic to reopen projects is still inside the mainwindow (not sure if that should be changed too).
Fixes #16748
=> PR: Allow console restart when reopening projects at startup

spyder/config/main.py
The previous shortcut was interfering with the one used in Czech and Hungarian keyboards to get brackets.
Fixes #15654.
=> PR: Change keyboard shortcut for "Find in files" action in the Search menu

spyder/app/tests/test_mainwindow.py
- `test_mainwindow.py::test_path_manager_updates_clients` started to fail too much on Mac, which makes our test suite to take too long to finish or not finish at all.
=> PR: Skip a test that became too flaky on Mac

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, spyder/app/tests/test_mainwindow.py
- Sync our spyder-kernels subrepo with https://github.com/spyder-ide/spyder-kernels/pull/335.
- This also skips a test on Mac because it became too flaky.
Fixes #16790.
=> PR: Fix inconsistent behavior when running list comprehensions in the debugger

spyder/app/mainwindow.py, spyder/plugins/editor/plugin.py, spyder/plugins/history/plugin.py, spyder/plugins/history/tests/test_plugin.py, spyder/plugins/ipythonconsole/plugin.py
- Spyder was crashing after turning off several plugins (e.g. Help, Shortcuts or the Editor). This should fix most of those errors.
- Add teardown methods to the IPython console to be able to turn it off. They were missing after #16324.
=> PR: Fix crashes when certain plugins are not available

installers/macOS/req-build.txt
Constrain IPython<7.28.0 for macOS installer only, until #16651 can be merged.
Fixes #16828
@mrclary
=> PR: Constrain IPython to be less rhan 7.28.0 for macOS installer

spyder/utils/icon_manager.py
This changes the icon used for text completions so it's visually different from the ones corresponding to LSP symbols.
**Before**
**After**
=> PR: Use a different icon for text completions

spyder/plugins/ipythonconsole/widgets/main_widget.py
=> PR: Fix some issues after the IPython Console migration

spyder/plugins/projects/api.py, spyder/plugins/projects/widgets/projectdialog.py, spyder/plugins/projects/widgets/tests/test_projectdialog.py
- Add message to explain users how to use that dialog.
- Validate selected directories and show a message about why a project can't be created at a particular location.
- Disable `Create` button when validation doesn't pass.
- Make that pressing `Enter` selects `Create` when validation pass.
- Make dialog to auto-resize when content is hidden.
- Remove unnecessary empty space.
**Before**
**After**
Fixes #16745.
=> PR: Improve the "Create new project" dialog (Projects)

spyder/app/tests/test_mainwindow.py
- It seems that that test hangs with the latest Matplotlib (3.5.0)
- This is a much better solution than the one I came up with in #16845.
=> PR: Don't use Matplotlib in a test to prevent hangs

installers/macOS/req-build.txt, spyder/plugins/ipythonconsole/widgets/client.py
With #14025 the critical logging message from `pydevd` no longer causes the installer test to fail, but is still briefly displayed in the IPython console. This PR filters this message for both the installer test and IPython console display.
Fixes #16828
=> PR: Filter 'This version of python seems to be incorrectly compiled...' pydev_log.critical message

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py
- We were not running both handlers correctly, which (for instance) was preventing `nest_asyncio` to do its job.
- Depends on spyder-ide/spyder-kernels#317
Fixes #16863.
=> PR: Run asyncio and normal handlers in the kernel (IPython console)

.github/scripts/modules_test.sh, spyder/plugins/findinfiles/widgets/main_widget.py, spyder/plugins/findinfiles/widgets/results_browser.py, spyder/plugins/findinfiles/widgets/search_thread.py, spyder/plugins/findinfiles/widgets/tests/test_widgets.py, spyder/plugins/outlineexplorer/widgets.py, spyder/plugins/pylint/main_widget.py, spyder/widgets/onecolumntree.py
* The panes that use that widget are Outline, Find and Code Analysis.
* Change mouse shape to pointing hand when hovering over tree elements
* Collapse tree roots with a single click
* Show horizontal scrollbar if content is too wide
* Showing a background color when hovering entries in Find (before we were not showing any color).
=> PR: UX improvements to panes that inherit from OneColumnTree widget

spyder/api/plugin_registration/registry.py, spyder/api/widgets/auxiliary_widgets.py, spyder/api/widgets/main_widget.py, spyder/app/mainwindow.py, spyder/app/tests/test_mainwindow.py, spyder/config/base.py, spyder/plugins/base.py, spyder/plugins/help/plugin.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
* The position and size of undocked plugins is saved when they are docked back to the main window. This allows us to restore those attributes when they are undocked again.
* If a plugin is undocked when the main window was closed, we restore it as undocked in the next session.
Fixes #16216 
Fixes #10649 
=> PR: Save and restore geometry of undocked plugins

spyder/dependencies.py, spyder/plugins/application/container.py, spyder/widgets/reporterror.py
- Dependencies were not added to a Github issue reported directly from Spyder.
- The dependencies dialog appeared as empty if displayed before the thread that computes dependencies has finished.
=> PR: Fix some issues with dependencies

spyder/plugins/editor/extensions/docstring.py
There are expressions, that are syntactically valid, but don't get recognized by the docstring generator.
This should allow it to work with more kinds of line breaks, handle empty lines in brackets and allows for string literal metadata in returned annotated.
This is mostly done by changing the way an end of a function definition is detected. It now, does not just search for a line ending with ":" but it now searches backwards in lines ignoring whitespace and skipping over empty lines if they are in brackets until a line end is found. A line end is defined by it ending with "):" or "]:" or ending with ":" and containing "->"
Fixes #14520
Fixes #14521 …
=> PR: Fix issues with docstring generation

spyder/api/config/decorators.py, spyder/api/preferences.py, spyder/plugins/completion/plugin.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/preferences/api.py
- Applying any option to the editor required a restart. This was probably caused by the changes in #16012.
- Applying options that are set through the Completion preferences page was also broken. I think this is another side effect of #16012.
- Improve performance when automatic completions are off.
- Remove unused imports in several places.
Fixes #16439.
Fixes #14188.
=> PR: Fix applying configuration options to the editor

MAINTENANCE.md, RELEASE.md, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/main_widget.py, spyder/plugins/ipythonconsole/widgets/shell.py
* Add more info to the RELEASE file. Update MAINTENANCE file (was using `4.x` in the commands).
* Change spyder-kernels version message structure to be translated properly (and fix missing outdated installation commands). New message: 
Also while checking this seems like an error raises when closing a client if no kernel is started (due for example not having the correct version of  `spyder-kernels` installed):
```
File "D:\Acer\Documentos\Spyder\spyder\spyder\plugins\ipythonconsole\widgets\main_widget.py", line 1753, in close_client
client.shutdown(last_client)
File "D:\Acer\Documentos\Spyder\spyder\spyder\plugins\ipythonconsole\widgets\client.py", line 585, in shutdown
self.shellwidget.shutdown(shutdown_kernel)
File …
```
=> PR: Update RELEASE and MAINTENANCE files and fix some IPython Console issues

spyder/plugins/editor/widgets/base.py
I am not sure why it is necessery to check for the change status on every text change. Upless I am missing something this is not needed.
Fixes #
=> PR: Do not check for change on every keystroke

installers/macOS/setup.py, spyder/utils/installers.py
* Ensured that `jellyfish` is packaged with the macOS installer
* Revised egg-info handling to ensure that dependency checks are not fooled
Fixes #16910
=> PR: Ensure jellyfish is packaged with macOS installer

spyder/dependencies.py, spyder/utils/programs.py, spyder/utils/tests/test_programs.py
- `programs.is_module_installed` was returning `True` for non-installed modules. That regression was introduced in Spyder 5.1.0, specifically in commit d535da2, part of #15657.
- That commit tried to handle the case of `python-lsp-black`, whose module name (`pylsp_black`) if different from its Setuptools distribution one (`python_lsp_black`).
- This PR improves the situation by handling that case better and adding tests for non-installed modules.
- It also removes a blank line before the `Mandatory` section of our dependencies, which was shown when reporting the status of missing dependencies after Spyder starts.
**Before**
**After**
Fixes #16935. …
=> PR: Fix detection of non-installed modules (Dependencies)

spyder/plugins/editor/plugin.py, spyder/plugins/editor/tests/conftest.py
- Spyder was crashing at start-up if Projects is not available, so we need to check for its presence first before trying to use it.
- I also took the opportunity to do the same for some actions that depend on the IPython console.
Fixes #16931.
=> PR: Fix errors when other plugins are not available (Editor)

spyder/plugins/application/container.py
Move always the dpi message dialog to the primary screen to prevent loosing track of it when disconnecting screens while the machine is suspended 
Fixes #16390 
=> PR: Move DPI change message dialog to the primaryScreen center

spyder/plugins/editor/widgets/tests/conftest.py, spyder/plugins/editor/widgets/tests/test_codeeditor.py, spyder/plugins/editor/widgets/tests/test_goto.py, spyder/widgets/mixins.py
- This was broken after #16864.
- Add a regression test for that method so it doesn't break in the future.
- Do some cleanup for the CodeEditor tests.
=> PR: Fix get_text_with_eol for files with CRLF line endings

spyder/plugins/editor/widgets/editor.py
Floats are not automatically cast to ints in Python 3.10, so we need to do it manually.
Fixes #16960.
=> PR: Cast floats to ints in tab switcher (Editor)

spyder/app/tests/test_mainwindow.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/main_widget.py
- This is the option
- It probably broke in #16324.
- I added a test for it so we can be sure it doesn't break in the future.
=> PR: Fix option to maintain focus on editor after running cells or selections

spyder/locale/de/LC_MESSAGES/spyder.po, spyder/locale/es/LC_MESSAGES/spyder.po, spyder/locale/fa/LC_MESSAGES/spyder.po, spyder/locale/fr/LC_MESSAGES/spyder.po, spyder/locale/hr/LC_MESSAGES/spyder.po, spyder/locale/hu/LC_MESSAGES/spyder.po, spyder/locale/ja/LC_MESSAGES/spyder.po, spyder/locale/pl/LC_MESSAGES/spyder.po, spyder/locale/pt_BR/LC_MESSAGES/spyder.po, spyder/locale/ru/LC_MESSAGES/spyder.po, spyder/locale/spyder.pot, spyder/locale/uk/LC_MESSAGES/spyder.po, spyder/locale/zh_CN/LC_MESSAGES/spyder.po, spyder/plugins/ipythonconsole/widgets/main_widget.py
- Fix `format` usage for some translated IPython Console strings.
- Update translations `*.po` files.
=> PR: Update translations for 5.2.1

conftest.py, spyder/api/plugin_registration/registry.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/appearance/confpage.py, spyder/plugins/appearance/plugin.py, spyder/plugins/appearance/tests/__init__.py, spyder/plugins/appearance/tests/test_confpage.py, spyder/plugins/completion/plugin.py, spyder/plugins/editor/plugin.py, spyder/plugins/help/plugin.py, spyder/plugins/help/widgets.py, spyder/plugins/history/widgets.py, spyder/plugins/maininterpreter/tests/test_confpage.py, spyder/plugins/preferences/api.py, spyder/plugins/preferences/plugin.py, spyder/plugins/preferences/tests/conftest.py, spyder/widgets/mixins.py
- Show a restart message whenever there is a mismatch between the selected UI theme and color scheme in preferences. That functionality broke in #16012.
- Fix observers that need to react to changes in color scheme. This was not working as expected for all plugins that need it (i.e. editor, help, history and IPython console).
- Add tests for the Appearance config page so its UX to change color schemes and UI themes doesn't break yet again (that UX is tricky to get right).
- In Preferences, don't add `section` to changed and restart options when it is `None`. This allow us to send the set of changed options to plugins in the same way as before #16012 was merged (not only Appearance but several other things were broken due to that).
- Cleanup unused imports.
By submitting this Pull Request …
=> PR: Fix changing color scheme and UI theme (Appearance)

.github/workflows/installer-macos.yml, .github/workflows/test-mac.yml
Seems like by default now `macos-latest` is MacOS 11
=> PR: Update CI workflows to use macOS 10.15

spyder/plugins/completion/providers/kite/provider.py
- Since Kite is not unsupported anymore, there's no need to keep showing that dialog.
- Besides, that dialog wrongly leads users to think that Spyder still works with Kite.
Fixes #16744
=> PR: Don't show Kite dialog the third time Spyder starts

NOTICE.txt
`NOTICE.txt` is suffering from bit-rot; it hasn't been updated as files were removed (or, in at least the one case I accidentally found, added) to Spyder.
I have checked that every listed file is still valid, and gone through the git history to locate the fate of those files which are not in the current (5.x) version.  Some of them have been removed, some have been renamed, and in two cases, there was just a typo in the filename in `NOTICE.txt`.
I have addressed each change or group of changes in a separate commit on this branch, mostly one commit per original commit, and noted the original commit date and hash in the new commit messages.  Every file listed in the resulting version of `NOTICE.txt` in this PR is present in the current 5.x branch.
By submitting this Pull Request or typing …
=> PR: Many updates to third party file lists in NOTICE.txt

spyder/plugins/ipythonconsole/widgets/main_widget.py
- Now we show the path of the interpreter that doesn't have the right version of spyder-kernels in the message.
- This way users will know where they have to update/install spyder-kernels for the IPyhotn console to work again.
**Before**
**After**
Fixes #17027 
=> PR: Improve message about missing spyder-kernels (IPython console)

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/README.md, external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py, external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
- Those warnings don't provide valuable information and only pollute the console.
- Depends on spyder-ide/spyder-kernels#350
Fixes #14928.
=> PR: Don't print DeprecationWarning's that come from comm handlers (IPython console)

spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/ipythonconsole/widgets/client.py, spyder/plugins/ipythonconsole/widgets/shell.py
- This is necessary to show errors when setting the Matplotlib backend after the kernel restarts, among other things.
- Part of spyder-ide/spyder-kernels#347.
=> PR: Reconfigure client before a kernel restart (IPython console)

spyder/plugins/ipythonconsole/widgets/client.py
There's no need to display those errors (as the one shown below) because it gives the impression that something is wrong in the console, when that's not really the case.
Fixes #17026.
=> PR: Avoid showing bening kernel errors in console banner (IPython console)

spyder/plugins/editor/confpage.py, spyder/plugins/editor/plugin.py, spyder/plugins/editor/tests/conftest.py, spyder/plugins/editor/tests/test_plugin.py, spyder/plugins/editor/widgets/codeeditor.py, spyder/plugins/editor/widgets/editor.py, spyder/plugins/editor/widgets/tests/test_bookmarks.py, spyder/widgets/mixins.py
- This functionality, along with changing EOLs from the `Source > Convert end-of-line characters` menu was broken.
- Add regression tests so it doesn't break in the future.
- Improve text and combobox options related to that.
**Before**
**After**    
Fixes #17045.
=> PR: Fix setting EOL characters when the user decides their preferred ones in Preferences

spyder/plugins/completion/container.py, spyder/plugins/completion/plugin.py
Interacting with completion checkbox preferences related with enabling completion providers (checking/uncheking them leaving them in the same initial state) can lead to trying to register/unregister already register/unregister completion status bar widgets.
Fixes #16997
=> PR: Add validation for registration/unregistration of completion provider status bar widgets

spyder/plugins/pylint/tests/test_pylint.py
- Running
pytest spyder/plugins/pylint/tests/test_pylint.py
was failing because it required a `QApplication` to be present before importing the Pylint plugin.
- I also improved those tests a bit by making them clearly visible while running.
Fixes #17071.
=> PR: Make Pylint plugin tests run independently from the rest in our test suite

setup.py, spyder/plugins/ipythonconsole/widgets/shell.py
Fixed the traitlets DeprecationWarning raised by `spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py::test_banners`.  The unit test should no longer raise a warning after this change.
Fixes #14534 with thanks to @dalthviz 
I affirm the [Developer Certificate of Origin](https://developercertificate.org),
=> PR: Fix traitlets deprecation warning

spyder/plugins/explorer/widgets/utils.py
See commit message for details.
PS: The same action in right-click menu of editor’s tabs is possibly affected as well.
rear1019
=> PR: Fix "Show in external file explorer" for non-existing file (Windows)

spyder/plugins/editor/plugin.py, spyder/plugins/editor/tests/test_plugin.py
Rework cursor position history
Current cursor history loops through the entire history at each cursor position change. This PR avoids that.
Fixes #
=> PR: Improve cursor position history (Editor)

spyder/plugins/pylint/tests/test_pylint_config_dialog.py
…py as well
The issue #17071 turns out to also affect `test_pylint_config_dialog.py`, leading to intermittent segfaults and other tests possibly failing.  This PR applies the same patch as #17074 (which was against `test_pylint.py`) to this other Pylint test.
Fixes #17071 (or its doppelganger!)
=> PR: Make Pylint config page test run independently from the rest in our test suite

spyder/api/widgets/main_widget.py, spyder/app/tests/test_mainwindow.py, spyder/plugins/console/plugin.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/ipythonconsole/widgets/main_widget.py
- Give focus to its focus widget after it's made visible (and do the same for the Internal console).
- Don't switch to it after running cells if the `focus_to_editor` option is `True`.
- Remove `sig_editor_focus_requested` because it was not used.
- Add regression tests for these changes.
Fixes #17028.
=> PR: Fix a couple of focus issues with the IPython console

spyder/plugins/editor/panels/scrollflag.py, spyder/plugins/editor/widgets/codeeditor.py
If there are too many flags in the document, the flags will slow down the printing. This disables the flags of a type if there are more than 10000.
To reproduce, create a file with:
```
with open("test.py", "w") as f:
for i in range(10000):
f.write("aaaaaa\n")
```
This will create 10000 error flags, which will slow down spyder significantly
Fixes #
=> PR: Limit the number of flags in the editor

spyder/plugins/maininterpreter/widgets/tests/test_status.py, spyder/utils/tests/test_conda.py, spyder/utils/tests/test_pyenv.py
This patch skips the remaining tests which rely on the presence of pyenv or conda, in the same way that #17067 was fixed in PR #17092.
(I never reported this as an issue; I just skipped them on the Debian side.)
=> PR: Skip conda and pyenv tests if these tools are not present

spyder/app/tests/test_mainwindow.py, spyder/config/lsp.py, spyder/dependencies.py, spyder/plugins/completion/providers/languageserver/provider.py, spyder/plugins/editor/widgets/tests/assets/yapf_range.py, spyder/plugins/editor/widgets/tests/assets/yapf_result.py, spyder/plugins/editor/widgets/tests/test_formatting.py, spyder/plugins/editor/widgets/tests/test_warnings.py
- We were not using `autopep8` for formatting when selected but `black`. That happened because we were not disabling the `black` PyLSP plugin correctly, so this one was taking precedence.
- This also fixes more failing tests for Python 3.10 and the latest version of Yapf in our test suite.
Fixes #17102
Fixes #17101 
Fixes #17100
=> PR: Fix autopep8 formatting and more failing tests

spyder/app/tests/test_mainwindow.py, spyder/plugins/explorer/plugin.py, spyder/plugins/explorer/widgets/explorer.py, spyder/plugins/explorer/widgets/main_widget.py
- This was broken due to a couple of wrong signal signatures. 
- Add a test to avoid regressions in the future.
Fixes #17129.
=> PR: Fix renaming files in the editor after the folder that contains them was renamed in Files

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
It seems this is caused because a column's dtype is reported as numeric and yet ends up with string and float data on it.
Fixes #17145.
=> PR: Catch error when computing the max of a dataframe column (Variable Explorer)

.github/workflows/installer-win.yml
- The problem is its latest release (1.5.0) doesn't have wheels per Python version. So we have to do some workarounds to avoid an error caused by that.
- I'm not really sure if this is the right fix, but it seems to work.
=> PR: Fix error with PyNaCl (Windows installer)

external-deps/spyder-kernels/.github/workflows/linux-tests.yml, external-deps/spyder-kernels/.github/workflows/macos-tests.yml, external-deps/spyder-kernels/.github/workflows/windows-tests.yml, external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/requirements/posix.txt, external-deps/spyder-kernels/requirements/python-27.txt, external-deps/spyder-kernels/requirements/windows.txt, external-deps/spyder-kernels/setup.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- This was fixed in ipython/ipykernel#830, part of IPykernel 6.6.1
- We now run `test_tk_backend` on Windows because it works.
- Depends on spyder-ide/spyder-kernels#360.
Fixes #17024
=> PR: Fix hang when setting the Tk backend on Windows (IPython console)

spyder/plugins/ipythonconsole/widgets/client.py
- The restart was not happening because there is some benign content written to the kernel stderr file, which caused aborting the restart.
- This could fix a similar problem for the Mac app.
Fixes #17042.
=> PR: Fix kernel restart for the Windows app (IPython console)

spyder/plugins/editor/panels/indentationguides.py
This error only appears on Python 3.10 because we were trying to automatically cast a float to an int.
Fixes #17159.
=> PR: Convert to int variable used to paint indent guides (Editor)

spyder/api/widgets/status.py
Missing parent for some widgets inside the base `StatusBarWidget` and `BaseTimerStatus` classes where causing some extra windows to pop-up
Fixes #16676 
Supersedes #17171 
=> PR: Add missing parent param to QObjects/QWidgets on the status bar base classes

.github/workflows/installer-win.yml
Adds a validation for previous installations with the Windows installer. Before launching the installer a validation for an old installation is run. If an old installation is detected a messagebox appears to ask the users if they want to launch the uninstaller:
Clicking Sí/Yes:
Depends on https://github.com/spyder-ide/windows-installer-assets/pull/6 and a new release (0.0.5)
Note: After the uninstall the installer needs to be relaunched to do the install
Fixes #17025 
I certify the above statement is true and …
=> PR: Update Windows installer assets URL to add previous installation validation

spyder/app/mainwindow.py, spyder/plugins/console/plugin.py, spyder/plugins/help/plugin.py, spyder/plugins/help/widgets.py, spyder/plugins/ipythonconsole/plugin.py, spyder/plugins/shortcuts/plugin.py
- This preserves the window layout left by users in previous sessions, instead of imposing our own.
- Move hiding the Internal console when not in development to its `on_mainwindow_visible` method.
- Remove an unnecessary slot in the Help pane.
Fixes #15331.
=> PR: Raise Help and IPython console to be visible only the first time Spyder starts

spyder/plugins/explorer/widgets/explorer.py
This is a small improvement to allow users quickly see the full path name in those panes, in case it's not clearly visible in the pane itself.
=> PR: Show tooltip with full path name in Files and Projects

spyder/app/tests/test_mainwindow.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
=> PR: Do not test for leaks on Windows to avoid tests stall

external-deps/spyder-kernels/.gitrepo, external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
- Depends on https://github.com/spyder-ide/spyder-kernels/pull/370
Fixes #
=> PR: Test that the debugger handles the namespace of a comprehension

.github/scripts/install.sh, installers/Windows/req-extras-pull-request.txt, installers/macOS/req-extras.txt, spyder/plugins/editor/panels/linenumber.py, spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py, spyder/plugins/onlinehelp/tests/test_pydocgui.py, spyder/widgets/calltip.py
- Some of these errors appeared after PR #17133.
- The other one was mentioned in https://github.com/spyder-ide/spyder/issues/17120#issuecomment-1023869160}
- Skip a couple of tests that started to hang on Linux.
- Avoid using Black 22 on CIs and installers because pylsp-black is not compatible with it.
Fixes #17130.
=> PR: Fix more type errors in Python 3.10 and also tests

spyder/plugins/editor/widgets/editor.py
Fixes the issue with the file name label not being updated when
the last tab is closed in the editor.
Fixes #17221 
I certify the above statement is true and correct: Ajax-Light
=> PR: Fix label update when creating an untitled file after no other file is open

README.md, setup.py, spyder/app/tests/spyder-boilerplate/setup.py, spyder/requirements.py
- The minimal Python version we require now is 3.7 (3.6 reached end-of-life last December).
- For PyQt we now require 5.9 and for PySide 5.12
Fixes #16971.
=> PR: Increase required versions for Python and PyQt/Pyside

spyder/dependencies.py
This avoids an error in the Mac app tests until we release a new, stable version of Spyder-kernels 3.
=> PR: Skip Spyder-kernels check for now (Dependencies)

spyder/plugins/ipythonconsole/widgets/shell.py
This is a follow-up on https://github.com/jupyter/qtconsole/pull/512
| before | This PR + https://github.com/jupyter/qtconsole/pull/512 + ipython/ipython#13372 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4623504/144723007-a31a0bc3-c461-4e63-8813-6df89399eeab.png) | ![image](https://user-images.githubusercontent.com/4623504/144722989-bb56e8a4-2e53-431d-a219-66e692bc57ce.png) |
Fixes #14895
Fixes last comments (non-sympy) in #3798
=> PR: Override RichJupyterWidget._get_color() because we use a custom style (IPython console)

.github/workflows/installer-win.yml, installers/Windows/installer.py, installers/Windows/req-extras-pull-request.txt, installers/Windows/req-extras-release.txt
* See https://github.com/spyder-ide/windows-installer-assets/pull/7 (depends on that and a new tag -> 0.0.6)
* Remove constraints for numpy and black
=> PR: Stop copying black dist-info when building Windows installers and update constraints for numpy and black

spyder/plugins/variableexplorer/widgets/dataframeeditor.py
It seems this was caused by an implicit conversion of float to int.
Fixes #17361.
=> PR: Fix bug when viewing Dataframes in Python 3.10 (Variable Explorer)

spyder/app/mainwindow.py, spyder/plugins/projects/plugin.py
- An error in the logic to decide how to load the previous session prevented that, if Projects was disabled, we didn't load any session at all.
- Fix the title of the Projects plugin. It was named as `Project` but I think it should be `Projects`.
Fixes #17360 
=> PR: Load previous session if Projects is disabled
